### ISSUE TITLE
Operators not correct

### ISSUE THREAD

**Issue by pappasa** [dotnet/docs#10046]
Change:
"Please enter a number between 1 and " + MaxNumber 
To:
"Please enter a number between 1 and " & MaxNumber 

Change:
Guess == Target 
To:
Guess = Target  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaccd5b7-81e5-b850-2764-6a37911bce6d
* Version Independent ID: e937ff92-5e6d-f54a-3ec1-0f1073571aa8
* Content: [How to: Create a Flowchart Workflow](https://docs.microsoft.com/en-us/dotnet/framework/windows-workflow-foundation/how-to-create-a-flowchart-workflow)
* Content Source: [docs/framework/windows-workflow-foundation/how-to-create-a-flowchart-workflow.md](https://github.com/dotnet/docs/blob/master/docs/framework/windows-workflow-foundation/how-to-create-a-flowchart-workflow.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mikkelbu** [comment]
Hi @pappasa. I think the code is correct C# as it is. The binary `&` operator in C# is the logical bitwise AND of the operands. You change change the examples from C# to VB in the upper right corner on the page (sorry about the size, but it is due to my screen resolution)
![image](https://user-images.githubusercontent.com/1007631/51406392-52668300-1b59-11e9-8489-b0141bad07cc.png)
If you change to VB then the examples will look as you propose above.

**Comment by mairaw** [comment]
Thanks @mikkelbu for your comment and @pappasa for your feedback. I think @mikkelbu's comment solves the issue so I'll be closing this but please let us know if we misunderstood something.
Also, our engineering team is going to be revisiting the page UI to see if we can make the language switcher more discoverable.
