### ISSUE TITLE
Custom exception skip or handle?

### ISSUE THREAD

**Issue by LambertWM** [dotnet/docs#10063]
The documentation is fine, but I am distracted by the philosophy behind the exception “handling” in the example code: it seems the author wants to do something when a custom exception is detected (?) but proceeds to rethrow the first exception that is not a custom exception? (thus missing subsequent custom exceptions). And: sometimes the aggregate exception is thrown, and sometimes the inner exception? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25bdb110-7ada-3817-bc40-9c11cab6513c
* Version Independent ID: 9476dc46-d4f0-e7f4-c21e-faaafe0433ea
* Content: [Exception Handling (Task Parallel Library)](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/exception-handling-task-parallel-library)
* Content Source: [docs/standard/parallel-programming/exception-handling-task-parallel-library.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/exception-handling-task-parallel-library.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
@rpetrusha assigning this to you as you are listed as the author. Perhaps you can explain the code and determine if it can be enhanced or clarified?

**Comment by rpetrusha** [comment]
Thanks for your feedback, @LambertWM. I think that there are several problems in the article:
-  The example is constrained to throwing a CustomException, but rethrows any unexpected exception. Rethrowing in turn stops execution of the foreach statement, so that any additional exceptions are not processed. It's reasonable for the code to handle unexpected exceptions; handling an exception in an `if` statement without a corresponding `else` statement seems unwise. But in the context of the example it would be preferable to display a message to the console. This is an issue that applies not only to the examples here, but to examples in the API documentation as well.
 - The examples could use more explanation. 
 - Rethrowing an AggregateException rather than individual exceptions that can't be handled makes sense in some contexts, but the documentation doesn't make it clear how that `throw ae.Flatten` differs from `throw` or `throw ae`.

I'll schedule some time to address these issues in a future sprint.

**Comment by Thraka** [comment]
@rpetrusha 
With the code in the first sample, if the first exception is not a `CustomException`, it will just rethrow and exit. I think the `throw` needs to be outside of the `foreach`
```csharp
          foreach (var e in ae.InnerExceptions) {
              // Handle the custom exception.
              if (e is CustomException) {
                  Console.WriteLine(e.Message);
              }
              // Rethrow any other exception.
              else {
                  throw;
              }
```
