### ISSUE TITLE
clrver is not available in Developer Prompt VS2017

### ISSUE THREAD

**Issue by theking2** [dotnet/docs#10092]
D:\Program Files (x86)\Microsoft Visual Studio\2017\Community&gt;clrver
'clrver' is not recognized as an internal or external command,
operable program or batch file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85e3c15d-854a-3ec5-66c2-efe819b722fc
* Version Independent ID: e441033f-e213-4f17-cbb9-016e2c4326dd
* Content: [Clrver.exe (CLR Version Tool)](https://docs.microsoft.com/en-us/dotnet/framework/tools/clrver-exe-clr-version-tool)
* Content Source: [docs/framework/tools/clrver-exe-clr-version-tool.md](https://github.com/dotnet/docs/blob/master/docs/framework/tools/clrver-exe-clr-version-tool.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Hi @theking2! Before we can investigate this, can you please let me know if you typed clrver from inside a Developer Command Prompt for Visual Studio window instead of just regular command prompt?

This is what I get with a regular prompt:
![image](https://user-images.githubusercontent.com/12971179/51572192-7bd52680-1e59-11e9-8caa-fc05a9e216a0.png)

This is what I get from inside the VS prompt:
![image](https://user-images.githubusercontent.com/12971179/51572209-8bed0600-1e59-11e9-9385-94f225d9ec34.png)

**Comment by theking2** [comment]
![image](https://user-images.githubusercontent.com/1612152/51660621-a258a600-1fae-11e9-8506-3407413cd7ca.png)


![image](https://user-images.githubusercontent.com/1612152/51660603-9371f380-1fae-11e9-9040-db81b3bc344b.png)

**Comment by mairaw** [comment]
Thanks for replying. We'll need to investigate what's going on. I added this to our backlog for now.

**Comment by mtttcgcg** [comment]
I had to open the Developer command prompt with Admin rights to avoid this error.
