### ISSUE TITLE
Handling deletes in POCO

### ISSUE THREAD

**Issue by maxiptah** [dotnet/docs#10095]
In your AddOrderItem you add OrderItem to a relationship. How do you handle deletes in a pure POCO class? Should Order *always* load related order items in repository during Get()? This might result in transfering lots of unnecessary data from DB. Should I use LazyLoader like here https://docs.microsoft.com/en-us/ef/core/querying/related-data? This would work, but break the persistance ignorance principle. Any guidance is really appreciated.
In fact adding an *existing* item via ID already would cause an exception during saving.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49c9fdb0-f078-2030-204d-67d016b22c8d
* Version Independent ID: 43bd7af4-f92e-f866-6725-b3c1b4e6afdb
* Content: [Implementing a microservice domain model with .NET Core](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/net-core-microservice-domain-model)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/net-core-microservice-domain-model.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/net-core-microservice-domain-model.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by rpetrusha** [comment]
//cc @mvelosop

**Comment by mvelosop** [comment]
Hi @maxiptah, that's a good question!

Removing items from an Order in eShopOnContainers is not implemented and would be a bit complex, because I guess you wouldn't want to remove the item directly from the DbContext.OrderItems property, which would be the simplest.

So I'll use a simpler example, more similar to what's usually done.

Imagine you have a `Project` entity that has a `IList<Activity>` collection and the usual navigation and foreign key properties (`Activity.Project` and `Activity.ProjectId`)

When you remove an `activity` from the project (using `Project.Activities.Remove(activity)`), the `activity.Project` navigation property is nullified, and you can use that to mark the activity for deletion on the DbContext, right before saving, by overriding the `SaveChangesAsync` method like this:

```csharp
public override Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
{
    var removedActivities = ChangeTracker.Entries<Activity>()
        .Where(e => e.Entity.Project == null)
        .Select(e => e.Entity);

    RemoveRange(removedActivities);

    return base.SaveChangesAsync(cancellationToken);
}
```

Achieving the above in `OrderItem` would be similar, except the navigation/FK properties don't exist in the POCO class, so you'd have to go to the `DbEntityEntry` class that has equivalent properties that would allow you to do that. But that's much more convoluted.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue as answered/stale, but fell free to comment, will reopen if needed.
