### ISSUE TITLE
acknowlegement

### ISSUE THREAD

**Issue by Joebass12** [dotnet/docs#10170]
[Enter feedback here]
the tutorial is a nice one
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 756e4425-16b0-abfd-1e5a-927f07a8af69
* Version Independent ID: 040f0373-5f32-5132-2e26-adf03e4d6100
* Content: [Introduction to C# - interactive tutorials](https://docs.microsoft.com/en-gb/dotnet/csharp/tutorials/intro-to-csharp/index)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/intro-to-csharp/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for your feedback @Joebass12. 

For your MySQL database question, I don't believe we cover that in our docs since it's a third-party database, but you can find information regarding MySQL and .NET in the following pages:
- https://dev.mysql.com/doc/connector-net/en/connector-net-introduction.html
- https://stackoverflow.com/questions/21618015/how-to-connect-to-mysql-database 
- https://www.codeproject.com/Articles/43438/Connect-C-to-MySQL
