### ISSUE TITLE
Pictures PLEASE!

### ISSUE THREAD

**Issue by doctordns** [dotnet/docs#10180]
This page and sub-pages really, really, really need diagrams. For someone just getting into Windows.Forms. seeing pictures of the different controls diagramming the setting of key controls. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecb313b6-34aa-6333-3228-4f66b10ceb3b
* Version Independent ID: f030777f-896e-2e9b-e347-0c600229243a
* Content: [Windows Forms Controls Used to List Options](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/windows-forms-controls-used-to-list-options#feedback)
* Content Source: [docs/framework/winforms/controls/windows-forms-controls-used-to-list-options.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/controls/windows-forms-controls-used-to-list-options.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
That's good suggestion @doctordns and we try to add them to our beginner's material nowadays. This article wouldn't apply to that though since it's not a step-by-step procedure, just a list of articles.
Since it's a broad suggestion and not applicable to this particular article, I'm closing this one but it's something that we pay attention to.
