### ISSUE TITLE
certificateValidationMode value options description

### ISSUE THREAD

**Issue by bugaevski** [dotnet/docs#10182]
I will be nice to have more details on the options - what exactly expect from these:
None||ChainTrust||PeerTrust||PeerOrChainTrust ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523e6933-c7de-abf0-d99f-00816614dbea
* Version Independent ID: 80d02ba7-8cec-bd8b-779e-ecd9c825f193
* Content: [&lt;certificateValidation&gt;](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/windows-identity-foundation/certificatevalidation)
* Content Source: [docs/framework/configure-apps/file-schema/windows-identity-foundation/certificatevalidation.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/windows-identity-foundation/certificatevalidation.md)
* Product: **dotnet-framework**
* GitHub Login: @BrucePerlerMS
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for your feedback, @bugaevski. The documentation notes that these are X509CertificateValidationMode values and provides a link to the [X509CertificateValidationMode](https://docs.microsoft.com/dotnet/framework/configure-apps/file-schema/windows-identity-foundation/certificatevalidation) documentation that provides more details.

I'll close this issue, since I think that the information available from following the link answers your question.
