### ISSUE TITLE
**Remove calls to HashAlgorithm.ComputeHash**

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#10206]
Calls to [HashAlgorithm.ComputeHash](https://docs.microsoft.com/dotnet/api/system.security.cryptography.hashalgorithm.computehash) should be removed from the documentation.

**Comment by tdykstra** [comment]
@bartonjs 

* What's the reason for removing calls to `HashAlgorithm.ComputeHash`?
* Calls to `ComputeHash` in code examples are for specific algorithms -- does this mean we want to remove all calls to `ComputeHash` for all algorithms?
* Does "remove calls ... from the documentation" mean delete any snippets that contain such calls? Or keep the snippets but replace the `ComputeHash` calls with something else?

**Comment by bartonjs** [comment]
I'm... not sure.

`ComputeHash` is the preferred API to use on `HashAlgorithm`... anything that uses TransformBlock or TransformFinalBlock should be rewritten to use `IncrementalHash`.

My best guess is it was meant for MD5/SHA1, but since the member lives on HashAlgorithm it ended up being collapsed down to HashAlgorithm.

I think my recommendation here is to close it as non-actionable/lost-context.
