### ISSUE TITLE
**Review SignedXML, SignedCMS**

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#10210]
@bartonjs, my notes don't indicate what the precise work item is here. Can you help?

**Comment by mairaw** [comment]
Pinging @bartonjs on this again so you guys can know exactly what needs to be done for this issue

**Comment by bartonjs** [comment]
I don't really remember any specifics of what we were going for.  Probably making sure samples are using modern algorithms (Aes instead of TripleDES or Rijndael; SHA256 instead of SHA1 or MD5) and making sure that SignedXml docs and samples are all consistent on messaging for concerns with https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.xml.signedxml?view=netframework-4.8#are-the-reference-values-safe-from-tampering (and the rest of the remarks beyond that point).

**Comment by tdykstra** [comment]
Closing per discussion with @baartonjs on 6/25.  

> making sure samples are using modern algorithms (Aes instead of TripleDES or Rijndael; SHA256 instead of SHA1 or MD5) 

Already covered by #10198 and #10199

>making sure that SignedXml docs and samples are all consistent on messaging for concerns with https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.xml.signedxml?view=netframework-4.8#are-the-reference-values-safe-from-tampering (and the rest of the remarks beyond that point).

Incorporating into #10211
