### ISSUE TITLE
nunit is not recognized a template

### ISSUE THREAD

**Issue by MattDillard** [dotnet/docs#10230]
When I run `dotnet new nunit`, I get the following error:

    No templates matched the input template name: nunit.

I have .NET Core SDK 2.1.300 (so says `dotnet --version`). Is this template not actually shipped with that SDK after all?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b952f8a-18e1-4843-0741-6ca877fb303a
* Version Independent ID: d80dfb96-bc86-a960-abec-255dd907d04d
* Content: [dotnet new command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-new.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-new.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by jr549** [comment]
Yeah been working with .Net Core 3.1 and still quite baffled by all of the errors and warnings I get when I use xunit, dotnet new xunit. It creates the project and test file but on restore is goes haywire. I checked the nuget.config and the 2 sources look as expected. I am not even sure where the xunit template is coming from since it is not in the sdk folder. I since added it to the .nuget/packages folder using the nuget download, version 2.4.0 but still get numerous errors. It is like things are out of sync.
