### ISSUE TITLE
Call out thread-safety for access to static class members

### ISSUE THREAD

**Issue by michael-hawker** [dotnet/docs#10244]
It'd be great if this article could also touch on thread-safety when accessing static members; I assume similar to the static class constructor, it will only be initialized at most once.  But it'd be nice to have that called out here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f20db0d-ef5c-d8e7-2267-0f409c499e0f
* Version Independent ID: de2dac73-e810-dd42-f518-e50926b3747f
* Content: [Static Classes and Static Class Members - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/static-classes-and-static-class-members)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/static-classes-and-static-class-members.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/static-classes-and-static-class-members.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for raising this issue @michael-hawker 

There is no language level guarantee on thread synchronization for static methods. Whether or not a static method is thread safe depends on the code in the static method. If the static method does not mutate shared data, it would be thread safe. However, any access to shared data would need to be synchronized.

Because there isn't a language guarantee here, we've avoided making any statement because there isn't language guarantee about thread safety for static methods. Any given static method may be thread safe. Or, it may not be. That can only be known by understanding the implementation of the method.

**Comment by michael-hawker** [comment]
Thanks @BillWagner, I understand that I can always put unsafe code somewhere that does silly things. :)

It's just helpful to know if the underlying construct is thread-safe and is only going to be able to be entered once or if I need to worry about mutexing around initializing/accessing the member or not.

**Comment by BillWagner** [comment]
After some internal review and discussion, I'm closing this.  There's nothing useful that we can say about static methods and thread safety. Anything would depend on the code in the method, and where the method is called, and the context where it's called.
