### ISSUE TITLE
Add information for .net core 2.1 and .net framework 4.7.2

### ISSUE THREAD

**Issue by nicoleta-scrimint** [dotnet/docs#10262]
Hi,
Could you please include information for the version of .net standards supported for .net core 2.1 and .net framework 4.7.2?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb8b774-c6f0-8235-6964-15219baf2ea7
* Version Independent ID: 6819a4a7-7527-d8c7-e132-767f7344e00e
* Content: [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)
* Content Source: [docs/standard/net-standard.md](https://github.com/dotnet/docs/blob/master/docs/standard/net-standard.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by nicoleta-scrimint** [comment]
I saw a closed issue and I understand that the table The lists the minimum platform versions that support each .NET Standard version. Thus .net standards 2.0 should be supported by .net core 2.1 and .net framework 4.7.2. From this table, should I understand that .net standards 2.1 has not a minimum platform version to support yet?

**Comment by rpetrusha** [comment]
Thanks for your feedback, @nicoleta-scrimint. .NET Standard has not yet been finalized and has not been released, so it is not documented; the latest version of .NET Standard is still 2.0.

Since the table lists the minimum supported versions of .NET Core and .NET Framework, .NET Standard 2.0 is implemented by .NET Core 2.0 and all later versions (i.e., .NET Core 2.1, .NET Core 2.2, and the preview version of .NET Core 3.0; similarly, .NET Core 2.0 is implemented by .NET Framework 4.6.1 and later versions (4.6.2, 4.7, 4.7.1, and 4.7.2). 
Since I think that this answers your question, I'll close this issue. Feel free to reopen it if you disagree.
