### ISSUE TITLE
Class access modifiers missing

### ISSUE THREAD

**Issue by AndyWDev** [dotnet/docs#10303]
Can we have this updated to include class scope.  I notice the examples given are missing this information (class TestClass and class Child) which could create some ambiguity for new coders.

I would be expecting  public class TestClass or private class Child as examples (with some discussion on what the access modifiers mean).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a86f6ff1-21bf-44ad-f603-e311648929a4
* Version Independent ID: 9b08428b-beba-0f94-6635-73e26d0de446
* Content: [class keyword - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/class)
* Content Source: [docs/csharp/language-reference/keywords/class.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/class.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @AndyWDev 

I agree that we should have samples that cover nested classes. I've added the Concepts label, because I think that content should be in a different section than the language reference. (It should be linked from here).  

I want to keep the language reference as a short, abridged survey of the features. Then rely on the C# spec for details of the rules, and rely on concepts and tutorials for *how* to use the features in practice.
