### ISSUE TITLE
Added information about bound conditions on the foreach loop would be useful

### ISSUE THREAD

**Issue by alaniane** [dotnet/docs#10327]
It would be useful to add information on what happens when the foreach loop is executed on empty list or null object.  I can code to find the answer, but it would be better if the documentation provided it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d710feeb-8f03-b211-a070-155938929d6b
* Version Independent ID: c980ea8e-ffb4-fbb1-1761-292858616cdd
* Content: [C# foreach statement](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/foreach-in)
* Content Source: [docs/csharp/language-reference/keywords/foreach-in.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/foreach-in.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a good suggestion @alaniane 

There are two answers:
- If the source collection is `null`, a `NullReferenceException` is thrown.
- If the source collection is empty, the body of the `foreach` loop is skipped. In other words, all "none" of the elements are enumerated, and execution continues with the next statement.

I've added this to our backlog, and applied the "up for grabs" label. If you'd like to submit a PR, I'll watch for it.  Otherwise, we'll address this when we next update this article.
