### ISSUE TITLE
Question about PR

### ISSUE THREAD

**Issue by badersur** [dotnet/docs#1038]
Do you prefer PRs that span multiple files with few changes or a PR per file?!

**Comment by BillWagner** [comment]
@badersur Great question.  I'll leave this issue open, because we should add it to our contributing.md file.

My initial set of guidance would be that a PR should address one "issue". That may be a single file, or multiple files. 

For example, a PR that changes .NET Core 1.0.0 to .NET Core 1.0.1 might affect several files, but it's a single change.

if you're addressing multiple fixes, separate PRs are preferred.

Thanks again.

**Comment by badersur** [comment]
You are welcome @BillWagner. For now, whenever I face an issue in a file I fix it and submit a PR. I will try to read more files to see if I should include more files in a PR.

**Comment by mairaw** [comment]
I agree with @BillWagner's answer. One issue per PR with one or multiple files is good.

Your method is working well @badersur. We appreciate your contributions so far!
