### ISSUE TITLE
A link to more info on -v option would be helpful

### ISSUE THREAD

**Issue by tdykstra** [dotnet/docs#10418]
Is there a doc we could link to for information on what formats work for specifying version?  For example, how to use wildcards in version numbers.  Also it might be helpful to specify what you get when you omit the -v option -- latest excluding prerelease.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff30b638-44e3-077c-3cad-b61d1314c303
* Version Independent ID: 784413e1-77f5-f2e6-a8f4-56a73fe2d3bf
* Content: [dotnet add package command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-add-package)
* Content Source: [docs/core/tools/dotnet-add-package.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-add-package.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
I found this: 

https://docs.microsoft.com/en-us/nuget/reference/package-versioning#version-ranges-and-wildcards 

It would be nice to add this. Adding it to the backlog and community project.

**Comment by tdykstra** [comment]
@Thraka Are you sure the range formats there work with the -v command line option?  And does the note about wildcards including prerelease apply here too?  This doc may need more than just a link to that doc.

**Comment by Thraka** [comment]
I would think so. I'm pretty sure this just passes the command line on to the nuget command directly (transforming the args to the appropriate names for nuget.exe)

EDIT
I just tried it out and it all worked as expected. I tried the prerelease * and didn't get an error (though its hard to tell what package is selected just because the version in the assembly doesn't specify pure text like `-alpha1`
