### ISSUE TITLE
How do I know...

### ISSUE THREAD

**Issue by tcjohnson71** [dotnet/docs#10434]
...when to use the Mutex and when to use the Semaphore?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51e078fd-3a63-8b58-49f8-67e49df9bc9f
* Version Independent ID: f082f7b2-e1a3-aa31-1081-5ca11c954d80
* Content: [Semaphore and SemaphoreSlim](https://docs.microsoft.com/en-us/dotnet/standard/threading/semaphore-and-semaphoreslim)
* Content Source: [docs/standard/threading/semaphore-and-semaphoreslim.md](https://github.com/dotnet/docs/blob/master/docs/standard/threading/semaphore-and-semaphoreslim.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by tcjohnson71** [comment]
Are they both kernel objects?

**Comment by pkulikov** [comment]
@tcjohnson71 the following section might help you with your first question:
https://docs.microsoft.com/en-us/dotnet/standard/threading/overview-of-synchronization-primitives#synchronization-of-access-to-a-shared-resource

**Comment by rpetrusha** [comment]
Thanks for submitting your question, @tcjohnson71, and thanks for your response, @pkulikov. I think that the article indicated by @pkulikov discusses the difference between a mutex and a semaphore sufficiently. Both are kernel objects, though both have to be assigned names to be used in cross-process operations. The lightweight, non-kernel equivalent to Semaphore is [SemaphoreSlim](https://docs.microsoft.com/dotnet/api/system.threading.semaphoreslim).   

Since I think that this answers your question, I'll close this issue. If you disagree, please feel free to respond.
