### ISSUE TITLE
Enumeration Types PDF download incorrect

### ISSUE THREAD

**Issue by jockster74** [dotnet/docs#10536]
When I download the PDF version of the chapter Enumeration Types, it actually downloads the entire C# Programming Guide. For other chapters the download is chapter-specific.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e72804b0-7d65-1585-67ea-863dc561124e
* Version Independent ID: 188ff9ab-de91-bf6a-d6a5-599389d2a76b
* Content: [Enumeration types - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/enumeration-types)
* Content Source: [docs/csharp/programming-guide/enumeration-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/enumeration-types.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for your feedback @jockster74. This behavior is by design. When you click Download the PDF, it'll download the entire section that you're in. In this case, the C# Programming Guide.

Not sure what you mean about the download being chapter specific. If you can provide an example where you see a different behavior, we can take a look.
