### ISSUE TITLE
What about dotnet publish -r?

### ISSUE THREAD

**Issue by ygoe** [dotnet/docs#10667]
When I publish my application for a fixed runtime with `dotnet publish -r linux-arm`, then are these packages also a dependency or can I just copy my files over and they'll always run?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cfd5cf0-f28e-be49-227a-c2bbe4e57b8d
* Version Independent ID: 016b2a9c-d1c9-6909-df3e-a49db60b7654
* Content: [Prerequisites for .NET Core on Linux](https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x)
* Content Source: [docs/core/linux-prerequisites.md](https://github.com/dotnet/docs/blob/master/docs/core/linux-prerequisites.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by NextTurn** [comment]
`-r` switch creates [Self-contained deployments (SCD)](https://docs.microsoft.com/en-us/dotnet/core/deploying/index#self-contained-deployments-scd).

See also [Self-contained deployment](https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli#self-contained-deployment).

**Comment by Thraka** [comment]
As nextturn said, this will create an SCD, which has all of the dotnet runtime files included. For linux though, I don't believe this copies any of the package dependencies for you, nor would it install them when you ran the app.

**Comment by ygoe** [comment]
Which leads me back to this page. So I know which dependencies I need for each single Ubuntu version, and for CentOS and Fedora in general. But not for anything else, like Debian, Raspbian, Redhat etc. And do I really have to create separate packages for every Ubuntu version? That's huge!

**Comment by ygoe** [comment]
Oops, closed while I was writing my reply. My question isn't answered yet, though, and I'm not allowed to reopen this issue. Should I ask for an improvement of the documentation elsewhere?

**Comment by NextTurn** [comment]
The RID you are using is `linux-arm`, neither `ubuntu-arm` nor `ubuntu.18.04-arm`. I guess the packages should work on any platform.

**Comment by ygoe** [comment]
Then why are there different native dependencies listed for Ubuntu (each version) and Fedora? That all doesn't make any sense to me. Is a self-contained app self-contained or not? Does it have additional dependencies or not? And which exactly? Has anybody ever used that after all?

**Comment by Thraka** [comment]
@ygoe I'll reopen the issue 👍 

I'll see if I can ping someone that can explain it better than I can. Perhaps we can make this clearer in the docs too.

**Comment by mairaw** [comment]
Any updates here @Thraka?

**Comment by Thraka** [comment]
@ygoe This is fixed in a PR from https://github.com/dotnet/cli/pull/11359 but it hasn't been deployed yet. Thank you for reporting the problem.

**Comment by Thraka** [comment]
@ygoe I got a response about this (which I forgot to put in here, sorry) and I was pointed to https://github.com/dotnet/core/blob/master/Documentation/self-contained-linux-apps.md which has some information on how to trim back which dependencies you need.

I don't see where there is a list of different dependencies for each Ubuntu release? Are you talking about for different architectures? (x64 vs ARM32 vs x64 Alpine for example)

Regarding those other distros, I would assume you need to figure out what is in common with the other distros and then that will tell you how many different releases you would need to ensure you package the correct dependencies to run on those distros.

Regarding your other question about self-contained, I guess that may sound misleading. The self-contained feature of `dotnet` is to produce an app along with the runtime that you can distribute as a single "thing." So you don't have to have the user install the runtime globally. 

I'm going to close the issue but we can keep talking if you want. I think your original question is indeed answered, you need to provide the dependencies (use some sort of package manager for distribution for example) for linux distros. And that self-contained is related to the .net core runtime being included with the app instead of requiring the user download and install it globally.
