### ISSUE TITLE
Abridged Reference: builtin value types

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#10726]
This new article will include:

**Simple types**
- bool
- enum

Sub-tasks are:

- [ ] Create the new articles
- [ ] Search for existing issues on content being migrated and consolidated. This is a good opportunity to fix those.
- [ ] Redirect existing content to the new articles.
- [ ] Remove old articles.
- [ ] Update all links in the .NET Content

**Comment by BillWagner** [comment]
There are new types that should be added to this task:

- `System.ValueTuple`
- `System.Index`
- `System.Range`

`ValueTuple` seems to fit nicely with the 'simple types', where "simple" means a value type that's not a single numeric value. `ValueTuple` is required by the 7.0 language and feels "simple".

Both `Index` and `Range` point to a possible new category: ValueTypes required by the language spec. Maybe it's enough to change the name from "simple" to "non-numeric value types". Or put it in the TOC following "numeric types" and label it "other value types".

**Comment by pkulikov** [comment]
@BillWagner it looks that this issue *redefines* what "simple" means. The existing definition is according to the spec:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/value-types#simple-types

> Maybe it's enough to change the name from "simple" to "non-numeric value types". Or put it in the TOC following "numeric types" and label it "other value types".

I think those two approaches are better. First, no need to redefine the current "simple types" notion. Second, would it be fine even not to label it as "other value types", but have the TOC (and articles) as follows:

Built-in value types:
- Numeric types
- bool
- enum
- System.ValueTuple (or just "C# tuples")
- System.Index and System.Range (or just "Indices and ranges")

Another concern: `char`. I know it's inside the numeric types, but it feels weird. Is it worth its own TOC entry and article (with remarks about its relation to `short`)?

**Comment by BillWagner** [comment]
Thanks for the thoughtful comments @pkulikov.  These discussions continue to be a key part of this project's success. Thank you. 🙇 

I agree that we should not use "Simple Types" to mean anything other than the meaning in the language specification.  That's a great point. 

And, one other type we missed in the lists earlier:  `System.Nullable<T>`. That should be in the list above between `enum` and `System.ValueTuple`.

Regarding `char`: Yes, it is unique. It should have its own page.

**Comment by BillWagner** [comment]
The content from the following files should be moved into this new article:

- docs/csharp/language-reference/keywords/built-in-types-table.md
- docs/csharp/language-reference/keywords/default-values-table.md
- docs/csharp/language-reference/keywords/value-types-table.md
- docs/csharp/language-reference/keywords/value-types.md

**Comment by pkulikov** [comment]
@BillWagner should this issue to be renamed to *builtin value types*?
Following the consolidation of the nullable value types articles, I'm thinking about the plan how to make further progress for this issue. Are you interested in it?

**Comment by BillWagner** [comment]
@pkulikov Good point. I renamed it.

I've got a number of tasks that need to happen before I'd work on this issue. If you want to start on a plan, go right ahead. I unassigned myself, and assigned this to you.

If the plan changes, let me know.

**Comment by pkulikov** [comment]
Guiding principles of the plan:

- Revise and move the reference pages about the value types to the `language-reference/builtin-types` folder.
- Revise and move the related code samples to the `/csharp/language-reference/builtin-types/` folder of the samples repo.
- Merge the programming guide articles into the reference articles.

The following plan wouldn't fix this issue completely, but rather consolidate existing docs. There would be one PR per one list item:

- [ ] Revise and move the [char](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/char) article.
- [ ] Revise and move the [bool](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/bool) article. Merge the [true literal](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/true-literal) and [false literal](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/false-literal) articles into the final article.
- [ ] Revise and move the [enum](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/enum) article. Merge the [Enumeration types](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/enumeration-types) article from the programming guide into the revised reference article. The final article can be called "Enumeration types" (instead of "enum").
- [ ] Revise and move the [struct](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/struct) article. Now, it's very short, but there are a lot of info to consolidate here. First, merge in the following articles from the programming guide/concepts: [Structs (C# concepts)](https://docs.microsoft.com/en-us/dotnet/csharp/structs), [Structs (C# programming guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/structs), and [Using structs (C# programming guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/using-structs). A lot of info shared by those articles, so the final merge result might be of the size of one article. That is related to #6179.
- [ ] Second, move various struct kinds into the new "struct" (or "Structure types") article. Those are: [readonly struct](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/readonly#readonly-struct-example) and [ref structs](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/ref#ref-struct-types). That way, all kinds of structure types would be documented in one place.
- [ ] Revise and move the [Value types](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/value-types) article. Merge in the [Value types table](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/value-types-table) and, maybe, [Built-in types table](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/built-in-types-table) (not sure here, as then the bits about `object` and `string` would be lost, but it might be fine).

@BillWagner what do you think? If it sounds like a good plan, I'll start working on that.

**Comment by BillWagner** [comment]
Thanks for reminder on this plan @pkulikov I missed the mention earlier.

This is a great plan. Thanks for documenting the steps so we can track them. 💯

**Comment by pkulikov** [comment]
@BillWagner I'll be back to working on this issue after the holidays, in the middle of January.

**Comment by BillWagner** [comment]
Thanks @pkulikov Enjoy the break. I'm looking forward to continuing our collaboration in the new year.

**Comment by pkulikov** [comment]
@BillWagner as part of the work on this issue, I would also like to move and revise the article about C# tuples (value tuples):
https://docs.microsoft.com/en-us/dotnet/csharp/tuples

I'd move it from the concepts part of the docs/TOC to the language reference part/TOC.
What do you think?

**Comment by BillWagner** [comment]
I like this plan @pkulikov 

It might make sense to trim the section on "discards", and combine it with the article on discards in general.  What do you think?

**Comment by pkulikov** [comment]
@BillWagner what section do you mean?

I've thought about trimming the [section about deconstruction](https://docs.microsoft.com/en-us/dotnet/csharp/tuples#deconstruction) and referencing the [Deconstructing tuples and other types](https://docs.microsoft.com/en-us/dotnet/csharp/deconstruct) article instead.

**Comment by BillWagner** [comment]
Thanks for checking @pkulikov Yes, I typed the wrong word. I think deconstruction will become even more interesting when records are available, and a single article devoted to that topic makes even more sense.
