### ISSUE TITLE
Abridged Reference: operators / bitwise operators

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#10731]
The bitwise operators are:

- `&` (bitwise AND for integral operands)
- `|` (bitwise OR for integral operands)
- `^` (bitwise exclusive-OR for integral operands)
- `~` (bitwise negation)
- `<<` and `>>` (shift operators)
- corresponding compound assignment operators

Sub-tasks are:

- [ ] Create the new articles
- [ ] Search for existing issues on content being migrated and consolidated. This is a good opportunity to fix those.
- [ ] Redirect existing content to the new articles.
- [ ] Remove old articles.
- [ ] Update all links in the .NET Content

**Comment by pkulikov** [comment]
@BillWagner should postfix increment/decrement also be in the list of primary operators? At least, [current section on primary operators] includes them.

**Comment by BillWagner** [comment]
@pkulikov I have those listed in arithmetic operators. I know they are listed as "primary" and have a different precedence. I *think* that made more sense from a search / findability perspective. 

Thoughts?

**Comment by pkulikov** [comment]
I like the idea of putting them into the set of arithmetic operators (I've also missed them in the list of unary operators).

That said, I'm confused by the grouping principle. How are the operators split in sets?

One article for arithmetic operators, another - for logical operators, third one - for relational operators belong to the same family (bitwise operations article is also from this family). So, the principle by which operators are grouped is *type of the operands and the nature of an operation applied*.

The set of primary operators looks to be from completely different family: the one defined by *precedence*. Frankly, I think the current section I've linked is good: it keeps the list of primary operators together with the whole list of operators, providing the grouping principle (precedence) on the same page.

The set of unary operators also looks strange, because it's based on another grouping principle: *number of operands*. However, that set excludes the operators included into other sets, which are built on different grouping principle. The grouping principles are independent, but somehow influence each other.

So, my main concern: what is the principle by which operators are grouped?

There can be several possible ones. Of the same preference/importance, even. Three listed above.

I think it would be great not to mix them. That is, one operator most probably might be assigned to some group within each grouping. Therefore, one operator might be mentioned in three (or more, or less) abridged references. If an operator is put *only* to one set based on *some* grouping, it reads that that grouping is "main" for this operator (for example, the arithmetic operators is the main for `++`). That's hard for findability, because a user must know (or guess), which grouping is the main one for the operator one is searching for. For example, I can imagine somebody searching for `++` in the list of unary operators, not in arithmetic operators, gets frustrated. Not found? OK, let's make a PR to include that operator into the topic :).
