### ISSUE TITLE
Reorganize the operator consolidation

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#10757]
Motivated by https://github.com/dotnet/docs/issues/10731#issuecomment-467576253  Thanks for the review @pkulikov 

The current proposed lists mix organizational strategies.  Their should be a single organizational strategy that accomplishes:

- When a reader searches for an operator, the article includes related operators for similar tasks. (for example, all the arithmetic operators are together, `&&` and `||` are together).
- Browsing a page explains a related set of concepts. (for example, `.` and `?.` should be covered together)
- The operators pages use a single organizational principle (the main motivation for creating this issue).

> Note: we'll use the docs display name functionality to annotate the TOC nodes with the symbols for each operator so if a reader knows the symbol, the page can be quickly located in the "operators" section.

**Comment by BillWagner** [comment]
Assigning `P0` because this must be resolved before work can begin on any of the following issues:

#10731 
#10732 
#10736 
#10738 
#10739 
#10740 
#10741

**Comment by pkulikov** [comment]
A number of observations/alternatives.

> When a reader searches for an operator, the article includes related operators for similar tasks. (for example, all the arithmetic operators are together, `&&` and `||` are together).

I'm trying to do that now when updating individual operator articles: include related operators into the **See also** section. However, it might be a too brief mention. What if we keep the page-per-operator approach and add the **Related operators** section to each page? Would it introduce too much duplication?

I partially like the approach in the Visual Basic TOC:
https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/operators-listed-by-functionality

Not a fan of the only-list-of-links pages, but TOC might be structured in this way, only with leaves being the links to the individual pages.

That way, it's possible to have a TOC per organizational strategy (possible downside - blown up TOC).

It looks that I'm searching for the solution which preserves individual pages, but adds the layer on top. That layer would reference individual pages. For example, what about having an article per organization strategy? C# operators - precedence. C# operators - functionality. I'm not sure if the arity needs its own article, though.

One advantage of having such a layer on top is that it's a change with a lesser impact (no need to remove old articles and setup redirections). That also makes it easier to experiment: no burden to select one strategy now: let's try one and if it doesn't work — ok, let's check another one. Or, as mentioned above, it's possible to publish two different views on operators: those two views are separate, do not depend on each other, but reference the same set of operator articles. And later-later, after observing how it would work out, it's an option to select the one strategy and "inline" operator articles.

**Comment by pkulikov** [comment]
By the way, I'm not extremely against consolidation of individual articles; some consolidation is beneficial and I'm for baby steps in this direction. I think those following, for example, already can be merged (even within current doc structure):
- `==` and `!=` into equality operators article
- `<`, `>`, `<=`, and `>=` into relational operators
- `<<` and `>>` into shift operators

From above, I say I gravitate to *functionality* as organizational strategy. However, some operators might be in a group that contains only one operator, others might be considered belonging to several groups. That's why I think that additional layer on top of individual articles would be helpful: it would allow to mention one operator within different groups.

For example, I think `&` and `|` belong to the logical operators (together with `!`, `^`, `&&`, and `||`... and `true` and `false`) (ok, I assume here that logical operators work only on `bool` operands). At the same time, those two belong to the operators one uses to work with bits (together with `~`, `^`, `>>`, and `<<`) (and applied to integral operands). Two sections (or maybe articles) describing each group would be useful.

However, the individual article on `&` is still useful, because it supports the following scenario: "Hm... I see the symbol in the code. What does it mean? Please, give me all the information about this symbol". The current doc structure supports that scenario: the plain one-level operators TOC is useful when searching for a symbol, which meaning is unknown. I think this scenario still should be supported. In particular, that means that an operator (symbol) should be fully covered in one article. Therefore, an existing individual operator article should never be split, but fully merged into another article, if such a merge is necessary.

When to merge? I would say, If a new article has still *only* one clear topic. That's why `==` and `!=` go in together well, but `&` and `|` are not so well. Each of the `&` and `|` is already about several things, so merging them into one would increase a number of topics in one article, might make that merged article complex.

Talking about existing structure and the use case it supports (and, I assume, still should support), there is another use case, which is not supported now and I think all the new issues about abridged references target fixing that use case. That is, "OK, I know what this symbol means. Where is it usually used? What other operators do typically go with this one?", or "I want to do some math with numerics: what are the available operators?", or "I want to play with bits: what can I do?". Again, I'm for additional *overview* reference to cover this use case: it allows mentioning the same symbol in different contexts and also some operators might be completely omitted from those overviews if they don't fit any; at the same time they still would appear in the good-old-plain-TOC and would be searchable. It's kind of top-down, helicopter-view approach. It's complimentary to the bottom-up approach, which is now in the docs on operators. And I think both approaches should be supported by the doc structure.

I stop, I talk too much. @BillWagner what are your thoughts? Do I understand your intention for abridged references correct (as described in the previous paragraph)?

**Comment by BillWagner** [comment]
@pkulikov I appreciate the thought you've put into this.  It's one reason why having a plan, issues, and a proposal helps discuss and improve as early in the process as possible.

I took another look at creating an organization based on usage. It's better, but probably not perfect. There's a lot that I like in your analysis:

> From above, I say I gravitate to _functionality_ as organizational strategy. However, some operators might be in a group that contains only one operator, others might be considered belonging to several groups. That's why I think that additional layer on top of individual articles would be helpful: it would allow to mention one operator within different groups. 

I am leaning in that direction. My first attempt was to put every operator in a single _group_, with none in single or miscellaneous groups. That doesn't work. I also really dislike a misc. group: that would send readers to an article with unrelated concepts.

> [Another supported scenario should be]  "OK, I know what this symbol means. Where is it usually used? What other operators do typically go with this one?", or "I want to do some math with numerics: what are the available operators?", or "I want to play with bits: what can I do?".

Yes, and I want to take that further: this is the primary use case, once the spec is published on docs (with some keys in docfx.json to get to more details on a single operator. Put another way, can the _overview_ pages be enough, if they include interactive examples and links to pertinent spec docs? I'm not sure, but I want to keep trying with outlines a bit longer...

**Comment by BillWagner** [comment]
Here's the 2nd pass at a functional based outline:

**Arithmetic operators**
- `++` Operator (prefix and postfix)
- `--` Operator (prefix and postfix)
- `*` multiplication
- `/` division
- `%` remainder
- `+` addition
- `-` subtraction
- `<<` left shift
- `>>` right shift
- `+`  unary positive
- `-`  unary negative
- `~`  bitwise complement
- `checked` / `unchecked`
- arithmetic compound assignment operators

> The above comment about "work with bits" means maybe shift should go in its own group, with bitwise `&`, `|` and `^`

**Relational and equality operators** 
- `==` equality
- `!=` not equal
- `<` less than
- `>` greater than
- `>=` greater than or equal
- `<=` less than or equal

> I'm open to the idea of splitting equality and relational into two separate groups.

**Type testing and assignment**

- `is` (and is with assignment)
- `as`
- `=` (assignment)
- `?` (nullable) `!` (null forgiveness)
- `switch` expression
- `true`, `false` (operators)
- `typeof` operator
- `(T)` explicit cast

**Logical operators**

- `!`  unary logical not
- `&` logical and
- `|` logical or
- `^` logical XOR
- `&&` conditional and
- `||` conditional or
- `??` null coalescing
- `?` `:` conditional (ternary)

> There's a good case to be made that `??` belongs with `?.`.

**string constant tokens**

- `@` verbatim string
- `$` interpolated string

**Instantiation and initialization** 
- `new` operator
- `default(T)`, `default` default value operator
- `delegate`
- `=>` lambda declaration
- `,` compound declaration
- `{}` block / compound statement

> This group feels a bit forced.

**Member access**
- `.` member access Operator
- `()` method call Operator
- `[]` array access Operator
- `?.` and `?[]` null conditional access and index Operators

** Pointers and unmanaged types**
- `->`
- `&` address of
- `*` dereference operator  

**Other operators and special tokens**

- `::` (namespace alias qualifier)
- `nameof`
- `sizeof`
- `await`  

> These should each get their own page. I can't create any logical grouping for any of the four.

**Comment by pkulikov** [comment]
@BillWagner

> Put another way, can the _overview_ pages be enough, if they include interactive examples and links to pertinent spec docs?

It depends. Below is one more take on the topic.

**Current approach to operator reference consolidation**

The main idea is to have a number of the operator *overview* articles. An overview article describes a group of related operators. Operators are put in a group based on their *usage/functionality*. The current list of groups is in the [comment above](https://github.com/dotnet/docs/issues/10757#issuecomment-468477396).

*At minimum* (or to start with), an overview article would include the corresponding sections from the current operator reference docs with interactive examples.

**What happens with the individual operator articles?**

Can those be removed completely by merging into the corresponding overview article?

Every article should be considered separately:
- Some operators don't belong to any group (for example, `::`). Their individual pages stay as they are now.

- Some operator symbols have only one meaning and belong to only one group. Examples are a group of equality operators and a group of relational operators. Their current pages can be merged together with an H2/H3 heading per operator (I assume, an individual operator still should be linkable). For those, overview pages seem to be enough.

- Some operator symbols change their meaning depending on the type of operands, but those meanings are related (in particular, go together in the spec). For example, let's consider the [binary `+` operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/addition-operator), With the current division proposal, it would end up in the group of arithmetic operators.
  
  **Question:** where and how are string concatenation and delegate combination described/mentioned? It would be out of topic to provide related examples and details in the article about arithmetic operators. Also, it doesn't seem that there is another group overview to cover those. I would say that an individual article most probably should stay in place.

  One might say that the related language spec [section](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#addition-operator) might be the replacement of an individual operator article. My concerns about language spec are further below.
  
  (By the way, note that the `/` and `%` operator articles might be fully merged into the arithmetic operator overview. However, that would mean that such an overview should distinguish between integer and floating-point arithmetic. Given `checked`/`unchecked` operators/keywords, that separation looks highly probable, anyway.)

- At last, there are operator symbols that have very different meaning. An example is the [`&` operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/and-operator), which ends up in the group of logical operators and in the group of pointer-related operators. That means, that existing article must be split: one part goes to one overview, while the rest of the article goes to another overview.

  **Question:** how then does a reader would learn about all possible meanings of the `&` symbol, given he faced such a symbol in the code and didn't know what it meant? Currently, the corresponding article in the docs is the only place. The language spec talks about the logical AND and the address-of operators separately, without cross-linking.

  A possible solution is to have two entries in the [operators TOC](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/) for the `&` symbol: one for logical AND, another — for address-of. Such a solution works as long as every operator is included into some overview and can be linked (that's why an H2/H3 heading per operator in an overview).

To summarize:
- It looks fine to leave group-less articles as is.
- It looks fine to merge an article that clearly belongs to only one group into the corresponding overview.
- It's even fine to split an article among multiple overviews, as long as every individual operator gets into some group and can be linked, or in other words, there would be still a way to provide an answer on the "What are all the meanings of this symbol?" question.

The hardest articles to deal with are those that contain sections that *do* belong to some group AND sections that *don't* belong to any group. Those are `+`, `+=`, `-`, `-=`. There might appear others after further group revisions.

A possible solution for such articles is to keep an individual article as it is now. The overview would link it (in a "For more information, see..." way), AND an article would link the overview (in a "For overview of related operators, see..." way). There might be some duplication in text, but examples can be reused.

**Remarks on the language spec**

I would treat the language spec links as they are treated now: explicitly state that the link goes to the language spec and it's "for more information". In other words, I wouldn't replace the doc reference article on the `+` operator with the "Addition operator" section from the spec, because the language spec is harder to comprehend: for the first-time/non-experienced reader paragraphs about dynamic binding and binary operator overload resolution might be overwhelming.

**Comment by rpetrusha** [comment]
A couple of miscellaneous comments:
- I would definitely split the "Arithmetic operators" group into two distinct groups -- arithmetic operators and bitwise operators. Given that bitwise operators are far more specialized, having it in its own group makes the arithmetic operators group far less intimidating. (I'd also never think to look for bitwise operators in the arithmetic operators group.)
- + is also a string concatenation operator. That seems to be missing.

More generally, I really like the functional/category approach. I think that it makes sense to supplement it with a single-page list of symbols/keywords that link to the appropriate article.

I think that it's fine to have any entire category of operators in a single article, such as all arithmetic operators in a single article. Failing that, it seems to me to e a good idea to include a closely related group of operators in a single article. For example, +,  ++ (prefix), ++ (postfix), and += can be included, which allows the article to be a basic reference as well as serve as a simple tutorial for anyone who might use addition by one instead of ++ or `x = x + y` instead of `x += y`.

The problem is how to handle operators that fall in multiple categories. I think that the best way of handling them is to treat them separately, but to note the alternate use whenever there is one. (For example, to not include & as a bitwise AND operator when treating it as a logical operator, but instead to note the alternate meaning of the & symbol with a link to the logical operators topic.)

**Comment by pkulikov** [comment]
@BillWagner as for operator grouping, I would keep groups as small as possible to have overviews very narrow-focused. The following division is derived from [your proposal](https://github.com/dotnet/docs/issues/10757#issuecomment-468477396).

**Arithmetic operators**
- `++` (prefix and postfix)
- `--` (prefix and postfix)
- `+` (unary and binary addition of numeric operands)
- `-` (unary and binary subtraction of numeric operands)
- `*` (multiplication)
- `/` (division)
- `%` (remainder)
- corresponding compound assignment operators
- `checked`/`unchecked`

**Bitwise operations**
- `&` (bitwise AND for integral operands)
- `|` (bitwise OR for integral operands)
- `^` (bitwise exclusive-OR for integral operands)
- `~` (bitwise negation)
- `<<` and `>>` (shift operators)
- corresponding compound assignment operators

**Logical operations (limited to `bool`)**
- `&` (logical AND for `bool` operands)
- `|` (logical OR for `bool` operands)
- `^` (logical exclusive-OR for `bool` operands)
- `!` (logical negation)
- `&&` and `||` (conditional logical AND and OR operators)
- `true` and `false` operators (**note:** it's still might be a separate article on its own and only referenced from the overview) @BillWagner what made you put those two operators into the "Type testing and assignment" group?
- corresponding compound assignment operators

**Relational operators**
- `<` (less than)
- `>` (greater than)
- `<=` (less than or equal)
- `>=` (greater than or equal)

**Equality operators**
- `==` (equal)
- `!=` (not equal)

As relational operator are predefined only for numeric types, while equality operators are for a broader set of types, I consider them as separate groups.

**Pointer-related operators**
- `&` (address-of)
- `*` (pointer indirection)
- `->` (pointer member access)

Pointer arithmetic with `++`, `--`, `+`, and `-` might also be included into the overview.

**Member access**
- `.` (member access)
- `[]` (array or indexer access)
- `?.` and `?[]` (null-conditional access)
- `()` (method call)

**Type testing, conversion and assignment**

- `is` (and is with assignment)
- `as`
- `=` (assignment)
- `?` (nullable) `!` (null forgiveness)
- `typeof` operator
- `(T)` explicit cast

@BillWagner why did you put the `switch` expression in this group? Cannot it be used in a broader context than only type testing?

**Not-in-any-group operators**
- `?` `:` (conditional operator). Somehow, it feels out of tune with the logical operators.
- `??` (null coalescing). It also feels not in the logical operations group. Most probably, it's because I limit logical operations to those on `bool` operands.
- `+`, `+=` (string concatenation and delegate combination)
- `-`, `-=` (delegate removal)
- `::` (namespace alias qualifier)
- `nameof`
- `sizeof`
- `await`
- `=>` (lambda declaration)

I would also not mix `@` and `$` into one string-related topic: those two features are of different size. Also, where would other two usages of `@` go?

**Comment by BillWagner** [comment]
> what made you put those two operators (`true` and `false`) into the "Type testing and assignment" group?

Not sure. I like your organization better here.

> why did you put the switch expression in this group? Cannot it be used in a broader context than only type testing?

Is was thinking about pattern matching with `is`, `as` and `switch`. I think it might be better to put those three in a single overview where *all* the patterns can be shown. Thoughts?

**Comment by BillWagner** [comment]
**Formal proposal**

I like the proposal in the previous comment by @pkulikov 

I'd like to adopt it as the resolution to this issue. I'll leave this open for further discussion until Wednesday. If there are no objections at that time, I'll update the related issues and close this discussion.

**Comment by pkulikov** [comment]
> I think it might be better to put those three in a single overview where _all_ the patterns can be shown. Thoughts?

I think to have a structured overview of pattern matching with all the patterns presented is a good idea. With that, should the "Type testing" overview still describe before-pattern-matching-era meanings of the `is` and `as` operators?

**Comment by pkulikov** [comment]
@BillWagner 

> ...I'll update the related issues...

I'd be glad to work on those issues and compile the corresponding overview articles.

**Comment by BillWagner** [comment]
@pkulikov Thank you!

Let's start with the the arithmetic operator page. That's the most well defined of the consolidated pages.

**Comment by BillWagner** [comment]
I've updated all the issues for this set of pages. Closing this.
