### ISSUE TITLE
How about another example of deployment with DevOps Pipelines

### ISSUE THREAD

**Issue by seanshankus** [dotnet/docs#10828]
most the devops pipeline examples are geared toward web apps and not .net core application/services.  It would be nice to see how to do non web .net app deployments with devops service (bonus points for multiple environment where the configuration needs to change).

sean

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a17d5d-5f6e-d6bc-324b-af411a42ccb8
* Version Independent ID: f58588d7-70f6-aa32-5c6d-ac3e7d72d87c
* Content: [.NET Core Application Deployment - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/deploying/)
* Content Source: [docs/core/deploying/index.md](https://github.com/dotnet/docs/blob/master/docs/core/deploying/index.md)
* Product: **dotnet-core**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
Hi!

Specifically this article are about the different publishing modes built into `dotnet.exe` which ways to build and deploy the application bits. Once you have done that, you would need to take these files to some other system like Azure Pipelines. And, that depends on what Azure Service you want to use. 

Right now though, you're more likely to find some docs on this in the Azure Service of your choice or in documentation related to Azure Pipelines. Either way, you're building your app, deploying it (which generates the files) zipping it up, and sending it to an Azure Service, but you're configuring that all in Azure Pipeline specifically.

I'm going to close this issue since it does not contain any actionable feedback related to this specific article.

Thanks.
