### ISSUE TITLE
nuget pack on osx

### ISSUE THREAD

**Issue by jchannon** [dotnet/docs#11066]
Under Nuget Distribution point 5 it says you have to use nuget pack.  On OSX you'd have to install mono which you shouldn't have to do.  What does nuget pack do that dotnet pack doesn't? This seems to go against cross platform support?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ccd42dc-0af2-1fa1-130a-61aff2d0770c
* Version Independent ID: 612b5eb7-23b9-68cd-a184-df9268ddb768
* Content: [Create a custom template for dotnet new - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/create-custom-template#use-nuget-distribution)
* Content Source: [docs/core/tutorials/create-custom-template.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/create-custom-template.md)
* Product: **dotnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
I would guess no difference. It would be good to change this to `dotnet pack`

**Comment by jchannon** [comment]
Can we get this done soon please? I've just hit this again. I also compared the results of dotnet pack and mono nuget.exe pack and they are completely different so you may find it's not as easy as just swapping them

**Comment by Thraka** [comment]
@jchannon I did a lot more investigation and the current `dotnet pack` command is not compatible with this tutorial. The `dotnet` commands end up working on the project file to generate things while the `nuget` command is working on that `.nuspec` file. 

I think the real answer to this problem is to rewrite the tutorial for the `dotnet pack` command. 

@KathleenDollard Can you comment on this? Can we use the `dotnet pack` command create a template without needing to use `nuget` directly?

**Comment by seancpeters** [comment]
@seancpeters

**Comment by seancpeters** [comment]
Overall this tutorial looks pretty good. 

It should be added that prior to creating the nupkg, the project being converted to a template should be cleaned. Otherwise the contents of obj\ and bin\ will get included in the template nupkg, which will cause a variety of problems when attempting to install the template pack. In general, there should be no .exe or .dll files included in a template pack - it's an unsupported scenario, and may prevent installation from succeeding.

Regarding installing a template from nuget.org, the listed command:
`dotnet new -i GarciaSoftware.ConsoleTemplate.CSharp`
will work in most situations. This command will install the latest stable version of the package from nuget. But if the nuget package version is a preview version, then the package name will need to be qualified with the version. For example if I wanted to install GarciaSoftware.ConsoleTemplate.CSharp Version 0.9.0-beta1, then the proper install command would be:
`dotnet new -i GarciaSoftware.ConsoleTemplate.CSharp::0.9.0-beta1`
This is dictated by how nuget resolves package version, and obeys the same syntax / rules.

I think it should be made clear that a template and a template pack are not synonymous - it's a common misconception (in the dotnet new world). A template pack contains one or more templates - most of the Microsoft owned template content is shipped in packs with multiple templates. 

For these section headers and their content: 
- "Install the template from a NuGet Package"
- "Install the template from a NuGet package stored at nuget.org"

They both contain text along the lines for "install the template from the nupkg" and "install a template from a NuGet package stored at nuget.org". What's really happening with these commands is that the **pack** is being installed. For this walkthrough, the pack happens to contain only 1 template, and so, by installing the pack, you're effectively just installing the one template. But in general this is not the case - all templates in the pack will be installed, and there is no way to install some, but not all, of the templates in a pack.

Similarly for uninstalling, these sections imply equivalence between a template and a template pack:
- "To uninstall a template from a NuGet package stored at nuget.org"
- "Uninstall the template from a local nupkg file"

The listed commands for these actions are causing the pack to be uninstalled, which uninstalls all the templates in the pack. Like with install, there is no way to uninstall just a selected template - the entire pack must be uninstalled.

While this walkthrough uses template packs that only contain one template, in general that's not the case, and I feel it would be best to be clear to authors about the difference between a template and a template pack.

**Comment by Thraka** [comment]
@seancpeters Thanks for the feedback. Would you be interested in updating the article and opening a pull request?

One issue though we still have is that the `dotnet pack` command seems lacking compared to `nuget pack`. And by forcing users to use `nuget pack` we require them (on *nux) to install Mono.

**Comment by KathleenDollard** [comment]
One issue though we still have is that the dotnet pack command seems lacking compared to nuget pack. And by forcing users to use nuget pack we require them (on *nux) to install Mono.

We'll take this part on. Would you mind filing it as an issue on the github.com/dotnet/CLI, which will then let you tidy up your repo. This is definitely a product feature issue, not a docs issue.
________________________________

**Comment by Thraka** [comment]
@KathleenDollard Filed an issue.

@jchannon I'm going to close this for now. Let's get the `dotnet pack` command fixed up and then we can remove nuget as a dependency for this scenario and not resort to all sorts of workarounds trying to trick `dotnet pack` into working.

**Comment by Thraka** [comment]
Reopening to track that we want to remove the `nuget pack` command explicitly from this tutorial.
