### ISSUE TITLE
Typo in section "Asynchronous microservice integration enforces microservice's autonomy"

### ISSUE THREAD

**Issue by platonish** [dotnet/docs#11104]
Second paragraph, last sentence: 
`...you have an architecture that won't be resilient when some microservices fail.`

I believe it should be: `...and architecture that would be resilient...`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89fd8427-589c-9158-f9e9-6b59d34ac4e2
* Version Independent ID: 3091e297-8939-cc0c-7437-5ec8be56ae3c
* Content: [Communication in a microservice architecture](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/architect-microservice-container-applications/communication-in-microservice-architecture#feedback)
* Content Source: [docs/standard/microservices-architecture/architect-microservice-container-applications/communication-in-microservice-architecture.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/architect-microservice-container-applications/communication-in-microservice-architecture.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
@mvelosop @CESARDELATORRE can you look at this feedback? I think the text is correct as-is.

**Comment by mvelosop** [comment]
Hi @platonish, @mairaw is right about the text.

A simplified version of the paragraph would be:

**If you need to call one microservice (B) from another (A) to provide a response, then the architecture is not resilient.**

It's not resilient because **microservice A** can't respond if **microservice B** fails.

A resilient architecture here would ensure that **microservice A** has a copy of the data it needs from **microservice B**, and the data is kept up to date (eventually) with an asynchronous communication system.

Hope this helps.
