### ISSUE TITLE
Recommending using 0 instead of real value makes test untrustworthy

### ISSUE THREAD

**Issue by Matiszak** [dotnet/docs#11288]
Hi,
I noticed that in section "Write minimally passing tests" the better solution uses 0 instead of 42. But let's suppose that the methods code is broken and it does not add at all. Then the test will also pass. Even in TDD style of working we would never see this test failing.

I think that the test should be changed to use value 1 instead of 0 and put a note below the test why using 1 and not 0 (because at first sight 0 is the most obvious minimal requirement in the test)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51947dc8-9ae8-21fa-13db-a7ffb3f9bc0e
* Version Independent ID: be661bf5-6f6e-cd18-344b-253edf5751ae
* Content: [Best practices for writing unit tests - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices#feedback)
* Content Source: [docs/core/testing/unit-testing-best-practices.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-best-practices.md)
* Product: **dotnet-core**
* GitHub Login: @jpreese
* Microsoft Alias: **wiwagn**

**Comment by jpreese** [comment]
I'm not quite sure I follow, Matiszak. The intent of that section is to highlight the fact that you should only do exactly what you need to in order to get the test to pass, and keep it as simple as possible.

In the string calculator example, this phase of the code would likely not have any addition, and would just be returning the single number that was passed in to add.

For example,

```csharp
public int Add(string input)
{
  return 0; // putting 42 here and writing a test that assumes 42, is more complex than just using 0
}
```

**Comment by Matiszak** [comment]
Yup, I think it just seemed weird to me to use 0 in adding. But your explaination makes sense.

**Comment by rzinnatullin** [comment]
However, I'd recommend using something different from default value of type, because it sometimes simplifies debugging. When debugging a method of Nth level of nesting, if you see 0 values, you don't really understand why they're zero - either because of a bug somewhere, or because they came from the unit test. If you see something like 42, or 1234, you'll probably quickly understand that the value was passed correctly.
