### ISSUE TITLE
Missing info about memory barrier

### ISSUE THREAD

**Issue by astrowalker** [dotnet/docs#11360]
One important issue about `await` is whether `await` creates memory barrier or not. Currently on MSDN page there is no word about it (confirming it, or denying) -- IMHO it should be mentioned.

**Comment by BillWagner** [comment]
@astrowalker Can you elaborate about what you mean by "creates a memory barrier"?  I'm not sure what you mean. What operations would you think is safe or unsafe based on a "memory barrier"?

**Comment by astrowalker** [comment]
@BillWagner , I answer with an example taken from: https://stackoverflow.com/questions/41928139/thread-safety-on-async-await-with-memory-caching

    private static async void TestAsync()
    {
        bool complete = false;
        Func<Task> testFunc = async () =>
        {
            await Task.Delay(1000);
            bool toggle = false;
            while (!complete)   // interesting part
            {
              toggle = !toggle;
            }
        };

        var task = testFunc();
        Thread.Sleep(2000);
        complete = true;
        await task;
        Console.WriteLine("Done");
    }

The interesting part is the loop (see the comment) -- it does not see the outside change (most likely because register caching + optimization). But when you add dummy `await` inside the loop, the outside change is seen inside -- if I am not mistaken this is because memory barrier is added and the actual value is read.

**Comment by BillWagner** [comment]
Thanks for adding that information @astrowalker 

It is due to optimizations and register caching.  Our page on [volatile](https://docs.microsoft.com/dotnet/csharp/language-reference/keywords/volatile) has more details.

I'll close this as resolved.

**Comment by astrowalker** [comment]
@BillWagner , I am lost, I didn't say a word about `volatile`. Maybe I add question to your explanation -- why with added `await` register caching does not trigger in?

Or in other words -- does `await` adds implicit memory barrier or not? For example http://www.albahari.com/threading/part4.aspx#_Memory_Barriers_and_Volatility in section starting with "The following implicitly generate full fences:" lists all (?) constructs which adds memory barrier, but I would like to be sure about `await` what it adds and what it does not add.

**Comment by BillWagner** [comment]
@astrowalker The [SO question](https://stackoverflow.com/questions/41928139/thread-safety-on-async-await-with-memory-caching) you referenced discussed `volatile` as one way to resolve this issue. I'll answer your questions in reverse order:

> Or in other words -- does await adds implicit memory barrier or not?

No. The composition from `await` does not contain any memory fencing.

> why with added await register caching does not trigger in?

Register caching still takes place. But, with an `await` in the loop, `testFunc` yields, and lets the other thread run, and reloads any registers when its execution continues.

It's an oversimplification, but the `await` forces a thread switch.

**Comment by astrowalker** [comment]
@BillWagner , thank you very much! It would be useful to add it to MSDN page directly to make it official (the only one unofficial statement I found is from Stephen Cleary https://stackoverflow.com/a/54413147/6734314 but it is opposite as I understand it "await will ensure all necessary memory barriers are in place").

**Comment by JohnRusk** [comment]
@BillWagner If await doesn't create a memory barrier, does that mean that, from the code that called the awaited method, it is safe to use the Task result, but it is not safe to use other shared memory than may have been manipulated by the Task when it was running?

This is important, because it makes a big difference to thread safety in some cases.

**Comment by epatstarkey** [comment]
@BillWagner @JohnRusk Did you ever get an answer to your question here John?

**Comment by BillWagner** [comment]
@JohnRusk @epatstarkey I apologize, I missed that question.

Adding @stephentoub who can provide insight on https://github.com/dotnet/docs/issues/11360#issuecomment-584378410

**Comment by stephentoub** [comment]
`await` itself doesn't create a memory barrier, but it also doesn't need to; that's not its job.  It's the job of the thing being awaited to ensure that anything it's written is visible to any consumer.  So, for example, Task's completion entails a store release barrier such that any work done prior to the Task's completion is published to anyone trying to consume it, and reading the status / result / etc. of a Task involves a read acquire barrier.

**Comment by epatstarkey** [comment]
@stephentoub Thanks for the precise answer, that's exactly what I wanted to know.

**Comment by hrumhurum** [comment]
According to Windows OS documentation, any wait operation that involves a kernel wait object creates an implicit memory barrier. I have a strong suspicion that `await` may inherit that property even if it does not use OS kernel objects directly.

You can check this yourself by examining the code of `System.Threading.Tasks.Task` class [here](https://github.com/dotnet/runtime/blob/4e48d2d85ed15140b95323e615a5433726b583b2/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs#L1281). The `Task` type has `Status` property, and every waiting operation will query that status in the end. Under the hood, `Status` reads `m_stateFlags` field which is marked with `volatile` keyword. Accessing a volatile field either for a read or write will issue a corresponding memory barrier. And the code behind `await` keyword does access `Task.Status` property, which in turn accesses the volatile `m_stateFlags` field. So to answer your question, `await` technically issues a memory barrier _after_ the task completion.

Regarding your sample code: for barrier synchronization to work, the barriers should be issued on both read and write accesses. Otherwise, the change may be not released or may not be acquired to/by other threads. To avoid those gotchas, I would suggest to modify the code as follows:

```c#
static async void TestAsync()
{
    bool complete = false;
    Func<Task> testFunc = async () =>
    {
        await Task.Delay(1000);
        bool toggle = false;
        while (!Volatile.Read(ref complete))   // interesting part
        {
          toggle = !toggle;
        }
    };

    var task = testFunc();
    Thread.Sleep(2000);
    Volatile.Write(ref complete, true);  // interesting part
    await task;
    Console.WriteLine("Done");
}
```

It would very convenient if we could mark a captured local variable with `volatile` keyword. However, the current C# syntax does not allow that. Thankfully, .NET provides [System.Threading.Volatile](https://learn.microsoft.com/en-us/dotnet/api/system.threading.volatile) class as a workaround.
