### ISSUE TITLE
Getting Started with .NET Core on VS Code

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#1141]
We need really basic introduction on how to get started with .NET Core on VS Code.
The golden path topic we have on docs covering VS Code (https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/using-on-macos), it's more like a tour.

We also need to make sure we're not duplicating content that is being done for VS Code docs.

**Comment by kendrahavens** [comment]
I helped with the VS Code docs and I'm really happy with them! Let's either duplicate their page or link to it. They also link to my video tutorial. 

[https://code.visualstudio.com/docs/runtimes/dotnet#_hello-world](https://code.visualstudio.com/docs/runtimes/dotnet#_hello-world)

- Benefits of linking to their page: They may update it themselves so we don't have to!
- Benefits of duplicating their page: We can highlight .NET Core content and keep entry users inside the .NET Core docs instead of the VS Code docs.

I'm leaning towards simply duplicating their page. (copy and paste!) The steps are not OS specific and they are general enough that they won't need to be updated every time a tool is newly released. I'll make a PR? Any suggestions while I do?

**Comment by mairaw** [comment]
I think I'd lean towards having our own so we can add more scenarios as needed. Although the topic is very simple and OS agnostic, I feel like a completely new user needs to be guided more, so I miss some screenshots (it would not be OS agnostic but we could note that in the start that the screenshots are for a particular OS but the steps are the same/similar across and/or call out which OS we'll be using in the title/description) and do some more hand-holding. The way that topic is written it almost doesn't tell you how to use VS Code and doesn't tell about the prompts you get along the way. 
So I'd layout the steps in a format similar to this:
1. Open Visual Studio Code.
2. Go to **File**, **Open Folder**. 
  -> insert screenshot perhaps?
3.  On the **Select Folder** dialog, choose the path where you want to create your Hello World app, such 
as *C:\Projects\HelloWorld*, and click **Select Folder**. 
4. Go to **View**, **Integrated Terminal** to open the [Integrated Terminal](https://code.visualstudio.com/docs/editor/integrated-terminal) or press Ctrl+\`.
etc.
And I'd also embed your video instead of just linking to it.
And in the end we could also add the VS Code in the See Also section.

Thoughts?
