### ISSUE TITLE
Required default constructor

### ISSUE THREAD

**Issue by amervitz** [dotnet/docs#11543]
Can you please elaborate on what is meant by a `Required default constructor` in the `Persistence Ignorance` section and how that violates that principle?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 829862b0-b51d-d4dd-d770-f875a588384f
* Version Independent ID: 4ab12fcc-7cc1-d40b-b5c4-d145fe25e98e
* Content: [Architectural principles](https://docs.microsoft.com/en-us/dotnet/standard/modern-web-apps-azure-architecture/architectural-principles#dependency-inversion)
* Content Source: [docs/standard/modern-web-apps-azure-architecture/architectural-principles.md](https://github.com/dotnet/docs/blob/master/docs/standard/modern-web-apps-azure-architecture/architectural-principles.md)
* Product: **dotnet**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by ardalis** [comment]
Just to clarify, let's say you have an entity `PurchaseOrder` and it has a PO number like `ABC123456` which is required. So you create the entity like this:

```
public class PurchaseOrder
{
  private string _poNumber = "";
  public PurchaseOrder(string poNumber)
  {
    _poNumber = poNumber;
  }
}
```

This is a perfectly good and intention-revealing OO class. It enforces its desired invariant that all purchase orders must have a PO Number by making it required in the constructor. It no longer has a default constructor because none is defined and the existence of one that requires a parameter eliminates the one that C# will otherwise create automatically.

However, this entity will not work with EF/EF Core. EF requires a default constructor. So if you have this entity in a project that uses EF, you will most likely write it like this:

```
public class PurchaseOrder
{
  private string _poNumber = "";
  public PurchaseOrder(string poNumber)
  {
    _poNumber = poNumber;
  }
  private PurchaseOrder() {} // Because EF needs it
}
```
This is a seemingly useless bit of code that your IDE will tell you can be removed because nothing is calling it, but if you do remove it, EF will break. This class is no longer persistence ignortant because part of its design has been altered for the sole purpose of allowing it to work with a specific persistence strategy, in this case EF.

Does that help?

**Comment by amervitz** [comment]
Yes that is helpful, thank you. I think the terminology of a `Required default constructor` violating the principle is the cause of my confusion, because I interpreted that as meaning that a default constructor violates the principal, because the default constructor is effectively being required by the compiler because it generates it when no other one has been provided.

A different way of stating this violation of the principle could perhaps instead be `Not including a default or parameterless constructor`. What do you think?

**Comment by amervitz** [comment]
On second thought I don't think my suggestion is right either.

In your example, how would you make the `PurchaseOrder` class be persistence ignorant given that you want it to work with EF?

**Comment by ardalis** [comment]
There's not really a good way that I know of - I would do what I show in the second option.

PI is something to strive for, and the more an ORM tool like EF can allow you to use PI entities, the better. But there are very often trade-offs between PI and the productivity benefits you get from using a tool like EF for your persistence.

**Comment by amervitz** [comment]
OK, circling back to the beginning, it seems like the guidance of not adding a required default constructor to a class that has other constructors (as in your EF example) is actually preventing a class from becoming PI, so I'm struggling to see it as a violation of the principle. For the same reason why a POCO type is PI, because it can be instantiated and manipulated without other specialized knowledge as to how the type is designed, so would a class that has a required default constructor added to it become usable in the same way.

**Comment by ardalis** [comment]
In my example above, the first class (without parameterless ctor) is sufficient for the task at hand and is PI. The second version adds a private parameterless constructor for the sole purpose of allowing EF to instantiate the class when it's doing its thing. Stuff that must be added to your object model solely because some particular persistence technology needs it, but which otherwise adds no value, makes the class less "persistence ignorant" and adds some technical debt. The fact that it requires a comment to tell the team why it's there so nobody inadvertently removes it is a big clue that it's a (minor) problem. Another example is `private set` when modern C# will let you just omit the `set` entirely if you're only initializing it during construction. If you get rid of the (unused) private set, as your IDE will suggest you do, suddenly EF will stop working and that property will always be null/default when fetched from persistence. Again you have design constraints being made on what are otherwise POCOs due to a specific choice of ORM technology. Does that make sense?

**Comment by amervitz** [comment]
That makes a lot of sense. I think this discussion as an accompaniment to the documentation clarifies the meaning of the statement. I will go ahead and close this off. Thank you!

**Comment by ardalis** [comment]
@maira thoughts on adding a link to this discussion from the doc, or otherwise adding some clarification to it?

**Comment by itadapter** [comment]
This item is very skewed, opinionated and mixes multiple separate contexts. Firstly, polyglot persistence has absolutely nothing to do with types of constructors, base classes et.al.  the idea that a "good constructor" must have required fields makes absolutely no sense in any real application. Real business applications deal with models containing 10s of fields, most of which are conditionally required. Practice shows that it does make a LOT of sense to do the very opposite - NEVER use .ctors with parameters, because there is no uniform pattern, and by adding these ctors which are by the way never called by anyone because all data models must be constructed automatically anyway.  So this article is very much biased.

On a separate note, having a base class, once again is absolutely orthogonal to providing polyglot persistence. What is important is that "active record" -like "saving" logic is NOT in base class - that is true, however in OOP which is NOT dead and very powerful still when done correctly it does make sense to model data models using OOP, using interfaces and extracting common attributes. This is even far more productive in the light of using polyglot data stores (e.g. MsSql / MongoDB / JSON files)
