### ISSUE TITLE
Wrong comment in the EncryptDataToStream example code

### ISSUE THREAD

**Issue by hongcc1** [dotnet/docs#11586]
Take note that in these two functions, the comment line right above calling the Protect data is wrong -- it should not be the same as the comment of the Protect in EncryptInMemoryData.  
Comment for the Protect in EncryptDataToStream should be something like "...The encrypted result is copied to the EncryptedData buffer. Original data in the Buffer remains the same."

Correct me if I am wrong. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e223a92-49ef-5bf0-9dab-13b7300fabd4
* Version Independent ID: bbac5ee9-27f0-cf07-5891-32a3e9a0341b
* Content: [How to: Use Data Protection](https://docs.microsoft.com/en-us/dotnet/standard/security/how-to-use-data-protection#feedback)
* Content Source: [docs/standard/security/how-to-use-data-protection.md](https://github.com/dotnet/docs/blob/master/docs/standard/security/how-to-use-data-protection.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by hongcc1** [comment]
Typo correction -

Take note that in the EncryptDataToStream function in the example code, the comment line right above calling the Protect data is wrong -- it should not be the same as the comment of the Protect in EncryptInMemoryData.
Comment for the Protect in EncryptDataToStream should be something like "...The encrypted result is copied to the EncryptedData buffer. Original data in the Buffer remains the same."

Correct me if I am wrong. Thanks.

**Comment by mairaw** [comment]
Thanks for your feedback @hongcc1. You're right, the comment shouldn't be the same. Would you like to submit the fix for this?
Perhaps you could say something like "Encrypt the data and store the result in a new byte array. The original data remains unchanged." What do you think?

The samples for this article can be found here:
https://github.com/dotnet/samples/blob/master/snippets/csharp/VS_Snippets_CLR/DPAPI-HowTO/cs/sample.cs
https://github.com/dotnet/samples/blob/master/snippets/visualbasic/VS_Snippets_CLR/DPAPI-HowTO/vb/sample.vb

These samples also have a typo where the sentences say "same same" twice like
The result is stored in the **same same** array as the original data.
