### ISSUE TITLE
Finalizer/Destructor Performance Cost

### ISSUE THREAD

**Issue by soonerjvm** [dotnet/docs#11684]
I've not had a lot of exposure to garbage collection algorithms, except maybe a few concepts on how they work.  But mentioned above, an empty destructor in C# may cause some performance issues.  Having used C# destructors in the past, this makes me curious if non-empty destructors can also cause some performance issues.  If this is the case, would you mind explaining why it would create some performance issues?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26b6bf23-9cd5-a7c5-dc6a-f9b911d784ff
* Version Independent ID: 9f040450-27b7-7e4a-b908-c3695f6aaad1
* Content: [Finalizers - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/destructors#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/destructors.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/destructors.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @soonerjvm we should update this language.

Creating a finalizer (empty, or with code) has performance implications. 

If you need a finalizer to correctly free unmanaged resources, you must accept the performance implications. Otherwise, the resource isn't released.

The note about empty finalizers is that adding an empty finalizer (which implies your class doesn't need one) has performance implications. Any object of that class must be finalized. The objects are added to the finalization queue when garbage collected. More objects on that queue mean more processing time to call empty methods. Only after finalization are those objects actually garbage collected.

I've added this to our backlog, and added the "up for grabs" label. We'll address this when we next update this document. In the meantime, one of our community members may issue a pull request for this clarification.

**Comment by soonerjvm** [comment]
It doesn't sound like the performance cost is too great, because it sounds like it's still of linear complexity.  It sounds like an empty finalizer is really creating a "waste-of-space" when the garbage collector is iterating through, what I'll just assume, and only using as an example, is something similar to a linked list, looking for resources to return to the OS.  If something like this is the case I can see how it would start to unnecessarily create some performance issues, especially if, kind of like you were saying, we are dealing with hundreds, thousands, or more of these objects.

But thank you for your response.  You did answer my question I think two-fold:  Finalizer's cost performance is equal whether it is empty or not, and performance cost appears to be linear.
