### ISSUE TITLE
IDisposable?

### ISSUE THREAD

**Issue by grosch** [dotnet/docs#11687]
The stream objects implement IDisposable.  Why aren't you using the "using" pattern here instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a7ce223-b955-7f50-6b53-15585c68f02d
* Version Independent ID: 78e4d95a-3a97-ec74-ebf4-843bad4efa7a
* Content: [How to: Send data by using the WebRequest class](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/how-to-send-data-using-the-webrequest-class#feedback)
* Content Source: [docs/framework/network-programming/how-to-send-data-using-the-webrequest-class.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/how-to-send-data-using-the-webrequest-class.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by Thraka** [comment]
The requirement here is really that you must `Close` the stream otherwise the connection is held. `Dispose` will `Close` the connection. Additionally, as to the way this is explained (step-by-step), trying to describe the using pattern start/end is more difficult than just stating that you have to `Close` one of them.
