### ISSUE TITLE
Too vague

### ISSUE THREAD

**Issue by Korporal** [dotnet/docs#11707]
This documentation is too vague. It begins by suggesting we "create a package from a SDK-style project" but how? how does one do that? There is no project type listed in VS 2019 named anything like "SDK Project".

Surely we aren't expected to manually create a text file and populate it manually with XML like this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc2b4abb-c382-17ef-f1f3-1413ee27aaa0
* Version Independent ID: 4d4bb4d2-a8f4-f142-7154-40ce7fc7ae32
* Content: [NuGet and .NET libraries](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/nuget)
* Content Source: [docs/standard/library-guidance/nuget.md](https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/nuget.md)
* Product: **dotnet**
* GitHub Login: @JamesNK
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Yes.. the wording in there is a bit odd... but it's kind of necessary because depending on what tool you're using (visual studio 2017 vs 2019? visual studio code? dotnet cli?) you may get different project formats. It may be worth listing some minimum versions required to get SDK-style projects.

With Visual Studio 2019 I believe that SDK-style is the format that will be created for you.
