### ISSUE TITLE
View Code link in API Reference Link pointing wrong line

### ISSUE THREAD

**Issue by ThePiranha** [dotnet/docs#1172]
View Code link for [Binder Class](https://docs.microsoft.com/en-us/dotnet/core/api/microsoft.csharp.runtimebinder.binder#Microsoft_CSharp_RuntimeBinder_Binder) under [Microsoft.CSharp.RuntimeBinder Namespace](https://docs.microsoft.com/en-us/dotnet/core/api/microsoft.csharp.runtimebinder#Microsoft_CSharp_RuntimeBinder) is pointing to [Line 16](https://github.com/dotnet/corefx/blob/master/src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/Binder.cs/#L16), which should be [Line 17](https://github.com/dotnet/corefx/blob/master/src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/Binder.cs/#L17).

Can anyone please point me to which repository the HTML code is maintaining?

**Comment by mairaw** [comment]
I believe it points to line 16 because the attributes are also part of the class declaration, so View Code would point to where the attributes start. @chenkennt could probably confirm this and if it's feasible to change to go straight to where the API is being declared.

Can you clarify what exactly you're trying to find?

**Comment by ThePiranha** [comment]
@mairaw Thanks for the update. Actually I was going through the APIs and noticed this.

**Comment by mairaw** [comment]
Closing this since our API reference docs no longer has a View Code link
