### ISSUE TITLE
Navigation tree has an issue breaking multiple links

### ISSUE THREAD

**Issue by codecadwallader** [dotnet/docs#11827]
The navigation tree in this area appears to have a broken link at:

Tutorials -&gt; Get started writing custom analyzers and code fixes

and everything after that part cannot be selected.  There are also two Tutorial sections immediately next to each other which may be part of the problem.  Thanks for any help/cleanup!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4bd716a-906d-983b-141c-4a4e2e2a79ec
* Version Independent ID: debed50c-98ce-ec0e-bcf6-0170a4e60fcc
* Content: [The .NET Compiler Platform SDK (Roslyn APIs)](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/)
* Content Source: [docs/csharp/roslyn-sdk/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/roslyn-sdk/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by codecadwallader** [comment]
Here's a little animated image of trying to navigate in the tree.  This is using FireFox v66.0.3 and I was able to reproduce it in Google Chrome as well with the default theme / no user profile.

![image](https://user-images.githubusercontent.com/3823772/56085842-58a78b00-5e3a-11e9-8117-bee79339c5c6.png)

**Comment by mairaw** [comment]
Thank you for letting us know about this issue @codecadwallader. It seems to be caused by our migration from Markdown to YAML format for the Table of Contents. This used to be hidden from our TOC because we still don't have those topics:
https://raw.githubusercontent.com/dotnet/docs/33388f53749f9557de8736572ec0dbe0abf234ae/docs/csharp/roslyn-sdk/toc.md

I'll remove those entries for now.

**Comment by codecadwallader** [comment]
Cool, thanks for the quick fix and I can confirm it looks better now. :)
