### ISSUE TITLE
What is "designer"?

### ISSUE THREAD

**Issue by MaxxVelocity** [dotnet/docs#11884]
Several documents mention a "designer" that must be on the screen in order to add an installer, but only UI applications have a "designer" view. Please update this to explain the exact process and stop assuming that this "designer" concept is everyday knowledge. I have 20+ years industry experience and have never seen a "designer" on an API. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fdb6f36-c952-4317-669d-b4618505b688
* Version Independent ID: 69caa919-1a67-806e-172b-f20653ca32b3
* Content: [How to: Add Installers to Your Service Application](https://docs.microsoft.com/en-us/dotnet/framework/windows-services/how-to-add-installers-to-your-service-application#feedback)
* Content Source: [docs/framework/windows-services/how-to-add-installers-to-your-service-application.md](https://github.com/dotnet/docs/blob/master/docs/framework/windows-services/how-to-add-installers-to-your-service-application.md)
* Product: **dotnet-framework**
* GitHub Login: @ghogen
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
Hello!

The Visual Studio editor treats the Service template types as designers, which is what this is referring to. The class types also are built on the designer concept, much like Windows Forms are. This is why the article talks about them in this context. I think it's this way (especially for the installer) because the installer stuff hooks into the installer dialog prompt system. As soon as you get into custom installer territory, you jump out of the API-only world that is referred to in the [How to: Write Services Programmatically](https://docs.microsoft.com/en-us/dotnet/framework/windows-services/how-to-write-services-programmatically) article.

The designer is called out specifically in Visual Studio here:

![image](https://user-images.githubusercontent.com/2672110/56309778-1367af80-60ff-11e9-9ade-d7c42cf9ef21.png)

I'm going to close this issue. If your problem is not solved, feel free to reopen or comment. Thanks!
