### ISSUE TITLE
Include referenced projects as assemblies

### ISSUE THREAD

**Issue by fleed** [dotnet/docs#11899]
Is it possible to include the referenced projects as assemblies embedded in the package?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7e805a3-f2ec-b05a-d5c8-29f7a8c16a5f
* Version Independent ID: 4257ec12-df6f-ec52-aad3-012e5fce8133
* Content: [dotnet pack command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack?tabs=netcore2x#feedback)
* Content Source: [docs/core/tools/dotnet-pack.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-pack.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by fleed** [comment]
Some more context: I have a solution with the dotnet tool project which is referencing some more projects within the solution.

At the moment, invoking `dotnet pack` is creating a package for the tool that it is expecting/referencing packages for the referenced projects, but at the moment I just would like to have a sort of "_self-contained_" package with the referenced assemblies and the required dependencies to external packages.

**Comment by Thraka** [comment]
Hello!

I believe the build system will only pack referenced assemblies if you are referencing them as a normal DLL library reference and not using a package reference.

That being said, you can edit the nuget package (with a tool such as NuGet Package Explorer) and add more files and reconfigure things **after** the package is created. I think you could also reference the DLL as an "included" file in your project or something. There may be tricky ways around it, but what I described above is how the system works by default.

I'm going to close this issue. If your problem is not solved, feel free to reopen or comment. Thanks!
