### ISSUE TITLE
no boxing, no casting

### ISSUE THREAD

**Issue by dgibbs-at-uwsp** [dotnet/docs#11918]
Isn't this comment a "lie"?  Or is it just pointing out that the programmer doesn't need to box or cast?  Because doesn't boxing/unboxing occur by the List?

// No boxing, no casting:
list1.Add(3);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1df209a-0be4-8d72-1535-d2fd90c3c61d
* Version Independent ID: 5b9991c8-9624-a3fe-0b44-1c565a2d378d
* Content: [Benefits of Generics - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/benefits-of-generics)
* Content Source: [docs/csharp/programming-guide/generics/benefits-of-generics.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/generics/benefits-of-generics.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mikkelbu** [comment]
The comment is correct, since the list has type `List<int>`. One of the advantages of generics besides compile-time type checking, binary code reuse, and clarity of the code was the avoidance of casting and boxing/unboxing.

See e.g. https://blogs.msdn.microsoft.com/jmeier/2006/10/06/performance-guideline-use-generics-to-eliminate-the-cost-of-boxing-casting-and-virtual-calls/ for more information.

**Comment by BillWagner** [comment]
@mikkelbu Thanks for providing the answer to @dgibbs-at-uwsp 's question.

I'll close this as an answered question.
