### ISSUE TITLE
Atomicity of WaitHandle.SignalAndWait

### ISSUE THREAD

**Issue by user2150** [dotnet/docs#12037]
The "Features Common to Automatic and Manual Events" section says: "A thread can signal an EventWaitHandle and then block on it, as an atomic operation, by calling the static WaitHandle.SignalAndWait method".

This means that
1) the WaitHandle.SignalAndWait method is atomic;
2) the handles to signal and to wait on are the same.

But in the article about WaitHandle.SignalAndWait
https://docs.microsoft.com/en-us/dotnet/api/system.threading.waithandle.signalandwait?view=netframework-4.8
we read: "This operation is not guaranteed to be atomic". And the handles to signal and to wait on in the example are different.

So my questions are:
1) Is WaitHandle.SignalAndWait actually atomic?
2) May be it is atomic when toSignal and toWaitOn handles are the same and is not when they are different?
3) Are there two different use cases when the handles are the same and when they are different?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b658ffa-560e-4823-0f0e-9c27942df6c8
* Version Independent ID: c8154d85-150e-ac3d-5efe-6bb8776b0365
* Content: [EventWaitHandle](https://docs.microsoft.com/en-us/dotnet/standard/threading/eventwaithandle#feedback)
* Content Source: [docs/standard/threading/eventwaithandle.md](https://github.com/dotnet/docs/blob/master/docs/standard/threading/eventwaithandle.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by tdykstra** [comment]
@kouvel can you answer these questions?

**Comment by kouvel** [comment]
> Is WaitHandle.SignalAndWait actually atomic?

No, I think the former doc means to say "as a combined operation" rather than "as an atomic operation".

> May be it is atomic when toSignal and toWaitOn handles are the same and is not when they are different?

No, if there are threads already waiting on the wait handle then the signal would typically release one or more different threads, then the wait would wait or accept the signal depending on the type of wait handle.

> Are there two different use cases when the handles are the same and when they are different?

Maybe, depends on the implementation, but not guaranteed. You can see roughly what the PAL does on Unixes here: https://github.com/dotnet/coreclr/blob/cea2abf54bcee9c155db39774f2d8a1ccd4b4c66/src/pal/src/synchmgr/wait.cpp#L756-L800

More info here: https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-signalobjectandwait

Curious, if it were atomic, how do you plan to make use of the atomicity?

The main advantage (from .NET perspective) is that this API combines two p/invoke overheads into one. There may be a relatively slight perf advantage in the implementation. I generally would not recommend using this API unless perf really matters and considering the work involved that would probably be a rare thing if at all, with likely better solutions to the perf issue.

**Comment by user2150** [comment]
No, I'm not using this API, I just wanted to understand what are threads and how they work. Now I'm working with the nice Task API and async/await.

Thank you for the clarification.
