### ISSUE TITLE
Private Constructor

### ISSUE THREAD

**Issue by timyhac** [dotnet/docs#12069]
Would it make sense to make the constructor for CardType private?

That way the users of our enumeration class can't instantiate their own card types, and it becomes closer to an enum.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d118f070-8743-e905-2d08-dc725a4e8b5f
* Version Independent ID: fae35cbd-75ae-4448-f066-7c91ccc35779
* Content: [Using Enumeration classes instead of enum types](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types#feedback)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mvelosop** [comment]
Hi @timyhac, thanks for your feedback.

I agree with you in the general case, when you use an enumeration class to replace an enum, that is something that has a finite set of values.

I just think there are better examples for an enumeration class, say the OrderStatus.

In this specific case, the static values are just a way to have an initial default set of values to seed a database.

So, in this specific case, it must be public, because it can be used to seed the DB from a text file, and the constructor needs to be public.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
