### ISSUE TITLE
Question on Loading Data from Database

### ISSUE THREAD

**Issue by debpu06** [dotnet/docs#12075]
**Issue description**

Question on implementation. Instead of loading the data from a file, I am loading from a DbContext. I am following the tutorial exactly, with the exception that once I load the data from the DbContext, I add it to the model using **LoadFromEnumerable**. 

However, when doing this I continually get the following error:

"AUC is not definied when there is no positive class in the data"

**Target framework**

Check the .NET target framework(s) being used, and include the version number(s).

- [x] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview3-010431
 Commit:    d72abce213

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64

Host (useful for support):
  Version: 3.0.0-preview3-27503-5
  Commit:  3844df9537
```
</details>

**Comment by debpu06** [comment]
Found out the issue was due to my data not having positive label values in my test/training data. Because of this it was not able to calculate the Auc value. Issue was mentioned [here](https://github.com/dotnet/machinelearning/issues/3175) in the dotnet/machinelearning repo. 

Closing this issue.

**Comment by larsbeck** [comment]
I am having a similar issue, however in my case I do have positive labels in my training data. I wrote a small test and figured out that you have to have >15% positive datapoints, otherwise this error occurs (I had 8%). I guess it does make sense to not have such a skewed dataset from an ML perspective. Maybe there is a way to deal with this programmatically or change the exception message. The way it is formulated now says there is no positive class in the data, which is not true in my case, just relatively few.
