### ISSUE TITLE
// Await the completed task.

### ISSUE THREAD

**Issue by foofoodog** [dotnet/docs#12071]
Why do the "int length = await firstFinishedTask; " instead of just using "int length = firstFinishedTask.Result;"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d15bb1b-5f7f-20f3-78c3-d2b5bce950ed
* Version Independent ID: 80bee493-257b-5c64-4f28-cfb4e9bae560
* Content: [Process asynchronous tasks as they complete](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/start-multiple-async-tasks-and-process-them-as-they-complete)
* Content Source: [docs/csharp/programming-guide/concepts/async/start-multiple-async-tasks-and-process-them-as-they-complete.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/start-multiple-async-tasks-and-process-them-as-they-complete.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for raising this question @foofoodog 

In most cases, both work. The difference is when the task is faulted. `await` will throw the first child exception stored in the `AggregateException`. The `Result` property will throw the `AggregateException`. 

I've added this to our backlog, and added the "up for grabs" label if you want to submit a PR that adds the answer I wrote above. Otherwise, we'll update it when we next update this article.

**Comment by foofoodog** [comment]
@BillWagner That is a good distinction and I appreciate the clarification, thank you.
Looking back on it I think this is bad example code and should just be scrapped and re-written for a lot of reasons. I will see if I can either bing/google/stackoverflow/write a better example and gist one that can be pasted into linqpad, or a .cs and be csc compiled.

My problem with bad examples code is new folks on the team will copy and paste this verbatim, and my code review turns into pair programming refactoring sessions :)
