### ISSUE TITLE
Finding runtime changes for .NET 4.8

### ISSUE THREAD

**Issue by csrowell** [dotnet/docs#12118]
I apologize as I am completely missing it, but I can't find a list of Runtime (vs Retargeting) changes for .NET 4.8. When I choose the drop downs on this page ("Select the .NET Framework you are currently targeting and then the .NET Framework you wish to migrate to") it redirects me to the Retargeting Changes page and for each item on that page the "Type" is listed as Retargeting. Even when choosing .NET 4.0 to 4.8 it only lists Retargeting changes and not Runtime changes. Thanks in advance for your help. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ea2516e-2b0d-7759-1703-c3a146a5c343
* Version Independent ID: 0776830f-df42-931d-ec86-f57b17a6545e
* Content: [Runtime Changes in the .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/runtime/#feedback)
* Content Source: [docs/framework/migration-guide/runtime/index.md](https://github.com/dotnet/docs/blob/staging/docs/framework/migration-guide/runtime/index.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @conniey
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @csrowell. I apologize for the inconvenience. We've unfortunately supplied incorrect URLs for all runtime changes that include .NET Framework 4.8, which causes retargeting rather than runtime changes to be displayed. We'll fix this immediately, though changes won't be published to docs.microsoft.com until early next week. 

In the meantime, you can manually modify the URL to display runtime changes. For example, if you select runtime changes from .NET Framework 4.5.2 to .NET Framework 4.8, the page at <https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/retargeting/4.5.2-4.8> is displayed. To display the corresponding runtime changes page, change **retargeting** in the URL to **runtime**, so that the URL becomes <https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/runtime/4.5.2-4.8>.

**Comment by csrowell** [comment]
Perfect, thanks for the workaround and letting me know I'm not crazy. 😊
