### ISSUE TITLE
WCF custom errors question?

### ISSUE THREAD

**Issue by minoseah629** [dotnet/docs#12119]
In .net mvc, custom errors can be turned on in web config. 

Does turning on custom errors have any effect to a WCF app?

I already implemented an IErrorHandler globally.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2bd955f-6c8f-c1a2-b350-e887d592c61e
* Version Independent ID: 89b8d72d-5585-3141-0fb0-1c8b9483e301
* Content: [WCF Error Handling](https://docs.microsoft.com/en-us/dotnet/framework/wcf/wcf-error-handling)
* Content Source: [docs/framework/wcf/wcf-error-handling.md](https://github.com/dotnet/docs/blob/staging/docs/framework/wcf/wcf-error-handling.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @HongGit
* Microsoft Alias: **wcfsrvt**

**Comment by Thraka** [comment]
@HongGit Perhaps your team can answer this question?

**Comment by dasetser** [comment]
cc: @mconnew in case you have more to add.

If you're hosting your WCF service as a web app setting the customErrors value will do something, since it is still a web app. For example, if you have some setup error with the service or IIS and try to navigate to the wsdl in a browser this setting would control how the error page is shown.

However, I don't think it should generally make any difference as far as handling errors in client requests like what this documentation page is about. If you set up your service correctly using fault contracts or IErrorHandler the errors should all be handled such that the customErrors value doesn't make a difference.

**Comment by Thraka** [comment]
@dasetser So if I understand what you're saying, it's that the server-side errors settings are still valid, but handling errors there has no affect on client-side. No matter what, WCF service error handling you've implemented (fault contracts or IErrorHandler) still get bubbled down to the client.

**Comment by mconnew** [comment]
@Thraker, with things like WebAPI and MVC, the URL sent to the server will change from one request to the other. e.g. http://example.com/Customers/1 vs https://example.com/Orders/17 . What the service does is highly dependent on the URL you send. With WCF, everything is sent to the same URL. e.g. http://example.com/MyService.svc and the thing which changes is the POST body. So if you mistype the url and go to .svb instead, then the customErrors kick in as the page doesn't get routed to WCF. So basically, if you get the url correct, the request gets to WCF so customErrors doesn't come into play. If you get the url wrong, it doesn't go anywhere near WCF and you aren't doing anything WCF related until you fix it. It's not like with an MVC app where the range of valid url's is infinite. One endpoint is one url, and you better get it right or else WCF isn't coming to your party and staying at home watching GoT leaving you to play with ASP.NET on your own.

**Comment by Thraka** [comment]
@mconnew Makes sense, thanks.

@minoseah629 I think this answers your question and I'm going to close this issue.

**Comment by minoseah629** [comment]
thank you for the responses. @Thraka, @dasetser, and @mconnew
