### ISSUE TITLE
Why ExecutionAndPublication and PublicationOnly have such names?

### ISSUE THREAD

**Issue by MNF** [dotnet/docs#12214]
Could you please explain in the article, why ExecutionAndPublication and PublicationOnly have such names? The descriptions of modes do not mention publication and it is not clear how behavior is associated with the name of mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c082508c-af74-1d6a-a954-e70aca02e1a4
* Version Independent ID: 85c92c40-9a7a-cd0f-fa63-53c87cb5febe
* Content: [Lazy Initialization](https://docs.microsoft.com/en-us/dotnet/framework/performance/lazy-initialization?view=netframework-4.8)
* Content Source: [docs/framework/performance/lazy-initialization.md](https://github.com/dotnet/docs/blob/master/docs/framework/performance/lazy-initialization.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
@kouvel can you help with this question? Is this an issue with the docs?

**Comment by kouvel** [comment]
I suspect that it's referring to what guarantees are made. There's some code that would do initialization and then a value produced would be published to be used by consumers thereafter. Sort of like:
- A safety mode of `None` does not guarantee anything (not to be used by multiple threads I figure, since otherwise multiple initializations may occur and multiple values may be published and used by consumers)
- A safety mode of `Publication` would guarantee that exactly one result of an initialization would be published and used by consumers, but does not guarantee that initialization code only runs once nor that it may not run concurrently
- A safety mode of `ExecutionAndPublication` would guarantee that initialization code would run in a thread-safe manner, and only one initialization would occur, the result of which would be published and used by consumers

**Comment by MNF** [comment]
@dotnet/docs, will @kouvel’ s explanation above be useful to include in the documentation?

**Comment by kouvel** [comment]
Yes I'll add to the docs
