### ISSUE TITLE
DownloadStringAsync with async

### ISSUE THREAD

**Issue by junpark12** [dotnet/docs#12265]
Hi I have a question.
I can define downloadStringAsync method using async keyword and
return content instead of Task.FromResult(content). 
Can you please point out what are the differences between original one and the code below?
I am confused little bit. thanks. 

static async Task&lt;string&gt; DownloadStringAsync(string address)
        {
            string content;

            if(cachedDownloads.TryGetValue(address,out content))
            {
                return content;
            }

            return await Task.Run(async () =&gt;
            {
                content = await new HttpClient().GetStringAsync(address);
                cachedDownloads.TryAdd(address, content);
                return content;
            });
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e64eba6-e183-dfd7-fc52-deaf8a717ed6
* Version Independent ID: f2135220-cdf6-a4bb-5f2a-9a5c0ac6fbdf
* Content: [How to: Create Pre-Computed Tasks](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-create-pre-computed-tasks)
* Content Source: [docs/standard/parallel-programming/how-to-create-pre-computed-tasks.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/how-to-create-pre-computed-tasks.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by svick** [comment]
The differences between the two are fairly subtle. The main ones are exception handling (the version with `async` never throws directly, but instead places any thrown exception on the returned `Task`) and performance (the version without `async` is more efficient). For more details, see Stephen Cleary's article [*Eliding Async and Await*](https://blog.stephencleary.com/2016/12/eliding-async-await.html).

Since the article is specifically about explaining how `Task.FromResult` could be used, I'm not sure there's anything that should be changed in it (even though the article I linked to recommends against this practice).

**Comment by junpark12** [comment]
thanks. actually the question is not related to this article. :)
