### ISSUE TITLE
dotnet clean command won't delete bin and obj folder that produced by dotnet publish

### ISSUE THREAD

**Issue by quantrpeter** [dotnet/docs#12304]
I tried to publish my console program to another folder for output, but i found there are still bin and obj exists in the source folder. When i run "dotnet clean", it won't delete these two folders in my src folder.
thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce4a4413-002d-4f6b-547d-3ac0c2cf84b8
* Version Independent ID: fad3d9a6-f1e8-7428-84cf-7895ece1efa2
* Content: [dotnet clean command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-clean)
* Content Source: [docs/core/tools/dotnet-clean.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-clean.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@livarcocc @KathleenDollard according to [this comment](https://github.com/dotnet/cli/issues/10372#issuecomment-440385887), it seems that `dotnet clean` only cleans build content and not publish content. Is that behavior by design? Do we intend to change this in future releases?

**Comment by livarcocc** [comment]
That is by design for now. We currently do not have plans to change this behavior.

cc @peterhuene in case he has something else to add.

**Comment by Thraka** [comment]
@quantrpeter As this is by design, I suggest you file an issue with https://github.com/dotnet/cli/issue and request that clean behaves this way (or some option to toggle it)

I'm going to close this as the bug isn't related to a problem with the documentation. Thanks!

**Comment by mairaw** [comment]
Reopening since the docs are saying the folders are cleaned. We should describe the correct behavior.

/cc @cartermp @terrajobst

**Comment by Thraka** [comment]
Reading it again I think the description is correct:

>Only the outputs created during the build are cleaned. Both intermediate (obj) and final output (bin) folders are cleaned.

This is true and is what indeed happens. Only the files generated for a **build** are deleted. It doesn't state that the bin folder is deleted. Per this description, publishing (being a whole other process that puts the published files into a folder under bin) wouldn't be affected.

**Comment by mairaw** [comment]
Yep, but we need to make that more clear.

**Comment by 1jeffchristensen** [comment]
**Setup:**
In folder D:\dev\myapp\ I have my sln file and no bin folder and no obj folder.
I run `dotnet --version` which outputs SDK 3.1.100

**Step 1:**
Then I run `dotnet build` from within D:\dev\myapp
Now I have a bin folder and a obj folder.

**Step 2:**
Now I run `dotnet clean` from within D:\dev\myapp

**Issue:**
I still have a bin and obj folder. (And I have a built dll for a referenced project that will never get updated unless I go manually the bin folder from my file system.)

**This is so problematic!** A dll built in bin\Debug\netcoreapp will now exist for a referenced project, but if I go make a change in the referenced project, the cli will **NOT** produce a new dll!

Even though the GitHub issue 12304 is about `dotnet clean`, I have identified several issues plaguing my team.

1. I believe that `dotnet clean` should clean what was just built using `dotnet` build seconds earlier.
2. `dotnet build` will no longer use the referenced project as source since there is already a built dll for the project, even though that dll is out of date.
3. The documentation for dotnet clean does not match the stated behavior when there are referenced projects in the csproj.

**Comment by Thraka** [comment]
@1jeffchristensen Hello.

However, I have projects that also use project references and when I do `dotnet clean` everything is deleted from the build bin/obj folder. It's completely empty for me. Are you copying files to these folders? the `dotnet clean` command parses the file/dependency tree for the project and cleans out everything known about the project. For example, if you have `file1.txt` referenced in your project as an asset to copy to the output folder, it will be deleted from the output folder with `dotnet clean`. However, if you just manually copy that file into the folder, `dotnet clean` isn't going to touch it, and that is a good thing.

If you need to go further and delete the entire bin/obj folders, I suggest you just make a small script and run that instead of `dotnet clean`. **Or** add a new task to your project that runs after the dotnet clean command that deletes those folders for you. For example:

```xml
<Target Name="AfterClean">
    <Exec Command="rm .\bin -r" />
    <Exec Command="rm .\obj -r" />
</Target>

**Comment by lukeschlather** [comment]
Could we add a new command called dotnet purge that deletes these folders?

**Comment by Thraka** [comment]
@lukeschlather You would want to file a request on https://github.com/dotnet/cli/ as this github repo is just for documentation related to how the CLI works. New features and/or bugs should be filed at the repo I just linked to. Cheers!

**Comment by quantrpeter** [comment]
thank you all gentlement, thanks a lot

**Comment by mairaw** [comment]
You actually wanna file the issues at https://github.com/dotnet/sdk, since the CLI repo has recently moved

**Comment by Thraka** [comment]
Thanks @mairaw .. I keep doing that. I updated my comment.

**Comment by dcaslin** [comment]
@Thraka's suggestion was very helpful but needed some tweaking to get it to run with latest dotnet core with a standard `dotnet clean` command. To save anyone else the trouble, you can drop this element right into your csproj file and it should work.
```

<Target Name="PostClean" AfterTargets="Clean">
    <Exec Command="rm .\bin -r" />
    <Exec Command="rm .\obj -r" />
    <Exec Command="echo Hit it with hammer clean complete" />
</Target>
```

**Comment by NickStrupat** [comment]
The `rm` command is not cross-platform (err, not cross-shell). I propose this more portable solution.

```xml
<Target Name="PostClean" AfterTargets="Clean">
    <RemoveDir Directories="$(BaseIntermediateOutputPath)" /><!-- obj -->
    <RemoveDir Directories="$(BaseOutputPath)" />
</Target>
```

The build properties are (partially?) enumerated here:
https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2019

**Comment by mauriciogracia** [comment]
Thank you all for sharing your knowledge, cleaning the /bin and /obj has help me to solve and issued about `Error CS0579: Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute`. 

I had to clean those folders because adding this to the .csproj was not enough.
  ```
<PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
```

**Comment by whuanle** [comment]
get out dir:
```

    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net6.0-windows10.0.19041.0|AnyCPU'">
      <LayoutDir>bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX2</LayoutDir>
    </PropertyGroup>
```
execute command
```
	<Target Name="ClientBuild">
		<Exec WorkingDirectory="./" Command="RMDIR /s/q &quot;$(LayoutDir)&quot;"/>
	</Target>
```

**Comment by jkone27** [comment]
is this fixed in NET9? i still have this in NET8 sdk

**Comment by sometimesacoder** [comment]
> The `rm` command is not cross-platform (err, not cross-shell). I propose this more portable solution.
> 
> ```
> <Target Name="PostClean" AfterTargets="Clean">
>     <RemoveDir Directories="$(BaseIntermediateOutputPath)" />
>     <RemoveDir Directories="$(BaseOutputPath)" />
> </Target>
> ```
> 
> The build properties are (partially?) enumerated here: https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2019

Note that this breaks a 'Rebuild' because as far as I can tell, msbuild always does a NuGet restore as the very first thing it does no matter what. So on a rebuild it does the NuGet restore which creates nuget metadata in the obj folder, then BeforeRebuild then Clean runs, then this custom PostClean target deletes the obj folder which breaks the NuGet packages, then it tries to run the build targets which fail from non-restored packages. Even if you get to run as the very first target the Rebuild fails since restoring nuget packages runs before any targets apparently. Considering it uses the obj folder you'd think it wouldn't do a NuGet restore until just before the build instead of before everything.

**Comment by mdhampton** [comment]
This problem is especially problematic when working on blazor/razor projects, as switching branches leaves the obj folder, and that can cause all sorts of odd build errors. The only solution I've found is to manually empty obj then do a full build.
