### ISSUE TITLE
CS0403 No longer appears in VS 2019 when using the is operator for unconstrained generics

### ISSUE THREAD

**Issue by dave-q** [dotnet/docs#12374]
In 2019 i can do this bool IsNull&lt;T&gt;(T thing) =&gt; thing is null;
I can't do this in 2017 (or as it turns out on my build server) is this a documented change? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a38eefc-8281-1a25-9ecd-38e11f6199f0
* Version Independent ID: ebbc28bf-be03-d0ce-ec86-a83b9c84b003
* Content: [Compiler Error CS0403](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0403)
* Content Source: [docs/csharp/misc/cs0403.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs0403.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this up @insulind 

We do document the new behavior for `is`  in the language reference for [is](https://docs.microsoft.com/dotnet/csharp/language-reference/keywords/is#-constant-pattern).  That doesn't discuss an unconstrained generic test like you show. Both that page and this one should be updated.

Ping @agocke and @gafter  to make sure this is a docs issue, and not a compiler issue.  I tried the following variations with C# 8.0 preview:

```csharp
int j = 5;
Console.WriteLine(j is null); // compiler error: cannot convert null to int because it is a non-nullable value type.
```

```csharp
bool IsNull<T>(T thing) => thing is null;

int j = 5;
Console.WriteLine(IsNull(j)); // compiles, writes "false".
```

```csharp
bool IsNull<T>(T thing) where T : struct 
   => thing is null; // compiler error: cannot convert null to T because it is a non-nullable value type.

int j = 5;
Console.WriteLine(IsNull(j)); 
```

If those are all correct, we'll update these articles.

**Comment by gafter** [comment]
Yes, that is correct.

**Comment by BillWagner** [comment]
There are two changes that should be made to fix this issue:

1. This article should mention that unconstrained generic types can use the constant pattern to check for null. It should also link to the language reference page for the [`is` keyword](https://docs.microsoft.com/dotnet/csharp/language-reference/keywords/is#-constant-pattern).
1. The reference page for `is` should be updated to add that the `null` constant pattern can be used with generic types as long a the constraint does not guarantee that the type is a non-nullable value type. The `struct` and `unmanaged` constraints would guarantee a non-nullable value type.  

The `System.Enum` constraint doesn't imply a struct. The following compiles because `System.Enum` is a class, not a struct:

```csharp
public static bool IsNull<T>( T thing) where T : System.Enum
    => !(thing is null);
````

I've added the "up for grabs" label based on the above description of the fix.
