### ISSUE TITLE
XAML code is inconsistent

### ISSUE THREAD

**Issue by rjkuehne** [dotnet/docs#12423]
when you get to the 'Add an image and a title' section above, the XAML code is different from the previous sections and some of the following sections so can't really go step by step here.  frustrating.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0dc39f7-b153-a46c-3b88-07c8ed2c71bc
* Version Independent ID: 78a14535-9703-e2af-4451-783a7c4c10be
* Content: [Create a WPF application in Visual Studio](https://docs.microsoft.com/en-us/dotnet/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application#feedback)
* Content Source: [docs/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by dhowes** [comment]
As you say, the sample code is inconsistent in that the box includes more code than has been introduced up to that point. However, the required code is highlighted. All the other code samples are fine.

**Comment by rjkuehne** [comment]
I did go further and see that you end up changing/adding code so that you get to the code that is shown in that step eventually.  Just seems to be a bit lazy, to confuse people rather than go step by step with them because you’ve already changed the code on your end.

**Comment by dhowes** [comment]
"I did go further and see that you end up"

"because you’ve already changed the code on your end"

I'm not sure whether "you" and "you've" here refer to the tutorial creators or to me. In case it's me, please note that I have nothing to do with this tutorial. I worked through it for the first time yesterday, noticed the highlighting, and thought it would be helpful to mention it so others could get past that step. As I indicated, I didn't see anything wrong with any of the remaining steps.

**Comment by JohnHunsberger** [comment]
In general I think I've learned more  by determining how to compensate for the omissions and errors than I might otherwise might have learned.  One example of my point is that there is a change to the ExpenseReportPage.xaml's d:DesignHeight="300" d:DesignWidth="300" to d:DesignHeight="350" d:DesignWidth="500".  As a newbe it took me a bit to discover how you did that trick.  In the main, the presentation was very helpful.  Thanks to the folks who put it together for us.

**Comment by JohnHunsberger** [comment]
By "you" I refer of course to the folks who kindly put this presentation together. :-)
