### ISSUE TITLE
Microservices do NOT require queues

### ISSUE THREAD

**Issue by brentstineman** [dotnet/docs#12484]
I take issue with the guidance in [this article](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/architect-microservice-container-applications/communication-in-microservice-architecture#asynchronous-microservice-integration-enforces-microservices-autonomy). While the use of queues is a great technique to promote the loose coupling of services... This article's wording positions them as the only truely viable option. 

In situations where latency is a key concern, the use of queues can be anti-pattern. I think the article needs to take a much more balanced approach and recognize that there are pros and cons to both approaches and help highlight when each might be suitable. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89fd8427-589c-9158-f9e9-6b59d34ac4e2
* Version Independent ID: 3091e297-8939-cc0c-7437-5ec8be56ae3c
* Content: [Communication in a microservice architecture](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/architect-microservice-container-applications/communication-in-microservice-architecture#feedback)
* Content Source: [docs/standard/microservices-architecture/architect-microservice-container-applications/communication-in-microservice-architecture.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/architect-microservice-container-applications/communication-in-microservice-architecture.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by CESARDELATORRE** [comment]
I think you are misunderstanding the content. We're not saying that Microservices always requires queues:

1. What we're saying is that the communication between the client app (either web app, mobile app or any front end) and the microservices is usually Http. Then, usually between the front-end and the microservices you usually have API Gateways that are also usually using HTTP, not queues.

2. However, the microservices should be autonomous between each other, so what we're trying to enforce is not to make long HTTP call chains between microservices and if any info from one microservice needs to be propagated to other microservices, then we recommend asynchronous communication for that. That means UPDATES which in most of the cases a small latency (eventual consistency using async communication) is okay for the business application. **But even for async communication you can also use either a Service Bus (kind of queues but using publish/subscription pattern) or no queues/service bus by using HTTP polling, also explained in that section as well, with no queues/service-bus at all.**

Sometimes you might require to call synchronously to other microservices from one microservice using HTTP or any other request/response protocol, but that approach is what we recommend to minimize because if you create long chains of synchronous calls between microservices that can be a nightmare when things go wrong in the application such as when on microservice goes slow or fails, retrys start trying and trying that microservice from multiple call chains, etc. if not handled properly you could even cause a DoS to your self.


Again, we're not saying that microservices require queues. You could have independent microservices being called from the API Gateways and front-end apps and only be using HTTP, for instance.

What we're saying is that for microservices intercommunication (communication between the internal microservices) it is recommended to use asynchronous communication and minimize as much as possible request/response communication (such as HTTP requests) "between the internal microservices" and do it only in certain exceptions, but it is perfectly fine to have HTTP communication like in a "start pattern" from the front-end or client app calling the microservices.

Hope this clarifies your question, but I think this is explained in the book if you read all the sections not just this particular section in the book.

Thanks for your feedback! :)

**Comment by Thraka** [comment]
Closing as this issue seems resolved.
