### ISSUE TITLE
The TaskCompletionSource not be canceled correct

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#12519]
@voidweapon commented on [Fri May 24 2019](https://github.com/dotnet/docs.zh-cn/issues/390)

In example of Exposing Complex EAP Operations As Tasks, the CancellationToken Just cancel WebClient, the tcs of TaskCompletionSource still running in some thread.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a7a2d4f3-d369-9945-79d1-31efea2f06cc
* Version Independent ID: 3004dcc5-a1d4-ba57-102d-46d955548085
* Content: [TPL 和传统 .NET Framework 异步编程](https://docs.microsoft.com/zh-cn/dotnet/standard/parallel-programming/tpl-and-traditional-async-programming#feedback)
* Content Source: [docs/standard/parallel-programming/tpl-and-traditional-async-programming.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/standard/parallel-programming/tpl-and-traditional-async-programming.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since the user is reporting an error in the code.
kind regards

**Comment by tdykstra** [comment]
@BillWagner Are you the right person to ask about this?

**Comment by BillWagner** [comment]
Thanks for the ping @tdykstra I can help.

The bug description isn't quite correct. It's true that `WebClient.CancelAsync()` cancels the download. It also invokes the `DownloadStringCompleted` handler, so that will mean that the `tcs.Task` does finish.

What's missing is that the handler doesn't check its event arguments to see if it was cancelled or completed. (There's a comment to that effect, but we should do better).
