### ISSUE TITLE
Nullable Types on VS 13 or 15

### ISSUE THREAD

**Issue by Rockin4Life33** [dotnet/docs#12672]
VS 2013 and/or VS 2015 does not seem to support Nullable Types.  

TFS VS 2013/2015 build server errors out when encountering Nullable types, I get errors on "?" on the line where I use them when I run a build.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b179d23d-c2fc-b4d6-64a6-451e5dd6c26c
* Version Independent ID: 745b7799-72f7-2df8-59a0-c09ec6572560
* Content: [Nullable Value Types - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/data-types/nullable-value-types#feedback)
* Content Source: [docs/visual-basic/programming-guide/language-features/data-types/nullable-value-types.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/language-features/data-types/nullable-value-types.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by Thraka** [comment]
What is the error? What version of .NET Framework are you targeting?

**Comment by Anovative** [comment]
@Thraka I don't recall the exact error message but it was throwing the error on the first `?` it encountered; which was a nullable.  The build server was 2013 or 2015 and the .NET Framework version is 4.6.  Since upgrading to a 2017 build server I doubt there will be issues anymore; but I have yet to test that.

**Comment by Thraka** [comment]
By build server do you mean TFS/Azure DevOps/VSTS (whatever it's called in that version) because if so, you really should open an issue on those product support channels, probably a forum or better yet stackoverflow may have some help. I'm going to close this issue under the assumption this is a product issue and not an issue with the documentation.

Sorry I can't be of more help!
