### ISSUE TITLE
Not beginner friendly with Main() and explicit

### ISSUE THREAD

**Issue by Almantask** [dotnet/docs#12720]
I was teaching OOP one of my students and was covering interfaces. I gave them the following task:
Fishes don't talk but fish is an animal
Cat is an animal and can talk
Dog is an animal and can talk
Human is not an animal, but can talk

They talked they sent me this:

```csharp
interface ITalk
{
    void Talk();
}

class Animal
{
    public virtual void WhatAnimal()
    {
        Console.WriteLine("Animal");
    }
}

class Fish : Animal
{

}

class Cat : Animal, ITalk
{
    public void ITalk.Talk()
    {
        Console.WriteLine("Meow");
    }

    static void Main()
    {
        ITalk obj = new Cat();
        obj.Talk();
    }
}

class Dog : Animal, ITalk
{
    public void ITalk.Talk()
    {
        Console.WriteLine("Woof");
    }

    static void Main()
    {
        ITalk obj = new Dog();
        obj.Talk();
    }
}

class Human : ITalk
{
    public void ITalk.Talk()
    {
        Console.WriteLine("Hello");
    }

    static void Main()
    {
        ITalk obj = new Human();
        obj.Talk();
    }
}


static void Main()      //Polymorphism
{
    ITalk a1 = new Cat();
    ITalk a2 = new Dog();
    a1.Talk();
    a2.Talk();
}
```

Why? Because of this page. Please fix it and make it clear, don't make lazy docs, make it intuitive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef21cb62-9cbd-84c8-cfae-6dd1a421180b
* Version Independent ID: d931e899-d6f0-55ff-ab3a-dfff6e31f5a2
* Content: [interface - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/interface#feedback)
* Content Source: [docs/csharp/language-reference/keywords/interface.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/interface.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@Almantask We agree that this is the wrong article for beginners that don't yet have a background in OO techniques.

I'm curious how they landed here, instead of the introductory material on [interfaces](https://docs.microsoft.com/dotnet/csharp/programming-guide/interfaces/) in the programming guide. That material, while still not perfect, is more approachable and explains the concepts you were trying to teach.

The language reference is for the syntax and semantic rules of the language, not style and design questions.

I'm going to close this, as the concerns you raise should not be addressed on this reference article. If you have comments on how we can improve the introductory OO material, you can open issues in the programming guide section.
