### ISSUE TITLE
Needs to be updated! it's a year old!

### ISSUE THREAD

**Issue by PhilKochan** [dotnet/docs#12786]
Needs to be updated! it's a year old!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b76cb0d-df6d-88c4-557d-ad327a566eef
* Version Independent ID: 95083e1c-ef53-e813-08e2-1aa31b431f00
* Content: [Choose between .NET Core and .NET Framework for server apps](https://docs.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server#feedback)
* Content Source: [docs/standard/choosing-core-framework-server.md](https://github.com/dotnet/docs/blob/master/docs/standard/choosing-core-framework-server.md)
* Product: **dotnet**
* GitHub Login: @cartermp
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Even though this topic hasn't been thoroughly reviewed in a year, we've been making small updates to it along the way as you can see in its commit history:
https://github.com/dotnet/docs/commits/master/docs/standard/choosing-core-framework-server.md

Whenever we make small updates like that, we don't change the date since the article hasn't been fully reviewed, just bits and pieces.

Is there anything specific that you feel that it's missing?

**Comment by mairaw** [comment]
Closing due to the lack of response. If you can get back to us with more information, we can reopen @PhilKochan. We pay attention to traffic and comments for all our topics to prioritize which ones get updated every month.
