### ISSUE TITLE
inputData in Batch missing

### ISSUE THREAD

**Issue by bjstigall** [dotnet/docs#12923]
The definition of inputData in the batch processing section is missing.  How to load from a CSV would be helpful.

[AB#1530397](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1530397)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30e7cf89-1a90-7693-db50-11b770c09160
* Version Independent ID: 21c26fd2-c6ad-2c2f-166b-03ac0590a1c2
* Content: [Make predictions with a trained model - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/machine-learning-model-predictions-ml-net)
* Content Source: [docs/machine-learning/how-to-guides/machine-learning-model-predictions-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/machine-learning-model-predictions-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @bjstigall,

Thank you for the suggestion. For brevity purposes and since the topic of loading data has already been covered in the [Load Data how-to](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/load-data-ml-net), the definition and process of loading this data into an `IDataView` was deliberately omitted from this sample. I do think it might be confusing and have added a note explaining the source of `inputData` as part of #12925. I hope that answers your question.
