### ISSUE TITLE
Using the check and cross marks to convey meaning is an accessibility issue

### ISSUE THREAD

**Issue by nschonni** [dotnet/docs#13000]
You could use the icons if you use an image with an applicable alt-text

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4b482b0-6dd1-42de-5389-5b0b47823402
* Version Independent ID: 79a4adc9-b2c9-68b7-669e-2bd8d2d44faf
* Content: [Evaluate breaking changes - .NET Core](https://docs.microsoft.com/en-ca/dotnet/core/compatibility/index)
* Content Source: [docs/core/compatibility/index.md](https://github.com/dotnet/docs/blob/master/docs/core/compatibility/index.md)
* Product: **dotnet-core**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks @nschonni for bringing awareness to this issue. I'm checking if we have any doc that already follows best practices on this so we can apply this consistently.

@gewarren tagging you since this area was assigned to you.

**Comment by Thraka** [comment]
@mairaw @gewarren I was looking at this and I'm curious. Is it an accessibility issue when the next word after the emoji conveys the thought? I can understand if it's just ✔️ or ❌ without any other text, but when it's ✔️ CORRECT doesn't the **CORRECT** become the alt-text for a screen reader?

**Comment by gewarren** [comment]
[This guidance](image type="icon") in our contributor's guide is interesting. It basically says that icons are decorative and should not have alt text. Go figure.

**Comment by Thraka** [comment]
Well I think really that is how these ✔️ check marks and stuff are used in the linked PR you have. Those are decorative. However, the ones in this specific document are **not** decorative and instead are used to represent status. This is really what needs to be fixed, not replacing them with images, changing the text that follows so that the check or cross is accurately presented for screen readers. For example:

>### Types
>
>- **✔️ Removing an interface implementation from a type when the interface is already implemented by a base type**
>
>- **❓ Adding a new interface implementation to a type**

Should become

>### Types
>
>- **✔️ ALLOWED: Removing an interface implementation from a type when the interface is already implemented by a base type**
>
>- **❓ DISALLOWED: Adding a new interface implementation to a type**

**Comment by gewarren** [comment]
Our team met today and concluded that it's not necessarily an accessibility issue. When we ran accessibility scans on these pages, they passed. Also, some screen readers do in fact read the ✔️ and ❌ emojis. Where it makes sense, such as in the original article this issue was created on, we will add clarifying text next to the emojis, however.

**Comment by nschonni** [comment]
Thanks for updating 👍
