### ISSUE TITLE
This page (migration from .NET Framework 4.6.1 to 4.7.1) should mention System.Runtime and some other system assemblies which are changed in .NET 4.7.1...

### ISSUE THREAD

**Issue by zxli** [dotnet/docs#13029]
Here is a few GitHub issues.
https://github.com/dotnet/corefx/issues/32757
https://github.com/dotnet/standard/issues/481

System.Runtime and some other system assemblies are integrated in .NET framework 4.7.1. It brings some weird issues for the apps developed with .NET framework 4.6.1 and then upgraded to .NET 4.7.1. Those apps used NuGet packages for System.Runtime with .NET framework 4.6.1 and could start to fail after the migration to .NET 4.7.1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e0c50e8-ca91-7949-1667-ea1630ec8f0b
* Version Independent ID: ad795371-4b90-51d3-0b9e-711e77945831
* Content: [Runtime Changes for Migration from .NET Framework 4.6.1 to 4.7.1](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/runtime/4.6.1-4.7.1)
* Content Source: [docs/framework/migration-guide/runtime/4.6.1-4.7.1.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/runtime/4.6.1-4.7.1.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @chlowell
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for your feedback, @zxli. Offhand, though, it strikes me that this is an issue that relates to IDE tooling rather than to the .NET Framework itself. @PriyaPurkayastha, what do you think?

**Comment by PriyaPurkayastha** [comment]
I agree with Ron's assessment that this is not a breaking change between .NET 4.6.1 to 4.7.1 based on this resolution provided for GitHub issue dotnet/corefx#32757 mentioned in this issue at the beginning:
The problem here I believe is with the VS tooling when you add the nuget package reference. It shouldn't be adding that extra binding redirect. If you instead migrate your project to use PackageReference then installing a new package won't generate binding redirects, and only at build time will we figure out if you need extra binding redirects or not, which in this case you shouldn't need any for System.Runtime as it already comes inbox for 4.7.1.

The .NET 4.7.1 release announcement blog has a section for "BCL - .NET Standard 2.0 section" which talks about this at:
https://devblogs.microsoft.com/dotnet/announcing-the-net-framework-4-7-1/

**Comment by gewarren** [comment]
Closing this issue since it's not a .NET Framework breaking change.
