### ISSUE TITLE
.NET Core 3.0 SingleExe docs

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/docs#13149]
.NET Core 3.0 will include the ability to publish an application as a single exe.
See https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-5/

- [ ] High level overview of the feature
- [ ] CLI options
- [ ] csproj options
- [ ] Where is the application extracted (per OS?)
- [ ] Are there any permissions issues possible? 
- [ ] Possible future features? 
- [ ] Comparison to WinRT?
- [ ] Where to provide feedback on the feature and to request additional features

**Comment by swaroop-sridhar** [comment]
Thanks @sdmaclea, please assign the issue to me.

**Comment by mairaw** [comment]
I feel this issue is already in progress. Here's what we have:
- Mention of this in the what's new docs: https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#default-executables
- Some coverage of that in the deployment docs and its children topics: https://docs.microsoft.com/en-us/dotnet/core/deploying/
- The following topic covers CLI options:
https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli

I'm in the process of updating the CLI reference docs and should mention that as well.

We don't typically cover where to log feature requests on articles since there's a link on the bottom of each article that takes you the developer community to log issues. If we need to send folks to a different spot, we can modify that, but that's the location discussed with the PMs previously for each area.
And possible future features shouldn't be discussed on docs. We cover the current status of tools and only mention bugs/issues if they impact a lot of people.

**Comment by swaroop-sridhar** [comment]
I agree @mairaw, design and further work discussions should be delegated to the design-doc which the "what's new" page already has a reference to.

I don't see the reference to PublishSingleFile in the following pages: 
https://docs.microsoft.com/en-us/dotnet/core/deploying/
https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli

In particular, we need to mention it in the deploy-with-cli page. Is this something you are currently working on? 

Apart from the CLI issue, we should mention the fact that the single-file feature works by extraction to temp directories. I'm happy to work with you in creating the docs. Thanks.

**Comment by Thraka** [comment]
@swaroop-sridhar The issue that you linked to was the issue filed to track this work in updating our documentation. I've closed that so that you can use this issue to track that. 

Before you write/update content, please make sure that you review the [voice principles for writing](https://review.docs.microsoft.com/en-us/help/contribute/writing-principles?branch=master). It would be good to review all of the articles in that TOC section.

**Comment by swaroop-sridhar** [comment]
@mairaw looks like the information in the `dotnet publish` [page](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-publish.md) is only up to version 2.1. Is there a place where we should PR doc changes for 3.0 ? (For example, single-exe options?) Thanks.

**Comment by dasMulli** [comment]
Btw there have been talks to discourage usage of `-p:PublishSingleFile=True` and `-p:PublishTrimmed=True` and rather pointing users towards creating publish profiles.

**Comment by dasMulli** [comment]
See the discussion on https://github.com/dotnet/cli/issues/12163

by @nguerrera:
> Can you point me to blog posts with -p? I specifically asked to document project file and the posts I saw had that.
>
> I don't want to encourage -p. Self contained is in the same boat and we've had many bugs with it.

**Comment by swaroop-sridhar** [comment]
I think @nguerrera was advocating that we document properties as if they were written in the csproj file, rather than advertising the `-p` syntax -- which I can understand. We still need to document the properties, as accessible from the `dotnet publish` page. So, that's what I'm asking about. 

This also applies to single-exe, ready-to-run and il-trimming.

CC: @fadimounir @sbomer
