### ISSUE TITLE
Default Version for 2.x

### ISSUE THREAD

**Issue by pkg01** [dotnet/docs#13391]
Isn't default version for 2.x is 7.0. I have core Version:   2.2.105 and `csc /langversion:?` shows 7.0 as default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5694e62b-c756-1f62-4014-2ceafa54c011
* Version Independent ID: 3f01c378-22e4-197c-a862-ab4a924506c7
* Content: [C# language versioning - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version)
* Content Source: [docs/csharp/language-reference/configure-language-version.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/configure-language-version.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
What `csc /langversion:?` tells you depends on the csc that's in your PATH. But .Net Core isn't using that, so it does not reflect what's going to be used when you build a .Net Core project.

For example, when I open Developer Command Prompt for VS 2017, `csc /langversion:?` reports 7.0 as default (and 7.3 as latest). But when I run `dotnet new console` and `dotnet run` in that same prompt, it uses C# 8.0 preview, because I have .Net Core 3.0 preview installed. And when I edit the csproj to switch to .Net Core 2.1, it uses C# 7.3 instead.

As far as I can tell, this means that the table is correct.

**Comment by pkg01** [comment]
hmm. so `csc /langversion:?` is not the right way of identifying c# version used by dotnet core.
How did you check that 3.0 is using C# 8.0 and 2.1 is using c# 7.3?

**Comment by svick** [comment]
By attempting to use language features from those versions.

You can also try to print the value of `LangVersion` in csproj, but that doesn't tell you the version directly: for .Net Core 3.0, it's `preview` and for .Net Core 2.0, it's empty, which means "default for the version of the C# compiler used", in this case, 7.3.

Neither of those options is great, so I think your best option is to trust the table. 🙂

**Comment by BillWagner** [comment]
I'm going to close this, as the table is the best information.
