### ISSUE TITLE
[desktop-guide wpf] Doc Package and distribute

### ISSUE THREAD

**Issue by Thraka** [dotnet/docs#13474]
Related to #10649

Doc the following set of articles:

- Windows Presentation Foundation
  - Overview
  - Getting started
  - Migration
  - Fundamentals
  - Working with data
  - Package and distribute
    - [ ] Package your app with MSIX
    - [ ] Publish a library to NuGet
    - [ ] Publish to the Microsoft Store

**Comment by mairaw** [comment]
@Thraka I'm starting to break down tasks from PR #14425 as discussed offline.

I believe this task would be the one for https://review.docs.microsoft.com/en-us/dotnet/core/deploying/desktop-packaging?branch=pr-en-us-14425

However, this article would be applicable to both WPF and WinForms.

So instead of jumping directly to Desktop Guide - WPF, you could have:
- Desktop Guide
  - WPF
  - Package

Or something to that extent. Can you review milestones here and confirm this is indeed the same as that article?

**Comment by Thraka** [comment]
This is the same packaging technology for sure. I wouldn't have the master desktop guide though, as it's just adding a root level (which takes up precious TOC space) without adding much value. I would just share docs across sets.

**Comment by mairaw** [comment]
OK. The other option would be to have this under a new node in .NET Core as well about packaging your app and you can then share in other places.
