### ISSUE TITLE
Roadmap: I need to do X, what do I target?

### ISSUE THREAD

**Issue by cartermp** [dotnet/docs#1359]
This is inspired from this long thread: https://twitter.com/Aaronontheweb/status/812383534744682496

We have a large base of developers who are familiar with .NET Framework, but the new world of .NET might be confusing to them.  They're not beginners in the sense that they do not have a blank slate, but they are likely to be unfamiliar enough with .NET Standard and .NET Core that everything could seem confusing, especially if they haven't been following the team's efforts closely for the past two years.

I think a lot of that confusion can be solved by a document that boils down to "I need to do `X`, what do I use and what do I target so I can get it done?".  This particular kind of document is missing from our documentation.  We have some documentation on porting from .NET Framework (which is likely outdated again), and we have some material for absolute beginners, but we don't have a good set of guidance for 'tweeners who know their way around .NET Framework and their own code, but don't quite have the full picture for how their code is supposed to move forward in the new ecosystem.

I propose a roadmap for as many useful scenarios as we think are reasonable, pointing people towards parts of the documentation that will be helpful for that scenario.  This may be most appropriate in the `index.md` file of the [.NET Platform Guide](https://docs.microsoft.com/en-us/dotnet/articles/standard/)(which needs to be rewritten anyways), or it could be another article under that TOC.

Thoughts?

**Comment by BillWagner** [comment]
This is a great observation. Let's start with a list of potential scenarios for "I need to do `X`".

1. Build a new library that runs on all supported .NET platforms.
2. Update an existing Windows only .NET library to run on all platforms.
3. Update a UWP library to a library that depends only on .NET Standard.
4. Repackage an existing application into libraries so that different apps can be built (Xamarin, UWP, Web, console...) Many of those libraries should depend only on standard, but some might be windows specific.

There's another whole axis of this question that relates to how to deliver libraries for each of these scenarios as NuGet packages.

I'm sure there are more. What other scenarios do people have?

**Comment by cartermp** [comment]
That's a good list.  I'll add "I need to run my server app cross-platform".  I think that we can break it up into four sections:

1. New to .NET
2. Familiar with the .NET Framework, but new to .NET Core and .NET Standard
3. Familiar with Xamarin, but new to .NET Core and .NET Standard
4. Familiar with the .NET Framework, Xamarin, .NET Core, and .NET Standard

Each can have subsections. that include your set and the one I mentioned.  I'll let this simmer a bit and write up a quick first draft.

**Comment by cartermp** [comment]
I took a slightly different approach in my PR.
