### ISSUE TITLE
Documentation efficiency improvement

### ISSUE THREAD

**Issue by jsgopalan** [dotnet/docs#13624]
Highlighting the default value of NetFx40_PInvokeStackResilience is going to be a great help.
Eg. Please mention what would be the default value if we do not specify this element in App.Config?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e039b4c-bfc3-a39b-a701-bba1d1379bdd
* Version Independent ID: afbf79c7-0e75-66d6-c35e-190c31a1e03a
* Content: [&lt;NetFx40_PInvokeStackResilience&gt; Element](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/netfx40-pinvokestackresilience-element#feedback)
* Content Source: [docs/framework/configure-apps/file-schema/runtime/netfx40-pinvokestackresilience-element.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/runtime/netfx40-pinvokestackresilience-element.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for your feedback, @jsgopalan.  The documentation indicates that 0 is the default value of \<NetFx40_PInvokeStackResilience>; that value defines the default behavior if the element is not set in the configuration file. 
I'll going to close this issue, since the documentation specifies the default value.
