### ISSUE TITLE
Net Framework?

### ISSUE THREAD

**Issue by Lechus** [dotnet/docs#13637]
Can we use it within a .NET Framework project or .Net Core only?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e2fd1ea-abfe-ada0-ce7b-1d7f50819c18
* Version Independent ID: 4d918f89-02f2-dbf6-a701-c2efe9eb9a7d
* Content: [Consume a .NET Standard library in Visual Studio 2017 - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/consuming-library-with-visual-studio?tabs=csharp)
* Content Source: [docs/core/tutorials/consuming-library-with-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/consuming-library-with-visual-studio.md)
* Product: **dotnet-core**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Hello!

You can use up to .NET Standard 2.0 in .NET Framework. .NET Standard 2.1 does not support .NET Framework. For more information, see the compatibility table on https://docs.microsoft.com/dotnet/standard/net-standard however .NET Standard 2.1 is still in preview and is not included on that table.

I'm going to close this issue. If your problem is not solved, feel free to reopen or comment. Thanks!
