### ISSUE TITLE
[Code Gallery] Migrate Simple Calculator MEF Application

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#13733]
## [Code Gallery] Migrate Simple Calculator MEF Application

**Sample URL**

https://code.msdn.microsoft.com/windowsdesktop/Simple-Calculator-MEF-1152654e

**Sample information**

38,931 downloads, with 5.0 rating (6 reviewers)

**Usage (in GitHub repos)**

-    docs\framework\mef\index.md

**Comment by rskar-git** [comment]
Hi @rpetrusha,

I have a working migration of this in VB and would be happy to contribute it. Before attempting to get this on git-hub, I need some clarifications.

(1) Is this directory hierarchy (with files as shown) OK?:

    samples/mef/simple-calculator/vb/
        readme.md
        SimpleCalculator2.sln
    	
        ExtendedOperations/
            ExtendedOperations.vbproj
            Modulo.vb
            
        MefCalculator/
            MefCalculator.vbproj
            MefCalculatorInterfaces.vb
            
        SimpleCalculator2/
            Program.vb
            README.txt
            SimpleCalculator2.vbproj
            
            My Project/
                app.manifest

(2) Is this readme.md header correct?:

    ---
    languages:
    - vb
    products:
    - dotnet-core
    - windows
    page_type: sample
    name: "MEF Sample: Simple Calculator"
    urlFragment: "simple-calculator-vb"
    description: "A .NET Core console application that contains the example method from Simple Calculator MEF Application in Visual Basic."
    ---

(3a) The original (pre-migration) code consists of a solution with two projects, with the DLL project (ExtendedOperations) making reference to the EXE project (SimpleCalculator2). That is allowable in .NET Framework; however to make this a .NET Core console application, I had to create an intermediary DLL project (MefCalculator). This is because (as I found out, the hard way :) ) a .NET Standard DLL cannot make reference to a .NET Core EXE. I guess I'm volunteering this now so you could make any follow-up questions or suggestions before the code gets to git-hub.

(3b) In order to make this run seamlessly, in the project files, I had to set OutputPath to "..\bin\Debug\" (or "..\bin\Release\") and make use of setting AppendTargetFrameworkToOutputPath (it is set to false).

Thanks! - Rich

**Comment by rskar-git** [comment]
Hi @rpetrusha, I uploaded the migrated project, and made a pull request, see: https://github.com/dotnet/samples/pull/1773. Let me know if there's anything I can/need to do. Thx!
