### ISSUE TITLE
Does ConfigureAwait(false) make sense for async streams?

### ISSUE THREAD

**Issue by lostmsu** [dotnet/docs#13874]
The examples with `await foreach` do not show if `ConfigureAwait` can be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94537c5-754e-9dea-94a8-7573011f588c
* Version Independent ID: aba09118-22c5-2c6a-954a-b9659a9644ae
* Content: [What's New in C# 8.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#static-local-functions)
* Content Source: [docs/csharp/whats-new/csharp-8.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-8.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a good question @lostmsu 

@stephentoub Do you have guiidance here?

**Comment by stephentoub** [comment]
It does make sense, and it can be used.  But because the underlying tasks returned from MoveNextAsync and DisposeAsync aren't directly available, you employ ConfigureAwait using the ConfigureAwait extension method on `IAsyncEnumerable<T>`:
https://github.com/dotnet/corefx/blob/f9c848d6ad5415c1fa844f5403ea8ef78c408f9a/src/System.Threading.Tasks/ref/System.Threading.Tasks.cs#L78
e.g.
```C#
await foreach (var item in source.ConfigureAwait(false))
{
    ...
}
```
