### ISSUE TITLE
Why do you change the handler lifetime?

### ISSUE THREAD

**Issue by stoksc** [dotnet/docs#13951]
The line in the first code block under the section "Configure a client with Polly’s Retry policy, in Startup" `.SetHandlerLifetime(TimeSpan.FromMinutes(5))  //Set lifetime to five minutes`, I'm not sure why it's needed. If it is, could there be a line explaining why, if not maybe remove it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6f5aecf-ef1c-5a61-de24-894f4f9032c3
* Version Independent ID: 95c81932-26fd-4a24-3b6f-8dd5bde20026
* Content: [Implement HTTP call retries with exponential backoff with Polly](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/implement-http-call-retries-exponential-backoff-polly#feedback)
* Content Source: [docs/architecture/microservices/implement-resilient-applications/implement-http-call-retries-exponential-backoff-polly.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/implement-resilient-applications/implement-http-call-retries-exponential-backoff-polly.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mvelosop** [comment]
Hi @stoksc,

The need for the HttpHandler to have a finite lifetime is to ensure changes in DNS are handled within a "reasonable" time frame.

So, if IP address of a server changes, then the clients (using the "ethernal" HttpHandlers) would not be able to connect again to that server, because they'd be trying to use the old address.

DNS changes on servers occur in failover scenarios as you can read in this interesting discussion: https://github.com/dotnet/corefx/issues/11224 and more specifically in this comment on the same dicussion: https://github.com/dotnet/corefx/issues/11224#issuecomment-270465613.

Anyway, you can get more information related to this in the [Use HttpClientFactory to implement resilient HTTP requests](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests) article in this guide.

So that's why a Lifetime is needed. As for why changing it, as usual, it all depends on the context, so you need to have the option to change it.

Hope this helps.

**Comment by stoksc** [comment]
Thanks for the response. I understand the reason you'd usually need to change it, I was wasn't sure if it was changed for any reason _in this example_. It seemed superfluous to the purpose of the docs so (even though I was pretty sure I already understood lifetime) I just wanted to make sure it wasn't some weird work around to do with using Polly.

Answer helps me understand it better though so thanks!

**Comment by mvelosop** [comment]
Great @stoksc, glad this could help you somehow!

So I'm closing this issue now but feel free to comment, will reopen if needed.

**Comment by OskarKlintrot** [comment]
The default lifetime is 2 min. So, the example code changes the lifetime from 2 min to 5 min. I guess it's because the retry policy might keep trying for more than 2 min? 🤔 The docs doesn't really say why the lifetime is extended by 3 min.

**Comment by StingyJack** [comment]
@mvelosop can you speak to why the default lifetime needs to be increased by 150% ? If @OskarKlintrot  is correct, then two minutes of hitting the wrong address sounds better than 5 minutes of hitting the wrong address.

**Comment by mungojam** [comment]
can this be re-opened. The actual question hasn't been answered and it's just puzzled me in the same way. I think an explanation should be added to the polly section

**Comment by StingyJack** [comment]
@mvelosop I think we are still looking for the reason this is part of the example. 

  https://github.com/dotnet/docs/commit/1b772c48b0f159b0eba0f857d626a2f80e8dee67 added it. @CESARDELATORRE do you know why this is setting a 5 minute timeout?

**Comment by Kilowhisky** [comment]
@OskarKlintrot had it right. 

With 5 max retries at 2^5 backoff that gives 3.5 minutes of straight retires if the http call gets a 30 second timeout.

**Comment by OskarKlintrot** [comment]
@Kilowhisky we understand what it does, where wondering why the lifetime is increased. @StingyJack summerized what were confused about: https://github.com/dotnet/docs/issues/13951#issuecomment-761716532
