### ISSUE TITLE
Guidelines for security administration

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/docs#1397]
_From @PeteX on January 9, 2017 17:46_

When we deploy an application, we also set up a maintenance process for it, because forgotten applications can easily turn into a security risk.  The main thing we're looking at is the application's third party dependencies.  These need to be updated if they have released security patches since our application was written.

The .NET Core documentation is very good on the programming-related aspects of security, for example how to use ASP.NET Core Identity, but it doesn't give any information relating to this kind of maintenance.  Ideally there would be a list of component versions which should no longer be used, because of known security weaknesses that have since been fixed.

I see there has been a security bulletin (aspnet/Announcements/issues/203) and it has been tagged Security.  Is that now a fixed policy, so searching for uses of that tag will turn up all known security issues?  Also presumably aspnet/Announcements is only for the web-related aspects of .NET Core.  Is there something similar for other components?

I imagine this is going to be an issue for lots of companies who are making the change from older versions of .NET.  As I understand it (my background is Linux more than Windows) with older versions, there was a single package rather than multiple components, and fixes would generally be installed automatically by Windows Update.

_Copied from original issue: aspnet/Docs#2486_

**Comment by Rick-Anderson** [comment]
To get you started, see the [.NET Core Support Lifecycle Fact Sheet](https://www.microsoft.com/net/core/support)
cc @richlander

**Comment by PeteX** [comment]
Thanks for the link; that document is a good start.  Is the idea that security exposures in any part of .NET Core will be fixed by a point release of the whole platform?  For example, in aspnet/Announcements/issues/203 a security issue with ASP.NET was fixed as part of the .NET Core 1.0.1 point release.  Can we assume that this will always be the case, rather than you releasing for example Microsoft.AspNetCore.Mvc 1.0.1.1 while the rest of the platform stays on 1.0.1?

If so, thank you, this makes our job much easier than it might be.  It's much more straightforward if we can just look for new releases of .NET Core without worrying about individual components.  Can I suggest that you spell this out in the fact sheet you linked above?

Presumably when the fact sheet says

> Once a patch update has been installed applications will begin using the update by default.

that is only for the runtime.  The packages (like Microsoft.AspNetCore.Mvc) will still pick up the versions in project.lock.json until such time as someone runs 'dotnet restore'.  Even then, if the package versions are specified exactly (1.0.0 rather than 1.0.*) the application will continue using the superseded packages until project.json is updated.

This is all fine, we accept the need for maintenance as the price of putting an application online, but we need to be clear what we're supposed to be checking for.

**Comment by mairaw** [comment]
/cc @richlander @staceyhaffner @leecow 

any thoughts on this?

**Comment by BillWagner** [comment]
This is older, but I think this relates to the topic: https://blogs.msdn.microsoft.com/dotnet/2014/01/22/net-4-5-1-supports-microsoft-security-updates-for-net-nuget-libraries/

**Comment by BillWagner** [comment]
See also #469

**Comment by PeteX** [comment]
The technique described in @BillWagner's link sounds interesting, but we're wanting to deploy on Linux, so that wouldn't help us directly.

Something similar but cross-platform would be very useful, though probably a significant amount of work for you.  For now, it would be fine if we just had instructions about what to check when we do our maintenance.

(If you can make the maintenance process smooth, I can imagine it being a significant selling point for .NET Core.  Maintenance is a nuisance, and if you can reduce the amount of time we have to spend on it, that's a good reason to use your product.)

**Comment by BillWagner** [comment]
@PeteX Thanks for the additional clarification.  We know we need more content here. We're investigating what the right answers are, and once we have the guidance, we'll get this done.

**Comment by blowdart** [comment]
I'm staying out of this, mainly because it's very runtime version specific and an utter mess. But yea, right now it's check the advisorys in the .net and asp.net repos and figure it out. In 3.0 it'll be different again, that'll be "just install the new runtime"

**Comment by IEvangelist** [comment]
Closing: operation clean sweep, dated...
