### ISSUE TITLE
Incorrect examples

### ISSUE THREAD

**Issue by SalFicara** [dotnet/docs#14103]
This statement could be extremely confusing to new comers as it doesn't make sense in the context in which it is used: Logger.WriteMessage += LogToConsole;

It should be: Logger.WriteMessage += Logger.LogToConsole;

Also, In general these examples are confusing and lack essential information in both description and example content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4da25ace-6dcf-3dfa-7b98-c0b29c769e46
* Version Independent ID: f6f03e15-36cb-d7ee-cb99-eee9a5ecc477
* Content: [Common Patterns for Delegates](https://docs.microsoft.com/en-us/dotnet/csharp/delegates-patterns#feedback)
* Content Source: [docs/csharp/delegates-patterns.md](https://github.com/dotnet/docs/blob/master/docs/csharp/delegates-patterns.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for adding this @SalFicara 

We'll make sure to address this when we next update this document.

In the meantime, I've added the "up for grabs" label for any community members to address.

**Comment by nemrism** [comment]
Actually, if you have a closer look to the full sample [here](https://github.com/dotnet/samples/tree/master/csharp/delegates-and-events), the line of code you pointed out is correct.

However I agree with you @SalFicara on the fact that the way it is explained in the article is quite confusing as we can't really understand where the `LogToConsole` method is located in the example program.

**Comment by eddynaka** [comment]
@BillWagner , based on the sample, it looks alright. Is this a bug or not?

**Comment by BillWagner** [comment]
@eddynaka 

The previous comment is correct. The code is correct, but the explanation does not help readers find that information.

**Comment by lucasnobredev** [comment]
@BillWagner so should we change the code or explanation?

**Comment by nemrism** [comment]
As the code is correct, we should rephrase the explanation only

**Comment by SeanKilleen** [comment]
I attempted to address this in two PRs across the docs & the samples.

* I extracted to a static class called `LoggingMethods` so that we could show the full context of the class within the docs sample.
* Updated the docs to show the new class for the contents of the `LogToConsole` method
* Updated the docs to clearly use the static class
* Added a comment to the first time we reference `LoggingMethods` out of context, to remind the reader it's one we created earlier.

Feedback on the overall approach welcome, but this seemed to find the sweet spot of:

* Making a concept explicit
* Allowing the code samples to be shown in the full context
