### ISSUE TITLE
Incomplete example and possible mixup in recommended naming

### ISSUE THREAD

**Issue by AzmL** [dotnet/docs#14142]
Referring to the recommended test suite at the end of this article (GetDiscountedPrice_ByDefault_ReturnsFullPrice and GetDiscountedPrice_OnTuesday_ReturnsHalfPrice).

It would be useful to show how Mock&lt;T&gt; is implemented, notably the code behind the .Setup() method.

Also, at the beginning of this article you explain a Mock is a Fake that becomes a Mock when it is used to validate the test. Here you do not use IDateTimeProvider to validate the test, so to me this remains a Stub, yet the object used to instantiate this Stub is called Mock..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51947dc8-9ae8-21fa-13db-a7ffb3f9bc0e
* Version Independent ID: be661bf5-6f6e-cd18-344b-253edf5751ae
* Content: [Best practices for writing unit tests - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices)
* Content Source: [docs/core/testing/unit-testing-best-practices.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-best-practices.md)
* Product: **dotnet-core**
* GitHub Login: @jpreese
* Microsoft Alias: **wiwagn**

**Comment by jpreese** [comment]
Thanks for the feedback, @AzmL 

Here are my thoughts!

> It would be useful to show how Mock<T> is implemented, notably the code behind the .Setup() method.

Are you asking for a bit more explanation on what `.Setup()` is doing? 

I don't want to get into the internals of what is going on in this document, but I could see value in explaining that calling `.Setup()` on the `IDateTimeProvider` with a `.Returns()` of `DayOfWeek.Tuesday` effectively means that when we call `dateTimeProvider.DayOfWeek()` in the code under test, the result will _always_ be the day that we passed in. In this case Tuesday.

This lets us force a day of Tuesday in our test, regardless of what day it really is.

> Also, at the beginning of this article you explain a Mock is a Fake that becomes a Mock when it is used to validate the test. Here you do not use IDateTimeProvider to validate the test, so to me this remains a Stub, yet the object used to instantiate this Stub is called Mock..

This is an unfortunate choice of wording by the testing library authors. In this document, the tests leverage [Moq](https://github.com/Moq/moq4/wiki/Quickstart) to handle any of our faking needs. In the Moq library, they implement a class called `Mock` that will let you configure how you want the interface to behave.

In this case, because we're setting the value to `DayOfWeek.Tuesday` and asserting against the result of `GetDiscountedPrice`, not the `dateTimeProviderStub` (which is just passed into the method), it really is a stub.

**Comment by AzmL** [comment]
Hi jpreese, and thanks for coming back to me.
I believe the passing of a delegate to .Setup() makes obvious what is conceptually happening behind the scene. What I was really interested in was the source code which allows that mechanism: does .Setup().Return() use reflection to instantiate an object which implements the interface T passed during "New Mock<T>"?
I now understand the tests rely on a third party library, which is probably why it does not show the implementation I was hoping to get to see. It would be helpful to mention the reliance of this library somewhere in the article.

**Comment by Thraka** [comment]
@jpreese I'm going to classify this as a doc-enhancement issue. Can you assign it a priority and add the milestone (backlog doesn't work, use the `backlog` label instead)?

**Comment by Thraka** [comment]
@jpreese Ha! I thought you had repo perms to do issue management stuff, I'll do it 😅
