### ISSUE TITLE
Broken link on .NET landing page

### ISSUE THREAD

**Issue by natke** [dotnet/docs#14279]
This link on the landing page is broken. We need to replace it with something sensible:

https://docs.microsoft.com/en-us/dotnet/machine-learning/resources

**Comment by mairaw** [comment]
You mean hub page?

Usually when we removed the index page of certain folders because of the TOC accessibility pages, we redirected those to the first entry in the TOC.

Because right now is URL path is not "hackable" - meaning you can't walk backwards on URLs such as https://docs.microsoft.com/en-us/dotnet/machine-learning/resources/ml-net-cli-telemetry.

Also, because you mentioned landing page, I noticed that one of your URLs was unnecessarily being redirected, so created #14322 to fix that.

**Comment by mairaw** [comment]
Also, this Resources link is used in the breadcrumb and is broken as well:
https://docs.microsoft.com/en-us/dotnet/machine-learning/resources/metrics

![image](https://user-images.githubusercontent.com/12971179/64644966-b380e680-d3c8-11e9-8ec2-75b381a8e4e9.png)

**Comment by natke** [comment]
Thank you @mairaw It's interesting that these pages get extremely low traffic (at least in our case anyway).
