### ISSUE TITLE
The rounding description for float remainder is incorrect

### ISSUE THREAD

**Issue by KoziLord** [dotnet/docs#14292]
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#remainder-operator

The article mentions that N is "the largest possible integer that is less than or equal to X / y" (Floor)
However the actual rounding applied during the calculation seems to be rounding to 0 and NOT towards -Infinity

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e783650c-e063-e268-316e-564362cb1e37
* Version Independent ID: aa9f4996-cab4-0bed-6452-213342453785
* Content: [Expressions - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#feedback)
* Content Source: [spec/expressions.md](https://github.com/dotnet/csharplang/blob/master/spec/expressions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
`x and y are positive finite values. z is the result of x % y and is computed as x - n * y, where n is the largest possible integer that is less than or equal to x / y.`

The previous is the paragraph you're speaking about, where x and y are floats. and it seems correct to me.

Let's take an example where `x = 5.3` and `y = 7.9`
`x / y` = 0.67 (approx.)
n is the largest possible int less than or equal to x / y, so n is zero.
then x % y is computed as `x - n * y`, and that is equals to `x` (`5.3`) because `n` is zero.
Evaluating `5.3 % 7.9` on C# compiler results in `5.3`


Another example where `x = 16.3` and `y = 2.8`.
`x / y` = 5.82 (approx.)
n is 5
`x % y` = `x - n * y` = `16.3 - 5 * 2.8` = `2.3`
And that is what I see when I evaluate on a C# compiler.

I maybe missing something, Can you give an example where you don't get the expected result ?

**Comment by KoziLord** [comment]
This works fine with positive numbers, it breaks with negative numbers however
Example:
-10.4 % 2 == -0.4
`n = Floor(-10.4 / 2)`
`n = Floor(-5.2)`
`n = -6`
`-10.4 - (-6 * 2)`
`-10.4 + 12`
`1.6`

**Comment by pkulikov** [comment]
@KoziLord 

> This works fine with positive numbers...

The [linked spec](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#remainder-operator) states that as well (emphasis mine):

> In the table, x and y are **positive finite values**. z is the result of x % y and is computed as x - n * y, where n is the largest possible integer that is less than or equal to x / y.

**Comment by KoziLord** [comment]
Right, however there isn't any specification about how negative values behave, I think changing it from
>In the table, x and y are positive finite values. z is the result of x % y and is computed as x - n * y, where n is the largest possible integer that is less than or equal to x / y.

to something like:
>In the table, x and y are finite values. z is the result of x % y and is computed as x - n * y, where n is a truncated integer of x / y.

**Comment by pkulikov** [comment]
The table after the paragraph shows how negative and non-finite values are treated.

**Comment by BillWagner** [comment]
As @pkulikov and others have mentioned, the description is correct.

I'll close this as the docs are accurate.
