### ISSUE TITLE
missing guidance on null guards

### ISSUE THREAD

**Issue by bitbonk** [dotnet/docs#14491]
There has been some discussion and misunderstanding on whether or not application and/or library developers now can remove any null guards (e.g. `if(input != null){...}`, `ArgumentNullException`) because of this feature. See for example [here](https://stackoverflow.com/questions/54526652/when-to-null-check-arguments-with-nullable-reference-types-enabled) and [here](https://devblogs.microsoft.com/dotnet/try-out-nullable-reference-types/#comment-3122). The documentation needs clear guidance if or if not (and if so, when) it is now safe to remove null guards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bea1e2ab-5517-b17c-4a65-7c7bae09261a
* Version Independent ID: 2a326631-709b-4461-6c15-a75a5087ef1d
* Content: [Nullable reference types in C# - C# 8.0 language proposals](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/nullable-reference-types#feedback)
* Content Source: [proposals/csharp-8.0/nullable-reference-types.md](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/nullable-reference-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @bitbonk 

The reference [guidance for corefx](https://github.com/dotnet/corefx/blob/master/Documentation/api-guidelines/nullability.md) is a good start. However, as we add more annotations to different APIs in corefx, we're continuing to learn the best way forward. We're not comfortable saying "we know the answers" yet. 

I've not assigned this a milestone, because we're not confident enough of the current guidance to recommend it universally. However, I've adding a high priority label because we agree it's important.

**Comment by bitbonk** [comment]
@IEvangelist  Can you clarify why this was closed? Where can I see the updated docs for this?

**Comment by BillWagner** [comment]
@bitbonk The PR was merged today. It will be published overnight, on our regular publishing cycle.

If you can't wait, the source is [here](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/nullable-reference-types.md#null-guard-guidance) on GitHub.

**Comment by IEvangelist** [comment]
Sorry, @bitbonk -- I should have commented with an explanation. I'll be sure to make that a part of my standard workflow from now on. Thanks for keeping me honest 👍
