### ISSUE TITLE
Clean up the CI document

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/docs#1454]

**Comment by wallymathieugarantibil** [comment]
[I wrote about](http://assertfail.gewalli.se/2017/01/29/Running-dotnet-core-11-on-appveyor-and-travis.html) the experience trying to get stuff running on travis with .net 1.1. 
It would be nice if we could have some accessible documentation about what the different preview versions for instance:
1.0.0-preview2.1-003177
1.0.0-preview2.1-003155
et.c. maps to. Or is this due to the fact that the current version is not really released?

**Comment by drewnoakes** [comment]
+1. Getting CI to work with AppVeyor on Windows is fine, but setting up Travis CI to build and test a .NET Core project seems impossible. I've tried so many combinations of configurations.

**Comment by wallymathieugarantibil** [comment]
I've gotten it to work for project json. It could be that you need to specify a later version of ubuntu.
