### ISSUE TITLE
Create a document that outlines the mapping of significant concepts between project.json and csproj

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/docs#1456]

**Comment by mairaw** [comment]
Let's work on the outline for this one so we can be on the same page of what's expected:
- We can use what @natemcmaster has written in his blog post to see a before and after the migration:
http://www.natemcmaster.com/blog/2017/01/19/project-json-to-csproj/
- I think we also need a "reference" topic explaining all the different elements you can use for .NET Core projects, what they mean and default values (on a similar fashion to this: https://docs.microsoft.com/en-us/nuget/schema/nuget-config-file as @peterblazejewicz pointed out) since those will not be covered in the MSBuild docs

**Comment by blackdwarf** [comment]
@mairaw for sure, @natemcmaster has created a great doc for this so we will use it. We already have a `csproj` reference in the works as part of the RC3 docs, so that needs to be updated.
