### ISSUE TITLE
Associativity of +=

### ISSUE THREAD

**Issue by sizenineelm** [dotnet/docs#14597]
It is worth noting that x += y may not be equivalent to x = x + y if y is an expression.

x = x + a + b will be evaluated as x = (x + a) + b (left associative +, left associative +)
x += a + b will be evaluated as x = x + (a + b) (left associative +, right associative +=)

This is of more significance if x is a type defining an overloaded operator+.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e31f06e-936e-d0c7-9dc0-9d10fd8a0dd9
* Version Independent ID: 43899711-a922-8180-25e6-d52af245846d
* Content: [+ and += operators - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/addition-operator#feedback)
* Content Source: [docs/csharp/language-reference/operators/addition-operator.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/addition-operator.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@sizenineelm it might look as an associativity issue. However, it's not that because the operators in question have different precedence levels. The assignment operators have its own, and the lowest, precedence level. That's why, given `x += a + b`, `a + b` is evaluated first because the `+` operator has higher precedence than the `+=` operator. After that, `+=` is evaluated with the results from the previous step.

And the operator precedence is presented on the operator overview page:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/#operator-precedence

> It is worth noting that x += y may not be equivalent to x = x + y if y is an expression.

Not sure if that's should be noted here. In general, a lot of articles use some form of `x op y` examples and usually that implicitly means that, even if `x` and `y` are expressions, their *results* are used.

**Comment by BillWagner** [comment]
This is an interesting discussion

After checking the pertinent section of the [C# specification](https://docs.microsoft.com/dotnet/csharp/language-reference/language-specification/expressions#compound-assignment), I think @pkulikov 's analysis is correct. The paragraph that starts "The term 'evaluated only once' means..." has the details on the order of evaluation.

@sizenineelm I'm going to close this issue, because I believe the explanation is correct. If you have an example that demonstrates different behavior, can you add that and re-open the issue?

**Comment by sizenineelm** [comment]
No problem. The explanation that it’s operator precedence rather than associativity makes sense – although the underlying issue of x = x + y not necessarily being the same as x += y with y as an expression still stands – x += y is more equivalent to x = x + (y).
