### ISSUE TITLE
Obsolete event

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#14599]
The code snippet under the `To call an event handler using AddHandler` title uses an obsolete event. I can fix this but not sure of the correct steps to do that, as the updates will be in both the samples and the docs repo.
If any of them is updated first, the article and the code would be mismatching at a point of time, is that okay to happen and they will just reconcile shortly after the other is merged? Or there is a better way in doing such changes ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 768a4cc5-d734-2ee4-f853-5cc5e510f06d
* Version Independent ID: 891620e5-6d3f-d730-a69e-c0206cae1020
* Content: [How to: Call an Event Handler in Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/procedures/how-to-call-an-event-handler#to-call-an-event-handler-using-addhandler)
* Content Source: [docs/visual-basic/programming-guide/language-features/procedures/how-to-call-an-event-handler.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/language-features/procedures/how-to-call-an-event-handler.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by rpetrusha** [comment]
What is the obsolete event, @Youssef1313. I don't see Form.Closing as obsolete.

Whether Form.Closing is obsolete or not, though, the example is not a good one, since it doesn't actually indicate what `formOpened` is or how it's invoked. So if you want to replace or improve the example, that would be great.
The best thing to do in changing the example is:
1. Create a new example and open a PR in the dotnet/samples repo.
2. Create a PR in dotnet/docs that consumes the example. Note that it depends on the PR in samples, and we'll label it as **Hold for related PR**.  
3. When the samples PR is merged, we'll close and reopen the PR in docs to begin a new build.
4. When the build succeeds, we'll merge the PR in docs.
5. Once the change is made in docs, you can open a PR to delete the original example, assuming that it isn't used somewhere else in the documentation.
 
Assuming that you'd like to replace the example, I'll assign this issue to you.

**Comment by Youssef1313** [comment]
![Screenshot_2019-09-24-07-35-27-579_com android chrome](https://user-images.githubusercontent.com/31348972/65483853-f7cab700-de9d-11e9-8e10-f3bbdef761e5.png)
