### ISSUE TITLE
Is there a rationale for porting existing WPF or Forms apps to .Net Core 3?

### ISSUE THREAD

**Issue by perl80903** [dotnet/docs#14917]
Since both of these UI technologies are only supported on Windows, where the traditional .Net framework is also supported, what's the rationale for porting such apps to .Net Core today?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e9a211f-0161-1e0c-a1e3-d4460fc4ec2b
* Version Independent ID: ef286ce7-d314-1aa1-7184-6f51efb5bfaf
* Content: [Migrating WPF Apps to .NET Core 3.0 - .NET Desktop](https://docs.microsoft.com/en-us/dotnet/desktop-wpf/migration/convert-project-from-net-framework#feedback)
* Content Source: [docs/desktop-wpf/migration/convert-project-from-net-framework.md](https://github.com/dotnet/docs/blob/master/docs/desktop-wpf/migration/convert-project-from-net-framework.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-wpf**
* GitHub Login: @mjrousos
* Microsoft Alias: **mikerou**

**Comment by Thraka** [comment]
Greetings!

That is a valid question. I think one that was in the old porting article and it should be addressed in this one too. I'm going to leave this issue open to track updating the article.

The reason is that new features and innovations for .NET are in the .NET Core stack (well [.NET 5 as of next year](https://devblogs.microsoft.com/dotnet/introducing-net-5/)). .NET Core has a lot of advantages over .NET Framework, even if your app is Windows-only. WPF for .NET Core is based on an [open source port of WPF](https://github.com/dotnet/wpf). So bug fixes and features will be on this code base going forward. This isn't part of .NET Framework.

An excerpt from [.NET Core is the Future of .NET ](https://devblogs.microsoft.com/dotnet/net-core-is-the-future-of-net/) blog post:

>With the .NET Core 3.0 release in September 2019 we think that all \*new* .NET applications should be based on .NET Core.
...
The primary application types from .NET Framework are supported, and where we did not port something over there is a recommended modern replacement. All future investment in .NET will be in .NET Core.
...
.NET Framework 4.8 will be the last major version of .NET Framework. If you have existing .NET Framework applications that you are maintaining, there is no need to move these applications to .NET Core. We will continue to both service and support .NET Framework

**Comment by canol** [comment]
One benefit I can think of is that .Net Core has a higher chance of supporting ARM64 Windows compared to .Net Framework, so a WPF app might natively support Windows on ARM in the future if it is ported to .Net Core. But I cannot see an ARM64 Windows package to download currently, so I don't know whether it is in their roadmap to support ARM64 Windows in the future.

**Comment by Thraka** [comment]
@canol I think that may be a better question for https://github.com/dotnet/coreclr 😄 Anyway, I'm going to close this issue since the original author hasn't responded, I'm assuming the question is answered.
