### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by vtoderica** [dotnet/docs#14983]
...
 EventTypeFilter configFilter = (EventTypeFilter)mySource.Listeners["console"].Filter;
...

Shouldn't "console" be replaced to "Default"? 
(I run on .net framework 4.6.1)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b06dc20-83e4-08e0-814d-15cd7dbcb96d
* Version Independent ID: 94734b9b-4f89-1fa3-9248-dfe2bfc61cc5
* Content: [How to: Create and Initialize Trace Sources](https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/how-to-create-and-initialize-trace-sources#feedback)
* Content Source: [docs/framework/debug-trace-profile/how-to-create-and-initialize-trace-sources.md](https://github.com/dotnet/docs/blob/master/docs/framework/debug-trace-profile/how-to-create-and-initialize-trace-sources.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by vtoderica** [comment]
Please ignore my previous remark.

**Comment by Thraka** [comment]
@vtoderica Not sure if you mean that we should ignore the title you changed or ignore this issue completely? If the latter, you can close the issue.

To answer your question though, no it shouldn't be named that. Steps 1-3 are supposed to be completed before you run the program. Step 3 creates the listener named **console** that Step 1 references.

I'll close this issue as I think your problem is solved. Thanks.

**Comment by vtoderica** [comment]
Thank you for your answer. I was wrong, but I realized that after I posted
the remark. Thank you !

lun., 7 oct. 2019, 20:53 Andy De George <notifications@github.com> a scris:
