### ISSUE TITLE
About tmpfs mounts

### ISSUE THREAD

**Issue by JiChao99** [dotnet/docs#15018]
on the page top，tmpfs mounts is one solution  for manage persistent data
&gt; The following solutions are used to manage persistent data in Docker applications:

but on the detail  description
&gt; tmpfs mounts ... are only meant for non-persistent data.

So, tmpfs mounts is not the manage persistent data solution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbe659da-9470-ce94-3c05-e635c6bbbaf5
* Version Independent ID: 25fd6c27-9c56-42fc-3ba2-b833e6116938
* Content: [State and data in Docker applications](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/architect-microservice-container-applications/docker-application-state-data#feedback)
* Content Source: [docs/architecture/microservices/architect-microservice-container-applications/docker-application-state-data.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/architect-microservice-container-applications/docker-application-state-data.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mvelosop** [comment]
Hi @JiChao99, thanks for your feedback!

That's right **tmpfs mounts** are not suitable to persist data, because the live in memory and are never written to disk, so there's really not much "persistance" there!

Of course there are situations where that could make sense, but the article has to be rephrased, because it's a bit confusing. 

Thanks for the heads up!
