### ISSUE TITLE
Mistake in the example of negative lookahead assertion

### ISSUE THREAD

**Issue by Konard** [dotnet/docs#15075]
In the table there is example of look-ahead:
`Zero-width negative lookahead assertion.`
`\b(?!un)\w+\b`

But this is not used as look-ahead, this is used as look-behind, the look-ahead usage will be like this: `\b\w+(?!un)\b`.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16d4698e-4220-c422-a554-8a481803d240
* Version Independent ID: f0e3b82a-8d81-ad9e-97fc-efb92f7d0d38
* Content: [Regular Expression Language - Quick Reference](https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference#feedback)
* Content Source: [docs/standard/base-types/regular-expression-language-quick-reference.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/regular-expression-language-quick-reference.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
Hello,

I think this is correct. It is a lookahead because the word boundary is the starting expression followed by the negative lookahead. So it starts from the beginning of the word and looks ahead for the match of `un` keeping the engine at the position of the word boundary start. If you modify it to check for `s` after the word boundary start, you'll see it works as expected matching the only word it can:

`\b(?!un)s\w+\b`

matches

![image](https://user-images.githubusercontent.com/2672110/66585755-45048500-eb3c-11e9-89c0-6af03dba2f22.png)

I'm going to close this issue.
