### ISSUE TITLE
Setting environment using dotnet publish commane

### ISSUE THREAD

**Issue by RaminMT** [dotnet/docs#15087]
Hi
I have a couple of questions:
1. Is it possible to set environment when publishing with `dotnet publish` like `dotnet publish --environment "Development"` or no? if yes how? 
2. Is it possible to ignore project warnings when publishing with `dotnet publish`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 211afdc7-c796-202d-239d-823f2a499dff
* Version Independent ID: 9439897e-dcb3-bc2e-5cae-35c1ca2e0681
* Content: [dotnet publish command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-publish.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-publish.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by RaminMT** [comment]
Hi again
Excuse me for not being enough clear.
By the term **environment** I mean `ASPNETCORE_ENVIRONMENT` environment variable or generally any environment variable.
And I know that warnings are not prevent the build or publish process but I want them to be hide so I can get more concentrated info

**Comment by Thraka** [comment]
No worries!

To hide the warnings, try passing this switch to MSBuild (which is what the `dotnet publish` command uses)

```
/p:WarningLevel=0
```

Environment variable, no. Since environment variables are consumed by your app but set by the host, you need to configure the host some how. For example, if you're going to deploy to the cloud, the cloud provider usually has an option to set the environment variables for your app. If you're deploying to someone's machine, you might want to supply as startup script for them to run. You can have your app detect the value of that variable and then output an error if it's not what you're expecting.

I think your questions are answered. I'm going to close this issue. Thanks!

**Comment by johngrayuk** [comment]
In case anyone arrives here looking to transform their web.config via dotnet publish, you can do this with (for example):

dotnet publish -o site /p:EnvironmentName=Staging

Adds the following to your web.config in the publish directory:

<environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Staging" />

**Comment by SergeyToff** [comment]
> I use `dotnet publish -configuration release /p:EnvironmentName=Staging ` but see that environment still `Production`. Can anyone help?

that becouse this command add only <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Staging" />

but if you read https://learn.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-9.0#environments sometimes DOTNET_ENVIRONMENT value overrides ASPNETCORE_ENVIRONMENT.

Can we use some commands for add DOTNET_ENVIRONMENT  ?
