### ISSUE TITLE
Indice/Range for yielded/async sequences

### ISSUE THREAD

**Issue by Countryen** [dotnet/docs#15137]
Hey there, quick question: Is it possible to use the new indices/ranges with async or yielded sequences?
Is there a way to do that? Since both features are new here, would be nice if it was mentioned here, too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94537c5-754e-9dea-94a8-7573011f588c
* Version Independent ID: aba09118-22c5-2c6a-954a-b9659a9644ae
* Content: [What's new in C# 8.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8?utm_source=csharpdigest&utm_medium=web&utm_campaign=featured)
* Content Source: [docs/csharp/whats-new/csharp-8.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-8.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
Not really, since an index or a range can be from the end and those can't be efficiently supported for a general `IEnumerable<T>` or `IAsyncEnumerable<T>`.

Though if you want, you can write something like that yourself, e.g.:

```c#
public static IEnumerable<T> Slice<T>(this IEnumerable<T> source, Range range)
{
    if (range.Start.IsFromEnd || range.End.IsFromEnd)
        throw new ArgumentException("Ranges with 'from end' indices are not supported.", nameof(range));

    var start = range.Start.Value;
    var end = range.End.Value;

    return source.Skip(start).Take(end - start);
}
```

And then use it like this:

```c#
enumerable.Slice(1..5)
```

You could also write a similar extension method for `IAsyncEnumerable<T>`, to make that easier, you could use [System.Linq.Async](https://www.fuget.org/packages/System.Linq.Async/4.0.0/lib/netstandard2.1/System.Linq.Async.dll/System.Linq/AsyncEnumerable).

**Comment by Countryen** [comment]
Thanks @svick, I didn't register that yet the indices/ranges not work on IEnumerable<T>.
Thanks also for the suggested Extension.
