### ISSUE TITLE
Link between 'Quick JIT (tier 0 jitted code)' and Tiered Compilation unclear

### ISSUE THREAD

**Issue by mungojam** [dotnet/docs#15143]
It says that in dot net core 3.0 tiered compilation is enabled by default and then explains the benefits of it. Then, out of the blue, it says how to enable 'Quick JIT (tier 0 jitted code)' without explaining if that is the same thing as tiered compilation or some extra improvement, nor any guidance on when we would want to enable it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d458030b-3efb-197f-6ac7-9fd4e2296218
* Version Independent ID: 6d01409e-fca6-10a3-2def-13ce28c9b210
* Content: [What's new in .NET Core 3.0](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#feedback)
* Content Source: [docs/core/whats-new/dotnet-core-3-0.md](https://github.com/dotnet/docs/blob/master/docs/core/whats-new/dotnet-core-3-0.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by mairaw** [comment]
Thanks for your feedback @mungojam. @richlander is this something you can help with?

**Comment by springy76** [comment]
I've reread this section again in again and it comes to no sense. And how does TieredCompilationQuickJit relate to R2R? Can it be combined? Is it mutally exclusive? Anyone knows anything?

**Comment by Thraka** [comment]
Sending email to @richlander

**Comment by kouvel** [comment]
I have put up a PR to clarify the doc: https://github.com/dotnet/docs/pull/15708

Quick JIT produces lower-quality code more quickly, and is enabled by default in .NET Core 3.0 for methods that don't contain loops. It's typically used during startup when the method also does not have R2R code available and has to be jitted, these are typically generics over value types, for example `List<Foo>` where `Foo` is a struct in an app assembly.

**Comment by richlander** [comment]
Hi! Great question!

The short story is this:

- tiered compilation has two tiers, tier 0 and tier 1.
- tier 0 is fast for startup but has slower throughout. Tier 1 is the opposite.
- with tiered compilation enabled (the default in 3.0), the runtime prefers tier 0 code at startup and then converts high value code to tier 1 later for faster throughout. That is the whole feature in a nutshell.
- tier 0 code can be provided in two different ways: native pre-compiled code in assemblies (via crossgen) or via quick jit.
- tier 1 code is optimized jitted code.
- both tier 1 and tier 0 jitted code is provided by RyuJIT.
- quickjit is very similar to the “minopts” mode that has existed in the runtime for many years. “Minopts” means minimum optimization. So, it is code that is very fast to generate but isn’t very good because it is lacking optimizations. For probably 80% of scenarios, quickjit is A-OK fine, because most code is only run once.
- the name “quickjit” was made up in 3.0 (blame me) to describe it as something as other than “tier 0 jit”.
- in some niche scenarios, quickjit is poor for performance and so you can disable it. That would mean that the only tier 0 code is crossgen and the rest of your code will be all tier 1. The tier 0 code can still be recompiled to tier 1 while your app runs.
- quickjit has a second one to “run with loops”. By default, we don’t use quickjit for methods with loops. We found multiple applications where quickjit code was a performance problem for methods with loops so we disabled it by default. Imagine a method that is only called once but has a loop with 10k iterations. You want the best code you can get for that. 
- we found a set of applications where quickjit with loops is a big win so you can opt into that mode. We didn’t make this the default because there were too many apps that had worse performance running this way.

**Comment by kouvel** [comment]
Just to clarify, Quick JIT was not enabled for loops for two main reasons:

**Comment by kouvel** [comment]
We didn't see any apps behave poorly due to enabling Quick JIT for loops. Most of what we saw was issues in benchmarks. There are more fundamental issues there though, and the choice made I believe was the right one.
