### ISSUE TITLE
Multiple dotnet test runs produce error

### ISSUE THREAD

**Issue by geronimus** [dotnet/docs#15450]
You might mention that you have to call `dotnet clean $testProjPath` ( - where *$testProjPath* is a variable containing the path to the test `*.csproj` file - ) between each subsequent call to `dotnet test $testProjPath`.

Otherwise, the user will get an error: `error CS0579: Duplicate ‘System.Reflection.AssemblyCompanyAttribute’ attribute`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b54562-9072-a864-be3d-44ed7965c798
* Version Independent ID: a69ec985-ed05-90dd-a686-dc956b0cf5df
* Content: [Organizing and testing projects with the .NET Core command line - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/testing-with-cli#feedback)
* Content Source: [docs/core/tutorials/testing-with-cli.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/testing-with-cli.md)
* Product: **dotnet-core**
* GitHub Login: @cartermp
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
@geronimus Hello.

I don't think this is correct. Generally that error is present because you have two things declaring that attribute. Usually this happens when you port a .NET Framework project (which stores these attributes in the *AssemblyInfo.cs* file) to the SDK project-style (which automatically generates these attributes for you)

Can you elaborate on your problem?
