### ISSUE TITLE
Why there's no Domain Service?

### ISSUE THREAD

**Issue by crclz** [dotnet/docs#15462]
**This is a rough idea.** My opinion may be wrong.

In my opition, one domain event MUST be in one single transaction, because an event is something happened in the past. To raise an OrderStartedDomainEvent, you should make sure the order aggregate has been persisted in the database. If the data has not been persisted in the database, some sub-events which attempt to get order aggregate from database will get `null`.

Secondly, can I say that the side effects which are supposed to be triggered by domain event MUST not have atomicity with the original action which raise the event? In a project, if (operation, side-effect) requires atomicity, I think this probably indicates a `Domain Service` (mentioned in Eric Evan's DDD book) should be used, which can perform transactions across several aggregates. I didn't see any Domain Service in this ebook, which confuses me.

For example. If a buyer placed an order, an email should be sent to he/she. The failure of sending the email should not be considered, because the success of placing an order has nothing to do with the state of the email. Under this situation, a `Domain Event` should be used.
But placing an order requires checking for the remaining amount of some items, under this situation, a `Domain Service` should be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d432d5bb-24a7-3bec-1e17-910c8129226e
* Version Independent ID: e41af96d-f015-a8e0-4449-7a508d7bccc8
* Content: [Domain events. design and implementation](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/domain-events-design-implementation)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/domain-events-design-implementation.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/domain-events-design-implementation.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by crclz** [comment]
@mvelosop I was viewing https://github.com/dotnet-architecture/eShopOnContainers/issues/721 and https://github.com/dotnet-architecture/eShopOnContainers/issues/700 and realized the problem may be the lack of domain service. Can you help me?

**Comment by mvelosop** [comment]
Hi @crclz, thanks for your feedback.

I don't quite get to see it that way.

Whether several related domain events must be in different or a single transaction is usually context specific, so, as usual, it depends, no golden rules here. 

Different transactions, and hence, eventual consistency, with the need to handle compensating action adds a lot of complexity that wasn't deemed necessary here.

The idea of domain services is to handle processes that don't naturally correspond to an aggregate or domain model, but are part of the domain.

In this case, however, I see the handlers are coordinating an action between two aggregates, `Order` and `Buyer`, which is the typical the role of Application Services and that's where Domain Event Handlers fit in, so every seems OK here.

So, I don't think the use of a domain service would solve the atomicity issue here, which was a design decision, because the processes we are talking about are at the application services level, implemented using message handlers with MediatR.

The fact that there are no domain services here, is just because this a simplified model that only implemented a few features.

Hope this helps.
