### ISSUE TITLE
Column to Predict (Label) dropdown cannot scroll down

### ISSUE THREAD

**Issue by todarko** [dotnet/docs#15474]
VS 2019 ASP.NET Core 3.0
ML.NET Model Builder extension 

When loading columns you cannot select a few if you have lots of columns that overflow the space viewable by the dropdown. Can't scroll, tab, or use arrow keys to move down the list.

![image](https://user-images.githubusercontent.com/41561202/67713781-be490800-f983-11e9-9017-f2b033f61151.png)

**Comment by luisquintanilla** [comment]
Hi @todarko,

Sorry to hear you're experiencing this issue. This has already been raised in the model builder repo and the team is currently working on fixing the issue. 

Issue Link: dotnet/machinelearning-modelbuilder#252

I suggest you follow the discussion there. Because this is not a documentation related question, in the future, please raise questions/ issues in the [dotnet/machinelearning-modelbuilder repo](https://github.com/dotnet/machinelearning-modelbuilder).
