### ISSUE TITLE
Install the .NET Framework for developers

### ISSUE THREAD

**Issue by walbourn** [dotnet/docs#15562]
The page *Install the .NET Framework for developers* is missing notes about VS 2017 (and it's updates) and VS 2019 related to which developer pack is supported by which version of VS. There is also missing notes about VS 2015 Update 2.

Visual Studio|.NET version
-- | --
VS 2019 (16.3) | .NET Framework 4.8   .NET Core 3.0
VS 2017 (15.8   update) | .NET Framework   4.7.2
VS 2017 (15.5   update) | .NET Framework   4.7.1
VS 2017 (15.3   update) | .NET Framework 4.7   .NET Core 2.0
VS 2015 Update 3 | .NET Framework   4.6.1   .NET Core 1.0
VS 2015 Update 2 | .NET Framework   4.6.1
VS 2015 (RTM) | .NET Framework 4.6
VS 2013 | .NET Framework   4.5.1
VS 2012 | .NET Framework 4.5

edit by @mairaw: added topic details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf46f86d-940f-3d1b-a83c-6ced0ead20bb
* Version Independent ID: 56305860-d431-de58-1503-cdf57e4814b5
* Content: [Install the .NET Framework developer pack or redistributable](https://docs.microsoft.com/en-us/dotnet/framework/install/guide-for-developers)
* Content Source: [docs/framework/install/guide-for-developers.md](https://github.com/dotnet/docs/blob/master/docs/framework/install/guide-for-developers.md)
* Product: **dotnet-framework**
* Technology: **dotnet-install**
* GitHub Login: @Thraka
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
We do cover that information for .NET Core under https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore30#prerequisites-to-develop-net-core-apps-with-visual-studio since you can't develop with certain versions of .NET Core if you're not on the right version of VS.

But not sure if I understand what this would mean for .NET Framework. /cc @vivmishra 

I can develop 4.8 apps in VS 2017, for example:
![image](https://user-images.githubusercontent.com/12971179/67907910-d614bd80-fb36-11e9-80b7-beca89e0a8f8.png)

**Comment by Thraka** [comment]
Looks like .NET 4.6 is the last to mention what Visual Studio version included it. I think this is an update worth making.

![image](https://user-images.githubusercontent.com/2672110/68058049-1c902680-fcb5-11e9-8e66-262669cc1d4a.png)

**Comment by gewarren** [comment]
This is similar to #9196. It's a little strange that we have this info in two separate articles.

**Comment by Thraka** [comment]
@gewarren I think there are three locations actually. Some have more visual studio stuff, but other than that the supported OS for each framework is repeated over and over.
