### ISSUE TITLE
Incorporate VBLang and C# Lang specs in Markdown

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#1561]
Our current docs describe how to download the C# and VB Language specifications:

See /docs/csharp/language-reference/language-specification.md and /docs/visual-basic/reference/language-specification.md

The language teams have published those specifications in the new language repositories:
[C# Specification in Markdown](https://github.com/dotnet/csharplang/tree/master/spec)
[VB Specification in Markdown](https://github.com/dotnet/vblang/tree/master/spec)

Instead of directing customers to download the earlier versions of the specifications, we should incorporate the updated markdown versions into our current documents at [Microsoft Docs](http://docs.microsoft.com).

There are a number of constraints to consider before we publish the specs. 

1. The specifications will be regularly updated for new language features. However, customers will want to see the version of the language that corresponds to their environment. For example, the current markdown versions are C# 6 and VB 11. As the specifications are updated for C# 7, VB 12, and beyond, customers will still need to reference earlier versions in addition to the latest versions.
1. The sections should be numbered as hyper-linked, as in the current versions.
1. The grammar sections need to support antlr syntax for validation.
1. Ideally, it would be best to incorporate the markdown source directly from the csharplang and vblang repositories as part of the build process. This will facilitate customer feedback and pull requests for any specification issues discovered in the field.
1. We need to trigger a build of the doc set when the language specifications (in the different repositories) have been updated.

There will also be concerns and decisions that are specific to each language. For that, I've opened sub-issues for each language:

- [x] Publish VB Spec in Markdown #1562
- [x] Publish C# Spec in Markdown #1563

/cc @AnthonyDGreen @madstorgersen @stevehoag @scottdorman

**Comment by scottdorman** [comment]
> Instead of directing customers to download the earlier versions of the specifications, we should incorporate the updated markdown versions into our current documents at Microsoft Docs.

Yes, I think the downloaded (offline) versions should be considered deprecated/out of date.

As for the constraints listed:

1. Yes, developers are going to want to see the specification for a given language version and be able to move freely between them.  I think some of this discussion is also in https://github.com/dotnet/csharplang/issues/64.
2. What benefit would numbering the sections provide? This seems problematic to me since there is no auto-number mechanism like there is in Word. If we insert a new section in between two existing sections, everything afterwards has to be manually renumbered.
3. I think all of the grammar should be done using antlr. This is something that @ljw1004 did when he was working with me on the initial porting of the VB spec to markdown.
4. Yes, yes, and yes! :) Being able to pull the markdown directly from the source repos is important to keep them up to date.
5. Should this trigger be automatic? Wouldn't we want this to only happen when a new "official" version of the spec is released?

**Comment by ljw1004** [comment]
ANTLR: What I did was (1) have a separate standalone ANTLR file for the entire grammar, (2) copy+paste segments into the grammar sections of the spec.

It was useful to have the grammar in a single file since that let me use common ANTLR tools while authoring it, to detect errors. I did detect a few errors. The most errors were in the newly minted spec (e.g. string interpolation). On the one hand this was still a draft spec so it's not surprising there were errors. On the other hand I discovered it is IMPOSSIBLE to author a correct grammar for a new language feature without tool assistance. In the old parts of the spec, I think there were oddities like something that was defined more than once in the body of the C# grammar, and I think maybe also something that was defined only in the grammar-appendix.

It'd be possible to auto-generate the single ANTLR file out of all the grammar blocks in the spec. That would lead to an unwieldy edit process, but I think that edits to the grammar are pretty infrequent so it wouldn't matter.

What I did instead was have a tool that validates that the grammar blocks in the spec and the grammar in the standalone file were in 1:1 correspondence. This was also a bit unwieldy.

I spent time "modernizing" the grammar. The VB and C# spec were both written in an idiosyncratic subset of BNF that didn't use basic operators like ? (zero-or-one), + (one-or-more), * (zero-or-more). I refactored the spec to use these, and it streamlined it. This refactoring process would have been impossible without ANTLR tooling support.

**Comment by scottdorman** [comment]
> The VB and C# spec were both written in an idiosyncratic subset of BNF that didn't use basic operators like ? (zero-or-one), + (one-or-more), * (zero-or-more). 

I think this is important and, going forward, the grammars should be written using just standard syntax. Yes, I think converting the grammars to proper BNF form so tools like antlr can work with them is a pain, but it's a one-time thing. Once it's properly converted, and only new language features are being added it's not as painful.

**Comment by BillWagner** [comment]
> What benefit would numbering the sections provide? This seems problematic to me since there is no auto-number mechanism like there is in Word. If we insert a new section in between two existing sections, everything afterwards has to be manually renumbered.

The ECMA spec uses numbered sections, so it would be a benefit to generate the same format. I would like to see this done with extensions to markdown that enabled the numbering. /cc @eisenbergeffect

>I think all of the grammar should be done using antlr. This is something that @ljw1004 did when he was working with me on the initial porting of the VB spec to markdown.

Yes. Thanks @ljw1004 for all the details above. Our current build processes enables us to include lines from code samples. That could be extended to antlr. 

>Should this trigger be automatic? Wouldn't we want this to only happen when a new "official" version of the spec is released?

We could trigger updates based on a branch label. I agree that we only want to release when there is something official, but I do want to avoid lots of manual tasks.

**Comment by EisenbergEffect** [comment]
@BillWagner Can you send me email regarding the extension feature request? I *think* I understand what you need but I'm not feeling 100% confident. I'm happy to work with you to nail down the details and put together a spec. Thanks!

**Comment by svick** [comment]
> For example, the current markdown versions are C# 6 and VB 11. As the specifications are updated for C# 7, VB 12, and beyond, customers will still need to reference earlier versions in addition to the latest versions.

I think GitHub branches (or tags) in spec repos should work fine for that.

@scottdorman 

> What benefit would numbering the sections provide?

When I reference the spec, I like to use both section numbers and section names. Section numbers are useful, because section names are not always unique. For example, the C# 4.0 spec (which I keep using, because the HTML version is most convenient for me) has 4 different sections named *Attributes*:

* §1.12 Attributes
* §10.2.1 Attributes
* §17. Attributes
* §B.2.13 Attributes

**Comment by BillWagner** [comment]
Closing this as the subtasks are now done. Thanks to @ljw1004 and @scottdorman for all the work to make this happen.
