### ISSUE TITLE
Sample of marshaling techniques

### ISSUE THREAD

**Issue by shvez** [dotnet/docs#15702]
It would be good to get any references on marshaling techniques for netcore. I'm facing an issue with code which worked fine in .net framework and does not work in .net core. It would be very useful to understand how marshaling can be used in case of type conversion issues

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c83628c-7002-9045-9c72-f8d97b784eb0
* Version Independent ID: a761a83d-5aa8-958a-d210-6eb8f7929ff2
* Content: [Understanding AssemblyLoadContext - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/understanding-assemblyloadcontext#feedback)
* Content Source: [docs/core/dependency-loading/understanding-assemblyloadcontext.md](https://github.com/dotnet/docs/blob/master/docs/core/dependency-loading/understanding-assemblyloadcontext.md)
* Product: **dotnet-core**
* GitHub Login: @sdmaclea
* Microsoft Alias: **stmaclea**

**Comment by jeffschwMSFT** [comment]
@shvez can you provide a bit more detail on what scenario you are trying to have work on .NET Core?  Can you share a repro?  We have a variety of documented scenarios with samples in interop.

**Comment by shvez** [comment]
@jeffschwMSFT 
so, we have a test assembly that depends on some production assemblies. That production code uses statics. in .netframework code we have created app domain and then using domain.CreateInstanceAndUnwrap(type.Assembly.FullName, type.FullName); we have created some type and could use its methods using class derived from MarshalByRef. Like this:
```
public abstract class ApplicationBase : MarshalByRefObject
```
Everything was working fine.

Now in dotnet core I do not have app domains. So, I'm using LoadContexts to load production code to different app context. I need this to keep statics working. and in result I get type conversion issue exactly like described in the documentation. The idea of common type usage does not really work for us. I thought that may be there some unknown tricks with marshaling in .netcore that could help me

**Comment by jeffschwMSFT** [comment]
Thanks for those details.  You are correct that we do not have this area well documented.  The management of separate AssemblyLoadContexts is more complex than Appdomains, but the static isolation, etc. should work in a similar way.  Do you mind sharing the same of your Appdomain code and we can offer some suggestions on how to move to ALCs?

cc @vitek-karas @elinor-fung

**Comment by shvez** [comment]
I'll do that tomorrow. that is a lot of work

**Comment by shvez** [comment]
@jeffschwMSFT I'll do that tomorrow. I have to admit that is a lot of work

**Comment by shvez** [comment]
@jeffschwMSFT here is an example of what we are doing. Of course,  it is very simplified.  But I hope it will give a clue.

[TypeMarshaling.zip](https://github.com/dotnet/docs/files/3813814/TypeMarshaling.zip)

**Comment by elinor-fung** [comment]
As you pointed out the common types do not work for you, another way to achieve this is through reflection. The general idea in that sample would be:
- Load `BaseApp.dll` in the default ALC
- Load each `ProdApp*.dll` in its own ALC
- Call `BaseApp` methods directly
- Call `ProdApp*` methods through reflection

Something like:
``` C#
string pathToProdAppAssembly = "...";
string prodAppTypeName = "...";
AssemblyLoadContext alc = new AssemblyLoadContext(name);
Assembly asm = alc.LoadFromAssemblyPath(pathToProdAppAssembly);
Type t = asm.GetType(prodAppTypeName);

BaseApp.BaseApp app1 = (BaseApp.BaseApp)Activator.CreateInstance(t);
app1.AbstracMethod();

string prodAppMethodName = "...";
MethodInfo method = app1.GetType().GetMethod(prodAppMethodName);
method.Invoke(app1, new object[0]);
```

Using common shared types in a shared assembly is generally the more streamlined way of handling the type conversion problems. So that we can better understand different migration scenarios and hopefully provide more guidance/recommendations for similar situations, would you also be able to tell us what mainly blocks that from being an option for you?

**Comment by shvez** [comment]
@elinor-fung 
well, the main issue with type sharing is static members in BaseApp. It is in the sample but I did not add it usage.
Also from your sample, it is not clear how do you share the `BaseApp` type. As is your code will not work. It will fail in this line `BaseApp.BaseApp app1 = (BaseApp.BaseApp)Activator.CreateInstance(t);` during type casting

**Comment by elinor-fung** [comment]
Ah, I missed that the statics that need to be isolated are actually in `BaseApp`. In that case, you wouldn't want `BaseApp` to be shared either.

In the previously posted sample, `BaseApp` is shared since - as you said - the base implementation of `AssemblyLoadContext.Load` returns null, such loading falls back to the default context. The `ProdApp*` assembly is in its own context as it is explicitly loaded by path through `LoadFromAssemblyPath` (no fallback to the default context) so it will be loaded in that ALC instance and not the default. With that, the `ProdApp*` type (in the non-default ALC instance) inherits from the `BaseApp` type (in the default ALC), so the cast to `BaseApp` (default ALC) works (casting to `ProdApp*` type from the default ALC would fail).

Yes, sharing through the default load context by returning null from a custom ALC is the common pattern. An alternative to returning null is to explicitly load/return the assembly from the specific ALC used for sharing (e.g. returning `AssemblyLoadContext.Default.Load...` for shared assemblies) in your overridden implementation of `AssemblyLoadContext.Load`. It is also possible to use a non-default ALC instance for sharing (by returning assemblies from that other ALC instance), but using the default is the recommended way.

That said, since the base `BaseApp` has statics that should not be shared, it should not actually be shared from the default ALC.

If all the assemblies you need to load/isolate (e.g. `BaseApp` and `ProdApp*`) are under a known path, your ALC could look like:
``` C#
internal class ProdAppLoadContext : AssemblyLoadContext
{
    private string rootPath;
    public ProdAppLoadContext(string name, string rootPath) : base(name)
    {
        this.rootPath = rootPath;
    }

    protected override Assembly Load(AssemblyName assemblyName)
    {
        string assemblyPath = Path.Combine(rootPath, $"{assemblyName.Name}.dll");
        return File.Exists(assemblyPath) ? LoadFromAssemblyPath(assemblyPath) : null;
    }
}
```
And its usage something like:
``` C#
ProdAppLoadContext alc = new ProdAppLoadContext("app1", TestContext.CurrentContext.TestDirectory);
Assembly asm = alc.LoadFromAssemblyName(new AssemblyName("ProdApp1"));
Type t = asm.GetType("ProdApp1.ProdApp1");

object app = Activator.CreateInstance(t);
MethodInfo method = app1.GetType().GetMethod("ProdApp1Method");
method.Invoke(app1, new object[0]);
```
Another possibility would be to use the `dynamic` keyword (basically reflection but without writing the code to directly use reflection APIs). Modified your sample to use both ways: [TypeMarshaling.zip](https://github.com/dotnet/docs/files/3821615/TypeMarshaling.zip)


If you need some resolution in your ALC more complicated than having a known root path under which the assemblies reside, the [`AssemblyDependencyResolver`](https://docs.microsoft.com/dotnet/api/system.runtime.loader.assemblydependencyresolver) could be of use. This is could be pretty similar to the [plugin](https://docs.microsoft.com/dotnet/core/tutorials/creating-app-with-plugin-support) scenario, with the difference being that the base type should not be shared (so the paragraph about making sure the base is shared would not be relevant).

**Comment by shvez** [comment]
thank you for the detailed answer. although nothing is clear about marshaling, I managed to extract assembly with shared types and it seems started to work

**Comment by vitek-karas** [comment]
.NET Core doesn't have anything like marshaling between load contexts. Typically communication between load contexts is done through shared types. This has the advantage that the calls are very fast - in fact there's no penalty calling between load contexts (because load contexts are only considered when loading assemblies, one loaded - everything is "equal").

The disadvantage is that the communication has to be explicit - that is the app must define the shared types for communication. They can't be "implied" the way .NET Framework did it with transparent proxies.

So this leaves several options:
* Add "Artificial" interfaces to the code, so that the interfaces can be shared and used for communication. This is the most common solution if the code is to be truly ported over to .NET Core.
* Use reflection to call into the assemblies in other load contexts - this is not a bad solution if the communication is limited - like loading something and making a single call on it.
* Use reflection and dynamic - this just makes writing reflection easier, so might be handy for more chatty communication. The downside is a complete loss of type-safety - compiler will not fail on wrong method names, params and so on - everything happens at runtime.
* Build a custom solution for proxies - there is a basis of this in .NET Core in the form of [DispatchProxy](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.dispatchproxy?view=netcore-3.0). You can use this to create a proxy and implement the calls using reflection or something similar. In reality this also more or less requires introduction of interfaces - but it doesn't enforce perfect match (the consumer may have a slightly different view of the world from the producer) - this is probably the closest one can get to transparent proxies from .NET Framework.

There's really no solution for "marshalling" true classes across (not interfaces) - The functionality necessary for that was in the .NET Framework runtime (it's very hard if not impossible to do this in C#) and was not carried over to .NET Core.

**Comment by shvez** [comment]
@vitek-karas thank you

So, it is probably better to remove marshaling from that doc page.
Also I have to say that in my case I'm not able to completely rewrite code to use shared interfaces because we currently forced to support both netframework and netcore versions. And that creates a lot of difficulties especially with the support of old-style configuration

**Comment by sdmaclea** [comment]
> So, it is probably better to remove marshaling from that doc page.

Marshalling seems to be a poor word choice on my part. We probably need a polished summary this discussion in the doc.

**Comment by vitek-karas** [comment]
Just maybe forgot to clarify for code which needs to support both .NET Framework and .NET Core:
* To create an instance of a type in the isolation AppDomain/AssemblyLoadContext the code for each platform is different. This is basically not possible to share really.
* Once created the communication can be done in a consistent way for both platforms if the objects implement interfaces. On .NET Framework the interfaces don't have to be explicitly shared (the runtime will automagically share them, or proxy the calls between them). On .NET Core these have to be explicitly shared. But once that it setup - all calls across the isolation boundary are just normal interface calls and thus the code can be exactly the same for both platforms.

So even if you have special requirements around statics and instantiation, those should not complicate the matters too much, as the code for .NET Framework and .NET Core for creation must be separate anyway. Adding interfaces to the classes should not typically be a big problem for either platform - but I obviously didn't try this in your code base, so I can't comment on the complexity of such task.

**Comment by shvez** [comment]
@vitek-karas that what I kind of realized. So, I managed to extract interfaces to an extra assembly that is shared now. this part is working fine. 
the only show stopper for me is the support of legacy configs. Probably It worth it to create a separate issue for that issue. at least I will get more understanding

thank you guys for help

**Comment by vitek-karas** [comment]
Would be interested in what legacy configs issues you run into... but I agree it's better done in a separate issue
