### ISSUE TITLE
Formatting arguments of function declarations and function calls

### ISSUE THREAD

**Issue by nojaf** [dotnet/docs#15755]
Hello, regarding https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#surround-function-arguments-with-white-space

Could some additional samples be provided in this area?
What would the recommended way be to format a single unit argument in a function signature.

F.ex
```fsharp
let myFunction () = // ...
```

or

```fsharp
let myFunction() = //...
```

And how about calling that function?
Should it be 

```fsharp
let meh = myFunction()
```

or 

```fsharp
let meh = myFunction ()
```

And what answer would apply to function calls on objects?

```fsharp
meh.ToString()
```

or 

```fsharp
meh.ToString ()
```

Related issues: https://github.com/fsprojects/fantomas/issues/554, https://github.com/fsprojects/fantomas/issues/555, https://github.com/fsprojects/fantomas/issues/552

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c09996f-24ac-cf39-ef43-d7909cbc2b89
* Version Independent ID: 1efdd523-8552-6421-e149-74f76826ef8f
* Content: [F# code formatting guidelines](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#feedback)
* Content Source: [docs/fsharp/style-guide/formatting.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/style-guide/formatting.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by smoothdeveloper** [comment]
@nojaf, I authored the section you are refering to.

I personally have those preferences: 

* method calls have their parens touching the member name, the same way as indexed properties and due to the fact they aren't succeptible to partial application, this also make the OO code closer to C# defaults, exception is single argument method call where the parens are droped but a space is then required
* function calls always have a space, that make their usage with or without parens around parameters look consistent and it cues the possibility of partial application

```fsharp
// OK
let r = r.ToString()
// Bad
let r = r.ToString ()
```

```fsharp
// OK
let r = sprintf ("ok %i") 1
// Bad
let r = sprintf("bad %i")(1)
```

@cartermp if those defaults / explanations are acceptable as part of the formatting guidelines, I can submit a PR to incorporate it into the document.

**Comment by cartermp** [comment]
@smoothdeveloper I think those are the right formatting defaults and a good explanation. Would happily accept a PR!

**Comment by knocte** [comment]
I'd love to understand why it's important to differentiate between a function call and a method call?

As for me, I constantly refactor my code to have less methods and more functions, and I wouldn't want the callers to have to be modified every time this happens.

To me, this differentiation sounds a bit like those coding-style guidelines that recommend camelCase or PascalCase depending on the visibility of the method. Then, whenever the visibility changes, all callers need to change, causing a lot of line damage. I only see downsides on this approach, not any advantages. I genuinely want to know the advantages I'm not seeing. Thanks
