### ISSUE TITLE
foreach on large datasets

### ISSUE THREAD

**Issue by PeriHartman** [dotnet/docs#15759]
The implication from the above description is that foreach first invokes IEnumerable to build an ordered array. What if your dataset has 10,000 elements ? That would be a horribly inefficient way to implement an iterator. Surely there's a better way. (P.S. I'm new to C#)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8ba3a4c-1796-84b8-4152-b9806483ce86
* Version Independent ID: bd878489-9a4c-6d99-6c4c-c56e0387012b
* Content: [Iterators](https://docs.microsoft.com/en-us/dotnet/csharp/iterators#feedback)
* Content Source: [docs/csharp/iterators.md](https://github.com/dotnet/docs/blob/master/docs/csharp/iterators.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
@PeriHartman Hello. I'm unsure which description you are specifically referring to, but it is possible it **could** be inefficient. The `yield return` solves this problem. For example:

```csharp
public IEnumerable<int> GetSingleDigitNumbers()
{
    yield return 0;
    yield return 1;
    yield return 2;
    yield return 3;
    yield return 4;
    yield return 5;
    yield return 6;
    yield return 7;
    yield return 8;
    yield return 9;
}
```

This code gives you the enumerator used by the foreach. That dataset though isn't fully populated into the enumerator. Each time the foreach loops, the next `yield` statement is processed, returning the value and essentially freezing the internal code of the enumerable until the next is requested.

In general, large large datasets are somewhere, they may be in memory, they may not, but the enumerator is only pointing at one piece of the dataset, it doesn't need to pull in everything at once, provided it's constructed properly. For example take

```csharp
public IEnumerable<int> GetDataSetItems()
{
    var dataset = new int[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
    List<int> results = new List<int>();

    foreach (var item in dataset)
        results.Add(item);

    return results;
}
```

Pretend that the dataset is on a server somewhere and is 10000s of items. The method is processing each item and building the result set BEFORE returning the results. So in here the problem lies in the fact that the internals of this enumerable is processing every item first. If an outside `for` loop is calling `GetDataSetItems`, the logical flow of code is this:

```
START FOR loop
FOR calls GetDataSetItems() to get an enumerator
    GetDataSetItems() starts own FOR loop to gather items to return
    Loops 10 times getting all items
    Returns all 10 items in an enumerator
FOR loop processes 1 item
FOR loop gets next item in enumerator
FOR loop finishes.
```

To build it efficiently, your enumerable would instead pass back each item individually

```csharp
public IEnumerable<int> GetDataSetItems()
{
    var dataset = new int[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
    List<int> results = new List<int>();

    foreach (var item in dataset)
        yield return item;
}
```

In this example the `yield return item` passes back an individual item, freezing the state of the method as it returns. The logic flow is now better:

```
START FOR loop
FOR calls GetDataSetItems() to get an enumerator
    GetDataSetItems() starts own FOR loop to gather items to return
    1 item is returned
FOR loop processes 1 item
FOR loop gets next item in enumerator
    GetDataSetItems() is called again by the enumerator
    1 item is returned
FOR loop finishes.
```

I hope this clarifies things. I'm going to close this issue but feel free to comment. Cheers!
