### ISSUE TITLE
If the problem is the HttpMessageHandler, why not make it more clear?

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/docs#15879]
&gt; This factory assigns the `HttpClient` an `HttpMessageHandler` from a pool it manages.

Then the `HttpClient` can be disposed, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b506236-b211-eb9d-b571-5efecdde76c8
* Version Independent ID: 24434b0e-0b82-e477-9440-2cc8f135df75
* Content: [Use HttpClientFactory to implement resilient HTTP requests](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests)
* Content Source: [docs/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mvelosop** [comment]
Hi @paulomorgado, thanks for your feedback. That's an interesting observation!

Taking a look at the source code for both [HttpClient](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpClient.cs/) and its base class [HttpMessageInvoker](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpMessageInvoker.cs/) you can see that there's an overload for HttpClient that allows disposing it, without affecting an externally managed HttpMessageHandler.

I didn't check the DefaultHttpClientFactory source, but that's almost for sure the overload used.

So you're right, it's OK to dispose an HttpClient that was instantiated by the DefaultHttpClientFactory, because it won't exhaust the available sockets (associated with the HttpMessageHandler).

Actually the HttpClient IS disposed, at the end of the request DI scope, because it implements IDisposable.

What do you think would be good to add to the article to make it more clear?

Hope this helps.

**Comment by paulomorgado** [comment]
It would be good to add an explanation of what usually makes it bad to dispose of an `HttpClient` and how the `DefaultHttpClientFactory` solves it. Probably say that it's what's expected from any implementation of `IHttpClientFactory`

**Comment by mvelosop** [comment]
Hi @paulomorgado,

I would've thought that the first two sections, namely:

- [Issues with the original HttpClient class available in .NET Core](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net-core) and
- [What is HttpClientFactory](https://docs.microsoft.com/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#what-is-httpclientfactory)

Contain just that you're suggesting, what do you think is missing there?

Thanks.

**Comment by paulomorgado** [comment]
@mvelosop, please point me to where it is mentioned that the issue is with the `HttpMessageHandler` and not with the `HttpClient` and where it is mentioned that you can/should dispose of the `HttpClient` returned by the factory.

**Comment by mvelosop** [comment]
Fair enough @paulomorgado, you're right, that's explained in the linked pages, but not here.

Will include those points in the article!
