### ISSUE TITLE
System.Threading.Thread.Abort changes

### ISSUE THREAD

**Issue by Symbai** [dotnet/docs#15878]
A note about System.Threading.Thread.Abort is missing. On .NET Core it throws a "System.PlatformNotSupportedException: Thread abort is not supported on this platform." exception, while on .NET Framework it does not.

What is the equivalent on .NET Core for Thread.Abort ?!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0f19516-254e-d701-1cd3-d2cf4ddac6e5
* Version Independent ID: dc951b71-083e-6127-99a6-e1278ce8c044
* Content: [Breaking changes, .NET Framework to .NET Core 3.0 - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/compatibility/framework-core)
* Content Source: [docs/core/compatibility/framework-core.md](https://github.com/dotnet/docs/blob/master/docs/core/compatibility/framework-core.md)
* Product: **dotnet-core**
* GitHub Login: @gewarren
* Microsoft Alias: **mairaw**

**Comment by gewarren** [comment]
[Cancellation tokens](https://docs.microsoft.com/dotnet/api/system.threading.cancellationtoken?view=netframework-4.8) are a less drastic way to cancel a thread.

**Comment by gewarren** [comment]
@PriyaPurkayastha Should this be added as a breaking change?

**Comment by PriyaPurkayastha** [comment]
@gewarren we will figure out next steps once I get some information back about existing documentation for .NET Core releases prior to .NET Core 3.0.

**Comment by gewarren** [comment]
Related issue: https://github.com/dotnet/corefx/issues/35229

**Comment by PhilipHassialis** [comment]
Is there any recent development on this? Thread.Abort() can still be typed without any kind of intellisense from the editor that it is obsolete (.NET Core 3.1 here). Souldn't the Abort becoming obsolete and/or moving out of .Net Core be mentioned in the documentation?

**Comment by gewarren** [comment]
@PhilipHassialis The .NET Core behavior is mentioned in the API documentation [here](https://docs.microsoft.com/en-us/dotnet/api/system.threading.thread.abort?view=netframework-4.8#System_Threading_Thread_Abort), but I don't think this surfaces in IntelliSense. We also have a new page in the works that lists all APIs that throw PlatformNotSupportedException on .NET Core.

**Comment by PhilipHassialis** [comment]
Thank you so much for the prompt reply, unfortunately most of the courses/tutorials/etc out there do not adhere to Core and keep on mentioning stuff that is already deprecated. Imho, a little mention of "this doesn't work in Core" in intellisense would be a godsend - along with an immediate mention in the title of the page or in the first paragraph of the documentation that directly indicates that a method/API will not work in Core. 

As a bonus, the documentation team could have separate pages that instead of having an example would simply mention that "....this method is deprecated and is supported only in Framework and not in Core", no examples, nothing the user can copy paste to their IDE only to see it fail, only the exceptions and a "do not use obsolete APIs" warning.

Once again, thanks so much for responding, happy new year and a million apologies for my rushed questioning.
