### ISSUE TITLE
Visual Studio Mac

### ISSUE THREAD

**Issue by cguerin** [dotnet/docs#15897]
On Mac, I get "Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA". 

Anyway to get a CPU neutral version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ca0a402-fa67-fbd4-4cbc-604b4b59c97c
* Version Independent ID: c8a996eb-82ed-a4bd-94d8-ef0b32158c67
* Content: [Tutorial: Generate an ML.NET image classification model from a pre-trained TensorFlow model - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification#feedback)
* Content Source: [docs/machine-learning/tutorials/image-classification.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/image-classification.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by luisquintanilla** [comment]
Hi @cguerin ,

Thank you for your question. This is just a warning and should not have an impact on your ability to train a model. It's a message that appears cross-platform, not just Mac, and to my understanding has to do with how the TensorFlow binaries are built by default. Here's a somewhat related discussion on the issue that may provide context. 

tensorflow/tensorflow#8037

From an ML.NET standpoint, it uses TensorFlow via TensorFlow.NET, a .NET library that provides bindings for TensorFlow.  Since this is not a documentation issue, I would suggest raising further questions on the official [TensorFlow repo](https://github.com/tensorflow/tensorflow) or [TensorFlow.NET repo](https://github.com/SciSharp/TensorFlow.NET) for questions related to TensorFlow.NET. If you have product questions/issues on ML.NET, the best place to raise them is the [ML.NET repo](https://github.com/dotnet/machinelearning).
