### ISSUE TITLE
Example out of sync with text in Memory and Span usage guidelines article

### ISSUE THREAD

**Issue by maziarrezaei** [dotnet/docs#15934]
At least for the first example, it seems it's not relevant to the explanation that goes after it.  There is no Span&lt;T&gt; in the code, and no Clear() method is called.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4819512e-1044-1c57-0de1-447164220fd5
* Version Independent ID: d6cf8d26-fb2f-7138-f0c7-ab529a5b9cde
* Content: [Memory&lt;T&gt; and Span&lt;T&gt; usage guidelines](https://docs.microsoft.com/en-us/dotnet/standard/memory-and-spans/memory-t-usage-guidelines#feedback)
* Content Source: [docs/standard/memory-and-spans/memory-t-usage-guidelines.md](https://github.com/dotnet/docs/blob/master/docs/standard/memory-and-spans/memory-t-usage-guidelines.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **dotnetcontent**

**Comment by tdykstra** [comment]
@maziarrezaei Thanks for pointing that out.  The problem was already pointed out by @svick in the PR that created the article ([here](https://github.com/dotnet/docs/pull/8055#discussion_r224223716) and [here](https://github.com/dotnet/docs/pull/8055#discussion_r224224342)), but those comments somehow were overlooked. I'm labeling this as a doc bug and we'll correct it as soon as resources are available to work on it.
