### ISSUE TITLE
Error with early open keyword in Get Started with F# in Visual Studio Code

### ISSUE THREAD

**Issue by pkeir** [dotnet/docs#16049]
In the "Get Started with F# in Visual Studio Code" article, the use of `namespace ClassLibraryDemo`, "below the open System declaration" causes `System` to be red-underlined, along with the problem: "Only '#' compiler directives may occur prior to the first 'namespace' declaration F# Compiler (530)".

Is there an error in the tutorial, or perhaps my setup is wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b07eeb2-d274-35da-78d4-b7d78c255590
* Version Independent ID: bf145620-7f23-eb4d-376d-f739562d9a79
* Content: [Get Started with F# in Visual Studio Code](https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/get-started-vscode)
* Content Source: [docs/fsharp/get-started/get-started-vscode.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/get-started/get-started-vscode.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by spavett** [comment]
Nothing wrong with your setup @pkeir. This example fails because whoever added it to the page didn't run it like they suggest you do! I'm a newbie and here on my holiday having a first look at F# and got the same issue but you can see from the error and a quick Google that the namespace is (probably) irrelevant at this stage of just running a first f# cmd line app built from a single file of F#. Not even sure the module is necessary - the example can be made to work without that also. Take out the namespace declaration and you should be good to go.

Namespacing is no doubt important to using F# for a real project but you can worry about that if you get beyond this page. I suspect that the last edit date of this page (12/23/2018) says something about how popular F# was in 2019. Its that time of year again and your comment was only three weeks ago...

Merry Christmas!

**Comment by GoodGuyGregory** [comment]
@spavett **Thanks a bunch** Had the same errors! 🚀
