### ISSUE TITLE
Last index is... ^1???

### ISSUE THREAD

**Issue by WrongBit** [dotnet/docs#16067]
Every programming child knows - array elements start from index 0.
If you "reverse" your view and stay at the end of array, your first element is... right - at index 0! So what is that clown who decide that "^1" is a good index for the last element???
"^" is the sign: count elements from end, not from start. Nothing more. If you cannot understand it, never introduce such features!

**Comment by BillWagner** [comment]
This was discussed and debated in the C# language design meetings for months. There are valid arguments for ^0 and ^1 being the last element. The samples in [this article](https://docs.microsoft.com/dotnet/csharp/tutorials/ranges-indexes) explain the reason for the chosen behavior.

Closing as product question, and answered.

**Comment by WrongBit** [comment]
I see no any correspondence between "arr.Length" and "^" symbol. ESPECIALLY when you use it with indexes: "arr.Length5" - sorry WHAT is that? (it's long form of your "^5")
Adequate people look at "^" sign as "count from other side of array". So I stay at the last element and using "^0" I "shift" on 0 elements and take one.

a[0] - first element. a[^0] - last element. Logical as 2x2=4. What mind you had when accepting those "^1"?

**Comment by CyrusNajmabadi** [comment]
> Adequate people look at "^" sign as "count from other side of array". S

That's correct.  `^` is the 'other side' of the array.  So if you index into the other side, you index out of bounds as would be expected.  To get the last element, you don't want "the other side", you want "the other side, minus 1", or `^1`.

We considered both approaches, and took a look at what code what doing in many different repos that could benefit from ranges/indices.  It turned out for the  vast majority of them, this indexing approach turned out to be better (versus one where `^0` was the last element).

Based on the empirical data and uniformity of the design here, we went with this.  All the alternatives were discussed in depth, but had issues that made them less good overall than the one that was picked.

I hope that helps! :)
