### ISSUE TITLE
Unable to Load DLL 'tensorflow'

### ISSUE THREAD

**Issue by lllhhu** [dotnet/docs#16104]
Running the TransferLearningTF sample project on win server 2008 R2 has failed to Load DLL 'tensorflow', but has no problem running on Win7

**Comment by mairaw** [comment]
@natke this seems related to a ML.NET sample

**Comment by luisquintanilla** [comment]
Hi @lllhhu 

Sorry to hear you're running into this issue. Because you were able to successfully run the application on Windows 7 but not on Server 2008 R2, it appears to be more of a product issue rather than documentation related. I would suggest raising this issue in the [dotnet/machinelearning repo](https://github.com/dotnet/machinelearning/issues).
