### ISSUE TITLE
Implies that Tasks aren't for Parallelization which isn't accurate. 

### ISSUE THREAD

**Issue by jesmith17** [dotnet/docs#16127]
In the first part of the article you make the statement "Cooking breakfast is a good example of asynchronous work that isn't parallel". But the tasks you describe are actually parallel tasks. The operation making toast has inherent wait time in it. There isn't actual work for the Chef to do while the toast is being cooked. So to speed up the process the Chef takes advantage of that wait time to start a parallel tasks like warming the pan for the Eggs.  It also implies that it's not a multi-threaded operation which i don't think is accurate. Using the analogy that to multi-thread this you would need multiple Chefs implies (incorrectly) that Chefs are not already multi-threaded. 

I get what you are trying to say here, but you take some liberties with the examples that aren't accurate, and I think developers will read this and make bad/poor inferences about when they should use these tools. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by gabeluci** [comment]
I disagree. I believe the analogy is perfectly accurate. What you're describing is a very common misunderstanding about what "asynchronous" means.

> But the tasks you describe are actually parallel tasks.

It might look like it's parallel because you have a several procedures that are _partially done_ at the same time. But that's not what "parallel" means. To take the definition of "parallel computing" from [Wikipedia](https://en.wikipedia.org/wiki/Parallel_computing):

> Parallel computing is a type of computation in which many calculations or the execution of processes are carried out simultaneously.

In other words, "parallel" means that two procedures are _actively running_ at the same time. That's not what's happening here.

Asynchronous programming is about going and doing something else while a procedure is waiting. (i.e. while _not actively running_)

One chef making breakfast is never actively doing two things at same time. He might start the coffee, but then he leaves the coffee maker alone to start the eggs. Then he leaves the eggs alone and moves to starting the bacon, etc.

Therefore it is correct to say that one chef represents one thread. One chef is not "multi-threaded".

The [final version of the code example](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/#code-try-8) will run on one thread: there will never be two things processed at the same time. The thread will switch from one thing to the other. 

(there are exceptions to this, like in ASP.NET Core which [doesn't have a synchronization context](https://blog.stephencleary.com/2017/03/aspnetcore-synchronization-context.html) and _might_ actually - but not always - run continuations of asynchronous methods on a separate thread)

**Comment by BillWagner** [comment]
Thanks for writing this @jesmith17 This is a common area where there is confusion.  

I agree with that @gabeluci has said: this does try to point out that CPU-bound parallelism is different than asynchronous operations. As we continue to address the planned work for [async and parallel programming](https://github.com/dotnet/docs/projects/42), we'll explore these nuances further.

I'll close this as answered, and planned in future work.
