### ISSUE TITLE
What about TensorFlow 2.0 models compatibility ?

### ISSUE THREAD

**Issue by jsgonsette** [dotnet/docs#16154]
Compatibility with TensorFlow 2.0 models is barely stated (correct me if I'm wrong). I can't find any information about training a model in Python/TensorFlow 2.0, exporting this model (SavedModel format) then use it in Dot.Net. When I tried I could load my model in Dot.Net, but got an exception as soon as I tried to push some data into. This exception is risen by some TF internal machinery, complaining about an unknown operation. As a result I have no idea if ML.Net is compatible with TF 2.0 or if something else is wrong. This point should be better explained.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 784daf15-838b-a41d-98f3-779ac307745f
* Version Independent ID: ddc8c98a-f8f8-f35b-0677-4c8f77c54236
* Content: [Save and load trained models - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/save-load-machine-learning-models-ml-net)
* Content Source: [docs/machine-learning/how-to-guides/save-load-machine-learning-models-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/save-load-machine-learning-models-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @jsgonsette 

Thanks for your feedback. Unless otherwise specified, the models referred to in the ML.NET Docs are those trained with ML.NET using the ML.NET format. 

Here is some documentation on how to use TensorFlow models within ML.NET:

https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/text-classification-tf

ML.NET makes use of TensorFlow via TensorFlow.NET, a library that provides .NET Standard bindings for TensorFlow. https://github.com/SciSharp/TensorFlow.NET

Looking at the repo, it does not look like TensorFlow 2.0 support is currently available. Although you can verify by opening an issue on the Tensorflow.NET repo and asking on there.
