### ISSUE TITLE
Expected more information

### ISSUE THREAD

**Issue by Dave-Lowndes** [dotnet/docs#16182]
I can't believe step 5 is so lacking. What tool would you suggest? I see later you suggest dotnet try-convert, but then say in effect that you don't recommend it. What subtle changes in behavior might it make that I might depend on?
This is really inadequate. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 577db847-e424-a9dc-ee2d-f2c6ddb54600
* Version Independent ID: 5fa219d8-0c9c-c758-c1ee-17cefd75ca24
* Content: [Port from .NET Framework to .NET Core - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/porting/#feedback)
* Content Source: [docs/core/porting/index.md](https://github.com/dotnet/docs/blob/master/docs/core/porting/index.md)
* Product: **dotnet-core**
* GitHub Login: @cartermp
* Microsoft Alias: **mairaw**

**Comment by cartermp** [comment]
@Dave-Lowndes the subtle changes _possible_ are extremely high in number, since there are a massive number of (sometimes strange) things that can be done with .NET Framework projects and the desktop MSBuild. Some of these behaviors may be things you've come to rely on, and we cannot guarantee that they will be the same when converted to the .NET SDK. As is written further in the docs, the `try-convert` tool is recommended as a starting point.

**Comment by Dave-Lowndes** [comment]
@cartermp Hi Phillip. If you know about these things, how about providing documentation on them? Vague statements are pretty useless.
Regarding the try-convert mention in the documentation. I felt that it was a rather lukewarm recommendation - more of a warning than a recommendation really!

**Comment by cartermp** [comment]
@Dave-Lowndes They're not really documentable. MSBuild XML is a turing-complete language, and so you have have arbitrary configuration that depends on something that will fail to build, or depend on legacy project flavoring (which isn't supported), or have your own flavoring (which isn't supported), or use legacy installer projects (which aren't supported), or...the list goes on and on to the point where it's easier to just run a tool to see how it goes, or start from scratch and copy/paste files over. There's no prescribed method for conversion.

I think the best list that can be provided is a small one that contains the top5 or so legacy project system behaviors that aren't supported, in a separate document that is linked to from here. However, because tooling is malleable, that list won't always be accurate over time, which increases our burden of ensuring the entire doc set is accurate even further.

**Comment by Dave-Lowndes** [comment]
@cartermp OK, I'd say document the top likely issues then. I'm particularly interested in that you mention legacy installer projects aren't supported. What precisely are you referring to there? I make use of the Microsoft Visual Studio Installer Projects extension - is that affected?

**Comment by Pyritie** [comment]
Adding this sort of reasoning to the document directly would be good enough for me, explaining *why* there's no simple button or VS extension which does everything for you (pointing at how complicated/extensible .NET Framework projects are). A vague "use a tool" just leaves me confused.
