### ISSUE TITLE
Feedback on existing dotnet new docs

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/docs#1623]
@mairaw

Original feedback issue is at https://github.com/dotnet/docs/issues/1450

>“After this, the project is ready to be compiled and/or edited further.”
That’s not 100% accurate. The user has to run dotnet restore before it’s ready to be compiled.
 
>“The command contains a default list of templates; use dotnet new --help”
This should be changed to “dotnet new --list”
 
In the article I don’t see any usage of project template specific help. For example dotnet new mvc --help. We should include that.

**Comment by mairaw** [comment]
Thanks for opening a new one so we can discuss some of your suggestions @sayedihashimi and work a bit more on this topic.

> “After this, the project is ready to be compiled and/or edited further.”
> That’s not 100% accurate. The user has to run dotnet restore before it’s ready to be compiled.
Well, the compilation process is a 2-step process, where you first need to restore then build. I can try to change the wording to make it a bit more clear but the project is actually ready to be compiled.

> “The command contains a default list of templates; use dotnet new --help”
> This should be changed to “dotnet new --list”
Well, both commands give almost the same exact output with the difference that --help also gives you examples on the bottom. So I'll add --list as an option.

>In the article I don’t see any usage of project template specific help. For example dotnet new mvc --help. >We should include that.
We do show the syntax with the template value:
`dotnet new [template] [-lang|--language] [-n|--name] [-o|--output] [-h|--help]`
I'll change the syntax to actually be `dotnet new <template> [-lang|--language] [-n|--name] [-o|--output] [-h|--help]` since template is not optional on that line.
I can also add some info on the attribute description itself about this.

I'm also planning to do some further edits to that topic:
- I'd like to list the templates that come pre-installed
- The basic description is still the old one. It should be changed to reflect the new behavior of templates allowing you to create projects or solutions.

Thanks!

**Comment by sayedihashimi** [comment]
@mairaw 

>Well, the compilation process is a 2-step process, where you first need to restore then build

With a statement like "the project is ready to be compiled", gives me the impression that I can execute `dotnet build` which won't work in this case.

>Well, both commands give almost the same exact output with the difference that --help also gives you examples on the bottom. So I'll add --list as an option.

`dotnet new --help` will be updated to tell users to run `dotnet new --list` to see the template list. Please change this to `dotnet new --list` so that the docs are future proof.

>We do show the syntax with the template value:

Sorry I may not have been clear. Templates can have specific parameters (the MVC template shows this). From the current state of the article I didn't not leave with that understanding.

**Comment by mairaw** [comment]
We have two copies of the article right now. This will change once we release VS 2017 RTM.

Are you looking at [this page](https://docs.microsoft.com/en-us/dotnet/articles/core/preview3/tools/dotnet-new)? There is a section about template options: https://docs.microsoft.com/en-us/dotnet/articles/core/preview3/tools/dotnet-new#template-options

**Comment by sayedihashimi** [comment]
Sorry I missed the Template Options section.

**Comment by mairaw** [comment]
No problem. Another thing I've noticed:
If you have a project in the folder when you're running `dotnet new --list`, you won't get all templates. So I'm guessing we should change that sentence to say `dotnet new -all`.

**Comment by sayedihashimi** [comment]
The behavior of --list is changing to always show all templates, unless the user passes in another parameter indicating project/item.

**Comment by mairaw** [comment]
Will this come with the next release or later @sayedihashimi? If later, I'd prefer to edit the topic in the future to show `--list` instead of `-all`; otherwise, people can get confused.
