### ISSUE TITLE
Why static methods instead of instance ones?

### ISSUE THREAD

**Issue by mrmowji** [dotnet/docs#16273]
I already asked the same question in StackOverflow, but it was closed since they thought it's opinion-based.

The issue is not the specification itself. It's the lack of reasoning behind "why"s. The reader may not understand the concepts easily, and the API docs must be the first place to look them up. I couldn't find anything, maybe it's my fault.

We have different types in .NET; `string`, `char`, etc. Variables of these types are basically objects; they have method members at least, like `ToString()`. But somehow, most of the methods are defined as class methods (`static`) and not instance methods. For example, we have a method for testing if a character is lower case (`IsLower()`). Consider the following statements:

```c#
// we have this
Console.Write(Char.IsLower(ch));

// not this
Console.Write(ch.IsLower());
```

To me, the second statement is more intuitive. But I want to know the reason behind why we have the first one, not the other.

The question is why these kind of methods are defined as `static` so we need to call them using the class, and not the instance itself? There are lots of these kind of static methods: `String.Join`, `Convert.ToInt32`, etc. So providing some explanation would help developers like me.

### Some possible answers from SO:
- It's a performance thing.
- Those methods were defined before introducing Extension Methods (C# 3.0).
- They're helper methods operating directly on public members of instances.

**Comment by Youssef1313** [comment]
I think this could be related to memory optimizations. If they were instance methods, they would be loaded with each object of the type `System.Char`.
I disagree about the reasoning of Extension Methods. Instance methods are not extension methods.

However, I'm not 100% sure.

**Comment by Thraka** [comment]
Unfortunately this still isn't the place to ask this question, just because I doubt you would get the answer you're looking for. But honestly, I don't think you would get a definitive answer. .NET is pretty robust and adaptable to your style of programming. The original engineers of the class model may have conceptually thought that the best place for these methods was on the type instead of the instance. If you put them on the instance, it just adds to the noise you see from things like intellisense. So maybe they categorized the methods into functionality and founds ones that were appropriate for the type and put them there as static members.

Also, these types in your example are primitive types, so perhaps it makes more sense (conceptually) to keep helper methods outside of the object instance.

I'm sure you could find all sorts of design pattern books and articles that argue one way or the other on this. I think stackoverflow got it right with the resolution of "Opinion based".

@BillWagner may be able to provide some thoughts, but I'm going to close this issue. 

Cheers!

**Comment by mrmowji** [comment]
@Thraka The problem with this pattern (if it is one), is that the developer can't easily find where to look up for a specific method; it's not obvious. For example when we need to join array elements into a string, we use the `Join` method from `String`, not any method related to that array type. **Should we see the return type of that method as a hint?** I don't know. Maybe that's a thing to live by :)

Thanks for the explanation though. Some good points I'll remember.
