### ISSUE TITLE
Dependency on libicu52 which is not present in Ubuntu 18.4.3

### ISSUE THREAD

**Issue by chrisvdb** [dotnet/docs#16374]
Could dotnet-sharedframework-microsoft.netcore.app-1.1.13 be recompiled to depend on a newer version of libicu present in Ubuntu 18.4.3? Currently it depends on libicu52 (>= 52~m1-1~) which is not present in the repo.

**Comment by mairaw** [comment]
@Thraka @dagood can you help move this feedback to the appropriate repo? This is not a doc issue.

**Comment by dagood** [comment]
> dotnet-sharedframework-microsoft.netcore.app-1.1.13

Based on the version number, this package can't be serviced because 1.1 has reached end of life (2019-06-27). You can see the current status at https://dotnet.microsoft.com/download/dotnet-core.

https://github.com/dotnet/runtime is the right place to file issues like this about the dotnet-runtime (shared framework) packages.

(I don't have permission to close or move issues in this repo.)

**Comment by mairaw** [comment]
Thanks for all the information @dagood. Closing this issue then.

And I've fixed your permissions issues now.
