### ISSUE TITLE
Remove confusing information & restructure and provide additional information

### ISSUE THREAD

**Issue by Jeej** [dotnet/docs#16438]
Hi,

Can this page be changed to be like the page in the ".NET Microservices: Architecture for Containerized .NET Applications" ebook ( https://docs.microsoft.com/en-us/dotnet/architecture/microservices/ )?

Please remove in the paragraph "Purpose" the section ".NET Microservices. Architecture for Containerized .NET Applications". It is not logical to download another ebook in this ebook.

Please add information like "action links", "version", "copyright", etc like in the other ebook.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae811ba0-e87d-2569-5b1d-e8493d933fa3
* Version Independent ID: 6fe4be5f-f5a5-7bb6-b78f-e4e5a758e540
* Content: [Architect modern web applications with ASP.NET Core and Azure](https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/#feedback)
* Content Source: [docs/architecture/modern-web-apps-azure/index.md](https://github.com/dotnet/docs/blob/master/docs/architecture/modern-web-apps-azure/index.md)
* Product: **dotnet-architecture**
* Technology: **modern-web-apps-azure**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by ardalis** [comment]
Addressing with https://github.com/dotnet/docs/pull/18622.

Note: eBook already has copyright and action links sections. Added a better Version description. Links to microservices ebook are intentional so readers can easily access information about either microservices-based or monolithic-based architectures. The microservices book should include a similar link back to this book.
