### ISSUE TITLE
Link compiler errors in Visual Studio to relevant docs page

### ISSUE THREAD

**Issue by ChrisMaddock** [dotnet/docs#16448]
![image](https://user-images.githubusercontent.com/4837132/71557739-2b3f5380-2a42-11ea-80e0-9c96ab52b0ad.png)

On the above interface, the NuGet error messages link directly to the relevant docs page, where as the CS and IDE errors instead link to a Bing search, where the docs page often ends up several results down.

Could the CS/IDE ones also link to the docs page? I can't see any difference in the meta data between the files for NU1101 and CS0116, so is this something that needs to be changed outside of the content?

**Comment by mairaw** [comment]
Yeah, I've noticed that too @ChrisMaddock and not sure who made that change. @BillWagner @Pilchie  any ideas on who to ping about this?

**Comment by BillWagner** [comment]
I'd start with @jinujoseph She may know.

**Comment by mavasani** [comment]
I believe this needs to be broken down into 2 separate work items for IDE and compiler diagnostics.

1. Compiler diagnostic help links: This should be a pretty trivial change to update [this](http://sourceroslyn.io/#Microsoft.CodeAnalysis.CSharp/Errors/ErrorFacts.cs,78) method to populate the map with entries for each compiler diagnostic ID and corresponding help link. All other infrastructure is in place to automatically light up this help link once this map is populated. I think this should be an issue filed on Roslyn repo and assigned to compiler team.

2. IDE diagnostics: This is a much bigger work item as we don't have dedicated docs pages for each IDE diagnostic ID. So the work here is to create a dedicated location in docs pages where we want to document these and then create one dedicated documentation page for each IDE diagnostic ID. Additionally, we need to then update the analyzer code for all IDE analyzer to have the help link URI so reported diagnostics can navigate to that page. I believe @sharwell had a tracking Roslyn bug for this work on IDE side, but I cannot seem to find it. This would obviously need a much bigger documentation push, but would be useful for customers.

**Comment by ChrisMaddock** [comment]
Great, thanks @mavasani!

I only mentioned the IDE errors, as I thought there were already docs pages for them. If not, the search seems like the right behaviour. 

When I’m at a desktop, I’ll have a look at the Roslyn code and see if this is something I can contribute. Thanks for the pointers!

**Comment by ChrisMaddock** [comment]
Hey @BillWagner, @mairaw - can I have your thoughts about how to go about this, please?

Following @mavasani's lead - I'd like to add direct links to the docs pages for the C# compiler errors.

Regarding those compiler errors that we don't have docs pages for yet, I'm thinking they should ideally link to [this](https://docs.microsoft.com/en-us/dotnet/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error) page. What I don't want to do however, is hardcode that in the Roslyn - so that every time someone adds a new compiler error page, they have to also update Roslyn.

I'm thinking instead of setting up Roslyn to link to pages of the format `/dotnet/csharp/language-reference/compiler-messages/cs{ERR_NUM}` - and then setting up redirects for all the errors that don't have their own pages yet. This would of course add a bunch of new entires to the redirect file, but mean that adding/removing pages was entirely within the control of the content team.

What would you think to this approach? 🙂

**Comment by mairaw** [comment]
Let me discuss this with @BillWagner and get back to you!

Just for context, the way it used to work before is that the Visual Studio IDE would call the F1 service URL (I'll need to get an older version of VS to test exactly what it looked like but it would be something similar to this):
`https://msdn.microsoft.com/query/dev16.query?appId=Dev16IDEF1&l=EN-US&k=k(CS{ERR_NUM});k(DevLang-csharp)&rd=true`

e.g. 
https://msdn.microsoft.com/query/dev16.query?appId=Dev16IDEF1&l=EN-US&k=k(CS1002);k(DevLang-csharp)&rd=true

The sorry page is already hooked up with specific error codes that don't have a dedicated page (look at the metadata on the page to see it)

e.g. https://msdn.microsoft.com/query/dev16.query?appId=Dev16IDEF1&l=EN-US&k=k(CS4030);k(DevLang-csharp)&rd=true

Maintaining the codes in that specific page instead of using redirects seem like it would be an easier task. I don't have context into why it was changed from F1 to Bing, but I bet they had customer feedback about the old experience not being useful by landing on the sorry page.

**Comment by ChrisMaddock** [comment]
Sounds good, thanks Maira. 😊
