### ISSUE TITLE
Changing the number of epochs 

### ISSUE THREAD

**Issue by Phoenix-313** [dotnet/docs#16442]
Hi,
I followed this tutorial to create the concrete crack classifier: 
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification-api-transfer-learning
I noticed that training stops early regardless of the selected number of epochs. So, how to make the ANN training run until a certain epoch or low error is reached?

**Comment by luisquintanilla** [comment]
Hi @Phoenix-313 ,

The reason why this is happening is due to early stopping being enabled by default. To disable early stopping, set the `EarlyStoppingCriteria` option in an [`ImageClassificationTrainer.Options`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.vision.imageclassificationtrainer.options?view=ml-dotnet) object to `null`. The code should look something like the code below:

```csharp
var classifierOptions = new ImageClassificationTrainer.Options()
{
 //...other options
Epoch = 50, // Can be changed to whatever number you want
EarlyStoppingCriteria =null
};
```

**Comment by Phoenix-313** [comment]
> Hi @Phoenix-313 ,
> 
> The reason why this is happening is due to early stopping being enabled by default. To disable early stopping, set the `EarlyStoppingCriteria` option in an [`ImageClassificationTrainer.Options`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.vision.imageclassificationtrainer.options?view=ml-dotnet) object to `null`. The code should look something like the code below:
> 
> ```cs
> var classifierOptions = new ImageClassificationTrainer.Options()
> {
>  //...other options
> Epoch = 50, // Can be changed to whatever number you want
> EarlyStoppingCriteria =null
> };
> ```

Thank you very much!
