### ISSUE TITLE
Update tutorials/libraries.md for MSBuild/csproj

### ISSUE THREAD

**Issue by GuardRex** [dotnet/docs#1646]
Developing Libraries with Cross Platform Tools
* https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries
* https://github.com/dotnet/docs/blob/master/docs/core/tutorials/libraries.md

xref https://github.com/dotnet/docs/issues/1574

**Comment by mairaw** [comment]
@cartermp @terrajobst hey guys, wondering if any of you would have some bandwidth to update this guidance this month? 

We should also move that .NET Standard table to an include file so that we only have to update one place when updating that table since the same info is also found at https://docs.microsoft.com/en-us/dotnet/articles/standard/library.

**Comment by cartermp** [comment]
I should be able to dedicate some time to this, yes.

**Comment by mairaw** [comment]
Assigning to you then @cartermp. #1693 is also related to this topic. Thanks!

**Comment by cartermp** [comment]
FYI, I'm midway through this.  Lots of fundamental changes have to be made to this article, unfortunately.  It's coming along.
