### ISSUE TITLE
Outdated LTS version mentioned in section `Install with bash Automation`

### ISSUE THREAD

**Issue by ConnerOrth** [dotnet/docs#16474]
"The script defaults to installing the latest long term support (LTS) version, which is .NET Core 2.1."

Should be 3.1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac255410-47e8-7c14-b14f-06dfe3e424f9
* Version Independent ID: 09a819ef-b5af-43f7-e744-60ca6f667a45
* Content: [Install .NET Core SDK on Windows, Linux, and macOS - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/sdk?pivots=os-linux#feedback)
* Content Source: [docs/core/install/sdk.md](https://github.com/dotnet/docs/blob/master/docs/core/install/sdk.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Youssef1313** [comment]
Correct. The current LTS is 3.1. I downloaded the `dotnet-install.ps1` to test that and make sure it actually downloads 3.1, but I got the following error:

![image](https://user-images.githubusercontent.com/31348972/71624590-04248580-2bec-11ea-8014-cc458a7a2e16.png)

Not sure if there's a problem with the script or I have problem from my side. But I'm going to open a PR since the current LTS is 3.1.
