### ISSUE TITLE
Unclear use of lock object

### ISSUE THREAD

**Issue by lukos** [dotnet/docs#16494]
In the example, you use a decimal and then a separate lock of type object. If the sample instead used Decimal, could the balance variable itself be used as the lock? In general, is a separate lock only needed for a) accessing a number of separate resources and b) accessing a single resource that is a primitive type?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b544eeb3-082e-1c67-eb76-f5ce0acee45e
* Version Independent ID: d4765a2e-ac77-e947-165c-5a0f88f4e8e2
* Content: [lock statement - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/lock-statement)
* Content Source: [docs/csharp/language-reference/keywords/lock-statement.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/lock-statement.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for raising this question @lukos 

The additional `balancelock` variable is required because the C# `lock` statement requires the locked object to be a *reference type*. The code would not compile if it tried to lock the `balance` variable because `Decimal` is a value type. See the 2nd paragraph in the specification for the [lock statement](https://docs.microsoft.com/dotnet/csharp/language-reference/language-specification/statements#the-lock-statement). 

I'll close this as answered.
