### ISSUE TITLE
Packs vs Shared libraries: More information is welcome 

### ISSUE THREAD

**Issue by MarcioAB** [dotnet/docs#16521]
For example: Why the project default libraries (as in assembly load context libraries) points to libraries in shared directory but the project framework (as in project dependencies) points to pack directory ? Why libraries in pack directory have xml documentation and libraries in shared directory don't. Why they have different sizes ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ce2ad2f-c2fb-b15a-fb97-75417a1b51e8
* Version Independent ID: 40eec307-4ff8-e68f-c8a7-ead32cccf776
* Content: [.NET Core distribution packaging - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/build/distribution-packaging)
* Content Source: [docs/core/build/distribution-packaging.md](https://github.com/dotnet/docs/blob/master/docs/core/build/distribution-packaging.md)
* Product: **dotnet-core**
* GitHub Login: @tmds
* Microsoft Alias: **mairaw**

**Comment by tmds** [comment]
https://docs.microsoft.com/en-us/dotnet/core/build/distribution-packaging is for explaining to Linux maintainers how they can package .NET Core.
I think this isn't the right document to explain the design.

cc @dagood @nguerrera

**Comment by dagood** [comment]
I agree this page isn't where we should describe shared frameworks (runtimes) vs. framework packs. [dotnet/designs/accepted/install-locations.md](https://github.com/dotnet/designs/blob/master/accepted/install-locations.md) and https://github.com/dotnet/designs/pull/50 are the only semi-official places I can think of where I've seen these documented.

(Once we do have it documented (or if someone finds some docs), I think it would be good to link to that from this distro packaging page so that maintainers can understand what they're putting together, though.)
