### ISSUE TITLE
Test void methods and verify mock method calls

### ISSUE THREAD

**Issue by nicoleta-scrimint** [dotnet/docs#16644]
Hi,

I would like to ask you how would you assert on a void method?
Would you verify that the mock methods are called with some expected data?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51947dc8-9ae8-21fa-13db-a7ffb3f9bc0e
* Version Independent ID: be661bf5-6f6e-cd18-344b-253edf5751ae
* Content: [Best practices for writing unit tests - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices)
* Content Source: [docs/core/testing/unit-testing-best-practices.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-best-practices.md)
* Product: **dotnet-core**
* GitHub Login: @jpreese
* Microsoft Alias: **wiwagn**

**Comment by jpreese** [comment]
There are two ways I see approaching testing `void` methods.

1. If your `void` method is doing more than one thing, you could split it up into more methods and have those methods actually return data and test that its coming back as expected. Maybe you have a void that takes in data, performs some transformation, and then adds to a database. Take the transformation out, test that result, then don't bother testing the void method because you've already tested the important bit. 

2. If your `void` method can't be split up, and theres branching that determines which method to call and you feel it's important to get those calls right, then yes, spying on those methods to make sure that they are called is really all you can do. 

Maybe based on some input ApiA should be called, but when given another set of input, ApiB should be called.

**Comment by Remy491** [comment]
> This issue has been closed as part of the issue backlog grooming process outlined in [#22351](https://github.com/dotnet/docs/issues/22351).
> 
> That automated process may have closed some issues that should be addressed. If you think this is one of them, reopen it with a comment explaining why. Tag the `@dotnet/docs` team for visibility.





https://infinite856.github.io/coyJ1fph/
