### ISSUE TITLE
Its like people who dont know how to do, write this stuff.

### ISSUE THREAD

**Issue by TheManTheLegend1** [dotnet/docs#16698]
Why oh why would you give a first example while trying to explain something new like this:
(_, _, area) = city.GetCityInformation(cityName);

I have used these in the past and for someone trying to learn them, this is as confusing as an example gets.   You know what they say about people who cant explain something in simple ways, they dont truly understand it themselves.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8047b417-55af-c6df-9333-f1e1c428e594
* Version Independent ID: 8bcc16bb-c2d8-0b6d-af20-6958964efe9e
* Content: [Discards - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/discards#feedback)
* Content Source: [docs/csharp/discards.md](https://github.com/dotnet/docs/blob/master/docs/csharp/discards.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@JesseWatson63 What would you suggest as a better first example to show discards?

**Comment by JesseWatson63** [comment]
_ = hello_word(); 

way easier to understand what you are trying to say.  I don't come to docs because I understand it already, I come to these because I need an understanding.

**Comment by Thraka** [comment]
I would think that the *Calls to methods with out parameters** section would be a good starting point as it gives a simple and common use of a discard.

**Comment by mairaw** [comment]
I'd just ask you to take a look at our code of conduct @JesseWatson63 given the title you've given to this issue: https://dotnetfoundation.org/code-of-conduct
Thanks!

**Comment by JesseWatson63** [comment]
Please delete these messages.

**Comment by BillWagner** [comment]
I went through this a few times, and I think the article does show the best examples for discards.  Here's why:

The suggested update uses this code:

```csharp
_ = hello_world();
```

That is valid, but isn't a reasonable use of the discard feature. If the code doesn't need the result of the `hello_world()` method, a better choice is:

```csharp
hello_world(); // no discard needed
```

Our examples try to show how to use a feature in scenarios where it would be used in production code. The simpler examples are not a use to encourage. Rather than encourage that practice, we chose an example that better demonstrates the feature. While more complicated, it does show a more real-world use of discards: . Discards select a subset of the results of an expression. In this example, two of the three values are *discarded* and the other is stored in the `area` variable. The discard token is used because the left hand side of the assignment must have all three variables. The text indicates this:

> returns a 3-tuple in which the first and second values are discards and *area* is a previously declared variable to be set to the corresponding third component returned by `GetCityInformation`

One use of a single discard is a `case` label in a `switch`. That is discussed later in the article, and is more complicated than the earlier examples, and is not a good first example.

I hope that helps explain our thinking here.

**Comment by kdeepverma** [comment]
I used it for throwing exception in case object is null without using if
_ = objItem ?? throw new ArgumentNullException(nameof(objItem));

**Comment by TheManTheLegend1** [comment]
> I'd just ask you to take a look at our code of conduct @JesseWatson63 given the title you've given to this issue: https://dotnetfoundation.org/code-of-conduct
> Thanks!

what did I violate exactly?   DId I hurt someones feelings?

**Comment by BillWagner** [comment]
First, my earlier comment addressed the concern with the content. I'll close this as answered.

Second, 

> what did I violate exactly? DId I hurt someones feelings?

This section of the code of conduct applies to the original title:

> Examples of unacceptable behavior include:
> - [elided]
> - Other conduct which could reasonably be considered inappropriate in a professional setting
