### ISSUE TITLE
More specifics on "How are dependencies shared" please

### ISSUE THREAD

**Issue by toryb** [dotnet/docs#16782]
I have a need to share a dependency on Microsoft.Extensions.DependencyInjection.IServiceCollection. I receive an object that implements IServiceCollection via dependency injection and want to call a static extension method in a plugin that is loaded from configuration at runtime. Initially I was loading Microsoft.Extensions.DependencyInjection in both AsseblyLoadContexts (Default & the plugin). I have finally figured out how to avoid loading it in the plugin context via &lt;ExcludeAssets&gt;runtime&lt;/ExcludeAssets&gt;. Now I need to know how to have my "coding of custom AssemblyLoadContext instance" implement the sharing as mentioned in the section "How are dependencies shared." The documentation above states "When any of these functions return a reference to an Assembly instance that was loaded in another AssemblyLoadContext instance, the Assembly instance is shared." How can I obtain a reference to an Assembly instance that was loaded in AssemblyLoadContext.Default?

For more information and a sample solution that reproduces my issue see my question on StackOverflow. (https://stackoverflow.com/q/59806686/9866443)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c83628c-7002-9045-9c72-f8d97b784eb0
* Version Independent ID: a761a83d-5aa8-958a-d210-6eb8f7929ff2
* Content: [Understanding AssemblyLoadContext - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/understanding-assemblyloadcontext#how-are-dependencies-shared)
* Content Source: [docs/core/dependency-loading/understanding-assemblyloadcontext.md](https://github.com/dotnet/docs/blob/master/docs/core/dependency-loading/understanding-assemblyloadcontext.md)
* Product: **dotnet-core**
* GitHub Login: @sdmaclea
* Microsoft Alias: **stmaclea**

**Comment by mairaw** [comment]
Is this something you can help with @sdmaclea?

**Comment by sdmaclea** [comment]
Not sure how you want to obtain it.  

Each type has a reference to the Assembly that defines it.  See https://docs.microsoft.com/dotnet/api/system.type.assembly?view=netcore-3.1 

You can query the `AssemblyLoadContext.Default` by `AssemblyName`.  See https://docs.microsoft.com/dotnet/api/system.runtime.loader.assemblyloadcontext.loadfromassemblyname?view=netcore-3.1 .  If the assembly was already loaded it will obtain it from the cache, otherwise it will load it.

**Comment by vitek-karas** [comment]
The best way to "share" is to return `null` from your custom's `AssemblyLoadContext.Load` method. That tells the runtime to fallback to the default context, which will try to resolve the assembly. If it can, the one from Default will be used - and thus "Shared".

With the `<ExcludeAssets>runtime</ExcludeAssets>` you should be able to use `AssemblyDependencyResolver` to implement your `AssemblyLoadContext.Load` method basically exactly as it's done int he sample. The `AssemblyDependencyResolver` should return null for the extension assembly in question (since with the project modifications, it should not be part of the plugin anymore) - thus the `Load` method will return null as well.

If the plugins are built correctly you should not need to have any specific code in your custom load context to handle the sharing.
