### ISSUE TITLE
InitializeForm should be InitializeComponent

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#16829]
A [very few samples](https://github.com/dotnet/samples/search?q=InitializeForm&unscoped_q=InitializeForm) has method called "InitializeForm". The well-known convention and Visual Studio default is "InitializeComponent".

**Comment by gewarren** [comment]
The [first one](https://github.com/dotnet/samples/blob/26c4e039170261d0d54782258b607ec0eb490455/snippets/visualbasic/VS_Snippets_Winforms/Classic%20PrintDocument%20Example/VB/source.vb) already has a call to InitializeComponent, so I'm not sure if this is feasible.

/cc @Thraka

**Comment by Thraka** [comment]
I would guess that this was manually created since the auto-generated name is InitializeComponent. If the code is going to be rewritten from scratch then it could be done correctly with the designer and not by hand. But if the sample compiles and is fine, we should leave it as this inconsistency isn't really important.

Thoughts?

**Comment by Youssef1313** [comment]
The first result has calls to both, but InitializeComponent doesn't even exist.

**Comment by Thraka** [comment]
True, I would delete the one that isn't used. However, I scanned the docs and I can't find this being referenced by anything. So it would probably be deleted in the future.

**Comment by Youssef1313** [comment]
It's used in dotnet-api-docs, [here](https://github.com/dotnet/dotnet-api-docs/blob/f37171b1ee7912fad473703ce48a91f96df382b8/xml/System.Drawing.Printing/PrintDocument.xml)

**Comment by Thraka** [comment]
thanks, i just did a general scan in this repo, whoops 😄
