### ISSUE TITLE
Needs documentation on how to install using .deb files directly

### ISSUE THREAD

**Issue by SidShetye** [dotnet/docs#16836]
Please see https://github.com/dotnet/core/issues/4179

when apt is down, we need a fall backs to download the .deb file and install it locally.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f33bad-b152-c53b-1b0a-234c9a075bd7
* Version Independent ID: 565e7432-c4b3-a1c2-8ce3-c8c1a0d8ebe8
* Content: [Install .NET Core on Ubuntu 18.04 package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1804)
* Content Source: [docs/core/install/linux-package-manager-ubuntu-1804.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-ubuntu-1804.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by dagood** [comment]
Interesting... I've done this before for a different issue to pick out a specific package, but hadn't considered it as a workaround for the periodic outages. I like the idea.

We may also want to consider offering tarball archives of the Debs and RPMs on https://dotnet.microsoft.com/download, because it's hard to find all right RPMs and Debs on https://packages.microsoft.com manually (even while knowing what you're looking for).

We do provide .NET Core as `.tar.gz`, however it takes more effort to switch over to that installation method from Deb/RPM.

Related, suggestion that we add a general description of the known outages to the docs: https://github.com/dotnet/docs/issues/16670

/cc @leecow @dleeapho @NikolaMilosavljevic

**Comment by Thraka** [comment]
If someone could write up the general info, I can port it to the docs. I'm not super-skilled in linux, although I can get around.

**Comment by dagood** [comment]
Well, here's a general process:

1. Navigate to the root directory where Debs/RPMs are hosted.
   * E.g. https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/
   * E.g. https://packages.microsoft.com/fedora/30/prod/
2. Find the root package you want to install.
   * E.g. `dotnet-sdk-3.1`, `aspnetcore-runtime-3.1`, or `dotnet-runtime-3.1`.
3. Download the highest version of that package. Install the package from file. Observe the error message.
   * Command varies per distro. In my experience, some package managers accept ordinary `install {file}` commands, but others you need to use the underlying tool like `dpkg` or `rpm`.
   * At least some package managers support installing a package from a URL, so download and install can be combined there.
4. Find each missing required Deb/RPM in the repo, download them.
5. Repeat (3-4) until no errors.

It's unfortunately not as simple as "here's a set of URLs, just replace the version number" because we don't update every single package during every single servicing release. E.g. `dotnet-sdk-3.0=3.0.102` depends on `dotnet-targeting-pack-3.0 (>= 3.0.0)`.

(This also makes it hard to release a tarball of all RPMs/Debs required for a certain release, because we'd have to harvest them from previous releases.)

**Comment by leecow** [comment]
We currently do not publish the Linux native installer packages to the same location as the rest of the release. That could certainly be changed. 

I like the idea of bundling the needed deb/rpm packages to simplify the experience. We could also go as far as including a bash script that drives the installation so that the experience is simply: download, unpack the tar to a directory, run the script.

**Comment by Thraka** [comment]
I think we need these instructions a bit better. It's hard to explain this in generic terms. For example, the two URLs you posted for the distros have different pathing schemes. If there are different commands on different distros, this needs to be called out.

Also, if the original problem is related to using APT to download from that repo path, isn't that going to just fail manually downloading?

I think it's better to tell them to download from the download page: https://dotnet.microsoft.com/download/dotnet-core/3.1 and once they have the version they want, here are the instructions to install.

**Comment by dagood** [comment]
> I think we need these instructions a bit better.

Yeah... the general steps I gave would require some fairly deep research to figure out how to apply them, and even once they make sense, they'd be intensely tedious. I don't think it makes sense to add the steps to the documentation as they'd have to be done today.

> Also, if the original problem is related to using APT to download from that repo path, isn't that going to just fail manually downloading?

The common problem is actually about the deb/rpm file being out of sync with a centralized repo manifest. Downloading the files manually would work fine there. (The manifest is the part that lags behind.) In other cases, yeah, there would still be a problem if the file itself is bad, but it's not the type of outage we normally see.

> I think it's better to tell them to download from the download page: https://dotnet.microsoft.com/download/dotnet-core/3.1 and once they have the version they want, here are the instructions to install.

I don't understand what the suggestion is vs. what we have today--following this flow is one way to get to this page.

Are you suggesting that we recommend the binary/tarball downloads instead? That's what I'm referring to here:

> We do provide .NET Core as `.tar.gz`, however it takes more effort to switch over to that installation method from Deb/RPM.

(It also ends up in a worse state: they no longer have automatic updates, so may miss security updates unless they remember to switch back to rpm/deb, manually keep track, or implement infra to use releases.json.)

---

I think that if we're going to do anything in the short term, this is the minimum:

> I like the idea of bundling the needed deb/rpm packages to simplify the experience. We could also go as far as including a bash script that drives the installation so that the experience is simply: download, unpack the tar to a directory, run the script.

However, keep in mind that we are pushing the service owners to improve quality: https://github.com/dotnet/core/issues/4167.

**Comment by Thraka** [comment]
Really the easy solution for this is to do what @leecow suggested as a possibility:

>We currently do not publish the Linux native installer packages to the same location as the rest of the release. That could certainly be changed.

If that happens, the instructions seem pretty straightforward for downloading the installer and getting this properly installed.

I agree, the tarball isn't optimal.

**Comment by leecow** [comment]
To be clear on the install instructions - Linux native installers are not a single bundle like Mac and Windows but are single component installers. So, the instructions would need to list the entire file set and explicit order they are installed. See an example in the [3.1 preview install instructions](https://github.com/dotnet/core/blob/master/release-notes/3.1/preview/3.1.0-preview3-install-instructions.md).

**Comment by dagood** [comment]
That's referring to the suggestion I posted earlier:

> We may also want to consider offering tarball archives of the Debs and RPMs on https://dotnet.microsoft.com/download, because it's hard to find all right RPMs and Debs on https://packages.microsoft.com manually (even while knowing what you're looking for).

It's not trivial from the release perspective, since not all packages are built during every release--some packages have to be brought forward and redisted in the next. Once we do that manual work once, though, it shouldn't be too hard to pull down the last release, update it with the current patch, and reupload. Definitely seems worth doing.

**Comment by leecow** [comment]
Davis, are you thinking of building a single tar.gz which contains the correct installer set?

**Comment by dagood** [comment]
> So, the instructions would need to list the entire file set and explicit order they are installed.

It's worked fine for me to include all packages in a single install command. I use `apt install ./*.deb` and stuff like that.

**Comment by dagood** [comment]
> Davis, are you thinking of building a single tar.gz which contains the correct installer set?

Yes, as an artifact of the release process, since we don't have access to the necessary bits at build-time.

**Comment by leecow** [comment]
@nakarnam as fyi

**Comment by dagood** [comment]
> To be clear on the install instructions - Linux native installers are not a single bundle like Mac and Windows but are single component installers. So, the instructions would need to list the entire file set and explicit order they are installed. See an example in the [3.1 preview install instructions](https://github.com/dotnet/core/blob/master/release-notes/3.1/preview/3.1.0-preview3-install-instructions.md)

I tried this out with a fresh `ubuntu:19.04` Docker container, and the instructions are missing [`netstandard-targeting-pack-2.1`](https://packages.microsoft.com/ubuntu/19.04/prod/pool/main/n/netstandard-targeting-pack-2.1/), but after getting that and putting them all in the same dir, `apt install ./*.deb` does work fine. It installs the platform dependencies as well.

So as a note to the current effort: we need to be careful to include the right `netstandard-targeting-pack-x.y` when these are produced.

**Comment by leecow** [comment]
I just gave this a whirl on Fedora and it did use packages.microsoft.com to satisfy any missing dependencies such as the targeting pack which wasn't updated. 

```
=============================================================================================================================
 Package                                 Architecture    Version                   Repository                            Size
==============================================================================================================================
Installing:
 aspnetcore-runtime-3.1                  x86_64          3.1.2-1                   @commandline                         7.5 M
 aspnetcore-targeting-pack-3.1           x86_64          3.1.2-1                   @commandline                         1.4 M
 dotnet-apphost-pack-3.1                 x86_64          3.1.2-1                   @commandline                          67 k
 dotnet-host                             x86_64          3.1.2-1                   @commandline                          39 k
 dotnet-hostfxr-3.1                      x86_64          3.1.2-1                   @commandline                         148 k
 dotnet-runtime-3.1                      x86_64          3.1.2-1                   @commandline                          29 M
 dotnet-runtime-deps-3.1                 x86_64          3.1.2-1                   @commandline                         2.8 k
 dotnet-sdk-3.1                          x86_64          3.1.102-1                 @commandline                          64 M
Installing dependencies:
 compat-openssl10                        x86_64          1:1.0.2o-7.fc30           updates                              1.1 M
 dotnet-targeting-pack-3.1               x86_64          3.1.0-1                   packages-microsoft-com-prod          3.4 M
 netstandard-targeting-pack-2.1          x86_64          2.1.0-1                   packages-microsoft-com-prod          2.1 M

```
Or would we want these archives to be complete?

**Comment by dagood** [comment]
> Or would we want these archives to be complete?

With the goal being an alternative when the AzLinux service is down, yes, they must be. For non-production preview instructions I suppose we care less, but it was a made for a nice trial run.

**Comment by dagood** [comment]
We could tell people to download a tarball of RPM/Debs for every release (3.0.0, 3.0.1, 3.0.2, ...) and pick out the RPMs/Debs they require, but that brings us back to a bad/undocumentable UX.

**Comment by leecow** [comment]
I like the idea of making them standalone. This will make the workflow pretty easy for folks to automate and it should be very stable.

**Comment by SidShetye** [comment]
IMHO, whatever path the team takes, it needs to be a one liner. Try

```
source < (curl -s https://example.com/install-dotnet.sh)
```

The scrips itself then figures out what needs to be pulled from where, in what order and installed where.

**Comment by Thraka** [comment]
@leecow @dagood Is there a direction decided on this? Should I just remove this from the march sprint (documentation wise) and move it to the next sprint?

**Comment by dagood** [comment]
It seems to me we've determined in this thread this isn't something we can adequately document--we need additional artifacts to make it reasonable. I don't think it makes sense to have this as a scheduled issue on the docs side of things.

**Comment by Thraka** [comment]
@SidShetye We're going to close this for now. As the product team is aware of the issue, they'll work on this from that side. I'll close this doc request for now. Thanks.

**Comment by dagood** [comment]
Filed https://github.com/dotnet/core/issues/4379 to concretely track creating/releasing the artifacts we've been talking about.

**Comment by leecow** [comment]
I'm running some experiments over the weekend and we'll use 5.0 Preview 1 validate and flesh out the experience. After that, we can move the guidance into Docs.
