### ISSUE TITLE
Correction Needed ?

### ISSUE THREAD

**Issue by tony-long** [dotnet/docs#16830]
This description doesn't match with most regex testing sites.

Grouping construct	Description	Pattern	Matches
( subexpression )	Captures the matched subexpression and assigns it a one-based ordinal number.	(\w)\1	"ee" in "deep"

Check regex101 - 

/
(\w)\1
1st Capturing Group (\w)
\w matches any word character (equal to [a-zA-Z0-9_])
\1 matches the same text as most recently matched by the 1st capturing group

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16d4698e-4220-c422-a554-8a481803d240
* Version Independent ID: f0e3b82a-8d81-ad9e-97fc-efb92f7d0d38
* Content: [Regular Expression Language - Quick Reference](https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference#feedback)
* Content Source: [docs/standard/base-types/regular-expression-language-quick-reference.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/regular-expression-language-quick-reference.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Thank you for opening this issue. I think the description is correct. It's talking at it in more of a developer tone. The pieces you're building when creating the regex are comprised on constructs, and specifically in this case, a grouping construct. When the subexpression is captured, it's assigned one-based ordinal number.

The description in regex101 is more user friendly instead of developer friendly. However, I don't discount that the phrase "capturing group" really should be somewhere in our description.

If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub. I'm going to close this issue though since I don't feel it meets the bar to remain open, however, you can still open a pull request to tweak this description if you would like.

Thanks again!

**Comment by tony-long** [comment]
Thank you for the great follow-up.

________________________________
