### ISSUE TITLE
Where is the C# equivalent of this page?

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#16929]
I know there is not really a material difference between c# and VB.net, but some folks will try to disqualify its advice because of the language its filed under.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 351f51de-0d01-7a2d-a9b7-677ad11074f2
* Version Independent ID: f4c1c6c9-84e3-438d-2ff3-435e27e2c76d
* Content: [Efficient Use of Data Types - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/data-types/efficient-use-of-data-types)
* Content Source: [docs/visual-basic/programming-guide/language-features/data-types/efficient-use-of-data-types.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/language-features/data-types/efficient-use-of-data-types.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by BillWagner** [comment]
Thanks for pointing this out @StingyJack 

There isn't a C# equivalent because all C# always assigns a strong type to a variable. (`var` in C# sets the variable's type to the type on the right hand side of the initialization statement.)

I'll close this.

@KathleenDollard do you think we should add a note about the C# and VB differences on this page?

**Comment by StingyJack** [comment]
@BillWagner  - I was actually focusing on the second section regarding the efficiency of types. I didn't even read that first part of the article about the declaration (no offense meant).  

Would you know if there is any benefit to be had between the integral types (16, 32, 64)?  After posting this, I found a reference at https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/data-types/numeric-data-types#performance that I think says 32bit is generally better, but was looking to confirm it for the other .net languages as well.

**Comment by BillWagner** [comment]
Thanks for clarifying @StingyJack I'll reopen this.

A quick answer: the perf difference between integral types on a modern CPU is small. If you know the size of the "natural" integral size for a CPU, that is typically the fastest.

I'll put this in our backlog, because there is a proposal discussion for a "natural int", `nint` that would map to the natural size on the target processor.
