### ISSUE TITLE
What is the sweet spot for SustainedLowLatency usage?

### ISSUE THREAD

**Issue by SidShetye** [dotnet/docs#17007]
For example:

1. How big should the system memory (or container memory limit for containers) be compared to the under-load memory usage of the application? e.g. If `dotnet-counters` shows a working set of 1GB under peak load, should the VM/container be assigned 1.5x that memory ?

2. Is it ok for a server app to permanently be in `SustainedLowLatency` mode? What are the pitfalls to watch out for?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fcebd46-8a64-9531-f6e1-3a330b61bb0f
* Version Independent ID: 7538a252-8fa8-4615-92df-f1c6d7d6a3e4
* Content: [Latency Modes](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/latency)
* Content Source: [docs/standard/garbage-collection/latency.md](https://github.com/dotnet/docs/blob/master/docs/standard/garbage-collection/latency.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by gewarren** [comment]
@Maoni0 Could you answer this one?

**Comment by Maoni0** [comment]
what I would worry most about when setting SustainedLowLatency is pinning introduced fragmentation that might "stretch" the heap out. by this I mean you have some long lived pins that make into gen2, and then the objects between them die so now there's fragmentation in gen2 which can only be used by promoting gen1 survivors. this can be observed by monitoring your workload without the SustainedLowLatency mode on. otherwise it's pretty safe to have on all the time.

**Comment by SidShetye** [comment]
Is there a GC API for monitoring for this? Or an alert/callback we can hook into for an alarm emerging from the app?
