### ISSUE TITLE
Azure Service Bus vs RabbitMQ

### ISSUE THREAD

**Issue by Loreno10** [dotnet/docs#17028]
**Issue description**

In article https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/integration-event-based-microservice-communications (and others preceding it) it is mentioned that RabbitMQ is a lower-level messaging bus implementation than Azure Service Bus:

> (...) RabbitMQ, a messaging broker transport, is at a lower level than commercial products like Azure Service Bus, NServiceBus, MassTransit, or Brighter. Most of these products can work on top of either RabbitMQ or Azure Service Bus.

In what sense is RabbitMQ a lower level product? How can the other, commercial, products work ON TOP OF RabbitMQ or Azure Service Bus - what does that even mean?

*Edited by Thraka to add doc details*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b037f198-3ee2-28f4-4d93-0999e5d3d3ef
* Version Independent ID: 9bd96308-c726-fcee-850e-a38fd22ff555
* Content: [Implementing event-based communication between microservices (integration events)](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/integration-event-based-microservice-communications)
* Content Source: [docs/architecture/microservices/multi-container-microservice-net-applications/integration-event-based-microservice-communications.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/multi-container-microservice-net-applications/integration-event-based-microservice-communications.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by ccerhan** [comment]
I am not a Microsoft fan but you may misunderstand the statement. Stating lower-level for Rabbit MQ does not mean it is underestimated. I understand from lower-level that it is not a more plug-and-play system than the other commercial products which generally uses Rabbit MQ at back-end. It is like preferring C# instead of C with which you must implement lots of fundamental libraries such as http clients or service bases. 

As a supporting argument, in this article, it is stated that:

> Of course, you could always build your own service bus features on top of lower-level technologies like RabbitMQ and Docker, but the work needed to “reinvent the wheel” might be too costly for a custom enterprise application.

**Comment by mvelosop** [comment]
Hi @Loreno10, thanks for the feedback.

Thanks @ccerhan for your comment too 😊, that's indeed the case.

Lower-level here means that it includes the core features, and then some, but there are other features that are important for production deployments that you'd have to implement yourself.

That's why the [Additional resources](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/integration-event-based-microservice-communications#the-event-bus) section in the article includes some production-grade offerings.

You can also take a look at the [wiki page from eShopOnContainers about Asynchronous messaging](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Asynchronous-messaging) for more information.

Hope this helps.

**Comment by mvelosop** [comment]
Closing this issue now but feel free to comment, will reopen if needed.
