### ISSUE TITLE
Transfer Learning

### ISSUE THREAD

**Issue by JamesCann** [dotnet/docs#17050]
I was reviewing one of the ML.NET Transfer Learning tutorials and came across this particular paragraph.

**Create a struct for Inception model parameters
The Inception model has several parameters you need to pass in. Create a struct to map the parameter values to friendly names with the following code, just after the Main() method:**

How does someone know where to get the parameters required for the Model?

**Comment by luisquintanilla** [comment]
Hi @JamesCann 

Thank you for your question. The parameters are specific to each model. In many cases, it's enough to know the height and width of the images used to train the model so when you try to use the model to classify / predict your data, you know the dimensions the model expects. In the case of this tutorial, the images were 224 x 224, which is what they're being resized to in the pipeline by the `ResizeImages` transform. With regards to the other parameters (scale, mean, channellast) they too are somewhat model specific. In the `ExtractPixels` transform, those parameters specify the order in which to get the pixels from an image. An pixel (color) can be represented by an array of values ranging from 0-255 corresponding to RGB. However, depending on how the image is stored, that representation can be in a specific order RBG,GBR,etc. Depending on the framework, that arrangement may differ. With regards to TensorFlow models, the typical arrangement is channel-last. Finally, the scaling / mean are used to normalize images. Because you're working with many values for each image (224 x 224 x 3 -> 150,528‬ values) each ranging from 0-255 it can help to normalize these values to fall between 0-1 to make it easier to compute and have all of the values in a more uniform range. That's where the mean and scale come in to normalize the pixel values as they're being extracted. In the tutorial, the scaling / channel last parameters were included to show some of the options available when consuming a TensorFlow model. However, as I mentioned in most cases, it is often enough to just know the height / width of an image.
