### ISSUE TITLE
dotnet clean is not deleting files in bin/debug/.netcore2.2

### ISSUE THREAD

**Issue by TestUser20191** [dotnet/docs#17139]
## Unable to delete files added using copyToOutputDirectory to PreserveLatest

I had a file with 
```
    <EmbeddedResource Include="Test.xml" > 
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
   </EmbeddedResource>
```
and have now updated it not to contain
```
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
```
in the .csproj file. 

When I try to run   _dotnet clean,_ the files which have been copied earlier still exists( Debug mode)

### Recommended action

- Should delete all files in that folder. 

### Category

- ASP.NET Core
- C#
- Core

### Affected APIs

     "Not detectable via API analysis"

---
#### Issue metadata

* Issue type: breaking-change

**Comment by gewarren** [comment]
I don't think this is a breaking change. A breaking change is an intentional change in behavior from a previous version. But I'm not sure that it's a bug either, because the [description of dotnet clean](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-clean#description) states that it only cleans the outputs created during the build, and test.xml isn't created during the build.

**Comment by gewarren** [comment]
I'm going to close this issue. If you still feel that there's a bug, please file an issue at https://github.com/dotnet/sdk/issues.
