### ISSUE TITLE
inheritdoc is per member?

### ISSUE THREAD

**Issue by JuanZamudioGBM** [dotnet/docs#17326]
For example with this interface:

```cs
/// <summary>
/// You may have some primary information about this interface.
/// </summary>
public interface ITestInterface
{
    /// <summary>
    /// Method documentation.
    /// </summary>
    void Method();
}

///<inheritdoc cref="ITestInterface"/>
public class TestClass : ITestInterface
{
    public void Method()
    {
    {
}
```

Method in TestClass will inherit the documentation also or do I have to add another &lt;nheritdoc /&gt; in Method as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04441bbc-7e98-d6df-2c5a-20e816d79dc7
* Version Independent ID: ba155807-a2b0-8982-abe7-fac1e2b51a7d
* Content: [&lt;inheritdoc&gt; - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/inheritdoc)
* Content Source: [docs/csharp/programming-guide/xmldoc/inheritdoc.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/xmldoc/inheritdoc.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
/cc @mikadumont 

Can you provide the answer? Then, we can get this doc updated.

**Comment by mikadumont** [comment]
Adding @sharwell

**Comment by JuanZamudioGBM** [comment]
@mikadumont  In that case there will we any changes in [CS1591](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1591)?

Right now if I remove the documentation from the method I get a warning,

**Comment by mikadumont** [comment]
Adding @sharwell

**Comment by sharwell** [comment]
The CS1591 warning would be related to https://github.com/dotnet/roslyn/issues/40325

**Comment by BillWagner** [comment]
Thanks for helping determine the correct update. I've added this to our backlog for when we next update this article.

**Comment by BillWagner** [comment]
reopening to address as part of updating the XML section

**Comment by ozdotnet** [comment]
Hi @BillWagner, Is this fixed with #23540? I'm on Visual Studio 2022 17.9.3 and using .NET 6.0 and I still encounter this.

Let's say I have an interface:
```csharp
///<summary>
/// Interface IFoo summary
///</summary>
public interface IFoo
{
    ///<summary>
    /// Foo method
    ///</summary>
    void Foo();
}
```

And it's implementation:
```csharp
/// <inheritdoc />
public class Foo : IFoo
{
    public void Foo() { ... }
}
```

Adding `/// <inheritdoc />` at class level should be enough (also based on this documentation: [Recommended XML documentation tags for a class and its members - C# | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#inheritdoc:~:text=Note%20that%20when%20you%20add%20the%20%3Cinheritdoc%3E%20tag%20to%20a%20type%2C%20all%20members%20will%20inherit%20the%20comments%20as%20well.). But I'm still getting the [CS1591](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1591) warning for the method. Am I doing something wrong?

**Comment by ozdotnet** [comment]
Hi @mikadumont, Can someone help with my question above please. Based on documentation adding `<inheritdoc />` on class level should be sufficient, and it is indeed sufficient. But warning [CS1591](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1591) keeps popping up in the IDE for the underlying methods. Does the analyser have to be updated also? Thanks

**Comment by sharwell** [comment]
> Based on documentation adding `<inheritdoc />` on class level should be sufficient, and it is indeed sufficient ...

The `<inheritdoc/>` at class level is not necessary for (and is ignored by) methods. The method receives default inherited documentation because it implements an interface member.

> But warning [CS1591](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1591) keeps popping up in the IDE for the underlying methods.

This was covered by a comment above. We have no control over this.
https://github.com/dotnet/docs/issues/17326#issuecomment-594928982

In projects I own and maintain, I generally disable three diagnostics to avoid noise:
https://github.com/dotnet/roslyn-analyzers/blob/332dd9ab9ec226d410cc4f42f7ebe24d4fdeb117/Directory.Build.props#L34-L46

**Comment by sharwell** [comment]
I'm not sure where that note came from, but [as the implementer](https://github.com/dotnet/roslyn/pull/36028) of `<inheritdoc/>` I'm fairly confident that it is not necessary. If that limitation does somehow exist, it would be part of the documentation pipeline and not part of Roslyn's handling of the feature.

**Comment by khlr** [comment]
I'm not sure if I correctly understand your last comment, @sharwell ...
What is "that limitation"?

Well in the end it seems to necessary to decorate each and every member with `<inheritdoc/>`. When it's only done at class level, VS keeps showing the warnings... Too bad it doesn't work at class level 😐
