### ISSUE TITLE
Example please!

### ISSUE THREAD

**Issue by noman9607** [dotnet/docs#17370]
A short code example (hello world?) with a comment block like 
#region "class summary"
/// &lt;summary&gt;
/// This class does something.
/// fields?
/// static
/// properties?
/// members?
/// &lt;/summary&gt;
Now give the whole csc command line to make it work. I can't get this doc to work using the csc command and I find the instructions cryptic-they make sense only if you already know how to use it. Pretend you have the helloworld.cs file with the comment block above at the top. Now what is the comman line to get the xml doc file?
thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99ceb5f1-d81a-ca44-6234-4b725e356328
* Version Independent ID: 2cd58b31-4d66-1b99-14a9-beb1d8de2c35
* Content: [-doc (C# Compiler Options)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/doc-compiler-option#feedback)
* Content Source: [docs/csharp/language-reference/compiler-options/doc-compiler-option.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/doc-compiler-option.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by MSDN-WhiteKnight** [comment]
There are examples of csc command line in this article: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/command-line-building-with-csc-exe

You can just append -doc to the end of these examples and it should work

**Comment by BillWagner** [comment]
There are a couple different changes that should happen here.

First, instead of `csc`, this should show how to use `dotnet build` to create documentation.

Second, it should link to [this article](https://docs.microsoft.com/dotnet/csharp/programming-guide/xmldoc/how-to-use-the-xml-documentation-features) which does show the example discussed above.

I'll add the "up for grabs" label based on a clear fix for what should happen here.
