### ISSUE TITLE
Replace language identifier to use the supported ones for OPS

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#1737]
We need to add the list of supported language to our [style guide](https://github.com/dotnet/docs/blob/master/styleguide/template.md#inline-code-blocks-with-language-identifier) and replace the alternative ones currently in use in our repo to the officially supported ones, since new features will be done based on those.

For example, replace \`\`\`cs with \`\`\`csharp, \`\`\`fs with \`\`\`fsharp, etc.

The list of supported identifiers can be found in this internal site:
https://review.docs.microsoft.com/en-us/csi/msdocs/code?branch=master

/cc @tompratt-AQ

**Comment by svick** [comment]
How hard would it be to support the alternative language names? That way, contributors would have one less thing to worry about.

**Comment by mairaw** [comment]
@adkinn can you please address this question?

**Comment by tompratt-AQ** [comment]
Here is some more information on this issue based searches of [our docs ](https://github.com/dotnet/docs/tree/master/docs ) and a comparison of the [Markdown Labels in the GFM list](https://github.com/jmm/gfm-lang-ids/wiki/GitHub-Flavored-Markdown-(GFM)-language-IDs )  that we currently endorse, and our internal list of [Supported Languages ](https://review.docs.microsoft.com/en-us/csi/msdocs/code?branch=master) that we want to replace it with:

While it is an excellent suggestion to make the coding easier for our contributors by supporting alternative names, what list of alternative language names (markdown labels) should we support? 
The GFM list? 
A list of our best guess at typical synonyms? 
If we go by the GFM list, for the 20 supported languages we currently have, there are 206 synonyms. Also, we are currently out of compliance with that list in the following ways:

- 332 Languages that we don't support (each with many acronymns listed) are on the GFM list.
- Azure CLI  =  Supported Language but no GFM Language ID.
- AzCopy  =  Supported Language but no GFM Language ID.
- NodeJS = Supported Language, no specific GFM Language ID but "njs" and "node" are listed under JavaScript.
- XAML  =  Supported language, but GFM lists it as a synonym for XML.
- Bash  =  Not a supported language. No GFM Language ID. Yet we have 11 instances in 3 files.

To match the Markdown Labels in our list of Supported Languages we just need to do the following:

C#  =  Change all 637 instances (266 files) from cs to csharp.
F#  =  Change 5 instances (1 file) from fs to fsharp.
JavaScript  =  Change 50 instances (8 files) from js to javascript.
PHP  =  Change 1 instance in 1 file from all uppercase "PHP" to "php". (Not Critical: because labels are case-insensitive.)
Add Bash to the list? =  Not on our supported language. No GFM Language ID. Yet we have 11 instances in 3 files.
Add HTML to the list? = Not on our supported language list, but we have one instance in one file.

**Comment by svick** [comment]
@tompratt-AQ Thank you for considering my suggestion.

> what list of alternative language names (markdown labels) should we support? The GFM list?

I think staying close to the GFM list makes sense, but it doesn't have to exact.

Adding languages on the GFM list that are currently not supported doesn't make much sense, considering that most of them will likely never be used on docs.ms. And I don't see any issue with supporting languages not on the GFM list, or having a specific version for some languages that GFM has as synonyms.

> Bash = Not a supported language. No GFM Language ID. Yet we have 11 instances in 3 files.

Actually, GFM has bash as synonym for Shell.

> To match the Markdown Labels in our list of Supported Languages we just need to do the following

You have to do that now, but I think you will also have to keep reminding new contributors that they can't use language ID synonyms that they know from GFM and that work in GitHub previews of their contributions.

**Comment by mairaw** [comment]
I'll keep discussing this with the team @svick. I agree with you that supporting cs and fs for example would be the most convenient. I need to file a request for them to also support newer identifiers like xml or sql. So I'll keep you posted, Thanks!
