### ISSUE TITLE
Misleading internal definition

### ISSUE THREAD

**Issue by skarllot** [dotnet/docs#17420]
The documentation says "Internal members are visible only in derived classes that are located in the same assembly", that is not true. Internal members are visible to all classes of same assembly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e813a38-d487-25dc-b70d-23fca9c47221
* Version Independent ID: 92fb3bd2-56a5-e060-8056-491aab145d26
* Content: [Inheritance in C#](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/inheritance#feedback)
* Content Source: [docs/csharp/tutorials/inheritance.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/inheritance.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @skarllot. That should be worded better.  It's correct on a careful read, because the entire bullet list is about the accessibility of members declared in a base class as seen from a derived class. 

That said, it is poorly written and should be updated. I've added this to our backlog to fix when we next update this article.

I've also added the "up for grabs' label if any community members want to update this in the meantime.
