### ISSUE TITLE
Still not updated

### ISSUE THREAD

**Issue by RachelAmbler** [dotnet/docs#17431]
Despite the previous issue being closed, this page still shows as being proposed. Is there a reason that this page has not been updated to show it's final?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d273731d-0f9a-1870-1275-bde4f4b3f69d
* Version Independent ID: 7d8b872e-6d86-77c1-2fad-afa110ab8f4c
* Content: [Null coalescing assignment - C# 8.0 specification proposals](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/null-coalescing-assignment#feedback)
* Content Source: [proposals/csharp-8.0/null-coalescing-assignment.md](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/null-coalescing-assignment.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @RachelAmbler 

In this section (under the C# specification), these features are listed as "proposed", because they have not yet been accepted into the ECMA standard, or the Microsoft proposed updates (listed in the C# 6 draft specification).

Admittedly, the committee is behind. (I'm on the committee, and we are working on the plan to update the official standard through the standards bodies). 

The [overview](https://docs.microsoft.com/dotnet/csharp/language-reference/) page for this section does explain the state. I'd like to know if that's hard to find so we can increase visibility for that explanation.
