### ISSUE TITLE
SSL Development

### ISSUE THREAD

**Issue by napalm684** [dotnet/docs#17552]
This article feels incomplete.  We are pushing devs to work with SSL from the beginning yet all the above is http?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b69a4b5-2003-e7a5-97a3-59e3737ea1ef
* Version Independent ID: c8fefbe8-6f9b-209a-3563-2cb51384707c
* Content: [Development workflow for Docker apps](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/docker-application-development-process/docker-app-development-workflow#feedback)
* Content Source: [docs/architecture/microservices/docker-application-development-process/docker-app-development-workflow.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/docker-application-development-process/docker-app-development-workflow.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @napalm684 , thank you for your feedback. 

Could you please share one example for us to review the specific section ? So that it would be easy for us to update the necessary details.

**Comment by sughosneo** [comment]
Hi @napalm684 , did you get a chance to look into it ? Or we can close this as of now and revisit it later. 
Please share your thoughts. 

Thank you.

**Comment by napalm684** [comment]
@sughosneo sorry for the delay. I revisited the docs and for every Docker file example port 80 is exposed not 443. The Docker compose example has http URLs. Linux containers have different constraints around using the locally installed certs for development etc.

The bottom line is best practice wants us to work with SSL from the beginning but here the official docs only cover HTTP. I think we can do better as a community to document the best practices rather than the easy win setup.

Does this help?

**Comment by sughosneo** [comment]
Hello @napalm684, Yes that's clear now. Thank you for your feedback. 

Most of the docker files in reference application `eShopOnContainers` only exposes port 80 than 443 because of the following reasons. 

1) All of these are internal communication and will stay behind the API gateway within a secure network/subnet.
2) And also to avoid self-signed certificate complexity for the beginners.

Yes, for the Production or Staging scenario it's recommended to use HTTPS with a valid certificate. For e.g you may want to refer [AKS TLS](https://github.com/dotnet-architecture/eShopOnContainers/wiki/AKS-TLS) wiki page which talks about `how to enable TLS on AKS for eShopOnContainers`?`

Hope this clarifies !

**Comment by sughosneo** [comment]
Hi @napalm684 , I am closing this issue as of now. If you have any further questions, please feel free to reopen it.

Thank you
