### ISSUE TITLE
Please explain why it is recommended to target the lowest version possible

### ISSUE THREAD

**Issue by cosminiv** [dotnet/docs#17555]
This sentence seems counter-intuitive to me, could you please add some explanations about it?
"In general, we recommend you to target the lowest version of .NET Standard possible"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb8b774-c6f0-8235-6964-15219baf2ea7
* Version Independent ID: 6819a4a7-7527-d8c7-e132-767f7344e00e
* Content: [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#feedback)
* Content Source: [docs/standard/net-standard.md](https://github.com/dotnet/docs/blob/master/docs/standard/net-standard.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
I think the key is this sentence: "The lower the version, the more platforms implement it.". This means that the lower the version of .NET Standard that you target, the more platforms your code can run on. For example, if your code targets .NET Standard 1.1, it can run on .NET Framework 4.5 and later and .NET Core 1.0 and later. But if you target .NET Standard 2.1, your code can only run on .NET Core 3.0 and later (and not .NET Framework).

**Comment by SangeetAgarwal** [comment]
I'm developing a .net core 3.1 app but it has to consume a .nuget package that targets net45/net461/net451 framework.

If for the new .net core 3.1 app, I choose target framework as .netcoreapp3.1 then it wouldn't work.

Which framework should I then target, .net Standard 1.1?

Are there any trade-offs for using say .net standard 1.1 as the target framework instead of .netcoreapp3.1?
