### ISSUE TITLE
MSI must be run elevated

### ISSUE THREAD

**Issue by DavidWBrooks** [dotnet/docs#17585]
At least on my Win10 system, double-click the MSI doesn't work. It must be run elevated (or from an elevated CMD prompt). I left this issue on github, but I don't think it was from this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 289d3b2b-8b21-d0a0-10fa-9a8b3fdb62ce
* Version Independent ID: 3145ef37-2a19-e3ca-ba78-95c2f1a41a6b
* Content: [Uninstall Tool - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/uninstall-tool?tabs=windows&source=docs#feedback)
* Content Source: [docs/core/additional-tools/uninstall-tool.md](https://github.com/dotnet/docs/blob/master/docs/core/additional-tools/uninstall-tool.md)
* Product: **dotnet-core**
* GitHub Login: @sfoslund
* Microsoft Alias: **dotnetcontent**

**Comment by sfoslund** [comment]
Since our installation instructions are located on the [releases page of our repository](https://github.com/dotnet/cli-lab/releases), I'm closing this issue in favor of [the one filed on our repo](https://github.com/dotnet/cli-lab/issues/133). I will reopen if that discussion results in a docs change.
