### ISSUE TITLE
Forecast is the Average of the Actual Rentals

### ISSUE THREAD

**Issue by asif48** [dotnet/docs#17644]
Hi Author...Its a simple and nice example of coupling of Machine Learning with asp.net...
From the graph its reflects that the Forecast  is the average of the Actual Rentals, which is not good. 
How can we improve the prediction of the algorithm? How can we predict for the upcoming dates of the month?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32d03435-cc6c-1123-a86c-d5c3eacc24bd
* Version Independent ID: 460afd2b-383d-7b90-6804-4b900c3bc9b2
* Content: [Tutorial: Forecast bike rental demand - time series - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/time-series-demand-forecasting)
* Content Source: [docs/machine-learning/tutorials/time-series-demand-forecasting.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/time-series-demand-forecasting.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by asif48** [comment]
If anybody can answer my question?

**Comment by luisquintanilla** [comment]
Hi @asif48 

Thank you for your question. Using the SSA transformers, since you're only using a single value, the time series, there are few tweaks you can make to improve your model. One way to go about it is to tweak the parameters such as the window size. Another way, although it doesn't exactly factor in seasonality out of the box is to use one of the regression transforms to predict forecast values. See this sample for using regression for forecasting.

https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/Forecasting-Sales
