### ISSUE TITLE
Update VS for Mac tutorial unit testing guidance

### ISSUE THREAD

**Issue by GuardRex** [dotnet/docs#1770]
Current unit testing guidance is to run the tests via the command line instead of from within the IDE and to run the project directly as opposed to using the Play button. The doc makes these compromises due to the inability of xUnit to discover tests properly. The doc should be updated to run the tests and run the project from the IDE.

**Comment by lextm** [comment]
This issue description is not accurate.

1. xUnit.net based .NET Core testing can run properly without xamarin.xunit extension, as it seems to use `dotnet test` directly to pull the results. Thus, I don't think xunit/xamarinstudio.xunit#60 is blocking here.
2. xunit/xamarinstudio.xunit#60 and its related items are only affecting Mono based projects.

So when reading [this article](https://docs.microsoft.com/en-us/dotnet/core/tutorials/using-on-mac-vs-full-solution) I could not fully understand why xunit/xamarinstudio.xunit is ever mentioned. If you plan to update the article to reflect the latest, you might remove the reference.

**Comment by GuardRex** [comment]
@lextm I just needed to remove that language. It wasn't clear at the time I put this up back in March where the blockage was. It's all working now from the IDE, so the PR here fixes the doc to show how to run the tests from the IDE.

On the other issue, there was an open bug report for it ... https://bugzilla.xamarin.com/show_bug.cgi?id=56921 ... so I think they'll have that fixed soon.

Thanks for explaining here and in the other issue how those bits are setup. With your help and that of @akoeplinger, we'll have smooth ⛵️sailing ⛵️ as soon as that last VSMac UI issue is addressed.

**Comment by lextm** [comment]
@GuardRex thanks. When you initially raised the issue xunit/xamarinstudio.xunit#60 I was not able to learn all the details either. That's probably a situation everyone wouldn't want to see. Glad to see that everything works fine right now.

Since this article fully focuses on .NET Core development in VS for Mac, I think we can safely ignore xamarinstudio.xunit in it. If users do have Mono projects, they should use other channels to find the extension.

BTW, xUnit.net 2.3 seems to introduce significant changes (they moved from `dotnet test` to `dotnet xunit`) for .NET Core project unit testing. So I suggest this article explicitly states that everything is written against xUnit.net 2.2. That can save the readers a lot of time if they happen to upgrade to xUnit.net 2.3 without noticing the incompatibilities.

VS for Mac should be updated to support xUnit.net 2.3 once it is officially available, and then this article might need a new revision.
