### ISSUE TITLE
How can I make prediction from Retrained-Model

### ISSUE THREAD

**Issue by gia01020304** [dotnet/docs#17782]
Hello guy,
I followed your guide to retrain the model. After that how to make a prediction I tried using dataPrepPipeline.Append(retrainedModel) but the result of prediction did not look right.
Thank you,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0366cc46-bc07-44fd-72d9-d37b40bd5eca
* Version Independent ID: 5c20d041-f946-d7c8-b0b5-7bee96e90282
* Content: [Re-train a model - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/retrain-model-ml-net#feedback)
* Content Source: [docs/machine-learning/how-to-guides/retrain-model-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/retrain-model-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @gia01020304 ,

What you want to do is either use the transforer itself

```csharp
var predictions = retrainedModel.Predict(dataViewToPredict);
```

or create a PredictionEngine.

See the following resources on how to make predictions.

https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/machine-learning-model-predictions-ml-net

**Comment by gia01020304** [comment]
Thank you for replying me, but it could not help me solve the problem,
`MulticlassPredictionTransformer<MaximumEntropyModelParameters> retrainedModel` with method **Predict not found**.
When I create predictions from retrainedModel
` mlContext.Model.CreatePredictionEngine<IrisData,IrisPrediction>(retrainedModel);` I received an error **Features not found**

**Comment by luisquintanilla** [comment]
@gia01020304 

The reasons for the first error is because a MulticlassPredictionTransformer doesn't implement the Predict method. Predict can only be called from a PredictionEngine which operates on a single instance of data. With MulticlassPredictionTransformer you can use Transform which operates on an IDataView. 

The second issue I assume happens because I'm guessing the IrisData class does not have a column called Features. Therefore, the PredictionEngine can't find that column.
