### ISSUE TITLE
Unnecessary using directive

### ISSUE THREAD

**Issue by Camios** [dotnet/docs#17828]
I have a class "Foo" in the default namespace of an assembly "Abc". I have a class "Bar" in another namespace "Abc.Def" of the same assembly. Why is it that I can use "Foo" in "Bar" without adding a using directive "using Foo;"?
i.e. I had a using Foo; directive, but Visual Studio says it is unused. I remove it and the code compiles.
The same thing happens when I use Foo from Bar's unit test project (different assembly and namespace). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7569e51d-92c7-294a-2d5f-e1ab3c35fdf8
* Version Independent ID: 86a1c11a-1d3c-902b-6cf3-5c004c59a856
* Content: [using directive - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-directive)
* Content Source: [docs/csharp/language-reference/keywords/using-directive.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/using-directive.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Good questions @Camios 

> Why is it that I can use "Foo" in "Bar" without adding a using directive "using Foo;"?

This is because `Bar` is declared in the namespace `Abc.Def`, all names in the global namespace, the `Abc` namespace and the `Abc.Def` namespace are in scope. 

> The same thing happens when I use Foo from Bar's unit test project (different assembly and namespace).

I'd need to see the code in Bar's unit test project, but my first thought is that the unit test project is in a namespace that's part of the `Abc` namespace.

I'll close this as an answered question. If you have more questions, let us know.
