### ISSUE TITLE
Could the team add more information about the topic "thread-safe-delegate-invocation"

### ISSUE THREAD

**Issue by BrayanKhosravian** [dotnet/docs#17867]
Could the team please add some more detailed explanation about the topic thread-safe-delegate-invocation
I mean thats a very interesting and essential topic imo. And there is only one line written:
"Use the ?. operator to check if a delegate is non-null and invoke it in a thread-safe way (for example, when you raise an event), as the following code shows"

Could the team explain why the ?. operator makes the invocation thread safe?
Sincerely and thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a25abe4-2b4e-119e-85e9-af19ed06e8c0
* Version Independent ID: 682b8c86-e49a-1d6d-8562-c9f919082bdc
* Content: [Member access operators and expressions - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators#thread-safe-delegate-invocation)
* Content Source: [docs/csharp/language-reference/operators/member-access-operators.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/member-access-operators.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@BrayanKhosravian the section goes on with the following words:

> That code is equivalent to the following code that you would use in C# 5 or earlier:
>
>```csharp
>var handler = this.PropertyChanged;
>if (handler != null)
>{
>    handler(…);
>}
>```

That is thread-safe (in the sense that we are sure to invoke a non-null delegate) because it atomically takes the snapshot of event handlers into the `handler` variable. If `handler` is not `null` at the check `handler != null`, it's also not `null` when it's called like `handler(...)` (even if somebody subscribes to or unsubscribes from `PropertyChanged`, it doesn't affect the value referenced by `handler` because delegate instances are immutable values).

Contrary, the following code
```csharp
if (PropertyChanged != null)
{
    PropertyChanged(…);
}
```

might fail: between the `true` non-null-check and invocation all event subscribes may unsubscribe in another thread and the `PropertyChanged` would be `null` at its invocation time.

**Comment by BillWagner** [comment]
Thanks for writing this @BrayanKhosravian And for the explanation @pkulikov 

It would be good to extend this with the text in the previous comment. That's a great explanation for why the `?.` operator provides the safety.

**Comment by BrayanKhosravian** [comment]
@pkulikov that makes sense and is exactly what i was looking for.
Thanks for the explanation.
