### ISSUE TITLE
port-to-core

### ISSUE THREAD

**Issue by efesar** [dotnet/docs#17934]
"For a full list, see the CoreFX issues marked as port-to-core"

The link in this sentence to port-to-core leads to a deprecated project on GitHub.

https://github.com/dotnet/corefx/issues?q=is%3Aopen+is%3Aissue+label%3Aport-to-core

From that project's readme:

Going forward, the .NET team is using https://github.com/dotnet/runtime to develop the code and issues formerly in this repository.

Please see the following for more context:

dotnet/announcements#119 "Consolidating .NET GitHub repos"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b76cb0d-df6d-88c4-557d-ad327a566eef
* Version Independent ID: 95083e1c-ef53-e813-08e2-1aa31b431f00
* Content: [Choose between .NET Core and .NET Framework for server apps](https://docs.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server?toc=%2Faspnet%2Fcore%2Ftoc.json&bc=%2Faspnet%2Fcore%2Fbreadcrumb%2Ftoc.json&view=aspnetcore-3.1#feedback)
* Content Source: [docs/standard/choosing-core-framework-server.md](https://github.com/dotnet/docs/blob/master/docs/standard/choosing-core-framework-server.md)
* Product: **dotnet**
* GitHub Login: @cartermp
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@efesar Thanks for bringing this up. Unfortunately it looks like the old issues haven't been transferred to the runtime repo yet, so until they do, I think we need to keep this link as-is.

**Comment by svick** [comment]
@gewarren First, all issues from dotnet/corefx have been transferred to dotnet/runtime, though it seems the port-to-core label wasn't. For example, based on [this archive.org page](https://web.archive.org/web/20190110014656/https://github.com/dotnet/corefx/issues?q=is%3Aopen+is%3Aissue+label%3Aport-to-core), the issue [dotnet/corefx#33897](https://github.com/dotnet/corefx/issues/33897) used to have that label, but the transferred issue, https://github.com/dotnet/runtime/issues/28101 does not. (Also, the link is now confusing, since it shows PRs, not issues.)

Second, based on https://github.com/dotnet/announcements/issues/130, porting from .Net Framework to .Net Core is now over. So I think this part of the article is outdated and should be either removed, or at least significantly reduced.

**Comment by gewarren** [comment]
@svick Thanks for that, I should have looked into this more deeply. I have a PR to remove that section of the article.
