### ISSUE TITLE
Process A should have Console.ReadLine(); as last line of code

### ISSUE THREAD

**Issue by GabrielZalisz** [dotnet/docs#17950]
Please add Console.ReadLine(); as last line of code in process A. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcc02010-ec28-4e04-0881-7cd1d9d8b148
* Version Independent ID: c5261008-5deb-2af9-647f-f07ec56d9e47
* Content: [Memory-Mapped Files](https://docs.microsoft.com/en-us/dotnet/standard/io/memory-mapped-files#feedback)
* Content Source: [docs/standard/io/memory-mapped-files.md](https://github.com/dotnet/docs/blob/master/docs/standard/io/memory-mapped-files.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
Hello @GabrielZalisz Can you clarify the request? Are you saying that you want a readline at the end so you can pause and analyze the output?

I believe this has been added in the latest versions of .NET, starting with .NET Core. I wouldn't want to put one in since this is the new standard and then would require two keypresses at the end.
