### ISSUE TITLE
List of value types

### ISSUE THREAD

**Issue by mrlife** [dotnet/docs#17980]
Since `DateTime` is in `System`, I thought it would have been listed on this page in the Value Types listing: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/types#value-types. Would it make sense to include it on this page? If not, is there a list of all value types somewhere in the docs?

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de24f644-5e7c-d3de-fd13-5969bb3e4b78
* Version Independent ID: 9173876e-49be-6c60-634d-eeb1944ab2fc
* Content: [Types - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/types#value-types)
* Content Source: [spec/types.md](https://github.com/dotnet/csharplang/blob/master/spec/types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi @mrlife,
Thank you for sharing your thoughts on this document. In looking at the section in question, while I understand where you are coming from because `System.DateTime` is a `struct` - I do not believe it is appropriate to add to this doc. The value types in this doc are "simple types which are identified through reserved words". There is no reserved word for "datetime".

The same would be true for other types under `System`, such as  `System.Timespan` and `System.Range` for example. In other words, not all value types under system have a corresponding reserved word. I hope this is helpful, and again thank you for raising this concern. I'm going to close this issue, but if you have additional questions - please do not hesitate to reach out. Thank you

**Comment by mrlife** [comment]
Hi @IEvangelist, thank you for the thoughtful response. Is there a page that lists all value types (simple and other) or a way to see them all? For example, value types can be nullable, so it would be good to have a reference for that.

**Comment by IEvangelist** [comment]
Hi @mrlife,
Are you asking for a listing of all value types under the `System` namespace? I'm not aware of any complete listing, that would be a massive list and as packages add additional objects to the namespace - I'm not sure how that would be managed. The .NET API browser might be beneficial: https://docs.microsoft.com/en-us/dotnet/api/system?view=netframework-4.8

**Comment by mrlife** [comment]
@IEvangelist In Entity Framework Core, value types are required by default, whereas other types are optional by default. Looking for a reference for that purpose is what led me to creating this issue. The best way to learn the value types may be to look up a given data type, as needed, to see if it's a value type. Thanks for your help!
