### ISSUE TITLE
Add linux package manager install instructions for CentOS 8

### ISSUE THREAD

**Issue by dagood** [dotnet/docs#18019]
.NET Core [is available on CentOS 8 AppStream](https://pkgs.org/download/dotnet-sdk-3.1). It seems like we should have a page for that, like we do [for RHEL 8](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-rhel8).

@leecow @rbhanda @dleeapho 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b603e29-5301-fcb8-d3e2-13db7ec842ed
* Version Independent ID: aa2f9276-c77a-5e60-a02b-d96cb511d8f9
* Content: [Install .NET Core on CentOS 7 - package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-centos7)
* Content Source: [docs/core/install/linux-package-manager-centos7.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-centos7.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by omajid** [comment]
Just an FYI that "CentOS 8 Appstream" is normal CentOS 8. CentOS 8 (and RHEL 8) provide packages in a number of different repsitories (mostly because of RHEL 8's different support policies for different repositories). The to main repositories, "BaseOS" and "AppStream", are both enabled by default on RHEL 8 and CentOS 8 systems.

If there's any chance of user-confusion, we could just call it "CentOS 8" in docs instead of "CentOS 8 Appstream".

**Comment by Mizux** [comment]
FYI the page https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-centos8 is still not in the "toc tree" in the left and you can't select it from the drop down menu (currently I see `Ubuntu 19.10`) selected

**Comment by omajid** [comment]
Doh. Forgot to do those changes. Let me open a new PR
