### ISSUE TITLE
Clarity required over NRT approach for Data Transfer Objects.

### ISSUE THREAD

**Issue by alistairjevans** [dotnet/docs#18099]
As requested by @BillWagner on twitter, I'm raising an issue around Nullable Reference Types and how they apply to Data Transfer Objects (DTOs).

Up until the introduction of NRTs, Data Transfer Objects have often not had an explicit constructor:

```csharp
class Student 
{
        [Required]
        public string FirstName { get; set; }

        [Required]
        public string LastName { get; set; }

        public string OptionalField { get; set; }
}
```

Mandatory fields (that cannot be null) were marked with ``[Required]`` or a similar appropriate attribute.

When we introduce NRTs, things get a bit more complicated as we attempt to use NRTs, where they overlap with what are effectively schema/business constraints.

```csharp
using System.ComponentModel.DataAnnotations;

namespace NullDto
{
    // Example Data Transfer Object - *not* specific to any ORM.
    //
    // From the perspective of the application, the [Required] fields are not optional, but are often 
    // populated automatically by a deserialiser. So there is an empty constructor to allow for that, which
    // results in the below warnings.
    class Student 
    {
        // warning CS8618: Non-nullable property 'FirstName' is uninitialized. Consider declaring the property as nullable.
        // warning CS8618: Non-nullable property 'LastName' is uninitialized. Consider declaring the property as nullable.
        public Student()
        {
            // Empty constructor used for deserialisation. 
        }

        public Student(string firstName, string lastName)
        {            
            // Constructor used when creating a new Student in code.
            FirstName = firstName;
            LastName = lastName;
        }

        [Required]
        public string FirstName { get; set; }

        [Required]
        public string LastName { get; set; }

        // No warning here, this field is actually optional (note no [Required] attribute).
        public string? OptionalField { get; set; }
    }
}
```

I could simply indicate that ``FirstName`` and ``LastName`` may in fact be null, but that's only true from a **language** standpoint; in practice, they will never be null, and I don't want to add to the cognitive load for developers by forcing them to check for null on properties that in practice are never null.

Current Options:

- Disable nullable behaviour in that one file (don't like that).
- Initialise ``FirstName`` and ``LastName`` to some default value (like ``String.Empty``) in the default constructor. Not a fan either; might work for strings, but becomes very complicated for any more interesting types.
- Suppress the warnings on the constructor. Again, not ideal, but at least it gives us an opportunity to document why we've done it.

Possible Solutions:

- Decorate a property with an attribute, like ``[ExternallyInitialized]`` or something similar, which indicates that a property is set externally. This could also mean that instantiating an instance through property initialization would generate warnings if you *didn't* set that property. Might have some overlap with the planned ``init`` access modifier?
- Treat classes differently if they have ``[Serializable]`` on the type (or something like that).

Anything else? I don't know what the best practice is here, or if I've missed something major?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a690704d-da32-dca7-ea3e-66b84fb1d00d
* Version Independent ID: 11f314de-dd3a-362e-b2bb-d0a2133cfc7b
* Content: [Nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references)
* Content Source: [docs/csharp/nullable-references.md](https://github.com/dotnet/docs/blob/master/docs/csharp/nullable-references.md)
* Product: **dotnet-csharp**
* Technology: **csharp-null-safety**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @alistairjevans That's a great explanation


adding @cartermp, @ajcvickers and @JeremyLikness  (Phillip has been involved in the nullable attributes, and Arthur & Jeremy are involved with EF and may have already solved this.

I think we can annotate these properties to use the nullable attributes to convey the design you've made. I've added this issue to the current sprint to address this month.

**Comment by ajcvickers** [comment]
+ @Shay Rojansky<mailto:Shay.Rojansky@microsoft.com>

**Comment by roji** [comment]
FWIW this is a well-known problem that's been raised in various issues (e.g. https://github.com/dotnet/csharplang/issues/2452#issuecomment-486685742, https://github.com/dotnet/csharplang/issues/3033, and many others).

Some of the pain may be alleviated by [Init Only Members](https://github.com/dotnet/csharplang/pull/3367/files), which would hopefully allow you to initialize a read-only member via an initializer (and not only via the constructor), although that doesn't fully address the concern here.

Please take a look at [the guidance we've written around DTOs for Entity Framework Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types#non-nullable-properties-and-initialization). The most complete/correct pattern IMHO would be for the DTO to have a nullable backing field, exposed by a non-nullable property whose getter throws if the backing field is null (i.e. uninitialized). This provides a strict non-nullable contract for users of the DTO, and at the same time allows for late initialization.

Since this pattern is somewhat verbose, I personally think that in some context it's sometimes acceptable to simply declare the property non-nullable but to initialize it to null. This is similar to the previous pattern, except that the exception is thrown later (when the value is dereferenced, not when it's retrieved), and the exception type itself is NRE instead of, say, InvalidOperationException.

**Comment by alistairjevans** [comment]
Thanks @roji, the two options listed in your guidance make lots of sense.

I suppose it's up to the developer whether they want to use the more verbose form of manually throwing an exception, or the terser (but perhaps slightly stranger) form of setting ``null!``.

Might I propose that since the issue you've documented for EF Core applies to general DTO class patterns outside of EF Core, that either a link to that content gets placed in the main C# docs for NRTs, or a more general form of that content makes its way into the C# docs somewhere? That would help people who do a lot of DTOs, but not EF.

I don't mind putting a PR together with that content, if @BillWagner could let me know the best location for it.

**Comment by roji** [comment]
Sounds great @alistairjevans. Ping me on the PR, I can also help out.
