### ISSUE TITLE
Typo in "Default interface methods"

### ISSUE THREAD

**Issue by moerwald** [dotnet/docs#18227]
"Default interface methods affects". I think it should be "affect" instead of "affects"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36588d0-6bdf-1740-220c-10b20bb88730
* Version Independent ID: 587ed47f-f532-e018-9b0d-6ee76afd20e4
* Content: [What's new in C# 8.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8)
* Content Source: [docs/csharp/whats-new/csharp-8.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-8.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi @moerwald,
Thanks for posting this issue. I added the `up-for-grabs` label on this issue, and hope that you'd be willing to send a pull request our way. Feel free to propose the change with the "Edit" button on the article - https://github.com/dotnet/docs/edit/master/docs/csharp/whats-new/csharp-8.md. Otherwise, we will try to get to this change sometime later.

**Comment by augustoproiete** [comment]
This issue was resolved by #18228

**Comment by IEvangelist** [comment]
Resolved by #18228
