### ISSUE TITLE
dotnetstandard 2.1 c# 8 and The event can only appear on the left hand side of += or -=

### ISSUE THREAD

**Issue by djary** [dotnet/docs#18223]
I'm using dot net standard 2.1 and c# 8, I want to create an event for my class (interface), I follow [this tutorial](https://docs.microsoft.com/en-us/dotnet/standard/events/#events) and I wrote an interface:

```
using System;
using Crawler.Paging;

namespace Crawler
{
    public interface ICrawler
    {
        public event EventHandler NextPage;
        protected virtual void OnNextPage(EventArgs e)
        {

            EventHandler handler = NextPage;
            handler?.Invoke(this,e);
        }
        void Paging(IPaging paging);
    }
}
```
but take me an error:

> Error The event 'ICrawler.NextPage' can only appear on the left hand side of += or -=

I proceeded with this training, so where is the problem?
[stackoverflow link](https://stackoverflow.com/questions/61558648/the-event-can-only-appear-on-the-left-hand-side-of-or-dotnetstandard-2-1?noredirect=1#comment108890744_61558648)

**Comment by IEvangelist** [comment]
Hi @djary,

Thank you for posting this issue. You're actually deviating from the tutorial, in the tutorial it shows how to use events with a `class`. Instead, you're attempting to use an `interface` with a default method implementation. This happens when using a default method implementation with an `interface`. If you change from an `interface` to a `class`, like demonstrated in the tutorial this will work. As of right now, accessing event members in default interface methods is not supported.
