### ISSUE TITLE
Property pattern unduly complex

### ISSUE THREAD

**Issue by DickBaker** [dotnet/docs#18349]
The doc code is currently
public static decimal ComputeSalesTax(Address location, decimal salePrice) =>
    location switch
    {
        { State: "WA" } => salePrice * 0.06M,
        { State: "MN" } => salePrice * 0.075M,
        { State: "MI" } => salePrice * 0.05M,
        // other cases removed for brevity...
        _ => 0M
    };

whereas this is simpler and avoids multiple Get access calls
public static decimal ComputeSalesTax(Address location, decimal salePrice) =>
    location.State switch
    {
        "WA" => salePrice * 0.06M,
        "MN" => salePrice * 0.075M,
        "MI" => salePrice * 0.05M,
        // other cases removed for brevity...
        _ => 0M
    };

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36588d0-6bdf-1740-220c-10b20bb88730
* Version Independent ID: 587ed47f-f532-e018-9b0d-6ee76afd20e4
* Content: [What's new in C# 8.0 - C# Guide](https://docs.microsoft.com/en-gb/dotnet/csharp/whats-new/csharp-8)
* Content Source: [docs/csharp/whats-new/csharp-8.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-8.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
1. [That section](https://docs.microsoft.com/en-gb/dotnet/csharp/whats-new/csharp-8#property-patterns) is specifically about property patterns, so a simplification that does not use property patterns would be not be useful. (Though maybe changing the code so that it couldn't be simplified so easily could be useful.)
2. It actually does not avoid extra getter calls, because using the property pattern this way means there is only one getter call. You can see this when you look [at the decompiled code for that method](https://sharplab.io/#v2:D4AQTABAwgsAUAb3hFEQGY0EYBsEAmApgMYCWAtgIYA20A9uQA4CuALoQMo2EDOAKpQAeACgCC+fACdePCNTrFKrUnQB2AGgIkKNCD24AFSaWKEAlBAC8APmSp78xcrV6A7qVbEAFnfsokcH5BEAgQHKxKhABcEABEAOqisRAAvlbWeobGphAAVBAADAB0BTgAsuq+wf5hEewxsWUAcslpNpnUhEYmhHmFJQDsAKwVVdWh4ZENZQCSrekdXdm9+cUFI5WB1agA9DsQdKxehJIQijy8ENLkdABuhPgQAGZ0pwBG0rceAJ5Ff2PBAD6CwKZQBKBSAG54Cl4PBwBBxFIZPAAvYMNgCrVIiEIABzQisSGpGFAA==).

**Comment by BillWagner** [comment]
Thanks for writing this @DickBaker and for the explanations @svick 

We should look for a better example where a property pattern could not be simplified away.

**Comment by mitchcapper** [comment]
Just use the country?
```
location switch
			{
				{ Country: "US", state:"WA" } => salePrice * 0.08m,
				{ Country: "UK"} => salePrice * 0.2m,
			};
```

**Comment by BillWagner** [comment]
Closing this as the "what's new" article no longer include C# 8 features.
