### ISSUE TITLE
Clarify the behavior of Encoding.RegisterProvider with respect to multiple providers and defaults

### ISSUE THREAD

**Issue by mklement0** [dotnet/docs#1837]
Note: Currently, only the Framework docs at https://msdn.microsoft.com/en-us/library/system.text.encoding.registerprovider(v=vs.110).aspx have a description of the method (quoted below), but I expect that to become the content at https://docs.microsoft.com/en-us/dotnet/core/api/system.text.encoding

* It seems that calling Encoding.RegisterProvider not only makes additional code pages available, but _also changes the default code page_, as reported by `Encoding.GetEncoding(0)`. This important aspect should be stated explicitly. Currently, the docs only say:

> makes character encodings available on a platform that does not otherwise support them. Once the encoding provider is registered, the encodings that it supports can be retrieved by calling any Encoding.GetEncoding overload.

While you could argue that the above also implies that  `Encoding.GetEncoding(0)`  will be provider-specific, I suggest making that more obvious.

* It seems that only _one_ provider can be registered at the time (last one registered wins), but that is not entirely clear:

> If the RegisterProvider method is called to register multiple providers that handle the same encoding, the last registered provider is the used for all encoding and decoding operations. Any previously registered providers are ignored.

I find the first half of that sentence confusing (you cannot actually register multiple providers, as the second half states, and what does "the same encoding" refer to, and why does it matter, if the newly registered provider replaces the previous one?), and if my interpretation is correct, I suggest simply trimming down the sentence to:

> The last registered provider is the used for all encoding and decoding operations. Any previously registered providers are ignored.

**Comment by rpetrusha** [comment]
@tarekgh Could you review this, please?

**Comment by tarekgh** [comment]
For Encoding.GetEncoding(0) we need to clarify that when there is no registered provider, we return UTF8 encoding. when a provider is register, the provider can return different Encoding than UTF8. I would avoid mentioning the word "Default" because this will confuse it with the property Encoding.Default. Also it is worth mentioning when using the provider from System.Text.Encoding.Codepages, Encoding.GetEncoding(0) will return the encoding matching the system ACP when running on Windows OS. 

For registering multiple providers, I am seeing trimming the sentence as suggested is not enough. we can have a provider that provide some encodings but not all encodings. at that case if the caller requested an encoding which is not supported by last registered provider would results to try the previous registered provider and so on till we find a provider can return the specified encoding. Personally I am seeing the current sentence is not confusing but it looks not clear to @mklement0 so we may think in rephrasing it.

@rpetrusha please let me know if you have any more questions

**Comment by rpetrusha** [comment]
Thanks @tarekgh. And thanks, @mklement0, for opening this issue. I've assigned it to myself, and will update the docs.

**Comment by mklement0** [comment]
Thanks, @rpetrusha.

Honestly, even after reading this I'm slightly confused, so I'll try to summarize the rules here - please tell me if that covers all aspects:

* By default, `Encoding.GetEncoding(0)` -  code page ID `0` signifying a default value of sorts -
 reports the same value as `Encoding.Default`.

* Once an encoding provider has been registered, `Encoding.GetEncoding(0)` reports _that provider's_ notion of the default encoding.

   * Does _every_ encoding provider _invariably_ redefine the default? Or can a provider choose to leave the then-effective default in place?

   * Registering the [System.Text.Encoding.CodePages](https://www.nuget.org/packages/System.Text.Encoding.CodePages/) NuGet package adds all legacy Windows code pages (encodings) and _additionally_ makes `Encoding.GetEncoding(0)` return the active "ANSI" code page (the encoding of the code page associated with the legacy system locale on Windows, which, on Unix systems, will be inferred from the active locale (in Core 2)).

* It is possible to register _multiple_ encoding providers, but the following rules apply:

   * The provider registered _last_ determines the value of `Encoding.GetEncoding(0)` (see above).  This means that you have no access to the default encoding as defined by _previously_ registered providers, correct?

   * Multiple providers can (and typically will) register distinct encodings, but for any given  encoding registered by more than one provider the definition of the provider registered _last_ is in effect.

**Comment by tarekgh** [comment]
> By default, Encoding.GetEncoding(0) - code page ID 0 signifying a default value of sorts -
reports the same value as Encoding.Default.

This is no true any more after registering the providers. this is why I mentioned try to avoid the word default. initially we didn't expose Encoding.Default because of the confusion but we had to expose it after the change in the plans to cover all desktop APIs in the net core. so please don't tie Encoding.GetEncoding(0) with Encoding.Default

> Does every encoding provider invariably redefine the default? Or can a provider choose to leave the then-effective default in place?

it is up to the provider to decide if need to return something for Encoding.GetEncoding(0) or not.

> The provider registered last determines the value of Encoding.GetEncoding(0) (see above). This means that you have no access to the default encoding as defined by previously registered providers, correct?

As I mention please split the concept of Encoding.Default from Encoding.GetEncoding(0) and everything would be clear. treat Encoding.GetEncoding(0) as any other encoding code page

**Comment by mklement0** [comment]
That clears it all up; thanks, @tarekgh.

As a result:

* other places in the documentation need updating (see below)

* it raises the question how to _reframe_ code-page identifier `0` in the docs - effectively, it is the _last_ registered _encoding provider's_  default (definition of of `0`). As stated, however, that concept loses its usefulness with _multiple_ registered providers.  
Perhaps `0` should be called _deprecated_?

Additional places in the current docs that need updating.

> "0 (zero), to use the default encoding."

* https://docs.microsoft.com/en-us/dotnet/core/api/system.text.encoding#System_Text_Encoding_GetEncoding_System_Int32_ 

* https://msdn.microsoft.com/en-us/library/wzsz3bk3(v=vs.110).aspx

**Comment by tarekgh** [comment]
@mklement0 I agree and thanks for your feedback. it is useful to reduce the confusion to the users.

**Comment by mairaw** [comment]
@rpetrusha should we change the milestone on this one?

**Comment by rpetrusha** [comment]
@mairaw, yes, I'll move it to June.
