### ISSUE TITLE
String comparison, sorting and globalization use ICU instead of NLS in Windows 19H1+

### ISSUE THREAD

**Issue by safern** [dotnet/docs#18423]
## Globalization support change on Windows 10 19H1+

We changed the underlying library that we use in order to get localization data, perform string/char sorting and comparisons. If an application is running on Windows 19H1 or later which ships with ICU native library, we will use ICU as the library to perform this operations instead of Windows NLS APIs. If we fail to load/find ICU on the OS we will fallback and use NLS.

### Version introduced

.NET 5.0 Preview4

### Old behavior

Globalization behavior was mainly derived from Windows NLS native APIs.

### New behavior

Globalization behavior will be mainly derived from ICU library shipped with Windows.

### Reason for change

1. Provide apps the same behavior in between different OSs (Linux, macOS, Windows).
2. Allow apps control the globalization behavior by supporting having the apps use custom-built ICU library.

### Recommended action

If customers want to fall back to use NLS, they can add a runtime switch in their runtimeconfig.template.json:
```js
{
    "configProperties": {
        "System.Globalization.UseNls": true
    }
}
```

They can also set an environment variable:
`DOTNET_SYSTEM_GLOBALIZATION_USENLS=true`

### Category

- Core
- Core .NET libraries
- Globalization

### Affected APIs

  - [System.String](https://docs.microsoft.com/en-us/dotnet/api/system.string?view=net-5.0)
  - [System.Span](https://docs.microsoft.com/en-us/dotnet/api/system.span-1?view=net-5.0)
  - [System.Globalization namespace classes](https://docs.microsoft.com/en-us/dotnet/api/system.globalization?view=net-5.0)

---
#### Issue metadata

* Issue type: breaking-change

**Comment by tarekgh** [comment]
Thanks @safern. I am listing some change suggestion here:

Maybe we need to change the title to something generic like "Globalization support change on Windows 10 19H1+"

> We used NLS APIs in all Windows SKUs.

We may rephrase it as `Globalization behavior was mainly derived from Windows NLS native APIs.`

> We use ICU APIs when we're able to find it in the OS, if not we fallback to use NLS.

We may rephrase it as `Globalization behavior will be mainly derived from ICU library shipped with Windows. `. Note I would avoid going to fallback details here as we are not expecting the fallback will really occur in normal cases.

> Provide apps the same behavior in between different OSs (Linux, Unix, Windows).

did you mean to say OSX instead of Unix?

> Provide apps an option to control the localization data and version of ICU they use by building a custom ICU.

maybe we can say `Allow apps control the globalization behavior by supporting having the apps use custom-built ICU library. 

> System.Char

This one need to be removed from the list. and we should remove all classes listed under Globalization namespace and just mention ` System.Globalization namespace classes'

**Comment by safern** [comment]
Thanks @tarekgh -- I've updated the issue with your recommendations.
