### ISSUE TITLE
What is $"

### ISSUE THREAD

**Issue by Vespiyanus** [dotnet/docs#18681]
For newbies, It would be very nice to see some explanations or note on $" (in Performing Operations on Source Elements section)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4a44517-d9a2-454d-90f3-90d9553ff4be
* Version Independent ID: f31a6959-8212-a49f-eeb4-43936dbfbadb
* Content: [Data Transformations with LINQ (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/data-transformations-with-linq)
* Content Source: [docs/csharp/programming-guide/concepts/linq/data-transformations-with-linq.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/data-transformations-with-linq.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi @Vespiyanus, thank you for raising this concern. Yes, I can see how it might be confusing to newbies. All of a sudden new and unfamiliar syntax is being used without any details about its usage.

I've added the "up-for-grabs" label on this issue, so that anyone could work on it before we have a chance to. To answer the ask, the `$"` is used for formatting strings, and is called [string interpolation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated).

What it does, is format expressions within the string. It tells the C# compiler that the string should evaluate the expressions and then concatenate the pieces together.

```csharp
double[] radii = { 1, 2, 3 };

IEnumerable<string> query =
    from rad in radii
    select $"Area = {rad * rad * Math.PI:F2}";
```

The query could then be iterated on, and it's just a string collection with the following values:

```
"Area = 3.14",
"Area = 12.57",
"Area = 28.27"
```

**Comment by jmarkman** [comment]
I'd like to take a crack at refactoring this particular section to provide a bit more clarity for newer readers, if that's alright.

**Comment by IEvangelist** [comment]
Hi @jmarkman - absolutely. Thank you
