### ISSUE TITLE
Change wording on the recommendation to use decimal for financial transactions

### ISSUE THREAD

**Issue by talouv** [dotnet/docs#18787]
I would argue that the argument to use decimals for financial transactions is misleading.

`Because the decimal type has more precision and a smaller range than both float and double, it's appropriate for financial and monetary calculations.`

I would argue that the argument should be something along the lines of

`Because the decimal type uses decimal precision whereas both float and double use binary precision, the decimal type is appropriate for financial and monetary calculations.`

In my view, the important point is that double and float precision is on the binary representation and you thereby can loose decimal precision even for decimals with low precision.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b24345d9-7aec-14ad-8c3c-56410267849a
* Version Independent ID: f83555d8-9dac-5019-3345-bb0f03e1311d
* Content: [Floating-point numeric types - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/floating-point-numeric-types)
* Content Source: [docs/csharp/language-reference/builtin-types/floating-point-numeric-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/builtin-types/floating-point-numeric-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @talouv 

I'm adding @KathleenDollard to this conversation. She and I have discussed in the past, and I'd like her opinion on wording.

**Comment by KathleenDollard** [comment]
I agree with @talouv and my experience is that most programmers miss the nuances here, and without that may fail to understand that the absolute worst thing you can do is multiple conversions Base 2<->10, followed by addition or subtraction of numbers not random in later digits, as can happen when dividing values that tend to be integers. This might be too much?

> The decimal data type is Base 10, which has the same kind of decimal values you work with as a human. The float and double data types are Base 2, which is convenient for the computer. Since the values are held differently, values you expect to be equal may not be equal, requiring comparison against a range. Converting from a Base 10 value to a Base 2 value loses accuracy and when doing math, rounding errors occur at values humans do not expect. Base 2 math works hard for accuracy, and as a result values of calculations can vary by bitness.  In addition, float and double do not throw exceptions when divided by zero. 

> For these reasons, decimal is the appropriate data type for financial and monetary calculations, as well as other calculations that do not have a high performance requirement.

**Comment by pkulikov** [comment]
@KathleenDollard sorry, your proposal more confuses me than explains. I would say it's too advanced. For example, if I have a choice to use either decimal or double for finances, I don't expect to convert between them, but use the chosen one. So, the remarks about conversions between bases seem not relevant at the first reading. As far as I understand, decimal fits finances better because it stores values in the format which is closer to the one as those are stored on paper, either on price tags or in accountant books, and does arithmetics accordingly. At this point, I see how the conversion between bases plays role here, but don't know how to phrase it in a clear way. Maybe, an example would work better? For example, `6 * 0.19 / 0.19 == 6` is true for decimal and false for double. And if I think about buying 6 pieces of bread, 0.19 dollars each, decimal looks preferred for accounting. Is that a good example?

Also, I think using word "base" might be misleading as well, again, it skips some necessary knowledge. In the end, decimal stores its value as zero and ones, in binary as well. The difference between decimal and double is the *format* in which they represent a number, factor it. As soon as one is aware of the format, word "base" has a clear meaning. Without that context, it can be confusing. And we should assume the readers of this doc are not aware of those formats, so they don't have proper context to think about the word "base".

**Comment by pkulikov** [comment]
I would suggest the following phrasing:

> The `decimal` type represents a real number in the (-1)<sup>s</sup><dot/> x M / 10<sup>n</sup> format (for more information, see the <xref:System.Decimal> API article). The `float` and `double` types are *binary* floating-point types; they use base 2 in their representations of a number. The `decimal` type format suits better to store values that are typically met in financial and monetary domains. For example, 0.1 can be exactly represented by a `decimal` instance, while there is no `double` or `float` instance that exactly represents 0.1. Because of that, unexpected rounding errors can occur in the result of arithmetic calculations, as the following example shows:
>
> ```csharp
>    (double step, double sum) = (0.1, 0.0);
>    (decimal stepDecimal, decimal sumDecimal) = (0.1m, 0.0m);
>    for (int i = 0; i < 1_000_000; i++)
>    {
>      sum += step;
>      sumDecimal += stepDecimal;
>    }
>    Console.WriteLine(sum);  // output: 100000.000001333
>    Console.WriteLine(sumDecimal);  // output: 100000.0
> ```
>
> That's why we recommend using the `decimal` type in financial and monetary applications.

@KathleenDollard @BillWagner @talouv what do you think?

**Comment by talouv** [comment]
What about keeping it short and simple, and then maybe linking to the docs of the decimal / double where they elaborate on the representation base?
https://docs.microsoft.com/en-us/dotnet/api/system.double
https://docs.microsoft.com/en-us/dotnet/api/system.decimal
(see remarks on both pages).

**Comment by talouv** [comment]
Now that I think of it, I might simply be wrong on creating this issue. You will have the same rounding errors as with doubles.
For doubles, 1/10+...+1/10 (10 times) will not equal 1, but for decimals 1/3+1/3+1/3 will not equal 1.

Why should it be better for financial transactions to have the rounding error for 3 times 1/3 than for 10 times 1/10? That makes no sense.

There is some discussion on this page on why decimals might be better: https://docs.microsoft.com/en-us/dotnet/api/system.decimal?view=netcore-3.1#remarks

That touches the initial argument more than my proposal.

However, using a decimal will at least provide more intuition on when rounding errors occur. But that - of course - is not the argument.

**Comment by pkulikov** [comment]
> Why should it be better for financial transactions to have the rounding error for 3 times 1/3 than for 10 times 1/10? That makes no sense.

@talouv that's right: `decimal` doesn't eliminate round-off errors completely. However, maybe, those round-off errors are met less frequently with `decimal` than with `float` or `double`. That is, I assume that one meets 0.1 more frequently in financial domain than 1/3. In general, I think that numbers of the form `abcd.efgh` are met in financial applications rather than of the form `n / m`. The `decimal` type can present `abcd.efgh` exactly as it is if that number has no more than 28 digits (1/3 is an infinite number and cannot be represented by `decimal` precisely). That already eliminates a large number of round-off errors that are caused by representation a real number in a given floating-point number format.

**Comment by talouv** [comment]
Good point. I talked with my colleague about this, and he pointed the same thing out, and I agree.

Very low level, you could say that in your online bank, you would enter 0.33 for 1/3 and 0.10 for 1/10. And you would not expect those numbers to cause any rounding errors.

**Comment by KathleenDollard** [comment]
Wow, great work @pkulikov. I started something and didn't like it. Accuracy and precision aren't the perfect words here, it's ultimately what is _expected_. And that the input values are in base 10. 

Three further thoughts: 

* I'm not crazy about saying "financial and monetary". My strong leaning is to say "unless the need for binary performance has been demonstrated", but that might be going too far. Maybe something like "where reliable, predictable calculations are needed, such as financial and monetary calculations." There are financial/monetary apps that need the performance of binary formats and non-financial apps that need decimal. 

* float and double have other unexpected behaviors - divide by zero and I don't think anyone has ever gotten the result of  double.MaxValue + 1 correct. 

* They are slower, but this is in the nanosecond-low microsecond range that most non-calculation intensive applications will be able to measure. 

* The code illustrates very well, but the resulting value is not consistent for some values across things like bitness. I think .1 is one of those values. Try this on a 32 bit and 64 bit version of .NET and ensure it is the same. Also, this particular value rounds correctly, so adding a comparison to the correct value might further illustrate. 

As for things like VAT calculations, they are usually rounded to the precision of the currency near the point of calculation. 

I think anything we do here to better say "this is a really good data type to use!" is good
