### ISSUE TITLE
Offer some clarification??

### ISSUE THREAD

**Issue by ssbaca** [dotnet/docs#18836]
I would suggest that some clarification would be helpful in the following paragraph.
**Download and manually install**
To extract the runtime and make the .NET Core CLI commands available at the terminal, first download a .NET Core binary release. Then, create a directory to install to, for example %USERPROFILE%\dotnet. Finally, extract the downloaded zip file into that directory.

First, regarding "download a .NET Core binary release.",  explain how to do that.
Second, explain %USERPROFILE% is and how to get to it to create a \dotnet sub-directory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac255410-47e8-7c14-b14f-06dfe3e424f9
* Version Independent ID: 09a819ef-b5af-43f7-e744-60ca6f667a45
* Content: [Install .NET Core SDK on Windows, Linux, and macOS - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/sdk)
* Content Source: [docs/core/install/sdk.md](https://github.com/dotnet/docs/blob/master/docs/core/install/sdk.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@ssbaca I thought about this for some time and I don't think I'm going to clarify these steps. Honestly, these steps are meant for advanced scenarios. I don't foresee a user who is unfamiliar with environment variables using manual install instead of automated install through the installer.

I will look at clarifying "download a .NET Core binary release." and making sure it matches the download site's terminology.

Tanks again for your feedback!
