### ISSUE TITLE
API reference for type should include namespace

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1896]
The API reference page for a type does not mention the namespace of the type clearly. For example, [`XPathExpression`](https://docs.microsoft.com/en-us/dotnet/api/System.Xml.XPath.XPathExpression?view=netframework-4.7):

![](https://cloud.githubusercontent.com/assets/287848/25018095/6d619c5a-2086-11e7-94cb-276f5e830423.png)

The above screenshot does not mention the namespace at all. It is mentioned in the TOC, in breadcrumbs and in the URL, but I don't think that's enough.

What is especially weird is that API reference pages for members do mention the namespace of the type right in the header (along with a confusing list of assemblies). For example, [`XPathExpression.Compile`](https://docs.microsoft.com/en-us/dotnet/api/system.xml.xpath.xpathexpression.compile?view=netframework-4.7):

![](https://cloud.githubusercontent.com/assets/287848/25018240/f6502612-2086-11e7-9257-71eec72de96a.png)

**Comment by rpetrusha** [comment]
@svick, you're quite correct. Currently, namespace information is available for type topics only on the breadcrumb (where almost no one will notice it), while assembly information is unavailable. Both namespace and assembly information are only available for type members.
We've opened an internal bug (#970251) to include namespace and assembly information for each type topic.

**Comment by rpetrusha** [comment]
@svick, I'm closing this issue, since it's been fixed. Namespaces now appear in the type pages, along with the assemblies in which the type can be found. Here is [XPathExpression](https://docs.microsoft.com/en-us/dotnet/api/system.xml.xpath.xpathexpression?view=netframework-4.7):
 
![image](https://user-images.githubusercontent.com/10886961/27047117-c29e8cb0-4f5b-11e7-930d-447dc3062076.png)
