### ISSUE TITLE
Document the SatelliteResourceLanguages MSBuild property

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/docs#18995]
In .NET Core 2.1 (SDK 2.1.300) we added support for specifying languages to preserve satellite resource assemblies for during publish. See dotnet/sdk#774 for details.

``` xml
<PropertyGroup>
  <SatelliteResourceLanguages>en-US</SatelliteResourceLanguages>
</PropertyGroup>
```

In a new .NET Core WinForms app, setting this property to "en-US" (the runtime's default language) will result in a saving of 15 MB on the size of the app when published self-contained. When combined with the `PublishTrimmed` flag, this is an ~18% size saving.

Other packages commonly used in .NET Core apps (including ASP.NET Core, WinForms, and WPF apps) include embedded satellite resource assemblies that don't provide any benefit in cases where the app is only ever run in a single language context anyway.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d4dafc-2217-9a7b-4590-27faa85164cd
* Version Independent ID: 64b80e80-1c15-c293-466a-918de98e96f6
* Content: [MSBuild properties for Microsoft.NET.Sdk - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props)
* Content Source: [docs/core/project-sdk/msbuild-props.md](https://github.com/dotnet/docs/blob/master/docs/core/project-sdk/msbuild-props.md)
* Product: **dotnet-core**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by stevenvolckaert** [comment]
What's the status on documenting the `SatteliteResourceLanguages` property; is it suppported or not?

I have many ASP.NET Core projects targeting `netcoreapp3.1`, they all have a reference to

```
<PackageReference Include="Humanizer" Version="1.33.7" />
```

Adding the `SatteliteResourceLanguages` property, e.g. setting its value to `en;fr;nl` doesn't make a difference. The build output and publish output still have a large number of localized Humanizer DLLs in languages I don't need.

**Comment by DamianEdwards** [comment]
@stevenvolckaert note your spelling of the property, you have a typo there. It should be `SatelliteResourceLanguages` with only one `t` and two `l`s. When I replicate the correct setup locally it works for me.

Also the version of Humanizer you're using is 6 years old. Any reason you haven't updated to a 2.x version that properly supports .NET Core and .NET Standard?

**Comment by stevenvolckaert** [comment]
Thanks for pointing this out @DamianEdwards!

I tried again with correct spelling, and it works, both with Humanizer v1.33.7 and v2.11.10. _(We've currently remained with v1.33.7 because there hasn't been an opportunity yet to upgrade.)_

However, this only works if `SatelliteResourceLanguages` is added to the project that contains the `Humanizer` package reference: In our case, it is an utility library that directly references `Humanizer`, and a number of ASP.NET, ASP.NET Core, .NET Framework and .NET Core projects reference the utility library via a `ProjectReference`.

Yesterday I added `SatelliteResourceLanguages` property (which I, like in my previous comment, might have spelled incorrectly) to one of the ASP.NET Core projects, and noticed it didn't work.

The `SatelliteResourceLanguages` needs to be added to the utility project, then it works.

Thanks a lot for your help @DamianEdwards! Much appreciated! 👌😎

**Comment by DamianEdwards** [comment]
Logged an issue to get this added to the MSBuild schema so it shows up in IntelliSense too: dotnet/msbuild#6854

**Comment by ShingZhanho** [comment]
I came across the problem a few days ago as well. I was using .NET Framework 4.8 when the problem occurred. Today I migrated my project to .NET Core 3.1 and everything just worked. So it seems like this has nothing to do with ModernWpf itself, it is a bug from Microsoft.

See  dotnet/sdk#3277

I am afraid you have to use a new SDK for this to work.
