### ISSUE TITLE
Update 'Reference assemblies'

### ISSUE THREAD

**Issue by alrz** [dotnet/docs#19067]
There is no information on how we can reference reference assemblies such that the actual implementation flows in from the parent project references (if possible), just like what we have with netstandard.

Also, some info on the difference with multi-targeting as the two have some conceptual overlap, I think.

(I might got this all wrong but the docs do not clearup any of that at all)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2652b073-4103-1426-af2c-cea38a6266de
* Version Independent ID: 26649234-af05-dd2b-b0b7-c648d38c471b
* Content: [Reference assemblies](https://docs.microsoft.com/en-us/dotnet/standard/assembly/reference-assemblies)
* Content Source: [docs/standard/assembly/reference-assemblies.md](https://github.com/dotnet/docs/blob/master/docs/standard/assembly/reference-assemblies.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @MSDN-WhiteKnight
* Microsoft Alias: **dapine**

**Comment by adegeo** [comment]
@alrz Sorry for the delay in answering your question. I'll send an email around to see if anyone knows.

Ping @MSDN-WhiteKnight

**Comment by MSDN-WhiteKnight** [comment]
> Ping @MSDN-WhiteKnight

Unfortunately i don't know how to update article to better explain what @alrz is asking about. What implementation assembly is mapped to the particular reference (either to reference assembly or to implementation assembly) is always decided by the component of runtime, Fusion in .NET Framework (https://docs.microsoft.com/en-us/dotnet/framework/deployment/how-the-runtime-locates-assemblies) or load context in .NET Core. It has no concept of project references, it just scans directories in certain order. As for why .NET Standard enables referencing "non-existant" netstandard.dll and then binding it to real assemblies at runtime, this is because any .NET Standard-compliant runtime contains stub netstandard.dll with tons of type forwarders to real implementations. Indeed, this is different from multi-targeting, because multi-targeting is about producing different deployments for different runtimes, not resolving a single deployment for multiple runtimes.

This all is not directly related to reference assemblies, but we can probably add links to some related articles that explain this. I just don't know up-to-date article about runtime assembly binding that considers .NET Core and .NET 5.

**Comment by alrz** [comment]
The article does mention `ProduceReferenceAssembly` msbuild property, but not how the client code could use it.

I find a blog post by @clairernovotny discussing this very topic: https://claires.site/2018/07/09/create-and-pack-reference-assemblies-made-easy but it uses a custom sdk and there's no mention of `ProduceReferenceAssembly` (probably because it was not available at the time?)

The only usages of `ProduceReferenceAssembly` I find in github is in dotnet/wpf and xamarin, but there is no info about how it works.

**Comment by MSDN-WhiteKnight** [comment]
For project references, they will be used automatically if ProduceReferenceAssembly is set in referenced project. Compilers will consider reference assembly as input whenever it's available, unless CompileUsingReferenceAssemblies property is set to false. This is documented here in roslyn docs: https://github.com/dotnet/roslyn/blob/master/docs/features/refout.md#msbuild , but wasn't included in this article, because the article is mainly about reference assemblies themselves, not MSBuild properties. For any other uses, the client selects the assembly file to reference manually, so it just needs to pick the produced reference assembly (from the ref/ directory under build output).

>The only usages of ProduceReferenceAssembly I find in github is in dotnet/wpf and xamarin, but there is no info about how it works.

From what I've found, WPF does not use ProduceReferenceAssembly, instead it uses custom mechanism to generate separate projects for reference assemblies: https://github.com/dotnet/wpf/blob/master/Documentation/gen-api.md CoreFX libraries do the same.

**Comment by adegeo** [comment]
@alrz I'm wondering if you would have more luck asking this question on https://github.com/dotnet/core and then if after that discussion, if there is something to document/improve over here, we can follow up?
