### ISSUE TITLE
Milliseconds Format String

### ISSUE THREAD

**Issue by CalvinAllen** [dotnet/docs#19224]
The formatting section refers to the milliseconds portion as "F", but just going through this, I had to use a lowercase "f"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb41b02f-8fe9-44a1-544f-b6016f1ff4b3
* Version Independent ID: 77358796-3ee2-9b86-7e0a-92c60ebc371a
* Content: [DateTime and DateTimeOffset support in System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/datetime/system-text-json-support)
* Content Source: [docs/standard/datetime/system-text-json-support.md](https://github.com/dotnet/docs/blob/master/docs/standard/datetime/system-text-json-support.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @layomia
* Microsoft Alias: **laakinri**

**Comment by adegeo** [comment]
@CalvinAllen I think it's using "F" because that trims off any milliseconds that are 0. So it's based on the output you want really. I find it more common to omit a millisecond portion if it's 0. If you used "FFF" you would probably always get a millisecond result.

```
Console.WriteLine(date1.ToString("hh:mm:ss.f", ci));
// Displays 07:27:15.0
Console.WriteLine(date1.ToString("hh:mm:ss.F", ci));
// Displays 07:27:15
Console.WriteLine(date1.ToString("hh:mm:ss.ff", ci));
// Displays 07:27:15.01
Console.WriteLine(date1.ToString("hh:mm:ss.FF", ci));
// Displays 07:27:15.01
```

https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#F_Specifier

I'm going to close this issue as I don't think there is anything to correct here 😄 Let me know if you feel otherwise! Cheers!
