### ISSUE TITLE
How to handle samples that have compile errors *by design*

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#19265]
See https://github.com/dotnet/docs/pull/19260#issuecomment-651764937

We had discussed two possibilities.

1. *Add configuration information to samples builds*. We'd tag samples that have compile errors with details about which line, and what error should be caused.
1. *Code that doesn't compile is in inline markdown*. In this strategy, code that should not compile isn't in projects, but is inline in markdown.

There are advantages to either plan.  The second is simpler for authors and the build system. Also, it avoids a situation where a reader downloads code and it doesn't build. The first is more future proof: any language enhancements that enable new scenarios would be caught if previously disallowed code now works.

Which is better?

/cc @adegeo @IEvangelist @NextTurn

**Comment by IEvangelist** [comment]
Thanks for formalizing this discussion @BillWagner.

I think I prefer option 2, as it simplifies the management of the build validation. Otherwise, it would become a growing concern to manage which lines are intentionally compiler errors, and which errors they should correspond to. Furthermore, it would introduce more work to add additional logic for these files in question, and cause more churn on the build system validation checks we recently established.

I think it is more clear to inline compiler errors in the docs, and then have explicit call outs about the context. One thing that we try to limit is the number of comments in our sample code, with that said - intentional compiler errors in sample code that are not commented, would potentially be cleaned up as changes are made. With intentional compiler errors inlined in the docs, it is explicit and is less likely to be missed in a code review.

**Comment by adegeo** [comment]
Tomorrow I'll be adding an optional config file that lives with the project or solution. We discovered we 100% need a way to set some compiler options.

While I can see that snippets may not compile, and I still think option 2 would be valid, is there a reason a **sample** would have compile errors?

**Comment by IEvangelist** [comment]
It's been more than two years since this issue was opened, and it's still not a priority. We've officially adopted option two:

> Code that doesn't compile is in inline markdown. In this strategy, code that should not compile isn't in projects, but is inline in markdown.

Closing this issue.
