### ISSUE TITLE
Also, href

### ISSUE THREAD

**Issue by JustDre** [dotnet/docs#19284]
This should also mention that the "href" parameter is available for *generic* hyperlinks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c9f2f59-0dec-c531-b19a-a2109ea0f973
* Version Independent ID: 74c6022c-8661-216e-4f48-e5f08f432f85
* Content: [&lt;see&gt; - C# programming guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/see)
* Content Source: [docs/csharp/programming-guide/xmldoc/see.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/xmldoc/see.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi @JustDre - thank you for posting this issue. You are correct, it should show that `href` is also valid and will function as a hyperlink. I'm marking this issue as "up-for-grabs", by all means please feel free to propose these changes as a pull request. Otherwise we'll try to get to it when we're able. Thank you.
