### ISSUE TITLE
Error in documentation 

### ISSUE THREAD

**Issue by jainvikram444** [dotnet/docs#19435]
[Enter feedback here]
I mention in attached file.
![error_tutorial](https://user-images.githubusercontent.com/1199227/87227487-ea44d600-c3b8-11ea-8e76-c631138ca6c0.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c922021-b12a-83e4-3ee6-eceecd6076d2
* Version Independent ID: fdb655a4-cff4-6c67-7244-673760379663
* Content: [Get started with .NET Core](https://docs.microsoft.com/en-us/dotnet/core/get-started?tabs=windows)
* Content Source: [docs/core/get-started.md](https://github.com/dotnet/docs/blob/master/docs/core/get-started.md)
* Product: **dotnet-core**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by Youssef1313** [comment]
Make sure you didn't "cd" into the project folder.

If you run the exact same commands in the documentation it should work correctly.

**Comment by IEvangelist** [comment]
Hi 👋 @jainvikram444
Thank you so much for posting this issue. We really appreciate it. Could you please provide me with a bit more information so that I can help dig into this issue with you?

As @Youssef1313 has said, if you change directories you will have to specify the `.csproj`. However, I'm curious what version of the .NET SDK you're using - could you please run the following .NET CLI command and reply with its output?

```
dotnet --info
```

This will help me understand your environment, and installed SDK, etc. Thank you
