### ISSUE TITLE
Race Condition

### ISSUE THREAD

**Issue by dgoldbergGIT** [dotnet/docs#19474]
I believe this code has a race condition because resultsTextBox.Text is set by multiple threads in the DisplayResult method. Please either correct, let me know why I'm wrong, or at least notate in the article that there is a race condition so it won't encourage bad practices and leave people wondering. 

Thank you!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 702427b0-0bcc-1152-75a5-c909717723c0
* Version Independent ID: 0dbb92ca-4166-ceaf-1083-1280703a9c15
* Content: [How to extend the async walkthrough by using Task.WhenAll (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/how-to-extend-the-async-walkthrough-by-using-task-whenall)
* Content Source: [docs/csharp/programming-guide/concepts/async/how-to-extend-the-async-walkthrough-by-using-task-whenall.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/how-to-extend-the-async-walkthrough-by-using-task-whenall.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment]
Hi 👋 @dgoldbergGIT
Thank you so much for posting this issue. We really appreciate it.

In looking through the code, I can see why someone might assume there is a race condition. However, this is perfectly acceptable as the `resultsTextBox.Text` is serving as live log if you will of the events as they happen in real time. In other words it's kind of like a pseudo *stdout*. If you look closely you'll see that it is appending rather than overwriting. So, the timing at which that occurs doesn't matter, thus no race condition. All of the places that use touch this use the [`+=` operator](https://docs.microsoft.com/dotnet/csharp/language-reference/operators/addition-operator) - which is really just concatenation. 

Does that make sense, or do you still have a concern?

**Comment by dgoldbergGIT** [comment]
Thanks so much for your response! After studying further, I'm wondering if there is no race condition for a different reason: [Since there is no call to Task.Run, in fact the UI thread is the only thread ever involved in this example (there is no other thread created).](https://docs.microsoft.com/en-us/dotnet/standard/async-in-depth). Instead, .NET is leveraging some OS calls to "simulate" multi-threading (or callbacks) on the same thread. I didn't understand this when I opened the issue. 

If there were multiple threads involved, then your explanation wouldn't make sense to me. Thread A could read resultsTextBox.Text and append a string and then be immediately suspended. Thread B could then read resultsTextBox.Text and append a new string and save resultsTextBox.Text. Then, thread A could save resultsTextBox.Text, and thread B's appended string would be missing. 

But at the same time, I'm wondering if it's possible that even though there is one thread, the same scenario as the multi-threaded example I gave can't occur if the single thread can move between different tasks just right? The only answer I can think of is that with async/await (and without Task.Run), it can't randomly switch to different tasks (it only switches when one task completes and another is ready). 

Thoughts?

Thanks again!

**Comment by pkulikov** [comment]
If different threads access that textbox, the app should crash, correct? UI elements can be accessed by the UI thread only. So, it's not about race condition but about crash/no crash of the app.

**Comment by IEvangelist** [comment]
I'm working on updating the tutorials. Since we're just using `await` without specifying `ConfigureAwait(true)`, the continuations will all occur on the UI thread and it's not clear which order the updates will occur in but they will each be atomic since there is only one UI thread. With the way that this is written now, there is no potential for a background thread to update the textbox text, thus no concern of app crash.

**Comment by IEvangelist** [comment]
Task(s)

- [x] https://github.com/dotnet/samples/pull/3819
- [ ] https://github.com/dotnet/docs/pull/19970

**Comment by IEvangelist** [comment]
Closed by #20153
