### ISSUE TITLE
Change var statement to new format.

### ISSUE THREAD

**Issue by WmHBollinger** [dotnet/docs#19481]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83cd166c-9e60-e6b5-1985-5dd04d3261f2
* Version Independent ID: 45bf2f1f-a453-0e2e-c115-050c9d621cb3
* Content: [Implicitly typed local variables - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/implicitly-typed-local-variables)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/implicitly-typed-local-variables.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/implicitly-typed-local-variables.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by WmHBollinger** [comment]
From https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/strings/
I tryed to use  "var jh = (firstName: "Jupiter", lastName: "Hammon", born: 1711, published: 1761);"
but my VS Comm 17 would not allow it

When I used "var jh = new { firstName = "Jupiter", lastName = "Hammon", born = 1711, published = 1761 }; ",
It was good. 

Please change web document page.

**Comment by IEvangelist** [comment]
Hi 👋 @WmHBollinger 
Thank you so much for posting this issue. We really appreciate it.

The difference is these two statements, is that the first is using a newer language level feature called tuples. It is perfectly valid C#, assuming you're using the correct version. The second statement, is an anonymous type - and has been around since C# 2 I believe.

You could get the latest version of Visual Studio Community 2019 - https://visualstudio.microsoft.com/downloads/. That would solve this problem.
