### ISSUE TITLE
appSettings documentation is missing

### ISSUE THREAD

**Issue by conniey** [dotnet/docs#1981]
# Cannot locate <appSettings> element documentation

While trying to redirect my old msdn links to the new ones for breaking changes.. I noticed that I could no longer find up-to-date documentation for <appSettings> element.

I found these two outdated ones (that say they are archived):
  * https://msdn.microsoft.com/en-us/library/aa903313(v=vs.71).aspx
  * https://msdn.microsoft.com/en-us/library/ms228154(v=vs.85).aspx

but when I try to follow the link to the [recommended one](https://msdn.microsoft.com/en-us/library/ms228154(v=vs.110).aspx), it does not exist.  Nor can I find it on docs.microsoft.com in the [configuration schema](https://docs.microsoft.com/en-us/dotnet/articles/framework/configure-apps/file-schema/configuration-element). :/

**Comment by rpetrusha** [comment]
@conniey, the appSettings element appears to have last been published in the .NET Framework 4.0 doc set. In the current doc set, it has been "paved over" and replaced with the ["This topic does not exist page"](https://msdn.microsoft.com/en-us/library/ms228154(v=vs.110).aspx) boilerplate. I'm trying to investigate the reason for this, if there was one, with the ASP.NET team, which owned the topic. Unfortunately, the topic has been deleted from CAPS, the authoring system that we used for .NET Framework 4.5 through 4.7 content, and therefore was not migrated to GitHub.

My suspicion is that this was part of a rather unfortunate initiative to reduce the size of our doc set by eliminating low page-view pages. I've noticed that the configuration settings documentation seems to have some major gaps caused by the haphazard removal of topics.

I've opened an item in the [Migration project](https://github.com/dotnet/docs/projects/8) to try to investigate this and what I think may be some other significant gaps in the configuration documentation.

**Comment by mairaw** [comment]
AFAIK the entire documentation for ASP.NET got removed from MSDN and then moved to the asp.net site but I don't which content was ported and which one was deleted.

Do we need to restore those topics?

/cc @Rick-Anderson @tdykstra @wadepickett

**Comment by rpetrusha** [comment]
I think that we at least need to restore the basic configuration settings documentation. 
In terms of appSettings, I may be wrong, but I don't think that it was used exclusively by ASP.NET; I distinctly seem to recall using it myself in non-ASP.NET applications.

**Comment by Rick-Anderson** [comment]
@rpetrusha  what's the process to get at least this restored? I'm concerned there might be new settings that are not documented in the older versions.

**Comment by mairaw** [comment]
At this point, the restore process might have to be manual. These probably only existed back in DxStudio.

**Comment by rpetrusha** [comment]
Restoration will have to be manual, since the files weren't migrated to CAPS. Fortunately, manual migration is fairly simple, and there are only a handful of topics.

**Comment by GuardRex** [comment]
> only a handful of topics

@rpetrusha Is there an easy way to isolate the missing topics, or should I dig through https://msdn.microsoft.com/en-us/library/1fk1t1t0(v=vs.71).aspx and perform a manual comparison to what we have in the repo to find the MIA topics?

**Comment by rpetrusha** [comment]
@GuardRex, there's no easy way to isolate the missing topics. I can't think of any way to do it other than performing a manual comparison.

**Comment by GuardRex** [comment]
Ok, thx. I'll get them on a 🐠 *Big Fishing Expedition!* 🎣

**Comment by rpetrusha** [comment]
@GuardRex, along with the config documentation, there's a legacy compat document that we need to recreate as well: [.NET Framework 4 Migration Issues](https://msdn.microsoft.com/en-us/library/ee941656(v=vs.100).aspx).

**Comment by GuardRex** [comment]
@rpetrusha Do they have a script for migrating markup content into markdown? If so, can I open a SiteHelp request to have *.NET Framework 4 Migration Issues* converted?

**Comment by rpetrusha** [comment]
Probably the best thing to do is to use Internet Explorer to save it as HTML, and use an HTML to markdown conversion tool. Whenever I've had to convert XML or HTML to markdown, I've done it manually, so I don't have a sense of what tool is better than the others.

**Comment by GuardRex** [comment]
I'll work a few sections and tables with https://domchristie.github.io/to-markdown/ ... we'll see how that goes.
