### ISSUE TITLE
How to change the Cryptographic Provider for an X.509 Certificate's Private Key

### ISSUE THREAD

**Issue by keke8273** [dotnet/docs#19920]
**Issue description**
I am trying to extend WCF by following this [how-to][1] guide from microsoft. The basic idea is to use  a hardware security module as the client-side private key holder, which means all cryptographic operations involving the client's private key must be carried out by the security module chip. But I was not able to achieve the the goal. 

**Target framework**

```
dotnet framework: 4.7.2
binding: netTcp
binding security: Message
clientCredentialType: Certificate (X509Certificate2) 
serverCertificate: X509Certificate2 
```

<details>

All certificates ( 1 server cert and 2 client certs ) are signed off by the same CA. The server certificate is a normal `pfx` file that contains both the certificate and private key. I prepared two different client certificates one with the private key and one without the private key. (two client side `pfx` files have the identical certificate ) 

**Observations**:

1. When using the client `pfx` file **contains** the private key, the client is able to communicate to the server in the mtls fashion. 
2. When using the client `pfx` file without the private key, the attempt to set up secure session fails with the following exception 
```
System.ArgumentException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
The certificate '<cert name>' must have a private key. The process must have access rights for the private key.
```
Stack Trace
```
System.ServiceModel.Security.TlsSspiNegotiation.ValidatePrivateKey(X509Certificate2 certificate)
System.ServiceModel.Security.TlsSspiNegotiation..ctor(String destination, Boolean isServer, SchProtocols protocolFlags, X509Certificate2 serverCertificate, X509Certificate2 clientCertificate, Boolean clientCertRequired)
System.ServiceModel.Security.TlsnegoTokenProvider.CreateTlsSspiState(X509SecurityToken token)
System.ServiceModel.Security.TlsnegoTokenProvider.CreateNegotiationState(EndpointAddress target, Uri via, TimeSpan timeout)
System.ServiceModel.Security.IssuanceTokenProviderBase`1.DoNegotiation(TimeSpan timeout)
```
3. In **neither** case, the provided `CustomX509AsymmetricSecurityKey` as per the how-to above was **NOT** used by the `WCF` framework. Did not even instantiate the class. The `CustomX509SecurityToken` was instantiated via the `CustomX509SecurityTokenProvider`. But the `SecurityKeys` property of the `CustomX509SecurityToken` class was never called, which is where the custom private key comes to play.  

**Questions**

1. Is the [how-to][1] guide out of date? Notice it is dated `03/30/2017`.
2. The exception when using the `pfx` without private key is sort of self-explanatory. I did not provide the private key. Why didn't WCF use the provided `CustomX509AsymmetricSecurityKey` as the private key? Isnt this the whole point that the user is providing an alternative private key in the form of a `X509AsymmetricSecurityKey`?  
3. Am I following the wrong guide to achieve what I want? I did try to set the [`PrivateKey`][2] property of the `X509Certificate2` class with a custom [`RSA`][3] implementation. But got lost trying to implement the [`ICspAsymmetricAlgorithm`][4] interface which is required by the `X509Certificate2.PrivateKey`

  [1]: https://docs.microsoft.com/en-us/dotnet/framework/wcf/extending/change-cryptographic-provider-x509-certificate-private-key
  [2]: https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificate2.privatekey?view=netframework-4.7.2
  [3]: https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rsa?view=netframework-4.7.2
  [4]: https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rsacryptoserviceprovider?view=netframework-4.7.2
</details>

**Comment by BillWagner** [comment]
ping @HongGit to respond.

**Comment by tdykstra** [comment]
ping @HongGit

**Comment by adegeo** [comment]
Sending email to @HongGit

**Comment by HongGit** [comment]
@mconnew  can you please comment?

**Comment by mconnew** [comment]
@keke8273, you are following the correct guide. WCF checks that the private key is readable before it tries to use it which is why you aren't seeing your implementation being hit. I looked at that code, and it looks to be mostly what you need but could do with a bit of updating (I'll explain at the end), but WCF doesn't get there yet. There are multiple things which could be happening here. First it checks to see if a switch has been set to disable usage of CNG. If you were doing this, you should know about it, it's an opt in app context switch applicable to all targeted Framework versions so I won't bother explaining that part. So presuming you haven't disabled use of CNG (which I think would be needed for hardware keys anyway), it does a few checks to make sure you can use the private key. It calls each of these methods in turn and stops when it gets a non-null result:
*RSACertificateExtensions.GetRSAPrivateKey
*DSACertificateExtensions.GetDSAPrivateKey
*ECDsaCertificateExtensions.GetECDsaPrivateKey

If your certificate is using either the RSA, DSA, or ECDsa algorithm then it should accept the certificate. You can call these methods yourself on your certificate and see what the results are. If they all come back null, then call X509Certificate2.GetKeyAlgorithm() and post the value. It's the OID of the algorithm your key is using. If the OID is for one of those 3 algorithms, then the only possible problem I can think of is it could be a permissions problem.  

The update needed in the code would be to replace usage of X509Certifcate2.PrivateKey with the appropriate extension method above. I suspect only RSACertificateExtensions.GetRSAPrivateKey will work in this case as the sample code is only for the RSA algorithm and the DSA/ECDsa based certificates won't work for that. There's also a chance much of that none of that code is needed because there's two modes of using certificates with Message Security and I believe the mode you are using doesn't need that sample code, but I'm not 100% on that.

**Comment by adegeo** [comment]
I'm going to close this as answered. Sorry for the delay @keke8273
