### ISSUE TITLE
CircuitBreaker is a stateful policy

### ISSUE THREAD

**Issue by mingue** [dotnet/docs#20026]
I think the example of the Circuit Breaker with Polly won't work.
The CircuitBreaker is a stateful policy and need to maintain the result of the lasts request to behave correctly. Either the policy has to be moved outside of the registration to be shared or used a Policyregistry as explained in:  https://github.com/App-vNext/Polly/wiki/Polly-and-HttpClientFactory#with-stateful-policies-use-as-selector-not-factory

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef44bb71-2ee5-bf25-bcd2-1f1eee8b2806
* Version Independent ID: 2c497f8a-2576-2c8e-8ebc-a9f8146c3630
* Content: [Implementing the Circuit Breaker pattern](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/implement-circuit-breaker-pattern)
* Content Source: [docs/architecture/microservices/implement-resilient-applications/implement-circuit-breaker-pattern.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/implement-resilient-applications/implement-circuit-breaker-pattern.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @mingue, thank you for reaching out. 

In the mentioned code snippet, the necessary policies for the circuit breaker pattern gets registered with `IHttpClientFactory` using `AddPolicyHandler()`.  And `SetHandlerLifetime()` method is used to keep track of how often it needs to keep checking the status of the circuit. You can checkout the working example in [here](https://github.com/dotnet-architecture/eShopOnContainers/blob/master/src/Web/WebMVC/Startup.cs#L183)

Please note, `IHttpClientFactory` is available since .NET Core 2.1 however it's recommend to use the latest ASP.NET Core 3.1 packages from NuGet in your project. You typically also need to reference the extension package `Microsoft.Extensions.Http.Polly` to use this functionality. 

You could also use `Polly.CircuitBreaker` and `AsyncCircuitBreakerPolicy` to register necessary policies and configuration to leverage the usage of the circuit Breaker pattern. 
For e.g :

```chsarp

private readonly AsyncCircuitBreakerPolicy _circuitBreakerPolicy;

public ProductSvc(IConfiguration configuration, IHttpClientFactory httpClientFactory)
{
    _configuration = configuration;
    _httpClientFactory = httpClientFactory;
    _circuitBreakerPolicy = Policy.Handle<Exception>()
        .CircuitBreakerAsync(1, TimeSpan.FromMinutes(1), onBreak, onReset, onHalfOpen);
}

.....
.....

public async Task<InventoryItem> GetNumberOfAvailableProductStockAsync(int productId)
{
    try
    {        
        return await _circuitBreakerPolicy.ExecuteAsync<InventoryItem>(async () =>
        { ...
        ...
        }
    }
    catch (BrokenCircuitException ex)
    {
        Console.WriteLine(ex.Message);
        throw ex;
    }
}
.........
............

```
For more details, you could also refer [Circuit Breaker](https://github.com/App-vNext/Polly#circuit-breaker)

Hope this helps !

**Comment by sughosneo** [comment]
Hi @mingue , I am closing this issue as of now. If you have any further questions, please feel free to reopen it. 

Thank you.
