### ISSUE TITLE
Bug in the example

### ISSUE THREAD

**Issue by balintn22** [dotnet/docs#20063]
In the example the method public bool Equals(TwoDPoint p) checks the type of p, where it is not necessary, but the method public override bool Equals(object obj) should, before casting p to a specific type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e95b738e-a319-8947-c098-692068c24b9c
* Version Independent ID: 227a6999-9add-4a0a-98cb-c0c6624d6089
* Content: [How to define value equality for a type - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/how-to-define-value-equality-for-a-type)
* Content Source: [docs/csharp/programming-guide/statements-expressions-operators/how-to-define-value-equality-for-a-type.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/statements-expressions-operators/how-to-define-value-equality-for-a-type.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
The method `Equals(object obj)` uses `as` keyword, which results in "null" if the given type cannot be converted to `TwoDPoint`. So, this doesn't seem to have a problem.

The method `Equals(TwoDPoint p)` compares the type, which seems necessary in my opinion.

If you create a new class `ThreeDPoint` that inherits TwoDPoint, and define a "Z" variable on it. Then comparing the type will be necessary.

Consider the following:

```csharp
var p1 = new TwoDPoint(5, 7);
var p2 = new ThreeDPoint(5, 7, 9); // ThreeDPoint inherits TwoDPoint.

if (p1.Equals(p2))
    Console.WriteLine("They are equal.");
else
    Console.WriteLine("They are NOT equal.");
```

The above code will print "They are equal." instead of "They are NOT equal." **if** you removed the following part:

```csharp
            if (this.GetType() != p.GetType())
            {
                return false;
            }
```

**Comment by BillWagner** [comment]
Thanks for pointing this out @balintn22 

@Youssef1313 's analysis is correct. I'll close this as an answered question.
