### ISSUE TITLE
Missing .Net Framework example

### ISSUE THREAD

**Issue by sanketshah11** [dotnet/docs#20200]
Please provide samples and example with .Net Framework, all the samples and examples target .Net Core

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dce49db-3548-7dad-bdb1-812efde7ac86
* Version Independent ID: 390a9c7a-2537-25ca-c041-0284c253acff
* Content: [Deploy a model in an ASP.NET Core Web API - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/serve-model-web-api-ml-net#feedback)
* Content Source: [docs/machine-learning/how-to-guides/serve-model-web-api-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/serve-model-web-api-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @sanketshah11 

Thank you for your suggestion. Unfortunately, there are no plans to create .NET Framework samples at the moment. We would encourage you to use .NET Core instead. However, if that's not an option, the concepts are generally transferrable. For example, assuming you're using an ASP.NET MVC (.NET Framework) application and already have a model you want to deploy to it as demonstrated in the article you raised this issue from:

1. Install [Microsoft.Extensions.ML](https://www.nuget.org/packages/Microsoft.Extensions.ML/) NuGet package to use the `PredictionEnginePool` service
1. Use dependency injection to register your model
1. Inject the registered `PredictionEnginePool` service into your controller
1. Use the injected `PredictionEnginePool` service to make predictions with the `Predict` method.

If working with non-web applications, you can use the `PredictionEngine` convenience API or the `Transform` method to make multiple predictions. Here is a guide on how to use a model to make predictions:

[Use a model to make preedictions](https://docs.microsoft.com/dotnet/machine-learning/how-to-guides/machine-learning-model-predictions-ml-net)

I would encourage you to take a look at the how-to guides since much of the ML.NET code would be the same for the most part regardless of whether you're using .NET Core or .NET Framework.

- [Load Data](https://docs.microsoft.com/dotnet/machine-learning/how-to-guides/load-data-ml-net)
- [Prepare Data](https://docs.microsoft.com/dotnet/machine-learning/how-to-guides/prepare-data-ml-net)
- [Train and evaluate a model](https://docs.microsoft.com/dotnet/machine-learning/how-to-guides/train-machine-learning-model-ml-net) 

Another alternative would be to use [Model Builder](https://docs.microsoft.com/dotnet/machine-learning/automate-training-with-model-builder) or the [ML.NET CLI](https://docs.microsoft.com/en-us/dotnet/machine-learning/automate-training-with-cli) to train a model. Both options provide you with a low-code way to train models. Note that they generate consumption and retraining code using .NET Core. However, using the generated code is optional.

I would also suggest in addition to looking at our guides and tutorials, check out the [machinelearning-samples](https://github.com/dotnet/machinelearning-samples) repository to get a sense of how to use the framework for different scenarios. I see you have already opened an issue dotnet/machinelearning-samples#842. I'll add a few tags so users are aware that help is needed on this and community contributions and input are welcome.  You can also check out the [Community Samples](https://github.com/dotnet/machinelearning-samples/blob/master/docs/COMMUNITY-SAMPLES.md). There is currently a [sample](https://mp.weixin.qq.com/s/x7mxim9uUoAfIEE_kvyFWg) that uses .NET Framework and an older version of ML.NET. Please note that the post is written in Chinese, so you may have to enable your browser translation features (if available) if that is not your native language.

I hope this helps. I'll close this issue for now and keep the issue in the machinelearning-samples repo open. Thanks again for your feedback.

**Comment by sanketshah11** [comment]
If I could have used .NET Core, I would have not asked for a sample. I already went through all the links posted in the answer before posting this request, even the one written in Chinese and the samples on github. Why are all examples focused on .Net Core even though the website clearly suggests it works on .Net Framework. Will all the functionality work as expected for a commercial project ? Sample would be very helpful.

**Comment by luisquintanilla** [comment]
Hi @sanketshah11 

ML.NET is built on .NET Standard which means it supports both .NET Core and .NET Framework. The choice to build samples for .NET Core comes from the overall .NET strategy.  You can read more about it in this [blog post](https://devblogs.microsoft.com/dotnet/net-core-is-the-future-of-net/). While future investments will be made on .NET Core, .NET Framework applications will continue to be supported and are safe to stay on that platform.
