### ISSUE TITLE
Finally is executed in C# 8.0

### ISSUE THREAD

**Issue by colbroth** [dotnet/docs#20274]
[The article gives an example of the finally block not getting executed when an exception is not handled. Is this still true for C# 8.0. I wrote an example to see and the finally block is getting hit. If so, could this page be updated to indicate this.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cd59701-079e-fdda-0c47-290f24f9eb4e
* Version Independent ID: a6f2953b-0da7-19fd-e121-aaeb65f60b17
* Content: [try-finally - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-finally)
* Content Source: [docs/csharp/language-reference/keywords/try-finally.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/try-finally.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @colbroth 

This is an area that is complicated by what is guaranteed by the C# standard and the CLR spec, as opposed to what is almost certainly going to happen in "normal" programs.

In almost all circumstances, `finally` blocks will run. The standard doesn't guarantee it, because there are edge cases where a program is quickly terminated. (One known example is an `InvalidProgramException`, where the IL statements are corrupt.)

The 2nd paragraph in this article should be updated to clarify the following points:
- In almost all cases, `finally` clauses will run.
- The only cases where `finally` clauses don't run involve a program being immediately stopped. On most operating systems, reasonable resource cleanup will take place as part of stopping and unloading the process.
