### ISSUE TITLE
What if I need to stream non-paginated data, like streaming stock price data?

### ISSUE THREAD

**Issue by JasOcher** [dotnet/docs#20284]
How would this be used to stream and return never-ending data such as stock or other market price data?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17f03524-58d6-870c-e43f-e7f9565608e5
* Version Independent ID: da634f1c-bb77-efb5-0066-c3760b79fa4c
* Content: [Generate and consume async streams](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/generate-consume-asynchronous-stream?WT.mc_id=anthonychuca-blog-antchu)
* Content Source: [docs/csharp/tutorials/generate-consume-asynchronous-stream.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/generate-consume-asynchronous-stream.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @JasOcher I've added this our backlog to address when we update this article (or create a new tutorial for never-ending streams)

To answer your question: Your `await foreach` loop would be an infinite loop because the stream doesn't end. In that case, you'd need to use some cancellation mechanism to stop reading from the stream and let it close in its `DisposeAsync` method.

**Comment by JasOcher** [comment]
Thanks Bill.  In regards to returning the data to a client UI or something, how would that be done when the stream isn't actually finished?

**Comment by BillWagner** [comment]
@JasOcher In an async stream, each element is available as its read. Once any work for `MoveNextAsync()` is completed, the `Current` property returns synchronously.

**Comment by JasOcher** [comment]
Great, thanks!
