### ISSUE TITLE
<include> example does not indicate every member must be decorated

### ISSUE THREAD

**Issue by bwatts** [dotnet/docs#20314]
The example on this page only shows how to provide documentation at the class level. It does not attempt to show how to specify comments for members of the class, though there are methods in the example.

This led me to a bunch of trial and error before I found that all members, not just the class, must have the `<include>` tag.

This makes the feature far less attractive, and that caveat should be readily available to future readers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8d418e3-b648-587e-155d-843ffb48b025
* Version Independent ID: 606a07e0-da13-f58f-4e64-be634479a55d
* Content: [&lt;include&gt; - C# programming guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/include)
* Content Source: [docs/csharp/programming-guide/xmldoc/include.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/xmldoc/include.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
adding @mikadumont to confirm the correct behavior.

**Comment by mikadumont** [comment]
@sharwell to take a look

**Comment by sharwell** [comment]
The `<include>` element only refers to the documentation for a single code element. The best way to improve the example on this page would be to document `Test.Main()` and `Test2.Test()` in addition to the types that are already documented.

@bwatts I would not recommend using `<include>`. It is slower for some analyzers, and does not integrate cleanly with IDE analyzers, code fixes, and refactorings. It is also tedious to define and maintain, and exacerbates problems related to code and documentation being out-of-date because you cannot see both at the same time.

**Comment by bwatts** [comment]
@sharwell Thanks for your reply. I did realize that the `<include>` would need to be on the methods as well. My feedback was that if your example were explicitly outlined in the docs, I likely would have realized the feature did not meet my needs sooner.

My goal was to provide robust documentation for a library I'm writing, without reducing the amount of C# in each file to 10-20%. This seemed promising, but I agree it ultimately isn't the right path.
