### ISSUE TITLE
mistake on documentation? Implicit conversions involving type parameters

### ISSUE THREAD

**Issue by leekr7070** [dotnet/docs#20323]
Is that a mistake on C# 6.0 Draft Standard or am i missing some new feature of C# 6.0?

[C# 5.0 Standard](https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-334.pdf)
> From T to an interface type I if it has an implicit conversion to an interface type I0, and I0 is varianceconvertible to I

[C# 6.0 Draft Standard](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/conversions#implicit-conversions-involving-type-parameters)
> From T to an interface type I if it has an implicit conversion to an interface or delegate type I0 and I0 is variance-convertible to I

If I is an interface type and I0 is variance-convertible to I, them I0 must also be an interface type! I0 will never be a delegate type!

**so instead of:**
> From T to an interface type I if it has an implicit conversion to an interface or delegate type I0 and I0 ...

**it should be:**
> From T to an interface type I if it has an implicit conversion to an interface type I0 and I0 ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7be4c24e-9e92-6b75-2b8e-2cb6cb072b5b
* Version Independent ID: 450064c8-720e-3b90-18d6-7bd5f183857e
* Content: [Conversions - C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/conversions#implicit-conversions-involving-type-parameters)
* Content Source: [spec/conversions.md](https://github.com/dotnet/csharplang/blob/master/spec/conversions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
I believe it's like this because the C# 5.0 spec is newer than the C# 6.0 draft spec (yes, really) and so only the C# 5.0 spec has the fixed wording. Once proper C# 6.0 spec is released (I think https://github.com/dotnet-foundation/projects/issues/90 is the most recent activity on that front), it should have the correct wording.

In more detail: MS released [their version of the C# 5.0 spec](https://www.microsoft.com/en-us/download/details.aspx?id=7029) in 2013, which contains the mistake you mention. Then, MS released a draft spec for C# 6.0, based on their version of the C# 5.0 spec, still containing the mistake. In 2017, Ecma released their version of the C# 5.0 spec, which contains improvements from the MS version of the spec. Now, Ecma is working on releasing their version of the C# 6.0 spec, based on their version of the C# 5.0 spec.

**Comment by BillWagner** [comment]
Thanks for writing this @leekr7070 

@svick has provided all the background on the history.  The standards committee has been working to add the C# 6.0 features to the C# 5.0 standard, and we should have a public draft if and when we are approved by the .NET foundation. 

I'll keep this open until we release that update, and assign it to me.

**Comment by leekr7070** [comment]
@svick @BillWagner 
Ok! Thanks for your attention!
Now i understand it.

**Comment by BillWagner** [comment]
Closing.  This is correct in the draft standard in [csharpstandard](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/conversions.md#11211-implicit-conversions-involving-type-parameters)
