### ISSUE TITLE
code in article is obsolete. Current version of ocelot is 16

### ISSUE THREAD

**Issue by ip75** [dotnet/docs#20393]
configuration file format changed. Your article is not actual. I spent much time to fix my project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10ce8eaa-b3ff-9b69-fea1-131eed36b9ec
* Version Independent ID: 771d9f72-b506-79ef-5398-030c1705ee9a
* Content: [Implementing API Gateways with Ocelot](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot)
* Content Source: [docs/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hello @ip75, Thank you for your feedback. 

Yes, in the reference application [`eShopOnContainers`](https://github.com/dotnet-architecture/eShopOnContainers) 
we don't use the `Ocelot` API Gateway any more. Instead of that we use `Envoy`.
Based on the recent feedback, we have tried to include more details on `Ocelot` version 16 related changes in the documentation. You can refer the PR #19980 for more details. 

We are closing this issue as of now, as it's already addressed. If you have any questions, please feel free to reopen it.
