### ISSUE TITLE
Thread behawior for Result property

### ISSUE THREAD

**Issue by mpostol** [dotnet/docs#20484]
`The Result property is a blocking property. If you try to access it before its task is finished, the thread that's currently active is blocked until the task completes and the value is available.`

 My concern is that `await` and `async` doesn't produce additional threads. So the Task producing Result may be executed on the same thread as the caller. Blocking the thread that calculates the result is useless. The sentence makes sense only if the caller is executed on a different thread. What happens if it is not the case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d055727b-c97c-4d25-39b8-a4d3f21d0444
* Version Independent ID: c8a7c6f1-8ee1-5030-db12-3db65a968501
* Content: [Async return types (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/async-return-types)
* Content Source: [docs/csharp/programming-guide/concepts/async/async-return-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/async-return-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
> So the Task producing Result may be executed on the same thread as the caller.

I think "may" is the important word here: under the default synchronization context, a `Task` can be executed on any `ThreadPool` thread.

> Blocking the thread that calculates the result is useless.

Yes. If you can, you should use `await task`, not `task.Result`.

> The sentence makes sense only if the caller is executed on a different thread. What happens if it is not the case?

If you have a `Task` that needs to execute on a specific thread (usually because of a custom synchronization context, such as in a WinForms or WPF app), then this can lead to a [deadlock](https://en.wikipedia.org/wiki/Deadlock).

**Comment by mpostol** [comment]
@svick thanks for the answer. Because I am working with students and my goal is to expand the [examples](https://github.com/mpostol/TP) I am using during my classes. Therefore,  let me continue this interesting discussion. 

As I said `await and `async` doesn't produce additional threads. ` - is it true? It is for sure.

In this case, we must consider the scenario that everything happens on one single thread (it is similar to well known concurrent programming paradigm when we have time-sharing for example to distinguish asynchronous operations executed on one processor). 

From the text we can read:

`The Result property is a blocking property.`

As mentioned above, assuming that the task and the call to Task.Result is on the same thread (is it possible?) it causes the deadlock condition - the thread blocks on the Result, and the Task cannot be executed because the thread is blocked on the Task.Result. 

My genera note is that you are using the terms task, thread, and synchronization context, but there is no description of the relation between them.  

What do you mean blocking the thread - a thread can be suspended - is it the same? Suspending the thread means that it may be rescheduled (i.e. continued), but after blocking ...

There is a more general problem. The documentation distinguishes two kinds of tasks: computation bounded and I/O bounded. How to classify the task that executes Task.Delay(x). 

Hope it helps.

Mariusz

**Comment by svick** [comment]
> As I said `await` and `async` doesn't produce additional threads. - is it true? It is for sure.

I wouldn't phrase it that way. There are certain patterns where just using `async`-`await`, you cause new threads to be added to the thread pool. But it's true that in general, calling an `async` method does not start a new thread.

> we must consider the scenario that everything happens on one single thread
> As mentioned above, assuming that the task and the call to Task.Result is on the same thread (is it possible?) it causes the deadlock condition

That's not how it works. A task that's not currently executing doesn't have a thread assigned. And with the default synchronization context, any task can execute on any thread pool thread. So a deadlock in the simple case would be possible only if there was limit to have only a single thread in the thread pool, which doesn't happen in practice.

> My general note is that you are using the terms task, thread, and synchronization context, but there is no description of the relation between them.

You can read the documentation: [`Task`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task?WT.mc_id=DOP-MVP-5002735), [`Thread`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.thread?WT.mc_id=DOP-MVP-5002735), [`SynchronizationContext`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.synchronizationcontext?WT.mc_id=DOP-MVP-5002735). I think that should be sufficient.

> What do you mean blocking the thread - a thread can be suspended - is it the same? Suspending the thread means that it may be rescheduled (i.e. continued), but after blocking ...

If you're talking about the `Thread.Suspend` method, then that's long been obsoleted and you shouldn't use it or teach it to your students (except possibly as an outdated curiosity).

Otherwise, they are similar. In both cases, the thread is temporarily not eligible to be executed and will become eligible again after something happens. But I wouldn't call them the same.

> The documentation distinguishes two kinds of tasks: computation bounded and I/O bounded. How to classify the task that executes Task.Delay(x).

`Task.Delay` is certainly not CPU-bound (I think that's a more common term for "computation-bound"). And it doesn't perform any input or output. So I'd say it's neither.

**Comment by BillWagner** [comment]
I've caught up to the discussion. It seems that @svick has addressed all the question raised by @mpostol 

I believe this can be closed without further action in docs.

Reopen with a comment why if you disagree.

**Comment by mpostol** [comment]
Thanks, you can consider it as answered. I believe that further improvement of the description should be addressed by separate publications. My point is that simplicity was not born by simplification. I prefer abstraction to hide details but don't forgot about them at the same time. I still believe that the topic needs a systematic approach to describe all aspects of the asynchronous versus synchronous processing, reactive programming, concurrency, parallel processing, real-time, critical section, race condition, scheduling, synchronization, deadlock, threads, tasks, processes, etc.  I am looking for motivation and volunteers.
