### ISSUE TITLE
Permission for dotnet-dump in Docker

### ISSUE THREAD

**Issue by zhiweiv** [dotnet/docs#20573]
> Special instructions for Docker
> If you're running under Docker, dump collection requires SYS_PTRACE capabilities (--cap-add=SYS_PTRACE or --privileged).

In kubernetes, I didn't add privileged permission to pod, I can still dump and analyze by dotnet-dump in linux pod, is this part outdated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a269a64-0a27-27d3-a509-47b9a0d114bf
* Version Independent ID: 49ff97ff-b39a-5ae8-e4b8-81a4f8eab50c
* Content: [dotnet-dump - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-dump)
* Content Source: [docs/core/diagnostics/dotnet-dump.md](https://github.com/dotnet/docs/blob/master/docs/core/diagnostics/dotnet-dump.md)
* Product: **dotnet-core**
* GitHub Login: @sdmaclea
* Microsoft Alias: **stmaclea**

**Comment by sdmaclea** [comment]
/cc @dotnet/dotnet-diag 

When we wrote this we weren't aware that this would work.  So yes it is outdated.

The `SYS_PTRACE` capability is only required to use `createdump` from a separate process.  dotnet-dump ask the process to dump itself so the capability is not needed.

**Comment by shirhatti** [comment]
If you have Docker 19.03.8 or newer, dotnet-dump will work if without requiring `CAP_SYS_PTRACE` if:
- `kernel.yama.ptrace_scope` <= 1 (on the host in the `cat /etc/sysctl.d/10-ptrace.conf` file)
- Linux Kernel version >= 4.8

------------------------------------

The mechanism we used to collect dumps relies on ptrace. The diagnostic server exposed by the runtime listens to a unix domain socket. On receiving the right request, the runtime forks and launches createdump via execve. The forked process now connects back to it’s parent process via PTRACE and is able to dump the process’ virtual memory.

In most security conscious environments, we use of ptrace was not permitted. Per my understanding, this is changing due to introduction of YAMA, a Linux security module. YAMA allows you more granular control over ptrace

Copying the relevant parts of the man page for YAMA:
```
0 - classic ptrace permissions: a process can PTRACE_ATTACH to any other
    process running under the same uid, as long as it is dumpable (i.e.
    did not transition uids, start privileged, or have called
    prctl(PR_SET_DUMPABLE...) already). Similarly, PTRACE_TRACEME is
    unchanged.

1 - restricted ptrace: a process must have a predefined relationship
    with the inferior it wants to call PTRACE_ATTACH on. By default,
    this relationship is that of only its descendants when the above
    classic criteria is also met. To change the relationship, an
    inferior can call prctl(PR_SET_PTRACER, debugger, ...) to declare
    an allowed debugger PID to call PTRACE_ATTACH on the inferior.
    Using PTRACE_TRACEME is unchanged.

2 - admin-only attach: only processes with CAP_SYS_PTRACE may use ptrace
    with PTRACE_ATTACH, or through children calling PTRACE_TRACEME.

3 - no attach: no processes may use ptrace with PTRACE_ATTACH nor via
    PTRACE_TRACEME. Once set, this sysctl value cannot be changed.
```

Docker made the change to no longer disallow ptrace as part of their [seccomp](https://github.com/moby/moby/blob/d984d3053be3d4abcc7b49d806f08409f61c522f/profiles/seccomp/default.json#L395-L406) profile provided you’re running at least kernel version 4.8.

As such, in my AKS cluster where my kernel version was 4.15.0-1066-azure, I was able to capture a dump without explicitly granting CAP_SYS_PTRACE or –priviliged to collect a process dump.

**Comment by zhiweiv** [comment]
It is still intend to be updated? Two years since first open.

**Comment by hoyosjs** [comment]
Yes, @zhiweiv. We've done some work on this lately, but I didn't see that the section at the bottom of the doc was still outdated. I wasn't aware of this issue until I got notified of it getting closed.
