### ISSUE TITLE
Consolidate create-document-namespaces

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#20633]
https://github.com/dotnet/docs/blob/master/docs/standard/linq/create-document-namespaces-csharp.md

https://github.com/dotnet/docs/blob/master/docs/standard/linq/create-document-namespaces-visual-basic.md

I think this should have been done in #17213. But was missed for some reason.

cc: @mairaw @jameshkramer

**Comment by Youssef1313** [comment]
@mairaw, I just noticed there are still articles in the language-specific folders (e.g. https://github.com/dotnet/docs/tree/master/docs/visual-basic/programming-guide/concepts/linq)

Was these not moved to standard directory for some reason?

**Comment by mairaw** [comment]
So, two separate issues:

The first one is by design since the technique used in VB is different than C#.

The second one the @dotnet/docs team will need to decide whether they will continue the consolidation project. The LINQ to XAML one was the first section I started with and the idea was to continue.
Here's another related issue opened by @gewarren https://github.com/dotnet/docs/issues/16482

**Comment by Youssef1313** [comment]
Thanks @mairaw for clarifying.

I think this can be closed in favor of #16482
