### ISSUE TITLE
Create pages documenting .NET SDK error messages

### ISSUE THREAD

**Issue by tdykstra** [dotnet/docs#20656]
An example of a .NET SDK error is [NETSDK1045](https://github.com/dotnet/sdk/blob/175d288a26019d74ea7f4524cb5195a28135b0ee/src/Tasks/Common/Resources/Strings.resx#L282-L285).

Follow pattern of [C# compiler error docs](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/)

High-traffic errors (# of F1 queries from VS)

- [x] NETSDK1045
- [x] NETSDK1004
- [x] NETSDK1064
- [x] NETSDK1079
- [x] NETSDK1071
- [x] NETSDK1005
- [x] NETSDK1080
- [x] NETSDK1022
- [x] NETSDK1073
- [x] NETSDK1013
- [x] NETSDK1138
- [x] NETSDK1137
- [x] NETSDK1136
- [x] NETSDK1141
- [x] NETSDK1130
- [x] NETSDK1112

Periodically review traffic statistics and document additional error numbers.

**Comment by adegeo** [comment]
Do we want to automate the creation of each file and basic structure?

**Comment by tdykstra** [comment]
I was thinking we would create a stub file and each time a page is created it would start by copying the stub Markdown.  Do you have a better idea?

**Comment by adegeo** [comment]
That sounds good. Can just use some powershell to load the xml file and for each data/value combo extract the error code and description and fill it in the copied file.

**Comment by tdykstra** [comment]
As long as it works selectively one by one, as we don't need to create pages for all of the errors, only those that require more explanation than the message itself conveys.

**Comment by adegeo** [comment]
We wouldn't want them all? If someone uses the error lookup in visual studio, where would it go for a missing error?

**Comment by tdykstra** [comment]
We could create one doc that lists all error numbers for which we decided additional information is not needed.

**Comment by marcpopMSFT** [comment]
I had originally assumed we'd have one doc with all the items in a table but I see that compiler errors and CA warnings are all separate documents so we'd be matching that existing experience.  Note that we may not have a lot of extra detail for many of them beyond what's in the message (as hopefully most of the messages are enough).

**Comment by ghogen** [comment]
@tdykstra @adegeo @marcpopMSFT  Some of these are still impacting our VS hub page, most significantly NETSDK1045 and NETSDK1004, which rank as one of top 25 incoming F1 queries.  

For NETSDK1045, I see a StackOverflow article that is currently popular, which could potentially be used as inspiration for an article. https://stackoverflow.com/questions/55741953/getting-netsdk1045-the-current-net-sdk-does-not-support-net-core-3-0-as-a-tar 

NETSDK1004 seems to be about a missing assets file, but that could have many causes.  I'd be in favor of adding the article here to capture the F1 traffic, even if it's fairly short and simple. https://stackoverflow.com/questions/55208188/how-to-fix-appcenter-build-error-netsdk1004 https://intellitect.com/netsdk1004-compile-error/

**Comment by adegeo** [comment]
@ghogen This was created, and some others: https://docs.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1005

**Comment by ghogen** [comment]
@adegeo OK, that's for NETSDK1005 but we are still seeing NETSDK1004 - maybe there's some slight difference if they both deal with a missing assets file.

**Comment by ghogen** [comment]
@adegeo It looks like @gewarren just added a doc for NETSDK1004. https://github.com/dotnet/docs/pull/22517 - Thanks!

If no one is working on NETSDK1045, I could submit one based on the StackOverflow information, as a start.

**Comment by marcpopMSFT** [comment]
@tdykstra , per our offline conversation, here are some comments on the top error codes customers are hitting F1 for so you can create a landing page for each. Let me know if you have questions for these and please include @dsplaisted on any PR review for these.
ErrorCode | Message | Comment |
-|-|-
NETSDK1138 | NETSDK1138: The target framework '{0}' is out of support and will not receive security updates in the future. Please refer to {1} for more information about the support policy. | The message routes customers to https://aka.ms/dotnet-core-support. we give a warning whenever the customer has a TargetFramework for a runtime that's out of support. That currently includes 1.0, 1.1, 2.0, 2.1, 2.2, and 3.0. We will add 5.0 in November. Customers can disable this warning by setting <CheckEolTargetFramework>false</CheckEolTargetFramework> in their project file
NETSDK1082 | NETSDK1082: There was no runtime pack for {0} available for the specified RuntimeIdentifier '{1}'. | This is somewhat similar to https://docs.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1145 and a potentially workaround is similar as well \<KnownRuntimePack Update="@(KnownRuntimePack)">\<LatestRuntimeFrameworkVersion Condition="'%(TargetFramework)' == 'TARGETFRAMEWORK'">EXISTINGVERSION\</LatestRuntimeFrameworkVersion>\</KnownRuntimePack>. Basically, we download known runtime packs for self-contained applications but there could be a pointer to one that's not available to the customer. They either have to override the value to one that's available on their nuget feeds or investigate their nuget configuration.
NETSDK1136 | NETSDK1136: The target platform must be set to Windows (usually by including '-windows' in the TargetFramework property) when using Windows Forms or WPF, or referencing projects or packages that do so. | If UseWindowsForms or UseWPF is true, we assume it's a windows app and so the platform has to be set to windows. net6.0-windows works. This can happen if a customer has a project to project reference where one is set to windows and the other is not.
NETSDK1112 | NETSDK1112: The runtime pack for {0} was not downloaded. Try running a NuGet restore with the RuntimeIdentifier '{1}'. | I think this can happen if you did tried to publish without building first and so the runtime pack was not available.
NETSDK1137 | NETSDK1137: It is no longer necessary to use the Microsoft.NET.Sdk.WindowsDesktop SDK. Consider changing the Sdk attribute of the root Project element to 'Microsoft.NET.Sdk'. | The customer should modify their project file to have \<Project Sdk="Microsoft.NET.Sdk"> instead of the WindowsDesktop sdk. This was changed in 5.0.
NETSDK1182 | NETSDK1182: Targeting .NET 6.0 or higher in Visual Studio 2019 is not supported. | There are more details on our support policy here: https://docs.microsoft.com/en-us/dotnet/core/porting/versioning-sdk-msbuild-vs
NETSDK1135 | NETSDK1135: SupportedOSPlatformVersion {0} cannot be higher than TargetPlatformVersion {1}. | The customer would want to check their project files for SupportedOSPlatformVersion. TargetPlatformVersion is inferred from the TargetFramework value.  So net6.0-windows10.0.19041 will set the TPV to be 10.0.19041. We use TargetPlatformVersion to determine which apis are available at compile time.

**Comment by gewarren** [comment]
Closing per @tdykstra.
