### ISSUE TITLE
Incorrectly marked code blocks

### ISSUE THREAD

**Issue by svick** [dotnet/docs#2069]
It seems that some code blocks in API reference are not correctly marked at all, resulting in code blocks that are not syntax highlighted and are preceded by e.g. "[C#]". For example, in [`BigInteger.IsEven`](https://docs.microsoft.com/en-us/dotnet/api/system.numerics.biginteger.iseven?view=netframework-4.7#remarks):

![](https://cloud.githubusercontent.com/assets/287848/25617358/2cf59c6e-2f42-11e7-945b-72cc7b3d2b78.png)

Running `git grep '\[C#\]' | wc -l` in the xml directory reports 92 occurrences.

In other cases, the code blocks are marked, but aren't included from snippets, which seems to result in showing code in all languages. For example, in [`List<​T>.ICollection.​Sync​Root`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.system-collections-icollection-syncroot?view=netframework-4.7#remarks):

![](https://cloud.githubusercontent.com/assets/287848/25617428/8d3e3540-2f42-11e7-9919-2f7bda7b6fb6.png)

(The `cpp#` language identifier is also confusing, I guess it represents C++/CLI?)

**Comment by tompratt-AQ** [comment]
@mairaw I'd like to take on this issue and fix these. In addition to the 92 instances in \xml, I found at least 19 files (~30 instances) with [C#] in \docs. I could also clean up the cpp# instances which look like a straight miscoding of cpp or the coding changed at some point? I say this because the examples are introduced as being c++ examples.

**Comment by mairaw** [comment]
Sure @tompratt-AQ. That would be great!
