### ISSUE TITLE
"Native sized ints don't have constants for MaxValue or MinValue, except for nuint.MinValue, which has a MinValue of 0."

### ISSUE THREAD

**Issue by curia-damiano** [dotnet/docs#20802]
In C#9 with .NET 5 RC1, nunit.MinValue is also a property and not a constant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36588d0-6bdf-1740-220c-10b20bb88730
* Version Independent ID: 587ed47f-f532-e018-9b0d-6ee76afd20e4
* Content: [What's new in C# 9.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9#fit-and-finish-features)
* Content Source: [docs/csharp/whats-new/csharp-9.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-9.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
ping @jcouv 

Is this a temporary behavior, or will `nuint.MinValue` be a compile time constant in later builds?

**Comment by jcouv** [comment]
Tagging @cston. I think this is by-design (the Min and Max values are not constants). I'm not sure what's the point of making `nuint.MinValue` as a constant, as that would be the exception and doesn't seem very useful.

**Comment by cston** [comment]
As @jcouv mentioned, this is by design. The values `nint.MinValue`, `nint.MaxValue`, and `nuint.MaxValue` depend on the runtime so the members are not constants.

cc @tannergooding

**Comment by tannergooding** [comment]
Yep, these cannot be "compile-time constants" as their value (minus `nuint.MinValue`) are dependent on the platform the code is running on.

The runtime should treat them as "jit-time constants", however, and the ultimate code output should be identical to as if a compile-time constant had been used.

**Comment by BillWagner** [comment]
@tannergooding  

> The runtime should treat them as "jit-time constants", however, and the ultimate code output should be identical to as if a compile-time constant had been used.

I'd like a bit of clarification on this.  In general, references to compile time constants, declared as `const`, are replaced by their value at compilation. That means changing the value of a `const` value is a binary breaking change: all consumers must recompile. That won't be true here, correct? Here, if one of these values change, that is neither source breaking nor binary breaking because the value is not evaluated at compile time. Is that correct?

**Comment by tannergooding** [comment]
> In general, references to compile time constants, declared as const, are replaced by their value at compilation.

Right.

> That means changing the value of a const value is a binary breaking change: all consumers must recompile.

It means that users must recompile to get the new value. I'm not sure how this is normally classified with regards to breaking changes.

> That won't be true here, correct? Here, if one of these values change, that is neither source breaking nor binary breaking because the value is not evaluated at compile time. Is that correct?

Correct, rather than being evaluated at C#/F#/VB compile time (when the source is compiled to IL) it is evaluated at JIT/AOT time (when the IL is compiled to native assembly).
You can, for example, see this here: https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATARgLABQGAzAATakDCpA3oaQ+WZAHYDOALqQJYteU5SAXlIBWANz1GUhiXI4kPPlSzCAfGMkFGpGUyVcAsjgAUASnVVBAalLEtOvXN5Gs5y5VW37hAL5A==

`M1` is compiled to directly return `8` as `C1` is a compile-time constant. While `M2` is compiled as `C2 + 3`, because C2 is a property.

However, if you look at the JIT Asm output: https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACMhgYQYG8aHunHIA7XBgYBLfsJbkGAXgYBWANxcey7vSbkko8a1IyAfPKXUeDVb23CAsuQAUASgOspAagZ1jp8+rHXSDpxY9Nw8aAF8gA=

You will see that both `M1` and `M2` directly return `8`, because while it wasn't a compile-time constant, the runtime can determine it is a JIT-time constant and do the necessary constant propagation to result in the same code.
`IntPtr` has a different value on different platforms but on a given platform, that value is constant. So it needs to be a property but can ultimately still be optimized the same.

**Comment by curia-damiano** [comment]
Thank you @tannergooding for your clarification.
But so, there is no difference between nunit.MinValue and all the other values (nint.MinValue, nint.MaxValue, nunit.MaxValue), and I don't see the reason to explicitly document that this particular value is treated as a constant.
I would rather say that during development time all 4 values are seen as properties, but then converted to constants during native code generation.

**Comment by BillWagner** [comment]
You are correct @curia-damiano 

This was my mistake. I mis-read the spec. I've added this to our current sprint for me to fix.
