### ISSUE TITLE
Insufficient information on hyphen behaviour inside character groups

### ISSUE THREAD

**Issue by ShinuziKyura** [dotnet/docs#20810]
It appears that inside character groups, the hyphen can be included in the group by being escaped using backslash: `\-`.

However, this still doesn't allow it to be used as the limit for a range of characters. This can still only be done if the hyphen is in the first or last character of the group, i.e.
```
// The second hyphen is seemingly ignored and there is no range defined...
// The following four examples have the same result when the expression is @"[+\-/]"

Regex.IsMatch("+", @"[+\--/]"); // true
Regex.IsMatch("-", @"[+\--/]"); // true
Regex.IsMatch(".", @"[+\--/]"); // false, if the range was properly defined, this should be true as well
Regex.IsMatch("/", @"[+\--/]"); // true

// The range is also not defined if we escape the hyphen even when it is the first character of the group
Regex.IsMatch("-", @"[--/]"); // true, as expected
Regex.IsMatch(",", @"[--/]"); // true, as expected
Regex.IsMatch("-", @"[\--/]"); // true
Regex.IsMatch(".", @"[\--/]"); // false, if the range was properly defined, this should be true as well
```

It kinda seems like a bug in the implementation, but on the other hand, it might just be a lapse on the documentation, I can't say for sure.
If it's the latter, maybe we can improve the docs by including some information regarding these cases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1958bf6-a17d-1256-d659-31066aa02604
* Version Independent ID: 95abea42-fa7f-3feb-ae38-049719ab938f
* Content: [Character Classes in .NET Regular Expressions](https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions#character-class-subtraction-base_group---excluded_group)
* Content Source: [docs/standard/base-types/character-classes-in-regular-expressions.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/character-classes-in-regular-expressions.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
I do feel like it's a bug, or there is some option that needs to be enabled, to get this to work. Using an online regex parser it works just as you expect it to, the range is implemented and `.` matches.

Can you comment @pgovind @eerhardt ?

**Comment by ShinuziKyura** [comment]
I've been testing a bit more, and indeed it begins to feel like a bug, it gets even weirder when the hyphen is the last character of the group and we escape it:
```
Regex.IsMatch("*", @"[*--]"); // true
Regex.IsMatch("+", @"[*--]"); // true
Regex.IsMatch("-", @"[*--]"); // true

Regex.IsMatch("*", @"[*-\-]"); // false, what???
Regex.IsMatch("+", @"[*-\-]"); // false, consistent with range not being defined
Regex.IsMatch("-", @"[*-\-]"); // true
```

**Comment by eerhardt** [comment]
@ShinuziKyura - what version of .NET were you testing? .NET Framework?

I tried the following on .NET 5 and all lines print `true`:

```C#
Regex.IsMatch("*", @"[*-\-]");
Regex.IsMatch("+", @"[*-\-]");
Regex.IsMatch("-", @"[*-\-]");
```

I believe this was fixed by https://github.com/dotnet/runtime/pull/1075.

**Comment by ShinuziKyura** [comment]
I believe it was .NET Core 3.1 (at least, I was able to replicate the original results just testing it now).

Looking at that issue, it does seem to be related. So going by the fix, and back to my original question, should the docs be updated to reflect that it should be possible to escape the hyphen when used inside a character class?

**Comment by eerhardt** [comment]
> should the docs be updated to reflect that it should be possible to escape the hyphen when used inside a character class?

Yes, I believe the docs should be updated that this is now possible in .NET 5.

cc @stephentoub @pgovind

**Comment by adegeo** [comment]
@ShinuziKyura I'm fixing this and some other issues raised about this article. However, in looking at where to put this information I discovered this note in the article where it's talking about character ranges:

> ![image](https://user-images.githubusercontent.com/67293991/184424228-972008d8-7596-4386-9486-edeb2e0c7af9.png)

My question is, if you must have the character at the start or end of the range, why would you need to escape it? Is there really anything to detail here? If you follow the rule of always putting the character at the start or end, unescaped, it should work all the time, right?

**Comment by eerhardt** [comment]
FYI - @joperezr

**Comment by joperezr** [comment]
the dash (`-`) is mostly a normal character in Regex except when used in character classes. If the dash is not either the first or the last character inside your character class definition it will need to be escaped.

@adegeo imagine the following scenario: you want a character class that includes all characters between `-` and `/`, then you would write a pattern like: `[--/]` without the need of escaping (since the dash is the first character in your character class). But now imagine that you want the same character class but also include the letter `a`. If you don't escape the character class, and just write it like: `[a--/]` the engine will have no way of knowing if the dash after the `a` is trying to define a range between the `a` and `-` or it should interpret the `a` as a single character, and the dash as part of the firstCharacter of a range. For this reason, the way to write that pattern is: `[a\--/]` which will signal the engines that the dash after the `a` shouldn't be counted as a range limiter. I hope that sort of makes sense.

**Comment by adegeo** [comment]
@joperezr Yes that makes sense! Thanks! In adding all of the examples that were detailed in this issue into a single program, I was able to generate results for each platform. They're the same as mentioned in this issue except for those final 3:

```
Regex.IsMatch("*", @"[*-\-]");
Regex.IsMatch("+", @"[*-\-]");
Regex.IsMatch("-", @"[*-\-]");
```

Starting in .NET 5 it's always true, while in anything prior (including .NET Framework) it's false, false, true. So the question now is what is the problem? Was there a bug in .NET Framework - .NET Core 3.1 which caused the incorrect result? Is the issue that `[*-\-]` isn't using the escaped `-` at the end as a proper character to complete the range and this was fixed in .NET 5? I'm unsure what to say exactly..

**Comment by joperezr** [comment]
Note that the pattern you shared above doesn't need the dash to be escaped (since the dash is at the end of the character class). You  should get the same results for:
```c#
Regex.IsMatch("*", @"[*--]");
Regex.IsMatch("+", @"[*--]");
Regex.IsMatch("-", @"[*--]");
```

>  Was there a bug in .NET Framework - .NET Core 3.1 which caused the incorrect result?

There was likely a bug in the parser that would interpret that character class differently (probably was taking the  `*` as a quantifier). In any case, I think the only way to know for sure would be to run it under the debugger to see how the parser was interpreting it.
