### ISSUE TITLE
C# 8 and 9 Pattern Matching

### ISSUE THREAD

**Issue by 333fred** [dotnet/docs#21026]
I don't see any examples for C# 8 and 9-style pattern matching on our pattern matching page. No recursive patterns, positional patterns, property patterns, etc. We likely need to copy in the examples from https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#more-patterns-in-more-places.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1f2a2fe-8279-e6b3-93e8-33398167655f
* Version Independent ID: 35191215-988f-3700-1f85-4751711f692e
* Content: [Pattern Matching - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/pattern-matching)
* Content Source: [docs/csharp/pattern-matching.md](https://github.com/dotnet/docs/blob/master/docs/csharp/pattern-matching.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @333fred 

I've added this to the list of .NET 5 / C# 9 updates.

**Comment by BillWagner** [comment]
@pkulikov Are there tasks remaining for this issue? Or did the recent PRs address everything?

**Comment by pkulikov** [comment]
@BillWagner the tasks I'm going to work further are about updating the reference pages (of `switch` and `is`).

However, it's not related to this issue. This issue is about the concept article:

https://docs.microsoft.com/en-us/dotnet/csharp/pattern-matching

Looks like that article was written in the C# 7.0 time and has not been updated since then. Nowadays, it's out-of-date. Also, it has big overlap with the reference about the `switch` statement. That is not necessary anymore. That article should either be completely rewritten or removed. For example, the following tutorial provides a better concept overview:

https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/pattern-matching
