### ISSUE TITLE
Why it is faster

### ISSUE THREAD

**Issue by felipepessoto** [dotnet/docs#21155]
> "This second version is more efficient with longer sequences in scenarios where the number sought is closer to the end of the array."

It is not clear why. Better branch prediction?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6968c8f-19ab-f79f-021a-265108870371
* Version Independent ID: 6b4f1fec-b9d1-f501-1fcf-2c6f15209a29
* Content: [Ref return values and ref locals (C# Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/ref-returns)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/ref-returns.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/ref-returns.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for asking this question @felipepessoto 

The algorithm shown is a linear search. If you know the item is toward the end instead of near the start, beginning at the end will examine fewer items.

I've marked this as an up for grabs issue for community members. We'll update it when we next update this article.

**Comment by Naidile-P-N** [comment]
@BillWagner One observation assuming the array is always sorted, when no number is greater than or equal to the target, this solution wouldn't be efficient. Do we need to include it with the note ?
