### ISSUE TITLE
CA1805 goes against self-documenting code principles and actually makes code less robust.

### ISSUE THREAD

**Issue by viniciusvillas** [dotnet/docs#21181]
Hi there!

The new rule CA1805 (do not initialize unnecessarily) goes against the principle of self-documenting code. I can elaborate: when you see an assignment like `Int32 i = 0;`, you're pretty sure that the code author meant 0 to be the initial value for this variable (and he didn't just forget to initialize it). You also prevent developers less versed on C# defaults to make false assumptions, like I've heard before that the default value of `Int32` is `Int32.MinValue`.

Also, AFAICT, these default assignments are ignored by the compiler optimization on release mode anyway.

This is why I really think that this rule should be deprecated in favor of higher quality code.

Thanks! :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 035a543d-8333-1702-6a79-f7c791b84631
* Version Independent ID: c26352c7-948c-800e-5229-97c1b367ef65
* Content: [CA1805: Do not initialize unnecessarily (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1805?view=vs-2019)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1805.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca1805.md)
* Product: **dotnet**
* GitHub Login: @stephentoub
* Microsoft Alias: **stoub**

**Comment by stephentoub** [comment]
> AFAICT, these default assignments are ignored by the compiler optimization on release mode anyway.

Sometimes.  Sometimes it can't as it can't tell if doing so could change the meaning of the program.

> This is why I really think that this rule should be deprecated in favor of higher quality code.

It should be showing up by default only as a suggestion in the IDE, not as a warning or error.  Are you seeing otherwise?  Or are you suggesting it not even show up as a suggestion and be entirely off by default?

**Comment by viniciusvillas** [comment]
Hello @stephentoub! Wow, thanks for the quick answer!

Yeah, I'm seeing them as warnings (image below) by default. I didn't change that. I could, but I'm rather proud of being compliant with the vast majority of the CA rules. This is an old code, originally written in C# 3.0.

I'm just not convinced that this is a good rule in general, since:
1) It assumes that new (and seasoned) developers have knowledge about .NET conventions for every value type and
2) It may cloud the original author intentions - did she/he meant to not initialize the variable, or she/he just forgot?

Anyway, I appreciate your attention and willingness to discuss this. Thanks!

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/19936834/96877057-8ae27180-144f-11eb-9206-658584e15de3.png)

**Comment by stephentoub** [comment]
> Yeah, I'm seeing them as warnings (image below) by default. I didn't change that.

@viniciusvillas, do you have a .editorconfig or a .ruleset that your project might be using? 

@mavasani, is it possible something is causing this to manifest as a warning rather than a suggestion by default?

> I'm just not convinced that this is a good rule in general

That's a fair opinion.  It does have a perf impact in some cases, though, and from my perspective, adds unnecessary clutter and leads to inconsistencies (but that is a stylistic opinion).  Regardless, based on the feedback we've decided to move the rule by default from suggestion to hidden, so it shouldn't show up in anyone's error list by default once that change (https://github.com/dotnet/roslyn-analyzers/pull/4353) ships.  However, since it shouldn't be showing up as a warning at all, I'm guessing there's something about your project configuration that is causing it to be upgraded to a warning, in which case such a change would affect it regardless of its default level.

**Comment by mavasani** [comment]
@viniciusvillas How did you enable/acquire the analyzers?

- If you used `Microsoft.CodeAnalysis.FxCopAnalyzers`, then this is by design: That package is much more aggressive, with all CA rules being warnings by default.
- If you enabled them from [.NET 5.0 SDK](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview), then it should be an IDE suggestion by default (and hidden diagnostics once https://github.com/dotnet/roslyn-analyzers/pull/4353 ships).

**Comment by viniciusvillas** [comment]
@stephentoub, great! Thanks! 😉
@mavasani, yes, you got it: I'm probably using `Microsoft.CodeAnalysis.FxCopAnalyzers.`. Thanks for the clarification!!
