### ISSUE TITLE
Cognitive Services Custom Speech link does not work

### ISSUE THREAD

**Issue by bryanjhogan** [dotnet/docs#2118]
On the the page - https://docs.microsoft.com/en-us/azure/cognitive-services/, the link to "Get started with the Custom Speech Service API" does not work. It returns a 404.

**Comment by svick** [comment]
First, this is not the right repo to report that, that would be [Microsoft/azure-docs](https://github.com/Microsoft/azure-docs).

Second, the whole custom speech service section seems to be pretty broken, which seems to have been caused by https://github.com/Microsoft/azure-docs/commit/b149913a21ef61352aa0d8ff5a92016d30c08ec5.

I considered creating a PR to fix this, but the azure-docs repo doesn't seem to be very responsive to PRs.

**Comment by bryanjhogan** [comment]
How does one report the problem to Microsoft/azure-docs when there is no Issue link?

**Comment by BillWagner** [comment]
@bryanjhogan I will route it to the right team.

**Comment by bryanjhogan** [comment]
Thanks @BillWagner  :)

**Comment by kriscrider** [comment]
@bryanjhogan We are updating the Landing Page today and it should resolve the broken link by tomorrow morning.

**Comment by BillWagner** [comment]
@bryanjhogan Can you report back after the doc @kriscrider mentions is updated? If that fixes everything, please close this. If not, let us know what else we should address.

**Comment by bryanjhogan** [comment]
Will do. Thanks all.

**Comment by kriscrider** [comment]
I just verified that this is fixed in Master.  @bryanjhogan @BillWagner

**Comment by bryanjhogan** [comment]
@kriscrider @BillWagner @svick It is working now, thank you all.

**Comment by BillWagner** [comment]
I'll close this then.
