### ISSUE TITLE
Describe guarantee for static constructor calls

### ISSUE THREAD

**Issue by rahul-deshmukhpatil** [dotnet/docs#21383]
I think it is important when does static constructor which could only access static fields is called.

As per the below StackOverflow question its static constructor is guaranteed to be called before any other non-static constructor is called or any of the static members(method, property, field, event, indexer) is referenced anywhere.

https://stackoverflow.com/questions/20451554/whats-the-function-of-a-static-constructor-in-a-non-static-class

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f20db0d-ef5c-d8e7-2267-0f409c499e0f
* Version Independent ID: de2dac73-e810-dd42-f518-e50926b3747f
* Content: [Static Classes and Static Class Members - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/static-classes-and-static-class-members)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/static-classes-and-static-class-members.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/static-classes-and-static-class-members.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @rahul-deshmukhpatil 

Instead of adding that information to this article, we should add a link to the C# specification section on [static constructors](https://docs.microsoft.com/dotnet/csharp/language-reference/language-specification/classes#static-constructors). Let's add a link toward the end of the articel.

I've added this to our backlog, and I've added the "up for grabs" label if anyone in the community wants to submit a PR before we make this update.
