### ISSUE TITLE
Don't think the last try/catch block is ever reached

### ISSUE THREAD

**Issue by mobj-cloudly** [dotnet/docs#21492]
It seems to me that the first try/catch will return a bool either if successful or unsuccessful, and that the second (last) try/catch will never execute.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 202e3f9f-a12a-53de-9069-fd469e3dbebc
* Version Independent ID: fd3699bb-4881-b6b4-1275-43eed3d5f626
* Content: [How to verify that strings are in valid email format](https://docs.microsoft.com/en-us/dotnet/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format)
* Content Source: [docs/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello!

The only time the first try/catch returns a bool is on an exception. The other `return match.Groups[1].Value + domainName;` is inside a local function so it only applies to code that calls the function `DomainMapper` which is passed to the `Regex.Replace` call. If no exception is raised, the code exits the first try and moves on to the next.

I'm going to close this issue. If your problem is not solved, feel free to reopen or comment. Thanks!
