### ISSUE TITLE
First Example does not match to the text

### ISSUE THREAD

**Issue by mstroppel** [dotnet/docs#21553]
The first example in section "Owners, consumers, and lifetime management" does not match to the text. E.g. `Span<T>.Clear` is never used in the example but mentioned in the text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4819512e-1044-1c57-0de1-447164220fd5
* Version Independent ID: d6cf8d26-fb2f-7138-f0c7-ab529a5b9cde
* Content: [Memory&lt;T&gt; and Span&lt;T&gt; usage guidelines](https://docs.microsoft.com/en-us/dotnet/standard/memory-and-spans/memory-t-usage-guidelines)
* Content Source: [docs/standard/memory-and-spans/memory-t-usage-guidelines.md](https://github.com/dotnet/docs/blob/master/docs/standard/memory-and-spans/memory-t-usage-guidelines.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@bartonjs Should `buffer.Destroy()` in the pseudo-code example be changed to `buffer.Clear()`?

**Comment by bartonjs** [comment]
Other text doesn't match the example,  e.g. it says it has a `Memory<char>` but the sample uses a conceptual type called `Buffer`.  I think it's intentional that the sample is using concepts instead of concrete types, so perhaps it's the prose that needs to be equally generalized.

@GrabYourPitchforks was this you?

**Comment by tdykstra** [comment]
This example/text mismatch was reported earlier by #15934. This issue is a duplicate but since the other was just closed by our stale issue bot, I'll leave that one closed and this one open.

**Comment by tdykstra** [comment]
ping @GrabYourPitchforks

**Comment by GrabYourPitchforks** [comment]
The example was largely copied from https://gist.github.com/GrabYourPitchforks/4c3e1935fd4d9fa2831dbfcab35dffc6, but that was meant to describe more general concepts and wasn't really talking about `Span<T>` or `Memory<T>` as a technology. In fact, the original draft includes this text directly above the buffer sample:

> Let's stick a pin in `Memory<T>` for now and speak about buffers in more general terms.

And aside from that one fragment, the rest of the section text doesn't mention `Span<T>` or `Memory<T>` _at all_.

If we wanted to keep this section generalized as in the original draft, we should remove references to things like `Span<T>.Clear`, which aren't relevant to the sample code. Or, if we wanted to make this section specific to `Span<T>` or `Memory<T>`, we need to reconsider the sample. You can't "rent" spans (since they're abstractions). And I think this part of the article might be too early to introduce dangerous concepts like `ArrayPool<T>`.
