### ISSUE TITLE
Snippet indentation touch-ups

### ISSUE THREAD

**Issue by guardrex** [dotnet/docs#2156]
The csharp snippets need a smidgen of work with broken indentation.

@tompratt-AQ Will this conflict with anything you've been doing?

**Comment by tompratt-AQ** [comment]
Glad you are tackling this Luke! I've seen some of the issues that you mention here during my recent work with the snippets, and I fixed a few of them where I could - but I'm sure there will be plenty left over. That said, I don't think we will directly conflict. Especially, after my PRs 2128, 2131, and 2138 are merged. All 3 of these PRs are about addressing the correct snippets from the topics, so I only touched  snippet files to fix snippet tags when they were mismatched or otherwise broken.

**Comment by GuardRex** [comment]
Ok, cool. I didn't want to dup any work you were doing or land us into a patch of PR conflicts. What I did didn't take long; so if we need to close this and address later, we certainly can do that.

**Comment by mairaw** [comment]
is this still blocked @GuardRex?

**Comment by GuardRex** [comment]
@mairaw I held off on further work ... see https://github.com/dotnet/docs/pull/2153#issuecomment-301626945

**Comment by GuardRex** [comment]
@mairaw This one pertaining to indentation in snippets won't make the cut for 7/31. Do u want to re-assign?

**Comment by BillWagner** [comment]
closed due to lack of action.
