### ISSUE TITLE
A constructor can invoke another constructor in the same object by using the this keyword.

### ISSUE THREAD

**Issue by miyazakizachary** [dotnet/docs#21582]
I do not understand on this as:

`public Employee(int weeklySalary, int numberOfWeeks)
    : this(weeklySalary * numberOfWeeks)
{
}`

will call another constructor

`public Employee(int annualSalary)
{
    Salary = annualSalary;
}`

I could see that the first constructor calling does not pass anything on `int annualSalary` parameter to the second constructor (another constructor). Is this possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 374a58d4-1905-c664-04b6-fd68e617f8c9
* Version Independent ID: 36d0bf3a-29bf-5162-c700-142b03f9a16c
* Content: [Using Constructors - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/using-constructors)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/using-constructors.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/using-constructors.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hey @miyazakizachary 

The article is correct. Using the `this` keyword following the `:` in a constructor declaration is how you call a different constructor in the same class. You can use either `: base(...)` or `: this(...)` to call a specific constructor in the base class or the same class to minimize duplicated code. In the example you cite, the constructor that take two parameters doesn't need to repeat any logic because it calls a different constructor which does all the computation.

I'll close this as answered.

**Comment by miyazakizachary** [comment]
Thanks for the answer. I didn't realize that I missed the equivalence:

`this(weeklySalary * numberOfWeeks) { }` is the same as `public Employee(int annualSalary) {...}`
