### ISSUE TITLE
Clean Code Violation in Code Snippet

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#21607]
---
**Issue moved from dotnet/docs.de-de#204**
- Please respond to @Bruellhusten.

---

_From @Bruellhusten on Friday, August 7, 2020 4:20:02 PM_

Dears, 

```
    public void AddOrderItem(int productId, string productName,
                            decimal unitPrice, decimal discount,
                            string pictureUrl, int units = 1)
    {
        //...
        // Domain rules/logic for adding the OrderItem to the order
        // ...

        var orderItem = new OrderItem(productId, productName, unitPrice, discount, pictureUrl, units);

        _orderItems.Add(orderItem);

    }
```

this code example is a direct violation of Clean Code. I see the benefit of the Application layer not needing to know how to create an OrderItem, but solving this by giving each property of OrderItem in one by one is an anti-pattern. In this example it may still be not too "smelly", but what if OrderItem is a bigger object? Would you pass 30 properties one by one as parameters into that method?
Intuitively I would either write the method as
`AddOrderItem(OrderItem orderItem)`
if there is no domain rules for adding these, 
OR use a class
`AddOrderItem(AddOrderItemCommand command)`

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 49c9fdb0-f078-2030-204d-67d016b22c8d
* Version Independent ID: 43bd7af4-f92e-f866-6725-b3c1b4e6afdb
* Content: [Implementieren eines Microservicedomänenmodells mit .NET Core](https://docs.microsoft.com/de-de/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/net-core-microservice-domain-model)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/net-core-microservice-domain-model.md](https://github.com/dotnet/docs.de-de/blob/live/docs/architecture/microservices/microservice-ddd-cqrs-patterns/net-core-microservice-domain-model.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @Bruellhusten, thank you for reaching out. 

If you refer the following code snippet in the reference application `eShopOnContainers`

[Order.cs](https://github.com/dotnet-architecture/eShopOnContainers/blob/07d36e3188f8e22d5d8d3010b5e1b23472fb5df6/src/Services/Ordering/Ordering.Domain/AggregatesModel/OrderAggregate/Order.cs#L75
)

```csharp

public void AddOrderItem(int productId, string productName, decimal unitPrice, decimal discount, string pictureUrl, int units = 1)
        {
            var existingOrderForProduct = _orderItems.Where(o => o.ProductId == productId)
                .SingleOrDefault();

            if (existingOrderForProduct != null)
            {
                //if previous line exist modify it with higher discount  and units..

                if (discount > existingOrderForProduct.GetCurrentDiscount())
                {
                    existingOrderForProduct.SetNewDiscount(discount);
                }

                existingOrderForProduct.AddUnits(units);
            }
            else
            {
                //add validated new order item

                var orderItem = new OrderItem(productId, productName, unitPrice, discount, pictureUrl, units);
                _orderItems.Add(orderItem);
            }
        }

```

You would notice `OrderItem` new object creation logic is embedded within the method `AddOrderItem()`. That's the reason, this method accepts multiple properties instead of `OrderItem object itself. This has also been described in [Encapsulate data in the Domain Entities](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/net-core-microservice-domain-model#encapsulate-data-in-the-domain-entities) section in the following manner :

*In this snippet, most of the validations or logic related to the creation of an OrderItem object will be under the control of the Order aggregate root—in the AddOrderItem method—especially validations and logic related to other elements in the aggregate. For instance, you might get the same product item as the result of multiple calls to AddOrderItem. In that method, you could examine the product items and consolidate the same product items into a single OrderItem object with several units. Additionally, if there are different discount amounts but the product ID is the same, you would likely apply the higher discount. This principle applies to any other domain logic for the OrderItem object*

Hope this helps !

**Comment by Bruellhusten** [comment]
Hi Sumit Ghosh, 

 

I had a few free minutes and thought I’d show what I mean in a pull request. 

https://github.com/dotnet-architecture/eShopOnContainers/pull/1523

 

Best Regards

Justus 

 

Von: Sumit Ghosh <notifications@github.com> 
Gesendet: Mittwoch, 18. November 2020 07:26
An: dotnet/docs <docs@noreply.github.com>
Cc: Justus Timmerer <justus@timmerer.de>; Mention <mention@noreply.github.com>
Betreff: Re: [dotnet/docs] Clean Code Violation in Code Snippet (#21607)

 

Hi  <https://github.com/Bruellhusten> @Bruellhusten, thank you for reaching out.

If you refer the following code snippet in the reference application eShopOnContainers

 <https://github.com/dotnet-architecture/eShopOnContainers/blob/07d36e3188f8e22d5d8d3010b5e1b23472fb5df6/src/Services/Ordering/Ordering.Domain/AggregatesModel/OrderAggregate/Order.cs#L75> Order.cs

public void AddOrderItem(int productId, string productName, decimal unitPrice, decimal discount, string pictureUrl, int units = 1)
 
        {
 
            var existingOrderForProduct = _orderItems.Where(o => o.ProductId == productId)
 
                .SingleOrDefault();
 
 
 
            if (existingOrderForProduct != null)
 
            {
 
                //if previous line exist modify it with higher discount  and units..
 
 
 
                if (discount > existingOrderForProduct.GetCurrentDiscount())
 
                {
 
                    existingOrderForProduct.SetNewDiscount(discount);
 
                }
 
 
 
                existingOrderForProduct.AddUnits(units);
 
            }
 
            else
 
            {
 
                //add validated new order item
 
 
 
                var orderItem = new OrderItem(productId, productName, unitPrice, discount, pictureUrl, units);
 
                _orderItems.Add(orderItem);
 
            }
 
        }
 

You would notice OrderItem new object creation logic is embedded within the method AddOrderItem(). That's the reason, this method accepts multiple properties instead of `OrderItem object itself. This has also been described in  <https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/net-core-microservice-domain-model#encapsulate-data-in-the-domain-entities> Encapsulate data in the Domain Entities section in the following manner :

In this snippet, most of the validations or logic related to the creation of an OrderItem object will be under the control of the Order aggregate root—in the AddOrderItem method—especially validations and logic related to other elements in the aggregate. For instance, you might get the same product item as the result of multiple calls to AddOrderItem. In that method, you could examine the product items and consolidate the same product items into a single OrderItem object with several units. Additionally, if there are different discount amounts but the product ID is the same, you would likely apply the higher discount. This principle applies to any other domain logic for the OrderItem object

Hope this helps !

**Comment by sughosneo** [comment]
Hi @Bruellhusten , thank you for providing more details and submitting the PR. 
Will review and update the PR.

**Comment by sughosneo** [comment]
Hi @Bruellhusten, We have closed this PR https://github.com/dotnet-architecture/eShopOnContainers/pull/1523 as it was stale for sometime now. Please note, the `dev` branch of [eShopOnContainers](https://github.com/dotnet-architecture/eShopOnContainers) is now updated to `.NET 5`. So if you could take the latest from the `dev` branch and submit a new PR with suggested changes. We will be happy to review and merge the changes. Thank you.
