### ISSUE TITLE
Missing example of how to connect to other apis

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#21608]
---
**Issue moved from dotnet/docs.de-de#205**
- Please respond to @AndiRudi.

---

_From @AndiRudi on Thursday, August 13, 2020 6:51:12 AM_

I think one example is missing here. At least I couldnt find that. 

Let's assume you already have a microservice infrastructure with several services and authentication with identity server. Now you want to integrate with external services. That means you will create a page for integrations where users can select several other systems to integrate with. Usually there will be a button like "intergrate with x" and then you are redirected to x to login and get an access token and refresh token. From then on the integration is active and our service can use the tokens to access the external system. 

Questions around this case are:
- How do you do that? Is it possible with the asp.net identity only or is identity server needed?
- Where do you store the tokens? Do you need to go through identity server or is this implemented in another service?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: d926868f-5446-63c6-75c0-ba879879f4b5
* Version Independent ID: ff9b78ce-a923-e763-08d5-c31cbb6a1f0e
* Content: [Sichern von .NET-Microservices und Webanwendungen](https://docs.microsoft.com/de-de/dotnet/architecture/microservices/secure-net-microservices-web-applications/)
* Content Source: [docs/architecture/microservices/secure-net-microservices-web-applications/index.md](https://github.com/dotnet/docs.de-de/blob/live/docs/architecture/microservices/secure-net-microservices-web-applications/index.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @mjrousos
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @AndiRudi, thank you for reaching out. 

I am not sure that I have understood your question completely. But still, I will give it a try to answer. 

In a microservices architecture, all microservices relies on an independent Identity provider to manage secure communication among different microservices.  Identity provider validates a registered client and helps it by providing a token to the requested client for passing it to the subsequent communications to other microservices.

For e.g : If one microservices request for a token by using any specific auth flow, Identity Server will verify that registered client and based on that it will give back the token. And that token can be used to call other microservices securely.

Now if you have an external system that needs to be integrated with your microservices architecture. That has to be registered with your Identity Server. So that whenever your microservice tries to talk to the external service
it should be able to pass the token which can be validated at the external service end. But in case if your external service has it's own set of Identity mechanism implemented already in that case caller microservice needs to talk to that separate Identity provider to fetch the right token to share with external service.

In either of the scenarios, you don't need to manage the token. Caller service needs to fetch the token from the respective Identity provider.

Hope this helps !

**Comment by AndiRudi** [comment]
Not completely. I understand where you're going, but it's still hard for me to bring this down to code. If you know any resource that describes the topic, I would appreciate if you share it. I couldn't find documentation about integration topics. Maybe a little more context would help.

Let's say we have two products that we want to connect. Product 1 is our SAAS application. Product 2 is Zoom. We want to build the feature to integrate with Zoom. For the sake of simplicity let's say that both products/companies have Keycloak as their Authentication Platform. 

Now we want to build the feature to activate an Integration. The user clicks on 'Integrate with Zoom' and is redirected to their Keycloak to authenticate. Upon Authentication the user is redirected to use with a code and we can now access refresh and access tokens. 

My question is, where are these tokens stored on our side? 

Idea 1: In our product there is one service that needs to talk to the zoom endpoints in the background all the time. So this service has to have the access token and eventually refresh them?

Idea 2: The two keycloaks of each company have to handle the authentication and our service?

Maybe you can clarify more?

**Comment by sughosneo** [comment]
Hi @AndiRudi, thank you for sharing more details.

I would look into your scenario as per below :

- In case if a user is not logged in to `Product 1`(SaaS application) and clicks on the button "Integrate with Zoom" in `Product 1`, a user will get redirected to the `Identity Provider`(`Keycloak` platform). 
- User will provide a valid credential and get authenticated.
- User will get redirected back to the `Product 1` (SaaS application) after acquiring the respective token.
- Where user will store the token in it's Cookie (Web MVC) or SessionStorage (SPA) based on the application type of `Product 1`.
- Then the user will further get redirected to the `product 2`(Zoom) API where in the authorization header it will pass on the access token.

Similar functionality has been implemented in [eShopOnContainers](https://github.com/dotnet-architecture/eShopOnContainers) reference application as well. Instead of the "Integration" button you need to "login" to the portal to access different functionality. For your specific scenario, the `Authentication flows` and `redirection logic` may be different.

>!Note : In this particular scenario, not sure why exactly one backend API needs to keep talking to the `Product 2`(Zoom) always but that can also be addressed by the `OAuth 2.0 client credentials flow`

For e.g : If you are using the `Microsoft identity platform` endpoint for `identity-as-a-service` you may want to refer below links for more details. Please note these are standard implementation of `oAuth2` authorization flow or `OpenID Connect` authentication flow. So you could take similar approaches for any other identity providers.

[OAuth 2.0 and OpenID Connect protocols on Microsoft identity platform](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols)

**Comment by AndiRudi** [comment]
Thanks for the update. I understand the flow you described, but my core question is exactly related to this line

> !Note : In this particular scenario, not sure why exactly one backend API needs to keep talking to the Product 2(Zoom) always but that can also be addressed by the OAuth 2.0 client credentials flow

In this application we don't want to store the token on the user. Instead we want to store it on a service. The reason for this is, that the service will create Zoom meetings automatically in the background. So in a periodic job the SAAS application is creating Zoom meetings. Therefore the service has to be able to access the Zoom API with a an access token (and eventually refresh it with refresh token when outdated). This is why I have currently stored the tokens in that service and put all the logic to refresh it there as well. This seems wrong, but I don't know how to do better.

**Comment by sughosneo** [comment]
Hi @AndiRudi, thanks for the update.

You don't need to store the token on the client/user side. You could use [OAuth 2.0 client credentials flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow) to configure a service to talk to another service on demand without any user intervention.

**Comment by sughosneo** [comment]
Hi @AndiRudi , considering the original issue has been answered. I am closing this issue as of now. Please feel free to reopen it if you have any further questions. 

Thank you.
