### ISSUE TITLE
Move include files from internal folders to the master\includes folder.

### ISSUE THREAD

**Issue by tompratt-AQ** [dotnet/docs#2179]
We need to remove include files from internal (primarily in C# and VB) and move them all here: https://github.com/dotnet/docs/tree/master/includes
 
If the file already exist in the main includes folder, we will keep the original file and delete the other instead of moving it.

If a file is moved, we will do the following:

1. Remove the metadata inside that looks like this:

translation.priority.ht: 
  - "cs-cz"
  - "de-de"
  - "es-es"
  - "fr-fr"
  - "it-it"
  - "ja-jp"
  - "ko-kr"
  - "pl-pl"
  - "pt-br"
  - "ru-ru"
  - "tr-tr"
  - "zh-cn"
  - "zh-tw"

2.  Fix all links to the file, using the format ~/includes/tokenname.md
 
Suggest reviewers
@mairaw

**Comment by tompratt-AQ** [comment]
@mairaw Could you comment on these two particular cases:
1. docs/csharp/language-reference/compiler-messages/includes/note_settings_general_md.md 
I propose that we move this one and keep it instead of the older one:  docs/includes/note_settings_general_md.md
The newer one has a link to a topic instead of to MSDN and the older one has an extra space typo in the link text.
2. docs/csharp/language-reference/compiler-options/includes/csharp_current_short_md.md
Should this file be moved? It seems like a dupe of docs/includes/csprcs-md.md

**Comment by mairaw** [comment]
1. Yes, you can replace the contents of docs/includes/note-settings-general-md.md with what was in the other note since i've update its contents after migration
2. I think so. we probably have more duplicates and i think the other name is friendlier.

I've also noticed that the second round of migrations also fixed the separator from _ (underscore) to -(dashes). I think it would be good to be consistent on that as well.
