### ISSUE TITLE
IAsyncDisposable Example with finalizer

### ISSUE THREAD

**Issue by MatthewLymer** [dotnet/docs#21858]
Since the `Dispose(bool isDisposing)` pattern is meant for cases where the class or subclasses may deal with unmanaged resources it would be good to have an example that shows that use-case.

A good example may also be in HTTP/2 where disposing of a stream may require sending a `RST_FRAME` frame on dispose, should this be invoked on the finalizer?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61a961dc-3ebf-2a96-a6eb-2e0b62ab909f
* Version Independent ID: d72276e1-9059-815f-dc14-a03a7544ab87
* Content: [Implement a DisposeAsync method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync)
* Content Source: [docs/standard/garbage-collection/implementing-disposeasync.md](https://github.com/dotnet/docs/blob/master/docs/standard/garbage-collection/implementing-disposeasync.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @MatthewLymer 
Thank you so much for posting this issue. We really appreciate it.

> Since the `Dispose(bool isDisposing)` pattern is meant for cases where the class or subclasses may deal with unmanaged resources it would be good to have an example that shows that use-case.

The code examples in the doc are intentionally generic to exemplify the pattern only.  Since the runtime itself is open-source and built atop .NET, this doc could probably be improved by adding links to some of these use-cases in the actually source itself.

> A good example may also be in HTTP/2 where disposing of a stream may require sending a `RST_FRAME` frame on dispose, should this be invoked on the finalizer?

I'm not sure that's a docs question, it sounds more like an implementation question. Again, I think we could add links to existing implementations as a point of reference, but this doc is really conceptional. Here is a finding from within the runtime OSS project that have implementations of both:

- [Utf8JsonWriter - Dispose / DisposeAsync](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Text.Json/src/System/Text/Json/Writer/Utf8JsonWriter.cs#L297-L345)

Also, here are the `HttpClient` and `HttMessageInvoker` impls:

- [HttpClient](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs#L655-L669)
- [HttpMessageInvoker](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Http/src/System/Net/Http/HttpMessageInvoker.cs#L115-L132)
