### ISSUE TITLE
Update framework/deployment topics for 4.7

### ISSUE THREAD

**Issue by GuardRex** [dotnet/docs#2196]

**Comment by rpetrusha** [comment]
@Guardrex, can you specify what you have in mind here? Though I may have missed something, I think that I updated the deployment topics.

**Comment by GuardRex** [comment]
@rpetrusha https://github.com/dotnet/docs/pull/1979#pullrequestreview-38860878

I mentioned this issue over there, so I thought it would cross-ref over here. GitHub has failed me this morning. :cry: Apparently, it just needs the link placed into the body of the comment.

**Comment by rpetrusha** [comment]
@GuardRex, sorry about that.  I didn't realize there this was related to an existing PR.

**Comment by mairaw** [comment]
The reason why I asked @GuardRex to create this issue is that the new installation topics that @richlander created don't talk about .NET 4.7, which is our most recent release. 

Also, some of the links seem to take you to the wrong page. e.g. https://go.microsoft.com/fwlink/?linkid=845529&source=dotnetdocs
