### ISSUE TITLE
New features and official documentation?

### ISSUE THREAD

**Issue by theundergroundsorcerer** [dotnet/docs#22115]
Is there a chance that the new features become "first-class citizens" in the official documentation and not merely "proposals"? A normal entry in the docs without "future considerations" left to language designers would be really nice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a60b6e17-36cf-bd6c-1b76-d38f1760a816
* Version Independent ID: 0fdeaa81-c3c2-c290-224e-792fcee9b297
* Content: [C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/)
* Content Source: [docs/csharp/language-reference/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
Are you talking about the specification or the documentation? If it's about the specification (because the proposals serve as temporary replacements for that), then it's being slowly updated and I believe the most recent work on that is here: https://github.com/dotnet-foundation/projects/issues/90. If it's about the documentation, which features specifically are you talking about?

**Comment by theundergroundsorcerer** [comment]
I mean documentation, but call it specification if you want. While one can read blog posts, try to make sense of language proposals or just go stack overflow, it is a bad substitute for official documentation. 

A simple example? Pattern matching - there is an entry in the docs (C# concepts) written in 2019 that covers it. However, there are many enhancements that came with c# 9. I believe that when someone looks for "C# pattern matching" - the end result should be a single page (or few linked pages) in the official documentation that describes it. Instead, one needs to look at few unrelated pages in the docs and several blog posts to see how the features looks in its current state. 

Or function pointers - one reading documentation, mostly wants a complete, accurate and up to date description of the construct, with some examples, use cases, etc. Language design issues are not relevant in this context. Seriously, when reading [function pointers](url=https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/function-pointers) page in the docs (I think it is the only one), it is hard to figure out how the current implementation state looks like, without looking for outer references.

No offense, but recent versions of C# are "implementation defined". There should be an accurate, complete and up to date entry in the official documentation that describes the new language features as they are in their current state. Sadly, they do not exist.

**Comment by BillWagner** [comment]
Thanks for all the details @theundergroundsorcerer 

We are working on this in a few different ways.  

(As @svick mentions), the ECMA committee is working to update the official standard from V5.0 to the present. We will be opening a public repo for that soon, and that will provide the definitive source for the language definition. (I'm on that committee as well as being responsible for the docs here).

Related, we're working to streamline and update the **Language Reference** section of the C# Guide. Historically, it contained a lot of duplicated text from the standard. That made it more academic than desired, and increased the amount of work to keep it up to date. 

We agree that publishing the proposals is a poor substitute, and we're working to address that.

I'd like to close this. Not because we aren't addressing it, but because it is an epic that encompasses several tasks. Project [#71](https://github.com/dotnet/docs/projects/71) has the current list of tasks. I'll continue updating it as we identify more features where there are gaps. Let me know if you agree. When the standard work goes public, we'll have similar projects for each feature added to the language since version 6.
