### ISSUE TITLE
Can't serializ the '\u3000' when using with UnicodeRanges.All

### ISSUE THREAD

**Issue by moyanming** [dotnet/docs#22147]
The '\u3000' seems can't be serialized when using with UnicodeRanges.All.
BTW, I have tested the [UnicodeRanges.CjkSymbolsandPunctuation](https://docs.microsoft.com/en-us/dotnet/api/system.text.unicode.unicoderanges.cjksymbolsandpunctuation?view=net-5.0) and the '\u3000' can't be serialized too.
![QQ截图20201224162108](https://user-images.githubusercontent.com/13234209/103074165-086b5f00-4604-11eb-9ff7-dfa1131787df.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbfcc376-0c18-5aab-f6b8-b2c6ef282acc
* Version Independent ID: 79bcd93d-81f8-5f02-3958-d364606265cd
* Content: [How to customize character encoding with System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-character-encoding)
* Content Source: [docs/standard/serialization/system-text-json-character-encoding.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/system-text-json-character-encoding.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
cc @GrabYourPitchforks

**Comment by GrabYourPitchforks** [comment]
__U+3000 IDEOGRAPHIC SPACE__ is always blocked because it is a member of [the _Space\_Separator \[Zs\]_ category](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=[:General_Category=Space_Separator:]). The only member of this category which is allowed is __U+0020 SPACE__. See [here](https://github.com/dotnet/runtime/blob/8f9edb350d71d7ec962d2add72747fd35d7fdb21/src/libraries/System.Text.Encodings.Web/tools/GenDefinedCharList/Program.cs#L157) and [here](https://github.com/dotnet/runtime/blob/8f9edb350d71d7ec962d2add72747fd35d7fdb21/src/libraries/System.Text.Encodings.Web/tools/GenDefinedCharList/Program.cs#L175) for the details of our implementation. Members of this category are always prohibited regardless of which Unicode ranges are included in the allow-list because of their potential to cause problems or errors in consuming applications.

If the currently behavior is overly restrictive we can consider relaxing it a bit. What is the problem being caused in your application?

**Comment by moyanming** [comment]
> **U+3000 IDEOGRAPHIC SPACE** is always blocked because it is a member of [the _Space_Separator [Zs]_ category](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B:General_Category=Space_Separator:%5D). The only member of this category which is allowed is **U+0020 SPACE**. See [here](https://github.com/dotnet/runtime/blob/8f9edb350d71d7ec962d2add72747fd35d7fdb21/src/libraries/System.Text.Encodings.Web/tools/GenDefinedCharList/Program.cs#L157) and [here](https://github.com/dotnet/runtime/blob/8f9edb350d71d7ec962d2add72747fd35d7fdb21/src/libraries/System.Text.Encodings.Web/tools/GenDefinedCharList/Program.cs#L175) for the details of our implementation. Members of this category are always prohibited regardless of which Unicode ranges are included in the allow-list because of their potential to cause problems or errors in consuming applications.
> 
> If the currently behavior is overly restrictive we can consider relaxing it a bit. What is the problem being caused in your application?

Hi @GrabYourPitchforks , thank you for the reply.
A good document of this exception is fine for me now. But it is good if there is an enum-flag that can be used to explicit this behavior.
