### ISSUE TITLE
I'm wondering if it's possible to implement a custom algorithm using ml.net

### ISSUE THREAD

**Issue by Dedigraz** [dotnet/docs#22195]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d25e646e-45cc-2edf-4ba0-9440b80a50a5
* Version Independent ID: fa1051ca-bf71-f12d-1f6c-f43220d460cb
* Content: [How to choose an ML.NET algorithm - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-choose-an-ml-net-algorithm)
* Content Source: [docs/machine-learning/how-to-choose-an-ml-net-algorithm.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-choose-an-ml-net-algorithm.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment]
Hi @Dedigraz 

Thanks for your question. It is possible to write your own algorithm. The code is available on GitHub https://github.com/dotnet/machinelearning where you can make pull requests against the repo. Since this is more of a product question, in the future, it's advised to open issues in the [dotnet/machinelearning](https://github.com/dotnet/machinelearning/issues) repo. 

Closing this issue for now since no immediate action is required on Microsoft Docs. If you have any documentation related issues, please feel free to open another issue.
