### ISSUE TITLE
Why the container hold reference to Transient services? Better not reference it.

### ISSUE THREAD

**Issue by RyanLiu99** [dotnet/docs#22393]
On this page, it states: "When you register Transient services that implement IDisposable, by default the DI container will hold onto these references, "

Since it is transient, it is created each time upon request anyway, why container need hold a reference to it?

Isn't better not to hold reference if it is transient, and let GC collect it automatically just like GC deals with any local objects that no longer in use? Isn't that mush simpler and safer? I think other container like Autofac does that.

Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d1c8ef1-6a01-df24-34ad-570f88df9303
* Version Independent ID: 7fb2be80-cb54-27bf-4f93-423d8540429e
* Content: [Dependency injection guidelines](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-guidelines)
* Content Source: [docs/core/extensions/dependency-injection-guidelines.md](https://github.com/dotnet/docs/blob/master/docs/core/extensions/dependency-injection-guidelines.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by davidfowl** [comment]
The GC doesn't automatically call dispose on your resources.

**Comment by IEvangelist** [comment]
Hi 👋 @RyanLiu99
Thank you so much for posting this issue. We really appreciate it.

This sounds like a product question, rather than one for the docs team. I have updated the label as such. This is an implementation detail, I'm not certain as to why it is implemented this way. You might want to ask this question in the runtime repo, scoped to [Microsoft.Extensions.DependencyInjection](https://github.com/dotnet/runtime/tree/master/src/libraries/Microsoft.Extensions.DependencyInjection). I can close this if you're okay with that, just let me know.

**Comment by RyanLiu99** [comment]
Hi IEvangelist,  ok, I will ask the same question in the runtime repo as you suggested. You may close this one. Thanks!
