### ISSUE TITLE
Please elaborate on decimal and Guid types passed as `in` arguments

### ISSUE THREAD

**Issue by Slaviusz** [dotnet/docs#22426]
_This practice often improves performance for readonly value types that are larger than IntPtr.Size. For simple types (sbyte, byte, short, ushort, int, uint, long, ulong, char, float, double, decimal and bool, and enum types), any potential performance gains are minimal. In fact, performance may degrade by using pass-by-reference for types smaller than IntPtr.Size._

`sizeof(decimal) == 16` which is double the `IntPtr.Size` on all 64bit platforms. Can you explain why is it listed having no to minimal performance gain?
On the contrary, also `sizeof(Guid) == 16` but `Guid` is not in the list. Does the same apply?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac8804c7-6acd-ab2a-4e14-0b99265969a5
* Version Independent ID: 183efcbd-a781-d303-f9cd-1c22da1676de
* Content: [Write safe and efficient C# code](https://docs.microsoft.com/en-us/dotnet/csharp/write-safe-efficient-code)
* Content Source: [docs/csharp/write-safe-efficient-code.md](https://github.com/dotnet/docs/blob/master/docs/csharp/write-safe-efficient-code.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @Slaviusz 

The list of simple types doesn't include `Guid` because it's not named in the C# language spec. It is an unmanaged type of similar size, but it's not mentioned as such in the C# language spec. 

In general, any low-level optimizations like this should be measured before making changes. I doubt that 16 bytes would make much of a difference unless it's in a method that's in a time critical hot path for your application.

I'll keep this open because I do want to make other changes to this article, and I'll address this at that time.
