### ISSUE TITLE
I feel the code is too long, the doc is too long to read.

### ISSUE THREAD

**Issue by PingPongSet** [dotnet/docs#22471]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17f03524-58d6-870c-e43f-e7f9565608e5
* Version Independent ID: da634f1c-bb77-efb5-0066-c3760b79fa4c
* Content: [Generate and consume async streams](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/generate-consume-asynchronous-stream)
* Content Source: [docs/csharp/tutorials/generate-consume-asynchronous-stream.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/generate-consume-asynchronous-stream.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for making this comment @PingPongSet I do have a few questions.

Many readers have responded positively to this tutorial because it does provide a real-world use for asnyc enumerables. That said, I'd like to learn more about what information you wanted. What did you hope to see from this article? If we already have it in place, I'll link to it from this tutorial. If not, we'll add a new article for this purpose.
