### ISSUE TITLE
How is the newline handled for file_header_template

### ISSUE THREAD

**Issue by valleyjo** [dotnet/docs#22519]
In the example a `\n` escape sequence is used. However, the example renders the header template on a single line. I see another example where the newline escape sequence will separate the header into different lines. Is the example here incorrect?

Other Example: https://docs.microsoft.com/en-us/visualstudio/ide/reference/add-file-header?view=vs-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48f32ca7-f4b4-0c5b-2c83-333fc8bb1d26
* Version Independent ID: 8f026f50-9ebf-3d7e-76e8-7abcf992a1aa
* Content: [IDE0073: Require file header - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0073)
* Content Source: [docs/fundamentals/code-analysis/style-rules/ide0073.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/style-rules/ide0073.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by adegeo** [comment]
Thank you for opening this issue. I believe you're correct in assuming the Visual Studio documentation is more accurate. This should be fixed in the example.

If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!

**Comment by sharwell** [comment]
The editor will apply the appropriate newline from the file when replacing `\n` or `\r\n` sequences found in the `file_header_template`. For this reason, it's simplest to just use `\n` when writing the template.
