### ISSUE TITLE
F# code formatting guidelines: Space before DU constructor arguments?

### ISSUE THREAD

**Issue by cmeeren** [dotnet/docs#22664]
In the [F# code formatting guidelines](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting), I can find no descriptions of whether DU cases should have a space before a parenthesized argument:

```f#
let opt1 = Some ()
let opt2 = Some (1, 2)
```

or:

```f#
let opt1 = Some()
let opt2 = Some(1, 2)
```

Could this be clarified and added? I can add a PR, but let's find out what it should be first.

**Comment by cartermp** [comment]
I think it's somewhat finnicky, since it's not a function application nor is it a method call.

Let's have it be a space:

```fsharp
let opt1 = Some ()
let opt2 = Some (1, 2)
```

This is the most common style used in the F# compiler source code and several codebases I've interacted with, so that's as canonical as it gets, I suppose.

Will happily accept a PR that adds this.
