### ISSUE TITLE
Out Parameter 

### ISSUE THREAD

**Issue by Alfi360** [dotnet/docs#22709]
Is this really correct ?
_Variables passed as out arguments do not have to be initialized before being passed in a method call. However, the called method is required to assign a value **before the method returns.**_

Shouldn't it be  : **Before its used** ?
look at the example below which satisfy the condition that the parameter is assigned before the method return, but its still gives the error that the out parameter need to be assigned. 
` static int Double(out int a)
        {
            a *= 2 ;
            a = 2;
            return a;
        }`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f6c8480-77a7-7505-5224-0efe15b9b755
* Version Independent ID: 993250d1-108c-ab1a-886e-ca1bfa9104c7
* Content: [out parameter modifier - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/out-parameter-modifier)
* Content Source: [docs/csharp/language-reference/keywords/out-parameter-modifier.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/out-parameter-modifier.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for bringing this to our attention @Alfi360 

I'm going to close this, because it is correct. The key point for that sentence is that an `out` argument *must* be assigned by the called method. Any variable must be assigned before it is accessed (read). It is because the calling method is not required to assign a value to an `out` argument that you see the warning you describe above. (Try it yourself: change the `out` above to `ref`, and the code compiles. That's because `a` must be assigned a value before it is passed to the `Double` method.

**Comment by Alfiqar** [comment]
Thank you Bill,

but isn’t out like a pointer, pointing to the variable being passed, which can be initialised. 

So let’s say I have :

`Int x = 2;
Double(out x);
`
In this case we are pointing to a place in memory that has the value of 2. If this is the case, why does it need to be assigned ?

**Comment by svick** [comment]
@Alfiqar Because each method is independent. When you look at a method, its behavior is completely specified by what you see there, it doesn't matter how it's called.

This means that if you say that a method has an `out` parameter, then the method can't read the parameter before assigning it. If you want to be able to read the original value, you should use a `ref` parameter instead, but then you're forcing every caller to set an initial value.
