### ISSUE TITLE
A solution folder whose name starts with a period ('.') will also trigger this error.

### ISSUE THREAD

**Issue by pshaffer** [dotnet/docs#22899]
I have found that when I add a solution folder to my solution where the name starts with a period (in an attempt to make it sort out as the topmost folder) it also triggers this problem, which wasn't in the list of possible causes.  Removing the leading period from the folder name clears up the problem.  Please add this to the list of possible causes in the page.  Even better, have them fix the problem in Visual Studio 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62af3ec3-7d59-7b4a-b9a1-413b8956bab7
* Version Independent ID: 31e0311a-8823-1d30-8f38-ac0c37ca07d9
* Content: [NETSDK1004: Assets file not found - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1004?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(NETSDK1004)%26rd%3Dtrue)
* Content Source: [docs/core/tools/sdk-errors/netsdk1004.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/sdk-errors/netsdk1004.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for reporting that.  I'll add that to the list of possible causes, or you're welcome to submit a PR to add it if you prefer.

**Comment by Youssef1313** [comment]
@tdykstra Is it possible this is a product bug? Could you please confirm with the product team if this is the expected behavior?

**Comment by tdykstra** [comment]
@TerryGLee  Can you help with this question (regarding allowable naming patterns for solution folders)?

**Comment by tdykstra** [comment]
[Response from Terry:]
It looks like this is product-specific feedback that should be brought to the attention to the engineering team. The venue in which we ask customers to do this is by using the [**Report a Problem**](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool. 

Otherwise, the documentation we have on solution files can be found via this search string from our Visual Studio IDE documentation: https://docs.microsoft.com/en-us/search/?scope=VS%20IDE&view=vs-2019&terms=solution%20file

As well, here are other resources you might consider using:

- [Visual Studio on Q&A](https://docs.microsoft.com/en-us/answers/products/vs) 
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)
