### ISSUE TITLE
Missing the application of the code examples

### ISSUE THREAD

**Issue by MarcSchillemans** [dotnet/docs#22922]
The code examples are simple enough to follow, but to see how these samples wil look like when they are used in code, would give the information needed to actually see how it works and how it will look like in practice

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 874ea00d-6ec4-55f4-f0e3-e818d21454c7
* Version Independent ID: 98072328-af31-5bc6-9ba4-1353328d5f10
* Content: [Expression-bodied members - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/expression-bodied-members)
* Content Source: [docs/csharp/programming-guide/statements-expressions-operators/expression-bodied-members.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/statements-expressions-operators/expression-bodied-members.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for raising that issue @MarcSchillemans 

Most of our tutorials have been updated since expressions bodied members were added to the language. Any of these [tutorials](https://docs.microsoft.com/dotnet/csharp/tutorials/) will show examples of expression bodied members in practie.

I'll close this as an answered question. If you have further questions, let us know.
