### ISSUE TITLE
dotnet-sdk is not available on channel 5.0 or latest/stable

### ISSUE THREAD

**Issue by BasPaap** [dotnet/docs#22956]
Following the instructions on this page, I ran sudo snap install dotnet-sdk --classic --channel=5.0 but snap returned the following error:

       error: snap "dotnet-sdk" is not available on stable but is available to install on the following
       channels:

       edge       snap install --edge dotnet-sdk

       Please be mindful pre-release channels may include features not completely tested or
       implemented. Get more information with 'snap info dotnet-sdk'.

A similar message appears when specifying latest/stable as the channel:

       error: snap "dotnet-sdk" is not available on 5.0/stable but is available to install on the
       following channels:

       5.0/edge   snap install --channel=5.0/edge dotnet-sdk

       Please be mindful pre-release channels may include features not completely tested or
       implemented. Get more information with 'snap info dotnet-sdk'.

Snap core version: 16-2.48.2.1
Raspberry Pi OS version: Linux raspberrypi 5.4.83-v7+ #1379 SMP Mon Dec 14 13:08:57 GMT 2020 armv7l GNU/Linux

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a40005eb-f935-d50d-10ce-c1e0a47ea70e
* Version Independent ID: 91f4a9b7-09d0-f18e-af4a-c0af28a8948f
* Content: [Install .NET on Linux with Snap - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-snap)
* Content Source: [docs/core/install/linux-snap.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-snap.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello.

I believe the snap package for .NET 5.0 ARM (which is supported by the pi) is a preview package, not the final release. It seems to be frozen at that version. You can try to use the [script installer](https://docs.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#scripted-install) to see if that gets it installed for you, otherwise, you'll have to do it [manually](https://docs.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#manual-install).

There is a short discussion thread that was opened on this that you can contribute to: dotnet/core#4757

I'm going to close this issue as there is nothing I can do for it currently. Cheers!
