### ISSUE TITLE
TYPO: Image has doubled reference numbers

### ISSUE THREAD

**Issue by arglgruml** [dotnet/docs#22954]
The image "Figure 3-4. Dapr integration in eShopOnDapr." has two "4"s and no "5" in its legend.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c5a1dc6-9f1a-e030-9881-44e13ac6d450
* Version Independent ID: 5808b993-1f47-7801-6c0c-1b5725cd9711
* Content: [Introduction to the eShopOnDapr reference application](https://docs.microsoft.com/en-us/dotnet/architecture/dapr-for-net-developers/reference-application)
* Content Source: [docs/architecture/dapr-for-net-developers/reference-application.md](https://github.com/dotnet/docs/blob/master/docs/architecture/dapr-for-net-developers/reference-application.md)
* Product: **dotnet-architecture**
* GitHub Login: @amolenk
* Microsoft Alias: **nanil**

**Comment by amolenk** [comment]
@nishanil It was fixed in master a couple of days ago, but not visible in the live branch yet. Anything else we need to do to push it through?

**Comment by EdwinVW** [comment]
It will be when this PR gets merged:https://github.com/dotnet/docs/pull/22952   From: Sander MolenkampSent: Tuesday, 23 February 2021 15:30To: dotnet/docsCc: Edwin van Wijk; MentionSubject: Re: [dotnet/docs] TYPO: Image has doubled reference numbers (#22954) @nishanil It was fixed in master a couple of days ago, but not visible in the live branch yet. Anything else we need to do to push it through?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by nishanil** [comment]
@amolenk Nope. We are good. We will wait for the PRs to get merged to live.
cc @IEvangelist
