### ISSUE TITLE
Enhance the note about var and nullable reference types

### ISSUE THREAD

**Issue by Dave-Lowndes** [dotnet/docs#22997]
The documentation notes:
"When var is used with nullable reference types enabled, it always implies a nullable reference type even if the expression type isn't nullable.
"

I think it should be worded more strongly, possibly adding something along the lines of ... If you don't want your variable to be nullable, always define its type fully; don't use var.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 651ba093-2cef-e0f6-be71-ffdf6551c2c4
* Version Independent ID: a4878d20-2a12-74ad-9fc0-9f589a44af35
* Content: [var - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/var)
* Content Source: [docs/csharp/language-reference/keywords/var.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/var.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @Dave-Lowndes That's a valid point.

I've added this to our backlog for the next update.

**Comment by CyrusNajmabadi** [comment]
Can you include me in this discussion if you are considering makign changes here.  I do not think we want to push `If you don't want your variable to be nullable`.  That would be an anti pattern.  The design and goal of the language here is to make it find to have *nullable types* as flow analysis ensures you don't have null-*values* used in a way that would cause a null-ref-exception.

**Comment by MelbourneDeveloper** [comment]
The warning should be in the strongest possible terms, like:

WARNING!!!! THIS WON'T DO WHAT YOU THINK. THE VARIABLE WILL BE NULLABLE. USE THE EXPLICIT TYPE INSTEAD

**Comment by CyrusNajmabadi** [comment]
@BillWagner @Dave-Lowndes , @MelbourneDeveloper is incorrect here, and this stems from a misunderstanding around how NRT works in practice.  it is vital that we explain this well, but in no way should we be warning people of this, nor should we be advising them to use the explicit type. 

This was a conscience and intentional part of the design of NRT and is was driven by actual data that demonstrated that view was overly restrictive and not useful when NRT-enabling real code bases.  We explicitly have a flow-based model for null-analysis within a method, because it's more accurate and allows correct, null-safe, code to work properly without the warnings that would occur by using the explicit type in this fashion.  

Please consult with LDM on this topic prior to writing anything here, and definitely do *not* give such a warning, or make statements like "this won't do what you think".  That si not helpful and will actively lead people astray from coding with the normal .net patterns and practices which should work in the presence of NRT and which we worked very hard to ensure appropriate semantics around.

Thanks!

**Comment by MelbourneDeveloper** [comment]
This was tongue in cheek and not meant to be taken literally.

The point is that the wording should be strong and clear to avoid confusion.

**Comment by CyrusNajmabadi** [comment]
I think we should be clear here as to what the language thinks and why that is a good thing.  In no way should we be pushing people to avoid ths, or even going into motivations like "If you don't want your variable to be nullable".  That's an anti-pattern.  NRT and the work around it, is not about preventing variables from being nullable.  It is about preventing null reference exceptions.  It's explicitly making the situation confusing if we even frame a discussion in that light because it misleads customers as to what the purpose of this work is, why they want, and why it works the way it does.  

As we've seen from https://github.com/dotnet/roslyn/issues/53078, there has already been confusion here.  So if we have docs that actually state anything like this, it would heavily compound that and lead more to think this way.  We want to actively avoid that, and steer people toward an accurate understanding of what hte language is doing here and why.  In that regard, our docs should be clear aobut types vs values, the goals of NRT preventing crashes, and the nature and limitations of inter vs intra-procedural analysis.

Again, under no circumstances should we frame this as `If you don't want your variable to be nullable`.  That should not be a thing.  If anything, we can bring this up to say: here's why you don't want to think about NRT in this fashion, and it can lead you astray as to what's actually going on.

Thanks, and feel free to reach out to me and anyone else on the LDM on this topic to ensure the story is clear an consistent on this topic.

**Comment by CyrusNajmabadi** [comment]
> This was tongue in cheek and not meant to be taken literally.

Sure.  I get it wasn't literal.  But we have to be careful about even the concept.  We can see how that can really mess with how people think about things.  It's similar to early docs on records which cast them in the light of being 'immutable'.  It might be ok to say that that might be an intuition you could have about it, but that it doesn't reflect reality.  It's the same thing here.  It can be actively harmful to discuss some of these topics in tihs manner as it can really throw people off as to how they think about NRT.  For example, it might make people think that the goal of NRT is to "express intent" or "ensure things are typed to not allow null as much as possible", and it might make them think that `null` is bad, or must be avoided in mehods.  It might then also make people nervous to discover that `var` can end up inferring a `nullable type` for a variable, and that (given the previous inferences) is then a bad thing when it really isn't.  :)

**Comment by MelbourneDeveloper** [comment]
Apologies if my words above were harsh. Again, this was my sense of humor and not supposed to be taken literally. 

I think the original documentation is fair:
> When var is used with nullable reference types enabled, it always implies a nullable reference type even if the expression type isn't nullable.

I think it's just worth noting that many people will end up reaching the documentation in the same way I did: by experimenting with code and then being directed to the docs when surprised. 

I'm not sure of the best way to alleviate confusion, but I think it would be a good idea to have a write-up about why `var` declares the variable as nullable and how the compiler rules will pick up possible cases where null is being used incorrectly. I personally think that it's worth considering declaring the type explicitly - at least in some cases. 

My reasoning is about intention. If I don't want the variable to be set to null at a later point in the code, I would want to specify that at the declaration level. I honestly expected that `var` would declare the variable as not nullable when the expression is not nullable, and I believe that others will think the same.

**Comment by CyrusNajmabadi** [comment]
> I honestly expected that var would declare the variable as not nullable when the expression is not nullable, and I believe that others will think the same.

Sure. That intuition is totally reasonable. And I do think we should have good docs explaining what's actually going on and why. 

The crux of the matter is simply that such behavior doesn't help any code it out there. Indeed, it's worse as it means users will get nrt warnings and errors on *good* code using good coding techniques and patterns. 

That goes very against the letter and spirit of nrt. We should be telling you about actual problems. However, the above intuition would lead to more false positives, and that greatly reduces the value of this feature.

**Comment by Dave-Lowndes** [comment]
Might some concise code examples help explain your perspective (possibly in a more in-depth article linked from the var document), because it's still not clear to me.
As has been mentioned, I also think most people are not going to expect var to be nullable in these circumstances - I was very surprised by it and assumed it was an error.

**Comment by CyrusNajmabadi** [comment]
>Might some concise code examples help explain your perspective

Sure.  Though i'll turn it around on you.  Can you give an example why that's not desirable to do it this way.  Let's look at a very simple sort of coding pattern (note thsi is just one of many):

```c#
void Whatever(Node node)
{
  for (var current = node; current != null; current = current.Parent)
  {
    ProcessNode(current);
  }
}

void ProcessNode(Node node) { ... }
```

This is an example of perfectly readable, sensible, idiomatic C# code.  Both methods do not want null to flow into them, and so are marked as taking just a non-null `Node`.  in the body of the first method though, we want to have a temp variable that we use to mark our place in that tree.  We initially start of that temp local pointing at the node we passed in.  But note that just because the node we passed in shoudl never be null, that is not a claim we are making about `current`. Indeed, we both want and expect `currrent` to become null as we walk the tree.  Our code though is sensibly written, and we will not ever use a `null` value for `current` in a place where that would be bad.  The compiler has performed flow-analysis.  So it knows that even though `current` has the type `Node?` it will always not `Node` within the body of that loop.

Here's an example of perfectly reasonable, well written, code that should be convertible to NRT without having to touch it at all.

--

Now, consider a world where we inferred that a local must be non-null because it was initially given a non-null value.  What would happen with the above code?  Well, immediately, you'd get a warning saying that `current = current.Parent` is potentially unsafe as it can put `null` into `current`.  But why is that a good warning to get?  The code is correct, and well written.  The point is entirely to walk it, allowing it to become null, but only processing when it is non null.  

This is why method bodies use flow analysis to make these determinations . Because that's what matters here.  It's not valuable or desirable to prevent hte local variable from containing null.  It's valuable and desirable to prevent that `null` value from being used in a manner that goes against the rest of hte program.  With this example you can see that that is what our flow analysis ensures, and you can see that preventing null in a case like this is just artificially limiting.

**Comment by Dave-Lowndes** [comment]
OK, thanks for that example, it does illustrate your point well.
Having said that, I think I'd have preferred to have it not compile without changing current to be nullable (because Parent must be nullable), but maybe that's just me (and others) preferring things to be explicit.
There's no pleasing some folk :)

**Comment by CyrusNajmabadi** [comment]
> Having said that, I think I'd have preferred to have it not compile without changing

**Comment by BillWagner** [comment]
Good points here.  

Any change would be consistent with the way we've described NRT in the [conceptual article](https://docs.microsoft.com/dotnet/csharp/nullable-references).

Reading through these comments, I think adding these points after the quoted sentence would add the clarity needed:

1. Point out that static flow analysis protects against dereferencing a `null` value, even for variables that are nullable reference types.
1. That means if a variable declared with `var` is never assigned to an expression that *might be null*, you'll never see any warnings (and you'll never throw any `NullReferenceExceptions` dereferencing that variable).
1. If you assign that variable to an expression that *might be null*, you must test that it isn't null before dereferencing it, or the compiler will warn that the variable *might be null*.

The behavior is consistent with the rules in the conceptual article on NRT, and as @CyrusNajmabadi points out: the goal of the feature is to provide tools so your code throws `NullReferenceException` less often. It's not opinionated on whether `null` is *good* or *bad*. 

I'd consider an additional sentence saying "You use the explicit type for a non-nullable reference type if you want to ensure that it's never assigned a value that *might be null*". I don't know that it's a useful addition though. The important additions are on the three points I made above.

Thoughts on those changes @CyrusNajmabadi?

**Comment by CyrusNajmabadi** [comment]
Overall i agree with you @BillWagner .  I still land on this just not being something to talk about: You use the explicit type for a non-nullable reference type if you want to ensure that it's never assigned a value that might be null

because i think that then implies to users that that's a way they should be thinking about code.  A core point of NRT here is that you shouldn't necessarily think about code that way.  As you say, NRT doesn't posit htat `null` is bad.  It posits that it's easy to accidentally get things like null refs.  Null is fine, and even an good way to represent things (esp. any case that needs sentinels), as long as those accidental null refs can be avoided.  That's what NRT seeks to provide.
