### ISSUE TITLE
Value ref vs. ref value

### ISSUE THREAD

**Issue by macha-firstis** [dotnet/docs#23104]
Since many years ago, I was always confused by the used terminology. And now I see it again: This article is about passing variables by **reference**. Another article is about passing variable by **value**.
In this article you use freely both terms: 

>a value that is passed by reference.

Please don't call the variable (object, instance) a **value** while this article is about the opposite - the **ref**.
Also, it might be good to revise all corresponding articles and just show the examples, how the **in, ref, out** work differently.

I'd like to suggest to reserve the term value for another opportunity. For example say a literal values article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d67349b-72bc-b7cf-f754-fa62d1fb592d
* Version Independent ID: 4f413bcc-90e7-d971-fe75-b4876124e75d
* Content: [ref keyword - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/ref)
* Content Source: [docs/csharp/language-reference/keywords/ref.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/ref.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @macha-firstis 

We'll edit this and make use of consistent terminology.

**Comment by tdykstra** [comment]
@macha-firstis Thank you for reporting this issue about consistent use of terminology. In this instance, however, I believe the language used in the docs is mostly consistent and accurate. I went through this article and those it links to, looking at the use of "value," and I found few places where it seemed like "value" was used inconsistently and a different word such as "variable" was a better choice. "Variable" doesn't always fit as a replacement for "value." For example, in the phrase "return value" it would not make sense to say "return variable" because the return statement might specify a literal or an expression rather than a variable. I'm editing this article for clarity to respond to this issue and will be opening a PR for that. For the best explanation of the difference between passing by ref vs. by value, see [Passing parameters](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/passing-parameters).
