### ISSUE TITLE
Explain why `using` is useful for `IDisposable`s, and consequences for not

### ISSUE THREAD

**Issue by stevedesmond-ca** [dotnet/docs#23294]
As a developer, I'd like to know what happens when an `IDisposable` isn't declared in a `using` block, so that I understand the GC consequences of choosing to / not to do so.

How (if at all) do `IDisposable`s get disposed of / GC'd if not wrapped in a `using` or explicitly `.Dispose()`d? Does this change whether they're local variables contained in a single method vs fields/properties on a class?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b83e20ec-96de-0340-0813-27968ae4ca89
* Version Independent ID: db8ef20b-08da-cbac-0d96-91dcef8abe56
* Content: [Using objects that implement IDisposable](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/using-objects)
* Content Source: [docs/standard/garbage-collection/using-objects.md](https://github.com/dotnet/docs/blob/main/docs/standard/garbage-collection/using-objects.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
I would guess that the managed resources in the IDisposable object would be GC'd like any other managed resources, but the unmanaged resources wouldn't be released until the process exited. Perhaps @IEvangelist or @Maoni0 can clarify further.

**Comment by Maoni0** [comment]
GC doesn't know anything about Dispose or IDisposable. GC only knows whether an object is finalizable and when that object is dead, whether the finalizer needs to be run. if so it will promote this object so its finalizer can run. otherwise the object is still considered dead and will be reclaimed. what Dispose usually does is to call SuppressFinalize which sets the bit that indicates the finalizer for this object is already run so when GC sees it it will not promote this object.

**Comment by davidfowl** [comment]
It's amazing how many developers think the GC disposes objects. I would add an explicit note in the docs about this in bold.
