### ISSUE TITLE
Availablility of the source code for the article

### ISSUE THREAD

**Issue by PingPongSet** [dotnet/docs#23524]
The source code where `WebApp` connects to `WebApi` is missing. Is it possible to provide this?

Another question is that how to reference `WebApiBaseAddress` in code defined `docker-compose.override.yml` file?

```
 webapp:
    environment:
      #...
      - WebApiBaseAddress=http://webapi
    ports:

    #...

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95aa8619-2154-00fb-5994-09b7a9673e03
* Version Independent ID: 182cacc8-12d1-70ac-6005-71d4f6f420d5
* Content: [Build ASP.NET Core applications deployed as Linux containers into AKS/Kubernetes clusters](https://docs.microsoft.com/en-us/dotnet/architecture/containerized-lifecycle/design-develop-containerized-apps/build-aspnet-core-applications-linux-containers-aks-kubernetes)
* Content Source: [docs/architecture/containerized-lifecycle/design-develop-containerized-apps/build-aspnet-core-applications-linux-containers-aks-kubernetes.md](https://github.com/dotnet/docs/blob/main/docs/architecture/containerized-lifecycle/design-develop-containerized-apps/build-aspnet-core-applications-linux-containers-aks-kubernetes.md)
* Product: **dotnet-architecture**
* Technology: **containerized-lifecycle**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment]
Hi @PingPongSet , thank you for reaching out. 

You can follow any of the approaches mentioned in [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-5.0) to call a backend API from the Web App.  And you need to make sure that you use the `WebApiBaseAddress` environment variable as URI instead of any hard-coded backend API URL. 

Also, you'll be able to access the `WebApiBaseAddress` environment variable within your Web App project by using the `IConfiguration configuration` or the `IOptions<AppSettings> setting`

You can find similar implementation in the `eShopOnContainers` reference application as well. 

For e.g : 

`Accessing Configuration Variable` : 
https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Web/WebMVC/Startup.cs#L178
or 
https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Web/WebMVC/Services/BasketService.cs#L29

`Defining the Named Client`
https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Web/WebMVC/Startup.cs#L155

`Fetching Basket Details`
https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Web/WebMVC/Services/BasketService.cs#L32 

Hope this helps !

**Comment by PingPongSet** [comment]
@sughosneo
Thanks for your comment and taking the time to provide the info, which is very helpful.

Closing it for now.
