### ISSUE TITLE
Incorrect category for ILxxxx

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#23790]
The docs state the category for these rules as "Publish" while it's actually "SingleFile". This is significant to users since the category can be used to configure rules, e.g: `dotnet_analyzer_diagnostic.category-Publish.severity = error` vs `dotnet_analyzer_diagnostic.category-SingleFile.severity = error`.

Note: We should confirm whether it had the category "Publish" in the past and indicate which version of the SDK has the changed category.

https://github.com/mono/linker/blob/a86658f4602e616d71e5d6db23a30940534132e2/src/ILLink.RoslynAnalyzer/DiagnosticCategory.cs#L9

cc: @gewarren @mavasani @agocke

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a12a9b9d-05b7-3c64-fd90-f4b66cb865fc
* Version Independent ID: ae6b86eb-a078-b6bd-98a0-8252de1f4734
* Content: [Publish rules (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/publish-warnings)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/publish-warnings.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/publish-warnings.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Youssef1313** [comment]
It used to have "Publish" category before it was moved from dotnet/roslyn-analyzers to mono/linker.
[Example](https://github.com/DaveSkender/Stock.Indicators/blob/f46f619132050896959c0ac426158b360c99e9a3/.editorconfig#L279) of a broken editorconfig as a result of this change.

**Comment by agocke** [comment]
Looks like this may have been changed accidentally. We should preserve the Publish category to prevent a breaking change here.

**Comment by Youssef1313** [comment]
> Looks like this may have been changed accidentally. We should preserve the Publish category to prevent a breaking change here.

@agocke This was changed per https://github.com/mono/linker/pull/1974#issuecomment-821560045 right?
Starting with which version will the new category take place?
I'm also curious why it was decided not to preserve the Publish category?

**Comment by tlakollo** [comment]
The PR is https://github.com/mono/linker/pull/1665 which is included from installer v6.0.100-preview.3.21202.5 and forward 
On the first analyzer, there was only one category for both trimming and single file. So one of the reasons was to have one category for each to differentiate the warnings. But I think the main reason for the change was that although Publish worked very well for .NET console apps due to the way the command line is structured. The ILLinker started to get used in other parts where the term Publish can be ambiguous or unexistent, but the term Single File is something they can relate to. For example Xamarin, they don't use the term publish but the end result is a single file .apk or .ipa  for android or ios respectively.
