### ISSUE TITLE
Should the docs say that Dispose doesn't have to be called on types like MemoryStream?

### ISSUE THREAD

**Issue by svick** [dotnet/docs#2385]
There are types like [`MemoryStream`](https://docs.microsoft.com/en-us/dotnet/api/system.io.memorystream) or [`StringWriter`](https://docs.microsoft.com/en-us/dotnet/api/system.io.stringwriter) that inherit the `IDisposable` interface from their base class, but don't actually clean up any resources when `Dispose()` is called.

Right now, the docs for these types contain what looks like standard `IDisposable` note:

> **Important**
>
> This type implements the IDisposable interface. When you have finished using the type, you should dispose of it either directly or indirectly. To dispose of the type directly, call its Dispose method in a try/catch block. To dispose of it indirectly, use a language construct such as using (in C#) or Using (in Visual Basic). For more information, see the "Using an Object that Implements IDisposable" section in the IDisposable interface topic.

Should the documentation instead say that it's not necessary to call `IDisposable` on such types? Right now, "`Dispose` doesn't do anything" is an implementation detail, this would promote it to an explicitly documented feature. But I think a lot of people (including me) already rely on that implementation detail.

**Comment by rpetrusha** [comment]
When we began adding the Dispose boilerplate (an operation that, unfortunately, was never completed), we also had intended to note cases in which calling Dispose was unnecessary, either because there was no real implementation or, in a few cases, because a type should not have implemented Dispose in the first place. That work was never done, either. So I would agree with you, @svick, that the documentation should not cases in which calls to Dispose are unnecessary.
