### ISSUE TITLE
Remarks section of enum members doc comment doesn't show in API reference

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#23950]
This is not specific to LanguageVersion enum. Any enum with `<remarks>` on a member won't show in the API reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d51a386d-ffa5-43b0-d29b-d01df05a7349
* Version Independent ID: 07a917bf-4fab-f961-404c-5a9a7a4da63f
* Content: [LanguageVersion Enum (Microsoft.CodeAnalysis.CSharp)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.csharp.languageversion?view=roslyn-dotnet-3.9.0)
* Content Source: [dotnet/xml/Microsoft.CodeAnalysis.CSharp/LanguageVersion.xml](https://github.com/dotnet/roslyn-api-docs/blob/live/dotnet/xml/Microsoft.CodeAnalysis.CSharp/LanguageVersion.xml)
* Product: **dotnet-roslyn-api**
* Technology: **microsoft.codeanalysis**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
Ping @joelmartinez 

Where should we route this?

**Comment by joelmartinez** [comment]
🤔 hmm ... this is because we currently treat enums differently than other types, where each member doesn't have an individual page in which we would show remarks; we just list all the enums and their summary on one page. Brainstorming a bit, we would probably either have to expand that out so that each member of the enum has its own page, or maybe do something where the remarks for each field are hidden by default, and you can expand them on-demand.

You probably want to work with PMs (ie. @mimisasouvanh and @rloutlaw) to design and prioritize this feature request :) 

/cc @TianqiZhang @wh-alice

**Comment by gewarren** [comment]
This is a known issue and we've already met once on the proposed design - https://dev.azure.com/ceapex/Engineering/_workitems/edit/390259.

**Comment by gewarren** [comment]
We also currently have a build warning to let you know that the remarks will be ignored.

**Comment by Youssef1313** [comment]
@gewarren Should I close if it's already tracked internally?

**Comment by gewarren** [comment]
Yes, I'll close this, but I've added a link to this issue in the internal tracking item. Thanks @Youssef1313 .

**Comment by gewarren** [comment]
Internal tracking issue: https://dev.azure.com/ceapex/Engineering/_workitems/edit/801799
