### ISSUE TITLE
Move and retire "What's new in C# 7.x"

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#24080]
As the last task of this project, the current C# 7.x what's new content should move to the appropriate location in the C# guide. It's no longer ✨ New ✨

**Comment by Eirenarch** [comment]
I don't understand why you'd do this. There are places that link to this article and also it is beneficial to be able to track how the language evolved version by version

**Comment by BillWagner** [comment]
@Eirenarch That's a good question There's three parts to the answer:

First, There will be redirects for any links to this article. They'll get rerouted to the C# 7.x sections of the [C# version history](https://docs.microsoft.com/dotnet/csharp/whats-new/csharp-version-history). Second, we won't make circular links, the content from the what's new article gets added to the version history article. Third, tutorials and examples for the new features will be moved to the sections on that language feature, rather than call them out by version.

We feel this is a good balance between learning the language as it exists now, and understanding the history of what features were added in each version. Both are important. We don't want to require readers to know which version introduced a feature to find it. We also want to explain the language's evolution.

The "what's new" by version pages are designed to help developers as they upgrade between versions. Once a version is old enough, that use is needed less. That's the reason to retire them eventually.

**Comment by Eirenarch** [comment]
I see. I somehow didn't realize the version history page existed or rather I assumed it contained release dates and corresponding .NET/VS versions and not lists of features.

**Comment by ToMakeSense** [comment]
@Eirenarch @BillWagner 
Frankly speaking, I don't like the document maintenance style -- **"Move and retire"**. I am grateful to you for maintaining the document so well. However, the document is like a product and the link should be stable enough.

I still remembered that not long ago, I queried [what's new in C# 6.0](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-6), unfortunately, I just couldn’t find it. I clearly remembered it was there just under `what's new`... I checked the github check-in history and found that the document was **permanently** deleted. well...

Yes, we still have [The history of C#](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-version-history), but this one is really too brief.

**If possible, please consider moving these documents to a folder to archive/reference, or you could just consider it as release notes, so that we could still find/redirect to them when we need to refer to the specific version.**

Many similar maintenance methods could be find below, which keep the original details and is also more reasonable.

**some Microsoft style**
* [Visual Studio Release Notes](https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes)
* [Nuget Release Notes](https://docs.microsoft.com/en-us/nuget/release-notes/)

**famous OSS style**
* [Elasticsearch Release notes](https://www.elastic.co/guide/en/elasticsearch/reference/current/es-release-notes.html)
* [Mongdb Release Notes ~ from V1.2-5.0](https://docs.mongodb.com/manual/release-notes/5.0/)
* [Couchbase Documentation Archive](https://docs-archive.couchbase.com/home/index.html)
