### ISSUE TITLE
Weird term "framework-dependent"

### ISSUE THREAD

**Issue by victor-yarema** [dotnet/docs#24423]
The page describes term "framework-dependent". But the definition says that in such case an app depends on "runtime". Why it is not called "runtime-dependent" then? Is there another term "runtime-dependent" which means something different than "framework-dependent"?
Personally I find the term "framework" pretty confusing nowadays. If I'm not mistaking it was used to describe something which is called "SDK" today. But here it was used as a synonym to "runtime". And I also assume that the vast majority of devs today clearly understand the difference between "SDK" and "runtime". Maybe "framework" is a good word for marketing or whatever. I am not good at that. But I find it not quite correct for technical documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85eba478-0374-bb9b-8fa7-d5cf7d520603
* Version Independent ID: 89967250-8c3b-1999-078f-94ad7518ed49
* Content: [Application publishing - .NET](https://docs.microsoft.com/en-us/dotnet/core/deploying/)
* Content Source: [docs/core/deploying/index.md](https://github.com/dotnet/docs/blob/main/docs/core/deploying/index.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by IEvangelist** [comment]
Hi 👋 @victor-yarema
Thank you so much for posting this issue. We really appreciate it.

In all honesty, I agree with you. The term is confusing and runtime-dependent makes more sense. I can only assume it was originally derived from the notion of .NET Framework. I labeled this issue as both product feedback and question. I'll tag a few folks here who might have a bit more insight.

@bartonjs @terrajobst and @davidfowl - do any of you have any idea where the term "framework-dependent" came from, see the ask above.

**Comment by adegeo** [comment]
I thought along the same lines about a year ago and actually edited this and maybe another doc to replace framework with runtime. However, this caused even more confusion because the term "framework-dependent" is used in other tools and programs such as Visual Studio. We had to revert those changes almost a year ago in #20165

From a product standpoint this is the name of the feature. It needs to be changed there and in Visual Studio before we can change it in the docs.

Your best bet is to search/discuss it over at https://github.com/dotnet/sdk or https://github.com/dotnet/runtime

😦
