### ISSUE TITLE
Token $ reserved for future use - code for a lower f# version

### ISSUE THREAD

**Issue by surfmuggle** [dotnet/docs#24457]
This sample 
```
    let swapElems (a, b) = (b, a)
    printfn $"The result of swapping (1, 2) is {(swapElems (1,2))}"
```
throws this:` error FS1160: This token is reserved for future use [C:\...]`. Version:  `dotnet --version 3.1.113`

My attempt to avoid `$` and use 
```
// either
printfn "The result of swapping (5, 9) is %s" + swapElems.ToString()
// or
printfn "The result of swapping (5, 9) is %s" + String.Concat(swapElems)
```
returns `error FS0001: The type 'string' does not match the type 'string -> unit` for ToString and Concat

For a f# beginner it is unclear if a f# tuple does support ToString or Concat or how to use them. I assume that swapElems returns void (== unit). But how can i get access to the tuple content?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89bef555-3de1-5d81-c02b-2ac8c049423b
* Version Independent ID: eb13ad9e-2c95-979b-6d6e-13d29653c6ba
* Content: [Tour of F#](https://docs.microsoft.com/en-gb/dotnet/fsharp/tour)
* Content Source: [docs/fsharp/tour.md](https://github.com/dotnet/docs/blob/main/docs/fsharp/tour.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by surfmuggle** [comment]
Using 

```
    let x,y = swapElems(5,9)
    printfn "The result of swapping (5, 9) is %i" + x
```

Does not help either: `error FS0001: The type 'int' does not match the type ''a -> unit'`

**Comment by svick** [comment]
F# does support string interpolation, but it requires .Net SDK 5.0. Maybe this page should mention that?

If you don't want to do that, some of the ways you could write this code are:

```f#
printfn "The result of swapping (5, 9) is %s" (swapElems(5,9).ToString())
printfn "The result of swapping (5, 9) is %A" (swapElems(5,9))
printfn "The result of swapping (5, 9) is (%i, %i)" x y
System.Console.WriteLine("The result of swapping (5, 9) is " + swapElems(5,9).ToString())
```

**Comment by surfmuggle** [comment]
In some companies it is not easy to upgrade to the latest dotnet core version. 
As you suggested it be good to 

- either add a min requirements
- or provide code sample that run at least on [the current LTS version of dotnet](https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-and-net-core?ranMID=46131&ranEAID=a1LgFw09t88&ranSiteID=a1LgFw09t88-.uLyG_clk_3KaVl4offHmg&epi=a1LgFw09t88-.uLyG_clk_3KaVl4offHmg&irgwc=1&OCID=AID2000142_aff_7806_1243925&tduid=%28ir__wqxmyfzcdskfqidukk0sohz3wv2xunqzp2hezmmc00%29%287806%29%281243925%29%28a1LgFw09t88-.uLyG_clk_3KaVl4offHmg%29%28%29&irclickid=_wqxmyfzcdskfqidukk0sohz3wv2xunqzp2hezmmc00).

I would prefer if every code sample runs at least on the current LTS version.

**Comment by cartermp** [comment]
Thanks for filing the issue. The docs don't have a way to toggle between LTS and non-LTS right now. If that becomes a capability, we can consider changing what the F# docs display. However, even with that, I'm not really a fan. What will happen is a pretty big ramp-up in maintenance complexity that I'm just not interested in keeping up with.

String interpolation examples are spread everywhere in the docs, so it's not just one spot that would need an update. And this is a feature we want people to use to the extent that the `printf` format strings are largely obviated for common/simple tasks. I recognize that this could be difficult for people learning the language _and_ being stuck on an older release. But this is also a short point-in-time problem, especially since .NET 6 LTS is releasing later this year.
