### ISSUE TITLE
Issue with docker-compose.yml

### ISSUE THREAD

**Issue by AtmiyaVaghela** [dotnet/docs#24491]
I have tried all steps provided but unfortunately, I am getting the error.

Dapr.Client.InvocationException: An exception occurred while invoking method: 'weatherforecast' on app-id: 'daprbackend'
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Dapr.Client.DaprClientGrpc.InvokeMethodAsync[TResponse](HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Dapr.Client.DaprClientGrpc.InvokeMethodAsync[TResponse](HttpRequestMessage request, CancellationToken cancellationToken)
   at DaprFrontEnd.Pages.IndexModel.OnGet() in C:\Users\atmiya.vaghela\workspace\learning\dapr\DaprMultiContainer\DaprFrontEnd\Pages\Index.cshtml.cs:line 23

After lots of research and learning. I found that daprbackend Web API project was added without HTTPS. But in docker-compose.yml this declares as,

`daprbackend-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "daprbackend", "-app-port", "443", "-app-ssl" ]
    depends_on:
      - daprbackend
    network_mode: "service:daprbackend"
`
Which gives 500 internal errors. After rewriting this as per below worked as expected. Hope my findings are correct and useful to others.

`daprbackend-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "daprbackend", "-app-port", "80" ]
    depends_on:
      - daprbackend
    network_mode: "service:daprbackend"
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83e95a3f-447b-8ca0-beb5-f0363896fe29
* Version Independent ID: b24e3ee5-404c-98a2-042e-6ac2d363b842
* Content: [Get started with Dapr](https://docs.microsoft.com/en-us/dotnet/architecture/dapr-for-net-developers/getting-started)
* Content Source: [docs/architecture/dapr-for-net-developers/getting-started.md](https://github.com/dotnet/docs/blob/main/docs/architecture/dapr-for-net-developers/getting-started.md)
* Product: **dotnet-architecture**
* GitHub Login: @amolenk
* Microsoft Alias: **nanil**

**Comment by amolenk** [comment]
Hi @AtmiyaVaghela!

Did you by any chance miss the following step when adding the DaprBackEnd project?

> By default, a Dapr sidecar relies on the network boundary to limit access to its public API. So, clear the checkbox for **Configure for HTTPS**.

If you left that checkbox checked, the generated ASP.NET Core API includes middleware for redirecting to HTTPS. By default, this will not work with Dapr. Unless, as you correctly write, you use the `-app-ssl` flag.

This is pretty easy to miss though, so I'll make it a bit clearer in the text.

**Comment by amolenk** [comment]
After re-reading your issue, I see that the problem is slightly different. The docker compose file should not use port 443. Let me check why that happens...

**Comment by AtmiyaVaghela** [comment]
> After re-reading your issue, I see that the problem is slightly different. The docker compose file should not use port 443. Let me check why that happens...

Yes exactly, I have updated that to 80 and remove "-app-ssl", then it worked correctly.

**Comment by amolenk** [comment]
Ok, figured it out.

The original walkthrough was based on HTTP and used ports 80 in the Docker Compose file. I don't think the `--app-ssl` flag was even available then.

A week ago, PR #24360 introduced a bug by changing the ports to 443. I believe the reason for this is that the reader probably missed the **clear the checkbox for Configure for HTTPS** comment in the instructions. That instruction is easy to miss and will require you to use `--app-ssl` and the 443 port settings to get the sample working. Unfortunately, that PR doesn't have a linked issue, so I missed it.

At this moment, the instructions in the book are incorrect because we now both tell you to disable HTTPS on the app and then tell you to use HTTPS in Docker Compose 😢 

I'll make two fixes:
1. Revert the changes in #24360 
2. Add an additional comment to the text to make it less likely that people will forget to uncheck the HTTPS checkbox.

In general, Dapr uses the network perimeter as a security boundary (as is common in sidecar patterns), so we don't want to recommend people to use HTTPS between sidecar/app by default.
