### ISSUE TITLE
"Don't assume the type is clear from a method name." - not honored by the analyzer team

### ISSUE THREAD

**Issue by xecrets** [dotnet/docs#24664]
This page states "Don't assume the type is clear from a method name.". This is not honored by the Visual Studio Roslyn analyzer.

Specifically see https://github.com/dotnet/roslyn/issues/29657 - and the part where @CyrusNajmabadi refers to the rules applied to determine if a "type is apparent" in order to suggest (or not) to use an explicit or implicit type (var).

"The rules are that the type 'Foo' is apparent if we see:

1. new Foo
2. new Foo[]
3. (Foo)...
4. ... as Foo
5. Foo.StaticMethodThatReturnsAFoo(...). i.e. XElement.Parse
6. ....ToFoo(...). i.e. Convert.ToDateTime, blah.ToList(),"

Specifically, rule #6 is in direct violation of "Don't assume the type is clear from a method name." . Assuming that ToList() makes a List, or ToDateTime makes a DateTime, or ToPerson makes a Person is exactly what "Don't assume the type is clear from a method name." addresses. But here it is coded in the Roslyn code analyzer to do exactly that - assume that the type is clear from a method name!

Please ensure that you are in sync within the company, so that the tools actually implement the best practices, either by changing the tool (vastly preferred in this case), or at the worst change the documentation to fit the tool implementation.

Best regards,

Svante

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40f42506-f4a5-859a-0266-ded002056d83
* Version Independent ID: f940f2ad-e13d-4d37-6439-f8afcbc4e4c7
* Content: [C# Coding Conventions](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions)
* Content Source: [docs/csharp/fundamentals/coding-style/coding-conventions.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/coding-style/coding-conventions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CyrusNajmabadi** [comment]
I disagree with this, and our analyzer mattress sure this is not a problem. Specifically, we do not make assumptions here. Instead we actually check that the method name and type do match. So if you have ToDateTime that returns a DateTime, then you can use `var`.  Of course, if it doesn't return that type, then don't use `var`. This is how the analyzer works and matches the behavior expected by the car majority of devs queried on how/when `var` sound be considered apparent.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi The problem here is that this doesn't match the dotnet/runtime guidelines :(

**Comment by xecrets** [comment]
It's not about the tools or compilers ability to interpret the code correctly. It's about the humans.

The guidelines are intended to facilitate for humans, the compiler will compile obfuscated code for example just fine. But that's not code we want to write or read as humans.

So the problem here is that the tool encourages us as humans to trust that a `ToList()` method actually returns a `List`, i.e. "assume the type is clear from a method name".

That's why the guidelines do not encourage the use of `var` everywhere. It'll compile and run correctly, but it doesn't make it easy for humans to read and understand.

So, when I say that that "Don't assume the type is clear from a method name" is not honored by the analyzer, I mean this to say that the analyzer does not encourage the correct style for humans. That the analyzer *knows* that `ToList()` returns a `List` is irrelevant. The human can't know without further examination, and should not assume so.

Then there's the even bigger issue that follows as a result, that the analyzer does not account for generics, and the fact that `.ToList<MyCoolType>()` will typically be written as `.ToList()` which makes it unclear for humans, if not the tools, just what `.ToList()` returns.

Everything about style is about the humans - not the tools! All the style-related refactorings offered as fixers for Roslyn Style Analzyer violations are true refactorings, they do not change the behavior of the code. In fact, in most cases, the compiler will produce the exact same IL code before and after. The tools do not care about style, except the style analyzers whose purpose I have understood to be to encourage a style that is good for humans. Otherwise I don't really know what they are for. I'm sure the compiler doesn't care what style I use ;-) .

This is where rule #6 in the Roslyn Analyzer logic for determining if a type is apparent falls short of the purpose and the guidelines in my and apparently many others opinion.

**Comment by BillWagner** [comment]
I'm going to close this without action on docs.  

As pointed out, any guidelines are for humans.  The article states:

> You can use them [the coding standards], or adapt them to your needs. The primary objectives are consistency and readability within your project, team, organization, or company source code.

The guidelines around `var` and *if the type is obvious* is the guideline that does generate the most different interpretations. In our docs samples, we lean away from using `var` a bit. That's because you can't hover over the `var` keyword in a webpage to see the type. In Visual Studio, that's yet another way the tools can help in any of the situations noted above. It's a technique I use often with generics, and especially with generics and anonymous types. 

 Finally, you can enforce your own guidelines using the .editorconfig settings for your projects.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi The problem here is that this doesn't match the dotnet/runtime guidelines :(

I'd be fine with teh dotnet/runtime team coming up with an analyzer that matches *their* desired coding pattern :)   

It's worth pointing out that this is the idea behind analyzers/fixers.  The goal isn't for the roslyn team to then come up with a system that will be right for every team out there (including first parties like dotnet/runtime).  It's that now any individual team can decide what is right for them.

As specified in our own bug tracking this, we will likely introduce another option for what seems to eb a common complaint area here.  However, we are not likely to provide the necessary fine grained control here to tweak each and every behavior necessary to be viable for all codebases out there.  For that, teams may have to roll their own tools.  If that's not palatable, then they'll have to assess the value in having such a specific codign policy for their repo.

**Comment by CyrusNajmabadi** [comment]
>  The human can't know without further examination, and should not assume so.

Yes.  The human can know.  Because that's how the analyzer works.  if ToList returned an array, it woudl not suggest using 'var'.  Indeed, it would tell you to *stop* using 'var'.  

> Everything about style is about the humans 

Here's the problem:

1. 'humans'
2. 'apparent'

There is no consensus on what these mean together.  Indeed, if you look at the roslyn tracking bug on this issue, you'll see *different* perspectives on this from different community members.  This is why, for 'apparent' we drove this by actually having these sorts of examples and asking a broad set of users who didn't liek 'var', but were ok with it in some cases, how they would feel about these cases.  We then picked what the overall majority felt was sensible here.

However, as is clear 'apparent' is in the eye of the beholder.  For example, i think the following is completely apparent: `(new X(), new Y())`.  That clearly has the type `(X, Y)`.  However, some more hard line people felt that this is not apparent, and only cases like `new` or `(cast)` would count.  Fundamentally, we had to take each rule and check it against a large corpus of code and users to determine if this more aligned with their intuition here or not.  And we picked based on that.

FOr things like `DateTime ToDateTime()` it was nigh-overwhelming that this was 'apparent'.  IIRC, there might have been one person who felt otherwise.  

--

Finally, as mentioned before, we are considering another mode (`when explicit`) that would be much more in the camp of: the exact type (and it's constituent parts), must appear `explicitly` in source in independent chunks.  in that case, it would not be ok for `DateTime` to show up in something larger.  And everything from the type, and all tyep arguments (but not namespaces) would need to be explicit on the right somewhere. 

I think this will help a subset of customers. But based on the conversations so far, i'm wary about this as there are already differing views on corner cases in terms of what might be considered 'explicit' or not.

**Comment by CyrusNajmabadi** [comment]
> Everything about style is about the humans - not the tools! All the style-related refactorings offered as fixers for Roslyn Style Analzyer violations are true refactorings,

This is not actually true :)

> they do not change the behavior of the code.

This is not actually true.  I did an analysis a while back, and the vast majority could change the behavior of code.  But this is accepted by almost everyone because:

1. it's unlikely to change meaning in reasonable coding patterns.
2. the value of the style rule outweighs the negative of the change.

> In fact, in most cases, the compiler will produce the exact same IL code before and after.

Also not true :)  Indeed, we started with that as a goal, but discovered there was almost *no* analyzers/fixers/refactorings we coudl actually ship with that constraint.

--

To give an example, imagine somehting as simple as the style rule recommending you use `?.`.  If the user has `a.b == null ? null : a.b.c;`, is it ok to offer to change that to `a.b?.c`?  Turns out if you take a strict view on the above, then "no".  This can change meaning and can lead to a break.  However, in practice, this will not and the value in having the feature and having it work on the 99.9% case far outweighs the problem of when it goes wrong on the 0.1% case.

**Comment by xecrets** [comment]
Pretty interesting, if somewhat offtopic, discussion on a closed issue!

> > @CyrusNajmabadi The problem here is that this doesn't match the dotnet/runtime guidelines :(
> 
> I'd be fine with teh dotnet/runtime team coming up with an analyzer that matches _their_ desired coding pattern :)
> 
> It's worth pointing out that this is the idea behind analyzers/fixers. The goal isn't for the roslyn team to then come up with a system that will be right for every team out there (including first parties like dotnet/runtime). It's that now any individual team can decide what is right for them.

Here's what it looks like from the outside, i.e. outside of Microsoft. This may be incorrect, but it's what I see and what I think a lot of others see.

Left hand - writes documentation, best practices and guidelines.
Right hand - writes tools to facilitate following best practices and guidelines.

From the outside I see Microsoft. One company, one organization - and presumably one view on what is officially best practices.

We've seen the various generations of static code analyzers from FxCop and forward as tools helping us to align with the best practices and guidelines suggested by Microsoft - because they are pretty good, and it's a great argument when there are differing views in the team -"because Microsoft says that's how it should be done". 

Now here we see refererences to "the dotnet/runtime team" and "the Roslyn team", with apparently differing views on what's best.

Can't you guys just discuss this and agree on one preferred style please?

**Comment by xecrets** [comment]
> To give an example, imagine somehting as simple as the style rule recommending you use `?.`. If the user has `a.b == null ? null : a.b.c;`, is it ok to offer to change that to `a.b?.c`? Turns out if you take a strict view on the above, then "no". This can change meaning and can lead to a break.

(Offtopic, I know, and the issue is closed, but this was really interesting!)

How does meaning change here? Yes, if `a`, `b` or `c` are written from other threads, sure, the behavior can potentially change due to race conditions during evaluation. However, if that *is* the case, then the behavior of both versions are undefined and/or implementation defined.

Also of course if `a`, `b` or `c` are in fact method calls or something with possible side-effects and not just simple variable references, then the meaning changes - and apparently the analyzer fixer will suggest to change `a().b() == null ? null : a().b().c()` into `a().b()?.c()` and if I read the language spec correctly when I just browsed it now, the null conditional operator in this case does guarantee that `a().b()` will only be evaluated once. So if `a()`or `b()` has side effects, meaning changes.

I did not realize that, that's really interesting. Thank you for pointing out that the suggested rewrites are in fact not necessarily safe, even if they are in the vast majority of cases.

It would be nice if there were some references in the documentation to some at least common cases where the rewrites are unsafe. If there is one, please point me to it!

**Comment by CyrusNajmabadi** [comment]
> Can't you guys just discuss this and agree on one preferred style please?

No. That's the point. There is no one style. The tools we build are to try to help many of the organizations and teams out there doing their own thing. 

Since people want only var. Some people never want var. Etc.   

If there was only one style, then literally we would mandate that in the language and compiler and reject everything else. However, that's not the philosophy of our ecosystem. We want to let customers decide what is best for *their* needs. We can certainly give advice and suggestions, but we leave it up to you. 

Note, as mentioned and explained above, the suggestions here are complimentary with the rules.

**Comment by CyrusNajmabadi** [comment]
> I did not realize that, that's really interesting. Thank you for pointing out that the suggested rewrites are in fact not necessarily safe, even if they are in the vast majority of cases.

Actually, the vast majority are *not* safe (where 'safe' is defined as 'same il'). :-)

Note that you can have completely defined code that is always guaranteed to execute one way, which changes meaning to always run another way post rewrite. The normal case of this is, as you realized, side effects (which there are language guarantees around). 

However, our position is that code written in this fashion which *does* depend on those side effects is the rare (and discouraged) case. So we'd rather accept the breaks in that sort of code versus not being able to supply the feature for 99.99% case where it will be doing the right thing for that particular user.

**Comment by BillWagner** [comment]
@xecrets Yes, this is an interesting discussion.  

> Can't you guys just discuss this and agree on one preferred style please?

Probably not, because each team is made up of individuals, all of whom have opinions. Further, each team has different goals. For example, in our team (dotnet/docs), we lean toward using new(er) language features more often. We will even update samples to use newer language features when the existing code is valid. Our reason is that we want developers to see the newer features more often, and adopt them when appropriate. (One example now is that our team turns on nullable reference types whenever a sample is updated. Another example is updating algorithms to use records or pattern matching.  That helps us adopt those practices, and means more developers see these constructs in more scenarios.) There is a *consistency* to our styles. 

> ...it's a great argument when there are differing views in the team -"because Microsoft says that's how it should be done".

I could argue that the different styles within different Microsoft teams provides multiple good examples for teams to follow. I don't mean that as a trolling comment, but rather that .NET is an ecosystem with different views on what's "best". Some of the reasons are subjective, and those different views are valid for different teams. Sometimes that may be part of the domain a team works in, other times it may be subjective opinion.

On your other question (regarding `a.b == null ? null : a.b.c` and `a?.b?.c`.  (Yes, if those are properties with side-effects, that's where they are semantically different):

> It would be nice if there were some references in the documentation to some at least common cases where the rewrites are unsafe. If there is one, please point me to it!

We cover these rules in the area of the language, so readers can find these edge cases. I don't think it's efficient to cover every edge case in each rule. However, in the language reference, and the spec, those rules and any differences are always spelled out.

Again, thanks for the discussion.

**Comment by CyrusNajmabadi** [comment]
> We've seen the various generations of static code analyzers from FxCop and forward as tools helping us to align with the best practices and guidelines suggested by Microsoft

This is not really the purpose of these tools. Indeed, I think you'd find that even teams that did use fxcop would likely heavily customize it, and outright just disable many rules. 

C# and.net are used in tons and tons of domains. And there is no 'one size fits all' set of rules that all those domains/components/services/programs/etc. Should follow. Instead, we expect teams to figure out what is best, and we provide tooling for many (not all) cases out there to assist the wide set of needs that users and teams have. 

So it's not a matter of different hands. It's a case of: use your knowledge and experience to pick what's good for you, and we can try to help (especially in the most common cases shared in the ecosystem). And when your needs are now specialized, we deliberately made a system to allow you to extend this with your own domain rules and fixes.

**Comment by CyrusNajmabadi** [comment]
My personal advice would be: stick with the defaults unless you want to start investing in customizing these tools yourself. 

If you want something different from the tools, then you likely have to either get a *huge* part of the ecosystem to go along with you, it till have to own custom tools and processes to deal with your different case. It's less likely that a different case, washed by a tiny subset of the ecosystem will necessarily get the attention to get it changed.

**Comment by CyrusNajmabadi** [comment]
> Again, thanks for the discussion.

Agreed. Thank you all for the discussion.

**Comment by xecrets** [comment]
> Actually, the vast majority are _not_ safe (where 'safe' is defined as 'same il'). :-)
You misunderstood me. I realize now that most suggested rewrites are not strictly identical to the original. What I meant to say was that in the vast majority of cases they are effectively safe in the sense that they do not change the behavior of the code in ways that break it.

> However, our position is that code written in this fashion which _does_ depend on those side effects is the rare (and discouraged) case. So we'd rather accept the breaks in that sort of code versus not being able to supply the feature for 99.99% case where it will be doing the right thing for that particular user.
Here I agree - but I think it could be more clearly stated in the documentation since even if it is rare it can happen. For example running "code cleanup" on a large code base increases the risk that it blows up at least once or twice. In this situation, and in general, it would be a help to encourage awareness of this possibility in the documentation.

**Comment by xecrets** [comment]
> > Can't you guys just discuss this and agree on one preferred style please?
> 
> No. That's the point. There is no one style. The tools we build are to try to help many of the organizations and teams out there doing their own thing.

I certainly realize that. But most organizations will try to have at just one set of best practices for their organization as a whole, and not leave it up to each and every team. That way lie madness ;-) .

The  [C# Coding Conventions](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions) are in fact quite good, and in my experience the real value in conventions and best practices is that they are consistently used, not the exact details of them. For example, curly brace placement and use does not really objectively matter - as long as a consistent convention is adopted.

I do think many many developers outside of Microsoft view the C# conventions and best practices as seen on the web as an official guide from Microsoft. Of course, it's up to every organization to take it or leave it or adapt it. But many like it, and it's easy and cheap to re-use someone else's good work instead of re-inventing that particular wheel again and again.

It would be nice if the tools, specifically the Roslyn analyzer in this case, actually did support the particular set conventions and best practices suggested by the [C# Coding Conventions](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions).

The issue here is that if we do want to specifically use the [C# Coding Conventions](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions), the tool does not support this fully. This is by us external folks, viewed as an inconsistency/bug. I now have a better understanding of the internal workings at Microsoft, and perhaps others reading this thread will benefit from this as well.

Stated differently, if the documentation team would use the Roslyn analyzer and accept all suggestions concerning the 'apparent' rule for 'var', the resulting published code on the web would not follow their own convention of "_Don't assume the type is clear from a method name_", since the tools implementation of "apparent type" does not honor this particular case.

Anyway, it's been a learning experience having this discussion, and that's something I really appreciate. I also much appreciate that there is a possibility to have such a discussion - so thanks to both @CyrusNajmabadi and @BillWagner .

Now I think I will go see how to build my own analyzer, or adapt the Roslyn analyzer, to fit our needs ;-) .

**Comment by xecrets** [comment]
> My personal advice would be: stick with the defaults unless you want to start investing in customizing these tools yourself.

Sticking with the defaults is what I'd like.

But this `ToList()`, `ToDictionary()`, `ToAnyType()` issue is a little bit of show-stopper in the long run, especially when `ToList()` is actually a generic `ToList<SomeExcitingType>()`, resulting in `var value = source.ToList();` where the actual type of `value` is `SomeExcitingType`. That's just too unapparent for me.

So, I think I'll go for the second option - looking into customizing or extending or rolling our own additional analyzer for this case.

**Comment by Youssef1313** [comment]
A bit off-topic: I wrote an [analyzer](https://github.com/Youssef1313/YAnalyzers) for this, in case you find it useful.

**Comment by xecrets** [comment]
> A bit off-topic: I wrote an [analyzer](https://github.com/Youssef1313/YAnalyzers) for this, in case you find it useful.

Awesome! Will check it out! But I was kind of looking forward to writing an analyzer, and now I don't have a good excuse to... :-( . Thanks!

**Comment by CyrusNajmabadi** [comment]
I have opened https://github.com/dotnet/roslyn/issues/29657#issuecomment-863259267 as a potential design approach to help out here.

**Comment by CyrusNajmabadi** [comment]
> What I meant to say was that in the vast majority of cases they are effectively safe in the sense that they do not change the behavior of the code in ways that break it.

Sure.  But there's no way to know this.  From teh perspective of static analysis we have to hope that things are safe and accept that things will break if not.  My point, generally, is that almost all our analyzers will make some assumptions here around this, and thus most analyzers can break things.

Note that different customers have different views on this.  A minority of them do actually want to state that under no circumstances should IL ever change.  However, the vast majority of them do align with our position that IL change is acceptable as long as meaning stays the same in reasonably written patterns and idioms.

> Here I agree - but I think it could be more clearly stated in the documentation since even if it is rare it can happen. For example running "code cleanup" on a large code base increases the risk that it blows up at least once or twice. In this situation, and in general, it would be a help to encourage awareness of this possibility in the documentation.

I'd have no problem with docs stating this.

> I certainly realize that. But most organizations will try to have at just one set of best practices for their organization as a whole, and not leave it up to each and every team. That way lie madness

Sure.  But each organization is very often different from teh rest.  Our docs and tools cater to that reality.  Not a reality where we just state what to do and everyone follows in lockstep.

Indeed, if the latter were true, you (and others) wouldn't even be complaining about this option.  You'd just say: this option is how MS defines it, so we'll do it exactly that way.  As these conversation show, even when we put forth a position, users *do* want to not follow it.  This has *always* been true *especially* with cases like Fxcop and the rest.  

> The issue here is that if we do want to specifically use the C# Coding Conventions, the tool does not support this fully.

Again, we disagree here.  You seem to have read this advice differently from us.  We read things in a way that the tooling *does* support the advice.  A fundamental misunderstanding here seems to be the idea that the method may be 'lying' and it may have a name which says one thing, but it does another.  However, *and this really needs to be emphasized*, the tools *check for that*.  If the method lies, then we will not suggest var, and will instead tell you there's a problem.

> Stated differently, if the documentation team would use the Roslyn analyzer and accept all suggestions concerning the 'apparent' rule for 'var', the resulting published code on the web would not follow their own convention of "Don't assume the type is clear from a method name"

This is incorrect.  The part you are missing is the `assume` bit.  Our tool does not `assume`.  It `verifies`.  If you havea  `ToDateTime()` method that returns a `TimeSpan` our tool will say: you need to write that as `TimeSpan dt = x.ToDateTime()`.  And it works that way for precisely this reason.  Because the name of the method *is* misleading.  When it's not misleading, then we allow for `var` to be used.

The tool and rule are complimentary here because the tool follows the `do not assume` part.  That's the benefit of static tooling.  It can go and spend the cpu cycles to check and validate this stuff and inform you when tehre's a problem.

**Comment by CyrusNajmabadi** [comment]
> issue is a little bit of show-stopper in the long run

Right.  That was my point.  As i've said several times, even when we put forth a position and tools to support that position, customers will always still want to tweak, and we follow the mindset of: that's ok.

Some ecosystems are much more explicit that there is only one right way to do things.  I think that's fine if that's the mentality of that ecosystem.  However, MS and .net has never taken that approach with our development advice and tooling stack.  We give suggestions, and we give tooling to help around that.  But we always feel that it's ultimately in your hands if you want to follow this or if you want to go another way.  Here you want to go another way, and that's ok.  Just recognize that your own first hand experience has shown you why the "we should just follow MS in everything" mindset doesn't happen for everyone in practice :)

**Comment by xecrets** [comment]
> > I certainly realize that. But most organizations will try to have at just one set of best practices for their organization as a whole, and not leave it up to each and every team. That way lie madness
> 
> Sure. But each organization is very often different from teh rest. Our docs and tools cater to that reality. Not a reality where we just state what to do and everyone follows in lockstep.

I was talking of Microsoft specifically here. I was expecting Microsoft to promote a common internal code style, but apparently each team is free to decide their own code style. This just surprised me.

> This is incorrect. The part you are missing is the `assume` bit. Our tool does not `assume`. It `verifies`. If you havea `ToDateTime()` method that returns a `TimeSpan` our tool will say: you need to write that as `TimeSpan dt = x.ToDateTime()`. And it works that way for precisely this reason. Because the name of the method _is_ misleading. When it's not misleading, then we allow for `var` to be used.

I am not succeeding in explaining what I am trying to say. I am not missing the `assume` bit. I am of the view that the guidelines are for *humans*, not for *tools* and the analyzer tools are there to assist humans in following the guidelines.

I fully understand that the tool knows if `ToDateTime()`returns a `DateTime`.

But a human reading the line of code just as it is written can't tell what type `dt` is in `var dt = x.ToDateTime()` without **making the assumption** based on the name of the method, or knowledge about what tools have been used with what options to verify the style.

If the human *knows* that the source code has not been modified since the last time someone verified the code with the tool, and acted upon all suggestions, then it's a safe assumption. But only under those conditions.

You also talk about eco systems, I try to take a wider view and see what happens when code is viewed outside of it's original context of space or time. The thing is, that if I see a piece of code, without knowledge of it's history, what tools were used in verifying it etc, I'd like to be able to understand it at a glance.

I may be looking at the code in 10 years time, when the tools have been obsoleted and may no longer be available, the build process was lost 5 years ago and I have no idea what eco system it was part of.

If I read `DateTime dt = x.ToDateTime();` outside of it's original context that I may know nothing about I will *know* without making any assumptions at all, about names or about tools, what the type of `dt` is. I think that's a good thing.

In order to know the type of `dt` in `var dt = x.ToDateTime();` I, the human, have to make some assumptions. I think that's less desirable.

**Comment by CyrusNajmabadi** [comment]
> This just surprised me.

It falls out of what I said before. Different domains have different needs. We do not believe one size fits all.

**Comment by CyrusNajmabadi** [comment]
> But a human reading the line of code just as it is written can't tell what type dt is in var dt = x.ToDateTime() without making the assumption based on the name of the method, or knowledge about what tools have been used with what options to verify the style.

That is the point :-)

That's the idea and using the analyzers in the first place... :-)

Also note that when we actually checked the ecosystem on this, there was broad consensus that ToDateTime and ToString etc were all cases they were on with var on. Have you considered you're just in a very nice group here (and again that demonstrates why there's no one size fits all). 

Even if we made the rule how you wanted it, we'd then have the reverse problem of far more people complaining: why can't I use `var` with ToString. It's literally always a string. Everyone on our team/group/company knows this. And even if it read crazy and want a string, then we'd see that because the tool would force is to write it the full type. 

You are asking for a special handling of your needs while also stating there should be a consistent set for everyone. This is ultimately always incompatible, which is why at that point we suggest rolling your own solution :-)

**Comment by CyrusNajmabadi** [comment]
> I may be looking at the code in 10 years time, 

In 10 years time the language may be very different. `new X` may not return an X :-)

**Comment by CyrusNajmabadi** [comment]
> But only under those conditions.

Enough of the ecosystem thinks that's a fine assumption to make.  They turn on the rule and know that their vs/build/ci validates things. So they can trust looking at the code and saying they know what it means. 

That group far outweighs the group that goes: I can't trust any of this and I absolutely must be able to know with 100% certainty in all scenarios.  That view was absolutely can't to be too onerous (similar to the view that refactorings be 100% safe). 

We optimized the tools and scenarios here for the majority for better or worse.
