### ISSUE TITLE
Update How to install GPU support in Model Builder

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/docs#24837]
- Add / Update screenshots
- Review outdated content and update as necessary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0495cff9-97a6-68ba-504c-ec7fcbc69a9c
* Version Independent ID: 0c7c0298-37e3-f945-fee5-fc6ccd7a362d
* Content: [How to install GPU support in Model Builder - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-gpu-model-builder)
* Content Source: [docs/machine-learning/how-to-guides/install-gpu-model-builder.md](https://github.com/dotnet/docs/blob/main/docs/machine-learning/how-to-guides/install-gpu-model-builder.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by bszymik** [comment]
I think that one important info is missing, even if it may sound obvious - you need latest GPU drivers for GPU support to function.
CUDA installer will actually downgrade your GPU drivers - and in my case even if all the CUDA / cuDNN versions were correct (and probably GPU drivers also seems to be matching minimal requirements of CUDA but was downgraded) I was getting an error 
`Failed to get convolution algorithm. This is probably because cuDNN failed to initialize `

After upgrading to most recent drivers from NVIDIA - all started working fine

BTW
I spent hours on making sure that i have correct version of CUDA / cuDNN / Tensorflow and if all files were copied in correct place and if PATH contains all what should be there - upgrading GPU drivers finally resolved the issue

**Comment by luisquintanilla** [comment]
@jwood803 can you please take a look at this one. Thanks
