### ISSUE TITLE
Change C# 6.0 and Earlier to C# 6.0 and Later

### ISSUE THREAD

**Issue by zacharylayne** [dotnet/docs#24922]
Documentation indicates `is` keyword type tests only in C# 6.0 or earlier. This keyword was introduced in C# 6.0 and is available in later versions of the language.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778dcff2-db62-27d5-c0a2-35460e0d72f8
* Version Independent ID: 14ddc828-0812-3c14-60cf-9109bf3b8f7b
* Content: [is operator - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/is)
* Content Source: [docs/csharp/language-reference/operators/is.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/is.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by MSDN-WhiteKnight** [comment]
>This keyword was introduced in C# 6.0 and is available in later versions of the language.

No, this does not seem true. I can compile code that uses `is` type testing even when targeting version 3.0. And could probably use it in earlier versions, but a Visual Studio issue prevents me building a project targeting them. The docs correctly state that in C# 6.0 and earlier `is` can only be used for type testing, and then discusses pattern matching introduced in 7.0. 

We could consider removing "In C# 6 and earlier" part, because this feature is available in all versions and so it's simply not worth mentioning the earlier versions. The previous incarnation of this article (in keywords section) was like this:

>The `is` operator checks if the result of an expression is compatible with a given type, or (starting with C# 7.0) tests an expression against a pattern.

(https://github.com/dotnet/docs/commit/bf617fc82fa0e1d5e4b2d083a9a5e83e1a7c643a#diff-aeca2a318547349c1034f8d1ad906583c8769ca64ed70a1e68885ae90ca77e4d)
