### ISSUE TITLE
Semicolon placement

### ISSUE THREAD

**Issue by MichaelStett** [dotnet/docs#25178]
There is a semiclon moved to other line in Example.
```csharp
// Loop until the worker thread activates.
while (!workerThread.IsAlive)
    ;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d226514d-c7cb-0d1b-b9dc-fb791399dc47
* Version Independent ID: aa5d1078-7f89-98ce-7fdc-107c9ed3eebc
* Content: [volatile - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/volatile)
* Content Source: [docs/csharp/language-reference/keywords/volatile.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/volatile.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
:wave: Hi @MichaelStett 

That semicolon on the next line is intentional. The two lines of code show a spin-loop to wait for another thread to complete an operation. Placing the semicolon on the next line makes it stand out more so readers of the code will see that it's an intentional spin loop.

I'll close this as an answered question.
