### ISSUE TITLE
Following the instructions did not yield a service I could actually start. I had to invoke `UseWindowsService` on the `IHostBuilder` in `Program.CreateHostBuilder`.

### ISSUE THREAD

**Issue by stevenwbass** [dotnet/docs#25427]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed148088-4550-2788-0756-390eab15e3f6
* Version Independent ID: 64d5cdf8-e50f-0c89-7f16-82645ba6383e
* Content: [Create a Windows Service using BackgroundService](https://docs.microsoft.com/en-us/dotnet/core/extensions/windows-service)
* Content Source: [docs/core/extensions/windows-service.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/windows-service.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @stevenwbass - I'm sorry that you had a bad experience, but this step is right there in the article. You must have skimmed past this or something?

![image](https://user-images.githubusercontent.com/7679720/127862848-e484cc48-074a-4db3-9393-e72a95363b13.png)

To help improve its visibility I'm adding another heading to help with discoverability. Instead of being nested under the **Rewrite the Worker class** heading, it will be under a new heading called **Rewrite the Program class**.

**Comment by stevenwbass** [comment]
Ah, yes, I must have. Thank you!
