### ISSUE TITLE
Patterns pointers need to be more visible in switch expression page

### ISSUE THREAD

**Issue by michael-hawker** [dotnet/docs#25606]
Was trying to figure out how to use [Type patterns](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/patterns#declaration-and-type-patterns) for the `switch` expression. I started of course at the switch expression document, but didn't see the obvious case I was looking for. It's instead in the `Patterns` page which is only called out earlier amongst a sample here:

```
For information about the patterns supported by a switch expression, see Patterns.
```

And at the end in the related pages. It's not obvious that there's a ton of other samples for different ways to use the switch expression from the existing docs where there's so much more on the Patterns page.

I almost feel like these two pages should be combined, but at the least, it'd be cool if it was more prominently called out all the ways that one can use a switch expression and point to the patterns page for more details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd278c65-14fb-2c27-966d-6e14c74fbcaa
* Version Independent ID: e94a68f9-1a6c-a7e0-e1ee-4be1114bb8dc
* Content: [switch expression - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/switch-expression)
* Content Source: [docs/csharp/language-reference/operators/switch-expression.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/switch-expression.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@michael-hawker combining the two pages wouldn't be fair. The is expression and the switch statement also support all the patterns. That's why the patterns have their own dedicated page. Also, listing all the supported patterns on the switch expression page would create the duplicate content and, thus, would make it harder to maintain the docs. For example, once a new pattern is introduced, only one page should be updated now in the reference section of the docs (instead of additional three, one per each construct that supports patterns). I remember the times when this was the case, as a result, the docs were outdated.

However, I agree with you that the call to check the Patterns page can be more inviting. For example, 

> For list of supported patterns and more examples of the switch expression, see Patterns.

What do you think?

**Comment by BillWagner** [comment]
Thanks for providing such a detailed description of what you were seeking and why it was hard to find @michael-hawker 

I agree with @pkulikov that we'd like to keep the supported *patterns* in one page, and the statements and expressions that support patterns in a different location. It's also clear that we need to call this out more.

I like the suggestion above, but I'd add putting it in an `[IMPORTANT]` block to call more attention to it.

Thoughts?

**Comment by pkulikov** [comment]
@BillWagner I agree with you about emphasising that with the block.

**Comment by michael-hawker** [comment]
Thanks you too, appreciate the discussion. I understand there's a good distinction, so makes sense to have pages geared from the different perspectives. That's always useful to have too depending on how you're searching and what your entry point is.

🎉
