### ISSUE TITLE
The code on this page is broken.

### ISSUE THREAD

**Issue by im-a-lebowski** [dotnet/docs#25625]
There are problems with the DomainMapper being recognized in .NET 4.5 in Visual Studio 2017. The code, as it stands, has problems once the DomainMapper object is mentioned. The first try block is entirely non-functional as is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 202e3f9f-a12a-53de-9069-fd469e3dbebc
* Version Independent ID: fd3699bb-4881-b6b4-1275-43eed3d5f626
* Content: [How to verify that strings are in valid email format](https://docs.microsoft.com/en-us/dotnet/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format)
* Content Source: [docs/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format.md](https://github.com/dotnet/docs/blob/main/docs/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by IEvangelist** [comment]
Hi @im-a-lebowski,

The code is not broken. It is a C# 7 feature, and since you're using .NET 4.5 - it should work. Since you're using Visual Studio 2017, you'll need to add `<LangVersion>7.3</LangVersion>`.

See:

- https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version#defaults
- https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/local-functions
