### ISSUE TITLE
discover uninstalled template packs online

### ISSUE THREAD

**Issue by robrich** [dotnet/docs#2565]
`dotnet new --show-all` lists all the templates I've installed previously, but doesn't help me discover template packs I could install.  It doesn't even document the `-i` parameter to help me understand I could install templates.  What's a good way to discover template packs?  Perhaps we could add a cli command like `donet new --show-online` or similar.

**Comment by svick** [comment]
There is a Pull Request open that will add information about installing templates (https://github.com/dotnet/docs/pull/2495), including a link to [Available templates for dotnet new](https://github.com/dotnet/templating/wiki/Available-templates-for-dotnet-new). Since installing templates is new in .Net Core SDK 2.0, which hasn't been released yet, the current documentation does not contain that information yet.

@GuardRex Should the link to "Available templates" be added to the main `dotnet new -i` documentation, instead of being hidden in the "Creating templates" article? It's useful for people wanting to use templates, not just for those who want to create them.

@robrich If you want to discuss how the documentation should look like, the you're in the right place. If you want to discuss or propose changes to `dotnet new` itself, then the right repository is either [dotnet/cli](https://github.com/dotnet/cli/) or [dotnet/templating](https://github.com/dotnet/templating/).

**Comment by GuardRex** [comment]
@robrich They included the `-all|--show-all` option in a group of ["hidden" arguments](https://github.com/dotnet/templating/blob/rel/vs2017/3-Preview3/src/Microsoft.TemplateEngine.Cli/CommandParsing/CommandParserSupport.cs#L133-L152); and on my first pass for the 2.0 updates, I left it in the topic. They setup the `-l|--list` option to list all of the templates installed on a system. I'm going to check with them and see what's what with this *secret* group of options and find out if none of them should be covered or if I should cover all of them. Yes, I agree you should open your request for a behavior change or a new feature to show online templates in the [dotnet/templating issues](https://github.com/dotnet/templating/issues).

The `-i|--install` option is new for 2.0, which hasn't released yet. That one will be covered when the PR that @svick mentioned is merged. Yes, @svick, that's a great idea to copy both of those links that lead to available template lists to the `dotnet new` topic. I'll update that PR now. :+1:

**Comment by mairaw** [comment]
documenting the -i flag is being tracked with issue #2405

@mlorbetske, @sayedihashimi can you comment on this request? should we just move to https://github.com/dotnet/templating/issues?

**Comment by sayedihashimi** [comment]
We don't have support to discover templates in the command line yet. I've created an issue to support this at https://github.com/dotnet/templating/issues/1084.

FYI for the time being, I have a nightly build that runs to search for templates on nuget.org. You can see the results at https://ci.appveyor.com/project/sayedihashimi/sayed-tools-w3a48.
I'd like to see if we can create a website around that for users.

**Comment by robrich** [comment]
https://github.com/dotnet/templating/issues/1084 looks like the right place to continue the "discover template packs" discussion, and https://github.com/dotnet/docs/issues/2405 documents `-i`.  Closing this issue here.
