### ISSUE TITLE
Option is incorrectly mentioned in the Get a list of installed templates section

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/docs#25650]
In the Get a list of installed templates section, the option mentioned corresponds to uninstalling the template `-u`, kindly update it to the right option of listing `-l`.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e7deb06-37bb-b659-7cf3-9c47a91e065e
* Version Independent ID: d6e6f989-3956-6a0e-5e9c-fb3d1f9bd751
* Content: [Custom templates for dotnet new - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates)
* Content Source: [docs/core/tools/custom-templates.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/custom-templates.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @adegeo
* Microsoft Alias: **tdykstra**

**Comment by adegeo** [comment]
Hello @egvijayanand The `-u` uninstall command lists the template packs you can uninstall, including the ID of the pack. The `-l` command lists the templates you can use, individually and isn't enough information to uninstall a template.

In this case the documentation is demonstrating how to see the template information so that you can uninstall it.
