### ISSUE TITLE
CA1822 docs *might* be incorrect.

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#25824]
The rule description:

> Members that do not access instance data or call instance methods can be marked as static (Shared in Visual Basic). After you mark the methods as static, the compiler will emit nonvirtual call sites to these members. Emitting nonvirtual call sites will prevent a check at run time for each call that makes sure that the current object pointer is non-null. This can achieve a measurable performance gain for performance-sensitive code. In some cases, the failure to access the current object instance represents a correctness issue.

I'm interpreting this as if the code violating this rule has *callvirt* IL instruction, which doesn't seem correct. The benefit seems like only saving a `ldarg` instruction.

```csharp
using System;
public class C
{
    public void M()
    {
        Static(); // IL code for that: call void C::Static()


        Instance(); // IL code for that:
        // ldarg.0
        // call instance void C::Instance()


        InstanceVirtual(); // IL code for that:
        // ldarg.0
        // callvirt instance void C::InstanceVirtual()
    }
    
    internal static void Static() => Console.WriteLine();
    internal void Instance() => Console.WriteLine();

    // No violation here. The analyzer intentionally bails out
    // for virtual methods to reduce false positives.
    internal virtual void InstanceVirtual() => Console.WriteLine();
}
```

Anything I'm missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2289e13-c2dd-ab47-7306-f67e618b4861
* Version Independent ID: 4458b59e-495d-6a5b-b479-fe69c5acf91e
* Content: [CA1822: Mark members as static (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1822)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1822.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca1822.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by MSDN-WhiteKnight** [comment]
>I'm interpreting this as if the code violating this rule has callvirt IL instruction, which doesn't seem correct.

It is correct technically. The C# compiler could emit callvirt instruction when calling non-virtual instance method. In your example the compiler is smart enough to determine that this is not needed, because you are invoking the method on `this` ref, which is never null. But if you were invoking on the symbol that could potentially be null, the compiler would emit a callvirt instruction. This is the case even on such code:

```
C c = this;
c.Instance();
```

`c` can't be null, but the compiler does not take advantage of it, and still emits callvirt.

The rule is not only about the case where we are calling the method from the same class and calls to instance and static methods look the same. In general case i think it's still worth mentioning that compiler could emit virtual call.

**Comment by Youssef1313** [comment]
Thanks for clarifying!

**Comment by Youssef1313** [comment]
I think there is no action needed here as the docs is accurate. Closing.
