### ISSUE TITLE
Demonstrate Inline Initialization

### ISSUE THREAD

**Issue by ardalis** [dotnet/docs#26096]
This example fails to demonstrate how to initialize properties and fields in their definition:

```
public class Person
{
    // Constructor that takes no arguments:
    public Person()
    {
        Name = "unknown";
    }

    // Constructor that takes one argument:
    public Person(string name)
    {
        Name = name;
    }

    // Auto-implemented readonly property:
    public string Name { get; }

    // Method that overrides the base class (System.Object) implementation.
    public override string ToString()
    {
        return Name;
    }
}
```

Instead of, or in addition to, initializing `Name` in the default constructor, the preferred approach would be to initialize it where it is defined. The whole class would then look like this:

```
public class Person
{
    // Constructor that takes one argument:
    public Person(string name)
    {
        Name = name;
    }

    // Auto-implemented readonly property with default value assigned:
    public string Name { get; } = "unknown";

    // Method that overrides the base class (System.Object) implementation.
    public override string ToString()
    {
        return Name;
    }
}
```

I just had a student question why this doc doesn't demonstrate the preferred approach - initialization where declared - so I'd like to see the doc updated to reflect it. I assume there's general consensus that this is the preferred approach but if not here are some reasons to prefer it:

- Less code
- More readable code
- It's obvious whether or not a given property has a default value without having to look elsewhere in the code (e.g. ctor)

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63989d15-db4e-9873-2cf7-77634496fe4e
* Version Independent ID: cd6c869c-fcc9-eb27-4ec0-94cb1e961a88
* Content: [Classes](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/types/classes#example)
* Content Source: [docs/csharp/fundamentals/types/classes.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/types/classes.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 92292](https://dev.azure.com/msft-skilling/Content/_workitems/edit/92292)

**Comment by BillWagner** [comment]
Hi @ardalis 

I'll keep this open, because we can improve this sample.

The suggestion isn't the preferred approach though. By removing the parameterless constructor, you can't create a `Person` without providing an argument for `name`. 

One alternative might be the following:

```csharp
public class Person
{
    // Constructor that takes no arguments:
    public Person() : this("unknown") {}

    // Constructor that takes one argument:
    public Person(string name)
    {
        Name = name;
    }

    // Auto-implemented readonly property:
    public string Name { get; }

    // Method that overrides the base class (System.Object) implementation.
    public override string ToString()
    {
        return Name;
    }
}
```

That version doesn't demonstrate the field initializer, and I'm not sure its more readable.

Finally, there are potential performance implications to initializing a member in a field initializer and also in a constructor. In the `Person` example the affect is minor, but if both the field initializer and constructor allocate sizable amounts of memory, that will impact performance. While that's a micro-optimization that should be measured before considering, we don't want to actively encourage the opposite pattern without more explanation.

I'll keep this in the backlog to address when we next update the fundamentals section.

**Comment by ardalis** [comment]
If you need a parameterless constructor in my version you would just add:

`public Person() {}`

and everything would behave as intended, no?

I agree with your other points but the reason to prefer field initializers is to eliminate the common bug in which fields/properties are not initialized properly. This is much harder to detect when the initialization is separate from the definition (and in this case, very separate, not just on a neighboring line).

If nothing else, they probably bear mentioning, perhaps along with your considerations.

Cheers
