### ISSUE TITLE
COR Library?

### ISSUE THREAD

**Issue by silkfire** [dotnet/docs#26285]
What is this mysterious **COR Library** you're referring to on this page and a few other Roslyn-related pages? Googling the term only redirects the user to the same MS Docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b74a970-ecb9-d883-84a6-0369d38e812a
* Version Independent ID: ab4f1d9b-96c8-7d35-6c5e-2b1547e7adb7
* Content: [Compilation.CreateArrayTypeSymbol Method (Microsoft.CodeAnalysis)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.compilation.createarraytypesymbol?view=roslyn-dotnet-3.11.0)
* Content Source: [dotnet/xml/Microsoft.CodeAnalysis/Compilation.xml](https://github.com/dotnet/roslyn-api-docs/blob/live/dotnet/xml/Microsoft.CodeAnalysis/Compilation.xml)
* Product: **dotnet-roslyn-api**
* Technology: **microsoft.codeanalysis**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by MSDN-WhiteKnight** [comment]
It is documented in the source comments: https://github.com/dotnet/roslyn/blob/main/src/Compilers/CSharp/Portable/Symbols/AssemblySymbol.cs#L47

>The system assembly, which provides primitive types like Object, String, etc., e.g. mscorlib.dll.

I believe in roslyn you never need to bother about corlib. It is always determined automatically (first referenced assembly containing System.Object). That's why this property is internal. Some doc comments leak this implementation detail, but it's not a big deal.

**Comment by silkfire** [comment]
Thanks. Now I understand that the COR part stands for **Common Object Runtime**. https://stackoverflow.com/questions/15061977/what-does-mscorlib-stand-for
