### ISSUE TITLE
"Reference Tracker framework" link leads to 404

### ISSUE THREAD

**Issue by sonicbhoc** [dotnet/docs#26387]
The [Reference Tracker framework](https://docs.microsoft.com/en-us/windows/win32/api/windows.ui.xaml.hosting.referencetracker/) link  in [Step 1 of the tutorial](https://docs.microsoft.com/en-us/dotnet/standard/native-interop/tutorial-comwrappers#step-1--define-methods-to-implement-and-understand-their-intent) leads to a 404 page. It seems to be a typo; The link should be microsoft.ui.xaml.hosting.referencetracker, but it says windows.ui.xaml.hosting.referencetracker instead.

I think it might help to give a little context in the text leading up to the link too, since there is no hint as to _what_ the Reference Tracker framework is or what tools use/need/implement it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1316676-9418-3418-d9fb-4114ff178700
* Version Independent ID: 50d9ac5f-ea31-0663-2ab4-993cd0d39ec0
* Content: [Using the ComWrappers API](https://docs.microsoft.com/en-us/dotnet/standard/native-interop/tutorial-comwrappers)
* Content Source: [docs/standard/native-interop/tutorial-comwrappers.md](https://github.com/dotnet/docs/blob/main/docs/standard/native-interop/tutorial-comwrappers.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @AaronRobinsonMSFT
* Microsoft Alias: **jekoritz**

**Comment by AaronRobinsonMSFT** [comment]
@sonicbhoc Thanks for reporting the broken link. As far as what it is that is intentional. The idea being if it is known API then it will be implemented otherwise it is an unknown and can be ignored. Perhaps one could mention it is for WinRT, but then we get into the complexity around "I want to support WinRT" but that gets more complicated because that is just the current consuming client and not the only possible client. I struggle to provide details more than simply the name. Do you have a suggestion on what would be helpful?

**Comment by sonicbhoc** [comment]
@AaronRobinsonMSFT I don't have a particular suggestion. Thank you for responding and fixing it so quickly, though.
