### ISSUE TITLE
Is the Collections guidelines page out of date?

### ISSUE THREAD

**Issue by SteveDunn** [dotnet/docs#26464]
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/guidelines-for-collections?source=docs

... says to prefer to return concrete read-only collections, e.g. `ReadOnlyCollection<T>` instead of `IReadOnlyCollection<T>`:

> ✔️ DO use ReadOnlyCollection<T>, a subclass of ReadOnlyCollection<T>, or in rare cases IEnumerable<T> for properties or return values representing read-only collections.

Following Postel's Law:
> "be conservative in what you send, be liberal in what you accept"

... the concrete type **is** more conservative than the interface, but does this trump 'prefer abstractions over concretes'?

Even if it is deemed by concensus that the this rule still holds, maybe a paragraph is required to show that the alternative has been considered.

**Comment by gewarren** [comment]
These guidelines are reprinted from a 2008 book, so unfortunately we can't change what's written. But it might be possible to add a note to the top of the page. @dotnet/docs Thoughts on this?

**Comment by MSDN-WhiteKnight** [comment]
What are concrete advantages of using IReadOnlyCollection? It's just IEnumerable with Count property attached to it, it does not provide an item indexer like ReadOnlyCollection. So it's not a full replacement for cases where ReadOnlyCollection is used today. Also, ReadOnlyCollection is implicitly convertible to IReadOnlyCollection anyway, so it does not hurt people who want to use abstractions. 

Maybe [IReadOnlyList](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.ireadonlylist-1?view=net-5.0) would be more suitable modern replacement, but i don't think it's worth changing guidelines at this point. While guidelines are old, changing them could create inconsistency between older and newer APIs. Changing guidelines is good for new substantial language features, such as async/nullable. There it's better to not touch what appears to work good.

**Comment by JulianBirch** [comment]
I mean, I've already provided a couple of examples where the advice is actively bad? e.g. configuration

Sometimes you'll want `IReadOnlyCollection`, sometimes `IReadOnlyList`. In general terms you want interfaces to reveal as little of their implementation details as possible, whilst still being useful for clients. e.g. a HashSet can be an IReadOnlyCollection and that might be a completely acceptable return value.

**Comment by MSDN-WhiteKnight** [comment]
>I mean, I've already provided a couple of examples where the advice is actively bad? e.g. configuration

I'm not enough familiar with that library to understand why it's bad. It seems i can implement IConfiguration interface without any need of IReadOnlyCollection. Its method return IEnumerable, where exactly IReadOnlyCollection could be used?

**Comment by SteveDunn** [comment]
> > I mean, I've already provided a couple of examples where the advice is actively bad? e.g. configuration
> 
> I'm not enough familiar with that library to understand why it's bad. It seems i can implement IConfiguration interface without any need of IReadOnlyCollection. Its method return IEnumerable, where exactly IReadOnlyCollection could be used?

The implementation of `System.Configuration` binds config to properties. If the config is a collection, and the field on a class is `IEnumerable` (or derived), then it picks a collection to use and populates the field.  If it is a concrete read-only collection, then it silently ignores it.

**Comment by EnricoMassone** [comment]
Another interesting point is that there is no mention of immutable collection types (e.g.: [`ImmutableList<T>`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutablelist-1?view=net-7.0)) in the Collections Guidelines page. 
These types are becoming more and more popular in the .NET community. Some guidelines on their usage could be really helpful.

**Comment by nivomi** [comment]
We're coming up on the two year anniversary of this issue - if the bad advice is still coming up as a top result on search engines, etc., and cannot be edited... wouldn't it be prudent to remove the article and replace it with a simple redirect to something like https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/collections? At the moment, and for the last 2 years+, this bad advice that's indistinguishable from any other documentation has just been left to fester and mislead.

**Comment by MSDN-WhiteKnight** [comment]
>if the bad advice is still coming up as a top result on search engines

I still don't see a valid argument why using ReadOnlyCollection is bad advice. I get that configuration binder does not support it, but this guidelines for public APIs, not for types used for configuration. While some of Framework design guidelines are indeed outdated, this particular page is completely OK.

**Comment by JulianBirch** [comment]
The text is written in a context where the modern alternatives had yet to be developed. At the time, this was the only way to represent a collection that the receiver could not change. I'd argue that ReadOnlyCollection has now been superseded by many more modern features:
* `IReadOnlyCollection` (doesn't create a new object, achieves same effect, more flexible implementation, easier to mock)
* `FrozenList` (faster lookups)
* `ImmutableList` (better for subsequent updates, thread-safe, backtracking)

The fact that it's incompatible with other BCL APIs just underlines the point that it's been superseded.

In the context of a public API, I'd argue `IReadOnlyCollection` is probably the default choice, but the other two have their place. I don't think there's _anywhere_ I'd favour `ReadOnlyCollection`.

**Comment by piskov** [comment]
@JulianBirch, @SteveDunn, @nivomi there are perfomance and safety implications which are all in favor of `ReadOnlyCollection`.

If we return `IReadOnlyCollection`, nothing prevents us from casting it back. But`ReadOnlyCollection` is trully unmodifiable as it’s a wrapper.

As for performance, consider this code:

```
private static void EnumerateCollection(IReadOnlyCollection<string> items)
 // or any other interface like IEnumerable
{
    foreach (var item in items)
    {
    }
}
```

Congratulations, we got ourselves boxing of enumerator and unnecessary memory allocation because of that. If instead we use concrete type (like `ReadOnlyCollection`, sic the missing `I`), we don’t allocate as the enumerator in List, Dictionary and other collections is value typed.

In addition to boxing the enumerator, the MoveNext and Current calls made per element go from being potentially-inlineable non-virtual calls to being interface calls. That interface dispatch immediately subjects us to 2…3× perfomance degradation.

Both of these things we would escape if used `ReadOnlyCollection` that is recommended in that “omg almost 20 year old” article :-)

> `IReadOnlyCollection` (doesn't create a new object, achieves same effect, more flexible implementation, easier to mock)

No new object, but 20(?) bytes will be allocated _each and every_ time you would try to enumerate + slower performance due to interface dispatch (don’t forget about GC of that allocations). And it doesn’t prevent you from casting back to say `List` and modify it all you want. So not exactly the “same effect”, would you agree?


> `FrozenList` (faster lookups)

There is no such thing (only FrozenDictionary and FrozenSet). As for frozen collections it’s more for long-live stuff due to creation time. Even with .net 8 frozen* creation improvements, `AsReadOnly` to create `ReadOnlyCollection` or `ReadOnlyDictionary` is O(1) operation (just a wrapper).

> `ImmutableList` (better for subsequent updates)

The current context is for `read-only` collections. ImmutableList is a bad name as it’s more about persistent collection optimized for copying. As for modifying the collection, it’s very hard to say it’s better for subsequent updates, as adding an element in `ImmutableList` is `O(log n)` operation. As is getting item by index from that list (as it has a tree as backing field instead of an array). Whereas both are `O(1)` in ordinary list. So unless you are copying a list in a loop (which would be `O(N²)` vs still `O(log n)`), ImmutableList  is rather specific option for very specific cases.

—

That said `ReadOnlyCollection` and `ReadOnlyDictionary` are here for a reason. They truly don’t allow outsiders to change the collection, they don’t allocate in foreach (compared to interface-based alternative like `IReadOnlyCollection` or `IEnumerable`), have concrete type that avoids interface dispatch, and are as fast to create in `O(1)` as they are just a wrapper.

Thus, @gewarren that page in question is absolutely not out-of-date regarding its advice even so many years later :-)
