### ISSUE TITLE
Revise Building Docker Images for .NET Core Applications Topic

### ISSUE THREAD

**Issue by JRAlexander** [dotnet/docs#2652]
# Revise Building Docker Images for .NET Core Applications Topic

This page needs to be revised: [Building .NET docker Images](https://docs.microsoft.com/en-us/dotnet/articles/core/docker/building-net-docker-images)

This will take the place of Issue #2035 - Update .NET Core Docker Doc 

## Needed Revisions
- [x] Move to the .NET Guide in the Table of Contents
- [x] Change Title to "Introduction to .NET and Docker"
- [x] Revised Outline
   - [x] Introduction
      - [x] What is Docker? 
      - [x] Further Reading.
    - [x]  .NET Docker Images
       - [x] Scenario Based Guidance
           - [x] Explain different OS base images better. Link to more Docker documentation on the different Docker clients (Mac, Linux, Windows).
       - [x] Cover scenarios: .net core, .net fx, aspnet core, aspnet fx, wcf, iis
       - [x] Interact with other msft stack images: mssql, vsts-agent, oms, azure-cli, etc. 
         - [x] Add multi-stage build explanation for using both sdk and runtime images in Dockerfile
    - [x] Explore the Rich Docker ecosystem. Link to microservices doc.
    - [x] Further Reading on .NET Core images: production, development/build explanations. 
        - [x] Add links to aspnetcore images.
        - [x] Provide links at bottom for related .NET Framework images doc
- [x] Develop with Docker
       - [ ] Describe what gaps our tools bring to developing with Docker
       - [ ]  Debug through a container in VS! Link to P2 tutorial.
      -  [ ] Getting Started with Docker and VS4Mac

Note: Consider splitting Image documentation into a separate doc than VS Code and Docker use.

**Comment by mairaw** [comment]
@JRAlexander we got a comment on the topic "Just wasted 30 minutes trying this, there should be a warning or something at the beginning showing what versions are supported, my project its using the 2.0 preview and after "yo aspnet" the app didn't start"

while we work at this, should we just put a warning on top that the topic hasn't been updated for 2.0 yet?

**Comment by ibqn** [comment]
are there any updates of the progress here?

**Comment by kaabahmed10p** [comment]
Do we have any ETA for this task?

**Comment by JRAlexander** [comment]
@kaabahmed10p - I am working on it now and intend to have it finished within the next few days.

**Comment by kendrahavens** [comment]
Let's remove the "What is Docker topic?" this can be found and linked to from [https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/container-docker-introduction/docker-defined](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/container-docker-introduction/docker-defined). @JRAlexander If you've already started on it it may be helpful to do a PR to help expand/update that doc.

I think we should expand "Further Reading on .NET Core images: production, development/build explanations" by contributing here [https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/net-core-net-framework-containers/official-net-docker-images](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/net-core-net-framework-containers/official-net-docker-images). I think our .NET and Docker blog post has more helpful details on this that can be added.

There is also already a doc on [debugging through a container in VS](https://docs.microsoft.com/en-us/dotnet/core/docker/visual-studio-tools-for-docker) so we can take that off the list. Also, this is very outdated [https://docs.microsoft.com/en-us/dotnet/framework/docker/console](https://docs.microsoft.com/en-us/dotnet/framework/docker/console) I'd like to retire it and link to the [debugging through a container in VS](https://docs.microsoft.com/en-us/dotnet/core/docker/visual-studio-tools-for-docker) doc.

I think Maira brought up a good point in the other PR. We should definitely see if these topics now exist since the time we identified the need for them. We may simply need to update some and provide good links to help visibility. I did search for these topics when helping develop the list, but I might have been searching in the dotnet docs only and not in the global Microsoft doc search. Looks like that turns up more docs overlapping here.

**Comment by jdk339** [comment]
How's the progress here? I still cannot figure out how to get an app on .NET Core 2.0 to run properly in Docker. These docs would be much appreciated.

**Comment by kaabahmed10p** [comment]
I was able to build an image for deployment using this URL: https://docs.docker.com/engine/examples/dotnetcore/

**Comment by Vlaaaaaaad** [comment]
I got excited when this got updated, but there is yet another issue.

The recommended image to use, `microsoft/dotnet:2.0-sdk`  fails with `/app/docker-compose.dcproj : error MSB4236: The SDK 'Microsoft.Docker.Sdk' specified could not be found.` as per https://github.com/dotnet/cli/issues/6178 .

Any plans to fix this? I don't find it ok for the official documentation to recommend failing images. At least a note to the https://github.com/dotnet/cli/issues/6178 should be added.
