### ISSUE TITLE
Apphost and global tools

### ISSUE THREAD

**Issue by matkoch** [dotnet/docs#26739]
@gewarren 

Could you please clarify what should be done for publishing of global tools? My global tool was targeting a bunch of TFMs including `netcoreapp2.1`, `netcoreapp3.1` and `net5.0`. What exactly is the outcome if I set `UseAppHost` to `false` ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 283b1820-abb9-9d7a-0bdd-9e7548f00d13
* Version Independent ID: a5e86b2b-6b6f-e9d8-2336-bab99fbec77b
* Content: [Breaking change: Generate apphost for macOS - .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/sdk/6.0/apphost-generated-for-macos)
* Content Source: [docs/core/compatibility/sdk/6.0/apphost-generated-for-macos.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/sdk/6.0/apphost-generated-for-macos.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mateoatr Could you answer this question?

**Comment by mateoatr** [comment]
Taking a quick peek at the CLI's tool code in https://github.com/dotnet/sdk and playing with the [dotnetsay](https://github.com/dotnet/core/tree/main/samples/dotnetsay) sample, it looks like `dotnet tool install` will create an apphost regardless of `UseAppHost` value and place it in `~/.dotnet/tools/.`. Of course, when locally debugging, this controls whether you get an executable or not when building.

/cc @vitek-karas @sfoslund

**Comment by vitek-karas** [comment]
The change described in this breaking change is only about `dotnet build`/`dotnet publish` which didn't generate an apphost on macOS, now it does. Setting `UseAppHost` to `false` will disable this and build will not produce the executable.

`dotnet tool install` should generate an executable, it has to in order to support running the tool via its name  -for example `dotnet-format`. Otherwise the only way to run the tool would be to use the muxer `dotnet dotnet-format` (I think).
