### ISSUE TITLE
Import or Using in the csproj file?

### ISSUE THREAD

**Issue by aktxyz** [dotnet/docs#26752]
I tried the following line from this page to add a namespace to the implicit using list ...

`<Import Include="System.IO.Pipes" />`

and that did not seem to work.  Googling around I found another tag name that did work

`<Using Include="System.IO.Pipes" />`

https://dotnetcoretutorials.com/2021/08/31/implicit-using-statements-in-net-6/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40c80da1-37e3-efc4-5208-4ef4c4d84cfd
* Version Independent ID: bcf66f2a-bd70-ea8c-e9f0-198c897a8634
* Content: [Breaking change: Implicit `global using` directives in C# projects - .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/sdk/6.0/implicit-namespaces)
* Content Source: [docs/core/compatibility/sdk/6.0/implicit-namespaces.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/sdk/6.0/implicit-namespaces.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Thanks @aktxyz. It's a little confusing because there were two separate breaking changes - one for Preview 7 and another one for RC 1. `<Import>` worked for Preview 7, and `<Using>` works for RC 1 and later versions. See https://docs.microsoft.com/en-us/dotnet/core/compatibility/sdk/6.0/implicit-namespaces-rc1 for the RC 1 changes.

I've created PR #26756 to hopefully make this less confusing.
