### ISSUE TITLE
application settings app.config / appsettings.json console and desktop apps

### ISSUE THREAD

**Issue by figuerres** [dotnet/docs#26769]
what kind of crazy drugs were used ?
with .net we had the xml app.config file and that has worked fine.

and i am ok with moving to json but what i am not ok with is now the settings has turned into a huge mess.....
i dont want to spend all day just to figure out how to do this!   
so why even go to the new json?
and how ?
and i find so many links that assume i need to do it in a web app.... what about desktop and console apps ?

this is one area that the new .net 6  and 5 and core have just made a mess of things....

can we please have a simple way to do settings for non web apps ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b458a209-339d-e896-4e85-6d1c6a7aa1f9
* Version Independent ID: 0d5de37c-8f89-b6a5-3132-2c5214196bfd
* Content: [Configuration in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/configuration)
* Content Source: [docs/core/extensions/configuration.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/configuration.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @figuerres

Thank you so much for posting this issue. We really appreciate all feedback. This documentation is the workload agnostic content that you're looking for. It's applicable to all modern .NET workloads, not just web.

With that said, what can I do to make this content easier to consume? How can I teach you these newer concepts, what would you like to see differently? I'm happy to help and always looking for ways to improve how these concepts are conveyed. From what I gather you're coming from .NET Framework, and you're used to the static `ConfigurationManager` world of things where you were limited to just XML.

Is that right? You can still use XML. But instead of having a static object for configuration, you'd have to either access configuration values from the `IConfiguration` or the strongly-typed `IOptions<TOptions>` interfaces. This was a major change, in that dependency injection is the focus  instead of relying on static global state. Is that helpful?

**Comment by figuerres** [comment]
also going back to the page this came from it shows an async task main etc....
but the new dot net 6 console app template does none of that.
and that host builder stuff   .... seems like its more for web hosting then for a console app.....

also confusing is the structure i see

it sys to create a host builder 

then put code here

then await host.RunAsync();

what ???    that just does not read clear, seems like my code is in the wrong place and i have no idea why its stuck there....

maby this old head is starting to get this but it looks like a bunch of code that was never needed before ....  and this doc does not match the new console template used by the new vs 2022 .....

**Comment by figuerres** [comment]
given:

` static async Task Main(string[] args)
        {
            using IHost host = CreateHostBuilder(args).Build();

            // Application code should start here.

            await host.RunAsync();
        }`

please show how at the // Application code should start here.  i would access the settings in my code ??  i have not found any example of that so far.

**Comment by figuerres** [comment]
please see here, sorry i did not post it here...

https://github.com/dotnet/docs/issues/26779

**Comment by IEvangelist** [comment]
Hi again @figuerres

I see what you posted in #26779. I've copied and formatted it here:

```csharp
static void Main(string[] args)
{
    IConfiguration config =
        new ConfigurationBuilder().AddJsonFile("appSettings.json")
            .Build();
    Settings options = new();
    config.GetSection(nameof(Settings)).Bind(options);
}
```

This will get you a `Settings` instance bound to the configuration section from the corresponding JSON configuration provider values, sure; but this is really an anti-pattern. When you use the generic host (which is not web specific, but rather workload agnostic) it will manage this for you, as well as provide many other conveniences, such as dependency injection. Instead of instantiating a `Settings` instance yourself and manually binding to to configuration, the framework will do it for you. This works too:

```csharp
static void Main(string[] args)
{
    using IHost host = Host.CreateDefaultBuilder(args).Build();

    // The options.Value below is your Settings object instance. 
    var options = host.ServiceProvider.GetRequiredService<IOptions<Settings>>();

    host.Run();
}
```

> NOTE: I removed the `async Task` returning `Main`. That was a feature added in C# 7.3 I believe, and it allows for the main entry point of the application to be asynchronous, which is awesome.

Doing it this way instead, you're not limited to JSON; and you'll have the ability to use the monitor capabilities where you can get change notifications when the underlying configuration changes. There are many other benefits, knowing that you're coming from .NET Framework 4.X to .NET 6 - there is a lot that has changed. I highly recommend reading through the following content as it is at the core of all modern .NET workloads:

- [Configuration providers in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/configuration-providers)
- [Options pattern in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/options)
- [Dependency injection in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection)
- [Logging in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/logging)
- [.NET Generic Host](https://docs.microsoft.com/en-us/dotnet/core/extensions/generic-host)

**Comment by figuerres** [comment]
first THANK YOU! that one line was just not in anything i saw about how to have the host object return my settings!

also as a side note: for over 2 years i was using Async and Task but i was using it with Web API and OData and Angular 2
i have never used it with a console app before.
that plus all the searches kept talking about settings for web apps just had me wondering if the new appsetting.json was for asp.net and not for the rest of the world.

I have seen a lot happen with  software, when i started it was DOS and C and the old old VB.
some days i see changes that are great and others i wonder if they are going backwards or sideways....

**Comment by figuerres** [comment]
well the story is not over yet...

i am not able to use that code...   

first what vs 2022 reported is that IHost does not have .ServiceProvider
it does have .Services.GetService<IOptions<Settings>>(); but that gives me no settings values...

for now i will use what is working for me, if you can find out what is going on and have some working code i will be interested. 

please test it with .net 6   in a console app.

**Comment by IEvangelist** [comment]
What about this:

_Program.cs_

```csharp
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

var host = Host.CreateDefaultBuilder(args)
    .ConfigureServices((context, services) =>
    {
        services.AddOptions();
        services.Configure<Settings>(
            context.Configuration.GetSection("Settings"));
    })
    .Build();

var logger = host.Services.GetService<ILoggerFactory>();
var options = host.Services.GetService<IOptions<Settings>>();
var setting = options?.Value;

var log = logger?.CreateLogger("Program");
log?.LogInformation(
    "Settings {{ Name = {Name}, Number = {Num}, TrueOrFalse = {Bool} }}",
    setting?.Name, setting?.Number, setting?.TrueOrFalse);

host.Run();
```

_Settings.cs_

```csharp
public class Settings
{
    public string? Name { get; set; }
    public int Number { get; set; }
    public bool TrueOrFalse { get; set; }
}
```

_appsettings.json_

```json
{
    "Settings": {
        "Name": "Does thing work?",
        "Number": 7,
        "TrueOrFalse": true
    }
}
```

_ConsoleApp7249.csproj_

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="appsettings.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.0-rc.2.21480.5" />
  </ItemGroup>

</Project>
```

Running this yields the following output:

```
info: Program[0]
      Settings { Name = Does thing work?, Number = 7, TrueOrFalse = True }
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\dapine\source\repos\DotNetSix.Console\DotNetSix.Console
```

**Comment by schh** [comment]
Has there been any impårovements in .net 6 for console / desktop apps as far as developer specific appsettingsfiles? that is prefereably it should simply work the same a s a webapp, the only info ive found is that you have to add these nevironment specific files using preprocessor directives, ignoring them in git etc. This is pretty clnuky and not very intuitve. It should work the same as a webapp.
