### ISSUE TITLE
The documentation on this page does not sufficiently explain the solution

### ISSUE THREAD

**Issue by samsmithnz** [dotnet/docs#26839]
The documentation on this page does not sufficiently explain the solution. There should be examples. This seems to break a lot of projects that worked with .NET 5, and the article doesn't explain how to resolve. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 655dd674-cbb3-2a90-a49c-8eaad8ee4fc9
* Version Independent ID: 99c3d060-f719-4d71-7851-08818e440384
* Content: [Breaking change: Generate error for duplicate files in publish output - .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/sdk/6.0/duplicate-files-in-output)
* Content Source: [docs/core/compatibility/sdk/6.0/duplicate-files-in-output.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/sdk/6.0/duplicate-files-in-output.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@sfoslund or @dsplaisted Can you comment on this question? It seems like there are still some open issues related to this, for example, https://github.com/dotnet/sdk/issues/15748 and https://github.com/dotnet/sdk/issues/20482.

**Comment by sfoslund** [comment]
@samsmithnz does the [recommended action](https://docs.microsoft.com/en-us/dotnet/core/compatibility/sdk/6.0/duplicate-files-in-output#recommended-action) section answer your question? There isn't a way to give a general example of how to avoid situations where this error occurs, since it's very dependent on your build set up, but the workaround is linked in that section as well, you can set[ ErrorOnDuplicatePublishOutputFiles to false ](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#erroronduplicatepublishoutputfiles)

**Comment by beleester** [comment]
The only recommended action, besides disabling the error message, is "Avoid situations where multiple files with the same name are copied to the publish output."  That's it.  It's completely useless - it's like I went to the doctor, explained my symptoms, and he nodded sympathetically and said "Have you tried not getting sick?"

Nobody needs to be told "avoid situations where you get errors."  If someone is looking for help with an error message, it means they are *already* in the situation that causes the error and they want help getting *out* of it.  What action should you be taking?  How can you get more information on what's wrong?  What sort of things in the build configuration might cause the same file to be copied more than once?

When I got this error, it turned out to be because I had a DLL marked as "Copy to Output Directory," so it got copied once because it was a required library, and a second time because I specified it should be copied.  So maybe a good first step in resolving it would be "Look at the error message, see which file is getting copied twice, and look at its properties."

**Comment by samsmithnz** [comment]
Second what beleester has just said. Additionally, the docs are not written in an inclusive way - they are written by an expert .NET developer who understands the cause and resolution explicitly. 

Note: in my situation, I had an ASP.NET website that referenced a class in an ASP.NET web service - to access some properties in a model. Not ideal, but it was a small thing that I didn't want to create an entire new models project for. The conflict was caused by both of them having an appsettings.json file.

**Comment by dsplaisted** [comment]
Thanks for the feedback folks.  The reason we didn't originally include much information in the recommended action is because there could be a lot of different reasons for this error.  We've now added two possible reasons and information about how to investigate more.

**Comment by samsmithnz** [comment]
Thank you for the additions. I reviewed the pr- why did the error number change?

**Comment by dsplaisted** [comment]
> Thank you for the additions. I reviewed the pr- why did the error number change?

I suspect it was something similar to #22639, where the error number changed from what it was originally added as due to earlier releases also adding error codes which merged forward.

**Comment by MelGrubb** [comment]
I have exactly one of the situations mentioned in the docs. One project references another, and they both have settings files. So what's the solution? I can't simply "avoid the situation" as suggested. The two projects legitimately have settings files. I have an Azure Functions project making use of some items in a WebApi project. The API needs its settings when running along, but obviously the Functions app has no use for them and should overwrite them. So until someone actually suggests an answer, I'm stuck.
