### ISSUE TITLE
"subscription-manager repos" command can fail on RHEL7; document should cover this case

### ISSUE THREAD

**Issue by The-MAZZTer** [dotnet/docs#27137]
When I enter the command:

subscription-manager repos --enable-rhel-7-server-dotnet-rpms

I receive the error message:

This system has no repositories available through subscriptions.

It is not possible to continue installing .NET using the guide when this error appears.

The troubleshooting section of the page listed below should cover this error message.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 197d466f-8967-78b1-b1fc-2c09367b0bec
* Version Independent ID: 2953e34e-d5e1-8d33-92a0-73a1d37cfb8e
* Content: [Install .NET on RHEL - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-rhel)
* Content Source: [docs/core/install/linux-rhel.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-rhel.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by The-MAZZTer** [comment]
Should add I am running the command on an internally hosted Amazon Web Services server.

**Comment by adegeo** [comment]
You may want to ask Red Hat support about that.

Tagging @omajid for any insights.

**Comment by omajid** [comment]
Thanks for cc'ing me.

Definitely agree on contacting Red Hat support.

I have also forwarded a link to this issue to some folks within Red Hat to see if we can improve the docs.

**Comment by RickJWagner** [comment]
Hi All,
My name is Rick, I work with the .NET team at Red Hat.
We don't view this as a .NET issue.  The problem is in the RHEL configuration, it's environmental.
Environmental issues (like disk failures, network connection troubles, etc.) are probably best handled outside the more targeted .NET docs.
Having said that, I'll also offer the suggestion that handling issues of this kind is exactly what Red Hat Support is for.  We'd gladly accept a support ticket.  Search engines also lead to our knowledge solutions, some of which look applicable (like the ones at [1] and [2]  Please give these a try).
Regards,
Rick
[1] https://access.redhat.com/discussions/4603661
[2] https://access.redhat.com/solutions/1981673

**Comment by The-MAZZTer** [comment]
Thanks for the response, I'm on vacation this week but I've passed this on to my project lead.
