### ISSUE TITLE
PrintMembers formatting in derived records – sealing method in sealed types has no use

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/docs#27173]
> For a sealed record that derives from another record: protected sealed override bool PrintMembers(StringBuilder builder);

When type (record) is `sealed` cannot be inherited thus sealing its members has no use. So correct signature is `protected override bool PrintMembers(StringBuilder builder)`;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20818c64-4ad8-fb15-5d79-e7f98614e9c4
* Version Independent ID: de1f383b-ef20-4776-57a8-04edae892166
* Content: [Records - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record#printmembers-formatting-in-derived-records)
* Content Source: [docs/csharp/language-reference/builtin-types/record.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/record.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
This may also be a spec bug.  (The records speclet has the same language)

/cc @jcouv

**Comment by BillWagner** [comment]
A developer can add or omit the `sealed` modifier when writing a custom `ToString` override for a record. Because either is accepted, we should probably remove any definitive statement in the docs about the signatures, but rather make sure that we accurately describe what signatures will work, and which signatures would generate an error or warning.
