### ISSUE TITLE
To unspecific

### ISSUE THREAD

**Issue by hjrb** [dotnet/docs#27284]
Is that workload installed per project or per solution or globally?
If installed globally - does that require admin rights?
How do I get a list of the installed workloads?
Trying to publish a Blazor WASM solution I keep getting this error.
Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1147	To build this project, the following workloads must be installed: wasm-tools
To install these workloads, run the following command: dotnet workload install wasm-tools	Blazor2048	C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets	38	

I ran dotnet workload install wasm-tools in an elevated prompt. Worked without any error. Still getting error during publish
Ran the same command in the directory of the projects. Still getting error during publish

This is supposed to be easy. But there a hundreds of pitfalls where stuff just doesn't work out of the box or as described :-(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bc768e4-9b1f-3e7d-afb9-e0115f896eec
* Version Independent ID: 6a0add91-7085-af96-9bac-de38e7249d35
* Content: [NETSDK1147: Missing workload for specified target framework - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1147?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(NETSDK1147)%26rd%3Dtrue)
* Content Source: [docs/core/tools/sdk-errors/netsdk1147.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/sdk-errors/netsdk1147.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@Rick-Anderson who can help with Blazor instructions?

**Comment by Rick-Anderson** [comment]
@guardrex

**Comment by guardrex** [comment]
Hello @hjrb ... A couple of quick answers, but we need to get you over to the product unit's ("PU") repo. They might ultimately redirect you elsewhere because AOT involves a few different groups of developers, but we'll start by having you open an issue over there for initial investigation.

* It's a global install per my current information, and they suggested documenting the optional workload installation using **either** of the following approaches:
  * Use the CLI command, as this error message indicates.
  * For the **ASP.NET and web development workload** in the Visual Studio installer, select the **.NET WebAssembly build tools** option from the list of optional components.
  
  They didn't provide further information, but I'll be tracking your PU issue for further doc improvements.

* For guidance on the CLI command, see :point_right: https://docs.microsoft.com/dotnet/core/tools/dotnet-workload-install and the additional commands in that docs node, including the `dotnet workload list` command for a list of installed workloads. I don't have further information outside of what you see there in the [*When to run elevated* section of the `dotnet install` command](https://docs.microsoft.com/dotnet/core/tools/dotnet-workload-install#when-to-run-elevated). You could open an issue from the bottom of that article if you feel that more detail is required in that section.

* For **Error NETSDK1147**, please open an issue for the PU at ...

  https://github.com/dotnet/aspnetcore/issues

  They're responding to dev feedback on errors and problems with the new AOT, runtime relinking, and native dependencies features and tooling.

  If you think to do so, please add a `cc: @guardrex` to the bottom of your opening comment. I track on their issues, but I don't see everything when I get super busy 🏃. If you mention me on the issue, I'll get the pings and keep tabs on the discussion for doc updates.

* WRT this error not being helpful enough, mention that to the PU in your issue. This is a generic SDK error and doc topic, so nothing can be addressed here. AFAIK, it's possible for them to provide enhanced error output. Let them know what you would have found helpful, even if it's only an added link to further information (e.g., a cross-link to the `dotnet install` command article here).
