### ISSUE TITLE
Mistake, or inconsistency at least, between two Exception code examples?

### ISSUE THREAD

**Issue by metaljase** [dotnet/docs#27669]
I think I've spotted a mistake, or inconsistency at least, in code examples across two pages.

An `ArgumentOutOfRangeException` is thrown (I believe correctly) on the following page:
[Exception Handling (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/exceptions/exception-handling)
```
int GetInt(int[] array, int index)
{
    try
    {
        return array[index];
    }
    catch (IndexOutOfRangeException e)
    {
        throw new ArgumentOutOfRangeException(
            "Parameter index is out of range.", e);
    }
}
```

An `ArgumentException` is thrown (perhaps incorrectly) on the following page:
[Creating and Throwing Exceptions](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/exceptions/creating-and-throwing-exceptions)
```
static int GetValueFromArray(int[] array, int index)
{
    try
    {
        return array[index];
    }
    catch (IndexOutOfRangeException ex)
    {
        throw new ArgumentException("Index is out of range", nameof(index), ex);
    }
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfeeac2f-fbeb-b4b5-ff02-fd48a28a2768
* Version Independent ID: 4d98bec1-a03a-4a9c-4108-cb847f9c18bd
* Content: [Creating and Throwing Exceptions](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/exceptions/creating-and-throwing-exceptions)
* Content Source: [docs/csharp/fundamentals/exceptions/creating-and-throwing-exceptions.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/exceptions/creating-and-throwing-exceptions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment]
I agree that I actually think that `ArgumentOutOfRangeException` is a better exception. Also using `try catch` isn't a good practice here. This should simply be an `if` condition.

**Comment by BillWagner** [comment]
Thanks for noting this @metaljase, and for the suggested improvement @Youssef1313 

I've added this to our backlog and added the "up for grabs" label.

**Comment by sputier** [comment]
@BillWagner According to my understanding, the point of this specific example is to show **how to throw a new exception which wraps a catched exception**. Throwing an exception following a consistency check is already covered by a previous bullet point : 
```
Programmers should throw exceptions when one or more of the following conditions are true:

-   The method can't complete its defined functionality. For example, if a parameter to a method has an invalid value:

        static void CopyObject(SampleClass original)
        {
            _ = original ?? throw new ArgumentException("Parameter cannot be null", nameof(original));
        }
```

In this case, the improvement suggested by @Youssef1313 might defeat the purpose of the example. Finding a more appropriate way to throw an exception with respects to best practices might be challenging, therefore I suggest we keep the actual code sample (maybe using `ArgumentOutOfRangeException` instead of `ArgumentException`). 

What do you think about this ? I can take care of creating the related PR whenever we agree on a way to handle this issue.
