### ISSUE TITLE
Examples are too simplistic

### ISSUE THREAD

**Issue by SteveBenz** [dotnet/docs#27776]
Questions that I had after reading this.  (I can imagine lots of people asking these)

1. What if "WeatherForecast" has a property that's another class.  Do I need to list it as well or will the compiler automatically include it?
2. What if I'm actually serializing a list of WeatherForecasts?
3. If it's falling back to Reflection, is there a way for me to know?  I'd like to make it so that a maintainer of my code doesn't accidentally do something that compromises performance and there being no way for them to know that they've made this mistake.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee53c3dc-df79-82ef-ce25-3233ff292c55
* Version Independent ID: 558903e9-8173-464e-ff8b-7744419ad7e4
* Content: [How to use source generation in System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-source-generation)
* Content Source: [docs/standard/serialization/system-text-json-source-generation.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json-source-generation.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by layomia** [comment]
> What if "WeatherForecast" has a property that's another class. Do I need to list it as well or will the compiler automatically include it?

> What if I'm actually serializing a list of WeatherForecasts?

Generally, you only need to specify types that will be passed to the serializer at the root level as `[JsonSerializable]`. There's no need to specify data types of properties as well. If it's a list of `WeatherForecast`s to be processed at the root of the serializer, you'd want to specifiy `[JsonSerializable(typeof(List<WeatherForecast))]`.

The only other types that need to be specified are runtime types that are declared as `object`, in the case of polymorphic serialization. For example

```cs
public class WeatherForecast
{
    public object Data { get; set; }
    public List<object> DataList { get; set; }
}

[JsonSerializable(typeof(WeatherForecast))]
[JsonSerializable(typeof(bool))] // runtime type for member declared as object needs to be specified.
[JsonSerializable(typeof(int))] // runtime type for member declared as object needs to be specified.
public partial class WeatherForecastContext : JsonSerializerContext { }

WeatherForecast wf = new() { Data = true, DataList = new List<object> { true, 1 } };
JsonSerializer.Serialize(wf, WeatherForecastContext.Default.WeatherForecast);
```

> If it's falling back to Reflection, is there a way for me to know? I'd like to make it so that a maintainer of my code doesn't accidentally do something that compromises performance and there being no way for them to know that they've made this mistake.

The source generation feature does not fall back to reflection, by design. If there's a type for which there's no source-generated metadata (i.e. not specified as `[JsonSerializable]`), the serializer will throw a `NotSupportedException` at runtime with an appropriate message.

**Comment by tdykstra** [comment]
Thanks, @layomia! I'll update the article.

**Comment by SteveBenz** [comment]
Thanks for the hard work here - I was able to figure out all that @layomia reported for myself without too much trouble - the whole package is very well designed and most things are pretty intuitive to guess through.  Updating the article would definitely be great as the example, as I read it, left me wondering whether it would work at all for my use case.
