### ISSUE TITLE
Wrong examples without required options for `dotnet store`

### ISSUE THREAD

**Issue by Marusyk** [dotnet/docs#27775]
The Examples section contains wrong code
```
dotnet store --manifest packages.csproj --framework-version 2.0.0
```
and the second one
```
dotnet store --manifest packages.csproj --skip-optimization
```
returns the same error

>  error MSB4057: The target "ComposeStore" does not exist in the project.

It is because `dotnet store` has required options: `-f` and `-r`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc238c72-c1eb-a09f-5b7b-801722924d38
* Version Independent ID: dbfcef0a-1079-0a2c-6bda-d2b57445ec29
* Content: [dotnet store command - .NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-store)
* Content Source: [docs/core/tools/dotnet-store.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-store.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@baronfel Do you know who can fix the examples and answer questions about `dotnet store`? There are two other open issues related to this one -- #18316 and #18317

**Comment by baronfel** [comment]
@dsplaisted can you offer any background here? Drew Noakes and Nick Guerra are also on the history for the [ComposeStore targets](https://github.com/dotnet/sdk/commits/main/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ComposeStore.targets), but I've never heard of this command before.

Naievely - We should update the examples to specify the TFM and RID so that the commands at least work. Separately, we should update the SDK to annotate those options as required, so that in the help text they are explicitly called out, like they already are in the docs.

**Comment by dsplaisted** [comment]
This page has some background: https://docs.microsoft.com/en-us/dotnet/core/deploying/runtime-store

Basically you can package up NuGet packages so that they can be shared by multiple apps when deployed instead of each app including a copy.  I think AWS Lambda uses it, but I'm not sure if there's much usage beyond that these days.

It sounds like we should fix the docs and command line parser as you suggest.
