### ISSUE TITLE
CBC-mode symmetric decryption

### ISSUE THREAD

**Issue by pfgrobler-work** [dotnet/docs#27913]
With [Timing vulnerabilities with CBC-mode symmetric decryption using padding](https://docs.microsoft.com/en-us/dotnet/standard/security/vulnerabilities-cbc-mode) recommending to no longer use CBC-mode symmetric decryption using padding

Is this recommendation in this rule to use  Mode = CipherMode.CBC still valid ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 895ad3c7-7fb5-95e7-8f03-30ad39659c86
* Version Independent ID: 5b70d7d9-25b0-0fe7-6d72-e4a270968d73
* Content: [CA5358: Do Not Use Unsafe Cipher Modes (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca5358)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca5358.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca5358.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @LLLXXXCCC
* Microsoft Alias: **linche**

**Comment by gewarren** [comment]
@bartonjs or @mavasani Could you comment on this?

**Comment by bartonjs** [comment]
The recommendation isn't to avoid the CBC mode in its entirety, instead the recommendation is to use a hybrid construction, such as encrypting data with CBC and then producing an HMAC or signature over the encrypted data to identify if it was tampered in transit.

Additionally, the particular concerns of a specific application may make the timing concern moot (e.g. if decryption requires a user to type a password then the thousands of attempts it takes to perform a padding oracle attack is pretty well thwarted).

As for the modes this rule recommends against:
* ECB is subject to "the penguin problem", which is well vizualized at https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Electronic_codebook_(ECB)
* OFB has an IV-reuse concern, the same key and IV with two different messages produce related output, which leaks data about those messages.
* CFB has less of an IV-reuse concern than OFB does, but it still has that same shape/class of problem (imperfect legitimate use can allow offline message analysis)

The remaining CipherMode value, CTS, is not very well supported (there's no support in .NET Core or .NET 5+, I don't remember if any types in .NET Framework supported it).

Two other "modes" exist for the AES algorithm, AES-CCM and AES-GCM (in .NET we expose these on distinct classes, because they behave very differently).  These modes build in a tampering check, which means that you don't need to add an HMAC or signature, but they suffer from IV/nonce reuse problems (GCM more so than CCM) and as such are best used by cryptographic experts and specialty protocols (such as TLS/SSL).

So... basically... CBC isn't perfect, but it's the best choice in a field of one.
