### ISSUE TITLE
CA1000 is overly restrictive

### ISSUE THREAD

**Issue by marcospgp** [dotnet/docs#28068]
I always disable this rule, it seems aggressively restrictive for the sake of protecting a rare scenario that in my view isn't even that confusing. Didn't know where else to leave this feedback, so here goes! Feel free to close :) And sorry for the annoyance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9974378b-c012-4648-5d90-f3ad6b0dc371
* Version Independent ID: ab933913-d16f-a92c-3733-d7e92cf00aa9
* Content: [CA1000: Do not declare static members on generic types (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1000)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1000.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca1000.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by sharwell** [comment]
Hi @marcospgp ,

Currently the rule is set to Hidden severity by default:
https://github.com/dotnet/roslyn-analyzers/blob/e52a3f1c0b45684ddaa041f26a980fa451ea9001/src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotDeclareStaticMembersOnGenericTypes.cs#L26

We didn't mark the rule as obsolete because it seemed like _most_ cases where this was a problem are cases where the static member uses the generic type argument. I'm interested to know if the cases that cause you to disable it fall into the same category.
