### ISSUE TITLE
How to change underscore naming styles?

### ISSUE THREAD

**Issue by zivkan** [dotnet/docs#28067]
The only instance of the word "underscore" is to mention that it's possible to set whether a name should start with an underscore, but the page doesn't explain how to change the style rule.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cfcd87a-a475-5fcf-2344-2b3a706a4b6d
* Version Independent ID: 95aa3bbf-7621-2064-f9d0-55105d55ee7e
* Content: [Code-style naming rules - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/naming-rules)
* Content Source: [docs/fundamentals/code-analysis/style-rules/naming-rules.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/style-rules/naming-rules.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@zivkan What is the naming style you want with respect to underscore characters? You can require it as a prefix or suffix, or as the word separator. These styles are listed here: https://docs.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/naming-rules#naming-style-properties.

**Comment by zivkan** [comment]
After a lot of head scratching, and reading other teams editorconfig files, i think I roughly understand what needs to be done. I've had too many meetings today to try it yet.

My feedback is that this is a very complex feature, even for experienced .NET devs, for someone who has never hand edited an editorconfig file before.

I think more examples, at least one that actually uses `required_prefix`, that would help.

**Comment by gewarren** [comment]
I agree that these naming rules are very confusing!

**Comment by zspitz** [comment]
@zivkan 

* A .NET **naming rule** has three parts: **symbol group**, **style** and **severity**. In other words, you're saying "symbol `x`  must have the style `y` applied to it; otherwise report it as a warning/error/info message (severity)".
* To define an entity -- a symbol group, style, or complete naming rule -- you set one or more properties. Property settings are grouped together into entities based on the kind of entity, and the common entity name (AKA title).
* Which properties you can set depends on the entity kind -- a symbol groups has certain properties, a style has others, and the naming rule has still others.

For example, in order to define a rule that private members must begin with an `_`, and if they don't it should be reported as an error, you could do the following:

* Define your symbol group, using `private_members` as the title:

  ```
  dotnet_naming_symbols.private_members.applicable_kinds = *
  dotnet_naming_symbols.private_members.applicable_accessibilities = private
  ```

* Then, define your style, using `underscore_prefix` as the title:

  ```
  dotnet_naming_style.underscore_prefix.capitalization = camel_case  # This is a required property value
  dotnet_naming_style.underscore_prefix.required_prefix = _
  ```

* Lastly, define the naming rule with the title `private_underscore_prefix`, and referencing the above entities:

  ```
  dotnet_naming_rule.private_underscore_prefix.symbols = private_members
  dotnet_naming_rule.private_underscore_prefix.style = underscore_prefix
  dotnet_naming_rule.private_underscore_prefix.severity = warning
  ```

---

Having said all that:

1. Does that make things clearer?
2. How would you change the documentation to better express this?

**Comment by zivkan** [comment]
@zspitz that does help, thanks!  I also owe you all an apology.

I think a big part of my confusion was that I was rushing and stressed trying to fix a CI failure blocking my entire team. After the CI agent appears to start installing the .NET 6 SDK without the .NET Core 2.1 runtime, our existing CI scripts started failing, and I was trying to unblock my team and get a green build quickly. In the end I removed `dotnet format` from our CI scripts for a different reason, making fixing this naming rule less time critical.

Anyway, given the complexity of this feature, I'm not sure how to improve the docs to help lazy customers such as myself who are looking for a sample to copy, paste, then only make minor edits. However, now that I'm reading the docs more slowly and carefully, plus what I read last week had time to "sink in", it no longer feels as complex as I previously thought.

For what it's worth, what's clicking with me now but not last week is exactly what you wrote in your first dot point. The rule references a symbol and style that is defined earlier. The three things (symbol, style, rule) are all required, but two are like variables referenced by the third. But I'm guessing this means the symbol and style can be used by multiple rules, which is why there's a benefit to handing the three different "kinds", rather than just one. When you re-use, the total lines in your editorconfig file is significantly reduced. The worst part is when I look at the docs again and read it more slowly, this is explained at least 3 times, but in my rush and panic to fix my team's build, I just didn't get it last week.

If I had a time machine, I'd stop myself creating this issue. I messed up. Sorry.
