### ISSUE TITLE
Document <LangVersion> for csproj files

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#2821]
The C# build system now includes a <LangVersion> node inside a csproj file that controls which version of C# the compiler should follow. Valid values include:

- ISO-1
- ISO-2
- C# 3.0
- C# 4.0
- C# 5.0
- C# 6.0
- C# 7.0
- C# 7.1 (beginning with .NET Core 2.0)
- latest (latest minor version)
- default (latest major version)

This can be set using the Visual Studio IDE, or editing the CSProj file.

@mairaw Can this be done with a `dotnet` CLI command?

**Comment by grokky1** [comment]
@BillWagner Also please document:

Visual Studio has an option for language version with "C# latest major version (default)". Which I assume means "7.0" rather than "7.1" which is confusing because most advice in SO/blogs is to do nothing and get the latest and greatest automatically though msbuild defaults.

But actually, to get 7.1 I need to do `<LangVersion>latest</LangVersion>`.

**Comment by mairaw** [comment]
Might be done as part of #2642. The new topic for 7.1 already mentions this.

**Comment by mairaw** [comment]
Also re. your question:
> Can this be done with a dotnet CLI command?
I haven't seen that. Adding @livarcocc and @nguerrera to help with that.

**Comment by BillWagner** [comment]
One issue is to point out that you should select "all configurations", not just "debug" (which is the default).
This is a common pitfall, from the feedback so far. 
So it would be great if we could include that in future instructions.
