### ISSUE TITLE
`in` overload rule

### ISSUE THREAD

**Issue by stanciuadrian** [dotnet/docs#28316]
The overload rules in the spec disallow `ref out` and `in out` combinations.
The given example is a pair of `in ref`.

The rule is correct but this page documents the `in` modifier.
I think the rules should be about `in ref` and `in out`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b1434b0-5459-7569-47f7-46bf33fc3953
* Version Independent ID: 8a4ae81b-1ae5-cbe6-d58b-df455414e245
* Content: [in parameter modifier - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/in-parameter-modifier)
* Content Source: [docs/csharp/language-reference/keywords/in-parameter-modifier.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/in-parameter-modifier.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
hi @stanciuadrian 

I'm not sure I understand your issue correctly. If I do, this issue should be closed. The `in`, `out`, and `ref` modifiers are all mutually exclusive. All mean that the parameter is passed by reference. The distinction is in whether assignment is required or permitted:
- `in` means the argument must be definitely assigned before calling the method. The method may not reassign that parameter. The argument is definitely assigned after calling the method (because it must be definitely assigned before calling the method.
- `ref` means the argument may be definitely assigned before calling the method. The method may reassign that parameter. The argument has the same definitely assigned state after calling the method that it had before calling the method.
- `out` means the argument may be definitely assigned before calling the method. The method must assign that parameter. The argument is definitely assigned after calling the method.

Let me know if I'm misunderstanding your comment.

**Comment by stanciuadrian** [comment]
The text from the `ref` markdown forbids `ref-out` and `ref-in` combinations: A compiler error occurs if the only difference between two members of a type is that one of them has a `ref` parameter and the other has an `out`, or `in` parameter. 

The text from the `out` markdown forbids the `out-ref` and `out-in` combinations: Therefore, methods cannot be overloaded if the only difference is that one method takes a `ref` or `in` argument and the other takes an `out` argument. 

The text from the `in` markdown is identical to the `out` one (copy/paste?) but that doesn't make it false nonetheless. In my opinion the documentation of `in` should explicitly forbid the `in-` combinations (by symmetry with the `ref` and `out` pages):

_I'd change it to:_ Therefore, methods cannot be overloaded if the only difference is that one method takes a `ref` or `out` argument and the other takes an `in` argument.

**Comment by BillWagner** [comment]
Thanks for the clarification @stanciuadrian 

I've opened a PR to address this.

**Comment by stanciuadrian** [comment]
LGTM

You're welcome!
