### ISSUE TITLE
Debugging on Raspberry OS ARM64?

### ISSUE THREAD

**Issue by SuperJMN** [dotnet/docs#28337]
I'm trying to debug with the ARM64 version of Raspbian OS and all I get it is "unloaded symbols". Is ARM64 debugging supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3e5dc95-a3a8-1cc6-049e-773e31449079
* Version Independent ID: 171f8840-fa9a-9174-2628-f3a9f6d0915e
* Content: [Debug .NET apps on Raspberry Pi](https://docs.microsoft.com/en-us/dotnet/iot/debugging?tabs=self-contained&pivots=vscode)
* Content Source: [docs/iot/debugging.md](https://github.com/dotnet/docs/blob/main/docs/iot/debugging.md)
* Product: **dotnet**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by CamSoper** [comment]
@joperezr @Ellerbach

**Comment by joperezr** [comment]
This is a good question, honestly I don't know what the answer is since this is mostly a question to either the VS team or the VS Code C# extension team which are the ones that own the debugger that gets installed into the target machine in order for a debugging channel to get established. If we don't have a linux arm64 debugger yet, then you wouldn't be able to setup ssh debugging.

**Comment by joperezr** [comment]
@SuperJMN did you try Visual Studio or VS Code for attaching?

**Comment by SuperJMN** [comment]
Hi @joperezr! I haven't because I'm not familiarized with it. I supposed that it uses the same remote debugger, so it should work the same way, shouldn't it? 

As a side note, I wouldn't like to use VSCode to debug my applications. VS has always been my option.

**Comment by Ellerbach** [comment]
I think this should work:
* You can remote debug to a Pi with VS Code or Visual Studio, install debug tools:
  `curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l ~/vsdbg`
* You have to do it as root because the debugger cannot sudo!
`sudo passwd root`
`sudo nano /etc/ssh/sshd_config`
* And add a line that reads:  
`PermitRootLogin yes `
* Then reboot:
`sudo reboot`
* Connect with Visual Studio into your RPI using SSH. 
* Launch the code you want to debug using dotnet.
* Attached the process from Visual Studio remote SSH debug.

And voilà :-) Tested on an arm32, no chance so far to test on arm64 but no reason it should not work properly as the debug elements exists for arm64
