### ISSUE TITLE
Change to title to `BackgroundService` instead of `Worker`

### ISSUE THREAD

**Issue by tebeco** [dotnet/docs#28451]
We're having several question on the C# Community Discord about `Worker Service`.
As a reminder, there's no such thing as a `Worker Service` in .net
* interface is `IHostedService`
* provided implementation is `BackgroundService`
* extension method is `AddHostedService`
* `Worker` is
  * the name of one random class `public class Worker : BackgroundService {}`
  * if that class was named `public class Foo : BackgroundService {}`, the docs would not have been `Foo Service in .net`
* `Worker` is/was a thing with Azure and we're even seing people using one instead of the other
* the page name does not page the paragraph:
![image](https://user-images.githubusercontent.com/2266487/156313621-a7c5a0fd-f4e9-4197-8141-819294b9d0d5.png)

## EDIT (more):
This article mix a lot of concept => see `terminology` block
Another way would be to change the title to `Worker template in .Net` if that's what it is really about

It would be better to focus on the functionnality (which is a `BackgroundService`) rather than on the name of a template that does not match the actual API.

**Because we're also seeing feedback of people saying they cannot use `Worker` because they are using AspNetCore by sending us link to that article**

## Consistency:
on that same page:
The `Worker Template` pointed with the green arrow looks perfect there but everything focus on `Background Service`
![image](https://user-images.githubusercontent.com/2266487/156315079-698dd837-a2ec-46e0-82cd-e317d636a263.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae847f16-ff74-ab68-7163-f713b447430c
* Version Independent ID: ff379d26-0d85-6d74-67da-4a3cd260b04d
* Content: [Worker Services in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/workers)
* Content Source: [docs/core/extensions/workers.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/workers.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @tebeco,

Thank you so much for posting this issue. We really appreciate it. I saw the discussion on the C# discord. The .NET product team were the ones that provided me with the name to use.

> As a reminder, there's no such thing as a Worker Service in .net

The term Worker Service has been used for many years and is considered accurate. In fact, the project `Sdk` relies on the `Microsoft.NET.Sdk.Worker`. It is a "Worker" service. The class that is generated as part of the template is also named `Worker`, and it implements the abstract `BackgroundService`. I do however agree that it's a little confusing and could be improved upon.

Perhaps we could rename the title to **Hosted Services in .NET**, since that is applicable in this context. But I'd need support from the product team to make such a change. In other words, all Worker Services are technically "Hosted Services", as they're implementations of `IHostedService`.

> This article mix a lot of concept => see terminology block

Yes, this is an _overview_ article and that is the purpose. It discusses at a high level all types, including the template, the `BackgroundService`, the `IHostedService` interface, and custom derivatives, as well as containers for workers, etc. The `BackgroundService` is but one abstract implementation, that is part of the Worker template - so it is inaccurate as a title here.

> Another way would be to change the title to Worker template in .Net if that's what it is really about

This article is _not_ exclusive to the Worker template, again it covers Worker Services as a concept. Additionally, the image that you posted where you circled many `background` references could have just as easily circled `IHostedService` or Worker.

I'm going to tag a few stakeholders from the product team for guidance here: @bradygaster @davidfowl

**Comment by tebeco** [comment]
I'm fine if the docs continue to name that Worker as long as it stop mixing
* the BackgroundService which is a type
* the Worker which is
  * A random class name
  * A dotnet template

As you might have seen on discord my word were a bit strong there.
It's not the first time (or the last) that there's confusion between these 3 things and often get a link to that article

If we want the article to focus on `Msft.Ext.*` I don't think calling it `Worker` is helping as i'm not sure there's a type or api named `Worker`

If we want the article to focus on providing a template to provide an application that runs as a worker, the name is fine but then both the vocabulary and the "terminology" block need to be changed and adapted in that direction

the most important part would especially be the "opening sentences" i guess to quickly clarify everything

**Comment by tebeco** [comment]
thx for the feedback ;) 👍

I hope the outcome will help anyone reading it understand the difference between both even if one could rely on the other.
That's generally the hard part ;)


Sorry about all the possible SEO implications, didn't though about that one
