### ISSUE TITLE
Meter name and instrument unit capitalization convention

### ISSUE THREAD

**Issue by katdti** [dotnet/docs#28471]
Hi

When looking at OpenTelemetry [semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/metrics/semantic_conventions) - they use lower cases in all meter names and unit examples. The MS doc capitalize first letter.
The OpenTelemetry semantic conventions also states unit annotation should be in {} brackets (e.g. {Hats})
Is it also here up to the metric consumer such as OpenTelemetry or Prometheus to change letter case and add brackets if needed as suggested in the Best Practices paragraph for instrument names with "'-" separators?

Regards
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61024acd-c2e8-291a-3007-7f09a1857690
* Version Independent ID: 02ec1bf2-d0fe-dac5-b2c1-45d607430b06
* Content: [Creating Metrics](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/metrics-instrumentation)
* Content Source: [docs/core/diagnostics/metrics-instrumentation.md](https://github.com/dotnet/docs/blob/main/docs/core/diagnostics/metrics-instrumentation.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tommcdon
* Microsoft Alias: **tommcdon**

**Comment by gewarren** [comment]
@noahfalk Can you answer the question about meter name and unit conventions?

**Comment by noahfalk** [comment]
Hi @katdti - sorry for the delay I see you asked this quite a while ago.

> Is it also here up to the metric consumer such as OpenTelemetry or Prometheus to change letter case and add brackets if needed as suggested in the Best Practices paragraph for instrument names with "'-" separators?

Yeah, at least that is my current opinion of what they should do. Ultimately it is the OTel SDK maintainer's choice whether they add support to do those name translations. I expect some 3rd parties will continue to follow .NET's existing convention and others will decide they prefer to adopt OTel's naming convention or invent their own. .NET's convention is ultimately only a recommendation rather than a requirement. Nothing in .NET's implementation of the Meter APIs enforces any naming rules. Hope that helps!

**Comment by gewarren** [comment]
Thanks @noahfalk. I'm going to close this issue since you've answered the question.
