### ISSUE TITLE
This is ridiculous when I say 5.0 I mean 5.0 and NOT 6.0

### ISSUE THREAD

**Issue by crtjr64** [dotnet/docs#28652]
I was directed to this page to create a .Net 5.0 service. When I attempt to start the process it says 6.0 is a prerequisite so again Microsoft wastes my time. You have the sincerity of a rock. Now I've got to go on a protracted search for what I need because the chain of instructions presented by Microsoft Docs is about as reliable as a cult leader. Why don't you just stop this? I'll move to 6.0 when ready, but playing these games to force us there just make developers distrust you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed148088-4550-2788-0756-390eab15e3f6
* Version Independent ID: 64d5cdf8-e50f-0c89-7f16-82645ba6383e
* Content: [Create a Windows Service using BackgroundService](https://docs.microsoft.com/en-us/dotnet/core/extensions/windows-service)
* Content Source: [docs/core/extensions/windows-service.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/windows-service.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi 👋 @crtjr64
Thank you so much for posting this issue. We really appreciate it.

> I was directed to this page to create a .Net 5.0 service.

From where, might I ask? I would be happy to update any incorrect references.

> When I attempt to start the process it says 6.0 is a prerequisite so again Microsoft wastes my time. 

I just recently updated this content to .NET 6, which is the long-term support (LTS) version. Whereas .NET 5.0 is not an LTS version. This is a very intentional change as we strive to have content that is:

- up-to-date, and
- aligns with LTS versions

> Now I've got to go on a protracted search for what I need because the chain of instructions presented by Microsoft Docs is about as reliable as a cult leader. Why don't you just stop this? I'll move to 6.0 when ready, but playing these games to force us there just make developers distrust you.

I'm sorry that you feel that way. It's not at all intentional, in fact - this content was just recently updated. And it doesn't differentiate that much from .NET 5 at all. I'm going to close this issue as there wasn't really a question, or any actionable follow up. If you need help with something, I'm happy to help.
