### ISSUE TITLE
How is this less secure that XML or JSON deserialization?

### ISSUE THREAD

**Issue by mdell-seradex** [dotnet/docs#28804]
Excuse me for any ignorance on my part, but I hope to get some clarity on this.
Isn't the BinaryFormatter supposed to be used specifically for Binary Serialization/Deserialization or is it also used for other things?
Shouldn't it only be deserializing data?
If so then wouldn't the deserializers for XML or JSON have the same issues trusting data, since the payload could contain bad data?
Or is the payload for binary serialization 1 blob that contains all of the data with no clear separation for each field?
If so then that would that not mean that each field would have to be stored in the exact same relative location to be able to deserialize correctly?  This sounds like an unsafe way to keep the fields.

I find it really disappointing that they have elected to not update or replace this serializer with something that is nearly as fast, but offers the needed protections.
Instead it needs to encode all data (including binary data - e.g. images) into text to make use of the XML or JSON serialization.
This type of encoding is well known to have significant performance impacts when sending larger amounts of data.
It does say we could use [BinaryReader](https://docs.microsoft.com/en-us/dotnet/api/system.io.binaryreader) and [BinaryWriter](https://docs.microsoft.com/en-us/dotnet/api/system.io.binarywriter) for XML and JSON, but gives no indication as to how one would do this.  This seems like it would need to encode the data as I mentioned before, encountering the same performance concern.

Please educate me on any misunderstands that I have.
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4a9e65f-dc69-2d49-763a-3ef41bd055ae
* Version Independent ID: 52919538-8a37-e4fa-2483-607c220e7ea2
* Content: [Deserialization risks in use of BinaryFormatter and related types](https://docs.microsoft.com/en-us/dotnet/standard/serialization/binaryformatter-security-guide)
* Content Source: [docs/standard/serialization/binaryformatter-security-guide.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/binaryformatter-security-guide.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @GrabYourPitchforks
* Microsoft Alias: **levib**

**Comment by IEvangelist** [comment]
Hi 👋 @mdell-seradex
Thank you so much for posting this issue. We really appreciate it.

I'm honestly not sure how to answer your question. Since it related to security, I'm going to tag @blowdart who knows all when it comes to .NET security.

**Comment by blowdart** [comment]
This really isn't a docs question, but let's try.

You're right in it's not a format problem, if you consider format to be how things are sent over the wire. It's a problem in what you can do during deserialization. Any serialization system that allows the payload to specify the type of object it carries is subject to remote code execution. 

To give a .NET framework example, framework contains a class for the generation of temporary file names, which contains a list of file names it's given you and when that class is disposed it deletes the files in question. It's possible to serialize this class. So an attacker could create a serialized representation of this class containing, say, web.config as a file name. When the class is disposed, or garbage collected web.config is deleted, and your website goes offline. Oops.

Constrained serializers, once which say "The payload must be of this class" would reject this input, because they're not going to expect the temporary file class. BinaryFormatter on the other hand has no constraints, its payload contains class names and so if you have something that accepted a binaryformatter serialized payload then during deserialization that class gets constructed and oh dear.

It's not just deleting files either, there are numerous what are called "gadgets" which allow you to run arbitrary code using certain classes and structures.

JSON by default is for known classes or primitive collections, but JSON.NET and other implementations have extensions that also allow you to specify the class names and introduce the same vulnerability.

The confusion over format arises because BinaryFormatter was the first and worst example of this, and people got stuck on the binary part rather than the real problem. It's why the doc says BinaryFormatter and not binary serialization.

The linked articles to OWASP et al go into detail about the vulnerability class, detail that's not suitable for inclusion in our docs. 

As for how to use BinaryReader and BinaryWriter that'd be a topic for those docs, but it's very much dependent on your scenario and advice may not be generic enough for a doc. Basically, write your data out in a known structure, either with a delimiter you understand, or known field sizes and only read into a matching class, don't ever allow a payload to control what classes are created when you read back.

**Comment by mdell-seradex** [comment]
I really appreciate your response, @blowdart.
Thank you.
It definitely provides much greater clarity on the subject.  I had no idea that binary formatter, and other classes, can dictate the type that gets deserialized.

I guess the confusion really is related to binary formatter vs binary serialization.
It sounds like you are saying that binary serialization/deserialization itself is still safe, as long as binary formatter is not used.

I don't recall anything in the docs about that, so if you were to change anything, I suppose it would be to mention that, and perhaps include a link to sample code that does that, or to docs on binary serialization that has that sample.
Or maybe I just missed it?

**Comment by blowdart** [comment]
We don't have anything because it's so context specific it's hard to recommend an approach. The 3rd party serializers generally do a good job and we don't want to take away from them.

**Comment by mdell-seradex** [comment]
I understand that it would be, but I thought that MS often gave general examples.

**Comment by IEvangelist** [comment]
Closing this as it was addressed in the issue comments, and not applicable to content as it is too specific of a situation.
