### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by martingbrown** [dotnet/docs#29097]
This page contains the following text:

[TODO: We should be more precise about the techniques the compiler is required to use to reach this judgment.]
[TODO: We should specify when a switch block is reachable.]

This makes it feel like the page is unfinished.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e3f3f52-86a5-4cc9-ab1f-874cad72b821
* Version Independent ID: f69dc2c8-79bc-300c-5804-e1f7aa5c8352
* Content: [Pattern matching - C# 7.0 draft specifications](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.0/pattern-matching#switch-statement)
* Content Source: [proposals/csharp-7.0/pattern-matching.md](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-7.0/pattern-matching.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi :wave: @martingbrown 

Yes, it's true that some of the feature specs weren't as fully finished as we'd like.

The good news is that the committee is catching up, and we've got a draft PR to update the standard. Watch dotnet/csharpstandard#61 to see this work continue.

I'll close this because it's already tracked as part of the committee's work here: https://github.com/dotnet/csharpstandard/blob/draft-v7/admin/v7-feature-tracker.md
