### ISSUE TITLE
Azure.Identity package required to run the sample

### ISSUE THREAD

**Issue by smflorentino** [dotnet/docs#29119]
The sample code on this page won't compile unless the Azure.Identity nuget is also installed. It's not marked as a dependency on the latest beta package (not sure about prior ones), and I'm not sure whether or it should be, or if the customer should just install this package separately to run the sample. Can you follow up with the product team on this and either:
- Fix the package dependency metadata to include Azure.Identity as a dependency
-  Update the docs saying it needs to be installed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29506de9-8ab4-0483-9a32-8af9a86a7b0a
* Version Independent ID: 093f3edc-7d63-0ce6-6a5d-e6c75c3cee76
* Content: [Resource management](https://docs.microsoft.com/en-us/dotnet/azure/sdk/resource-management)
* Content Source: [docs/azure/sdk/resource-management.md](https://github.com/dotnet/docs/blob/main/docs/azure/sdk/resource-management.md)
* Product: **dotnet-azure**
* GitHub Login: @nickzhums
* Microsoft Alias: **xinrzhu**

**Comment by scottaddie** [comment]
@smflorentino By design, none of the Azure SDK client libraries take a dependency on _Azure.Identity_. Instead, the libraries depend on _Azure.Core_. _Azure.Core_ contains a `TokenCredential` class, which gives you a couple options for authentication:

1. Create your own custom implementation of `TokenCredential`.
1. Use one of the many token-based credential types offered in _Azure.Identity_.
