### ISSUE TITLE
When a type loaded by System.Reflection.MetadataLoadContext "is" another type

### ISSUE THREAD

**Issue by Forgind** [dotnet/docs#29336]
**Help us make content visible**

I was looking at https://github.com/dotnet/docs/blob/main/docs/standard/assembly/inspect-contents-using-metadataloadcontext.md

The issue is that I'm unclear on how to check if a type "is" another type. For instance, let's say Foo extends Bar. If I have Foo f, loaded from an assembly inspected using MLC, and I check `if (f is Bar)`, it returned false. If I loaded the type Bar from the same MLC that Foo was loaded from, it still returned false.

My more specific issue was when I had a class from the MLC-loaded assembly with properties, and I tried to inspect the type of those properties. The workaround I found was walking from that type to the base type (eventually object) and checking at each stage if its name matched the one I was looking for, but that's messier.

[Edit to add document details]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d4a1a18-d470-6a2e-30d3-8f89a82aaaf8
* Version Independent ID: f1e8d3e4-e92e-f8e4-85fd-666101347b2f
* Content: [How to: Inspect assembly contents using MetadataLoadContext](https://docs.microsoft.com/en-us/dotnet/standard/assembly/inspect-contents-using-metadataloadcontext)
* Content Source: [docs/standard/assembly/inspect-contents-using-metadataloadcontext.md](https://github.com/dotnet/docs/blob/main/docs/standard/assembly/inspect-contents-using-metadataloadcontext.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @MSDN-WhiteKnight
* Microsoft Alias: **dapine**

**Comment by svick** [comment]
> If I have Foo f, loaded from an assembly inspected using MLC

This should be impossible. If you load an assembly using the MLC, then you can't have an instance of a type from that assembly.

> The workaround I found was walking from that type to the base type (eventually object) and checking at each stage if its name matched the one I was looking for, but that's messier.

Why do you need to check the whole inheritance hierarchy? Checking just the name of the type in question should be enough.

**Comment by MSDN-WhiteKnight** [comment]
`is` operator could never work with MetadataLoadContext, it's meaning is baked into language so it could only work with a type defined at compile time. `IsAssignableFrom` works for MLC, but it is not compatible with runtime reflection. If you test using a type loaded in MLC too, it should work:

```
Assembly matchAssembly = mlc.LoadFromAssemblyPath(typeof(ITaskItem).Assembly.Location);
Type tMatch = assembly.GetType(typeof(ITaskItem).FullName);
//...

if (tMatch.IsAssignableFrom(pi.PropertyType))
{
    Console.WriteLine("Property is ITaskItem");
}
```

The runtime reflection is incompatible, because RuntimeType.IsAssignableFrom is currently hardcoded to work only with runtime type, TypeBuilder, or types whose UnderlyingSystemType is runtime type: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/RuntimeType.cs#L324 MLC types does not implement UnderlyingSystemType to return runtime type, so they hit a path that always returns false. Do someone know it it's an expected limitation that should be documented, or it could be lifted? /cc @steveharter I remember someone expressed desire to make converting between MLC types and runtime types easier, but it wasn't yet formally proposed.

**Comment by steveharter** [comment]
The summary from @MSDN-WhiteKnight is spot on: the `is` keyword will not work with MLC since that implies instances, not types. Instead use the type should be obtained from the instance and then `Type.IsAssignableFrom(type)` or the newer `Type.IsAssignableTo(type)` used which works with MLC provided that both types are obtained from MLC and not from elsewhere.

> /cc @steveharter I remember someone expressed desire to make converting between MLC types and runtime types easier, but it wasn't yet formally proposed.

I don't have the request handy, but I do recall that as well. Although it is possible to add interop, I can't think of anything that can't be done manually by ensuring all types being compared are obtained from an instance of a MLC. Such a new API has to be designed to be deterministic and straightforward; likely the API would support a lookup mechanism that given an external type or object, can obtain the corresponding type from MLC and perhaps also support enumerating the various assemblies so that an assembly doesn't need to be specified.

**Comment by steveharter** [comment]
FYI here's the issue for converting between MLC types and runtime: https://github.com/dotnet/runtime/issues/41450

**Comment by MSDN-WhiteKnight** [comment]
Pushed an update to this doc that describes a working way to test for assignabilty: <https://github.com/dotnet/docs/pull/29831>. I believe loading a second type into MLC is better workaround then trying to do a manual walk of base types. 

Is there anything more to address here, or this issue could be closed?

**Comment by Forgind** [comment]
One last question: are any of these things expected to work after the MLC has been disposed? Like if I load two types before it's disposed and cache them, then check if one is assignable from the other later, should that work?

**Comment by MSDN-WhiteKnight** [comment]
> One last question: are any of these things expected to work after the MLC has been disposed? Like if I load two types before it's disposed and cache them, then check if one is assignable from the other later, should that work?

No: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/MetadataLoadContext.Apis.cs#L50

    The behavior of any Type, Assembly or other reflection
    objects handed out by the MetadataLoadContext is undefined after disposal.

**Comment by Forgind** [comment]
Ah, ok. That was the real issue I'd been facing. We were disposing of the MLC before trying to check if everything worked. Thanks!
