### ISSUE TITLE
Shorthand?

### ISSUE THREAD

**Issue by MichaelBrooks-Informatyx** [dotnet/docs#29517]
[Enter feedback here]
This page states that

`public override string ToString() => $"{fname} {lname}".Trim();`

is a shorthand version of
```
public override string ToString()
{
   return $"{fname} {lname}".Trim();
}
```
but these are both the same length. The first form has removed the two characters '{' and '}' and added the two characters '=' and '>'. The newline characters are irrelevant - they could be removed from the second form as easily as in the first form.
Can we have a credible explanation of any benefits of the first form please? So far all I see is two ways of doing the same thing, which is a contravention of Occam's Razor and only serves to add confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a695fde2-da48-835f-423d-d34fb048d6ab
* Version Independent ID: e8eab8da-72ba-991a-c011-a41d2ed9939d
* Content: [=&gt; operator - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-operator)
* Content Source: [docs/csharp/language-reference/operators/lambda-operator.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/lambda-operator.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mohamed-azhar** [comment]
In my personal experience, I haven't noticed any major performance difference between the 2 methods mentioned. The "shorthand" version is using [C# Expression-Bodied Members](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/expression-bodied-members#methods) feature which was introduced with C# 6. The feature enables us to write expressions with one liners resulting in reduced boilerplate, clean and readable code.

**Comment by BillWagner** [comment]
Hi @MichaelBrooks-Informatyx 

As already mentioned, the `=>` can be used for an Expression bodied member. The two forms of methods are equivalent. The expression bodied member *is* shorter, because you only need to write the expression. You don't need to include the `return` keyword to make it a statement. The whitespace becomes significant when you have single expression methods that use [pattern matching](https://docs.microsoft.com/dotnet/csharp/fundamentals/functional/pattern-matching#compare-discrete-values). The horizontal spacing does matter there.

All that said, there's no requirement to use expression bodied members. In docs, we use both forms. We don't make any recommendation preferring one over the other. As you say, they are equivalent.

I'll close this as an answered question.
