### ISSUE TITLE
Typically, you'll want to keep Global Usings in a single location. 

### ISSUE THREAD

**Issue by MNF** [dotnet/docs#29746]
It will be useful to provide further tip, which single location is recommended .
Do you recommend  it be in the top of Program.cs (if such file exists in the project)?
Or create some file GlobalUsings.cs in Properties subfolder?
Or something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7569e51d-92c7-294a-2d5f-e1ab3c35fdf8
* Version Independent ID: 86a1c11a-1d3c-902b-6cf3-5c004c59a856
* Content: [using directive - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-directive)
* Content Source: [docs/csharp/language-reference/keywords/using-directive.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/using-directive.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by sharwell** [comment]
The SDK creates a generated file with global using directives defined via the project. The approach I recommend for adding to this list is adding new global using items to the project file itself, and these will be added to the same location.

**Comment by BillWagner** [comment]
I'm adding this to our backlog, and adding the "discussion" label.

@CyrusNajmabadi @jinujoseph Do we have analyzers that make a recommendation for where global usings should be added in a project?

**Comment by ahaleiii** [comment]
I'm experimenting with `Program.Usings.cs`, which can be nested under `Program.cs` if desired.

I would prefer  to keep global usings out of `Program.cs` so that top level programs can stay small and on point.

**Comment by Bunnywood** [comment]
A separate file is a cleaner solution in my opinion, fwiw :)

**Comment by sharwell** [comment]
> I'm adding this to our backlog, and adding the "discussion" label.
> 
> @CyrusNajmabadi @jinujoseph Do we have analyzers that make a recommendation for where global usings should be added in a project?

We don't have any refactorings right now, but we did discuss the desired placement.
https://github.com/dotnet/roslyn/issues/55895#issuecomment-940461765

The primary desired placement is likely to be the project file, as this location has already been adopted by the .NET SDK.

**Comment by kzu** [comment]
@sharwell perhaps it's time to fix https://github.com/dotnet/roslyn/issues/34636 so that the analyzer can suggest a change that goes to the project file 😉

**Comment by JoeMayo** [comment]
Wherever it goes will still work. However, I wanted to bring up something about putting global usings in the Project file. It felt odd to me to do that because a using directive has always been code. Is there a precedent for putting declarative code in the Project (*.csproj) file? My initial thought on Project file semantics is that Project files are about what goes into a project and how it is built, rather than what the project does. I could be wrong, but just wanted to mention that.

**Comment by CyrusNajmabadi** [comment]
The position of hte Language Design group is that these are just code.  However, we also have no issue with layers around the language (e.g. the project system/sdk) deciding they want to have their own representation of this as long as it ends up emitting normal C# code that hte user could have written themselves anyways.

Personally, i don't think anything much needs to be said/controlled on this topic.  Users can/should place global usings wherever they think is best.  The IDE will already tell you what global usings are in pulled in from other files, and you can navigate using that to find out which files these were declared in if you want to remove/tweak that.

**Comment by kzu** [comment]
I agree with @CyrusNajmabadi but I'd say that in order for consumers to have a good user experience in the IDE, roslyn analyzers and corresponding code fixers should be able to suggest (and move) global usings to the project file too. Otherwise, you are making that option significantly less friendly than the code-only alternative (where you can effectively move code anywhere in the solution via a simple codefix). See https://github.com/dotnet/roslyn/issues/34636

**Comment by CyrusNajmabadi** [comment]
Honestly, i don't really see the need for much in teh way of tooling here.  I would expect that touching this stuff woudl be extremely rare.  You basically just do it a tiny handful of times, then never touch it again.  So being manual is fine.

**Comment by glennawatson** [comment]
I found use when refactoring a large project recently and would of loved a refactor tool to add my global usings.

**Comment by kzu** [comment]
I guess that same criteria didn't apply to adding one trivial property to the csproj eh? 

![image](https://user-images.githubusercontent.com/169707/173078103-f6bc0f89-db0d-4711-ae87-ba1c50e8f7a5.png)

Just to do this *once*, not even a "tiny handful of times":

```xml
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
```

That code fixer could not just modify the csproj directly via a "plain" analyzer due to the mentioned bug.

**Comment by peteraritchie** [comment]
Looks like the XUnit dotnet project template has settled on _in a file named Usings.cs_.

![image](https://user-images.githubusercontent.com/408620/174830510-dc28ddae-8248-4c43-812d-8440f34a4001.png)
