### ISSUE TITLE
Nondestructive mutation shows inconsistent hashcodes

### ISSUE THREAD

**Issue by Vaskaran** [dotnet/docs#29937]
Hi,
I have the following code:
```
Employee emp1 = new Employee(1,1000.7);
Console.WriteLine(emp1);

Employee emp2 = emp1 with { Id = 2 };
Console.WriteLine(emp2);


Employee emp3 = emp1 with { Salary=3000.5, Id = 2 };
Console.WriteLine(emp3);

Employee emp4 = emp1 with { Salary = 5000.5, Id = 3 };
Console.WriteLine(emp4);

//Checking hashcodes
Console.WriteLine(emp1.GetHashCode());
Console.WriteLine(emp2.GetHashCode());// emp1 and emp2 hascodes are same
Console.WriteLine(emp3.GetHashCode());// Different hashcode
Console.WriteLine(emp4.GetHashCode());

struct Employee
{
    public double Salary;
    public int Id;
    public Employee(int id,double salary)
    {
     
        Id = id;
        Salary = salary;
    }
    public override string ToString()
    {
        string emp = $"Emp Id{Id} earns ${Salary} per month";
        return emp;
    }
}
```
Once I run this code, I see the following output:

Emp Id1 earns $1000.7 per month
Emp Id2 earns $1000.7 per month
Emp Id2 earns $3000.5 per month
Emp Id3 earns $5000.5 per month
1707992465
1707992465
-58963822
-60247790

I understand that the hashcodes can be different.But my question is: first two hashcodes are always identical,but the third and fourth one are not. I tried similar programs and in each case, I have noticed that only for the first copy, the hashcodes are identical,but for the "additional copy operations" using "with expression"- this is not the case.

Is this an expected behavior?Do we have any document for this?

Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9220116-e950-04cf-b6d5-70d15a084a22
* Version Independent ID: 0960802e-80c3-cb56-cb8b-ab1f1b20fb4e
* Content: [Structure types - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/struct)
* Content Source: [docs/csharp/language-reference/builtin-types/struct.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/struct.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Adding @stephentoub 

I know the default implementation of `GetHashCode()` has changed over time for `struct` types. I think the behavior you're seeing is correct based on that implementation.

If you want non-destructive mutation to change the value of the hash code value, you should use a `record` or a `record struct`. Those types will always use all the fields of the type to compute the hash code. 

As an alternative, you could write your own `GetHashCode` override for your `struct`. That's generally not recommended; we'd recommend using a `record` type instead.

**Comment by stephentoub** [comment]
This is all implementation detail, but historically (and today in both .NET Framework and .NET Core) ValueType.GetHashCode wants to just hash the bytes that make up the struct, but it can only do that in some circumstances, if the struct doesn't have any fields that would require special handling.  Floating-point types require special handling, so ValueType.GetHashCode is forced to fall back to a slow path that just finds the first field on the type and uses a hash code based on that field... that's why your changing Id doesn't affect the hash code.

If your struct will have its hash code used, e.g. you're using it as a key in a dictionary, you should override GetHashCode.  That will give you the best behavior, predictability, and performance.

**Comment by BillWagner** [comment]
The details for `GetHashCode`, including overriding it, are covered well in the API reference page:

- [General remarks](https://docs.microsoft.com/dotnet/api/system.object.gethashcode#remarks)
- [Notes for inheritors](https://docs.microsoft.com/dotnet/api/system.object.gethashcode#notes-to-inheritors)

I'm going to close this because this page shouldn't include the detailed instructions on overriding `GetHashCode`. Most structures don't need to override that method. Those that do should check the details for that API.
