### ISSUE TITLE
Code block is split into several consecutive fragments

### ISSUE THREAD

**Issue by yeremee** [dotnet/docs#2994]
The sample code is split into several consecutive fragments. For example, here: https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/styling-and-templating. The code block looks like:

![code block](https://raw.githubusercontent.com/yeremee/_test/master/2017-08-25_21-43-00.png)

It is very inconvenient.

**Comment by mairaw** [comment]
You're right @yeremee. This is due to our migration to docs. Our previous system used to concatenated these pieces of code, like [here](https://msdn.microsoft.com/en-us/library/481765e5-5467-4a75-9f7b-e10e2ac410d9(vs.100)):

![image](https://user-images.githubusercontent.com/12971179/29738239-ea78b826-89d2-11e7-9c91-c09ada37cba1.png)
