### ISSUE TITLE
Worker Service - Missing Template

### ISSUE THREAD

**Issue by nezero** [dotnet/docs#29940]
After installing all prerequisites, the "Worker Service" template does still not appear in my list of project templates.

It only appeared after installing ASP.NET and Web Development workloads.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed148088-4550-2788-0756-390eab15e3f6
* Version Independent ID: 64d5cdf8-e50f-0c89-7f16-82645ba6383e
* Content: [Create a Windows Service using BackgroundService](https://docs.microsoft.com/en-us/dotnet/core/extensions/windows-service)
* Content Source: [docs/core/extensions/windows-service.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/windows-service.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hey @KathleenDollard and @DamianEdwards, would either of you know why the Worker Service template is not included in the non-ASP.NET and Web Dev workloads? /cc @bradygaster

**Comment by bradygaster** [comment]
@IEvangelist - it came from the ASP.NET team so historically we've owned the template. Do you have a proposal that it be elevated outside of ASP.NET? cc @vijayrkn

**Comment by IEvangelist** [comment]
> @IEvangelist - it came from the ASP.NET team so historically we've owned the template. Do you have a proposal that it be elevated outside of ASP.NET? cc @vijayrkn

Hi @bradygaster,

This issue is from a confused customer, as my docs failed to include the workload requirement of "ASP.NET and Web Development". The worker has its project SDK:

```xml
<Project Sdk="Microsoft.NET.Sdk.Worker">
```

With the `Microsoft.Extensions.Hosting` NuGet package, a worker can run without ASP.NET or as a Web app. I agree with the customer that this is confusing, and while I need to address this in the docs as a temporary fix - I would encourage the template not to be part of the ASP.NET and Web workload. Part of the reason that all of these docs started showing up under the .NET docs site, was due to the fact that the `Microsoft.Extensions.*` packages are designed for all workloads, not just Web. What are your thoughts?

**Comment by IEvangelist** [comment]
> These are the other .NET workload options in VS: ![image](https://user-images.githubusercontent.com/3981619/176470380-c60186f3-79e0-4af1-9249-94c2d9406e76.png)
> 
> I don't know if this aligns with any other workload options in VS. I agree that having to choose 'web' to get 'worker' is not intuitive but not sure if we have an alternate option here.

What about having it be part of the .NET SDK itself? Where does the _Console App_ template come from?

**Comment by satishgitme** [comment]
Other way around is, while installing ASP.net development stuff just select the ASP.net project templates. That brings the worker service project template.
