### ISSUE TITLE
Record or Class or Struct? Decision Tree

### ISSUE THREAD

**Issue by JerryNixon** [dotnet/docs#29962]
I was certain that this page would help me decide between records and structs and classes. It's an unexpectedly unclear decision process that I think new developers struggle to understand. Why not provide a decision tree? A decision tree like (is it this? yes/no). If such a tree comes across as too simple, then it will be simple to create, I hope. But the struggle is real. Especially with students. 

Some starter questions:

1. Is my data mutable?
2. Do you want value-based equality?
3. Do you want non-destructive mutation?
4. Do you want a reference type?

Also see: https://twitter.com/jerrynixon/status/1392721462423953410
Also see: https://twitter.com/jerrynixon/status/1539605996481429505

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2eb21e6e-7798-e557-be3f-f27ab9c93e05
* Version Independent ID: a526a9cc-938e-7528-b5b4-4879c5085152
* Content: [Classes, structs, and records in C#](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/object-oriented/)
* Content Source: [docs/csharp/fundamentals/object-oriented/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/object-oriented/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---
[Associated WorkItem - 297237](https://dev.azure.com/msft-skilling/Content/_workitems/edit/297237)

**Comment by BillWagner** [comment]
Adding @IEvangelist 

We've talked about this, but I couldn't find the content. It's clearly needed.

I'd also adde tuples as a possibility, when the needs are even less.

We should also recommend against creating anonymous types going forward. (There's no reason to remove them from a code base that's using them, but we shouldn't recommend making more of them.

**Comment by IEvangelist** [comment]
Hi @BillWagner and @JerryNixon,

There was an issue about this years ago, found it here:

- https://github.com/dotnet/docs/issues/1575

This issue was addressed in https://github.com/dotnet/docs/pull/19201 where at the time we assumed there was enough coverage for classes vs structs, and effort resulted in a new article: [Choosing between anonymous and tuple types](https://docs.microsoft.com/dotnet/standard/base-types/choosing-between-anonymous-and-tuple). This is a bit related and we could benefit from creating an article for records, classes, and structs.
