### ISSUE TITLE
Is strong name signing supported or not? Mutually exclusive statements exist

### ISSUE THREAD

**Issue by albert1355** [dotnet/docs#29982]
See:
https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/strong-name-signing-exceptions#:~:text=Strong%2Dname%20signing%20is%20not%20supported%20in%20.NET/.NET%20Core%2C%20and%20there%20is%20no%20workaround.

versus this entire page and specifically:
https://docs.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name#:~:text=Although%20.NET%20Core%20supports%20strong%2Dnamed%20assemblies%2C%20and%20all%20assemblies%20in%20the%20.NET%20Core%20library%20are%20signed
https://github.com/dotnet/runtime/blob/main/docs/project/strong-name-signing.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d48640e-df05-fb9c-d896-975c53cf2571
* Version Independent ID: fb37dffe-541a-246e-ab14-aba0423848af
* Content: [Breaking change: Strong-name APIs throw PlatformNotSupportedException - .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/strong-name-signing-exceptions)
* Content Source: [docs/core/compatibility/core-libraries/6.0/strong-name-signing-exceptions.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/core-libraries/6.0/strong-name-signing-exceptions.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@buyaa-n Can you help to answer this?

**Comment by blowdart** [comment]
Define "supported". 

The APIs for checking strong name signatures in .NET 6 throw, but .NET 6 (or core) never used them internally.

But you can still strong name assemblies in all versions of .NET using the sn tool. .NET Core/5/6+ never checks signatures in its runtime, but if you're targeting cross platform libraries (for example I have a basic auth package which targets .NET Standard 2.0, so it runs on full framework too) then it's a good idea for cross runtime compatibility because full framework still enforces strong naming if you are strong naming the calling app. 

As ASP.NET 3.1 is supported on .NET Framework for the foreseeable future, strong naming will live as long as it does.

**Comment by blowdart** [comment]
Define "supported". 

The APIs for checking strong name signatures in .NET 6 throw, but .NET 6 (or core) never used them internally.

But you can still strong name assemblies in all versions of .NET using the sn tool. .NET Core/5/6+ never checks signatures in its runtime, but if you're targeting cross platform libraries (for example I have a basic auth package which targets .NET Standard 2.0, so it runs on full framework too) then it's a good idea for cross runtime compatibility because full framework still enforces strong naming if you are strong naming the calling app. 

As ASP.NET 3.1 is supported on .NET Framework for the foreseeable future,

**Comment by gewarren** [comment]
Thanks @blowdart!
