### ISSUE TITLE
C# Version not specified

### ISSUE THREAD

**Issue by Manueeell** [dotnet/docs#30026]
Which was the first version of C# to introduce patterns and pattern matching? Can this be clarified in the article?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46225236-316d-bf2c-add4-6cea9b579ddc
* Version Independent ID: 528c02d9-3551-c7df-817e-ea50b2760f51
* Content: [Pattern matching overview - C# guide](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/functional/pattern-matching)
* Content Source: [docs/csharp/fundamentals/functional/pattern-matching.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/functional/pattern-matching.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
It's a bit complicated, because pattern matching was not added all at once, but it was expanded version after version.

Some examples from this article:

* Pattern matching itself was initially added in C# 7.0.
* The `switch` expression was added in C# 8.0.
* Relational and `not` patterns were added in C# 9.0.
* List patterns will be added in C# 11.

I don't think all of this information needs to be in the article, at least not in detail. Though a note that list patterns are currently in preview could be helpful.

**Comment by BillWagner** [comment]
Thanks @Manueeell 

I'd like to learn a bit more about how this information will be useful to you. As @svick points out, there were new features added to pattern matching in every version from C# 7 through C# 11. (C# 12 planning hasn't started, so I have no information on further updates).

I want this page to provide a solid overview of all the pattern matching features available today. That said, I don't want to make it hard for anyone using older versions of C# to find what they need. That's why details on how you'd use this information will help me present it in the most useful way possible.
