### ISSUE TITLE
Standard Formatter behaves different in different environments

### ISSUE THREAD

**Issue by fkucuk** [dotnet/docs#30095]
Hello String Formatter behaves different in different environments when I use standard formatter.

The same code below, different outputs:

```csharp
        var value = 10000.25M;
	Console.WriteLine(value.ToString("C", System.Globalization.CultureInfo.CreateSpecificCulture("ar-EG")));
```

In one computer decimal sepator is a specialized Arabic comma  (٫), in another computer it is dot (.).

ج.م. 10٬000٫25 ‏
 ج.م. 10,000.25‏

Isn't this weird?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ae38fce-fc98-9420-6b0b-ceee4e885f2d
* Version Independent ID: f23035e0-f271-b48c-f9a9-8582be80b4ad
* Content: [Standard numeric format strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings)
* Content Source: [docs/standard/base-types/standard-numeric-format-strings.md](https://github.com/dotnet/docs/blob/main/docs/standard/base-types/standard-numeric-format-strings.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@fkucuk There could be a lot of things at play here, such as OS configuration. I believe you could have a computer configured to use a different locale for currency, such as US while the system is using Arabic for everything else. You may want to check out https://docs.microsoft.com/en-us/globalization/locale/currency-formatting and see if there is something that can help you in configuring the system that you feel is operating incorrectly.

Otherwise, I'm not too sure what else I could do here. You may want to ask on StackOverflow or another general programming support forum if you can't figure it out.
