### ISSUE TITLE
mixin support like dart language

### ISSUE THREAD

**Issue by aliessmael** [dotnet/docs#30263]
Hi , is it possible to support mixing with fields support, It will help us to implement behaviors (features) in separate clean mixin
then we compose our class using those mixin, fields are important to implement behaviors,

Just imagine this example , if I want to make game player class that can play sound , produce light, and fall by physics

it is very clean to make these features as seperate mixin : Sound, Light, Rigidbody
then I can compose them like  class  MyPlayer : with Sound, Light, Rigidbody
basically  it will copy mixin code into MyPlayer

It will be awesome also if mixin will have constuctor and destructor called when MyPlayer class created or destroyed.
of course also must be able to cast MyPlayer to any mixin, for example I want to Add MyPlayer to Physics System, I must cast to Rigidbody.
last thing mixin can use and force MyPlayer to have specific feilds or functions. ( for example all mixins code require MyPlayer position).

Regards.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c8d9be-958f-d92a-77f5-c105fa307c93
* Version Independent ID: 0974453c-bf3d-37ed-a965-c4178f3be945
* Content: [Create mixin types using default interface methods](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/mixins-with-default-interface-methods)
* Content Source: [docs/csharp/whats-new/tutorials/mixins-with-default-interface-methods.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/tutorials/mixins-with-default-interface-methods.md)
* Product: **dotnet-csharp**
* Technology: **csharp-advanced-concepts**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @aliessmael 

I'm going to close this because it's not a docs issue, but a product request. You can suggest news features in the [dotnet/csharplang](https://github.com/dotnet/csharplang) repository.

The LDM (Language design meeting) team discussed possible designs to enable this feature. After deliberating, the decision was that the likelihood of introducing the "diamond inheritance problem" was too great. That's a reason for the restriction that default interface members can't include instance fields.

This is still an attractive feature, but it would require a better solution before it can be added.
