### ISSUE TITLE
converting to nullable

### ISSUE THREAD

**Issue by CastonYoung** [dotnet/docs#30334]
"You can also explicitly cast a nullable value type to a non-nullable type, as the following example shows:..."

No I can't!  Visual Studio gives me a CS0030 error if I try to do this.
`double StandarDeviation(List<(double)> x)
{	double avr = 0;
	x.ForEach((num) => avr += (double)num);
	return 1.0;//Stub
}`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3e65a97-5e33-ab78-cd40-b20c3219ca2f
* Version Independent ID: 1ae0aed9-e565-44ae-aebe-c55a0a02c2c5
* Content: [Nullable value types - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-value-types)
* Content Source: [docs/csharp/language-reference/builtin-types/nullable-value-types.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/nullable-value-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CastonYoung** [comment]
Okay removing the () in List<(double)> seems to have resolved the issue, but still a terrible error message.

**Comment by svick** [comment]
[When I compile your code](https://sharplab.io/#v2:C4LgbgpgTglgZgTwDQBMQGoA+ABADAAmwEYAWAbgFgAoalAewFcAjAGwnwGVgBDAOxW5QAIhDAxuwGHV4AKADIwAzsAA8M+szYBKAHz4AHluoBvavnP4NrdtzBR8AXny5KVCwYB0AMTpQAotwAxgAWMjK8DAC2Wo56tvboTuqM1loR0a7u2ADs+EQeLtQAvkA===), I get two error messages:

>    error CS8124: Tuple must contain at least two elements.
>    error CS0030: Cannot convert type '(double, ?)' to 'double'

The second one should make you think there's something wrong with the type of `num`, and the first one explains what the actual problem is. So it seems to me that the error messages here are reasonable and helpful.

**Comment by CastonYoung** [comment]
Hmm... error CS8124 never showed up for me, and I'm using a 2019 version.
Well thanks for looking into it.

**Comment by BillWagner** [comment]
Thanks for noting this @CastonYoung 
And for the helpful analysis @svick 

I'm going to close this as it's not relevant to the linked error message.
