### ISSUE TITLE
Updates for .NET Framework 4.8.1

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#30542]
- [x] Update .NET Framework versions and dependencies
- [x] Update What's new in .NET Framework
- [x] Update How to: Determine which .NET Framework versions are installed
- [x] Update breaking changes for 4.8.1 target - see #30541

**Comment by gewarren** [comment]
Related to #29985.

**Comment by martinsuchan** [comment]
I'm especially interested in "breaking changes" page since .NET 4.8, similar to this one:
https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/runtime/4.7.2-4.8

**Comment by gewarren** [comment]
> I'm especially interested in "breaking changes" page since .NET 4.8, similar to this one: https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/runtime/4.7.2-4.8

@martinsuchan There are no breaking changes since 4.8. I am updating the breaking changes docs today to reflect this.

**Comment by reflectronic** [comment]
Is there documentation coming about the Arm64 support in .NET Framework 4.8.1? My understanding is that it requires some kind of opt-in from the application author, and that some features are not supported under the Arm64 version of .NET Framework. @richlander mentioned that there will be articles explaining how to opt-in to Arm64 support for .NET Framework apps -- are they coming soon? Is it required to target .NET Framework 4.8.1 for Arm64 support, or is there a way to opportunistically enable this support for apps targeting lower versions?

**Comment by TaraOverfield** [comment]
> Is there documentation coming about the Arm64 support in .NET Framework 4.8.1? My understanding is that it requires some kind of opt-in from the application author, and that some features are not supported under the Arm64 version of .NET Framework. @richlander mentioned that there will be articles explaining how to opt-in to Arm64 support for .NET Framework apps -- are they coming soon? Is it required to target .NET Framework 4.8.1 for Arm64 support, or is there a way to opportunistically enable this support for apps targeting lower versions?

There is some documentation published already.  This issue is to track the additional updates which are needed.  Documentation that is already published is: 
Blog post: [https://devblogs.microsoft.com/dotnet/announcing-dotnet-framework-481/](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevblogs.microsoft.com%2Fdotnet%2Fannouncing-dotnet-framework-481%2F&data=05%7C01%7Ctarao%40microsoft.com%7Cd4f95b84888246619ef808da7b12d9e6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637957618145587840%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Jf90IT3ax0nzzViZ04bZZnB0a4Etbk2K82BTLzhuMzo%3D&reserved=0)
Downloads page: [Download .NET Framework | Free official downloads (microsoft.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdotnet.microsoft.com%2Fen-us%2Fdownload%2Fdotnet-framework&data=05%7C01%7Ctarao%40microsoft.com%7Cd4f95b84888246619ef808da7b12d9e6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637957618145587840%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4WcJh3phFfo9%2FZFQW4h9xL2aBsnF8hBQTM4Gtj5ijsI%3D&reserved=0)
Release notes: [https://github.com/Microsoft/dotnet/tree/master/releases/net481/README.md](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2Fdotnet%2Ftree%2Fmaster%2Freleases%2Fnet481%2FREADME.md&data=05%7C01%7Ctarao%40microsoft.com%7Cd4f95b84888246619ef808da7b12d9e6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637957618145587840%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=d6rrqTvDDHYZ1dsix4r8XhB8JPkHeKrmT75j386Iu4Q%3D&reserved=0)

Blog post for Visual Studio 17.3: [https://devblogs.microsoft.com/visualstudio/visual-studio-2022-17-3-is-now-available/](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevblogs.microsoft.com%2Fvisualstudio%2Fvisual-studio-2022-17-3-is-now-available%2F&data=05%7C01%7Ctarao%40microsoft.com%7Cd4f95b84888246619ef808da7b12d9e6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637957618145587840%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SSZ2OE%2FnifJv1BFpS0gUee8qS61xU34Sg7ZwnSj2g48%3D&reserved=0)

**Comment by TaraOverfield** [comment]
I've staged changes for these and more areas needing updates in in this PR: https://github.com/dotnet/docs/pull/30619
- Update .NET Framework versions and dependencies
- Update What's new in .NET Framework
- Update How to: Determine which .NET Framework versions are installed
