### ISSUE TITLE
API reference should include remarks

### ISSUE THREAD

**Issue by svick** [dotnet/docs#307]
I noticed this on `ParallelOptions` ([source](https://github.com/dotnet/corefx/blob/master/src/System.Threading.Tasks.Parallel/src/System/Threading/Tasks/Parallel.cs), [docs](http://dotnet.github.io/api/System.Threading.Tasks.ParallelOptions.html)): The API reference page for the class or its members show the `<summary>`, but not `<remarks>`. I think that remarks should be included in API reference.

**Comment by mairaw** [comment]
@cartermp, @svick found an example of what we were looking for last week to see whether remarks tags are being included in the generated docs or not. The answer is not.
This class is also a good example of the doc/code ratio we were talking about.

/cc @chenkennt

**Comment by chenkennt** [comment]
Remarks is actually supported, but currently the triple slash comments is actually coming from the intellisense files shipped with .NET Framework rather than from corefx repo, those files doesn't have remarks at all. @mairaw do you think we should switch to use comments from source code? I remember the main concern to not use source code is it has much less content than intellisense files (except remarks).

**Comment by mairaw** [comment]
@chenkennt not having content is still a concern for now. We're working towards getting the /// comments into the source. Is it possible to merge those two for now? I thought we were already merging the two inputs. We could choose which one would have the highest priority in case both source and IntelliSense have the same section, but the remarks in this case would show up since it only exists in the source side.

**Comment by mairaw** [comment]
With the launch of [API Browser](https://docs.microsoft.com/en-us/dotnet/api/) yesterday, we can finally close this one. 🎆 

Now, the docs for the .NET API reference don't come directly from the /// comments in the source code. So in some cases we might need to revisit the docs to add the information that is present in the source code.

We'll be bringing those docs over here pretty shortly, so everyone will be able to contribute.

**Comment by MarkPflug** [comment]
These new API docs look fantastic!

Question: how do these new docs align with the documentation that "ships" with Visual Studio? Meaning the documentation that you can install and view in the Microsoft Help Viewer. Will contributions to the new documentation system eventually end up in there as well?

I always preferred the Help Viewer because it was faster to find (via the Index) what I was looking for and navigate around. The online API browser appears to be competitive now (the search box on the main page is delightfully responsive). However, for offline browsing the Help Viewer is still the only option (not a common use-case admittedly).
