### ISSUE TITLE
Stacked Usings Section is confusing to me

### ISSUE THREAD

**Issue by gbrunton** [dotnet/docs#30862]
I'm really confused about what issue you are trying to bring to our attention within this section. Here's a couple of questions.

1. Is the problem you are brining up here inherit to all stacked usings or just await usings?

2. Is this only a problem if you use ConfigureAwait? So if you aren't using ConfigureAwait you can use stacked usings without worry?

3. Within the "Unacceptable Pattern", you seem to be implying that there's an inherent issue with stacked usings such that we would otherwise expect the DisposeAysnc to be called but because of this issue it won't be. But in the code I'd never expect the DisposeAysnc methods to be called since the exception is happening before the await usings. This does not seem to be problem with stacked usings at all. I don't understand how this code is an example of using stacked usings the wrong way. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61a961dc-3ebf-2a96-a6eb-2e0b62ab909f
* Version Independent ID: d72276e1-9059-815f-dc14-a03a7544ab87
* Content: [Implement a DisposeAsync method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync)
* Content Source: [docs/standard/garbage-collection/implementing-disposeasync.md](https://github.com/dotnet/docs/blob/main/docs/standard/garbage-collection/implementing-disposeasync.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hi @gbrunton - thanks for posting this issue. I'll work on clarifying this a bit, as I do agree that it could be stated more clearly.

**Comment by IEvangelist** [comment]
Hi @gbrunton,

I verified a few things with @bartonjs on this matter. I think the missing part in the content text was that I needed to add the eligibility of finalizers. Any time a `.ctor` throws, the object didn't finish, so it can't get disposed. It is eligible for finalization, if it has a finalizer.

**Comment by bartonjs** [comment]
> Is this only a problem if you use ConfigureAwait? So if you aren't using ConfigureAwait you can use stacked usings without worry?

More, or less.

The ConfigureAwait is something that most libraries should be using so that they don't force requests from the UI thread to go back to the UI thread (unless that was intentional, of course).  

For classic IDisposable that's not applicable, so you get nice stacks:

```C#
using (One one = new One())
using (Two two = new Two())
{
  ...
}
```

with IAsyncDisposable and no ConfigureAwait, it looks the same:

```C#
await using (One one = new One())
await using (Two two = new Two())
{
  ...
}
```

except the calls to DisposeAsync now occur on whatever the current synchronization context is instead of being ambient.  So add the ConfigureAwait calls:

```C#
await using (One one = (new One()).ConfigureAwait(false))
await using (Two two = (new Two()).ConfigureAwait(false))
{
  ...
}
```

Except that doesn't compile.  (It would compile had I used `var`, but then there'd be a weird break somewhere else.  This is part of why I generally avoid `var`.)

So the next most obvious thing is to factor out the declarations:


```C#
One one = new One();
Two two = new Two();
await using (one.ConfigureAwait(false))
await using (two.ConfigureAwait(false))
{
  ...
}
```

except now you've changed the functional flow... one.DisposeAsync is not called if `new Two()` throws when it would have before we started adding ConfigureAwait.

If your coding style permits it, there's a hybrid model:


```C#
One one;
Two two;
await using ((one = new One()).ConfigureAwait(false))
await using ((two = new Two()).ConfigureAwait(false))
{
  ...
}
```

but nested side effects are hard for most people to read.

Next up is the most obviously right pattern:


```C#
One one = new One();
await using (one.ConfigureAwait(false))
{
    Two two = new Two();
    await using (two.ConfigureAwait(false))
    {
      ...
    }
}
```

and if you don't like the extra nesting, there's the one time my personal style permits the "braceless using" (and with it one of my few `var`s):


```C#
One one = new One();
await using (one.ConfigureAwait(false))
{
    Two two = new Two();
    await using var ignored = two.ConfigureAwait(false);

    ...
}
```
