### ISSUE TITLE
Future tense for something that now exists

### ISSUE THREAD

**Issue by SteveDunn** [dotnet/docs#30968]
The document references features as future tense: _"Will have"_. This was probably correct at the time of writing, but it might confuse readers now, now that C# 8 is available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc900853-b666-5815-9d69-e408af3e3900
* Version Independent ID: 77f3af83-d0ca-7d48-d06d-0f28f5f05a49
* Content: [Pattern based using and using declarations - C# 8.0 draft specifications](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/using)
* Content Source: [proposals/csharp-8.0/using.md](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-8.0/using.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @SteveDunn 

I agree. This is an issue with all the feature proposals. We're publishing them while the ECMA committee catches up on the [C# standardization effort](https://github.com/dotnet/csharpstandard). We want to keep them as is because they reflect the proposed design of the features.

We'll stop publishing each of these feature specs on docs.microsoft.com as the corresponding feature is added to the latest draft standard.

I'll close this, as we don't plan on changing this article.

**Comment by SteveDunn** [comment]
OK @BillWagner - thank you for the explanation
