### ISSUE TITLE
Elaborate more?

### ISSUE THREAD

**Issue by RyanLiu99** [dotnet/docs#31014]
Not quite understand this paragraph:

> Writing a generalized async return type is an advanced scenario, and is targeted for use in specialized environments. Consider using the Task, Task<T>, and ValueTask<T> types instead, which cover most scenarios for asynchronous code.

Can you elaborate more?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d055727b-c97c-4d25-39b8-a4d3f21d0444
* Version Independent ID: c8a7c6f1-8ee1-5030-db12-3db65a968501
* Content: [Async return types (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/async-return-types)
* Content Source: [docs/csharp/programming-guide/concepts/async/async-return-types.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/async/async-return-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @RyanLiu99 

We think that most `async` methods should use the `Task` and `Task<T>` types for the return value. In a small minority of cases, `ValueTask<T>` provides better performance because it reduces allocations. We think there are very few specialized scenarios where creating a new type for `async` return values will provide benefits. 

With that background, do you think you might need to create a new generalized async return type? If so, I'd like to learn more about the motivating scenario.

**Comment by RyanLiu99** [comment]
Now I got it, didn't quite understand "generalized async return type".   I totally agree with you and happy with what .NET provides now.   Thanks!
