### ISSUE TITLE
Testing the keyword typo in the title

### ISSUE THREAD

**Issue by adegeo** [dotnet/docs#31047]

**Comment by gewarren** [comment]
I'm guessing your regex isn't working property.

**Comment by adegeo** [comment]
yarrp

**Comment by gewarren** [comment]
@adegeo If you don't want it to respond to a close event, you can change the task to a "scheduled search" task instead of an event-based task, and you can specify that the issue should be "open" as one of the conditions. But they don't want it to run more than every 3 hours, so the labels wouldn't necessarily be added as soon as the issue is opened.

Or perhaps there's a way to exclude issue closing events here - https://github.com/dotnet/docs/blob/66d2ae9aa78d98f6b84a23869432ef1197286c62/.github/fabricbot.json#L321-L324.
