### ISSUE TITLE
documentation conflict

### ISSUE THREAD

**Issue by cgeier** [dotnet/docs#31679]
While reading the article [Tutorial: Create a Windows service app](https://learn.microsoft.com/en-us/dotnet/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer#implement-service-pending-status), I noticed:

```
[StructLayout(LayoutKind.Sequential)]
public struct ServiceStatus
{
    public int dwServiceType;
    public ServiceState dwCurrentState;
    public int dwControlsAccepted;
    public int dwWin32ExitCode;
    public int dwServiceSpecificExitCode;
    public int dwCheckPoint;
    public int dwWaitHint;
};
```

If one refers to [SetServiceStatus function (winsvc.h)](https://learn.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-setservicestatus) and [SERVICE_STATUS structure (winsvc.h)](https://learn.microsoft.com/en-us/windows/win32/api/winsvc/ns-winsvc-service_status) one sees the following:

```
typedef struct _SERVICE_STATUS {
  DWORD dwServiceType;
  DWORD dwCurrentState;
  DWORD dwControlsAccepted;
  DWORD dwWin32ExitCode;
  DWORD dwServiceSpecificExitCode;
  DWORD dwCheckPoint;
  DWORD dwWaitHint;
} SERVICE_STATUS, *LPSERVICE_STATUS;
```

According to [Windows Data Types](https://learn.microsoft.com/en-us/windows/win32/winprog/windows-data-types), `DWORD`, is _A 32-bit unsigned integer_ which according to [Built-in types (C# reference)](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/built-in-types), should be `uint`. (or `System.UInt32`) not `int`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 75152e30-b486-3ba0-c606-25ada7347b22
* Version Independent ID: e797ddfe-a9d3-93a4-61bd-fd6dc9b8d6b4
* Content: [Tutorial: Create a Windows service app - .NET Framework](https://learn.microsoft.com/en-us/dotnet/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer)
* Content Source: [docs/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer.md](https://github.com/dotnet/docs/blob/main/docs/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment]
@AaronRobinsonMSFT Can you help with this question? Should a DWORD be mapped as int or uint?

**Comment by AaronRobinsonMSFT** [comment]
@cgeier This is a good question and something we are rather poor at for a few reasons. The primary case though is unsigned integers are not CLSCompliant, which means VB.NET cannot use types with unsigned integers. In practice, since this is at an interop boundary it doesn't matter whether it is signed or unsigned.

**Comment by cgeier** [comment]
@AaronRobinsonMSFT: Would that mean that this is true for C# as well? According to [Native interoperability best practices](https://learn.microsoft.com/en-us/dotnet/standard/native-interop/best-practices#common-windows-data-types), `DWORD` is `uint` in C#.

**Comment by AaronRobinsonMSFT** [comment]
> Would that mean that this is true for C# as well?

No. C# has support for unsigned integers. However, if a type is defined with a `uint` field then it can't be consumed from VB.NET. This means that most older interop documents use `int`. Going forward, it is quite possible to use `uint` if that is desired, but sometimes that is more cumbersome and pedantic for now practical gain. For example, many Win32 APIs state `DWORD` for a length argument for a passed in output buffer length. Consider [`ReadFile()`](https://learn.microsoft.com/windows/win32/api/fileapi/nf-fileapi-readfile), which could be defined as follows in a P/Invoke signature.

```csharp
[DllImport("Kernel32")]
bool ReadFile(
    SafeHandle hFile,
    [Out] byte[] lpBuffer,
    uint nNumberOfBytesToRead,
    ref uint lpNumberOfBytesRead,
    IntPtr lpOverlapped);
```

The issue with this definition is there is no technical need for `nNumberOfBytesToRead` defined as `uint`. In fact it can make use annoying because one must now cast the `Length` property value to `uint` from the passed in buffer. The same is true for the `lpNumberOfBytesRead`, because the caller likely is going to pass that to some other .NET API that accepts `int` for the same `CLSCompliant` reasoning.

Yes, the `DWORD` type represents an unsigned integer, that is true. We define those best practices to help users understand what is most appropriate and accurate. In this case, the sample is a practical example where following the strict guidelines reduces utility.

**Comment by gewarren** [comment]
Thanks @AaronRobinsonMSFT. I'm going to close this issue as resolved now.
