### ISSUE TITLE
any support? or ongoing work?

### ISSUE THREAD

**Issue by bullipatty** [dotnet/docs#31704]
What is this garbage? After leaving StackOverflow SG topics, they lost any support! Only one, at least commenting, is canton7, please get your shit together and at least fix the dependency resolution problems of SGs or document them properly. SGs could offer such an positive development. Having supported SGs on SO and developing my own SGs now feels like such a humiliating time waste...
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 99a4410c-4c8d-0107-845b-9a951bb76682
* Version Independent ID: f1ed9873-3e29-b4bd-2dbb-44dd9a05d790
* Content: [Source Generators](https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview)
* Content Source: [docs/csharp/roslyn-sdk/source-generators-overview.md](https://github.com/dotnet/docs/blob/main/docs/csharp/roslyn-sdk/source-generators-overview.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @bullipatty 

First, there is ongoing work on [incremental source generators[(https://github.com/dotnet/roslyn/blob/main/docs/features/incremental-generators.md). We agree that we need to add more tutorials and examples here. It's a big job, and we want to have a full plan in place, rather than share out incremental pieces. 

Second, I'll encourage you to read our [Code of Conduct](https://github.com/dotnet/docs/blob/main/CODE_OF_CONDUCT.md) and consider editing your issue. Its tone is a clear violation.

I'll close this, as we're already working on the plans to address the concerns.

**Comment by bullipatty** [comment]
I used that Form, your fault for posting it directly to github without mentioning a CoC

[cid:a2b97516-9542-436b-86bb-8a54045e089f]
________________________________
Von: Bill Wagner ***@***.***>
Gesendet: Donnerstag, 13. Oktober 2022 17:32
An: dotnet/docs ***@***.***>
Cc: Patrick Beynio ***@***.***>; Mention ***@***.***>
Betreff: Re: [dotnet/docs] any support? or ongoing work? (Issue #31704)


Hi @bullipatty<https://github.com/bullipatty>

First, there is ongoing work on [incremental source generators[(https://github.com/dotnet/roslyn/blob/main/docs/features/incremental-generators.md). We agree that we need to add more tutorials and examples here. It's a big job, and we want to have a full plan in place, rather than share out incremental pieces.

Second, I'll encourage you to read our Code of Conduct<https://github.com/dotnet/docs/blob/main/CODE_OF_CONDUCT.md> and consider editing your issue. Its tone is a clear violation.

I'll close this, as we're already working on the plans to address the concerns.

**Comment by bullipatty** [comment]
Updated and tried to be more constructive.
