### ISSUE TITLE
https://aka.ms/dotnet-install-templates has bad redirect + No "Install templates docs"

### ISSUE THREAD

**Issue by rachelappel** [dotnet/docs#3178]
Originally opened by @shanselman at https://github.com/aspnet/Docs/issues/4018
Asked to move here per @danroth27 

With SDKs backward compatible (without global.json) it possible to create a .NET Core 1.1 application by using the new version, such as
`dotnet new console --framework netcoreapp1.1`
This returns with an error that this is not a valid value for –framework and a link to install additional templates:  https://aka.ms/dotnet-install-templates
It would be ideal if this link showed how to install a template for .NET Core 1.1 with the the .NET Core 2.0 SDK as well as the general "how to install templates" topic. 
However, this aka link redirects to Introduction to ASP.NET Core: https://docs.microsoft.com/en-us/aspnet/core/

I see a few to-dos here:

- [ ] Create "how to install dotnet new CLI templates" topic
- [ ] How to install .NET 1.1 templates while using the .NET 2.0 CLI
- [ ] Update the https://aka.ms/dotnet-install-templates link

/cc @mlorbetske @RickAndMSFT 

From Mike, some starter text:

To install the 1.0 and 1.1 project templates, please run one or more of the following commands

For web templates:
dotnet new -i Microsoft.DotNet.Web.ProjectTemplates.1.x::1.0.0-*

For class library or console apps:
dotnet new -i Microsoft.DotNet.Common.ProjectTemplates.1.x::1.0.0-*

For unit test projects:
dotnet new -i Microsoft.DotNet.Test.ProjectTemplates.1.x::1.0.0-*

**Comment by mlorbetske** [comment]
cc @sayedihashimi

**Comment by mairaw** [comment]
@sayedihashimi for some reason I can't find that aka.ms link in the tool even though I should have permissions (since when I tried to create it again, it tells me that you and ddfwlink are the owners). It seems that since that issue was created for aspnet/docs, you created a help topic in one of the repos and changed the aka.ms link to that. 

We already have a topic that covers custom templates, including installation:
https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates#installing-a-template

Should I just update that topic to include that info and then we change aka.ms link and delete that other topic?

**Comment by sayedihashimi** [comment]
@mairaw the end-user will see this error whenever they try to invoke a template which is not installed. One very common case of that is a user trying to create a 1.1 project after installing 2.0. In that case the linked doc is not very helpful. I'd like to link to a page which includes that info since it will be a common case when visiting the link.

**Comment by mairaw** [comment]
@sayedihashimi yep, I understand that. What I was proposing is to add that info to that existing doc. Do you agree with that?

**Comment by sayedihashimi** [comment]
Sounds good
