### ISSUE TITLE
We need better documentation please!

### ISSUE THREAD

**Issue by oscarvarto** [dotnet/docs#3180]
# dotnet cli needs better documentation (including F# please!)

F# is a "first-class member of .NET" https://docs.microsoft.com/en-us/dotnet/fsharp/ 
but it is very hard to find the correct way to use dotnet with F#.

# General

I tried with `$ dotnet new console -lang F# -f net462` to use .NET 4.6.2 on mono (also with net461) and I get an error because neither net461 nor net462 are valid values for -f (Framework) flag

I could easily solve this problem by myself if I could find documentation on the "valid values for -f (Framework)" flag.

Also, the `$ dotnew new console --help` output is not enough
It doesn't say anything about the correct switch values... The --help message is not very helpful

Something like `$ dotnet new console -lang F# --target-framework-override net462 -o hello` works!  
Found some examples here https://github.com/Microsoft/visualfsharp/issues/3303#issue-240393680

But it shouldn't be necessary to dig in a lot of github issues for my "first-class member of .NET" language...

Now I don't know how to run my build with mono (I want/need type providers. But dotnet core still doesn't support TP: https://github.com/Microsoft/visualfsharp/issues/3303)

I followed this comment, https://github.com/Microsoft/visualfsharp/issues/3303#issuecomment-316256202 , and using 

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="$(OS)=='Unix'">
    <FscToolPath>./tools</FscToolPath>
    <FscToolExe>fsharpc.exe</FscToolExe>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
```

with a `./tools/fsharpc.exe` file:
```
#!/usr/bin/env sh
mono /Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/fsharp/fsc.exe --exename:$(basename "$0") "$@"
```

I can compile with `$ dotnet build`, but cannot run with `$ dotnet run`

By the way, I also had to add this to my `~/.zshenv`:
```
export FrameworkPathOverride=/Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/4.6.2-api
```

Maybe https://github.com/TheAngryByrd/dotnet-mono is the answer? But hell, it demands a lot of will to keep digging hours and hours to use my "first-class member of .NET"-language 😞

**Comment by cartermp** [comment]
The documentation specifies valid values for `-f` [here](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new?tabs=netcore2x#template-options).  If you think that `net462` or other values should be added, the correct place to file an issue is the [CLI repository](https://github.com/dotnet/cli).  We'll update the documentation here to reflect the product if a change is made.

Suggestions about improving `--help` should be created as an issue on the [CLI repository](https://github.com/dotnet/cli), because this is a change that has to happen to the product.  We'll update any relevant info in the docs as necessary.

`--target-framework-override` doesn't seem to be documented.  Seems like something which should be on that page.  @mairaw @nguerrera is this accurate?

Type Provider support on .NET Core is still in progress (as specified in the issue you've linked, and our [official blog post](https://blogs.msdn.microsoft.com/dotnet/2017/08/14/f-and-net-core-roadmap-update/)).  We will not be documenting the workaround, as sort of a hacky state of affairs.

**Comment by mairaw** [comment]
Yes, I was discussing with @KathleenDollard, @mlorbetske and @livarcocc about this one offline after seeing on gitter and suggesting @oscarvarto to open an issue here. 

It seems that `--target-framework-override` was left on purpose out of --help and therefore was not included on docs. I'll need confirmation from the CLI team on whether we want to add that or not.

Also, `-f|--framework` is also not documented for console apps even though the template seems to have that and help doesn't show that. Is `--framework` really supported for the console template? If so, what are the expected values and scenario where this is used since it's not used for .NET Framework apps.

**Comment by tdykstra** [comment]
> `-f|--framework` is also not documented for console apps even though the template seems to have that and help doesn't show that. Is `--framework` really supported for the console template?

`--framework`  for console apps was added to the doc along with a link to valid values in #14356, closing this issue.
