### ISSUE TITLE
Exact Rulesets of AnalysisMode options

### ISSUE THREAD

**Issue by AndreasHoersken** [dotnet/docs#32093]
Hi all,

is there a description. which rules are activated by the different AnalysisMode-Options (i.e. None, Minimum, Recommended, All, cp. https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview#enable-additional-rules)? Which option activates the default-rules (cp. https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview#enabled-rules) ?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f8906b2c-b984-0427-d064-829e7ea2fc55
* Version Independent ID: 128f9903-971d-6a66-a2cb-9b12acbc55e7
* Content: [Code analysis in .NET](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview)
* Content Source: [docs/fundamentals/code-analysis/overview.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/overview.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

---
[Associated WorkItem - 45470](https://dev.azure.com/msft-skilling/Content/_workitems/edit/45470)

**Comment by gewarren** [comment]
@AndreasHoersken You can look at the different preconfigured .editorconfig files in this directory to see which rules are enabled for `Default`, `Minimum`, and `Recommended`: %ProgramFiles%\dotnet\sdk\7.0.100\Sdks\Microsoft.NET.Sdk\analyzers\build\config. For example, the file to look at for `Minimum` is *%ProgramFiles%\dotnet\sdk\7.0.100\Sdks\Microsoft.NET.Sdk\analyzers\build\config\analysislevel_6_minimum.editorconfig*.

@mavasani I expected to see "analysis level 7" files in this directory since it's .NET SDK version 7.0.100. Do you know why I don't see them?

**Comment by mavasani** [comment]
> @mavasani I expected to see "analysis level 7" files in this directory since it's .NET SDK version 7.0.100. Do you know why I don't see them?

this was fixed recently, which version of the SDK do you have?

**Comment by gewarren** [comment]
@mavasani I have 7.0.100:

C:\>dotnet --list-sdks
3.1.425 [C:\Program Files\dotnet\sdk]
6.0.202 [C:\Program Files\dotnet\sdk]
6.0.306 [C:\Program Files\dotnet\sdk]
7.0.100 [C:\Program Files\dotnet\sdk]
