### ISSUE TITLE
Unit Test for Converter

### ISSUE THREAD

**Issue by sgbhagwath** [dotnet/docs#32520]
[Enter feedback here]
Could you all add an example of a unit test for one of the converters Read method, e.g., DateTimeConverterUsingDateTimeParse. One of the parameters passed to the read method should be a ref struct, Utf8JsonReader. I am interested in knowing how you would mock the ref struct.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5de37d79-751f-e372-e866-efde28f4908c
* Version Independent ID: 678c4f23-764a-7ccd-0d6d-159a30957477
* Content: [How to write custom converters for JSON serialization - .NET](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/converters-how-to?pivots=dotnet-7-0)
* Content Source: [docs/standard/serialization/system-text-json/converters-how-to.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json/converters-how-to.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@eiriktsarpalis Can you help with this question?

**Comment by eiriktsarpalis** [comment]
The `Utf8JsonReader` cannot be mocked unfortunately, since it's a struct. You would need to create an instance using [one of its constructors](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonreader.-ctor?view=net-7.0), so typically this would involve creating a JSON payload that would trigger the desired behavior you need to test for.

**Comment by gewarren** [comment]
I'm going to close this as answered. Thanks Eirik.
