### ISSUE TITLE
Move the "Hello World" section from Tour of C# to the new Overview section

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#3276]
This new page will take the updated "Hello World" section from the Tour of C#

**Comment by BillWagner** [comment]
I reviewed the existing "Tour of C#" sections this afternoon, and there is more work here than just updating the opening of the tour.  Here are my observations:

1. ***The Tour of C# section closely follows the top level organization of the C# Programming Guide***. There's significant redundancy in these two sections. Because of the redundancy, the Tour can be shortened to one or two articles as an overview, with several links to the similar sections in the Programming Guide.
1. ***The Tour of C# does not mention many of the newer features of C#.*** Examples are:

     - LINQ

**Comment by rpetrusha** [comment]
This looks good, @BillWagner. A couple of comments:
- What I don't get a good sense of is how the tour content differs from the programming guide content, and how they in turn differ from some of the quickstarts. (For example, how does the string interpolation tour differ from the string interpolation quickstart?) I would think that the tour should present a very bare-bones, simple introduction to each of these areas, with the detail in the programming guide section. I think that it would be helpful to more explicitly define what a tour is, as opposed to a programming guide topic, a quick start, and a getting started (which I'm wondering whether we should remove, since they're the .NET Core folder). 
- There's some redundancy (possibly) between **Types and Variables** in **Index** and **Classes and Objects** in **Creating types**. That's probably more than legitimate, though.
- Should delegates be added to the **Creating types** section, rather than **Program building blocks**?
- I'm not sure that I would drop arrays, especially given the number of APIs that take arrays rather than collection objects as parameters. Perhaps arrays and collections?
- From the viewpoint of a tour, I'm wondering about generics as a feature area. Assuming that the tours are fairly simple, generics can be covered by collections, nullable, and perhaps some combination of delegates (like Action\<T...> and Func\<T....>) and async.
- It might be good to add lambda expressions in the building blocks section.

**Comment by pkulikov** [comment]
@BillWagner @rpetrusha several observations from my side.

>The Tour of C# does not mention many of the newer features of C#. Sadly, "newer" here starts with version 2.0.

The "What's new in..." articles can be viewed as language tours:
https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-6 (covers string interpolation)
https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7 (covers tuples and pattern matching)

Those articles constitute a (not complete) tour of C# from the chronological point of view. 

>The entire section "Tour of C#" gets replaced with a small set of articles.

Let me bring this suggestion to its limit (maybe, not realizable). What if the "Tour of C#" is replaced with **one** article that might be the introduction page of the programming guide:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/

That page now is almost the mere list of links that duplicates the TOC. By the way, that page contains the following sentence:
>If you are a complete beginner with programming or with C#, you might want to visit the C# Quickstarts or Getting Started with C# interactive tutorial, where no prior programming knowledge is required.

Note that is refers to the quickstarts as the way to get the first impression of the language. Here I agree with @rpetrusha 
>What I don't get a good sense of is how the tour content differs from the programming guide content, and how they in turn differ from some of the quickstarts. 

So, maybe the "Tour of C#" should be removed/split in two parts:
- the introduction page of the programming guide that might briefly describe the content of the guide
- revised current and new quickstarts: I've observed several remarks that the current string interpolation quickstart is too big step from other quickstarts. So, the parts of the "Tour of C#" that do not fit the programming guide might be converted to quickstarts to cover the existing gap is the set of quickstarts.

At last, some of the "Tour of C#" articles duplicate language reference:
https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/expressions (the list of the operators at the second half of the page should be replaced with the link to [C# operators](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/))

https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/statements (it's heavily about C# keywords)

**Comment by BillWagner** [comment]
Great feedback @rpetrusha @pkulikov 

The key observations is these:  

> Let me bring this suggestion to its limit (maybe, not realizable). What if the "Tour of C#" is replaced with one article that might be the introduction page of the programming guide:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/

> I would think that the tour should present a very bare-bones, simple introduction to each of these areas, with the detail in the programming guide section. 

Yes! This is exactly what I'd hope to do. When I built the outline, I'm concerned it's too long. If I can shrink it to one article, I will. Note that instead of the "programming guide", it will be an overview of C#. It would be here: https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp in the TOC.

So, the "Tour of C#" would be the overview.

> There's some redundancy (possibly) between Types and Variables in Index and Classes and Objects in Creating types. That's probably more than legitimate, though.

Likely true. I want to minimize it. I take that as a first draft task.

> Those articles (what's new...) constitute a (not complete) tour of C# from the chronological point of view.

Yes, but those don't help the audience that has never used earlier versions. This would present the current C# language as a holistic thing.

> So, maybe the "Tour of C#" should be removed/split in two parts:
> - the introduction page of the programming guide that might briefly describe the content of the guide
> - revised current and new quickstarts. So, the parts of the "Tour of C#" that do not fit the programming guide might be converted to quickstarts to cover the existing gap is the set of quickstarts.

I like that idea a lot. That probably expands the scope into several PRs. I'll propose scoping this to the first bullet, linked to the existing quickstarts where appropriate.

> At last, some of the "Tour of C#" articles duplicate language reference:

Yes, and that's something that should be removed and linked to the reference for details, and more quickstarts for examples.

Here's version 2:

**Proposal:**

The entire section "Tour of C#" gets replaced with overview article(s) and links to quickstarts. The purpose of the *Tour of C#* is to provide an *overview* of the language.  To provide samples for different areas, there are links to interactive quickstarts.

The outline will be updated in the next comment. (Working with 📓 to sketch out ideas now).

**Comment by svick** [comment]
@BillWagner In another channel, you said:

> You can help by identifying the aspects of C# you use to convince others to try it.

When I try to convince people to use C#, they're usually already an experienced programmer that knows other languages, so I tell them what I see as problems in the languages they know that C# solves, while also trying to convince them that what they like in that language is still in C#.

E.g. if they know Python, I would tell them about static typing and type inference, so they don't have to write types everywhere. If they know C++, I would tell them about the GC, fast compilation times and also performance-related features (`struct`, `Span`, `unsafe`, etc.). In any case, I would also mention that C# is cross-platform, because I think C# still has a reputation as a Windows-only language (even though that's more about .Net than C#).

I would not tell them about classes or enums, because they already know what those are.

Though I'm not sure if this answer is of any use when deciding what to include in the "Tour of C#".

**Comment by carloscds** [comment]
@BillWagner 
A topic about namespaces, explain what is and how can I use. 
Some topic about a project struct, for example: CSharp Project File, references (maybe a link to another doc), 
IDEs that I can use, for example Visual Studio and Visual Studio Code (maybe a link to another doc)
A referente to kind of projects that we can create using C#: client, web and mobile. Linking to another docs.

**Comment by BillWagner** [comment]
I asked for some internal feedback from @IEvangelist on the tour.  Here's the response:

- The organization of the TOC might be an opportunity for improvement, when perusing the articles Program structure starts with a CLI tool the user is probably unfamiliar with – and then immediately starts with a block of code that introduces, namespace and class.
 - This feels a bit jolting as I see that there is an entire article dedicated to Classes and objects, seems like this should perhaps be reordered?
  - I could easily see Interfaces being immediately after Classes and objects
- I’m curious as to whether or not the following common C# concepts should be introduced in the Tour:
  - Under Expressions (even if only links to more information about them to raise awareness)
    - Lambda expressions
    - Throw expressions
    -Expression-bodied members
  - Statements
    - It might be great for someone learning C# to have a corresponding of each statement, like a common use case.
      - For example, lock statement – when should I use lock and what does the statement do?
      - Try / catch, what does that do? If learning C#, I might not have any idea…
  - Classes and objects
    - Should we mention struct in here, as a structure that could represent an object and maybe a tuple?
      - Feels like the tour started talking about how C# thinks of OOP, then quickly converged into semantics – it’s a mix of conceptual and how-to (which I suppose is desired for a tour)
  - Delegates
    - This is the perfect articles to include examples of lambda expressions, and how Func and Action are in fact delegates, etc
  - Attributes
    - As someone learning C#, why do I care about attributes, when should I use them? This articles talks about what they are and how to use them, but not why
    - Since this is currently the last article in the Tour, where do we go next? There is no continuation from here, or next steps.
 
It might be cool to have the tour enable interactive C# for these bits. Some additional thoughts are that some of the code examples could benefit from a sweeping clean up, all minor things of course – but general formatting, best practices and modernizing.
