### ISSUE TITLE
Example Appears to Cause an Infinite Loop if Copied Verbatim from this Page

### ISSUE THREAD

**Issue by kcragin** [dotnet/docs#32782]
The example on this page of removing tasks from the list appears to be incorrect. Please double-check that the correct task is being removed from the list. In my [StackOverflow answer](https://stackoverflow.com/questions/74479812/waiting-for-multiple-external-events-in-durable-azure-functions-and-act-on-them/74617770#74617770), you can see my answer, which explains that the programmer could inadvertently code an infinite loop. The answer also explains how to fix the problem, so you might be able to incorporate that into your docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4d15bb1b-5f7f-20f3-78c3-d2b5bce950ed
* Version Independent ID: 80bee493-257b-5c64-4f28-cfb4e9bae560
* Content: [Process asynchronous tasks as they complete](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/start-multiple-async-tasks-and-process-them-as-they-complete?pivots=dotnet-7-0)
* Content Source: [docs/csharp/programming-guide/concepts/async/start-multiple-async-tasks-and-process-them-as-they-complete.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/async/start-multiple-async-tasks-and-process-them-as-they-complete.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks @kcragin 

The code in the sample is correct, but we should add a note to clarify what's happening.

The result of `Task.WhenAny()` is a `Task<Task<int>>`. 

That method call is `await`ed. The result of the `await` is the `Task<int>`. And, that's the task that should be removed from the list.

It's easier to see in this example because it's a `Task<int>`, rather than a `Task`. In scenarios where `Task.WhenAny` returns a `Task<Task>`, it's easier to fall into the situation you describe.

We should add a note to explain that.

**Comment by kcragin** [comment]
Oh, right. I was away from C# for a while and got hung up on `Result` too while answering that question. Thanks for your response.
