### ISSUE TITLE
Missing correct way to validate enum parameter

### ISSUE THREAD

**Issue by dimabarbul** [dotnet/docs#33204]
In documentation at [Parameter Design](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/parameter-design) page under **Validating Arguments** section there is a point `❌ DO NOT use Enum.IsDefined for enum range checks.`.
It would be great if the documentation provided the reason to not use `Enum.IsDefined` and the correct way to validate enum parameter.

**Comment by gewarren** [comment]
@billwagner as the owner of the design guidelines docs.

**Comment by gewarren** [comment]
@dimabarbul I found the answer in [an older version of this article](https://learn.microsoft.com/en-us/previous-versions/dotnet/netframework-3.5/ms229025(v=vs.90)):

"Do not use System.Enum.IsDefined(System.Type,System.Object) for enumeration range checks as it is based on the runtime type of the enumeration, which can change from version to version.

A later version of a library can add values to a shipping enumeration. Using `IsDefined` for data validation can be dangerous because existing code (which did not handle the new value) will treat the new value as valid input because `IsDefined` returns true for the new value. Check that the input is in the range of values your program can support and throw an exception if it is not."

Since this article is taken from copyrighted material, we're unable to add the extra information to it, unfortunately.
