### ISSUE TITLE
macOS prerequisites: open files limit in 2.0.2+

### ISSUE THREAD

**Issue by dasMulli** [dotnet/docs#3338]
The macOS prerequisites doc has a section "Increase the maximum open file limit" detailing how to set a system-wide higher open file limit for processes using `launchd`/`launchctl` or `ulimit`.

Since https://github.com/dotnet/coreclr/pull/14054 has been merged and will be part of the 2.0.2 release, this should no longer be necessary as this appears to have been a bug in CoreCLR trying to set a higher limit itself, but with a wrong value. The value should now be set automatically to the system's highest allowed value (~10500 IIRC) and no manual intervention is needed.

cc @mairaw

**Comment by mairaw** [comment]
Thanks @dasMulli.
 
@leecow @janvorli this issue is for the following topic:
https://docs.microsoft.com/en-us/dotnet/core/macos-prerequisites?tabs=netcore2x#increase-the-maximum-open-file-limit 

When we release .NET Core 2.0.2, should we keep that info but note that is only applicable to older versions?

**Comment by leecow** [comment]
A note indicating the setting is more likely to be needed in older versions of Core sounds like the right edit.

**Comment by janvorli** [comment]
Yes, the setting is only applicable in older versions, in the 2.0.2, it doesn't make sense, we already set it to the max possible value in the PAL.

**Comment by mairaw** [comment]
Ok thanks for the feedback @leecow @janvorli!

**Comment by chrisckc** [comment]
Hi, i downloaded and installed dotnet-sdk-2.0.3-osx-gs-x64.pkg yesterday and had to increase the open file limit to much more than 2048 to get the dotnet command to work properly.

Initially set the open file limit to 2048 as suggested in the current documentation (using the suggested method) before i even tried the dotnet cli, but i found that i was unable to run "dotnet --version" , "dotnet new" or "dotnet restore" without getting seemingly random errors regarding not being able to load various assemblies etc. Due to the errors not being consistent it made me suspect the open file limit could still be an issue.

Here are some examples of the errors to help anyone searching to find this post:

`$dotnet new
Getting ready...
Error: Could not install "/usr/local/share/dotnet/sdk/2.0.3/Templates/microsoft.dotnet.web.itemtemplates.2.0.3.nupkg".
Error: Error getting value from 'TemplateInfo' on 'Microsoft.TemplateEngine.Edge.Settings.TemplateCache'.
Error: Could not install "/usr/local/share/dotnet/sdk/2.0.3/Templates/microsoft.dotnet.common.projecttemplates.2.0.1.0.0-beta2-20170810-304.nupkg".
Error: Error getting value from 'TemplateInfo' on 'Microsoft.TemplateEngine.Edge.Settings.TemplateCache'.
Error: Could not install "/usr/local/share/dotnet/sdk/2.0.3/Templates/microsoft.dotnet.web.spa.projecttemplates.2.0.3.nupkg".
Error: Error getting value from 'TemplateInfo' on 'Microsoft.TemplateEngine.Edge.Settings.TemplateCache'.
Error: Could not install "/usr/local/share/dotnet/sdk/2.0.3/Templates/microsoft.dotnet.web.projecttemplates.2.0.2.0.3.nupkg".
Error: Error getting value from 'TemplateInfo' on 'Microsoft.TemplateEngine.Edge.Settings.TemplateCache'.
Error: Could not install "/usr/local/share/dotnet/sdk/2.0.3/Templates/microsoft.dotnet.common.itemtemplates.1.0.0-beta2-20170810-304.nupkg".
Error: Error getting value from 'TemplateInfo' on 'Microsoft.TemplateEngine.Edge.Settings.TemplateCache'.
Error: Could not install "/usr/local/share/dotnet/sdk/2.0.3/Templates/microsoft.dotnet.test.projecttemplates.2.0.1.0.0-beta2-20170810-304.nupkg".
Error: Error getting value from 'TemplateInfo' on 'Microsoft.TemplateEngine.Edge.Settings.TemplateCache'.
Error getting value from 'TemplateInfo' on 'Microsoft.TemplateEngine.Edge.Settings.TemplateCache'.
Could not load file or assembly 'System.Reflection.Emit.Lightweight, Version=4.0.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. A device attached to the system is not functioning.
 (Exception from HRESULT: 0x8007001F)
   at System.Linq.Expressions.Compiler.LambdaCompiler..ctor(AnalyzedTree tree, LambdaExpression lambda)`

`$ dotnet --version
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.DotNet.Cli.Utils.Reporter' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.IO, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. A device attached to the system is not functioning.
 (Exception from HRESULT: 0x8007001F)
   at Microsoft.DotNet.Cli.Utils.Reporter.Reset()`

`$ dotnet new webapi
The template "ASP.NET Core Web API" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/template-3pn for details.

Processing post-creation actions...
Running 'dotnet restore' on /Users/username/Documents/Development/DotNetProjects/dotnetcore2-test/dotnetcore2-test.csproj...

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.DotNet.Cli.Utils.Reporter' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Console, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. A device attached to the system is not functioning.
 (Exception from HRESULT: 0x8007001F)
   at Microsoft.DotNet.Cli.Utils.Reporter.Reset()`

After trying many commands, this was the only command which actually showed a meaningful error message:

`$ dotnet new -l
System.IO.IOException: Too many open files in system`

After setting my max open files to 524288, the problem was solved. I didnt want to start messing about gradually increasing it.
I also set max proc to 2048 while i was at it for good measure.

You can check the current settings on macOS using:
`$ launchctl limit`

I am definitely running 2.0.3 here is the output of dotnet --version now that its working:

`$ dotnet --version
2.0.3
`
I am running macOS High Sierra 10.13.1 with 16GB RAM

If this is still an issue the documentation needs to be updated to reflect the higher limit that is required.

**Comment by janvorli** [comment]
@chrisckc this is strange, the 2.0.3 SDK should now contain 2.0.3 runtime that should not need any change in the max open files, since the runtime should set it to the maximum possible value. I've fixed that in #14054 and verified that the fix caused the limit to be set to the maximum possible value. So I wonder what's going on. Let me try to test the published 2.0.3.

**Comment by janvorli** [comment]
I have tried the tar.gz packaged SDK from here "https://www.microsoft.com/net/download/thank-you/dotnet-sdk-2.0.3-macos-x64-binaries" and it worked fine for me. I suspect that either the .pkg version is wrong or somehow, it is trying to incorrectly use older runtime already present on your machine. 
Can you also dump the `dotnet --info` please?

Btw, the output of `launchctl limit` on my device is:
```sh
janvorli-mac:dotnet janvorli$ launchctl limit
        cpu         unlimited      unlimited
        filesize    unlimited      unlimited
        data        unlimited      unlimited
        stack       8388608        67104768
        core        0              unlimited
        rss         unlimited      unlimited
        memlock     unlimited      unlimited
        maxproc     709            1064
        maxfiles    256            unlimited

```

Can you also please try to download the .tar.gz version to any folder, untar it there and run the ./dotnet from that folder?

**Comment by chrisckc** [comment]
`$ which dotnet`
>/usr/local/share/dotnet/dotnet

This is from the dotnet executable in my env path variable which was installed by the pkg file that i originally downloaded

`$ dotnet --info`
>.NET Command Line Tools (2.0.3)

>Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  eb1d5ee318

>Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.3/

>Microsoft .NET Core Shared Framework Host

 > Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

Output from the dotnet executable in the tar.gz file downloaded from the link:

`dotnet-sdk-2.0.3-osx-x64 $ ./dotnet --info`
>.NET Command Line Tools (2.0.3)

>Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  eb1d5ee318

>Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /Users/chrisclaxton/Downloads/dotnet-sdk-2.0.3-osx-x64/sdk/2.0.3/

>Microsoft .NET Core Shared Framework Host

>  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

They seem to be identical.

I will later attempt to recreate the issue by reverting my max files setting back to the default. I will also then try the dotnet executable from the downloaded tar.gz file. Don't really want to reboot my machine just yet.

**Comment by dasMulli** [comment]
> After setting my max open files to 524288, the problem was solved

How did you do that? The maximum value supported on macOS by default is `10500`. At least what the API will let you set and is what the 2.0.3 runtime will set. If you really need more, it's going to be complicated.

I'm a bit curious that you hit the issue with `dotnet --version` - that really doesn't load much. The failures previously only occurred when restoring target NuGet graphs without cache and fallback folder or loading rest projects with lots of dependencies. So `dotnet new` can trigger this but `dotnet --version` always worked with the default `256` limit.

**Comment by chrisckc** [comment]
@dasMulli i just set that value in the limit.maxfile.plist file i created inside /Library/LaunchDaemons/

`$ cat limit.maxfiles.plist `
><?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
        "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>limit.maxfiles</string>
    <key>ProgramArguments</key>
    <array>
      <string>launchctl</string>
      <string>limit</string>
      <string>maxfiles</string>
      <string>524288</string>
      <string>524288</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>ServiceIPC</key>
    <false/>
  </dict>
</plist>

**Comment by chrisckc** [comment]
Ok, i have tried to recreate the issue and failed to do so, which is not a surprise to be honest.
Before i did anything here is the output of the 2 commands:
`$ ulimit -a`
>core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 2048
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 2048
virtual memory          (kbytes, -v) unlimited


`$ launchctl limit`
>	cpu         unlimited      unlimited      
	filesize    unlimited      unlimited      
	data        unlimited      unlimited      
	stack       8388608        67104768       
	core        0              unlimited      
	rss         unlimited      unlimited      
	memlock     unlimited      unlimited      
	maxproc     2048           2048           
	maxfiles    524288         524288         
	
I removed the limit.maxfiles.plist and rebooted, now i get this:
	
`$ ulimit -a`
>core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 2048
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1418
virtual memory          (kbytes, -v) unlimited

`$ launchctl limit`
>	cpu         unlimited      unlimited      
	filesize    unlimited      unlimited      
	data        unlimited      unlimited      
	stack       8388608        67104768       
	core        0              unlimited      
	rss         unlimited      unlimited      
	memlock     unlimited      unlimited      
	maxproc     1418           2128           
	maxfiles    256            unlimited  
	
The dotnet command still works, i tried the commands which failed before and they are fine.
I noticed that "ulimit -a" was still reporting 2048 so i removed "ulimit -n 2048" from etc/profile which i added according to the docs.

After reboot i now get this:

`$ ulimit -a`
>core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 256
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1418
virtual memory          (kbytes, -v) unlimited

`$ launchctl limit`
>	cpu         unlimited      unlimited      
	filesize    unlimited      unlimited      
	data        unlimited      unlimited      
	stack       8388608        67104768       
	core        0              unlimited      
	rss         unlimited      unlimited      
	memlock     unlimited      unlimited      
	maxproc     1418           2128           
	maxfiles    256            unlimited   
 
The dotnet command still works now that my max files is set to 256. I also checked ~/.bash_profile to make sure it didn't contain anything that would effect max files.

In the output of "launchctl limit", i now have 256 as the soft limit, the hard limit is unlimited. In  theory i should now have the default settings for macOS High Sierra.
 
I did a bit more digging, it seems that the method of setting the limits is different depending on the version of macOS, in Sierra it seems to be the  /Library/LaunchDaemons/  plist file method, the 2 limits in the plist file are the soft and hard limits respectively. Regardless of those limits they cannot exceed the kernel maxfiles limits.

`$ sysctl kern.maxfiles kern.maxfilesperproc`
>kern.maxfiles: 49152
kern.maxfilesperproc: 24576

I will continue and let you know if i encounter the issue again with the default settings now back in place.
Just curious, how exactly does the dotnet command now set the maxfiles limits?
Thanks

**Comment by dasMulli** [comment]
See https://github.com/dotnet/coreclr/blob/d664f5ff1c7a8463c552c0eb6163999452c39694/src/pal/src/init/pal.cpp#L1056-L1085

it calls `setrlimit()` which according to [Apple's doc](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man2/setrlimit.2.html) only accepts up to `OPEN_MAX`, which is currently 10500 (which is also the maximum you can pass to `ulimit -n`)

**Comment by mairaw** [comment]
@JRAlexander since you now own the prereqs, I'm assigning this one to you. I changed milestone to Q2.
