### ISSUE TITLE
Provide step-by-step documentation to install dotnet sdk on WSL

### ISSUE THREAD

**Issue by alelom** [dotnet/docs#33654]
[Enter feedback here]
With the current documentation, I get the "Unable to locate package" error right at the start, and the troubleshooting does not point at any specific WSL solution. I got the help I needed [from the first google result instead](https://www.dotnetthailand.com/programming-cookbook/wsl-powershell-useful-scripts/install-dotnet).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#troubleshooting)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **.net**
* Technology: **dotnet-installation**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hi @alelom sorry this issue got lost to time. We rewrote this documentation about a month ago, vastly redesigning it. However, I'm unsure why you would have had problems with WSL2, the instructions are the same regardless of Ubunut in a VM, physical machine, docker container, or even in WSL2.

I don't think there is anything I can do right now, since we really redesigned this article. If you run into a problem, please feel free to open a new issue. Again, sorry for the delay.
