### ISSUE TITLE
Is the "development" computer the Windows box or the Raspberry Pi?

### ISSUE THREAD

**Issue by DougAtClir** [dotnet/docs#33756]
Need to clarify **"development"** computer. 

In the text below, does **development** mean the Windows box or the Pi?

> **Set up launch.json in Visual Studio Code**
> On the **development** computer, add a launch configuration to the project's launch.json.
> 

- Where does the code that I am debugging physically reside? Is it on the Windows or Raspberry Pi? Some articles say code does not have to be on the Windows box. 

- Also, which .NET 7 components need to be installed on the Windows machine that runs VS Code? 

- Is the code for the Pi built on Windows or is it build on the Pi? This will have a bearing on the .NET components that I need to install on the Windows box.

- Launch the debugger - I am assuming this is from VS Code on the Windows box?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f3e5dc95-a3a8-1cc6-049e-773e31449079
* Version Independent ID: 171f8840-fa9a-9174-2628-f3a9f6d0915e
* Content: [Debug .NET apps on Raspberry Pi](https://learn.microsoft.com/en-us/dotnet/iot/debugging?tabs=self-contained&pivots=vscode)
* Content Source: [docs/iot/debugging.md](https://github.com/dotnet/docs/blob/main/docs/iot/debugging.md)
* Product: **dotnet**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

---
[Associated WorkItem - 61247](https://dev.azure.com/msft-skilling/Content/_workitems/edit/61247)

**Comment by CamSoper** [comment]
You *can* install VS Code and the .NET SDK on the Pi. The problem is that the default version of Raspberry Pi OS is 32-bit, and Omnisharp (the C# plugin for VS Code) doesn't support 32-bit ARM.

If you're using 64-bit Raspberry Pi OS, you can run the whole stack on the Pi, you just probably won't be happy with the performance. That's why I recommend using a PC for your development and just deploying to the Pi. I'll add a callout to this doc Monday that clarifies this.

Your development PC doesn't have to be Windows. It can be Linux or macOS too.
