### ISSUE TITLE
don't use 'var' in your examples and show the actual type, please.

### ISSUE THREAD

**Issue by jhp518** [dotnet/docs#33892]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ae769054-b1de-d528-baab-ea2a275d2a72
* Version Independent ID: b5130725-9cfc-5424-53b6-a6b0860aa6fc
* Content: [Group query results (LINQ in C#)](https://learn.microsoft.com/en-us/dotnet/csharp/linq/group-query-results)
* Content Source: [docs/csharp/linq/group-query-results.md](https://github.com/dotnet/docs/blob/main/docs/csharp/linq/group-query-results.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @jhp518 

It's customary in LINQ queries to use `var` (implicitly typed local variables), rather than the explicit type. The first example in this article shows one example: The result of the query is `IEnumerable<IGrouping<string, DataClass.Student>>`. 

In instances like these, the type doesn't communicate much about the "shape" of the data that's returned by the query. The code following gives much more context: The `IGrouping` has a key (`string`) and a set of values (`DataClass.Student`). The query returns a sequence (`IEnumerable`) of those objects.

We'll continue to use `var` in these more complex LINQ queries. That's a standard that's typical in production code. However, in all cases, the context should provide sample code that explains the general "shape" of the results.

I'm closing this as not planned.
