### ISSUE TITLE
dotnet-publish: Which "publish-related properties" are supported?

### ISSUE THREAD

**Issue by NightProgramming** [dotnet/docs#34017]
[Here](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-publish#msbuild) the docs say:

```
You can also set publish-related properties by referring to a .pubxml file. For example:
dotnet publish -p:PublishProfile=FolderProfile
```

I would have assumed for instance that the `DeleteExistingFiles` property inside .pubxml is a _publish-related property_ but it is ignored by `dotnet publish`.

Also the `LastUsedBuildConfiguration` seems to be ignored because `dotnet publish` still builds and copies the Debug dlls, not the Release dlls although I have specified:

```
<LastUsedBuildConfiguration>Release</LastUsedBuildConfiguration>
```

Is `LastUsedBuildConfiguration` not a _publish-related property_? I would have guessed that it is.

I think it's not a mistake on my end because the `PublishDir` setting in .pubxml is honored when I do `dotnet publish` and the `DeleteExistingFiles` and `LastUsedBuildConfiguration` settings are honored when publishing via Visual Studio. Maybe `DeleteExistingFiles` and `LastUsedBuildConfiguration` are meant to only be used by Visual Studio but the docs here only mention `PublishUrl` to be meant to be used by Visual Studio.

I think it would be very helpful to write in the docs which _publish-related properties_ exactly are supported by `dotnet publish` in order to avoid confusion and maybe also it should be mentioned what the necessary replacements are for unsupported _publish-related properties_, e.g. `--configuration` argument has to be used instead of `LastUsedBuildConfiguration` setting.

Using .NET 7 SDK and tested with a completely new ASP.NET Core Web Application project. I didn't test any other _publish-related properties_.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 211afdc7-c796-202d-239d-823f2a499dff
* Version Independent ID: 9439897e-dcb3-bc2e-5cae-35c1ca2e0681
* Content: [dotnet publish command - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-publish)
* Content Source: [docs/core/tools/dotnet-publish.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-publish.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 66017](https://dev.azure.com/msft-skilling/Content/_workitems/edit/66017)

**Comment by tdykstra** [comment]
@baronfel
Should `dotnet publish` honor all of the `.pubxml` properties that Visual Studio publishing honors? Specifically if `dotnet publish` ignores `DeleteExistingFiles` and `LastUsedBuildConfiguration`, is this a bug or just a difference to be documented in the `dotnet publish` article?

**Comment by baronfel** [comment]
It's really hard to say which properties `dotnet publish` will ignore because it's entirely determined by the build targets that run as part of the publish operation. It is very likely that, say, `SelfContained` would be honored in both scenarios, but unfortunately PublishProfiles are also used by VS to store a lot of 'last run' data. Many publish mechanisms used by VS are not runnable from the CLI, so there's no worry about overlap at least.

There's some effort in https://github.com/dotnet/sdk/pull/29817 to bring the CLI more into alignment with VS's behaviors, but `LastUsedBuildConfiguration` for example may never be used.

There's probably a good documentation split between the 'packaging' aspect of publishing and the 'deployment automation' aspect of publishing - the CLI and VS both do the former, and properties relating to that we should support, but the CLI will probably never do the latter.

**Comment by tdykstra** [comment]
@NightProgramming Thanks for the suggestion. I'm adding a paragraph that notes the difference between the VS and the CLI handling of .pubxml properties.
