### ISSUE TITLE
Confusion between ASP.NET MVC and ASP.NET Core

### ISSUE THREAD

**Issue by alowdon** [dotnet/docs#34020]
The first paragraph says "In ASP.NET Core, there's no longer any distinction between MVC and Web APIs. There's only **ASP.NET MVC**, which includes support for view-based scenarios, API endpoints, and Razor Pages (and other variations like health checks and SignalR)." Should it instead say "There's only **ASP.NET Core**, which includes support...")?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b88301c1-3105-0a7e-f67a-5fb68cdfe801
* Version Independent ID: 5b50eda9-73e8-a381-f175-e61dddd0a50d
* Content: [Compare ASP.NET Web API 2 and ASP.NET Core](https://learn.microsoft.com/en-us/dotnet/architecture/porting-existing-aspnet-apps/webapi-differences)
* Content Source: [docs/architecture/porting-existing-aspnet-apps/webapi-differences.md](https://github.com/dotnet/docs/blob/main/docs/architecture/porting-existing-aspnet-apps/webapi-differences.md)
* Product: **dotnet-architecture**
* GitHub Login: @ardalis
* Microsoft Alias: **nanil**

---
[Associated WorkItem - 64057](https://dev.azure.com/msft-skilling/Content/_workitems/edit/64057)

**Comment by ardalis** [comment]
I would probably have said "There's only ASP.NET Core MVC" (when this was originally written) but then that's not really accurate today since we now have minimal APIs and a bunch of other stuff that's not MVC at all.

Today I think saying "There's ASP.NET Core, which supports view-based scenarios, API endpoints, Razor Pages, and more using MVC or other patterns." would probably work.

**Comment by erjain** [comment]
Thank you so much @ardalis  and @Rick-Anderson for the quick response and updates.
