### ISSUE TITLE
Improve Get started with .NET Core experience

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#3404]
Topic: https://docs.microsoft.com/en-us/dotnet/core/get-started

The page is a bit overwhelming for a new .NET Core developer. We should simplify it.

**Comment by BillWagner** [comment]
This is a high priority, but there is quite a bit of work to break this up and not lose the information that is part of the current topic.

**Comment by CamSoper** [comment]
What about splitting it up into Windows/Linux/macOS tabs?  Do we use tabs in the DotNet docs?  [Here's an example of what I'm talking about](https://docs.microsoft.com/en-us/dotnet/azure/dotnet-tools?view=azure-dotnet&tabs=windows).

Also, it seems to me the Hello World tutorial should be made a bit more prominent.

**Comment by ItsPugle** [comment]
I've done some work in conjunction with sites like [wikiHow](https://wikihow.com) to improve articles and to make them more readable/welcoming for new users. If someone covers the technical stuff, I can go through and do some work on the wording to encourage new users. I'm not sure if I'd be able to do *that much* due to time restrictions but still....

**Comment by ricardodsanchez** [comment]
How about just using this page as a landing page with links to individual pages for each operating system?

Eventually, the individual pages for each OS will probably be linked up and accessed directly most times. There is really no reason to have Windows, Linux, and MacOS all in one page.

**Comment by CamSoper** [comment]
@ricardodsanchez - That's why I mentioned the tabs - That way the URL doesn't change, and we still simplify the page for the user.  Also, DocFx (the documentation platform) is going to have the capability to automatically select the tab relevant for the user's OS sometime in the near future (if it's not there already).
