### ISSUE TITLE
Newbie question regarding await

### ISSUE THREAD

**Issue by qodes** [dotnet/docs#34275]
Hi,

I think I understand this code mostly, but it confuses me a lot why there's a `await finishedTask;` right before the `breakfastTasks.Remove(finishedTask);` line whithin the `while` statement. I commented it out, and all seems to run okay, but I don't understand whether that was done in error, or whether there's something fundamental that I still don't understand.

Thank you!
Miguel

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 79c2a674-a335-4802-5c52-4a2af998cc7f
* Version Independent ID: 3001f6f2-b04b-5513-54a6-fedfccc94e51
* Content: [Asynchronous programming in C#](https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/#await-tasks-efficiently)
* Content Source: [docs/csharp/asynchronous-programming/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/asynchronous-programming/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by gfoidl** [comment]
Can you link the article / sample you are refering to?

**Comment by gabeluci** [comment]
I assume you're referring to [this code block](https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/#code-try-11).

You're right that the `await finishedTask;` is not really necessary in that specific example, but there are two reasons that you may want to await that task in other cases. `Task.WhenAll()` returns the `Task` object that completed. If that `Task` returns a result that you want to use, then awaiting it will let you use that object.

In this case, the `FryEggsAsync()` method already returns an object of type `Egg`, but it's not used. Let's say that the `Egg` class had a `PopTheYolk()` method (because it's a fried egg - sunny side up). Then you could do this:

```
if (finishedTask == eggsTask)
{
    Egg friedEgg = await finishedTask;
    friedEgg.PopTheYolk();
    Console.WriteLine("eggs are ready");
}
```

Second, the `Task` could have ended in the `Canceled` or `Faulted` state. In both those cases, there would be an exception that will not be thrown until you await it.
