### ISSUE TITLE
Nullable properties loose it's nullability

### ISSUE THREAD

**Issue by jlchavez** [dotnet/docs#34381]
defining an interface like:

```
public interface IItem : IItem<Guid>
{

}

public interface IItem<TKey>
{
    TKey? Id { get; set; }
}

public abstract class Item<TKey> : IItem<TKey>
{
    protected Item()
    {

    }

    public Guid? Id { get; set; }
}

public class Item : Item<Guid>, IItem
{
    protected Item()
    {

    }
}
```

will not allow it to be used as, nullability property is lost:

```
var instance = new Item()
{
  Id = null
}
```

unless reimplemented in the class

```
public class Item : Item<Guid>, IItem
{
    protected Item()
    {

    }

    public new Guid? Id { get; set; }
}

```
At least this document should be updated as if the draft has changed or something is missing yet, since we are already in C# 11

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20fdee79-d110-1c13-f40a-5976c4905de6
* Version Independent ID: e494f6dd-cc4e-0524-2c22-49f1ee067303
* Content: [Nullable reference types - specification - C# 9.0 draft specifications](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/nullable-reference-types-specification)
* Content Source: [proposals/csharp-9.0/nullable-reference-types-specification.md](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-9.0/nullable-reference-types-specification.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by AlekseyTs** [comment]
This is a known limitation of generic code caused by the fact that nullable value types are different runtime types.

The `?` on a type parameter not known to be a value type makes nullable only reference type type arguments. Nullable value types are different types. For example, ```Guid?``` is actually a ```System.Nullable<Guid>```. Whereas ```string?```, is still a ```string``` with a little annotation for the compiler that values are allowed to be `null`. Generic type substitution cannot change types. 
In metadata the ```Id``` property looks like:
```
    .property instance !TKey Id()
    {
        .get instance !0 IItem`1::get_Id()
        .set instance void IItem`1::set_Id(!0)
    }
```

Substituting ```TKey``` with ```Guid``` makes it ```.property instance Guid Id()``` rather than ```.property instance Nullable<Guid> Id()```. And, obviously, it cannot be assigned a value of ```Nullable<Guid>```.

When a `struct` constraint is added, the property declaration is actually ```Nullable<TKey> Id { get; set; }``` and in IL looks like:
```
    .property instance valuetype [System.Runtime]System.Nullable`1<!TKey> Id()
    {
        .get instance valuetype [System.Runtime]System.Nullable`1<!0> IItem`1::get_Id()
        .set instance void IItem`1::set_Id(valuetype [System.Runtime]System.Nullable`1<!0>)
    }
```

Substituting ```TKey``` with ```string``` makes property ```.property instance string Id()```. And since there is a `?` annotation, it is legal to assign `null` to it.
