### ISSUE TITLE
Sample code error

### ISSUE THREAD

**Issue by squa7ed** [dotnet/docs#34738]
The "using System.Reflection;" statement is not correct in sample code of step 2 under "Add the code" section. It should be "using System;".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ffe064a-2c6e-284f-7706-528d1c861de3
* Version Independent ID: 7ff2fe61-8884-694d-db38-3e2cc292fe61
* Content: [Tutorial: Create a .NET tool - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create)
* Content Source: [docs/core/tools/global-tools-how-to-create.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/global-tools-how-to-create.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for contacting us. That part of the code is actually correct -- `System.Reflection` is needed for code added in the following step, which refers to `Assembly` and `AssemblyInformationalVersionAttribute`.  I'm adding a note to that effect, as I expect others would have the same question. The `using System;` statement is not needed because it's one of the [implicit usings](https://learn.microsoft.com/en-us/dotnet/core/tutorials/top-level-templates#implicit-using-directives). Also, while looking into this I noticed that the namespace was wrong due to a copy/paste error, and I'm fixing that.
