### ISSUE TITLE
Expand and move API obsoletion policy.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/docs#34755]
**Issue description**

The .NET API obsoletion policy is listed in https://learn.microsoft.com/en-us/dotnet/core/compatibility/library-change-rules a little ways down the page. As far as I have been able to see it is the only place it can be found. It is difficult to find and does not say anything about temporary configuration switches that are often provided to give customers time to migrate.

**Target framework**

Not applicable as this is about a policy not specific to any given TFM.

There are two parts to this issue...
1. Expand on the policy to include configuration switches
2. Move the policy somewhere with more visibility
    - Maybe under https://learn.microsoft.com/en-us/dotnet/core/compatibility/categories

**Comment by StephenBonikowsky** [comment]
FYI @gewarren and @jkotas and @PriyaPurkayastha

**Comment by gewarren** [comment]
@StephenBonikowsky This was mostly addressed by #35169, except we didn't add anything about temporary config switches. There was, however, much discussion before this text was approved. Do you still feel that info needs to be added?

**Comment by PriyaPurkayastha** [comment]
Thanks for raising this question @gewarren. You are right, temporary workarounds were discussed as part of our extensive discussions leading to the publishing of the policy addressed by https://github.com/dotnet/docs/pull/35169, and here is the consolidated summary:
- Every breaking change that is documented has a section for "Recommended Action" for mitigations.
- Mitigations can be in many forms and not necessarily always config switches.
- For high impact breaking changes where customers might need to rewrite a significant part of the logic, temporary workarounds might be provided to provide extra time to implement the mitigation.
- There is no fixed tenure for temporary workarounds. If there is security risk or high maintenance cost, we want to delete it sooner rather than later. On the other hand, if there is no security risk and we see many customers using the temporary workaround, we might keep it longer.
Due to the above, we cannot really have a specific policy about duration of a config switch which is just one type of a temporary workaround provided as a mitigation for a breaking change.

**Comment by StephenBonikowsky** [comment]
All good with me
