### ISSUE TITLE
Possible confusing typo?

### ISSUE THREAD

**Issue by ptoye** [dotnet/docs#34816]
The text says that "the compiler will emit nonvirtual call sites". I'm not sure what a "nonvirtual call site" is - so much gobbledygook -  but it seems to me that "omit" is more likely. to be correct. Also, an explanation (or a link to one) of "nonvirtual call site" would be nice.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c2289e13-c2dd-ab47-7306-f67e618b4861
* Version Independent ID: 4458b59e-495d-6a5b-b479-fe69c5acf91e
* Content: [CA1822: Mark members as static (code analysis) - .NET](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1822)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1822.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca1822.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by cremor** [comment]
I think "emit" is correct. The compiler will emit nonvirtual calls to static members. In contrast, for instance members it will emit virtual calls.

About the explanation of "nonvirtual call site": The doc says this immediately after mentioning it:

> Emitting nonvirtual call sites will prevent a check at run time for each call that makes sure that the current object pointer is non-null. This can achieve a measurable performance gain for performance-sensitive code.

In other words: For each virtual call (for an instance member) the runtime has to do a non-null check before calling the member (and raise a NullReferenceException in case the object reference is null). Also, the member call itself has to be virtual (since it might be overridden).
In contrast, for nonvirtual calls the runtime doesn't have to do a non-null check (because there is no object reference that could be null) and doesn't have to do a virtual call (static members can't be overridden).

You can find more information here: https://stackoverflow.com/questions/193939/call-and-callvirt

**Comment by IEvangelist** [comment]
"emit" is correct. Closing this issue.
