### ISSUE TITLE
How do we push nuget package and symbols package in oe go using pattern?

### ISSUE THREAD

**Issue by dazinator** [dotnet/docs#35193]
There is a new symbols package format called `.snupkg`
I can't see any examples of pushing a nuget package (.nupkg) and its symbols package (.snupkg) in one push command. Is this possible?

I think it would be useful to update this document with an example fo that,
I can see you can use glob patterns to push multiple packages but I am not sure what pattern syntax is supported - or how to specify multiple patterns.

Consider the follwing example:
```
dotnet nuget push "**/*.nupkg"

```

How do I make that also push the `.snupkg` file sitting alongside?
I want to use a pattern to do this based ont he file extension so that I don't have to hardcode a package name - meaning this set up will work in a wide range of situations / different projects without constant tweaking.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b363ab07-ea19-574f-e0db-25fd5702255d
* Version Independent ID: 6fa9479a-85db-5498-6b7e-2418fc7bac32
* Content: [dotnet nuget push command - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push)
* Content Source: [docs/core/tools/dotnet-nuget-push.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-nuget-push.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @karann-msft
* Microsoft Alias: **tdykstra**

---
[Associated WorkItem - 96534](https://dev.azure.com/msft-skilling/Content/_workitems/edit/96534)

**Comment by tdykstra** [comment]
@dotnet/nuget-team can you respond to this question?

**Comment by dazinator** [comment]
> I don't believe it is possible. The dotnet CLI doesn't have support for both pushing a package and symbols as they need to be executed individually.
> 
> You could likely use a script or automation of some sort to push both packages and symbols to give you a single-command like experience.

That's disappointing. For such a common scenario, I would expect this to fall within the remit of the existing tooling. Who wants to be burdened with creating custom tool for such a niche scenario when these formats are really fostered on to us via dotnet and nuget. Please consider adding something to product backlog!

**Comment by zivkan** [comment]
@dazinator @JonDouglas I believe that pushing symbols packages is actually by default. There's a `--no-symbols` argument that needs to be supplied to disable this behaviour. NuGet first pushes the nupkg, and if that is successful, it looks for a symbols package with a matching filename, and if it finds it, pushes that too.

However, with V3 feeds, the feed itself needs to tell NuGet that it supports symbols packages. For server implementors, here are the docs for the "symbol package push" resource: https://learn.microsoft.com/en-us/nuget/api/symbol-package-publish-resource

This is because the debugger doesn't know anything about NuGet, so the server has to implement the debugger's network protocol, and customers needs to configure their debugger to use the nuget feed's symbols URL. When you restore packages, NuGet does not download symbols.
