### ISSUE TITLE
Unclear complete scenario

### ISSUE THREAD

**Issue by ohadbitt** [dotnet/docs#35205]
Two things are unclear for me:
- The complete scenario publishing to specific runtime. If i follow the installation example for linux- what do i need to then run the exe on linux? Will it just work by double click?         This page https://learn.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli#self-contained-deployment suggests that the native libraries will need to be there somehow and install specific runtime. Does that mean that if i use the -r linux option it would just run from linux or do i need to install dotnet as well? 
- The page states that RuntimeIdentifier will set SelfContained to true by default but the CLI example sets it to false - does that mean that it sets it to true but you can force it to be false ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e1932751-7c2b-ce92-936e-e97f8581d5fa
* Version Independent ID: de677d1f-386a-e4c3-fdd0-6806b3ef2c0e
* Content: [Create a single file for application deployment - .NET](https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli)
* Content Source: [docs/core/deploying/single-file/overview.md](https://github.com/dotnet/docs/blob/main/docs/core/deploying/single-file/overview.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @LakshanF
* Microsoft Alias: **lakshanf**

---
[Associated WorkItem - 147248](https://dev.azure.com/msft-skilling/Content/_workitems/edit/147248)

**Comment by ohadbitt** [comment]
Also the example uses both
    <TargetFramework>net6.0</TargetFramework>
and
    <SelfContained>true</SelfContained>

How is it possible these work together ? isnt the second one means its not for a specific framework?

**Comment by adegeo** [comment]
Thank you for this issue. I'll look into this this month.

**Comment by adegeo** [comment]
Sorry for the delay in getting back to you about your questions.

> The complete scenario publishing to specific runtime. If i follow the installation example for linux- what do i need to then run the exe on linux? Will it just work by double click? 

There isn't an equivalent concept of `.exe` on linux. When you have a binary on linux, you have to have to set it with executable permissions, which would let the desktop double click it or let a terminal run it.

> This page suggests that the native libraries will need to be there somehow and install specific runtime. Does that mean that if i use the -r linux option it would just run from linux or do i need to install dotnet as well?

Self-contained apps include the dotnet runtime with the app, so it doesn't require that the runtime be preinstalled. However, dotnet itself has dependencies which need to be installed on the host machine. Depending on which linux distro you're using, the dependencies can be different. For example, here are the dependencies required for [Debian](https://learn.microsoft.com/en-us/dotnet/core/install/linux-debian#dependencies).

While publishing an app puts all the binaries of the app and dotnet together for you to distribute, it doesn't "package" it up into an installer or anything like that. You'll still have to handle that on your own if you want a nice end-to-end experience for your users. This is why package managers are so popular, you can publish your app as a package for Ubuntu, then list the libraries it's dependent upon, and they'll be installed automatically.

This is kind of the case for Windows too, though not so much because Windows includes a lot of the dependencies .NET needs by default. But, take Windows 7 for example. It's an old OS and was supported with .NET 6 (but not .NET 7). The dependencies of .NET 6 for that OS include the *Microsoft Visual C++ 2015-2019 Redistributable* which may or may not be installed already. But the latest redistributable comes with Windows 10/11 and on these OSs you don't have to worry about it because it's already there.

> The page states that RuntimeIdentifier will set SelfContained to true by default but the CLI example sets it to false - does that mean that it sets it to true but you can force it to be false ?

Correct. Any parameters on the command line will override the parameters set in the project file.

> Also the example uses both
> net6.0
> and
> true
>
> How is it possible these work together ? isnt the second one means its not for a specific framework?

(assuming you mean true for `SelfContained`)\
You're always targeting a specific framework (6.0 in this case), but what you may not be targeting is a platform (windows vs linux for example). When you publish self-contained, you need to designate a platform (it defaults to your current platform) so that the platform-specific binary can be built, the .net runtime for that platform is included, and any app-specific dependencies you have are also included (not .net native dependencies mind you). But if self-contained is false, you still generate a platform-specific executable, and it includes any app-specific dependencies you have are included, but the .net runtime isn't included. This means the user must have the runtime already installed before you run the app.

I think this answers your questions, so I'll close this issue. Please feel free to continue to comment though.
