### ISSUE TITLE
CS0108 mentions variables when it actually applies to members

### ISSUE THREAD

**Issue by distantcam** [dotnet/docs#35288]
The current description for error [CS0108](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0108) reads:

> A variable was declared with the same name as a variable in a base class. However, the [new](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/new-modifier) keyword was not used. This warning informs you that you should use new; the variable is declared as if new had been used in the declaration.

Everywhere it says variable it should say member. Also mentioning adding "new" to variables makes this extra confusing as new variable is object initialisation, not member overriding.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 52797d6c-c245-a61d-f4f6-8ef064577271
* Version Independent ID: ae6523de-e0c6-3f66-1790-c6a723f5fd94
* Content: [Compiler Warning (level 2) CS0108](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0108)
* Content Source: [docs/csharp/language-reference/compiler-messages/cs0108.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs0108.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Those are good observations @distantcam 

We should use the term "member" instead of "variable" here. (This same warning also applies to property declarations).

As for using the `new` keyword, that should be reworded, but the recommendation is correct. By adding the `new` modifier to the declaration you declare that the derived member hiding the base member was intentional. The example in the article shows this syntax, but it's commented out.
