### ISSUE TITLE
what is the difference between IDE0025 and IDE0027?

### ISSUE THREAD

**Issue by ali50m** [dotnet/docs#35306]
I`m not clear with the difference between editorconfig settings for [csharp_style_expression_bodied_accessors] and [csharp_style_expression_bodied_properties]

I don`t quite understand the difference between these two samples.

https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0025#csharp_style_expression_bodied_properties

https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0027#csharp_style_expression_bodied_accessors

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42631282-b935-c2d5-a45a-52b889717022
* Version Independent ID: c043d9b5-3822-8589-ed92-066f8c2809b1
* Content: [IDE0025: Use expression body for properties - .NET](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0025)
* Content Source: [docs/fundamentals/code-analysis/style-rules/ide0025.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/style-rules/ide0025.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

---
[Associated WorkItem - 156748](https://dev.azure.com/msft-skilling/Content/_workitems/edit/156748)

**Comment by gewarren** [comment]
@ali50m I agree these two are confusing and the docs could use some beefing up to explain the differences.

IDE0025 concerns the property as a whole, whereas IDE0027 specifically concerns the accessor parts of the property.

For a read-only property that simply returns a value without doing any computation, if IDE0025 is set to `csharp_style_expression_bodied_properties = false` but IDE0027 is set to `csharp_style_expression_bodied_accessors = true`, you end up with a property that looks like this:

```csharp
public int TemperatureF
{
    get => _temp;
}
```

But if you set IDE0025 to `csharp_style_expression_bodied_properties = true`, the property is simplified even further (even if you set IDE0027 to `csharp_style_expression_bodied_accessors = false`):

```csharp
public int TemperatureF => _temp;
```

For a read-write property, the difference becomes a little more apparent, because the property can't be written in an expression-bodied manner (because it consists of more than one line). So even if IDE0025 is set to `csharp_style_expression_bodied_properties = true`, you still end up with curly braces, i.e. a block body.

In the following examples, the first true/false refers to expression-bodied properties, and the second to expression-bodied accessors.

```csharp
        // false, true
        public int TemperatureB
        {
            get => _temp;
        }

        // true, true (or true, false)
        public int TemperatureC => _temp;

        // true, true (or false, true)
        public int TemperatureD
        {
            get => _temp;
            set => _temp = value;
        }

        // true, false
        public int TemperatureE
        {
            get
            {
                return _temp;
            }
            set
            {
                _temp = value;
            }
        }
```

**Comment by gewarren** [comment]
I'm going to reopen so I can add this info to the articles.
