### ISSUE TITLE
Misleading documentation about disposing IAsyncDisposable resources within synchronous context.

### ISSUE THREAD

**Issue by Ozzian** [dotnet/docs#35660]
The documentation doesn't help when you want to dispose IAsyncDisposable resources in your synchronous Dispose method. Actually, it has a misleading line in the example:

```
(_asyncDisposableResource as IDisposable)?.Dispose();
```

Take ServiceBusClient for example. It doesn't implement IDisposable, but only IAsyncDisposable , so the cast evaluates to null and the DisposeAsync() is never called.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61a961dc-3ebf-2a96-a6eb-2e0b62ab909f
* Version Independent ID: d72276e1-9059-815f-dc14-a03a7544ab87
* Content: [Implement a DisposeAsync method](https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync#implement-both-dispose-and-async-dispose-patterns)
* Content Source: [docs/standard/garbage-collection/implementing-disposeasync.md](https://github.com/dotnet/docs/blob/main/docs/standard/garbage-collection/implementing-disposeasync.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
If there were just a call to `Dispose`, then you have bigger issues... I can see your argument though. This is how to implement both patterns. I'm making a small update to the source and part of the article to make it clearer. Thanks!

**Comment by IEvangelist** [comment]
Hi again @Ozzian - the recommended way to dispose of an `IAsyncDisposable` is asynchronously. 

There are no formal recommendations to dispose of them any other way, and to my knowledge that is intentional. However, if they do implement the `IDisposable` interface, then you'd call `Dispose`. Personally, if I were to run into this situation on a side-project of mine, I'd strive to first dispose asynchronously, and if that wasn't possible - I may consider using:

```csharp
_asyncDisposableResource.DisposeAsync().GetAwaiter().GetResult();
```

> **Note**
> Again, this is not a formal recommendation.
