### ISSUE TITLE
Changing collection while iterating it should not be undefined behavior

### ISSUE THREAD

**Issue by svick** [dotnet/docs#3575]
The documentation for [`List<T>.GetEnumerator`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.getenumerator) and [`LinkedList<T>.GetEnumerator`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.linkedlist-1.getenumerator) say:

> An enumerator remains valid as long as the collection remains unchanged. If changes are made to the collection, such as adding, modifying, or deleting elements, the enumerator is irrecoverably invalidated and its behavior is undefined.

I think undefined behavior should be avoided if possible. In this case, I believe both collections ensure that if the collection is modified, the next call to `MoveNext()` will throw `InvalidOperationException`. Would it make sense to document this specific behavior, so that it's not undefined?

**Comment by BillWagner** [comment]
@svick I like this idea.  I'd like feedback from @safern and @ianhays on this idea as well.

**Comment by safern** [comment]
I also like this idea as well. Saying `it's behavior is undefined` makes it not very clear on what will happen if the collection is modified and actually there is a defined behavior as @svick mentions which is throwing an `InvalidOperationException`

**Comment by ianhays** [comment]
Sounds good to me.

**Comment by pkulikov** [comment]
@svick @mairaw  That looks that the whole **Remarks** section is the same for various GetEnumerator() method descriptions:
https://github.com/dotnet/docs/search?p=2&q=+or+deleting+elements%2C+the+enumerator+is+irrecoverably+invalidated+and+its+behavior+is+undefined.&type=&utf8=%E2%9C%93

Can it be moved to an include file with updating the piece of undefined behavior?

**Comment by mairaw** [comment]
Yes, that's a good solution @pkulikov.

**Comment by pkulikov** [comment]
@mairaw Can then I grab it for the fix?

**Comment by mairaw** [comment]
@pkulikov for sure! Thanks for wanting to contribute. Let us know if you need help with anything.

**Comment by pkulikov** [comment]
@mairaw cool! As I see all include files are in the **includes** folder. Then what is the file naming convention to follow?

**Comment by mairaw** [comment]
Yes, that's where they live. The only convention we have is lowercase file names and use dashes as separators. You could name it something like getenumerator-remarks or something similar that explains the intention.

**Comment by pkulikov** [comment]
@mairaw That's clear, thank you.

**Comment by pkulikov** [comment]
@mairaw I've looked at various **Remarks** sections thoroughly and they don't look the same anymore: they contain links that depend on enumerator type. So, solution with one include file would not work.

Thus I will update individual xml files for `List<T>` and `LinkedList<T>` to fix the original issue at least. I'll use phrasing from [SortedSet documentation](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.sortedset-1.enumerator.current?view=netframework-4.7.1).

If that's fine with you and as soon as PR for those two types is reviewed, I can go through other collection types and update them if necessary with one PR per type.

What do you think?

**Comment by pkulikov** [comment]
@safern @ianhays @BillWagner during the work on fixing this issue, the interface docs (ones of both `IEnumerable` and `IEnumerator`, both non-generic and generic) have been revised.

One of those revisions is PR dotnet/dotnet-api-docs#247 that rephrases the part related to this issue in the following way:
> If changes are made to the collection, such as adding, modifying, or deleting elements, the behavior of the enumerator is undefined.

Note that the remark about *invalidated* enumerator is gone. That is because there are collections' implementations that accept changing the collection during enumeration (ones from the `System.Collections.Concurrent` namespace; thanks to @stephentoub for the point).

As the interface docs claim the behavior undefined, the docs of specific implementations can
- add no additional information and be the same as the interface docs, OR
- describe particular behavior of the specific implementation.

What approach do we select for the docs of the `System.Collections.Generic` collections? 
- Merely state that behavior is undefined (repeating the interface docs) OR
- Stay with the decision made earlier in this thread: state that an enumerator is invalidated and calls to `MoveNext` and `Reset` throw an `InvalidOperationException`?

I give my vote to the variant with the defined behavior as that behavior is consistent throughout all the collections from the `System.Collections.Generic` namespace and doesn't look to be the candidate for the change because of the performance, xplat, etc reasons. Moreover, that invalidated behavior has been documented for quite a long time already, and changing that behavior might be considered as a breaking change.

So, @safern @ianhays @BillWagner, what would be the best choice for the docs?

**Comment by svick** [comment]
@pkulikov Thanks for your work on this.

The thing I don't like about using the term "undefined behavior" here is that it means the implementation is allowed to do *anything*.

Are the two options you mentioned, namely throwing `InvalidOperationException` and allowing enumeration to continue, the only reasonable ones? If that's the case, could the documentation for the interfaces be changed to allow only those two options?

If there are other reasonable options, could the documentation be changed to allow only those?

**Comment by pkulikov** [comment]
@svick if we want to list the options in the interfaces docs, we should talk not about reasonable options, but about the current set of choices already *implemented* in .NET. I'm aware of three different approaches:
- Invalidate enumerator and throw, as in `System.Collections.Generic`
- Take the snapshot of the collection at the moment `GetEnumerator` is called and enumerate through that version of the collection, as in `System.Collections.Concurrent`
- Make an enumerator blind to the changes, as an array enumerator:
```csharp
var q = new int[] { 23, 3 };
var en = q.GetEnumerator();
Console.WriteLine(en.MoveNext()); // returns True
Console.WriteLine(en.Current); // returns 23
q[0] = 13;
Console.WriteLine(en.Current); // returns 13
Console.WriteLine(en.MoveNext()); // returns True
```

It's possible that there are other ways to treat the collection changes implemented in .NET that I'm not aware of.

Second, as soon as the interface docs list possible behaviors, a reader has a reasonable question: "Which one of the listed behaviors is implemented by the collection X?". One goes to the docs of the collection X to find an answer on that question. So, if the interfaces docs contain the list of possible behaviors, the docs of *all* implementations should be revised.

If we want to do that, I suggest to open a new issue to track the work on it. Even if we want to discuss that topic further, I suggest to do that in a new issue.

The current phrasing (with "undefined behavior"), you're right, means that implementation might do *anything*, so a reader is invited to check the docs of the implementation (in case he knows what implementation is in use). Those docs *might* contain description of the behavior, but also might say that behavior is undefined as well.

By the way, my first thought was also to list reasonable behaviors in the interface docs. However, as I've described above, coming with the complete such list might take a lot of time. So, I've come up with a quick fix of the "undefined behavior".

**Comment by BillWagner** [comment]
@svick 

> The thing I don't like about using the term "undefined behavior" here is that it means the implementation is allowed to do anything.

I agree, and that's why we use it very rarely. See the conversation on dotnet/dotnet-api-docs#231 for more background.
