### ISSUE TITLE
iostream error CS1024

### ISSUE THREAD

**Issue by CNCTECHROOM** [dotnet/docs#36111]
[Enter feedback here]
First c++ hello world cannot find or exucute iostream New to c++ visual studio win 10

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff65be67-852d-a862-5f09-be4c720e005b
* Version Independent ID: f38287f8-ed77-2147-7935-a981be58dd15
* Content: [Compiler Error CS1024](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1024?f1url=%3FappId%3Droslyn%26k%3Dk(CS1024))
* Content Source: [docs/csharp/misc/cs1024.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs1024.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Hi @CNCTECHROOM 

The page referenced is a C# compiler error code. Your text indicates you're making a C++ app. 

I think you accidentally created a C# application instead of a C++ application. 

I'll close this as it's not a docs issue. If you have other questions, I recommend posting a sample in our [Q & A](https://learn.microsoft.com/answers/) section.
