### ISSUE TITLE
Clarify target audience of .NET Framework version detection topic

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#3631]
# Clarify target audience of .NET Framework version detection topic

## Issues with Existing Topics

[How to: Determine which .NET Framework versions are installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed) recommends the use of the registry (and requires administrative privileges) to detect the installed version of the .NET Framework. The topic implicitly identifies developers as its target audience, but doesn't do it explicitly. Developers should be explicitly identified as the topic's target audience.

//cc @kendrahavens @mairaw

**Comment by doctordns** [comment]
I think it's very important for IT Pros to know what versions of the Framework are loaded. This is because some cmdlets and some .NET classes) are only available with certain versions of PowerShell and the Framework.

I would therefore argue this topic should not only be 'targeted' at Devs, but also at IT Pros.
