### ISSUE TITLE
What purpose does .NET serve on Linux?

### ISSUE THREAD

**Issue by jimlloyd** [dotnet/docs#36627]
I want to know what purpose the .NET runtime serves on Linux. What, if any, vscode features require it? I have installed it before but it seems that periodically I get an error "Failed to run .NET runtime. ..." If I cancel that alert I don't notice any problems.  Is there some subtle user experience that will be improved if .NET is runnable?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e92ae0e3-2f90-5eeb-ed2c-bdfb85c5eaca
* Version Independent ID: 1850602d-6b92-1449-c8bd-116e36fc0f26
* Content: [Install .NET on Linux distributions - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/linux?tabs=netcore2x)
* Content Source: [docs/core/install/linux.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux.md)
* Product: **.net**
* Technology: **dotnet-installation**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hi @jimlloyd The biggest advantages that the runtime provides to the OS is really from the software that utilizes it. When an app ships without the runtime and relies on the local runtime you've installed, it gets these benefits:

1. The app package is smaller as it doesn't include the runtime.
2. The app benefits from patches applied to the runtime. If the app shipped the runtime with itself, any security and bug fix updates applied to the locally installed runtime wouldn't apply to the app.
3. Optionally the app author can make the app fully cross-platform (if it doesn't use any platform-specific code). This requires the app runner to start the app via dotnet directly with `dotnet path-to-app-binary`. Otherwise they get a platform specific executable that does that `dotnet path-to-app-binary` for you automatically.

If something on your system is complaining about a missing runtime you'll have to figure out what that app is, what runtime it's expecting, and if it's looking for the runtime in a different place.

I hope this answers your question. I'll close this issue. Please feel free to comment again. Cheers!
