### ISSUE TITLE
Please provide actual code examples

### ISSUE THREAD

**Issue by ahazelwood** [dotnet/docs#36712]
Please provide an example of how a class would be structured with its constructors (i.e. pulling in ILoggerFactory).  Also a case of using NullLoggers.

Especially with legacy libraries, where we internally use NLog, it was always easy to call a method like: `var logger = LogManager.GetCurrentClassLogger();` and then just use the logger as a static variable in the class.

This documentation would be helpful as it took me a long time to figure out how to get DI to work in cases where it's not apparent (for example, Static/Instance methods).

For example, I have an implementation class that I can then populate from the constructor of any of my application that do not currently rely on things like `IHostedService`.

```cs
public static class ApplicationLogger
{
    public static ILoggerFactory LoggerFactory { get; set; } = new LoggerFactory();
    public static ILogger<T> CreateLogger<T>() => LoggerFactory.CreateLogger<T>();
    public static ILogger<T> CreateLogger<T>(ILoggerFactory loggerFactory) => loggerFactory.CreateLogger<T>();
    public static ILogger CreateLogger(string categoryName) => LoggerFactory.CreateLogger(categoryName);
}
```

This is initialized with a call like the following (once I actually have a `ILoggerFactory` instance):

```cs            
ApplicationLogger.LoggerFactory = loggerFactory;
```

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9cb767be-972d-9086-a759-d051fb11d555
* Version Independent ID: 3c6a20c4-b69f-8a21-3603-16d18a257ff4
* Content: [Logging guidance for .NET library authors - .NET](https://learn.microsoft.com/en-us/dotnet/core/extensions/logging-library-authors)
* Content Source: [docs/core/extensions/logging-library-authors.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/logging-library-authors.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment]
Hey @ahazelwood - (sorry for the delay, been heads down writing .NET Aspire docs) thanks for posting this issue. The issue is that you're `ApplicationLogger` is `static`. Are you familiar with the term ["static cling"](https://deviq.com/antipatterns/static-cling)?

With dependency injection, instead of relying on static global mutable state, you explicit define your dependencies as requirements of the containing class. The DI container materializes the dependencies, and you're good to go. If you're using the `ILogger<TCategoryName>` and `ILoggerFactory`, these are provided by the DI container when you've registered them (as common with hosted-apps).

Anywhere you're doing logging, you could simply add a constructor parameter for the corresponding `ILogger` type:

```cs
public class SomeExampleService
{
    private readonly ILogger<SomeExampleService> _logger;

    public SomeExampleService(ILogger<SomeExampleService> logger)
    {
        _logger = logger;
    }
}
```

Does that make sense? Then in your tests, for example, if you don't want to register the full services, you could manually instantiate this service and pass it a `NullLogger<SomeExampleService>.Instance`.

```cs
public class ExampleTests
{
    [Fact]
    public void SomeExampleServiceTest()
    {
        // Arrange
        var sut = new SomeExampleService(NullLogger<SomeExampleService>.Instance);

        // Act
        // ...

        // Assert
        // ...
    }
}
```

Does that make sense?
