### ISSUE TITLE
NetworkInterface.NetworkInterfaceType missing enum values in remarks

### ISSUE THREAD

**Issue by logmanPL** [dotnet/docs#3679]
Property NetworkInterfaceType of NetworkInterface in Remarks section is missing return enum values 

[On this page](https://docs.microsoft.com/en-us/dotnet/api/system.net.networkinformation.networkinterface.networkinterfacetype?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Net.NetworkInformation.NetworkInterface.NetworkInterfaceType);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.6.2);k(DevLang-csharp)%26rd%3Dtrue&view=netframework-4.7.1)

I can confirmed that it may also return NetworkInterfaceType.Wireless80211 as correct value.

**Comment by rpetrusha** [comment]
@davidsh, can you confirm the additional enum return value?

**Comment by davidsh** [comment]
The enum type `NetworkInterfaceType` is defined here:

https://github.com/Microsoft/referencesource/blob/master/System/net/System/Net/NetworkInformation/interfacetype.cs#L2-L36

As an enum type, it could return any of those values.

**Comment by mairaw** [comment]
Perhaps we should just remove that paragraph. It doesn't make sense to list all the enum values in the remarks, in my opinion.

I also noticed there's a typo on the page:
**An** NetworkInterfaceType value that specifies the network interface type.

**Comment by logmanPL** [comment]
From users answers on stackoverflow I can say that not all values are possible or it's not clear when they can happened. For ex. GigabitEthernet is not present event if interface actually is gigabit ethernet (instead you get Ethernet value). From my point of view, as there are many possible values it's really important to known what to expect from NetworkInterfaceType property.

**Comment by mairaw** [comment]
Yes, if the property doesn't always return all enum values and there are special conditions, then I agree with you @logmanPL, we should list which enum values you can get. My understanding after reading @davidsh's comment was that any value could be returned.

**Comment by rpetrusha** [comment]
@logmanPL, the specific value returned depends on the runtime conditions of the network, but it is possible for the property to return any value in the enumeration. 

So rather than list individual enumeration members that the property might return, the documentation needs to be revised to note that the property can return any value from the enumeration, but that the specific value returned depends on runtime conditions of the network typology. 

We'll schedule some time to revise the documentation in the course of the next three weeks.
