### ISSUE TITLE
Make it easier to find pages using Google search

### ISSUE THREAD

**Issue by HermanEldering** [dotnet/docs#3710]
Usually when I'm looking for information I'll do a search on Google. For instance when searching a method in the framework API, like "Convert.ChangeType". I would like to have the API page at docs.microsoft.com to be near the top of the search results. 

Currently it will always point to msdn.microsoft.com and it is impossible for me to find the page I want at docs.microsoft.com through Google, even when using "site:". It either just doesn't find it or it will be a page not in English. Bing also doesn't show docs.microsoft.com on the first search page.

The API pages on msdn.microsoft.com have a link to docs.microsoft.com but it is not deep linked so then I have to type my search query again, which is not a good experience. Maybe the quickest solution would be to just automatically redirect from msdn.microsoft.com API pages to the equivalent docs.microsoft.com page.

I have submitted some API pages to Google for indexing today, perhaps that will help.

**Comment by mairaw** [comment]
Hi @HermanEldering, thanks for your feedback. This behavior is currently by design. Our API pages on docs are set to not be indexed. The reason why we had to do this is because we couldn’t have a new site that is just a copy of another site (in this case, MSDN). Google would probably stop indexing docs altogether. We’re working really hard to fix the remaining issues that are preventing us from redirecting the latest version of the .NET Class Library from MSDN to Docs. We hope that happens soon. For now, the best way is to use the search on API browser for that (https://docs.microsoft.com/en-us/dotnet/api/). Apologies for the inconvenience.

**Comment by HermanEldering** [comment]
Thanks for the reply. It is good to know that it is by design for now and being worked on. I like the new site so I hope to see the transition soon.
