### ISSUE TITLE
There are no examples for VB or C#, both of which are supposed to be able to be hosted.

### ISSUE THREAD

**Issue by NeilMJohnson** [dotnet/docs#37121]
[Enter feedback here]
This has not been updated in a while, but I can find no examples for Visual Basic, only Python and Ruby.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8cf468aa-8191-3e82-8e05-c69907e086c4
* Version Independent ID: 5b9ba335-2b0e-cafd-3409-bf1f54d16fa2
* Content: [Dynamic Language Runtime Overview - .NET Framework](https://learn.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/dynamic-language-runtime-overview?source=docs)
* Content Source: [docs/framework/reflection-and-codedom/dynamic-language-runtime-overview.md](https://github.com/dotnet/docs/blob/main/docs/framework/reflection-and-codedom/dynamic-language-runtime-overview.md)
* Product: **dotnet-framework**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
It's been a long time since I've looked into the DLR, so I'm unsure if my memory is correct. But, the DLR is about getting other dynamic languages, such as Ruby and Python, running on .NET. C# and Visual Basic already run on .NET, and they're typed languages, not dynamic languages.

The DLR itself is an area we're not investing docs into. The latest DLR stuff is hosted on GitHub with the IronLanguages group at https://github.com/IronLanguages

I'm going to close this issue because I don't think there's anything in the docs to do here, but feel free to comment.
