### ISSUE TITLE
Install locations from feed not always as stated

### ISSUE THREAD

**Issue by SRNissen** [dotnet/docs#37204]
In the section

### .NET SDK and CLI environment variables
`DOTNET_ROOT`, `DOTNET_ROOT(x86)`

you write:

> Specifies the location of the .NET runtimes, if they are not installed in the default location. The default location on Windows is C:\Program Files\dotnet. The default location on macOS is /usr/local/share/dotnet. The default location on Linux varies depending on distro and installment method. The default location on Ubuntu 22.04 is /usr/share/dotnet (when installed from packages.microsoft.com) or /usr/lib/dotnet (when installed from Jammy feed).

This is not necessarily the case - on running `sudo apt-get install dotnet-sdk-7.0` the runtimes ended up in `/usr/lib/dotnet` but the sdks ended up in `/usr/share/dotnet` - this has been *very* confusing to debug (dotnet finds the runtime but not the sdk) and I have no good idea how it happened (possibly because I added a microsoft feed to get powershell? Which also supplies the sdk, but not the runtime, so I get a jammy runtime but a microsoft sdk?)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c1fab316-eb04-50f5-03c8-bf3004981d3e
* Version Independent ID: 0c8e3542-470a-fa11-0d27-061384c4c3ba
* Content: [.NET environment variables - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables#net-sdk-and-cli-environment-variables)
* Content Source: [docs/core/tools/dotnet-environment-variables.md](https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-environment-variables.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by SRNissen** [comment]
I have run a few tests backward and forwards.

I can reliably recreate the issue when I add MS repos to get powershell.

My current workaround has been to get powershell from Snap and not add the MS repos to APT.

Still, that seems silly - what am I supposed to advice my colleagues here? "Avoid adding MS repos if you have to do dotnet development" seems like very weird advice.

**Comment by adegeo** [comment]
Hi @SRNissen This sounds like a package mixup problem. You'll need to configure your package manager to AVOID getting the .NET packages from the MS Feed while allowing all other packages (such as powershell) to be sourced from the MS Feed.

The [Install .NET on Ubuntu Overview](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu) page includes a lot of information about resolving these problems. Read the intro and the warning message there, then check the **Decide how to install .NET** section. I added a decision tree there to help these types of scenarios. Hopefully this gets you working. Please provide feedback on that page if there's a problem or improvement to that page.

I'm going to close this issue here because I think that link should provide all the information you need. If you feel that you want to continue the conversion here, please feel free to reopen the issue, otherwise, use the feedback link on the overview page and I'll get alerted to the new issue. Thanks!

**Comment by SRNissen** [comment]
Hi

Thank you, it is a thorough and useful guide (better than the one for powershell) but I don't need it today - I found a solution on the same day I opened the issue.

I returned to the issue yesterday because a junior ran into the exact same problem and as I was explaining the solution, I wanted to update this issue to make it known to the dotnet team that Microsoft guidance on how to install Powershell will break casually break dotnet installs.

As a purely administrative matter you can leave the issue closed or you can re-open it - inside our org it is solved, our internal handbook now has guidance on how to avoid this, or how to get back out if you accidentally got into this situation.

But as a fact about documentation, the issue has not been solved until Microsoft guides don't give mutually exclusive directions.

For reference, the powershell guide that doesn't tell you it will break dotnet installs is this one:

https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.3

**Comment by adegeo** [comment]
Thanks for the link @SRNissen I'll file a bug on that documentation telling them to add matching (or point to the ubuntu article) documentation.
