### ISSUE TITLE
Anonymous method code example isn't correct.

### ISSUE THREAD

**Issue by navedrasul** [dotnet/docs#37665]
### Type of issue

Typo

### Description

Great article! However, the _anonymous method_ code example wrongly uses _lambda expression_ instead of an _anonymous method_.
Thanks,

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/events/how-to-subscribe-to-and-unsubscribe-from-events

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/events/how-to-subscribe-to-and-unsubscribe-from-events.md

### Document Version Independent Id

0488a6a9-a606-026b-ad8b-33bb3150b4be

### Article author

BillWagner

**Comment by BillWagner** [comment]
Hi @navedrasul 

My first thought is to close this. From the [current standard](https://learn.microsoft.com/dotnet/csharp/language-reference/language-specification/expressions#1219-anonymous-function-expressions):

> *Note*: For historical reasons, there are two syntactic flavors of anonymous functions, namely *lambda_expressions* and *anonymous_method_expressions*. For almost all purposes, *lambda_expressions* are more concise and expressive than *anonymous_method_expressions*, which remain in the language for backwards compatibility. *end note*

In this instance, there isn't a noticable difference. The example is a lambda expression, because it doesn't include the parameter types. 

If you have different thoughts, let me know.
