### ISSUE TITLE
C# 中的记录类型简介

### ISSUE THREAD

**Issue by xinchenglei** [dotnet/docs#37789]
### Type of issue

Missing information

### Description

错误的用词 （可能由于错误的连词输入）

{
不可变性
不可变类型会阻止你在对象实例化后更改该对象的任何属性或字段值。 如果你需要一个类型是线程安全的，或者需要哈希代码在哈希表 『中国』 能保持不变，那么不可变性很有用。 记录为创建和使用不可变类型提供了简洁的语法。
}
[中国应改为 “中”]

### Page URL

https://learn.microsoft.com/zh-cn/dotnet/csharp/fundamentals/types/records

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/types/records.md

### Document Version Independent Id

8991024e-b64a-bc2a-9612-5649d89bda2b

### Article author

BillWagner

**Comment by IEvangelist** [comment]
Rough translation:

**Title**
> C# 中的记录类型简介

"Introduction to record types in C#"

**Description**

> 错误的用词 （可能由于错误的连词输入）
> {
> 不可变性
> 不可变类型会阻止你在对象实例化后更改该对象的任何属性或字段值。 如果你需要一个类型是线程安全的，或者需要哈希代码在哈希表 『中国』 能保持不变，那么不可变性很有用。 记录为创建和使用不可变类型提供了简洁的语法。
> }
> [中国应改为 “中”]

"Wrong word usage (possibly due to incorrect conjunction)

{
Immutability
Immutable types prevent you from changing any of the object's properties or field values after it has been instantiated. Immutability is useful if you need a type that is thread-safe, or if you need the hashed code to remain unchanged in the hash table. Records provide a concise syntax for creating and using immutable types.
}
[China should read "China"]
"

**Comment by BillWagner** [comment]
Thanks for noting this @xinchenglei 

I created an internal work item for our localization team to correct the translation.

Closing as it's tracked in their system.
