### ISSUE TITLE
[方法主体和局部变量]节的错别字

### ISSUE THREAD

**Issue by SimsalYang** [dotnet/docs#37893]
### Type of issue

Typo

### Description

在 [方法主体和局部变量] 节中，实例代码下方对解释文字中

> 如果上述 `i` 的声明未包含初始值，那么编译器会在后续使用 `i` 时报告错误，因为在后续使用时 `i` 不会在程序中得到明确赋值。

应为

> 如果上述 `j` 的声明未包含初始值，那么编译器会在后续使用 `j` 时报告错误，因为在后续使用时 `j` 不会在程序中得到明确赋值。

### Page URL

https://learn.microsoft.com/zh-cn/dotnet/csharp/tour-of-csharp/program-building-blocks

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/tour-of-csharp/program-building-blocks.md

### Document Version Independent Id

c723989f-2ff6-389d-dcb4-f55d97d14501

### Article author

BillWagner

**Comment by BillWagner** [comment]
Rough translation:

In the [Method Bodies and Local Variables] section, the example code is below the explanatory text

> If the above declaration of i does not contain an initial value, then the compiler will report an error when i is used subsequently, because i will not be explicitly assigned in the program on subsequent uses.

It should be

> If the above declaration of j does not contain an initial value, then the compiler will report an error on subsequent use of j, because j will not be explicitly assigned in the program on subsequent use.

**Comment by BillWagner** [comment]
The fix should be in the English source. The text (including the translation) is correct, but not as clear as it should be. In the example, `i` is initialized before the `while` loop, so it is definitely assigned. `j` is definitely assigned inside the `while` loop, before it's read. 

The text is saying that *if* `i` had not been set to an initial value:

```csharp
int i;
int j;
```

Then, there would be an error at the `while` statement because `i` wouldn't be definitely assigned.

Adding to our backlog, and adding the "help wanted" label.

**Comment by SimsalYang** [comment]
Thanks, I re-read the text and realized that it was a mistake of mine, that I had ignored the word "if".
