### ISSUE TITLE
Inferred type of an iteration variable always optional?

### ISSUE THREAD

**Issue by cveld** [dotnet/docs#38020]
### Type of issue

Missing information

### Description

It seems that the inferred type of an iteration variable is always optional. Why is that? The documentation does not explain that.

E.g. 
```c#
var list = new List<string>();
foreach (var item in list) { } // item has type _string?_ instead of the expected _string_
```

Interestingly the compiler does not complain when I explicitly specify the iteration type:

```c#
var list = new List<string();
foreach (string item in list) { } // item has the expected type _string_
```

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/iteration-statements

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/statements/iteration-statements.md

### Document Version Independent Id

8b6cb66c-8bef-fed0-1677-acee6bd3e052

### Article author

BillWagner

**Comment by BillWagner** [comment]
Hi @cveld 

First, to make sure I'm interpreting your issue correctly, I think that by saying "the type is optional", you mean the implied type is a *nullable reference type*.

If that's correct, it is mentioned [here](https://learn.microsoft.com/dotnet/csharp/language-reference/statements/declarations#implicitly-typed-local-variables) in the language reference.

We should add a link to that section from here (possibly in a similar note).

I'll add this to our backlog, and add the "help wanted" label if anyone wants to submit a PR before we make our next update.

**Comment by cveld** [comment]
Can you also explain why this is happening? And is there any way to enforce a non-nullable reference type? I guess I can switch over to the c# 9 way:

```c#
List<string> list = new();
```

or even:
```c#
List<string> list = []
```

**Comment by BillWagner** [comment]
@cveld 

Two parts to the answer: First, Both of those are valid. They create empty collections. Neither contains a null value.

Second, [this section](https://learn.microsoft.com/dotnet/csharp/nullable-references#null-state-analysis) explains why any reference variable declared with `var` is a nullable reference type: You can rely on the compiler's null state static analysis to ensure you don't dereference null. That's the important part for your code: you won't thrown any null reference exceptions, because the compiler will warn you if you dereference null, or assign a possibly null value to another variable that isn't known to be non-null.
