### ISSUE TITLE
Add more platforms to supported .NET Standard platforms

### ISSUE THREAD

**Issue by jzeferino** [dotnet/docs#3814]
# Add more platforms to supported .NET Standard platforms

I wan't to add this platforms to the .NET Standard supported platforms [here](https://github.com/dotnet/docs/blob/master/docs/standard/class-libraries.md#net-standard-class-libraries):

*   Xamarin.iOS 10.14
*   Xamarin.Android 7.5
*   Xamarin.Mac 3.8
*   Mono 5.4

## Suggest reviewers

@rpetrusha, @mairaw

Can I PR it?

**Comment by mairaw** [comment]
@terrajobst any thoughts on this?

I'd probably future-proof the list as well. So we could list:
Xamarin.iOS 10.0 and later versions
Xamarin.Android 7.0 and later versions
Xamarin.Mac 3.0 and later versions
Mono 4.6 and later versions

Note that I changed the versions to be ones supported since .NET Standard 1.0 and not the 2.0 only.

**Comment by jzeferino** [comment]
@mairaw do you want me to change my PR?

**Comment by mairaw** [comment]
I don't see any open PRs @jzeferino. An I missing something?

**Comment by jzeferino** [comment]
Sorry @mairaw I was wrong, I din't created the PR yet. I will create it.

**Comment by philippgille** [comment]
@jzeferino: I followed [your advice](https://github.com/dotnet/docs/pull/3813#pullrequestreview-79682233) and added more platforms to [my PR](https://github.com/dotnet/docs/pull/3813). I added a "Close #3814" in the commit message, because the PR solves this issue.
