### ISSUE TITLE
How to use resgen generate file with version

### ISSUE THREAD

**Issue by chucklu** [dotnet/docs#3878]
https://github.com/dotnet/docs/blob/master/docs/framework/tools/resgen-exe-resource-file-generator.md

I have checked the document for resgen, however I can not find the option to generate file(*.resources.dll) with specified version.

**Comment by rpetrusha** [comment]
@chucklu, resgen creates a .resources file, not a *.resources.dll file. That .resources file can then be included in a versioned assembly by using either a language compiler (to embed it in an application assembly) or [Al.exe, the Assembly Linker)](https://docs.microsoft.com/en-us/dotnet/framework/tools/al-exe-assembly-linker) (to embed it in a satellite assembly); it's at this stage that you specify a version. For information about the overall process of including resources in an app, see [Creating Resource Files](https://docs.microsoft.com/en-us/dotnet/framework/resources/creating-resource-files-for-desktop-apps).

That said, the topic on resgen.exe could be clearer in placing resgen within the overall context of developing an app that uses resources. And the Creating Resources topic needs to be modernized for .NET Core. I'm leaving this issue open and assigning it to myself so that this work can be scheduled.

**Comment by chucklu** [comment]
@rparcalab  Thanks, I mistaken the usage.  I have tried with al.exe to generate the *.resources.dll file.
Maybe I can close this issue?
