### ISSUE TITLE
error CS8802: Only one compilation unit can have top-level statements.

### ISSUE THREAD

**Issue by soujanya30** [dotnet/docs#38811]
### Type of issue

Missing information

### Description

[Enter feedback here]
"error CS8802: Only one compilation unit can have top-level statements." is displaying in my device please fix it

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error?f1url=%3FappId%3Droslyn%26k%3Dk(CS8802)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error.md

### Document Version Independent Id

58a19505-ac46-c5c8-12cc-fe87b6aa18a7

### Article author

@BillWagner

### Metadata

* ID: bbb051ee-f020-66ba-c601-4a08ad32ef61 
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**

**Comment by BillWagner** [comment]
Hi @soujanya30 

This is one of the issues we need to add help for. Thanks for pointing that out.

One file in a C# program can contain *top level statements*. Those top level statements represent the entry point to the program. (This would often be the `Main` method in earlier C# versions or other languages). 

Because it's the entry point to the program, only one file may have top level statements. All other statements must be in members defined in classes or structs.

**Comment by soujanya30** [comment]
so what should i do to start c# in all file in place of only one file , please provide a solution for it

**Comment by BillWagner** [comment]
Hi @soujanya30 

We've got a few articles that will help. I recommend starting with this article on [top-level statements](https://learn.microsoft.com/dotnet/csharp/fundamentals/program-structure/top-level-statements). Then, this tutorial has an [introduction to classes](https://learn.microsoft.com/dotnet/csharp/fundamentals/tutorials/classes),

Finally, when you get stuck, post a short sample to our [Q & A](https://learn.microsoft.com/en-us/answers/tags/309/csharp) site. There are a number of folks that can answer these specific questions.

**Comment by zashab** [comment]
? be open

S.Shabani
