### ISSUE TITLE
Claims Mapping Breaking Change is missing

### ISSUE THREAD

**Issue by luccawilli** [dotnet/docs#38827]
### Type of issue

Missing information

### Description

The article is missing the information, that the claims mapping changes in .NET 8
JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();

... to ...

JsonWebTokenHandler.DefaultInboundClaimTypeMap.Clear();

https://github.com/dotnet/AspNetCore.Docs/pull/30939

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/compatibility/8.0

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/compatibility/8.0.md

### Document Version Independent Id

1dc7a986-52e6-3a88-0163-4a869afc75d3

### Article author

@gewarren

### Metadata

* ID: 250b5b35-569a-c5fa-2bf8-9d951bc1bdb7 
* Product: **dotnet-fundamentals**

**Comment by gewarren** [comment]
@guardrex Who is the developer that made the breaking change? Can you ask them to log an announcement for the breaking change at https://github.com/aspnet/Announcements/issues? That gives me the info I need to document it.

**Comment by guardrex** [comment]
AFAIK, it was announced in a general way per ...

* https://github.com/aspnet/Announcements/issues/508
* https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/8.0/securitytoken-events

It seems like the problem is that the specific API `DefaultInboundClaimTypeMap` isn't explicitly mentioned, along with a lot of other API in that area. A list of explicit API changes could be added to the announcement ... and perhaps the article, too. It might fend off more issues coming in.

I think Stephen Halter is aware of the details (e.g., who did the work) based on PU issue discussions about the change, so I'd recommend pinging him for more info if needed.
