### ISSUE TITLE
How to configure debugging on existing console projects? 

### ISSUE THREAD

**Issue by kitingChris** [dotnet/docs#38853]
### Type of issue

Missing information

### Description

This tutorial assumes that an launch.json exists. 
No explanation on how to set up the debugger correctly.
Please provide more information about launch settings and how to configure debugging properly.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tutorials/debugging-with-visual-studio-code

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tutorials/debugging-with-visual-studio-code.md

### Document Version Independent Id

f5df932b-b092-2832-9c9a-61a9c43dcdb3

### Article author

@tdykstra

### Metadata

* ID: 40d7fd04-e358-9a83-aef2-bfcba1169699 
* Product: **dotnet-fundamentals**

---
[Associated WorkItem - 196546](https://dev.azure.com/msft-skilling/Content/_workitems/edit/196546)

**Comment by tdykstra** [comment]
This tutorial is one in a series, and the first in the series is the one that sets up the files in the .vscode folder. That's why the first in the series is listed as a prerequisite. Follow the directions in the first tutorial and you'll be able to start debugging in the second tutorial. Note the advice in the first tutorial Prerequisites section warning that for this to work, the new extension C# Dev Kit should not be installed.
