### ISSUE TITLE
Tick

### ISSUE THREAD

**Issue by massara2003** [dotnet/docs#39085]
### Type of issue

Code doesn't work

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1061?f1url=%3FappId%3Droslyn%26k%3Dk(CS1061)#to-correct-this-error

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs1061.md

### Document Version Independent Id

df4263c1-477a-3c32-9abe-3fcb850e6c1b

### Article author

@BillWagner

### Metadata

* ID: 60c946d7-649b-44e4-49a9-543565904d18 
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**

**Comment by massara2003** [comment]
tick

**Comment by BillWagner** [comment]
Hi @massara2003 

Our bot closed this because you didn't provide any information about the issue.

What information do you need that isn't available in this page?

If you want specific help on your application, you should post a small sample on the [Q & A](https://learn.microsoft.com/answers/tags/309/csharp) site.

I've added the "needs more info" label because we need more information to update the article.
