### ISSUE TITLE
"Provide Feedback" button sends user to wrong feedback site

### ISSUE THREAD

**Issue by SRNissen** [dotnet/docs#39093]
### Type of issue

Other (describe below)

### Description

Reading the article, I had some feedback.

So I clicked "Provide feedback" and wrote a suggestion for an improvement to dotnet:

https://developercommunity.visualstudio.com/t/Treat-warnings-as-errors-on-a-per-file/10556031?viewtype=all

You will notice that the URL is "`.visualstudio.com`"

I was informed that the thing I wanted was already available by using the a visual studio feature. When I clarified that I was using vscode, I was informed that I was on a visual studio specific site.

...

Well yes. Apparently. Can't say I noticed before I was told, I was just on the site that I was guided to directly from the very not visual studio specific C# language reference, when I pressed the button about wanting to provide feedback on dotnet.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/preprocessor-directives.md

### Document Version Independent Id

501be68d-5ad0-18d9-8958-54215bb57fc0

### Article author

@BillWagner

### Metadata

* ID: 716913e5-dbbe-bdb0-909a-4d8c2dc7be97 
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**

---
[Associated WorkItem - 199061](https://dev.azure.com/msft-skilling/Content/_workitems/edit/199061)

**Comment by BillWagner** [comment]
Hi @SRNissen 

I'm going to close this. 

I see that one of the compiler team members provided an answer on the Developer Community issue.

We chose to use the developer community site because it's simpler than asking readers to navigate the many repos for .NET on GitHub.

That said, in the future, if you have requests for the language, you can also create an issue on the [dotnet/csharplang](https://github.com/dotnet/csharplang/issues) repo. 

Both locations are checked by the same teams.
