### ISSUE TITLE
Highlight the runnable nature of samples in API Ref

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#3930]
In the DateTime reference, highlight the runnable nature of the C# samples:

- [ ] Change the intro wording to add "runnable" in the opening.
- [ ] Consider adding a quick sample above the fold.

Note that the second task would be jarring without a VB interactive experience.

/cc @LadyNaggaga

**Comment by ChrisMaddock** [comment]
This is really cool! 😄 Can't wait for this to become more widespread - would love to make use of it for the NUnit Docs at some point too.

I presume the eventual plan is for this to be rolled out to all the docs? Is there a central issue tracking that, or is it all being handled internally?

**Comment by mairaw** [comment]
@eisenbergeffect to talk about rollout strategy

**Comment by EisenbergEffect** [comment]
For conceptual content, the run functionality can be turned on for any sample at will. This is mostly about the content team determining that an individual sample will work correctly in that environment.

For reference content, I don't think we want to turn it on everywhere, since we can't guarantee that all reference samples will work in the REPL experience. I'm not sure if we have a way to individually enable those. There was an email conversation recently but I wasn't sure where that landed. @dend may be able to comment on this along with @BillWagner

**Comment by BillWagner** [comment]
We can configure the interactive feature in content.

Use "csharp" as the language for displaying C#.  Use "csharp-interactive" to use C# with the interactive REPL experience.

For include files, the tags are [code-csharp] and [code-csharp-interactive], respectively.

**Comment by mairaw** [comment]
DateTime reference already has a boilerplate with the explanation of the Run button.
