### ISSUE TITLE
.NET Framework 3.5.1 should be listed under "Applied to"

### ISSUE THREAD

**Issue by lextm** [dotnet/docs#3931]
I believe .NET Framework 3.5.1 is still supported as part of Windows (per your support policies). So no matter how old it is, it should be listed under "Applied to" section of a .NET API (like `WindowsIdentity` class).

> In the meantime, .NET Framework 4.5 and 4.5.1 are not supported any more (also per your support policies), so it would be strange to see them listed. Thus, if you really care about **consistency**, there are more works to be done here (either remove 4.5 and 4.5.1, or add all framework releases).

**Comment by mairaw** [comment]
Hi @lextm, yes, you're right. It's been in my backlog to add 3.5 to the list of assemblies we reflect against. 

Due to compliance requirements, we cannot simply remove any version of the documentation for the .NET Framework, So we're waiting for our archive site to be launched and ready to handle API reference archival. Then, we can move the unsupported versions there and our legal obligations can be met. 

@dend I'm not sure if there are any plans on listing when an API was actually introduced for each platform similar to what we have on MSDN.

**Comment by rpetrusha** [comment]
3.5 now appears in the **Applies to** section. Closing.
