### ISSUE TITLE
Parameter 'name' cannot be empty

### ISSUE THREAD

**Issue by KristinBethea** [dotnet/docs#39391]
### Type of issue

Missing information

### Description

[Enter feedback here]
I am trying to update my nuget and it says I need to add the name of the source. I add the name of the source and then it says it doesn't recognize the name of the source as a command. I tried with and without quotation marks.  

It would be very helpful if you could provide more examples of updating nuget commands.
Thanks!

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-update-source

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-nuget-update-source.md

### Document Version Independent Id

6f933117-c953-108b-9643-0d2e0d071873

### Article author

@tdykstra

### Metadata

* ID: a57fb8d7-4c24-ea3c-1679-310ce977d71d 
* Service: **dotnet-fundamentals**

---
[Associated WorkItem - 208205](https://dev.azure.com/msft-skilling/Content/_workitems/edit/208205)

**Comment by Nigusu-Allehu** [comment]
As mentioned in https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-update-source#description, the `
dotnet nuget update source ` command is used to update a package source in a nuget config file. A nuget config file is used to define various settings and configurations for NuGet, such as package sources.

For example, let say you have a source that you would like to be added to your nuget configuration. You can do that by using the following command `dotnet nuget add source [package source path] --name [name]`
As an example I will add `https://api.nuget.org/v3/index.json` as a source to my nuget config.
``` powershell
> dotnet nuget add source https://api.nuget.org/v3/index.json --name mySource
```
If the source path specified and name do not exist in your config file, the command will add it to the list of sources in your nuget config. If you would like to see the list of all the sources that have been configured, you can use the command `dotnet nuget list source`. The command will list the source names with their paths.
it would look something like
```
Registered sources
  1. mySource
          https://api.nuget.org/v3/index.json
```

Now this is where `dotnet nuget update source` becomes useful. What if you would like to update one of the sources that were listed? For example, let us say we want to update `mySource` to point to a different path(source): C:/myNewNuGetSource. 
We can do that as follows:

``` powershell
> dotnet nuget update source mySource --source C:/myNewNuGetSource
```

Now if you do `dotnet nuget list source`, you should see that `mySource` has been updated to point to the new source.

In you case, you are getting `Parameter 'name' cannot be empty` error because the name of the source you are trying to update is missing. In my previous example, `dotnet nuget update source --source C:/myNewNuGetSource` would have caused the `Parameter 'name' cannot be empty` error. You can resolve that by making sure the name of the source you are trying to update is present.
