### ISSUE TITLE
AddNewtonsoftJson

### ISSUE THREAD

**Issue by Nehal-NB** [dotnet/docs#39665]
### Type of issue

Code doesn't work

### Description

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'IMvcBuilder' does not contain a definition for 'AddNewtonsoftJson' and no accessible extension method 'AddNewtonsoftJson' accepting a first argument of type 'IMvcBuilder' could be found (are you missing a using directive or an assembly reference?)

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1061?f1url=%3FappId%3Droslyn%26k%3Dk(CS1061)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs1061.md

### Document Version Independent Id

df4263c1-477a-3c32-9abe-3fcb850e6c1b

### Article author

@BillWagner

### Metadata

* ID: 60c946d7-649b-44e4-49a9-543565904d18 
* Service: **dotnet-csharp**
* Sub-service: **errors-warnings**

**Comment by BillWagner** [comment]
hi @Nehal-NB 

What information did you need in this article to fix the error in your code? I've added the "needs more info" label because we need more info to improve the doc.

If you're looking for help with your application, you should post a question on our [Q & A site](https://learn.microsoft.com/answers/tags/309/csharp) with a sample.
