### ISSUE TITLE
Capitalization error for INumber

### ISSUE THREAD

**Issue by SamuelMcAravey** [dotnet/docs#40041]
### Type of issue

Typo

### Description

There is a typo on the following line in the section 'Errors in interface declaration': "For example, Inumber<T> can declare"

The code fragment 'Inumber' is mis-capitalized.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/static-abstract-interfaces?f1url=%3FappId%3Droslyn%26k%3Dk(CS8920)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/static-abstract-interfaces.md

### Document Version Independent Id

3e88b1be-6262-c93e-99d2-7f3d6aace3d8

### Article author

@BillWagner

### Metadata

* ID: 6c5f11ea-10d2-77e3-1642-b52ba0905dd1 
* Service: **dotnet-csharp**
* Sub-service: **errors-warnings**

**Comment by BillWagner** [comment]
Thanks for pointing this out @SamuelMcAravey 

I've opened a PR to fix this issue.

In the future, when you find these kinds of issues where the fix is clear, you can click the pencil icon at the top of the article to create a PR instead of writing the issue. Either way, thanks for helping us improve.
