### ISSUE TITLE
シリアルポート自動取得

### ISSUE THREAD

**Issue by MATSUDA-YUJI** [dotnet/docs#40980]
### Type of issue

Code doesn't work

### Description

Dim SerialStr(4) As Byte    '//CP2102のdefaultSerialは0001
SerialStr(0) = &H30
SerialStr(1) = &H30
SerialStr(2) = &H30
SerialStr(3) = &H31
Dspserialstr = ConvertToString(SerialStr(), 4)   '// "0001"

BC30105 ERROR

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/visual-basic/misc/bc30105?f1url=%3FappId%3Droslyn%26k%3Dk(BC30105)#to-correct-this-error

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/visual-basic/misc/bc30105.md

### Document Version Independent Id

ccf238a6-f40e-1998-e5de-565ba699ad33

### Article author

@KathleenDollard

### Metadata

* ID: 3c99b034-3731-d8fc-231d-24d1e9cfe5ed 
* Service: **dotnet-visualbasic**
* Sub-service: **errors-warnings**

**Comment by adegeo** [comment]
Hello. This forum here isn't really for coding problems. I do suggest you try places like StackOverflow and Microsoft Q&A for coding language help. For help about array's, see [Visual Basic Arrays](https://learn.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/arrays/).

It looks like you're trying to convert the array into a string. The method you used `Convert.ToString(SerialStr(), 4)` expects a single type, such as an individual `Byte`, to convert to a string. You're passing in `SerialStr()`, which is the array variable without a specific index, which is why the error appeared. You need to provide which individual array element you want to convert, such as `SerialStr(1)` or `SerialStr(2)`.

It looks like you're putting in character codes, such as the physical character 0 and 1 into the array as bytes. A byte can be converted into a char then added to a string. This code should work. Notice I also changed `SerialStr(4)` to `SerialStr(3)`. In VB you specify the array upper bound, not the array total number of elements. In other languages, like C#, you specify the total number.

```vb
Dim Dspserialstr As String
Dim SerialStr(3) As Byte
SerialStr(0) = &H30
SerialStr(1) = &H30
SerialStr(2) = &H30
SerialStr(3) = &H31

Dim builder As New System.Text.StringBuilder

For Each item In SerialStr
    builder.Append(Convert.ToChar(item))
Next

Dspserialstr = builder.ToString()
builder = Nothing

Console.WriteLine(Dspserialstr)
```
