### ISSUE TITLE
What are `$ID` and `$VERSION`?

### ISSUE THREAD

**Issue by rwb196884** [dotnet/docs#41420]
### Type of issue

Code doesn't work

### Description

What are $ID and $VERSION?

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#register-the-microsoft-package-repository

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md

### Document Version Independent Id

1d732b15-9e64-633a-000c-ad96d9d3818a

### Article author

@adegeo

### Metadata

* ID: 80707602-f283-e796-d3b8-3287fbc011dc 
* Service: **dotnet-fundamentals**
* Sub-service: **install**

---
[Associated WorkItem - 264464](https://dev.azure.com/msft-skilling/Content/_workitems/edit/264464)

**Comment by adegeo** [comment]
@rwb196884 Our automation closed this issue instantly because you didn't type anything in the description field, which is a common in spam comments. However, I noticed your subject is valid, so I reopened this.

You're write, this info is missing. While moving things around for this article something got out of sync. I'll work on getting it fixed. 

$ID is the distro and $VERSION is the version of the distro. You can browse the URL here: https://packages.microsoft.com/config/
