### ISSUE TITLE
Instructions appear to conflict for this one, who is new to Git.

### ISSUE THREAD

**Issue by Chris8top8he8r** [dotnet/docs#41527]
### Type of issue

Other (describe below)

### Description

[Enter feedback here]
Hi Git.

I tried to download in command prompt with git clone and failed authentication, and just learned it won't take pws any more.  Trying to figure out installation of GCM on Ubuntu.

https://github.com/git-ecosystem/git-credential-manager/blob/release/docs/install.md

At the above URL it says Linux preferred GCM install method is .NET 7.  Under .NET Tool heading I click on .NET version 7 and it takes me to 

https://learn.microsoft.com/en-us/dotnet/core/install/linux#packages

where I click on Ubuntu and get to 

https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu

and scroll down to heading "Supported Distributions" and I see a version 7 listed in the table for Ubuntu 24 as a backport.  Scroll to end of that heading and it says version 7 is no longer supported.  For me as a new person it doesn't sound good.  :)  I'll have to learn what a backport is.  In the meantime I cannot git clone from command line by pw.  And don't know proper way to install GCM.  Wouldn't there be a way to use my Authenticator app on my phone to authenticate in CLI?  I have no idea.  My only point with all this, is that it seems out-of-date because the first Git URL says use version 7 .NET and Microsoft says it is not supported.  That's all.  Thanks for listening.  Chris wigglemylegs.com

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-install?pivots=os-linux-ubuntu-2404&tabs=dotnet8

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu-install.md

### Document Version Independent Id

e7286112-86cf-8d6a-655b-ee851f396d15

### Article author

@adegeo

### Metadata

* ID: 72799d86-e122-1706-18a2-d0bfde699bfc 
* Service: **dotnet-fundamentals**
* Sub-service: **install**

**Comment by adegeo** [comment]
Hi @Chris8top8he8r Did you get this resolved? Yes, .NET 7 is unsupported. It's up to GCM to update their app to .NET 8. So yes you can install .NET 7 still, but there isn't any support from Canonical and Microsoft.

Regarding the documentation I would love to get anymore feedback you have of your experience. Ubuntu can get complicated for sure. The table listing "Backports" has a link in the table header, did you see that link? Did it take you time to discover it? I was hoping it would be intuitive that someone sees "Backports" and not knowing what it is, sees that link and clicks it.

**Comment by Chris8top8he8r** [comment]
Hi Steve.

Thanks for your reply.

Not sure if I can help with this, but I’ll try.

I was able to get it all working.  Whether it is fully correct I don’t know yet.  I can only remember the basic idea of my confusion with the links.  Having stumbled through it to success, makes it difficult to remember.

When starting, I didn’t pay attention to the difference between .NET SDK and .NET Runtime.  I figured the SDK would include a runtime, and the runtime is probably all I need.  So wasn’t paying enough attention and trying to go too fast without reading details.  When clicking in the table for 7.0, 6.0 backports, I somehow installed version 6 of some type because it was supported and 7 was no longer supported.  That made me believe the docs at Git which had referred me there were out-of-date, since the Git URL link said install version 7.  After installing 6, GCM still wouldn’t work.  Then I went back and somehow decided, possibly from advice at stackoverflow, that I might as well install version 8.  So then I had 6 and 8 and GCM wouldn’t work.  I may have even mixed Ubuntu .NET and Microsoft .NET.  Cannot remember how I did it.  Then I found the following after searching my error which stemmed from having multiple versions of .NET, so no …/fxr.

https://stackoverflow.com/questions/73753672/a-fatal-error-occurred-the-folder-usr-share-dotnet-host-fxr-does-not-exist

This link above is pretty well laid out and was the only place I could find things described this way.  I checked my instructions for AOSP builds at developer.sony.com and determined I needed .NET SDK.  Once I knew that, I could focus more.  Then I did all these steps in the link above and first installed 8.  GCM still didn’t work.  Then because this link above stated to install other versions in parallel with his method, I then installed 7.0.  Then I had 7 and 8.  Following up on reported errors or problems that Ubuntu terminal reported, then got me to install OpenSSL and get certs and things.  Eventually got through GCM authentication and sync’d repo.  Whew.

What wasn’t clear to me in this process was that simply because something wasn’t supported, doesn’t mean it won’t work.  Just means it’s beyond EOS or EOL.  Also, it might have helped if the Git link to install version 7 would have said I must use 7 even though it is no longer supported, and GCM does not work with 6 nor 8.

Thanks again.

Chris





***@***.***
***@***.***
Christopher Jay Wolff
Wiggle My Legs, Incorporated
Wigglemylegs.com
200 East Liberty Street, Unit 8377
Ann Arbor, Michigan  48107
Voicemail (734) 276-5979
Live cell calls and texting use Signal app with (734) 276-5979
Office (734) 405-8772
Or, click here for live chat ***@***.*** <https://1090.3cx.cloud/wigglemylegs> or phone ***@***.*** <https://1090.3cx.cloud/wigglemylegs> right now in browser.


***@***.***<https://www.instagram.com/wigglemylegs/>

**Comment by adegeo** [comment]
Thank you for all of the info, this is valuable feedback!

**Comment by adegeo** [comment]
I've been thinking about this issue on and off for the last few months. I'm not totally sure where to go with it simply because Linux can get complicated, and it has a lot of concepts that take time to learn. The install docs here aren't extensive in every place about it, because it muddles the info for the majority of users that basically know what they're doing (for at least get through it as though they did 😁). I don't consider myself an expert either, I've learned a lot as I've written these docs and made sure to play with Linux more. I've always found these situations infuriating where you can't get these things fixed, because I just want it to work.

The supported vs non-supported is an interesting issue. I tried to keep old versions listed for this exact scenario, where someone has a version of software that says it requires the out-of-date runtime. There are those that think it should just be scrubbed out entirely, but my personal preference is to archive rather than delete, but I digress.

We're in a transition period with Ubuntu where, as of this last month, no longer building .NET for Ubuntu and Canonical has taken over. This gets rid of the issue where people have mixups with Microsoft .NET and Ubuntu .NET packages. Canonical also took over the .NET Snap packages, which is another way to install .NET.

I'm going to close this issue, but I just wanted to reiterate that your feedback is seared into my brain and as I go forward with all of the Linux docs, I'm keeping it in mind. It's an iterative process.

**Comment by Chris8top8he8r** [comment]
Hello Steve.

Thanks for the professional follow-up and the heads up on .NET for Ubuntu!!  I seriously didn’t expect to hear from you about this, but it’s a very thoughtful note and I appreciate it.  You’re kind to include me here.  No wonder they have you in the job you’re in there.

I hope my thank you note reply doesn’t reopen your closed case.  Please close again if so.

May good fortune and God’s blessings be with you!!

:)

Chris
