### ISSUE TITLE
DisableWinExeOutputInference section incorrectly states it applies to .NET 5 SDK and later

### ISSUE THREAD

**Issue by jcotton42** [dotnet/docs#42096]
### Type of issue

Outdated article

### Description

DisableWinExeOutputInference says "Applies to .NET 5 SDK and later."

This is outdated, .NET 6 and later do not require this property in order to set the OutputType to Exe for WPF and WinForms apps https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/6.0/outputtype-not-set-automatically.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props-desktop#shared-settings

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/project-sdk/msbuild-props-desktop.md

### Document Version Independent Id

76ee87b9-2409-85e8-1d84-542a8bea05c9

### Article author

@adegeo

### Metadata

* ID: 27169485-5ab9-abeb-9cb9-92f75fbb6867 
* Service: **dotnet-fundamentals**

**Comment by adegeo** [comment]
Thanks for spotting this!

**Comment by jcotton42** [comment]
The PR as merged entirely removed the .NET 5 information, instead of merely clarifying what runtimes it applied to. I don’t think that was the right choice.

**Comment by adegeo** [comment]
Hi @jcotton42 

We've been trying to remove out-of-date information that doesn't really have bearing on the product anymore. Considering .NET 5 was a short-term release and this change was only introduced for that one version, I don't think this is relevant information to keep around. .NET 5 came out in 2020 (4 years ago in a few months) and support ended in 2022 (a little over 2 years ago).

**Comment by jcotton42** [comment]
@adegeo the docs consistently keep around information on old .NET versions. Look at the BCL reference docs, it still has everything going back to Framework 1.1.

**Comment by adegeo** [comment]
Yes, that is true, but it's different in the modern .NET world where these versions are supported for a short span, versus .NET Framework which had lifecycles of a decade or longer.

This really was a judgement call on my part. I'm happy to discuss it. I felt the technical dept of this particular setting wasn't worth keeping around considering the following points:

1. This scenario **only** applies to using the .NET 5 MSBuild via the .NET 5 SDK.

   It becomes confusing because if you use .NET SDK 6+ but target .NET 5, you **don't** get the behavior that was described in that article, and the `<DisableWinExeOutputInference>` setting does nothing.

1. It's a STS release that's no longer supported.
1. The setting was introduced specifically for .NET 5.
1. It was removed in .NET 6 due to customer complaint.
1. There isn't anything else in that article specific to .NET 5.

**Comment by jcotton42** [comment]
@adegeo I still am personally against the idea, because even though .NET 5 is out of support, that particular detail still applies to that SDK.

Sure, people probably aren't making _new_ GUI projects targeting .NET 5 using the .NET 5 SDK, but someone might be maintaining an existing one, and if they run into this issue they won't be able to as easily find the solution to their problem. Why remove the information instead of simply clarifying when it applies?

**Comment by adegeo** [comment]
>Sure, people probably aren't making new GUI projects targeting .NET 5 using the .NET 5 SDK, but someone might be maintaining an existing one, and if they run into this issue they won't be able to as easily find the solution to their problem.

That is a good point. While I was considering restoring the content but with a focus on how it's only related to .NET 5 SDK, I discovered that it's also documented here; https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/5.0/automatically-infer-winexe-output-type#recommended-action

The other part of your statement is interesting `if they run into this issue they won't be able to as easily find the solution to their problem` How would someone even find this information in the real world? Maybe we can do some improvements to SEO on it, but I fear the problem is too generic for search even uncover for a user running into it. Trying to think like the user, what actual scenario would they be in where they needed this information, and what would they search for?
