### ISSUE TITLE
Table data for breaking change article "Adding a ZipArchiveEntry with CompressionLevel.."

### ISSUE THREAD

**Issue by jespersh** [dotnet/docs#42425]
### Type of issue

Typo

### Description

The table with the data
| `CompressionLevel` | Bit 1 | Bit 2 |
|--------------------|-------|-------|
| `NoCompression`    | 0     | 0     |
| `Optimal`          | 0     | 0     |
| `SmallestSize`     | 1     | 0     |
| `Fastest`          | 1     | 1     |

Based on the page https://learn.microsoft.com/en-us/dotnet/api/system.io.compression.compressionlevel?view=net-8.0 I think it should be: 

| `CompressionLevel` | Bit 1 | Bit 2 |
|--------------------|-------|-------|
| `NoCompression`    | 0     | 1     |
| `Optimal`          | 0     | 0     |
| `SmallestSize`     | 1     | 1     |
| `Fastest`          | 1     | 0     |

Maybe reorder the rows like

| `CompressionLevel` | Bit 1 | Bit 2 |
|--------------------|-------|-------|
| `Optimal`          | 0     | 0     |
| `Fastest`          | 1     | 0     |
| `NoCompression`    | 0     | 1     |
| `SmallestSize`     | 1     | 1     |

And should bit 2 be listed first? hmm

| `CompressionLevel` | Bit 2 | Bit 1 |
|--------------------|-------|-------|
| `Optimal`          | 0     | 0     |
| `Fastest`          | 0     | 1     |
| `NoCompression`    | 1     | 0     |
| `SmallestSize`     | 1     | 1     |

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/9.0/compressionlevel-bits

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/compatibility/core-libraries/9.0/compressionlevel-bits.md

### Document Version Independent Id

6c5412db-188e-1ce4-de8f-f5a3585c0930

### Article author

@gewarren

### Metadata

* ID: 12d7748c-529c-0c43-2a22-cb49cc47b807 
* Service: **dotnet-fundamentals**

**Comment by gewarren** [comment]
@edwardneal Are there any changes needed to [this table](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/9.0/compressionlevel-bits#new-behavior)?

**Comment by edwardneal** [comment]
Thanks for the ping @gewarren. The table in the published document is correct as-is.

The values of the `CompressionLevel` enumeration don't precisely correspond to the values in the ZIP header, and this is by design - they're not the same thing. This enumeration is also passed to BrotliStream, DeflateStream, GZipStream and ZLibStream, so the `CompressionLevel` enumeration is effectively a way to describe the tradeoffs .NET should make during compression rather than a set of values which are tied to any one single compression method.
