### ISSUE TITLE
Example shows only compare and return instructions

### ISSUE THREAD

**Issue by bravequickcleverfibreyarn** [dotnet/docs#42827]
### Type of issue

Typo

### Description

![Example](https://github.com/user-attachments/assets/878fa130-227d-4517-abdb-5de103e626db)

Description is written as if example bellow should be more verbose but is shows only compare and return instructions.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-9/runtime

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/whats-new/dotnet-9/runtime.md

### Document Version Independent Id

13391d3d-7426-ac0c-d41c-f1754a1baffc

### Article author

@gewarren

### Metadata

* ID: b651446d-aea3-1b80-d99a-9033b794c387 
* Service: **dotnet-fundamentals**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+13391d3d-7426-ac0c-d41c-f1754a1baffc)

**Comment by gewarren** [comment]
@amanasifkhalid Can you look at this issue when you get a chance?

**Comment by amanasifkhalid** [comment]
> Description is written as if example bellow should be more verbose but is shows only compare and return instructions.

@bravequickcleverfibreyarn could you please elaborate on how the description implies the below example should be more verbose? The way I read it, the "updated assembly" is what the code looks like after the aforementioned JIT optimizations kicked in. Above the snippet you linked, the blog post includes the unoptimized code with the heap allocations, conditional moves, etc.

**Comment by amanasifkhalid** [comment]
@gewarren do you think it would be clearer if we rewrote the explanation as "In this example, the compiler now avoids the heap allocations, and it also evaluates the expressions..." to avoid the "not only... but..." form?

**Comment by bravequickcleverfibreyarn** [comment]
I shall elaborate. I would expect that example is showing more lines of optimized output. Namely how does inlined code looks w/o _boxing_ instructions.

**Comment by amanasifkhalid** [comment]
> Namely how does inlined code looks w/o boxing instructions.

I see. You're correct that the code should initially become more verbose from the JIT inlining the `Compare` method. However, after the JIT unboxes `x` and `y`, it can determine that `x` and `y` are both integers, and their values are known. Because the JIT knows the values of `x` and `y`, it no longer needs the `Compare` method at all; the JIT can const-eval `x == y` at compile-time. So it determines `3 != 4`, which implies `result` is false, which implies we should return 100 -- hence the small amount of assembly generated at the end.

The clause "but it also evaluates the expressions `x.Equals(y)` and `result ? 0 : 100` at compile time" is doing some heavy lifting here. I suppose we can add some more detail after it, like "Because the JIT can now determine that `x` and `y` aren't equal, it knows `result` will be false, which means the method should just return `100`." @bravequickcleverfibreyarn would this help clarify the example?

**Comment by bravequickcleverfibreyarn** [comment]
Yes, that sounds fine. I did not even get a clue that I should figure this out.

**Comment by amanasifkhalid** [comment]
@gewarren are you able to open a PR for this, or would you like me to?

**Comment by gewarren** [comment]
> @gewarren are you able to open a PR for this, or would you like me to?

If you could, that would be awesome. Thanks!
