### ISSUE TITLE
FontCapitals enum .net framework versions missing

### ISSUE THREAD

**Issue by wstaelens** [dotnet/docs#4333]
https://docs.microsoft.com/nl-be/dotnet/api/system.windows.fontcapitals?view=netframework-4.7.1
vs.
https://msdn.microsoft.com/en-us/library/system.windows.fontcapitals(v=vs.110).aspx

.net framework version is available since 3.0 but on docs it only starts with "4.5, 4.5.1, 4.5.2, 4.6, 4.6.1, 4.6.2, 4.7, 4.7.1". The 3.0 is not included. Which is important information.

(+ the msdn version has empty examples. 😄 )

**Comment by mairaw** [comment]
Thanks @wstaelens for your feedback. I'll add @dend to this discussion to see if we could have the same behavior as in MSDN for the version info.  The reason this hapopens is because on docs we're only showing the versions we're reflecting against vs. the whole history,

For the empty examples on MSDN, we won't fix that, since we'll be redirecting to docs pretty soon.

**Comment by wstaelens** [comment]
well it is very very very useful to see when a function/class is initially supported. especially when customers do an upgrade and you get a crash that we directly see a possible reason :smile:

**Comment by mairaw** [comment]
Issue moved to https://github.com/MicrosoftDocs/feedback/issues/217
