### ISSUE TITLE
"Why can't I select a different C# version?" not addressed

### ISSUE THREAD

**Issue by Pxtl** [dotnet/docs#43428]
### Type of issue

Missing information

### Description

In Visual Studio 2022, this page is linked in the Advanced Build Settings of a .NET framework 4.7.2 project, with the caption "Why can't I select a different C# version?"

No answer to that question is provided on this help-page.

!["Why can't I select a different C# version?" screenshot](https://github.com/user-attachments/assets/dcd7d1ec-39bd-4df2-bb6a-a521899095e2)

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/configure-language-version.md

### Document Version Independent Id

3f01c378-22e4-197c-a862-ab4a924506c7

### Article author

@BillWagner

### Metadata

* ID: 5694e62b-c756-1f62-4014-2ceafa54c011 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+3f01c378-22e4-197c-a862-ab4a924506c7)

**Comment by BillWagner** [comment]
@Pxtl 

Thanks for pointing this out. I've added it to our backlog, and I've added the "help wanted" label to this issue. 

The reason you can't change the LangVersion through the Visual Studio UI is because the default is the best supported configuration: The language version matches the target TFM. In the Visual Studio UI, you can change the target TFM (for example, from .NET 6 to .NET 9) and that will change the language version from C# 10 to C# 13). That change updates the configured language version to match.

**Comment by Pxtl** [comment]
Thanks, Bill.  The reason I was looking was I had an automated build that was failing (complaining about parse errors on a line with an arrow-property, so it was safe to assume it was a language feature) while VS was succeeding.  Logically I assumed it was some language setting of the proj file.  Turns out it had nothing to do with that, the build-script failed because it was using one of the many abandoned old versions of `msbuild.exe` that are kick around on modern development machines, which is why it didn't have support for modern language features.

Still, having better information in the article would've helped during debugging this problem.

**Comment by shethaadit** [comment]
Hi @BillWagner, I will work on this and raise the PR soon. :)
