### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by SayedHussein1** [dotnet/docs#43775]
### Type of issue

Code doesn't work

### Description

 events.AddAndroid(android =>
 {
     android.OnCreate((activity, bundle) =>
     {
         var action = activity.Intent?.Action;
         var data = activity.Intent?.Data?.ToString();

         if (action == Android.Content.Intent.ActionView && data is not null)
         {
             activity.Finish();
             System.Threading.Tasks.Task.Run(() => HandleAppLink(data));
         }
     });
 });
AddAndroid 
'type' does not contain a definition for 'name' and no accessible extension method 'name' accepting a first argument of type 'type' could be found (are you missing a using directive or an assembly reference?).

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1061?f1url=%3FappId%3Droslyn%26k%3Dk(CS1061)

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs1061.md

### Document Version Independent Id

df4263c1-477a-3c32-9abe-3fcb850e6c1b

### Article author

@BillWagner

### Metadata

 events.AddAndroid(android =>
 {
     android.OnCreate((activity, bundle) =>
     {
         var action = activity.Intent?.Action;
         var data = activity.Intent?.Data?.ToString();

         if (action == Android.Content.Intent.ActionView && data is not null)
         {
             activity.Finish();
             System.Threading.Tasks.Task.Run(() => HandleAppLink(data));
         }
     });
 });
AddAndroid 
'type' does not contain a definition for 'name' and no accessible extension method 'name' accepting a first argument of type 'type' could be found (are you missing a using directive or an assembly reference?).

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+df4263c1-477a-3c32-9abe-3fcb850e6c1b)

**Comment by BillWagner** [comment]
Hi @SayedHussein1 

The best location to post this is our [Q & A](https://learn.microsoft.com/answers/tags/309/csharp) site. You may need to include more of your current code to get a good answer. The snippet you posted doesn't use the symbol `name`. From what's posted, I can't see what the error is.

The article here is correct, in that the compiler error is because you're trying to use a symbol (`name`) that isn't defined. The article can't include specific information for each application. I'll close this, but I do encourage you to ask on the Q & A site.
