### ISSUE TITLE
What kind of media type does StringContent constructor support?

### ISSUE THREAD

**Issue by chucklu** [dotnet/docs#4487]
[StringContent(String, Encoding, String)](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.stringcontent.-ctor?view=netframework-4.7#System_Net_Http_StringContent__ctor_System_String_System_Text_Encoding_System_String_)
The third parameter is  mediaType  String 
The media type to use for the content.

When I pass "application/base64" as the mediaType, I got the following error message.
```c#
new StringContent(fileContent, Encoding.UTF8, "application/base64")
```
> The best overloaded method match for 'System.Net.Http.StringContent.StringContent(string, System.Text.Encoding, string)' has some invalid arguments
> ExceptionType:Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
> Assembly:Anonymously Hosted DynamicMethods Assembly
> Method:System.Net.Http.StringContent CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Type, System.Object, System.Text.Encoding, System.String)

I  find  the media type from this [page](https://www.sitepoint.com/mime-types-complete-list/).
I am not sure if this class can support all media types.
I wonder if you guys can list how many media types are supported for StringContent's constructor.

**Comment by svick** [comment]
The error message talks about overload resolution, which means you're using `dynamic` and types of parameters you passed in couldn't be matched to any overload of the `StringContent` constructor.

I'm pretty sure this is because `fileContent` is not a `string`, which it has to be according to the method signature. This has nothing to do with the `mediaType` you used.

**Comment by chucklu** [comment]
@svick  Thanks, I forgot to convert dynamic type to string.
