### ISSUE TITLE
C# documentation: two "entry points" for async programming

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#4490]
While .NET Standard documentation has one [entry point](https://docs.microsoft.com/en-us/dotnet/standard/async) for asynchronous programming, the C# part of docs has two:
- [Asynchronous programming](https://docs.microsoft.com/en-us/dotnet/csharp/async) which is mostly about `async` and `await`
- [Asynchronous programming with async and await (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/) which explains `async` and `await` in-depth and provides examples.

Should those two be somehow combined (also a good opportunity to revise content)? Otherwise, people might land in the shorter version like in the #4379 issue.

As a quick fix, I've added cross-references between those pages as a part of the #4489 PR.

**Comment by rpetrusha** [comment]
Thanks for opening this issue, @pkulikov. This is indeed a good opportunity to revise content. The revision, though, is likely to be less than straightforward, since the second entry point, [Asynchronous programming with async and await](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/), is a result of migrating a combined Visual Basic/C# doc set into separate Visual Basic and C# versions. These two doc sets are basically duplicates of one another, except of course that revisions in one set are not necessarily made in the parallel doc set. There also is a doc set in the .NET documentation, [Task-based asynchronous programming](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/task-based-asynchronous-programming), that also repeats some of the content found in these two doc sets.
Over the next week or so, I'll take a look at the duplication and triplication, come up with what I think is  a reasonable plan of action to address it, and add it to the issue you've opened.

**Comment by spottedmahn** [comment]
Hi @rpetrusha - any updates?  Thanks 🙏

**Comment by rpetrusha** [comment]
Unfortunately, @spottedmahn, there is no update. Thanks, though, for pinging me. I'll schedule some time during our next sprint to work on a plan for the revision.
