### ISSUE TITLE
Revise How to: Use Selected Value... topic to display all XAML

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#4536]
# Revise How to: Use Selected Value... topic to display all XAML

## General

See Issue #4526 

The [How to: Use Selected Value, SelectedValuePath, and SelectedItem](https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/how-to-use-selectedvalue-selectedvaluepath-and-selecteditem) topic needs to be prevised to present the entire contents of the [window1.xaml](https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/how-to-use-selectedvalue-selectedvaluepath-and-selecteditem) file.  Highlighting should then be used to indicate the individual parts that are discussed in the topic. 

The code also needs to be modified, as PR #4526 suggests, and the text modified to more clearly explain the code.

@ManGupt @BillWagner

**Comment by ManGupt** [comment]
I agree with @BillWagner on updating the XAML code. Here is my suggestion:
changing <HierarchicalDataTemplate DataType="EmployeeInfo"
to <HierarchicalDataTemplate x:Key="SampleTemplate" DataType="EmployeeInfo" 
and
changing <TreeView ItemsSource.../>
to <TreeView ItemTemplate="{StaticResource SampleTemplate}" ItemsSource.../>

What do you think?

**Comment by ManGupt** [comment]
@rpetrusha I would love to do the modification. Just guide me as I am new.

**Comment by BillWagner** [comment]
@ManGupt I just noticed your previous comment. Most of our team was involved with the MVP summit last week, and missed some GitHub notifications.  

What can we do to help you get started?

**Comment by ManGupt** [comment]
How do I download the code "samples/snippets/csharp/VS_Snippets_Wpf/TreeViewSelectedValue/CS" to check the changes that I have made?

**Comment by ManGupt** [comment]
How can I add reviewers to my pull request #4662 ?

**Comment by svick** [comment]
@ManGupt 

> How do I download the code "samples/snippets/csharp/VS_Snippets_Wpf/TreeViewSelectedValue/CS" to check the changes that I have made?

You have to download the whole repository and then find the directory there. To download the repository, you have two choices:

1. Use git. This is the common approach that lets you keep an up-to-date local copy of the repository and also perform other operations.

    To do this, go to the main page of the repository, click *Clone or download* and either select *Open in …* if you want to use one of the offered choices of git client (like GitHub Desktop) or copy the URL and use it in your git client. If you're using git command line interface, the command to use would be `git clone https://github.com/dotnet/docs.git`.

2. Download a ZIP archive of the repository. This is not commonly used and makes sense only if you need access to a copy of the repository rarely.

    To do this, go to the main page of the repository, click *Clone or download* and select *Download ZIP*.

> How can I add reviewers to my pull request #4662 ?

I believe you can't actually add reviewers in a way GitHub would recognize (you would need "write access" to do that). GitHub already automatically added @BillWagner as a reviewer, because he's the "code owner" for C# samples.

If you want to notify someone else, you can add a comment to your Pull Request, mentioning the user with a `@` before their user name. It's also common to indicate that you're notifying someone of the PR by using `cc:` (which is a convention coming from email). So, if I wanted to notify you, I would write `cc: @ManGupt`.
