### ISSUE TITLE
Docs for Microsoft.Extensions (Configuration, Dependency Injection, Logging) packages

### ISSUE THREAD

**Issue by petroemil** [dotnet/docs#4567]
As of now, I believe these packages are maintained by the ASP.NET team and their documentation is also only available inside the ASP.NET Core section ([Configuration](https://docs.microsoft.com/en-gb/aspnet/core/fundamentals/configuration), [Dependency Injection](https://docs.microsoft.com/en-gb/aspnet/core/fundamentals/dependency-injection), [Logging](https://docs.microsoft.com/en-gb/aspnet/core/fundamentals/logging)), even though these are not ASP.NET Core specific libraries and are used by a number of other projects.

It would be nice if there would be a more generic introduction to these libraries in the .NET Core Guide section (for people building their own apps/services/libraries), and the ASP.NET Core (or any other project) docs could refer to that and just extend it with framework/library specific examples.

### Adding a task list

Edit by @Rick-Anderson 
~Port over all .NET content from ASP.NET Core repo - .NET fundamentals / Microsoft Extensions:~
Create .NET content versions of content in the ASP.NET Core repo - .NET fundamentals / Microsoft Extensions:

- [x] [Configuration](https://github.com/dotnet/docs/pull/20598)
- [x] [Generic Host](https://github.com/dotnet/docs/pull/20697)
- [x] [Dependency injection](https://github.com/dotnet/docs/pull/20758)
- [ ] [Logging](https://github.com/dotnet/docs/pull/20782)
- [ ] [Options pattern](https://github.com/dotnet/docs/pull/20813)

**Comment by mairaw** [comment]
Thanks @petroemil for your feedback. @Rick-Anderson @csharpfritz what do you guys think?

**Comment by Rick-Anderson** [comment]
@petroemil  sounds like a good idea. After the .NET Core version were written, we could refactor the ASP.NET Core versions.

**Comment by mairaw** [comment]
@richlander any thoughts on this request?

**Comment by tdykstra** [comment]
This has been languishing for more than a year now.  In theory it's a great plan, but as a practical matter it might never get implemented as it stands, since it would take a lot of time, and both content teams (.NET and ASP.NET) have extensive backlogs of higher-priority issues.

Here's an alternative approach that might adequately address the issue with much less time investment:
* Create brief introduction docs to publish in the .NET Standard or Core doc set, basically a single paragraph or so about the feature (DI/logging/configuration) that links to the ASP.NET Core doc for information about how to use the feature.
* In each ASP.NET Core doc add section(s) as needed on using the feature outside an ASP.NET app – maybe how to use it with generic host without the web host defaults.
* As part of this approach, I’d incorporate the non-ASP.NET scenarios into the migration docs as well, and get rid of the TOC entry  “[Logging (not ASP.NET Core)](https://docs.microsoft.com/en-us/aspnet/core/migration/logging-nonaspnetcore)”

**Comment by IEvangelist** [comment]
Port over all .NET content from ASP.NET Core repo - .NET fundamentals / Microsoft Extensions:

- [ ] [Configuration](https://github.com/dotnet/docs/pull/20598)
- [ ] Dependency injection
- [ ] Generic Host
- [ ] Logging
- [ ] Options pattern

**Comment by Rick-Anderson** [comment]
> Port over all .NET content from ASP.NET Core repo - .NET fundamentals / Microsoft Extensions:

That's not a good idea. 

* It looks like 90%+ of the target audience is ASP.NET Core. 
* The ASP.NET Core team maintains these, so it's best left in the ASP.NET Core repository.

**Comment by IEvangelist** [comment]
> That's not a good idea.

Per our call yesterday, and the discussion with Tom - we're moving forward with this for the following reasons:

- New .NET developers coming to our repo need to understand these fundamentals which _are not_ specific to ASP.NET Core
  - This is a gap in our .NET content, we cannot assume that all developers are building web apps
  - 90%+ is an estimate and there is no data to support that claim
- All of the Microsoft Extensions were intentionally architected to serve more than just web, there are other workloads that are included, such as but not limited to; Cloud native, Gaming, IoT, Mobile, Desktop, Machine learning, Data, etc.
- Customers _need_ examples of doing these things without ASP.NET Core
- All of these efforts are being tracked / prioritized appropriately for the [".NET 5 Wave"](https://github.com/dotnet/docs/issues/18923)
