### ISSUE TITLE
How to: Display Windows Forms in the Designer is not working for current version

### ISSUE THREAD

**Issue by yasirbhutta** [dotnet/docs#4604]
How to: Display Windows Forms in the Designer **link** is not working for current version 

see the following article for above mentioned issue.
https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/how-to-add-controls-to-windows-forms

**Comment by svick** [comment]
What exactly do you mean by "not working"?

**Comment by yasirbhutta** [comment]
**## Following link is not working for current version of dot net.**
![image](https://user-images.githubusercontent.com/12986974/37254884-455ff50e-2566-11e8-80af-20bc2c54b484.png)
error after opening above mentioned link .......
![image](https://user-images.githubusercontent.com/12986974/37254907-8e006a1e-2566-11e8-8002-2824f5d3a407.png)

**Comment by mairaw** [comment]
We should change the link to go to the previous version: https://msdn.microsoft.com/en-us/library/bf3f1e5b-ea07-4529-85c6-6af3ded0cec5(v=vs.100)

**Comment by eriawan** [comment]
@mairaw 
Could I create a new page for this with the content from the MSDN link for VS 2010? 

Imho, it deserves its own page in docs instead of linking back to older MSDN link.
Because I need to update the links inside the MSDN link to sync with the contents on docs, because the links in the old MSDN points to other older MSDN links.

For example, the link of "Event Handler Overview" link in this paragraph points to other older MSDN link:

![image](https://user-images.githubusercontent.com/8773147/37899315-64b6e5e2-3115-11e8-9ed0-279fc9f7e26d.png)

And if new page is created in this docs, then we could link the Event Handler overview to this docs link instead: 
https://docs.microsoft.com/en-us/dotnet/framework/winforms/event-handlers-overview-windows-forms

**Comment by eriawan** [comment]
@mairaw 

Please confirm about my proposal in previous comment https://github.com/dotnet/docs/issues/4604#issuecomment-376110094
I'd like to work on this but I thought I still had some questions to confirm.

Or is this issue feedback closed forever?

**Comment by mairaw** [comment]
Tagging @adegeo since I'm no longer on the docs team

**Comment by adegeo** [comment]
@eriawan My plan for .NET 5 winforms didn't include this type of content (as it's not really called out in the existing active winforms content). However, I think this is valuable content. We should really cover all sorts of steps that users do with Visual Studio as how-to content.

I've added a main TOC section "Using Visual Studio" to the [planning issue](https://github.com/dotnet/docs-desktop/issues/72). Let's close this issue and use a [new issue I've opened](https://github.com/dotnet/docs-desktop/issues/181) to discuss the common user scenarios related to using Visual Studio.
