### ISSUE TITLE
Create content for "Creating Libraries in Visual Studio"

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#470]
This issue tracks creating content for this topic: ~~http://dotnet.github.io/docs/core-concepts/libraries/libraries-with-vs.html~~

The above link moved. The new location is: https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries-with-vs

This topic parallels the topic for creating libraries using cross-library tools (~~http://dotnet.github.io/docs/core-concepts/libraries/libraries-with-cli.html~~) but will provide an emphasis on using Visual Studio.

The above link moved. The new location is: https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries

**Comment by EricZimmerman** [comment]
both those links no worky. id love to move to core but half if it seems to not be working, at least in VS 2015

**Comment by mairaw** [comment]
This issues needs to be updated or even closed since we moved to a new site and restructured the Table of Contents. @BillWagner can you check?

The tooling is still in Preview release @EricZimmerman. Have you checked this topic already: https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/using-on-windows?

**Comment by BillWagner** [comment]
Thanks for helping us make this better. I updated both incorrect links above.

**Comment by mairaw** [comment]
We already have this one for class libraries: https://docs.microsoft.com/en-us/dotnet/articles/csharp/getting-started/library-with-visual-studio-2017
