### ISSUE TITLE
Learn C#: Generics

### ISSUE THREAD

**Issue by tdykstra** [dotnet/docs#489]
Issue tracking new topic at https://github.com/dotnet/core-docs/blob/master/docs/languages/csharp/generics.md

**Comment by tsolarin** [comment]
@tdykstra I'd like to contribute to this, is it up for grabs?

**Comment by tdykstra** [comment]
@BillWagner what is the plan for the C# generics article?

**Comment by tsolarin** [comment]
@BillWagner thoughts?

**Comment by BillWagner** [comment]
@tsolarin @tdykstra Sorry for the late response. I was looking at quite a few different options.

I'd rather not have anyone start on this topic just yet. (Adding the Backlog label for that reason). That's because we are looking at how best to mange the distinction between standard library topics and language specific topics. There will be a topic under the '.NET Standard section that covers the language independent parts, and a smaller topic that is C# specific. We are still discussing exactly where that line is.

@tsolarin I am happy that you want to keep contributing. Can you look at any of the issues from #53 thru #67 ? We really need more sample code for developers to work through, and the accompanying article to help them follow along. I know those are currently assigned to me, but I'd be happy to re-assign one of those to you. Just leave a comment, and @ message me on any of those issues.

**Comment by BillWagner** [comment]
closed via migrating the existing MSDN content.
