### ISSUE TITLE
Inappropriate name of function in an example (F# unittesting) - sumOfSquares

### ISSUE THREAD

**Issue by jurajplavcan** [dotnet/docs#4902]
# Inappropriate name of function in an example - sumOfSquares

https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-fsharp-with-dotnet-test

In the example unit tests are written for a `MyMath.sumOfSquares` function in a TDD fashion. As I read through the document the name of the function appeared rather inaccurate.

## Possible fix

Based on the last test:

```
let ``SquaresOfOdds works`` () =
    let expected = [1; 9; 25; 49; 81]
    let actual = MyMath.sumOfSquares [1; 2; 3; 4; 5; 6; 7; 8; 9; 10]
    Assert.Equal(expected, actual)
```

I would suggest calling the function `MyMath.squaresOfOdds` instead of `MyMath.sumOfSquares`.

**Comment by jurajplavcan** [comment]
I can submit a PR if you consider this worth changing.

**Comment by pkulikov** [comment]
@jurajplavcan your proposed change is one way to fix the article. In that case this sentence from the article:
> The `sumOfSquares` method returns the sum of the squares of all odd integer values that are part of the input sequence. 

should be updated as well.

Another way to make this topic correct is to provide the correct implementation and tests for `sumOfSquares` (or consider renaming to `sumOfSquaresOfOdds`) that would return a scalar value rather than a sequence.

/cc: @cartermp

**Comment by pkulikov** [comment]
@cartermp what is preferred fix:
- update requirement statement and function name to match implementation and tests OR
- fix implementation and tests to match requirements?

**Comment by jurajplavcan** [comment]
@pkulikov @cartermp I chose the first option: update the requirement statement and function name
