### ISSUE TITLE
.NET: Reflection & code generation

### ISSUE THREAD

**Issue by tdykstra** [dotnet/docs#493]
Issue tracking new topic at https://github.com/dotnet/core-docs/blob/master/docs/csharp/reflection.md

**Comment by lindexi** [comment]
I want know :

1.  what is reflection

2. What the reflection can help us to programming

3. How about the safe of reflection

1. How to use reflection

1. What is the disadvantages about reflection.

**Comment by rpetrusha** [comment]
This isn't really a C# issue, since support for reflection comes from the framework and particularly the types in `System.Reflection`. Once the .NET Framework documentation is migrated, there will be a sizable doc set that centers on reflection available on docs.microsoft.com. It would be a mistake to have a standalone C# reflection topic or section that duplicates content.
At the same time, the outline that you've provided, @lindexi, identifies some issues (use cases, advantages, security and best practices) that aren't well covered in the documentation. 
I'm keeping this issue active, but changing its title to **.NET: Reflection & code generation**.

**Comment by lindexi** [comment]
Thx @rpetrusha  for the .NET Framework documentation bring me to https://docs.microsoft.com/en-us/dotnet/articles/csharp/reflection but cant find any thing.

**Comment by rpetrusha** [comment]
Sorry that I wasn't completely clear, @lindexi. The reflection documentation doesn't exist yet on docs.microsoft.com.  It can be found on MSDN at [Reflection in the .NET Framework](https://msdn.microsoft.com/en-us/library/f7ykdhsy(v=vs.110).aspx). That documentation set will be migrated to docs.microsoft.com in the near future, and will form the basis of the new reflection documentation set.

**Comment by lindexi** [comment]
My search engine bring me to docs.microsoft.com but not found the documentation and thank you @rpetrusha  to give the MSDN site.

**Comment by GuardRex** [comment]
Updating loc for this doc: https://github.com/dotnet/docs/blob/master/docs/csharp/reflection.md

**Comment by GuardRex** [comment]
Note: When this doc is created, link "reflection" on line 27 of docs/csharp/modern-events.md to the new topic.

**Comment by mairaw** [comment]
Closing this one since we have the .NET reflection topic on docs. We'll create a new issue to revisit that one and perhaps move it under the .NET Guide.
