### ISSUE TITLE
CoreCLR is written in C#/C++

### ISSUE THREAD

**Issue by ShalokShalom** [dotnet/docs#4975]
Your current [text](https://docs.microsoft.com/en-us/dotnet/core/index) says it is written in C/C++

**Comment by svick** [comment]
I think it depends on what you consider to be "CoreCLR".

If you count everything that's in the coreclr repo, then it indeed includes code written in C#.

But if you only include the actual runtime (and exclude core libraries), then I think it's fair to say that CoreCLR is written in C++.

Considering that this is just an example and not some in-depth description of what CoreCLR is, I think not mentioning C# is fine.

On the other hand, I don't understand why C is mentioned, since CoreCLR contains almost no C code.

**Comment by ShalokShalom** [comment]
Which is what I mean, see the name of the issue. I consider C#/C++ also as correct :slightly_smiling_face:

**Comment by ShalokShalom** [comment]
I guess the person who wrote this, intended to spell C#/C++, so its probably a typo.

**Comment by pkulikov** [comment]
Yes, most probably, it's a typo. The full sentence:
>CoreCLR is platform-specific. It's built in C/C++, so is platform-specific by construction.

with the link to the [CoreCLR repo](https://github.com/dotnet/coreclr) that contains 65% C# and 30% C++.

Though, I don't understand *... is platform-specific by construction.* @ShalokShalom @svick could please explain that.

**Comment by ShalokShalom** [comment]
I guess it means platform-independent?

**Comment by mikedn** [comment]
The runtime libraries (VM, GC, JIT) are written in C/C++ (it's not unusual for people to say C/C++ even if there's little to no actual C code in there) and as such they're obviously platform specific.

The "corelib" assembly is written in C#. And despite being written in C#, it too is platform specific, like System.IO and System.Security.Cryptography.Algorithms mentioned below.

IMO both that piece of documentation and this associated issue are just splitting hairs. The intention of the paragraph is to explain that there are platform specific and platform independent libraries. What language those are written in is pretty much irrelevant (and easily observable by looking at the source code in those repos).

**Comment by ShalokShalom** [comment]
Ah I see. The distinction between C and C# is for the most developers probably more as splitting hairs. Platform specific is clearly correct.

**Comment by pkulikov** [comment]
What adds to confusion, I think, is the discussion of platform-neutral/platform-specific **code** in the same topic with the figure that shows what part of the CoreFX C# code is platform-specific. So, there are platform-specific **code** and platform-specific **library**. While some of GC code might be platform-neutral - I assume, the GC library itself is platform-specific.

**Comment by ShalokShalom** [comment]
A detailed description is probably suitable?

**Comment by mikedn** [comment]
> So, there are platform-specific code and platform-specific library.

Yes, libraries like System.IO are platform specific because they contain platform specific code. I don't see what's confusing about that.

> While some of GC code might be platform-neutral - I assume, the GC library itself is platform-specific.

Most of the code is platform neutral. But since it's written in C/C++ the resulting libraries are platform specific - coreclr.dll and clrjit.dll on Windows and libcoreclr.so and libclrjit.so on Linux. The entire C/C++ source code could be platform neutral and the resulting libraries would still be platform specific, that's how native libraries work.

> A detailed description is probably suitable?

A detailed description of what? How would it help? The only problem in that text is that it equates the CoreCLR repository with the runtime even if that repository also contains the source code for the corelib assembly. Simply replacing "CoreCLR" with "runtime" should be enough to clarify things:

"The runtime is platform-specific. It's built in C/C++, so is platform-specific by construction."

**Comment by mikedn** [comment]
> Simply replacing "CoreCLR" with "runtime" should be enough to clarify things:

Or drop the whole CoreCLR/C/C++ thing and instead talk about System.Private.CoreLib since most section seems to refer only to .NET assemblies. And it's exactly what's useful to point out in the documentation - that some assemblies are platform specific thus you can't just copy them from Windows to Linux.

**Comment by ShalokShalom** [comment]
I think the core issue here is that you refer to the runtime and the repo with the same name.

**Comment by pkulikov** [comment]
>Or drop the whole CoreCLR/C/C++ thing and instead talk about System.Private.CoreLib since most section seems to refer only to .NET assemblies.

I think that is a good update of the current text.

**Comment by mairaw** [comment]
@karelz @richlander pinging again for help

**Comment by karelz** [comment]
@richlander already simplified the page in PR #6769 in August. C++ is not mentioned anymore, closing.
(Let me know if I missed anything, we can reopen in such case)
