### ISSUE TITLE
Missing versions of .NET

### ISSUE THREAD

**Issue by jcurl** [dotnet/docs#5120]
Determining .NET 1.0 framework via the registry doesn't work with these instructions. You have to iterate through the key "SOFTWARE\Microsoft\NET Framework Setup\Full\" looking for entries starting with "v". Then you find the language code and a product key. Once you've got the product key, you can then look in "SOFTWARE\Microsoft\NET Framework Setup\Product\{0}" and then get details if it's installed and the version key.

Secondly, installing .NET 3.0 isn't detected using this code in the registry. I assume that is because it only adds a few Windows XXX Foundation elements. Only from .NET 3.0 SP1 is visible in the registry.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [How to: Determine which .NET Framework versions are installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* Service: **unspecified**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks @jcurl. @rpetrusha can you take a look at this feedback?

**Comment by Zorka44** [comment]
May i suggest this for powershell?

(Get-ChildItem "HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\" -Recurse | ? {$_.Property -eq 'Version'}) | Get-ItemPropertyValue -Name Version | Group | % {$_.Name}

**Comment by jcurl** [comment]
Would it help if I put my repository on GitHub which I try to implement the rules?

**Comment by jvermot** [comment]
There's a tool called asoft .NET version detector: http://asoft.be/prod_netver.html
I like this one because I don't need to do all the logic and keep it updated without having to touch code. They keep it updated with every new build/release.
It can export to xml/text and just show via the UI.

My 2cts

**Comment by FormadorLar** [comment]
Hi! Any way to reinstall all .net framework packages in W2K8_R2 with registry values, etc, etc, etc? 

I'm starting to lose hope.. It started when I tried to reinstall WSUS server.. it wouldn't install as .net framework was >3.5. So, read all about net framework and tried to use a tool (https://blogs.msdn.microsoft.com/astebner/2012/08/04/net-framework-cleanup-tool-now-supports-net-framework-4-5-and-windows-8) to uninstall all framework "4" versions. It worked ok, and i managed to reinstall WSUS... but sadly it wouldn't work ok, so I uninstalled the WSUS role once again, and used the tool once more to cleanup all net framework remains.

Now, for the 2nd time, i tried to install the WSUS role and it wouldn't install , as it stated in the logs, detected only the framework 2.0 running, so it wouldn't install. Since then, i'm trying to reinstall all net framework packages, but unsuccessfully... i deleted parts of the registry, i removed entries manually... well.. now i'm a little lost!

This is a production server and it has a lot of software, and some don't work now, because they need framework 4 to be installed (including sql server 2008 express - had it, but i'm using 2005 version, wich works actually)... i can't install framework 4 whatsoever, by windows update, or any other means... 

So, is there a way to put it all working again? I was avoiding to restore windows to a previous date, so i had next to put all databases backups, files and folders, permissions, etc... to restore them to the actual state.

Help?!?

Thank you in advance!

**Comment by EliteLoser** [comment]
I'm trying to keep this PowerShell function that handles the logic updated: https://github.com/EliteLoser/DotNetVersionLister - and it's … on GitHub, so feel free to let me know when I'm out-of-date. ;) I wove to defend the .NET version listing to my grave! (hm)
