### ISSUE TITLE
string.Format API: not accurate description of formatting sequence

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#5151]
The [How arguments are formatted](https://docs.microsoft.com/en-us/dotnet/api/system.string.format?view=netcore-2.0#how-arguments-are-formatted) section of the `string.Format` API topic is not accurate in the second step:
>If you call the `Format(IFormatProvider, String, Object[])` overload and the `provider` parameter implements the `ICustomFormatter` interface...

`provider` doesn't have to implement mentioned interface (though, it's common practice that it does) and `provider.GetFormat` custom formatter is used if it's not `null`

I want to fix it. 
However, which way is preferred:
- just fix in place with minimum changes.
- remove that section at all and link to [the section that describes that same processing order](https://docs.microsoft.com/en-us/dotnet/standard/base-types/composite-formatting#processing-order) in the conceptual docs in more details and correctly.

In general, the `string.Format` article contains almost the full [Composite formatting](https://docs.microsoft.com/en-us/dotnet/standard/base-types/composite-formatting) topic content. Is it intentional or the result of two different doc writing threads?

**Comment by rpetrusha** [comment]
Thanks, @pkulikov, both for opening this issue and for your careful review of the formatting docs. I really appreciate it.
The duplication isn't by design so much as it's the result of two different doc writing threads. Composite formatting was revised much earlier (most of the revision occurred more than a decade ago), and String.Format was revised with the goal of creating an encyclopedic reference on String.Format in a single place. 
We need to review the extent of duplication in the documentation and decide how to handle it, but until that happens, it strikes me that the best fix at this point is to fix the documentation in place.

**Comment by pkulikov** [comment]
@rpetrusha that's clear. Then I'll fix the issue in place with minor clean-ups whenever possible.
