### ISSUE TITLE
Index Initializers section is inaccurate

### ISSUE THREAD

**Issue by drewjcooper** [dotnet/docs#5169]
In the Index initializers section, the initial text about collection initializers seems to imply that there was no way to initialize a Dictionary<,> prior to the new C# 6.0 syntax.  This is incorrect.  The following code is semantically equivalent to the index initializer example in the document.

```csharp
private Dictionary<int, string> webErrors = new Dictionary<int, string>
{
    { 404, "Page not Found" },
    { 302, "Page moved, but left a forwarding address." },
    { 500, "The web server can't come out to play today." }
};
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36fef60d-04e9-dc86-2e3f-134c10ea37bb
* Version Independent ID: 09b5aa7a-1b43-8bf9-9786-f10f457488dd
* Content: [What's New in C# 6 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-6)
* Content Source: [docs/csharp/whats-new/csharp-6.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-6.md)
* Service: **unspecified**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@BillWagner if my understanding is correct, this issue was fixed by #5577

**Comment by DevonAleshire** [comment]
Drew, you are awesome. Great explanation as well. Let me find some time to clarify it better since I started working down the issue. I will focus on making sure there is a distinction made between the fact that the previous method is a collection initializer using the IEnumerable implementation and the new index initializer utilizes the indexer support as an object initializer for index assignment during initialization.

**Comment by DevonAleshire** [comment]
@pkulikov and @BillWagner I will try to simplify the details a little for incorporation into the documentation as noted above by @drewjcooper . I think it is an important concept to hit the wave tops of without getting overly complex. Let me know if issue #5169 is something you want to keep open a little longer, otherwise I will hold off. 

Also off topic, @BillWagner I did not even realize who you were until I was looking through my Safari books queue yesterday and saw the effective and more effective books ha ha. I was like, I have seen that name recently. Pleasure to assist.

**Comment by pkulikov** [comment]
@DevonAleshire if you want to contribute further to fixing this issue, ask the maintainers to assign the issue to you. That way, other contributors know that somebody is working on the issue and don't grab it (this one has the *up-for-grabs* tag, which means it shouts to the community contributors for attention). 

Furthermore, the issue doesn't seem to be urgent and is of the medium priority (notice the *P2* tag). So, take your time to think about it and come up with the good wording; really, no hurry. However, don't feed your perfectionist self and make a PR as soon as you start rewriting text in circles; the PR reviews and feedback really help and sometimes are eye-openers. 

If during the process, something happens that make you stop working on this issue (long hours in office for the six-months-ahead deadline, a new hobby, a sudden trip to Tibet for a year, or just lost fun), please notify maintainers to un-assign the issue from you. That's fine.

**Comment by drewjcooper** [comment]
@pkulikov yes, I think the section should focus on object initializers, because that's where the indexer support is in the language.  It really has nothing to do with collection initializers, except that either can be used to initialize a dictionary, or other collection type with a sparse index.

**Comment by BillWagner** [comment]
Updating this sprint because I'm updating the same article for P1 work.
