### ISSUE TITLE
IEqualityComparer<T>.Default example needs improvement

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#5192]
The IEqualityComparer<T>.Equals implementation needs to handle nulls.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd5c9615-f57c-9382-3a98-034e1d60b6f3
* Version Independent ID: 8dc49322-4333-5f78-2843-f8a9df52ad5f
* Content: [EqualityComparer<T>.Default Property (System.Collections.Generic)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.equalitycomparer-1.default?view=netframework-4.7.2#System_Collections_Generic_EqualityComparer_1_Default)
* Content Source: [xml/System.Collections.Generic/EqualityComparer`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections.Generic/EqualityComparer`1.xml)
* Service: **unspecified**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by svick** [comment]
I started fixing and modernizing this example, but then I realized the example is pointless: instead of `BoxEqDimensions`, the example could directly use `EqualityComparer<Box>.Default` or even omit the `Dictionary` constructor parameter altogether and the result would be the same.

Do you see a simple way to fix that issue? If not, what would be a good example to use for `EqualityComparer<T>.Default`?

**Comment by BillWagner** [comment]
@svick The scenarios I've seen are to provide an simple overload for `Find` methods in collections.  Something like:

```csharp
public class SomeCollection<T>
{
   public T Find(T sought, IEqualityComparer<T> equalityTest = EqualityComparer<T>.Default)
   {
       // ...
   }
{
```
