### ISSUE TITLE
New Samples?

### ISSUE THREAD

**Issue by mredmond64** [dotnet/docs#5221]
Most of these samples (e.g. Strings, Buffers) point to pages that are no longer being maintained, and I assume they do not apply to .NET Core. Can we get some update samples that work across platforms?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6de86b6e-fcc7-3d20-4a71-6df93c261769
* Version Independent ID: 9855800a-1100-f0cf-d4a8-e9b52b1f0409
* Content: [Marshaling Strings](https://docs.microsoft.com/en-us/dotnet/framework/interop/marshaling-strings)
* Content Source: [docs/framework/interop/marshaling-strings.md](https://github.com/dotnet/docs/blob/master/docs/framework/interop/marshaling-strings.md)
* Service: **unspecified**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks @mredmond64 for your feedback. I think this issue is related to two issues we have already opened in our repo:
- #4649 
- #2028

I'll be closing this one but feel free to comment on the other issues above. Given the amount of content we have, we do prioritize this sort of revision based on a number of things such as page views, customer requests, etc.
