### ISSUE TITLE
Copy method not built into File Stream

### ISSUE THREAD

**Issue by blakecodes** [dotnet/docs#5285]
Good solution, but why would a copy method not be built into the File Stream library?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d050f686-38eb-bb76-5747-9e138f4da679
* Version Independent ID: 93b69d5a-5df1-c0e1-930d-2f5ee1c1fe6e
* Content: [How to: Copy Directories](https://docs.microsoft.com/en-us/dotnet/standard/io/how-to-copy-directories)
* Content Source: [docs/standard/io/how-to-copy-directories.md](https://github.com/dotnet/docs/blob/master/docs/standard/io/how-to-copy-directories.md)
* Service: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment]
A copy method is built into Stream and FileStream, @blakecodes. There are two overloads of the [Stream.CopyTo](https://docs.microsoft.com/dotnet/api/system.io.stream.copyto) method and two overloads of the [Stream.CopyToAsync](https://docs.microsoft.com/dotnet/api/system.io.stream.copytoasync) method. 
However, if you're interested in file copy operations like the one illustrated in the example, using streams is expensive when compared with operations like File.Copy or File Info.CopyTo.
Since this is a product rather than a documentation issue, but .NET already includes stream copy functionality, I'm going to close this issue.

 However,
