### ISSUE TITLE
Example code for C# checked/unchecked article

### ISSUE THREAD

**Issue by LambertWM** [dotnet/docs#5356]
As usual the example code is a bit too bloated and complex for my taste.
to make it shorter and clearer: why not have one "add" method and then call it twice, once from a "checked" block and once from an "unchecked" block? 
Btw, why not use int.MaxValue (just to illustrate that this exists)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbbcec4d-d8ff-d906-57ec-378689eb99a5
* Version Independent ID: 88e4ead1-3745-2be6-9cfb-0f02eeacf9c1
* Content: [checked (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/checked)
* Content Source: [docs/csharp/language-reference/keywords/checked.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/checked.md)
* Service: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for your feedback @LambertWM. We're adding this to our backlog since this is not wrong but a suggestion to improve it.

**Comment by yawnston** [comment]
> why not have one "add" method and then call it twice, once from a "checked" block and once from an "unchecked" block

Because that doesn't work. It's kind of a gotcha - if you call a method from inside a checked block, and an arithmetic overflow happens in that method, unless there's a checked block inside it, there is no exception. The following code does not throw an exception and returns a negative integer.

```
public class Program
{
	public static int DoSomething()
	{
		int a = 10;
		int b = int.MaxValue;
		
		return a + b;
	}
	
	public static void Main()
	{
		Console.WriteLine(checked(DoSomething()));
	}
}
```

It makes sense, because the method could be called from both checked and unchecked contexts. Therefore there's no universal way how to decide if to throw an exception in that case. This means the checked block has to be directly in the place where you're doing the math. The following code does throw an exception:

```
public class Program
{
	public static int DoSomething()
	{
		int a = 10;
		int b = int.MaxValue;
		
		return checked(a + b);
	}
	
	public static void Main()
	{
		Console.WriteLine(DoSomething());
	}
}
```

That being said, it would definitely be nice to have the docs reflect this.
