### ISSUE TITLE
Why do I need to run the Windows Identity Federation Utility to get this to work?

### ISSUE THREAD

**Issue by TRegan3** [dotnet/docs#5433]
I have a functioning AD FS running.  When I point to it and run this code I get an error message telling me I am not authenticated and lack permission to view the page.  However, if I run the Windows Identity Federation Utility against the web site (it inserts a lot of Microsoft.Identity tags into the web.config and creates a FederationMetadata.xml file) the site works.  Should I need to run the Identity Federation Utility?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0d879ff-bf90-a7d2-76bb-7b854739d6d4
* Version Independent ID: 0b8e1f3a-ea6e-c78f-9e92-b1afa71fef4b
* Content: [How To: Build Claims-Aware ASP.NET MVC Web Application Using WIF](https://docs.microsoft.com/en-us/dotnet/framework/security/how-to-build-claims-aware-aspnet-mvc-web-app-using-wif)
* Content Source: [docs/framework/security/how-to-build-claims-aware-aspnet-mvc-web-app-using-wif.md](https://github.com/dotnet/docs/blob/master/docs/framework/security/how-to-build-claims-aware-aspnet-mvc-web-app-using-wif.md)
* Service: **dotnet-framework**
* GitHub Login: @BrucePerlerMS
* Microsoft Alias: **dotnetcontent**

**Comment by VincentGau** [comment]
How to configure a custom STS since Identity and Access Control is deprecated. Are there any tutorial about build a custom STS.

**Comment by AdamantiumWolverine** [comment]
I ran into the same issue when I used the FedUtil.exe that comes with the Windows Identity Foundation v4.0 SDK.  It seems that the FedUtil.exe utility that comes with the SDK is for .NET3.5 which uses the Microsoft.IdentityModel rather than the newer System.IdentityModel for .NET4.0.  


Fortunately, the Microsoft.IdentityModel will still work with your .Net 4.0 application.

Basically, if you choose to use FedUtil, which definitely makes setting up your application for ADFS Claims easier, you will be using the Microsoft.IdentityModel.  

This article has instructions for setting up your site to use the System.IdentiyModel.  However, when I followed the instructions from this article, authentication seemed to not be working.  So I just chose to use the Microsoft.IdentityModel for my application.


  I noticed that when we use FedUtil, the following modules are added to the web.config:
  <validation validateIntegratedModeConfiguration="false" />
    <modules>
      <remove name="ApplicationInsightsWebTracking" />
      <add name="ApplicationInsightsWebTracking" type="Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule, Microsoft.AI.Web" preCondition="managedHandler" />
      <add name="WSFederationAuthenticationModule" type="Microsoft.IdentityModel.Web.WSFederationAuthenticationModule, Microsoft.IdentityModel, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" preCondition="managedHandler" />
      <add name="SessionAuthenticationModule" type="Microsoft.IdentityModel.Web.SessionAuthenticationModule, Microsoft.IdentityModel, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" preCondition="managedHandler" />
    </modules>
  </system.webServer>

However, this article doesn't specify any authentication module entries to add to the web.config.  I believe that may have something to do with it.

I found the below article which provides another example on using the System.IdentityModel.  
https://www.codeproject.com/Articles/639458/Claims-Based-Authentication-and-Authorization

In this article, the author includes the Session Authentication Module (SAM) that comes with the System.IdentityModel namespace.
<modules>
      <add name="SessionAuthenticationModule" 

        type="System.IdentityModel.Services.SessionAuthenticationModule, 
              System.IdentityModel.Services, Version=4.0.0.0, Culture=neutral, 
              PublicKeyToken=b77a5c561934e089" />      
</modules> 

I haven't bothered to switch my app back to trying the System.IdentityModel again, but I'm thinking that adding the SAM module may be necessary for the authentication piece to work correctly.

**Comment by AdamantiumWolverine** [comment]
REPOSTING WITH FIXES TO TEXT WHICH GOT ESCAPED:

I ran into the same issue when I used the FedUtil.exe that comes with the Windows Identity Foundation v4.0 SDK. It seems that the FedUtil.exe utility that comes with the SDK is for .NET3.5 which uses the Microsoft.IdentityModel rather than the newer System.IdentityModel for .NET4.0.
Fortunately, the Microsoft.IdentityModel will still work with your .Net 4.0 application.
Basically, if you choose to use FedUtil, which definitely makes setting up your application for ADFS Claims easier, you will be using the Microsoft.IdentityModel.
This article has instructions for setting up your site to use the System.IdentiyModel. However, when I followed the instructions from this article, authentication seemed to not be working. So I just chose to use the Microsoft.IdentityModel for my application.
I noticed that when we use FedUtil, the SessionAuthenticationModule and WsFederationAuthenticationModule modules are added to the web.config:
          <modules>   
                 <add name="WSFederationAuthenticationModule" type="Microsoft.IdentityModel.Web.WSFederationAuthenticationModule, Microsoft.IdentityModel, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" preCondition="managedHandler" />
               <add name="SessionAuthenticationModule" type="Microsoft.IdentityModel.Web.SessionAuthenticationModule, Microsoft.IdentityModel, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"  preCondition="managedHandler" />
          </modules>


However, this article doesn't specify any authentication module entries to add to the web.config. I believe that may have something to do with the authentication portion not working.

I found the below article which provides another example on using the System.IdentityModel.
https://www.codeproject.com/Articles/639458/Claims-Based-Authentication-and-Authorization

In this article, the author includes the Session Authentication Module (SAM) that comes with the System.IdentityModel namespace.

     <add name="SessionAuthenticationModule"
    type="System.IdentityModel.Services.SessionAuthenticationModule, 
          System.IdentityModel.Services, Version=4.0.0.0, Culture=neutral, 
          PublicKeyToken=b77a5c561934e089" />      

I haven't bothered to switch my app back to trying the System.IdentityModel again, but I'm thinking that adding the authentication modules may be necessary for the authentication piece to work correctly.

**Comment by AdamantiumWolverine** [comment]
Just looked at the WIF Code Sample Index and took a look at the web.config.  The module entries for the SessionAuthenticationModule and WsFedrationAuthenticationModule for the System.IdentityModel are in there.


    <system.webServer> 
     <modules> 
       <add name="WSFederationAuthenticationModule" type="System.IdentityModel.Services.WSFederationAuthenticationModule, System.IdentityModel.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" preCondition="managedHandler" /> 
       <add name="SessionAuthenticationModule" type="System.IdentityModel.Services.SessionAuthenticationModule, System.IdentityModel.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" preCondition="managedHandler" /> 
      </modules> 
    </system.webServer>

**Comment by mairaw** [comment]
That content is being archived with PR #14801. It's not maintained any longer. So I'm closing this issue.
