### ISSUE TITLE
Add versioning to Programming Guides

### ISSUE THREAD

**Issue by Powerhelmsman** [dotnet/docs#5451]
I programming guides, if best practices or recommended guidance changes between library versions, provide a way to select the version of .NET (or Core, etc) that you're using. This would be better than always providing docs on the latest versions.
For example, in the C# Programming Guide, Pattern Matching may be the best way of achieving something in the latest code, but it would not be possible with older tooling/frameworks.
Some way to navigate back in time on the docs for older guidance would be really useful.
This issue is transferred from https://github.com/MicrosoftDocs/feedback/issues/74

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc2fe8f7-b023-5aa7-52c2-b9c1c5c13ded
* Version Independent ID: 18c373d4-02f9-4cc6-656d-9cf4d11f6498
* Content: [C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/)
* Content Source: [docs/csharp/programming-guide/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/index.md)
* Service: **unspecified**
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
This won't get fixed in the manner described above. However, it may be that we add a section on how practices have changed with different versions. This would serve a couple purposes:

1. It would help highlight where new language features  can be used to simplify existing (common) practices.
1. It would catalog older practices for customers on older version, or looking at legacy codebases to upgrade.
