### ISSUE TITLE
Document is outdated

### ISSUE THREAD

**Issue by MarcSigrist** [dotnet/docs#5509]
If you create public documentation like this, plese make sure it is up-to-date at all times. Neither .NET Core 1.1, nor .NET Framework 4.7.x versions are mentioned in https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb8b774-c6f0-8235-6964-15219baf2ea7
* Version Independent ID: 6819a4a7-7527-d8c7-e132-767f7344e00e
* Content: [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)
* Content Source: [docs/standard/net-standard.md](https://github.com/dotnet/docs/blob/master/docs/standard/net-standard.md)
* Service: **unspecified**
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by svick** [comment]
> Neither .NET Core 1.1, nor .NET Framework 4.7.x versions are mentioned in [the table].

That doesn't mean the table is not up to date. That's because .Net Core 1.1 doesn't add support for any .Net Standard compared with .Net Core 1.0. And .Net Framework 4.7.x doesn't add support for any .Net Standard compared with .Net Framework 4.6.1.

Put differently, there are no cells to put .Net Core 1.1 or .Net Framework 4.7.x in, since each cell lists the *lowest* version of the given framework that supports the given version of .Net Standard.

**Comment by MarcSigrist** [comment]
Thanks, that makes sense. And indeed it's correctly described in the legend: "The version number in each cell indicates the minimum version of the implementation you'll need in order to target that .NET Standard version."

**Comment by mairaw** [comment]
I'm going to close this since the information on that table is correct. If you have any suggestions on how to make that more discoverable, please let me know.
