### ISSUE TITLE
Layout errors

### ISSUE THREAD

**Issue by cremor** [dotnet/docs#5582]
The layout in the "Web Application" section is broken. Seems like special layout syntax is displayed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a0e7552-60ad-9488-87cb-0476def066f3
* Version Independent ID: 2453c298-590d-6c9a-1952-7b1359d19b00
* Content: [Runtime Changes for Migration from .NET Framework 4.7.1 to 4.7.2](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/runtime/4.7.1-4.7.2)
* Content Source: [docs/framework/migration-guide/runtime/4.7.1-4.7.2.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/runtime/4.7.1-4.7.2.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @chlowell
* Microsoft Alias: **ronpet**

**Comment by svick** [comment]
It seems this issue is caused by space in the include path (`~/includes/migration-guide/runtime/web application/dataannotationsdatatypeattributedisableregex-app-setting-on-by-default-net.md`). Is there a reason why [web application](https://github.com/dotnet/docs/tree/master/includes/migration-guide/runtime/web%20application) and [web](https://github.com/dotnet/docs/tree/master/includes/migration-guide/runtime/web) are two different directories?
