### ISSUE TITLE
C# tutorials - versioning

### ISSUE THREAD

**Issue by stevehoag** [dotnet/docs#56]
Should teach versioning in C# through the use of the override and new keywords. 

Tutorials should include one or more code examples, each example should also show expected output and should include an explanation of the code where it isn't obvious. Examples shouldn't be dependent on a specific IDE or target platform.

**Comment by tsolarin** [comment]
@BillWagner still up for grabs?

**Comment by tsolarin** [comment]
@BillWagner up for grabs?

**Comment by BillWagner** [comment]
@tsolarin Sure. Do you want to work on this one?

If so, let's learn from our experience with the XML doc article. Let's start with an outline, either as a comment on this issue, or as a PR with a Work in Progress (WIP) comment. Then, once we agree that the outline is good, then move forward. I want to avoid having you do as much re-work as the last time.

**Comment by tsolarin** [comment]
Sure @BillWagner, I'll get to creating a barebones first draft and post the link here once it's ready

**Comment by tsolarin** [comment]
@BillWagner Sorry for the delay been a bit busy. Here's my outline https://github.com/tsolarin/core-docs/blob/versioning/docs/csharp/versioning.md. I couldn't find a pre-existing versioning page that contained documentation metadata.

Looking forward to your feedback

**Comment by BillWagner** [comment]
@tsolarin I will look at this today. (Got totally slammed yesterday).

**Comment by BillWagner** [comment]
/cc @stevehoag (He wrote the original issue)

I'd like to see you approach this in terms of what happens for any of these kinds of methods when base classes change. For example:

1. What happens when a base class adds new overrides of a virtual method?
2. What happens when a base class adds new methods that conflict with a derived class's methods?
3. What happens when a base class changes the default value on any optional arguments?

Overall, readers should learn what changes they can make in version 2 (and later) that won't negatively impact the developers that created derived classes? 

And, if a base class does make those kinds of breaking changes, how should the derived class author react?

**Comment by tsolarin** [comment]
@BillWagner apologies for the delay, been busy with work on travel. I should have something ready for review by the end of this week
