### ISSUE TITLE
.Net Framework versions table does not look good

### ISSUE THREAD

**Issue by svick** [dotnet/docs#5646]
If I view the .Net Framework versions table in my not-fullscreen browser window, it doesn't look very good (shown horizontally scrolled for effect):

![](https://user-images.githubusercontent.com/287848/40615803-a0144cd4-6288-11e8-908e-4c200d8c3ada.png)

I think the biggest issue is trying to cram the Features column there. Assuming that information can't be significantly shortened, maybe it could be moved outside the table?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fe5242-e3b2-6cfe-5308-63fc96272657
* Version Independent ID: 1abaaeb7-d7ed-5522-c16f-409f22a074cc
* Content: [.NET Framework Versions and Dependencies](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies)
* Content Source: [docs/framework/migration-guide/versions-and-dependencies.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/versions-and-dependencies.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Maybe we need to use a layout different than a table for that information @rpetrusha.

**Comment by rpetrusha** [comment]
We need to change something, @mairaw, although a table seems best for this information. The problem here, as you point out, @svick, is the Features column. We could move it out of the table into a separate section. But that doesn't seem to me like a very attractive alternative; I think that it ends up making this a scaled-down version of the what's new topic along with some version information. I wonder whether the Features column is useful at all; I can't imagine anyone making serious use of it, as  opposed to the What's New topic. I'm wondering if we can just delete the column and add a link to what's new after each .NET Framework version number. Thoughts?

**Comment by mairaw** [comment]
@rpetrusha I agree that linking to What's new might be best here since the topic is not about the new features.
