### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by TharosTheDragon** [dotnet/docs#5683]
Last sentence in introduction of Remarks section: "Then you can add child elements that define the resources, each with an value."

You may think to fix this by changing "an" to "a," but I suspect there's a missing word and I don't know what it's supposed to be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 199e0c6e-18c6-b2e4-3335-dff64f564cc0
* Version Independent ID: af481a26-f252-b0e6-926e-fdf6f831cff9
* Content: [ResourceDictionary Class (System.Windows)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.resourcedictionary?view=netframework-4.7.2)
* Content Source: [xml/System.Windows/ResourceDictionary.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows/ResourceDictionary.xml)
* Service: **unspecified**
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for your feedback, @TharosTheDragon. Your surmise that the "an" was correct because text had dropped out of the documentation turns out to be correct. The original text was "an \[x:key](https://docs.microsoft.com/en-us/dotnet/framework/xaml-services/x-key-directive)". We've opened a PR to address this issue.
