### ISSUE TITLE
The ref keyword topic is not complete

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#5686]
Related to #5682, [ref keyword](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/ref) topic doesn't mention [`ref struct`](https://docs.microsoft.com/en-us/dotnet/csharp/reference-semantics-with-value-types#ref-struct-type) and related `ref readonly struct` usage of the `ref` keyword.

**Comment by BillWagner** [comment]
In addition to the `ref` topic, the `struct` topic should include information on `ref struct` and `ref readonly struct`.

**Comment by pkulikov** [comment]
@BillWagner what about the following structure. The main article on `struct` should describe:
- "canonical" structs
- `readonly struct`
- `ref struct`
- `ref readonly struct`

Given that, the `ref` and `readonly` topics can then only mention usage and link the main article on `struct` for more information.

The question is: what is the main article on structs? The `struct` keyword topic references the one in the programming guide:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/structs

Should that page accumulate all information about structs and all other pages link to it?

That rearrangement, if it makes sense, might take several PRs.

**Comment by BillWagner** [comment]
That makes sense @pkulikov I started updating the `ref` page, thinking I could fix this issue in #6086 That would make the PR too large to reasonably review. This issue will be fixed in a separate PR.

**Comment by BillWagner** [comment]
@pkulikov 's list is the right outline.

See #4441 for an important question.  To answer that as well, the coverage of `readonly struct` s must include when the compiler disallows an operation, and when it enables the operation on a defensive copy.  For example, what happens when a readonly struct contains a (not readonly) struct? In particular, can methods of the contained struct be called? Are those methods called on defensive copies?
 What happens when the not readonly struct is passed by ref (not `ref readonly`)?
