### ISSUE TITLE
Please Expland Linux part of Documentation

### ISSUE THREAD

**Issue by AceHack** [dotnet/docs#5748]
You say

"On Linux, you need to edit the shell environment file to configure the PATH."

Please expand on that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0c5b03c-2854-8462-57dc-b0239388096e
* Version Independent ID: 13b38200-ed54-7bfe-f7cf-099cf1b010f4
* Content: [.NET Core Global Tools](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools)
* Content Source: [docs/core/tools/global-tools.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/global-tools.md)
* Service: **unspecified**
* Product: **dotnet-core**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **mairaw**

**Comment by KathleenDollard** [comment]
@wli3 Can you fix this/help me fix this

Do we have enough environment variables that we should just have an entry on how to do it in different shells?

**Comment by wli3** [comment]
before giving detail instruction.

@AceHack 

1. expand PATH is such a common practice in unix. Do we have existing document that we can reference? Is there any other Microsoft product has done that before? 

2. since this is a such a fundamental usage of unix shell. Should we link to official document of respective shell like bash, zsh, csh?

3. as I mentioned in 2. There are a lot of shell available like bash, zsh, csh, ksh, fish. And I don't want SDK's document to become a general Unix documentation. Should we scoped to the most common shell, bash shell?

**Comment by AceHack** [comment]
@wli3 So what I was mostly talking about was WHAT to add to the path.  This says you need to configure the path but not what to add to the path.  The message you get when actually installing a global tool is much more informative as it mentions the actual location that needs to be added to path.

**Comment by wli3** [comment]
I see:

Append $HOME/.dotnet/tools to PATH.

However, I went back to the doc. I think what to expand is “in which case SDK will not automatically add PATH and make the command available by just type the command”, if so. It should be (the sentence may need some proofing)

If the user installs dotnet SDK via tar.gz in Linux, or the user’s shell is not bash. The user need to append _$HOME/.dotnet/tools_ (or expended path to _tools_ directory) to environment variable _PATH_ by respective shell’s method.

**Comment by nojaf** [comment]
How does it work on Linux when you install a global tool into a folder using the `--tool-path` option.
You get an exe but how to run this?
