### ISSUE TITLE
Unclear where to report issues related to the product

### ISSUE THREAD

**Issue by CoolDadTx** [dotnet/docs#5749]
It is unclear who/where feedback for the package generation functionality in the new project system goes. Who owns this feature such that I can report issues/feedback? The feedback I have right now related to not only "missing" properties to control generation but also how the package gets generated itself. It is unclear whether this is a NuGet, MSBuild or Project System area.

The feedback link is for the docs but it doesn't clarify where feature feedback should go. This would be nice to include in the docs. Right now there are too many GitHub repos to figure it out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [Additions to the csproj format for .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj)
* Content Source: [docs/core/tools/csproj.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md)
* Service: **unspecified**
* Product: **dotnet-core**
* GitHub Login: @blackdwarf
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
If you see in the bottom of each topic, there are two buttons: one for content, one for product.

![image](https://user-images.githubusercontent.com/12971179/40897280-12eff614-676f-11e8-8901-df963c80d9c5.png)

Because of the reasons you mentioned (too many repos, unclear where to file the bug), we settled on https://developercommunity.visualstudio.com/spaces/61/index.html for product feedback. The product team will triage those and move them to the appropriate owners.

**Comment by mairaw** [comment]
Also, if you have a guess of what repo should be, you can try to filing on that repo and the team will move if it's the wrong one.
