### ISSUE TITLE
Navigation in Docs problem

### ISSUE THREAD

**Issue by ahmad2smile** [dotnet/docs#5772]
I selected C# guides and then searched for 'protected' keyword and I get navigated to visual basic guide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2b0a262-7753-7570-0bd0-78bdc6dca56a
* Version Independent ID: 68a121a7-69d3-25d1-50c0-26f40948eaf0
* Content: [Protected (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/modifiers/protected#feedback)
* Content Source: [docs/visual-basic/language-reference/modifiers/protected.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/modifiers/protected.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
That's by design @ahmad2smile.  The filter by title search only shows what's on the first level TOC, which is different for C# and Vb content.

![image](https://user-images.githubusercontent.com/12971179/40897142-11bb37c8-676e-11e8-8f43-200dbb13e37a.png)

If you use the site search, you should be able to find the C# protected topic:
![image](https://user-images.githubusercontent.com/12971179/40897150-22d0d6bc-676e-11e8-8dfc-0204723e7826.png)

https://docs.microsoft.com/en-us/search/index?search=protected&scope=.NET

Let us know if that solves your issue.

**Comment by ahmad2smile** [comment]
I get here by selecting C# Guides.

`https://docs.microsoft.com/en-us/dotnet/csharp/`

Then search and click and It takes me here.

![screenshot 2](https://user-images.githubusercontent.com/6108922/40904842-815cf300-67f5-11e8-854f-e7b5b30c8bb3.png)


Redirected URL:

`https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/modifiers/protected`

**Comment by pkulikov** [comment]
That is because C# language reference topics are not in the main TOC, while Visual Basic and F# ones are. However, the C# language reference TOC looks too big to be included in the main TOC. To be consistent, should other two language references be removed from the main TOC, @mairaw?
