### ISSUE TITLE
Inline functions and generic types

### ISSUE THREAD

**Issue by sebhofer** [dotnet/docs#5804]
Is the last line in the feature table correct? It says: "An inline function cannot be parameterized with a standard generic type parameter." However, `let inline g a b = a, b` will give me `g : a:'a -> b:'b -> 'a * 'b`. For me this contradicts the statement.  Or do I interpret this statement incorrectly?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d56dc27-d3f4-2ac1-0cd1-61d06fb8e314
* Version Independent ID: 1abc963d-0fa8-a313-0637-e99dd67064ed
* Content: [Statically Resolved Type Parameters (F#)](https://docs.microsoft.com/en-gb/dotnet/fsharp/language-reference/generics/statically-resolved-type-parameters)
* Content Source: [docs/fsharp/language-reference/generics/statically-resolved-type-parameters.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/generics/statically-resolved-type-parameters.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by JRAlexander** [comment]
Bumping - 
@cartermp can you take a look at this feedback? Thanks!

**Comment by cartermp** [comment]
I think this is a poorly-described behavior in the document. I think what it's saying is by inlining something, you are perhaps indicating to the F# compiler that you are constraining other inputs to this function to conform to rules that are determined either by SRTP in the signature or the use of those inputs in the function body. For example:

```fsharp
let inline add x y = x + y
```

This constrains `x` and `y` to only be types that can be added together, not any arbitrary `x` and `y`. Since Generics would be any arbitrary `x` and `y`, this is fundamentally incompatible with normal generics because the usage of `x` and `y` necessarily constrains their types in a way that is less open than what a fully generic parameter would support.

If I were to remove `inline`, then the F# compiler would see that `x` and `y` are not fully generic and specialize to `int`, or specialize to `float` if you were to use it with floating-point values. This is, again, because `x` and `y` are not actually generic based on their usage. The `inline` keyword is lets the compiler know this "up front" and use static constraints to define the input types.

This is all perfectly valid in F# land, and usually fairly well-understood.

However, you can easily write code like this:

```fsharp
let inline test<'a> (a: 'a) = a

test<string> ""
test<int> 12
```

This code clearly violates what the table is saying, because you can parameterize the inline function with a generic type and use it. However, recall what I just wrote previously: if the types are used in any way that is not actually generic, then the F# compiler cannot treat them as generic! This can lead to one of the following:

* The routine is specialized, as I mentioned before
* The routine cannot find something to specialize to and the compiler will give an error

This is when you must typically apply a Statically Resolved Type Parameter to let the compiler know _how_ to constrain the input types, and it must be `inline` so that it can be used appropriately at the call site.

I believe that this is what the document is attempting to convey, but it does not appear to be doing so effectively. I expect I'll need to rewrite this a bit 😿

**Comment by cartermp** [comment]
After thinking this through a bit more and talking it over with a few others, the only reasonable thing I can do is rewrite the article. I'll probably do that sometime in the next week.

**Comment by JRAlexander** [comment]
Mind if I add it to the 139 milestone?

**Comment by cartermp** [comment]
Sounds good!

**Comment by mairaw** [comment]
@cartermp when do you plan on addressing this?

**Comment by cartermp** [comment]
Yep. Been slammed with other work, though.

**Comment by mairaw** [comment]
No worries @cartermp. Should I move this to the backlog then?

**Comment by cartermp** [comment]
Yes, please!

**Comment by bender2k14** [comment]
Did this get completed in Sprint 139?

**Comment by TysonMN** [comment]
I don't know what "backlog" means to @dotnet/docs.  My understanding of the term is that anything that is a problem should be on the backlog.  @cartermp confirmed above that this issue is a problem.  At the same time, it is possible to never address this issue by keeping it at the bottom of the backlog (which is easy when the workflow adds new items to the top of the backlog).
