### ISSUE TITLE
ProcessStartInfo.ArgumentList needs documentation

### ISSUE THREAD

**Issue by PerMildner** [dotnet/docs#5832]
There is no documentation for ProcessStartInfo.ArgumentList

Presumably it's a replacement for the error-prone ProcessStartInfo.Arguments, but it how should ArgumentList be used?

I found https://github.com/dotnet/corefx/issues/23592 but that too does not say what the final design for ArgumentList is. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cdda533-d47f-ee8b-5045-517c34b74ab5
* Version Independent ID: 5f19e4c7-6c66-1d09-93b1-6e8e7abfc192
* Content: [ProcessStartInfo.ArgumentList Property (System.Diagnostics)](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.argumentlist?view=netcore-2.1&viewFallbackFrom=netframework-4.7.2)
* Content Source: [xml/System.Diagnostics/ProcessStartInfo.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Diagnostics/ProcessStartInfo.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @PerMildner. We have lots of gaps in the .NET Core API reference that we need to cover. 

In the meantime, does the source code help with the final design for this? 
https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/ProcessStartInfo.cs#L66

@joperezr, can you help with the question about the API usage?

**Comment by airbreather** [comment]
FWIW, this is just as convenient on the Windows side, since it also handles arguments with embedded whitespace and quotes.

The .NET Fat application that I maintain at work has a helper to try to replicate what the "`PasteArguments`" files from [here](https://github.com/dotnet/corefx/tree/176fb6aed060d5ef2284844652f24b8aa965d827/src/Common/src/System) do, and I definitely see some things here that our version doesn't do, so I add my strong support for documenting this, as well as updating the documentation for `ProcessStartInfo.Arguments` to indicate the interaction that it has with this property.

**Comment by mairaw** [comment]
Moving this top the backlog for now.

**Comment by tobia** [comment]
According to the [tests committed along with the change](https://github.com/dotnet/corefx/pull/27191/files#diff-f70f12d034b1030726b9e9597dde4e64R23), it's supposed to be used like this:

    ProcessStartInfo psi = new ProcessStartInfo("filename");
    psi.ArgumentList.Add("arg1");
    psi.ArgumentList.Add("arg2");

This is quite a convoluted and hidden way to set the argument list for a process execution. But I guess that kind of criticism doesn't belong in this issue.
