### ISSUE TITLE
Which Trainer best fits my need?

### ISSUE THREAD

**Issue by thiagoboccio** [dotnet/docs#5910]
I'm developing a simple project to predict names, based on name first letter and name gender.
Which trainer would you use and why?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: e855e630-1a30-d138-4ac6-bfeefebf9aae
* Version Independent ID: afc0a7d1-d3c2-acf2-d4ea-d2565e22b237
* Content: [ML.NET tutorials](https://docs.microsoft.com/pt-br/dotnet/machine-learning/tutorials/)
* Content Source: [docs/machine-learning/tutorials/index.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/index.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by mairaw** [comment]
@OliaG @asthana86 can one of you help with this question? Should I move this to the dotnet/machinelearning repo? Thanks.

**Comment by OliaG** [comment]
Hi @thiagoboccio, thank you for the question.

If you want to predict any name (meaning you'll feed in a huge list of names) by first letter(s), that would be an example of Sequence Prediction. We do not have an API for it in ML.NET yet. Also for this particular case instead of machine learning I would use a probabilistic finite state automaton.

An example where you can use ML.NET APIs right now: 
If you have a small set of names (for example employees in a team) with some other characteristics of the employees, and you’d like to predict the name base on the characteristics. In this case you can use Multiclass Classification.

**Comment by thiagoboccio** [comment]
Got it!
I'm doing what you suggested based on what we can do right now with ML.NET, gonna let you guys know in case I get stuck...
Thanks :)
