### ISSUE TITLE
The .NET Framework row is sligthly misleading

### ISSUE THREAD

**Issue by 0x53A** [dotnet/docs#5915]
The small footnote (1) is really inconspicious. I can understand that you want to sweep this under the rug, but it is important to know what is supported where.

The old table looked like this: https://cloud.githubusercontent.com/assets/4236651/26560789/86e0a85e-44b9-11e7-9e8f-427ad198a3cf.png

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb8b774-c6f0-8235-6964-15219baf2ea7
* Version Independent ID: 6819a4a7-7527-d8c7-e132-767f7344e00e
* Content: [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#feedback)
* Content Source: [docs/standard/net-standard.md](https://github.com/dotnet/docs/blob/master/docs/standard/net-standard.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by svick** [comment]
Why do you think it's important to prominently document what the .Net Core SDK 1.x did? As far as I know, there is no reason to use that. Even if you want to target the .Net Core runtime 1.x, you can use the .Net Core SDK 2.x for that.

**Comment by svick** [comment]
As far as I can tell, VS2015 only supports *preview* versions of .Net Core tooling 1.0. I don't think the documentation should focus on what old, preview versions do.

**Comment by 0x53A** [comment]
But it's not even about .NET Core, it's about full framework and old csproj format.

**Comment by dasMulli** [comment]
There is a .NET Standard 2.0 support package for VS 2015 but it has some problems that should be about to be fixed soon (https://github.com/dotnet/sdk/issues/1539). It requires manually installing the newest VS 2015 NuGet VSIX from https://www.nuget.org/downloads and following the download links it prints out when you're trying to reference .NET Standard NuGet packages.

Otherwise I agree that there is no reason to document tooling that is no longer recommended to be used.

**Comment by 0x53A** [comment]
It woud be great if that information (link to the support package) could be added there. And even then, if the tooling is a manual installation (in contrast to an automatic update), then I'm not sure if I can expect everyone to have it installed.

So I still think the information that VS2015 supports NET Standard 1.4 (NET 4.6.1) and NET Standard 1.5 (NET 4.6.2) out-of-the box, and NET Standard 2.0 (NET 4.6.1) with the support package is really valuable.

**Comment by dasMulli** [comment]
4.7.1 still needs some facades. Only 4.7.2 has all the assemblies in-box that are needed to use csc only if you have dll references. But even for 4.7.2 there are some corner cases that are still not fixed without tooling support - https://github.com/dotnet/sdk/issues/1738

> Also, the support package hacks into the build process with MSBuild targets…

The same happens in VS 2017, only that the extension targets are preinstalled into VS.

cc @leecow about the link - I think I saw this more prominently on https://dot.net somewhere, but can't find it now (aside: the new download experience is a lot better though)

**Comment by mairaw** [comment]
@0x53A I wouldn't call that information a lie. It's what's currently supported in the most current versions of the SDK. 

We decided to remove the 1.0 SDK information because it was causing confusion and I had several people requesting me that I clean that up on that doc. You can see the changed versions on the standard repo that we link to from the article: https://github.com/dotnet/standard/blob/master/docs/versions.md.

AFAIK you cannot develop .NET Standard libraries using csproj in VS2015, just consume them. I have an issue #2927 that I've been trying to get to it for months now. I'm hoping I can finally address it this current sprint. I just increased its priority yesterday during our triage meeting. VS2015 only supported the project.json format, which is not supported.

**Comment by 0x53A** [comment]
Apologies, "lie" was a bit aggressive and unconstructive.

> We decided to remove the 1.0 SDK information because it was causing confusion and I had several people requesting me that I clean that up on that doc.

I mean, the status-quo IS really confusing, because it is complex. But I am not sure if removing / hiding information reduced that complexity ...

> AFAIK you cannot develop .NET Standard libraries using csproj in VS2015, just consume them.

Practically, the table serves two purposes:

* what can I produce?
* what can I consume?

Normally, I would expect both of these to be the same, if they aren't, then it might be good to explicitly call that out. In my case, the consuming part is more important, because for my own dependencies, I can just produce full-fx, but many third-parties switched to .NET Standard only.

> But even for 4.7.2 there are some corner cases that are still not fixed without tooling support

:\  :sadpanda:


-------------------------

Some of the information in this thread I've seen already, strewn over multiple different github issues, other things are new to me. Would it make sense to add this either into the main documentation, or create a new page and link to it? NET Standard is praised as the cure to everything, but it is really hard to find detailed information about it. 

And I'd like to repeat my previous ask:

> Summarized, I think there should be two rows: __native support__, and __supported through tooling and deployed facades__.

As I read it, the __native support__ row for NS2 would be vNext (4.7.3 ?) because even 4.7.2 has issues? That's really important information!

**Comment by leecow** [comment]
The .NET Core Tools for VS2015 are linked from https://github.com/dotnet/core/blob/master/release-notes/download-archive.md. @dasMulli , is this what you're referring to?

**Comment by mairaw** [comment]
I don't feel like we should add that information back. @terrajobst what do you think? I'm inclined to close this issue as by-design. We should encourage people to move to newer versions of the SDK.

**Comment by 0x53A** [comment]
I'd like to reword my ask:

Please provide two rows, one for natively supported, one for supported through shims.

Scenario: I have a .NET Standard 2.0 Lib and Exe. For which frameworks is my deployment 2 files, and for which frameworks is my deployment 100 files?

**Comment by terrajobst** [comment]
> But even for 4.7.2 there are some corner cases that are still not fixed without tooling support - dotnet/sdk#1738

What corner cases are you referring to? dotnet/sdk#1738 seems to only talk abou 4.7.1. AFAIK 4.7.2 has no issues with consuming .NET Standard 2.0 binaries.

> Please provide two rows, one for natively supported, one for supported through shims.

That makes it more complicated that it needs to be. My opinion is that we should probably jut change the cell from 4.6.1 to 4.7.2 once 4.7.2 is (widely) available. We can then add an asterisk that points people so some guidance on how to use .NET Standard 2.0 before that.

**Comment by Gonnagle** [comment]
In my opinion it would be really helpful to have the table to somehow indicate which framework versions have a "native" support and which with the "hacks". What @terrajobst suggests seems rather good approach (list the first version supporting it without additional tooling and footnote about the additional support since 4.6.1 via tooling).

**Comment by 0x53A** [comment]
Well, nothing happened so far, so probably nothing will happen the next few months.
