### ISSUE TITLE
MsBuild or Command Line Integration, CI and Publish

### ISSUE THREAD

**Issue by gencebay** [dotnet/docs#5917]
Can I publish WCF service library project with auto generated *.svc and web.config files that integrated CI pipeline. (VSTS, TFS, Task or Command Line).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74770e0d-c48a-8355-8e73-c8afb968a7ac
* Version Independent ID: 686d2fa7-335b-8fb7-0c44-85231d49a4d8
* Content: [WCF Service Publishing](https://docs.microsoft.com/en-us/dotnet/framework/wcf/wcf-service-publishing)
* Content Source: [docs/framework/wcf/wcf-service-publishing.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/wcf-service-publishing.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
@zhenlan is this something you or someone from your team can help?

**Comment by zhenlan** [comment]
@gencebay is your question about whether you can publish a WCF application as part of CI instead of inside Visual Studio? Are you thinking about publishing to IIS? If yes for both questions, publishing of WCF applications is very similar to publishing ASP.NET applications, so you should be able to use tools for publishing ASP.NET applications, for example, web deploy.

cc @Lxiamail

**Comment by dasetser** [comment]
We don't currently support this functionality for the WCF Service Library projects. Your options for this would be to either use a WCF Service Application project (which includes these in the project and has more advanced publishing support), or create a custom MSBuild task to do this generation for you.
