### ISSUE TITLE
How to suppress compiler warnings

### ISSUE THREAD

**Issue by k3davis** [dotnet/docs#5975]
It would be helpful IMHO if information was provided on these pages about how to turn these warnings off.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1982705-65b6-fc10-f51c-43989fd20dca
* Version Independent ID: 04dea072-a176-b403-8550-ffde758c2f6f
* Content: [Compiler Warning (level 4) CS1591](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1591)
* Content Source: [docs/csharp/language-reference/compiler-messages/cs1591.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-messages/cs1591.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thanks for your feedback, @k3davis. A link to a topic that discusses how to suppressing compiler errors and warnings is found in this topic's parent page, [C# Compiler Errors](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/index),  For command line compilation compilation, there are also the [`-warn` and `-nowarn` switches](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/listed-by-category).

We currently have several issues open to improve our documentation for compiler error and warnings. Your comment identifies a number of additional issues:

- The linked topic that provides information on configuring warnings assumes that you're using the Visual Studio IDE. We should create a new topic that shows how to configure warnings by using a **.csproj** file and when compiling from the command line.
- To find the link to the topic about configuring warnings, you have to use the TOC to navigate to the top-level topic, which is hardly intuitive. Since there are a limited number of compiler warnings, it makes sense to use an include file that is imported into each warning topic and that provides a link to the topic on warning configuration.
I'll add this as an item to our [Projects for .NET Community Contributors](https://github.com/dotnet/docs/projects/35) in the event that a community member would like to begin working on it. And we'll review it as we begin work on improving our compiler error/warning documentation. 
Again, thanks for your feedback.

**Comment by DickBaker** [comment]
It would be useful to explicitly mention the VS project properties page (Build tab) that includes a checkbox next to the "XML documentation file" text. If this is set then CS1591 warnings will appear. This corresponds to the .csproj file having a related non-blank text in e.g. <DocumentationFile>bin\DickProj.xml</DocumentationFile>

I inherited a project where previous developer had started the XML Documentation tagging process but was far short of completing the job, so I was hit with a blizzard of warnings. Easy enough to switch off (either by clearing the checkbox or setting the filter checkbox in the "Error List" window) but would be helpful to those similarly blighted if this page briefly described purpose/fixes with more useful links to fuller explanations.

BTW seems it has been 6 months since OP and RP commented, so about time for action!

**Comment by RichardJFoster** [comment]
An associated challenge with this warning relates to the fact that the warning is still flagged (at least in Visual Studio 2017), even if there is an <inheritdoc/> tag, and there is inherited documentation available for the property/method in question (e.g. from a base class or interface level). I recently encountered a scenario where a team member saw the warning in this scenario and felt the need to add a documentation comment to make the warning go away. Alas, in doing so they replaced useful inherited documentation with alternate text that was of significantly lower quality, wasting their time and that of the person who subsequently had to revert those changes.

**Comment by Izharsa** [comment]
https://stackoverflow.com/questions/7982525/visual-studio-disabling-missing-xml-comment-warning
