### ISSUE TITLE
method doesn't exist

### ISSUE THREAD

**Issue by samboustani** [dotnet/docs#5985]
'DateTime' does not contain a definition for 'LessThan'.  .NET Core 2.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 582b5193-1b57-b5e5-6dd6-92cd03616a25
* Version Independent ID: f29ddee7-9d38-1e44-2f4f-ea4c1c98bd7d
* Content: [DateTime.LessThan(DateTime, DateTime) Operator (System)](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.op_lessthan?view=netcore-2.0#System_DateTime_op_LessThan_System_DateTime_System_DateTime_)
* Content Source: [xml/System/DateTime.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/DateTime.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by pkulikov** [comment]
@samboustani what made you think so? 

"LessThan" is the name of the operator. To use this operator in your code, use `<` symbol:

```csharp
var t1 = DateTime.Now;
var t2 = DateTime.Now;
Console.WriteLine(t1 < t2);
```

**Comment by rpetrusha** [comment]
Since LessThan is an operator rather than a method, @samboustani, the Syntax section shows the operator symbol; as @pkulikov indicates, it's `<`. The documentation also indicates that the equivalent method is DateTime.Compare; the current instance is earlier than a second instance if the Compare method returns a negative value.
Since the operator does exist, I'll close this issue. If you don't agree, @samboustani, feel free to respond.
