### ISSUE TITLE
Case Sensitivity

### ISSUE THREAD

**Issue by NotAClue** [dotnet/docs#6024]
Is the compare used for oldValue with the current string case sensitive or insensitive?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 012299fc-cd36-4cd8-9bdf-1d7a9a431516
* Version Independent ID: 9bb0a732-d14f-d0b4-460d-5952d52c47d5
* Content: [String.Replace Method (System)](https://docs.microsoft.com/en-us/dotnet/api/system.string.replace?view=netframework-4.7.2#System_String_Replace_System_String_System_String_)
* Content Source: [xml/System/String.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/String.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for your feedback, @NotAClue. The Remarks section of the String.Replace(String,String) overload notes that, "This method performs an ordinal (case-sensitive and culture-insensitive) search to find oldValue." Since the documentation contains the information you wanted, I'll close this issue; if you disagree, please feel free to respond.
