### ISSUE TITLE
Domain Info

### ISSUE THREAD

**Issue by vasanthloganathan** [dotnet/docs#6088]
Hi, Have a question. Will this work if the client and service are in different domains? if not is there any workaround?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c9566f7-bc96-dacf-1ed8-79bc04b853f6
* Version Independent ID: 659130d9-16ac-b94f-2680-9c1effa6f087
* Content: [Transport Security with Windows Authentication](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/transport-security-with-windows-authentication#feedback)
* Content Source: [docs/framework/wcf/feature-details/transport-security-with-windows-authentication.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/transport-security-with-windows-authentication.md)
* Product: **dotnet-framework**
* GitHub Login: @BrucePerlerMS
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
@zhenlan can you or your team help with this question?

**Comment by zhenlan** [comment]
I think it will require trust relation between the two domains. Add @mconnew to confirm.

**Comment by vasanthloganathan** [comment]
thank you all

**Comment by mconnew** [comment]
@vasanthloganathan, it will require a trust relationship between the two domains if you are using Kerberos. If you using explicit credentials (where you provide the username, password and domain to WCF instead of using the ambient login security context) which exist in the domain of the target server, then you can authenticate with NTLM and you don't need the trust relationship. NTLM has some security considerations that you should be aware of before using NTLM, there's plenty of information already findable with a search engine so I'll leave that for you to investigate if you decide to go that way.

**Comment by mairaw** [comment]
Thanks @mconnew for your help. I'm closing this issue.
