### ISSUE TITLE
what is "namespace-qualified name" and how do I get it?

### ISSUE THREAD

**Issue by StevenTCramer** [dotnet/docs#6125]
"You can use the GetType method to obtain a Type object for a type in another assembly, if you know its namespace-qualified name."
This must not be "typeof(myClass).FullName"  because that does not work for other assemblies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22f9d661-af1e-596f-8402-323649908ccd
* Version Independent ID: ea2b3fc7-f10b-b50f-52ef-4eb5f92c0c19
* Content: [Type.GetType Method (System)](https://docs.microsoft.com/en-us/dotnet/api/system.type.gettype?view=netcore-2.1#System_Type_GetType_System_String_)
* Content Source: [xml/System/Type.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Type.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
We should clarify that.

A "namespace qualified name" is the fully qualified name of a type, including its namespace. For example the fully qualified name of `String` is `System.String`. The fully qualified name of `Task<T>` is `System.Threading.Tasks.Task<T>`.

**Comment by d-dizhevsky** [comment]
The given page have 20 references (CTRL+F for `AssemblyQualifiedName`) to what `AssemblyQualifiedName` is. And I assume that if you are reading `remarks` somewhere at the middle of the post, you should've also read the other parts of it as well. 
@BillWagner what kind of changes we would need to do in order to clarify this?

**Comment by BillWagner** [comment]
@d-dizhevsky Adding a single sentence to define `AssemblyQualifiedName` on first use would fix this. (I would keep the links as well.)

**Comment by StevenTCramer** [comment]
@d-dizhevsky the page has a single reference to **"namespace-qualified name"**.  And I quote it the initial issue and again here:

**"You can use the GetType method to obtain a Type object for a type in another assembly, if you know its namespace-qualified name."**

@BillWagner tried to clarify what was meant by  "namespace-qualified name", which I think can be obtained with `typeof(myClass).FullName`

**But I do not think one can obtain a Type object using GetType from another assembly using the FullName (namespace-qualified name).**

It works fine with `AssemblyQualifiedName`  but that was **not** the question.

**Comment by d-dizhevsky** [comment]
`namespace-qualified name` can be obtained by https://msdn.microsoft.com/en-us/library/system.type.assemblyqualifiedname(v=vs.110).aspx 
e.g. `typeof(Object).AssemblyQualifiedName` FullName is another story and can’t be used full “path” to the type of another assembly because it is not really “full” in these terms

**Comment by StevenTCramer** [comment]
So `namespace-qualified name` should be removed or replaced with AssemblyQualifiedName?  

"You can use the GetType method to obtain a Type object for a type in another assembly, if you know its `AssemblyQualifiedName`"

**Comment by BillWagner** [comment]
Fixed in dotnet/dotnet-api-docs#316

**Comment by mrpmorris** [comment]
It looks wrong to me. Let me elaborate...

`You can use the GetType method to obtain a Type object for a type in another assembly, if the you know its namespace-qualified name. GetType causes loading of the assembly specified in typeName.`

If I am not mistaken you cannot force load of an assembly simply by specifying a class name that is qualified only to namespace level, because dotnet won't know which assembly to load in order to find that namespace + class.  So it should be "assembly qualified name".

It then goes on to say 

`You can ***also*** load an assembly using the Load method, and then use the GetType or GetTypes methods of the Assembly` (Emphasis mine)

The use of the word "also" implies it is an alternative to the first suggestion. However, this second approach is suggesting that the coder uses the assembly path on `Assembly.Load` and then use a namespace qualified class name to get the type from the loaded assembly. If the alternative is suggesting a namespace-qualified class name then this further supports the idea that the first approach is detailing an assembly-qualified class name. 
My recommendations are:

1. Change `if the you know its` to `if you know its`
2. Change the text to read `You can use the GetType method to obtain a Type object for a type in another assembly by specifying its assembly-qualified name. In this case the GetType method causes the loading of the assembly specified in typeName. Alternatively, you can load an assembly using the Assembly.Load method and then use a namespace-qualified type name in the GetType or GetTypes methods of the assembly instance returned from Assembly.Load`
