### ISSUE TITLE
Cannot lock on null object

### ISSUE THREAD

**Issue by MorganKauppi** [dotnet/docs#6188]

**Comment by svick** [comment]
This issue originally said:

> Cannot do "lock(PreDrawEvent)", since PreDrawEvent will (probably) be null initially

And it was linking to [How to: Implement Custom Event Accessors (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/events/how-to-implement-custom-event-accessors).

@MorganKauppi I agree the example is bad. Not just because `PreDrawEvent` could be `null`, but also because locking like this can never work, because the `PreDrawEvent` object will keep changing.

I have opened a Pull Request to fix this: https://github.com/dotnet/docs/pull/6324.
