### ISSUE TITLE
Categories of Access modifiers seems to be incorrect

### ISSUE THREAD

**Issue by aditimantri2196** [dotnet/docs#6206]
Are there seriously six access modifiers in c#?

The brief provided for "private protected" should be the brief for "protected internal" instead. And, does "private protected" access modifier seriously exist? If it does what does this exactly do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8181f41d-b6ce-ad66-084e-8d2b514b87e2
* Version Independent ID: 494c4344-b752-4f86-5b66-1ef4b81c1e75
* Content: [Classes and Objects in C# - A tour of the C# Language](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/classes-and-objects#feedback)
* Content Source: [docs/csharp/tour-of-csharp/classes-and-objects.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tour-of-csharp/classes-and-objects.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
> Are there seriously six access modifiers in c#?

Yes.

> The brief provided for "private protected" should be the brief for "protected internal" instead.

It should not. `protected internal` means the member is accessible from the containing class, derived classes or types in the same assembly.

> And, does "private protected" access modifier seriously exist? If it does what does this exactly do?

It does exist since C# 7.2, see [this page](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/private-protected). It does what its description says: it means the member is accessible from the containing class or types that are both derived and within the same assembly.
