### ISSUE TITLE
MemoryStream vs FileStream

### ISSUE THREAD

**Issue by brunis** [dotnet/docs#6210]
Any reason you're using a MemoryStream here?  is FileStream content encoding out of our hands and would it be problematic with Json?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ee09ba-3e07-b558-1e18-0af2afbd3809
* Version Independent ID: 93820b68-aa8a-7cdd-c952-60e5e4118252
* Content: [How to: Serialize and Deserialize JSON Data](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/how-to-serialize-and-deserialize-json-data)
* Content Source: [docs/framework/wcf/feature-details/how-to-serialize-and-deserialize-json-data.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/how-to-serialize-and-deserialize-json-data.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by BenjaminChambers** [comment]
I assume it's just for simplicity. Any stream would work, a memory stream is simply the easiest.

**Comment by Snorchy** [comment]
Yes but with XML serialisation FileStream is used. I think enforcing consistency would be a good idea.

First because it eliminates any confusion like the original question. Stuff like: "Why are they using MemoryStream here and FileStream there? JSON can't handle files efficiently?" Especially to newbies.

Second because it allows for comparison between types and you can quickly see their implementation differences.

**Comment by mairaw** [comment]
@Lxiamail can you look at this feedbacK for a WCF article? Thanks!

**Comment by Thraka** [comment]
Consistency is nice, but this is not a high priority. I'm going to close this issue. Please feel free to update the sample and submit a PR. Thanks!
