### ISSUE TITLE
Please clarify *why* <supportedRuntime> is required

### ISSUE THREAD

**Issue by kkm000** [dotnet/docs#6234]
It is stated that all .NET applications using CLR 1.1 and higher (which, in the year 2018, means *all* applications) "should" specify the supported runtime. What is lacking is an explanation *why* should they, and when it can be different from the TFM hardcoded into the executable.

I [asked this question a long time ago on StackOverflow](https://stackoverflow.com/q/47298916/1149924), and, although it did attract some visits, there are no answers or even comments to date.  Given than the executable assembly is always created by the toolchain with an assembly-level  `System.Runtime.Versioning.TargetFrameworkAttribute` identifying the "sku" (ILDASM output is in the linked question), then why the config setting duplicating this information is required (or, if the word "should" is used here in the RFC-2119 sense, highly recommended)? And, practically speaking, I've yet to find an executable that would not work without it.

So I believe an explanation is required here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbaa501d-ecb5-34d9-841f-d858056af103
* Version Independent ID: 5b9d3e55-a6e5-46c7-78d3-fc5f2b3a5bab
* Content: [&lt;supportedRuntime&gt; Element](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/startup/supportedruntime-element)
* Content Source: [docs/framework/configure-apps/file-schema/startup/supportedruntime-element.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/startup/supportedruntime-element.md)
* Product: **dotnet-framework**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by matthew1471** [comment]
Not 100% sure but I believe if multiple version of the .NET framework are installed or items which are not present in that version your program can crash at the point the new method/param is attempted to be called which makes for a poorer user experience or difficult to debug. It appears as the .NET releases have increased since 4.0 this is laying the groundwork to replace specifically targeting a version (such as 4.7.1).

For instance if I use something in .NET 4.7.1 that happens to not be in .NET 4.0 that you have installed. If the <supportedRuntime> says the app requires 4.7.1 then the app will not run. If it does not specify this then you'll attempt to run it anyway and if I haven't used any 4.7.1 specific items you will use the app without issue.

It looks like we've stayed on CLR 4 for a while, with everything since just being improvements on it : https://en.wikipedia.org/wiki/.NET_Framework_version_history#Overview

**Comment by kkm000** [comment]
@matthew1471, Thanks for sharing your thoughts. There are two interesting facts to keep in mind. 

First, when you say “if multiple versions of the .NET framework are installed,” are you speaking of e. g. .NET v2.0 and 4.0, or e.g. v4.0, 4.5 and 4.7.1? The latter is not possible, as all 4.x upgrades are replacements of the previous framework files. There are two directories on the machine, one per .NET 4 bitness, `%SystemRoot%\Microsoft.NET\Framework\v4.0.30319` and another with similar path but  Framework64, and all assemblies are deployed right there. Their strong name also does not change between versions. On the machine I am typing this, I have framework v4.7, but the strong name of the assembly `C:\Windows\Microsoft.NET\Framework64\v4.0.30319\System.Core.dll` is `System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089`. Note the version: it is 4.0.0.0 always. So with .NET 4.0, there are no longer SxS version of the framework itself.

This also implies complete backward compatibility of all 4.x versions. When you install a newer version of the framework, all older bits are gone, and the new set of DLLs should perform exactly same for all existing apps. Of course, your concern “what if 4.8 breaks my app?” is valid, but this, if happens, is an indication of a bug in the framework implementation.

Second of all, the statement at the very end of the quote you are providing (by the way, I do not understand where is the source of it), “Since .NET 4 it looks like altering the targeting options in Visual Studio actually just changes this App.config param,” is not correct. There is also an attribute `System.Runtime.Versioning.TargetFrameworkAttribute` always automatically added by into the executable by the compiler (we are talking about .exe files, as only they may have the runtime-honored .config files). Check my SO question link for more details. This attribute indicates the target framework. i do not know if the runtime will prevent execution of such an .exe if the installed version of the framework is lower, but so it true about a .config file.

Now think about this. There is an attribute in the assembly, that is placed automatically by the compiler when the file is built. The author has no simple control over this attribute: if you target 4.5, the compiler will emit an attribute with the string `".NETFramework,Version=v4.5"` as the first argument¹. No space for error, even if you wrote your .csproj with Notepad. *Why on Earth you are also required to duplicate this information in the .config file?* If you are using Notepad as your favorite IDE, there is a much, much greater potential for a mistake here. Suppose there is a  .config file. Which information is more reliable? If you were the runtime, which of the two would you trust? I'm sure you'd bet on the attribute. That's the point where I am getting utterly, royally confused!

And in fact, all executables in my posession happily run without a .config file at all. Micrsoft's own nuget.exe is distributed as a single .exe without a config file.

----
¹The targeting pack MSBuild scripts indicate the version, and a file is autogenerated in the %TEMP% directory. This can be  seen by invoking MSBuild from command line (the following is very abridged) and then checking the file contents:
```
C:\projects\foo\foo>msbuild
 . . .
CoreCompile:
  C:\...\bin\Roslyn\csc.exe ... foo.cs "C:\Users\kkm\AppData\Local\Temp\.NETFramework,Version=v4.5.AssemblyAttributes.cs ...

C:\projects\foo\foo>type "C:\Users\kkm\AppData\Local\Temp\.NETFramework,Version=v4.5.AssemblyAttributes.cs"
// <autogenerated />
using System;
using System.Reflection;
[assembly: global::System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.5", FrameworkDisplayName = ".NET Framework 4.5")]

C:\projects\foo\foo>
```
So *maybe* not all toolchains would implant the attribute. But even still, the attribute is guaranteed to stay forever with an executable, and its .config file is not. For the part of the system capable of launching an executable, reading an attribute out of it is a no-brainer. So it's still confusing why the recommendation is not "always make sure your EXE has the correct TargetFrameworkAttribute." Instead we are to re-type this very same information into the config file by hand. What for?

I think that by this point I am over my weekly limit on using the word "confusing" and exhausted the monthly supply of the question "why?", so I should stop here! :)

**Comment by kkm000** [comment]
@mariaw, I still got not an answers on SO to this question, and, apparently, not much activity here is expected, given how old the issue has been open. Maybe you have any idea who at Microsoft could clarify it? I remember that you have always been very responsive in other issues I previously opened in this repo! I am coming back to think of it once in a while (today I'm reminded of it by a next upvote to the SO question), and it's still as perplexing as ever. I would really appreciate it if you could forward that into an internal mailing list, or whatever you have inside there--I've never worked for MS, but there must be such a thing! :). Cheers, and thank you!

**Comment by mairaw** [comment]
Sorry for the delay @kkm000. As you can see, our backlog has been growing and we're a small team.
 
@csharpfritz any idea who could help with this question? Is there something we could add to the topic to explain why is needed?

**Comment by csharpfritz** [comment]
I'm not familiar with this topic... and would ask @DamianEdwards to help redirect to someone who can better address the question

**Comment by JirkaHanika** [comment]
The reason is explained here: [https://stackoverflow.com/questions/21566528/what-happens-if-i-remove-the-auto-added-supportedruntime-element](https://stackoverflow.com/questions/21566528/what-happens-if-i-remove-the-auto-added-supportedruntime-element).  In my experience, in some cases supportedRuntime can save you substantial headaches; when running on lower .NET version than the one used to build it without a suppportedRuntime setting, an app can end up in a zombie state much inferior diagnostically than refusing to start up and complaining about the .NET version.

However, there's an exception to this.  If you'd add supportedRuntime with the lowest value for a particular major CLR version, such as "v4.0.0", and targetFramework of all your projects is also at least .NET 4, such a setting has no practical effect.  The app won't run on anything lower anyway.  You could still specify supportedRuntime out of a habit and it wouldn't be wrong.

**Comment by kkm000** [comment]
@JirkaHanika, thanks for the reference, seems to make sense.

Do you happen to know whether the `TargetFrameworkAttribute` ignored, or enforced? If the latter is the case, then the app.config clause still appears to be redundant?

**Comment by JirkaHanika** [comment]
The attribute specifies which .NET version has built the assembly, or more exactly, what targetFramework setting in your (entry) project file or in VS, mediated through the appropriate targetting pack installed in the build environment, was in effect.  In addition, it provides a soft hint to tell the installed framework which version of itself to emulate, but only if you haven't specified any supportedRuntime; furthermore, the attribute is still ignored when the framework doesn't recognize the version, typically because it's a newer version than the framework version available in the deployment environment.

If you need to enforce anything, follow Microsoft's guidance and use app.config.  For a high level overview, see here: https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-configure-an-app-to-support-net-framework-4-or-4-5

I'm intentionally simplifying by disregarding any framework versions older than 4, as those can co-exist with version 4 and thus give you some different types of choices; but the referenced pages still cover those, too.

**Comment by MSDN-WhiteKnight** [comment]
Agree, this line is misleading. Remarks already indicate that if it's absent it will default to target framework. It is probably supposed to mean "*This element should be used by all applications built with version 1.1 or later of the .NET Framework instead of requiredRuntime element used with .NET Framework 1.0*". But given that 1.0 and 1.1 are not supported for a long time, and applications targeting them are in fact extremely rare, i don't think it's worth mentioning at all. Additionally, summary does not reflect the SKU parameter (which is technically not related to runtime). 

So the summary should be changed to something like that:

>Specifies which versions of the common language runtime and, optionally, .NET Framework release the application supports.

And this can be appended to remarks:

>If this element is specified and none of the supported .NET Framework versions is found on the target machine, the application will fail to run and instead display the message asking to install the requred version.

**Comment by kkm000** [comment]
@JirkaHanika, thanks for the explanation. I think I understand now.

Yes, it's somewhat surprising that Microsoft's development documentation still documents how to develop an application for the Framework 1.1 or 2.0. These versions could be long-term-supported, but *develop a new application*? But I may not know everything. Maybe someone somewhere still has reasons to do just that...
