### ISSUE TITLE
Combining diacritics

### ISSUE THREAD

**Issue by Rolschge** [dotnet/docs#6262]
"\u0061\u0308".StartsWith("\u0061", StringComparison.InvariantCulture)
-&gt; false
"\u0061\u0308".Substring(0,"\u0061".Length).StartsWith("\u0061", StringComparison.InvariantCulture)
-&gt; true
It seems to me, that a comparison with substring gives different results due to combining diacritics in unicode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9d4aca5-9f7b-19de-969f-3f54d2fab15e
* Version Independent ID: 394bb8e0-e246-17ef-18f8-d2b8ea72c0c7
* Content: [String.StartsWith Method (System)](https://docs.microsoft.com/en-us/dotnet/api/system.string.startswith?view=netframework-4.7.1#System_String_StartsWith_System_String_System_StringComparison_)
* Content Source: [xml/System/String.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/String.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for submitting this issue, @Rolschge. Unicode combining characters are considered in the comparison. If you call StartsWith to determine if "\u0061\u0308" starts with "\u00e4", the result is true for the invariant culture and for the current culture (at least when the current culture is en-US).  For culture-sensitive comparisons, the runtime does some string normalization before performing the comparison, so that the comparison is between text units rather than individual 16-bit characters. If you want a byte-by-byte or binary comparison, you should use StringComparison.Ordinal or StringComparison.OrdinalIgnoreCase.

@tarekgh, you might want to add additional detail or corrections to my response, @tarekgh.

I think that this is adequately documented throughout our documentation set. If you think that there's some area of the documentation that needs improvement, please let us know. We'll keep this issue open for the next several days so that you can respond.

**Comment by tarekgh** [comment]
The string "\u0061\u0308" string is the characters a and  ̈  which will be equivalent to the "ä"

"\u0061\u0308".StartsWith("\u0061", StringComparison.InvariantCulture) is false becaue the string "ä" doesn't start with "a" ligustically "ä" and "a" are different characters. 

while 

"\u0061\u0308".Substring(0,"\u0061".Length)

while return "\u0061" which is "a" and "a".StartsWith("a") is true. 

This is by design. 

The confusion is coming from String class treats the contents as an array of characters (no normalization or anything is done on the characters). so it treats \u0061\u0308" as 2 separate characters as long as you are not doing any linguistic operation on it (e.g. Compare, StartsWith, EndsWith, IndexOf, and LastIndexOf.

**Comment by Rolschge** [comment]
Thanks for the details on linguistic operations vs non-linguistic operations.
Maybe this could be emphasized in the docs.

A shorter example on this topic:
`> "\u0062\u0308".Contains("\u0062")`
`true`
`> "\u0062\u0308".IndexOf("\u0062")`
`-1`

**Comment by tarekgh** [comment]
@Rolschge

We have the documentation of StringComparison which talk about the different options can be used when performing the operations on the string with some examples. 

https://docs.microsoft.com/en-us/dotnet/api/system.stringcomparison?view=netframework-4.7.1

I don't mind adding more specific examples as you pointed out. I'll let @rpetrusha handle that.

**Comment by Rolschge** [comment]
Thanks.
