### ISSUE TITLE
No mention of `App.config`, unclear intended workflow

### ISSUE THREAD

**Issue by ite-klass** [dotnet/docs#6313]
When creating a new C# project in Visual Studio, it will create an `App.config` file. Visual Studio automatically copies this to the output directory with adequate name `myApp.exe.config`.

This documentation does not mention the `App.config` file, not as a default, nor as a possible alternative.

Instead, it talks about `myApp.exe.config`, even explicitly saying that the file should be named `myApp.exe.config`. But if that is the intended workflow, shouldn't the project template create the App.config under that name?

What is the intended workflow?

The paragraph in question:

&gt; When you develop in Visual Studio, place the source configuration file for your app in the project directory and set its Copy To Output Directory property to Copy always or Copy if newer. The name of the configuration file is the name of the app with a .config extension. For example, an app called myApp.exe should have a source configuration file called myApp.exe.config. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b39c5030-7cdb-a2b4-4abf-0451ab4d8de4
* Version Independent ID: 4aae87fd-84b4-4cbf-aeec-4da9a43f4396
* Content: [Configuring Apps by using Configuration Files](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/index)
* Content Source: [docs/framework/configure-apps/index.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/index.md)
* Product: **dotnet-framework**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by astafan8** [comment]
Are there any news on resolving this issue? I read the documentation just now, and it's still confusing what is going on.

Specifically, my question is the following. If in the `.proj` file, i set the xml attribute to "always copy" the `app.config` file, then not only i get the generated `myapp.exe.config` file in the build (or publish) directory, but i also still get the `app.config` file there, which i learned from this article is of no use. So i decide that since `app.config` is not used by the built executable, then let's ont copy it to the "output directory". So i go and remove the corresponding xml attribute from the `.proj` file, but when i do so, the `myapp.exe.config` file DOES NOT get generated! Why is that? What is wrong with my understanding? Can the documentation page be improved to be more explicit?
