### ISSUE TITLE
Improve informations about possible usage of nameof operator

### ISSUE THREAD

**Issue by TobiasSekan** [dotnet/docs#6406]
I would be nice , when this article have a table or a text that contains information about usable elements for nameof operator.

e.g.
name of namespace = yes/no ?
name of class = yes
name of function = yes
value =  no
operator = no
..... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d6e6220-cbdf-c81c-1f3f-eceaac577b3d
* Version Independent ID: d7516eb5-db45-8651-70a3-21115a4ba432
* Content: [nameof  (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/nameof)
* Content Source: [docs/csharp/language-reference/keywords/nameof.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/nameof.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@TobiasSekan Thanks for the feedback.  I am going to close this, because I think all the information from your table is in the first sentence of this article:

> Used to obtain the simple (unqualified) string name of a variable, type, or member.

Mapping to your table items

name of namespace = no
name of class = yes (it's a type)
name of function = yes (it's a member)
value = no
operator = no

If you disagree, you can reopen this issue and add more details about what you are looking for.

**Comment by PavelShalahai** [comment]
Can you please add to examples switch/case + enum example? It would be very helpful. 
 
public enum Days
    {
        Sunday,
        Monday,
        Tuesday
    }

 switch (Days)
                {
                    case nameof(Days.Sunday):
                        Doomething();
                        break;

                    case nameof(Days.Monday):
                        Doomething();
                        break;
               }

**Comment by svick** [comment]
@PavelShalahai Why do you think that's a good example? If you're switching using an enum, the variable should be of the `enum` type, not `string`, in which case you wouldn't need `nameof` (i.e. it would be just `case Days.Sunday:`).

Also, if you have new feedback, you should open a new issue, instead of commenting on an unrelated issue for the same article.
