### ISSUE TITLE
Lack of support for *.sfproj type 

### ISSUE THREAD

**Issue by TomaszSynak** [dotnet/docs#6424]
Can't add *.sfproj type to existing sln file. Getting: 
> Project ... has an unknown project type and cannot be added to the solution file. Please contact your SDK provider for support.

Used command: _dotnet sln add Tmp.sfproj_
Ref: [dotnet sln](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-sln)

**Comment by mairaw** [comment]
@KathleenDollard @livarcocc @peterhuene does dotnet sln support adding service fabric projects? 

Should I move this feedback to the CLI repo?

**Comment by peterhuene** [comment]
Sorry @mairaw, I missed this ping.  With 2.1.300 and later of the .NET Core SDK, we're expecting `DefaultProjectTypeGuid` to be set when evaluating the project.  For SDK-style projects, this either gets set by the default language-specific targets (for C# and VB) that ship with MSBuild or inside of specific SDKs (like F#'s SDK, for example).

I'm not familiar with service fabric projects at all, but if this did work in the past, it's only because `dotnet sln add` would blindly assign the project type as C# for unknown projects.  This would have resulted in the incorrect project system used when opening the solution in VS if it in fact wasn't a C# project.

Any MSBuild project can set `DefaultProjectTypeGuid`, but it's generally expected to be set at the SDK-level.  Thus, if there's an SDK for service fabric projects, `DefaultProjectTypeGuid` can be set in their targets to resolve the issue.

I've discussed this a little with @TomaszSynak on dotnet/cli#9477, which was a related issue regarding `DefaultProjectTypeGuid` not being set for any cross-targeting project.

**Comment by mairaw** [comment]
I'm closing this issue then. @TomaszSynak please work with @peterhuene and file an issue at https://github.com/dotnet/cli/issues/ instead with the required repro steps and the engineering team will take a look. After the investigation is done in the product side, I'm happy to add a note about the expected/actual behavior to our docs.
