### ISSUE TITLE
Folder Encrypting

### ISSUE THREAD

**Issue by Manoj-Prabhakaran** [dotnet/docs#6475]
how to use for encrypting a whole folder???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a8e441d-cd59-de15-a814-0d86d4cda052
* Version Independent ID: c94ca6d4-7e93-8aac-93d1-7f249c77d243
* Content: [Walkthrough: Creating a Cryptographic Application](https://docs.microsoft.com/en-us/dotnet/standard/security/walkthrough-creating-a-cryptographic-application)
* Content Source: [docs/standard/security/walkthrough-creating-a-cryptographic-application.md](https://github.com/dotnet/docs/blob/master/docs/standard/security/walkthrough-creating-a-cryptographic-application.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by BillWagner** [comment]
@Manoj-Prabhakaran This may be best asked on a  Q & A forum like Stack Overflow. I have a number of clarifying questions about how you would extend this sample: Do you want to encrypt a folder as a single file? Do you want each file in a folder encrypted separately? Would they all use the same key?

Those questions make me think this is best answered on a Q & A forum rather than in docs.

**Comment by Manoj-Prabhakaran** [comment]
@BillWagner  Thank you very much for your Answer

**Comment by tdykstra** [comment]
Thanks for contacting us. We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
