### ISSUE TITLE
Operator precedence

### ISSUE THREAD

**Issue by avifarah** [dotnet/docs#6483]
I was looking for operator precedence

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eeac581-6235-2192-d909-e7fe3d21197f
* Version Independent ID: 9d8e2a57-1c18-8cba-9bd4-eef546fe2dcb
* Content: [C# Operators](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/#see-also)
* Content Source: [docs/csharp/language-reference/operators/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thanks for your feedback, @avifarah. Operator precedence is discussed in [Operators](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/operators#operators-evaluation-and-operator-precedence) topic in the C# programming guide.

Since operator precedence is documented, I'm going to close this issue. If you disagree, please feel free to respond.
