### ISSUE TITLE
Document which settings from NuGet.config affect dotnet restore

### ISSUE THREAD

**Issue by nphmuller** [dotnet/docs#6496]
In the docs it's mentioned that `The behavior of the dotnet restore command is affected by some of the settings in the Nuget.Config file`. Please consider documenting which settings exactly affect `dotnet restore`. Because currently I simply have to try what works and what doesn't, which isn't really productive.

For example: NuGet allows [using environment variables](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#using-environment-variables). But this is not supported through dotnet restore (or at least, I can't seem to get it to work).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b256dc4-c4ad-c115-f4e2-40310bc3505a
* Version Independent ID: 0b993779-65a2-6092-4047-2fc2ec16170b
* Content: [dotnet restore command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore?tabs=netcore2x)
* Content Source: [docs/core/tools/dotnet-restore.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-restore.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by BillWagner** [comment]
Thanks for pointing this out @nphmuller 

We'll work to get that updated.  /cc @KathleenDollard

**Comment by IsmailHassani** [comment]
@nphmuller hmm, seems like I stumbled to the same error? ;)

**Comment by Thraka** [comment]
@nphmuller @IsmailHassani Hi, I'm going to start taking a look at this.

**Comment by Thraka** [comment]
Details on what is going on:

dotnet restore is extremely similar to:

dotnet msbuild /t:restore
(this runs with net core’s msbuild)

msbuild /t:restore
(runs with net framework’s msbuild)

Restore Target and Task are implemented in nuget.build.tasks.dll:
https://github.com/NuGet/NuGet.Client/tree/dev/src/NuGet.Core/NuGet.Build.Tasks

Some other docs:

Nuget.config details:
https://docs.microsoft.com/nuget/consume-packages/configuring-nuget-behavior

Details on some other settings:
https://docs.microsoft.com/nuget/consume-packages/managing-the-global-packages-and-cache-folders

The NuGet.config docs have sections.
The sections that are not applicable are:
- bindingRedirects
- solution
- trustedSigners

The **bindingRedirects** section does not apply to **PackageReference**, in both dotnet.exe and nuget.exe. dotnet.exe supports _only_ **PackageReference**. 

The **solution** section is legacy and Visual Studio specific. 

The **trustedSigners** is not applicable because we don’t have support for cross platform verification, so that will be added later.  https://github.com/NuGet/Home/issues/7606
