### ISSUE TITLE
Windows couldn't complete the requested changes.

### ISSUE THREAD

**Issue by IzaacJ** [dotnet/docs#6528]
Whne trying to activate .NET Framework 3.5 through Programs and Features->Turn Windows features on or off I get the usual popup for installing it, but when downloading required files I get this:

Windows couldn't complete the requested changes.
The system cannot find the file specified.
Error code: 0x80070002

So how do I solve this? First time EVER I've ran into this.

Windows 10 Pro x64.

**Comment by rpetrusha** [comment]
I'm sorry to hear that you're having difficulties, @IzaacJ. The following may help resolve your problem:
- [Install the .NET Framework 3.5 on Windows 10, Windows 8.1, and Windows 8](https://docs.microsoft.com/en-us/dotnet/framework/install/dotnet-35-windows-10) 
-  [Error message when you try to update a Microsoft Windows-based computer: "0x80070002"](https://support.microsoft.com/en-us/help/922582/error-message-when-you-try-to-update-a-microsoft-windows-based-compute)
- [Fix Windows update issues](https://support.microsoft.com/en-us/help/10164/fix-windows-update-errors)
- [Possible cause of 1935 error with HRESULT 0x80070002](https://blogs.msdn.microsoft.com/astebner/2005/02/01/possible-cause-of-1935-error-with-hresult-0x80070002/)
I'll close this issue, since it doesn't have a documentation impact.
