### ISSUE TITLE
Developing w/o an Internet Connection / Offline

### ISSUE THREAD

**Issue by richlander** [dotnet/docs#654]
We need a topic on this experience. It's more a set of patterns and how we think about it.

**Comment by mairaw** [comment]
@richlander can you elaborate on what you'd like to see in this topic?

**Comment by hifi** [comment]
From Linux packaging point, there are some things that should be considered regarding this topic and I think they are important for distributions to accept .NET Core as part of their base packaging.

First, all dotnet* packages that are part of the runtime or SDK need to be self-hosting and offline buildable. They must not depend on any online resources or any code that can't be built from the sources. They also need to install into normal LSB paths rather than /opt.

All stock .NET Core NuGet packages must be packaged as distribution packages that can be referenced in projects normally and the default NuGet install should prefer a local repo over online if it can satisfy dependencies. AFAIK NuGet already supports local paths so it's only a matter of default configuration and packaging guidelines.

Ideally at the end `dotnet new` and `dotnet run` will both work offline. Adding new NuGet packages through the package manager would feed the tools creating a fully offline ecosystem that you can depend on.

This also enables writing real Linux .NET Core cli applications that could be packaged for distributions like any other software and allow porting some that depend on Mono to .NET Core if wanted.

If some of these issues have already been solved, could they be referenced in this issue to get an overview of what has been done and what's still pending?

**Comment by BillWagner** [comment]
Assigning P2 to this issue. 

I've found I can usually work around a lack of a connection, once packages are restored.  If you want to raise the priority, go ahead @richlander

**Comment by mairaw** [comment]
Who would help with this @richlander? Would it be @leecow?

**Comment by leecow** [comment]
Richard will need to provide a bit more info on the topic he has in mind. 

@hifi - Thanks for that feedback! The Linux packaging angle is a priority for us which we are actively working toward. [dotnet/source-build](https://github.com/dotnet/source-build/) is the place where that conversation and work is happening.

**Comment by BillWagner** [comment]
This issue has been closed as part of the issue backlog grooming process outlined in #22351.

That automated process may have closed some issues that should be addressed. If you think this is one of them, reopen it with a comment explaining why.
