### ISSUE TITLE
Not everything documented in the code appears in the docs website

### ISSUE THREAD

**Issue by sfilipi** [dotnet/docs#6542]
This namespace has a lot more other public classes and public methods inside them, that don't appear in the docs.microsoft.com website. 

For example: AppendRowsDataView is public and does have proper XML style comments on it: https://github.com/dotnet/machinelearning/blob/a5faca6beac1b7b5a19e1211dfaa1e254ae1f370/src/Microsoft.ML.Data/DataView/AppendRowsDataView.cs

It also exists in the docs repo:
https://github.com/dotnet/ml-api-docs/tree/master/dotnet/xml/Microsoft.ML.Runtime.Data 

but doesn't show up on this list. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db0baab6-e781-fea4-7a0d-6eed783c1312
* Version Independent ID: 51859fe7-fbe9-2280-2aa4-5955d7de3f7f
* Content: [Microsoft.ML.Runtime.Data Namespace](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.runtime.data?view=ml-dotnet)
* Content Source: [dotnet/xml/ns-Microsoft.ML.Runtime.Data.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/ns-Microsoft.ML.Runtime.Data.xml)
* GitHub Login: @dotnet-bot

**Comment by mairaw** [comment]
Hi @sfilipi, this is because that API was the only one chosen to be exposed in the docs before. 
You can see the logic of what's being filtered out at https://github.com/dotnet/ml-api-docs/blob/master/dotnet/xml/_filter.xml.

We can make adjustments if needed. I can remove the whole filter for that namespace if that's what you wanna do. Just let me know if that's what you wanna do.

We should review the filter list for every release.

**Comment by dend** [comment]
👍 to what @mairaw stated above. The specific issue is caused by [this fragment](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/_filter.xml#L55-L59).
