### ISSUE TITLE
Exceptions?

### ISSUE THREAD

**Issue by bdcoder2** [dotnet/docs#6564]
Question - I ASSUME if the documentation does not include an "Exceptions" section, then none can or will be thrown (in this case) by the Enqueue() method? - Yes / No?

Once upon a time, in documentation far, far away there used to be mention of error codes returned by functions.   It would be nice to know if methods do or do not throw exceptions.   As Yoda once said -- "Do or do not, there is no try" -- but these days, I have to wrap every method call in a try because I have no clue what method will likely throw an exception !!  

[End of Rant] 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a56a0580-a156-229a-bb67-20e722672feb
* Version Independent ID: 7f555541-8c30-34b4-43f3-bb081a1b9d24
* Content: [ConcurrentQueue&lt;T&gt;.Enqueue(T) Method (System.Collections.Concurrent)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentqueue-1.enqueue?view=netframework-4.6.2)
* Content Source: [xml/System.Collections.Concurrent/ConcurrentQueue`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections.Concurrent/ConcurrentQueue`1.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for your feedback, @bdcoder2. In general, we attempt to document all exceptions that might be thrown by a method. In an ideal world, all exceptions are documented, and if there is no exceptions section, the method does not throw an exception. Unfortunately, though, we're not perfect, and we do miss exceptions that should be documented. Where this is the case, please let us know via a GitHub issue and we'll document it.

That said, there are some exceptions that we never document since they can be thrown by any (or almost any) method. In particular, we don't document the NullReferenceException that is thrown when a method is called on a null reference, since this results purely from developer error. And we don't document the OutOfMemoryException that can be thrown by any method that allocates memory, since the exception is extremely infrequent and catastrophic, 

In looking at the source for ConcurrentQueue<T>.Enqueue, for example, I don't see any exceptions thrown. 

Since this is a general question that is not immediately actionable, I'll close this comment. If you disagree, please feel free to respond.
