### ISSUE TITLE
Object initialisers, what's the benefit?

### ISSUE THREAD

**Issue by NickHumphries** [dotnet/docs#6568]
It seems to me that object initialisers simply move code from one place to another. What is the actual advantage of using this style?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5121576-832f-dba0-f489-ba17c1891161
* Version Independent ID: 0ffb923c-a49c-ed59-abb6-9618aea5df61
* Content: [How to: Initialize Objects by Using an Object Initializer (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/how-to-initialize-objects-by-using-an-object-initializer)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/how-to-initialize-objects-by-using-an-object-initializer.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/how-to-initialize-objects-by-using-an-object-initializer.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thanks for submitting your feedback, @NickHumphries. Using object initializers is really a matter of coding style and preference. That said, it offers two attractive features: making the intent of code clearer, and convenience (as well as cleaner, more concise code). 
As far as making the intent of code clearer, in the example, the choice is to call the constructor, where it's not always clear what the constructor arguments are or what they represent, or assigning the same arguments to properties, which generally produces more readable code. In terms of convenience, rather than separately calling the constructor and then assigning property values, it can be done in a single operation. 
I hope that this answers your question. If it doesn't, feel free to respond. I'll close this issue, since it doesn't have documentation impact.
