### ISSUE TITLE
example output

### ISSUE THREAD

**Issue by johnnyagerard** [dotnet/docs#6608]
Running the example code, I don't have the exact time of the day:
20
Example string.
7/22/2018 12:00:00 AM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f669fa6b-11b2-4b97-898d-025018e76cd5
* Version Independent ID: e1745bae-146e-ae73-2c17-a5e16eaa303f
* Content: [dynamic (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/dynamic)
* Content Source: [docs/csharp/language-reference/keywords/dynamic.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/dynamic.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by johnnyagerard** [comment]
It's in convertToDynamic() static method

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @johnnyagerard. The Today property returns the date with no time component (or a time component equal to midnight). I suspect the Now property was originally used, the example changed, and the output not updated. We've opened a PR so that the output corresponds to the actual output produced by the example, at least for a computer whose culture is en-US.
