### ISSUE TITLE
Missing new ReadOnlySpan overloads

### ISSUE THREAD

**Issue by raffaeler** [dotnet/docs#6616]
The StringBuilder API has been recently (2.1) improved with many overloads taking ReadOnlySpan&lt;char&gt; but the documentation, althought referring to 2.1, does not report them.
Reference: https://github.com/dotnet/coreclr/pull/13163/commits/997f4e8e114f5d582b85a8fe29a880cdbcc0bca0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2e7c7d5-d12c-5430-bfee-b6171e843c4e
* Version Independent ID: 19d6c6e2-2fe7-bd44-1141-44d5337f22fe
* Content: [StringBuilder Class (System.Text)](https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder?view=netframework-4.7.2)
* Content Source: [xml/System.Text/StringBuilder.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text/StringBuilder.xml)
* Product: **.net**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
@raffaeler, which APis are missing? A comparison of source with the StringBuilder documentation shows the following are all present:
- [CopyTo(Int32, Span\<Char>, Int32)](https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.copyto?view=netcore-2.1#System_Text_StringBuilder_CopyTo_System_Int32_System_Span_System_Char__System_Int32_)
- [Append(ReadOnlySpan\<Char>)](https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.append?view=netcore-2.1#System_Text_StringBuilder_Append_System_ReadOnlySpan_System_Char__) 
- [Insert<Int32, ReadOnlySpan\<Char>)](https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.append?view=netcore-2.1#System_Text_StringBuilder_Append_System_ReadOnlySpan_System_Char__)
- [Equals(ReadOnlySpan\<Char>)](https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.equals?view=netcore-2.1#System_Text_StringBuilder_Equals_System_ReadOnlySpan_System_Char__)

I'm going to close this issue as not repro, since all new Span and ReadOnlySpan-related APIs are present (though they still have to be documented). If you disagree, please feel free to respond.
