### ISSUE TITLE
Benefits?

### ISSUE THREAD

**Issue by eschneider999** [dotnet/docs#6627]
I'm guessing there is some benefits to doing this? Performance?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26899b81-d6f9-534a-83ee-283dd8aae545
* Version Independent ID: 3061125d-7de4-97ef-ccb0-ee792d6f2ae1
* Content: [readonly keyword (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/readonly?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(readonly_CSharpKeyword)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.5.2)%3Bk(DevLang-csharp)%26rd%3Dtrue)
* Content Source: [docs/csharp/language-reference/keywords/readonly.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/readonly.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
It depends on the context of the read-only keyword, @eschneider999. For fields, the benefit is not performance but program design; it prevents what should be a write-once field having its value change, which can have disastrous consequences. For the remaining two uses, the benefit is performance.  See ["Reference semantics with value types"](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-2#reference-semantics-with-value-types) in the What's New in C# 7.2 article. 
Since your question doesn't have any actionable documentation impact, I'll close it.

**Comment by eschneider999** [comment]
there is a benefit for static fields, but i think the main benefit is securing the initial value.
My point is that nothing in the explains the reason to use the readonly statement.

If noone understands the benefits, they will not use it...
