### ISSUE TITLE
K-Means Clustering

### ISSUE THREAD

**Issue by subash774** [dotnet/docs#6635]
Is there a way of finding out how many clusters data is separated into after we train the model? In other words, without "predicting", how do we know the number of clusters? Also, is there a way to find optimum value for K like in scipy? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd15175c-5b7d-4310-ecf5-32ffc7bc588b
* Version Independent ID: 38adc676-934e-0ff9-c868-527f075c96df
* Content: [Machine learning tasks](https://docs.microsoft.com/en-us/dotnet/machine-learning/resources/tasks)
* Content Source: [docs/machine-learning/resources/tasks.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/resources/tasks.md)
* Product: **dotnet-ml**
* GitHub Login: @aditidugar
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
@GalOshri or @Zruty0 - Could you answer this? Thanks!

**Comment by Zruty0** [comment]
Currently, KMeans algorithm exposed in ML.NET does not try to infer the optimum number of clusters, it always used the user-specified value K.

Therefore, there should not be a problem finding what is the value of K, since it's user-defined. However, as far as I know, the clustering model outputs a vector-valued column of 'distances to centroids', and the cardinality of this column is equal to the number of clusters, so this is another indirect way for finding K after the fact.

**Comment by JRAlexander** [comment]
Thanks, @Zruty0! @subash774, I am closing as it appears resolved. If this is not the case, then please reopen. Thanks!
