### ISSUE TITLE
Missing method CreateEntryFromFile

### ISSUE THREAD

**Issue by JeffLangballe** [dotnet/docs#6648]
The method CreateEntryFromFile is missing from the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3d6ec69-e771-7535-d7b8-cde3e43ae629
* Version Independent ID: 6edb630b-4e65-bdf8-8efd-cb5974682887
* Content: [ZipArchive.CreateEntry Method (System.IO.Compression)](https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.ziparchive.createentry?view=netframework-4.7.1#feedback)
* Content Source: [xml/System.IO.Compression/ZipArchive.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO.Compression/ZipArchive.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by svick** [comment]
It's not missing, it's just less visible because it's an extension method. See [`ZipFileExtensions.CreateEntryFromFile`](https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.zipfileextensions.createentryfromfile?view=netframework-4.7.1).

This means it's listed in [the Extension Methods section of documentation for `ZipArchive`](https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.ziparchive?view=netframework-4.7.1#extension-methods).

**Comment by JRAlexander** [comment]
Thanks for your feedback, @JeffLangballe! This appears resolved so I'm going to close this. Please reopen if that is not the case.
