### ISSUE TITLE
Error handling; no mention of Result<'a,'b>

### ISSUE THREAD

**Issue by aggieben** [dotnet/docs#6665]
The section on exceptions mentioned the idea of using the `Option` type for usecases where errors aren't really exceptional, but I think it's probably better to use `Result` - and really, I'd think that idiomatically functional F# code should prefer using results rather than throwing exception in nearly every case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b185b377-3bc4-49fe-fcc2-63500cc9d29e
* Version Independent ID: 5bd70365-b75b-5439-eb86-6a22e4f05684
* Content: [F# component design guidelines](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/component-design-guidelines)
* Content Source: [docs/fsharp/style-guide/component-design-guidelines.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/style-guide/component-design-guidelines.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
Guidance for error management is, I think, better described in the Coding Conventions article: https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/conventions#error-management

Where various concerns for DDD, exceptions, and results are addressed. But a bit of information is in both places - here and in the coding conventions article - that really complete the picture. No approach is universally better, as there are tradeoffs to consider in either case. I'm not currently pleased with how some of this information is split across files. Perhaps we can bring bits from both into the other, but I'd have to think through how to rationalize this.

The guide as a whole does have duplicated content, since it includes the Component Design Guidelines, which are useful, but do not cover many concerns that become relevant in larger codebases.

**Comment by aggieben** [comment]
@cartermp Perhaps it would be useful to link to that section in the F♯ Coding Conventions then?  Currently the .NET Library Design Guidelines document is linked, and it is C♯-centric.

**Comment by cartermp** [comment]
@aggieben Done. I think the section I link to can have more work:

* Provide an example where Result makes sense
* Provide an example where Option makes sense

Because today it's really only lip service that's paid to them. But at least the guidance is centralized, and certainly in the case of exceptions, more fleshed out.
