### ISSUE TITLE
Value object ef core migrations

### ISSUE THREAD

**Issue by IsharaPannila** [dotnet/docs#6674]
Properties of Value object needs to have setters to add them with ef core migrations.

public class Address : ValueObject
{
    public String Street { get; set; } // without this "set;" this will not work

orderConfiguration.OwnsOne(p => p.Address)
                            .Property(p=>p.Street).HasColumnName("ShippingStreet");
and this will also fails with "Field '&lt;XXXX&gt;k__BackingField' of entity type 'XXXX' is readonly and so cannot be set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b14bbb-dc66-f1a2-8b14-39ef3b4bde1d
* Version Independent ID: 4f0bfce6-eac9-e09e-0d17-08c2842720ac
* Content: [Implementing value objects](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/implement-value-objects)
* Content Source: [docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/implement-value-objects.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/implement-value-objects.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by mvelosop** [comment]
Hi @IsharaPannila,

You're right, we detected the issue too, although the problem then was about deserializing an integration event

We are working on it, it's issue dotnet-architecture/eShopOnContainers#667.

I'm closing the issue here because it's being addressed in the [eShopOnContainers repo](https://github.com/dotnet-architecture/eShopOnContainers)
