### ISSUE TITLE
Does it mean that C# compiler does not compile statements line by line due to its optimization AI?

### ISSUE THREAD

**Issue by verynewuser** [dotnet/docs#6720]
If we try to initialize a class field with another class field at the time of declaration, C# compiler gives us this error. Does it mean that the C# compiler can compile any of those two statements one before the other and the path is NOT fixed?

```
class TheClass
{
  int first_int = 100;
  int second_int = first_int; // Error here
}
```

The workaround for this situation is:
```
class TheClass
{
  int first_int = 100;
  int second_int;
  public TheClass
  {
    second_int = first_int;
  }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19167a3c-283f-e0c1-d1cb-3b773954779b
* Version Independent ID: 360140ec-e61d-3117-e7a7-92473887f7b6
* Content: [Compiler Error CS0236](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0236)
* Content Source: [docs/csharp/misc/cs0236.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs0236.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
> Does it mean that the C# compiler can compile any of those two statements one before the other and the path is NOT fixed?

No, that's not the rules. The fields are initialized in order, but the language rules define that they cannot depend on each other.  This is explained in detail in the [C# specification](https://docs.microsoft.com/dotnet/csharp/language-reference/language-specification/classes#instance-field-initialization) where field initialization rules are defined.

I'm closing this, as this article is correct, and explains the fix for the problem.
