### ISSUE TITLE
Update F# Golden Path Article

### ISSUE THREAD

**Issue by cartermp** [dotnet/docs#681]
The F# golden path article (https://github.com/dotnet/core-docs/blob/master/docs/scenarios/solution-authoring/f-golden-path.md) needs to be updated to use the correct version numbers/bits for .NET Core SDK Preview 2.  This is going to be dependent on https://github.com/Microsoft/visualfsharp/pull/1290.

It also needs an appropriate entry in the TOC.

**Comment by jacqueline-homan** [comment]
I am relatively new to learning F# and I do not have VS or Windows. So I think one big issue right off that needs to be addressed is the need for making it a lot less impossible for people who are not on Windows that are trying to learn F#. When something works for a tutorial author who's on Windows using VS, the beginner struggling to learn is left unable to complete a tutorial if they're on Linux and having to use Monodevelop because things don't reference the same way (like F# script files, for example). Having enough knowledge or skill level to know how to translate everything to a different toolset than what a tutorial author has **​is** something beyond the scope of beginners. Especially considering disadvantaged populations who didn't get to learn computers until MUCH older in life (not all of us had computers at age 10 or the opportunity to learn computer stuff until much later in life).
