### ISSUE TITLE
Question about access modifier

### ISSUE THREAD

**Issue by vladkolodka** [dotnet/docs#6816]
Hi. I have a question. When I am trying to use any access modifier for an explicit interface, I'm getting an error: "The modifier &lt;modifier_name&gt; is not valid for explicit interface implementation".
As I understand, I should not try to do so, but. What is the access modifier used implicitly?
Logically, there must be only one valid access modifier - "public". But it does not work either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bda601c2-3dbe-4ad1-db39-670cff3b654c
* Version Independent ID: 092fce57-ea16-c7a6-c85d-f6c111eba4eb
* Content: [Explicit Interface Implementation (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation)
* Content Source: [docs/csharp/programming-guide/interfaces/explicit-interface-implementation.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/interfaces/explicit-interface-implementation.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thanks for your comment, @vladkolodka. An explicit interface implementation does not have an access modifier since it is not accessible as a member of the type in which it is defined. Instead, it is only accessible when called through an instance of the interface. Interface members are always public.  

Attempting to define an access modifier results in compiler error [CS0106](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0106). This is the same compiler error that results when you attempt to attach an access modifier to a member in an interface definition -- and it is produced for the same reason.

I hope that this helps to answer your question. 

I'm closing this issue, since it doesn't have a documentation impact.

**Comment by alamseti** [comment]
Hi, 
See the below program. How should I access the I2 and I3 interface methods?

using System;

namespace InterfaceExmple
{
    interface I1
    {
        void Show();
    }

    interface I2 : I1
    {
        new void Show();
    }

    interface I3 : I2
    {
        new void Show();
    }

    class Test : I3
    {
        public void Show()
        {
            Console.WriteLine("I1 Show");
        }

       void I2.Show()
        {
            Console.WriteLine("I2 Show");
        }

        void I3.Show()
        {
            Console.WriteLine("I3 Show");
        }
    }
    class Program
    {
        static void Main(string[] args)
        {
            Test obj = new Test();
            obj.Show();
            obj.I2.Show();
            Console.ReadLine();
        }
    }
}
