### ISSUE TITLE
Is there a reason for the casting in the first try/catch example?

### ISSUE THREAD

**Issue by ravidw** [dotnet/docs#6866]
((IDisposable)s).Dispose(); 
It should be working without the casting as well, isn't it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b83e20ec-96de-0340-0813-27968ae4ca89
* Version Independent ID: db8ef20b-08da-cbac-0d96-91dcef8abe56
* Content: [Using objects that implement IDisposable](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/using-objects)
* Content Source: [docs/standard/garbage-collection/using-objects.md](https://github.com/dotnet/docs/blob/master/docs/standard/garbage-collection/using-objects.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by svick** [comment]
In this specific case, yes, it would work the same without the cast, because `StreamReader` implements `IDisposable` implicitly.

But some types might implement that interface explicitly, which is where it would make a difference.

Since this article is explaining how `using` works in general, I think it makes sense to keep the cast in there.

**Comment by rpetrusha** [comment]
Thanks for your question, @ravidw, and for your response, @svick. The IL-generated code includes a [callvirt](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.opcodes.callvirt) call to IDisposable.Dispose, which translates into a cast to IDisposable in the event that the type disposed by the `using` statement provides an explicit interface implementation. 
I hope that this answers your question, @ravidw; if it doesn't, please feel free to respond. In the meantime, since I don't believe that your question impacts the documentation, I'll close this issue.
