### ISSUE TITLE
-checked default value

### ISSUE THREAD

**Issue by johnnyagerard** [dotnet/docs#6878]
There seems to be a contradiction that I don't understand.

In the "-checked (C# Compiler Options)" page, it is said the following:
    "The default value for this option is -checked-."

And on this page, it is said that:
    "By default the value of that option is unset".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afbca89d-149d-f904-bbec-71446bfa5506
* Version Independent ID: 6ce3ce8d-a80c-81aa-2d16-b2fec0d8a89a
* Content: [Checked and Unchecked (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/checked-and-unchecked)
* Content Source: [docs/csharp/language-reference/keywords/checked-and-unchecked.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/checked-and-unchecked.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@johnnyagerard The `-checked` compiler option has two possible values: `+` (set) or `-` (unset). The last dash in
> The default value for this option is -checked-.

corresponds to the `-` value (unset) of the option. 

The compiler page should be clarified.

**Comment by johnnyagerard** [comment]
Thank you for the clarification.

**Comment by rpetrusha** [comment]
Thanks for raising this issue, @johnnyagerard, and for pointing out that the documentation needs some clarification, @pkulikov. 
In the [-checked (C# Compiler Options)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/checked-compiler-option) topic, the paragraph that mentions the default value is `-checked-` also continues with a scenario that uses `-checked-`, which is confusing, since it's a scenario for using the default value. That confusion can be addressed by simply adding a paragraph break and rephrasing the resulting second paragraph slightly.
I've added this to the backlog and the community contributor's project.

**Comment by pkulikov** [comment]
@rpetrusha it looks that #6877 fixes this issue

**Comment by rpetrusha** [comment]
Yes, thanks for pointing that out, @pkulikov. I forgot to check that #6877 was linked to this issue, which I'll close manually.
