### ISSUE TITLE
Standardize See also section to use bulleted list

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#6923]
Our See also section is not standardized at the moment. Some sections use bulleted lists, while others use the entries with two spaces at the end. After a contributor's PR, we discussed internally and decided it was better to use bulleted list from now on. When contributing to this issue, break into smaller PRs so we're not overwhelmed by a huge PR.

**Comment by nemrism** [comment]
Last 5 PRs cover the end of /docs/csharp/** folders

**Comment by nemrism** [comment]
I may be wrong, but PR  #8145 doesn't "fixes" this issue but "contributes" to it.
This issue still need "a lot" of standardization in some sections of the docs.
cc @rpetrusha @amaldevv

**Comment by mairaw** [comment]
You're right @nemrism. Reopening.

**Comment by NextTurn** [comment]
Section titles are not standardized as well. Some sections use `See also`, while others use `See Also`. Which one is preferred?

While `See also` is always used in `dotnet/dotnet-api-docs` repo.

**Comment by pkulikov** [comment]
@NextTurn 

> Some sections use `See also`, while others use `See Also`. Which one is preferred?

`See also`
Moreover, for all the titles and headings, sentence-casing is preferred: #808

**Comment by NextTurn** [comment]
It seems that bulleted list is not welcome elsewhere.

https://github.com/MicrosoftDocs/cpp-docs/pull/778#issuecomment-461979749

**Comment by mairaw** [comment]
@corob-msft I'm interested to know why you think that using HTML elements in Markdown is better than using the bulleted list for C++. This solution has worked really well for us.

**Comment by corob-msft** [comment]
@mairaw 

The main reason we use breaks in the C++ docs is because the use of bullets is a gratuitous change from the MSDN format. We stumbled upon using bullets while trying to fix the broken markdown conversion that merged all the links into one line, before we figured out the real problem: there was only one space at the end of each line instead of two. Another reason is, bullets imply more emphasis and cohesion to the list than is warranted. I preferred the original formatting.

After converting all our **See also** links, parameter lists, definitions, and EBNF syntax blocks to use two spaces at the end, we discovered another problem, based solely on markdown usability. Because most contributors do not have "visible spaces" turned on in their editors, they can't readily determine that some lines need to have two spaces at the end to be formatted correctly. The GitHub web editor is a common offender. Even worse, some editors are configured to strip trailing spaces automatically. It was a problem I saw it appear in many contributions.

The markdown to HTML conversion just turns two spaces at the end of a line followed by a single newline into a <br/> tag. Rather than have an endless task of finding and fixing the spaces at the end of lines in various contributions, I've used the <br/> tag explicitly everywhere to indicate a break instead of a paragraph. It just shortcuts the conversion process a bit. Every contributor using any editor can see the <br/> tag and will use it appropriately. They don't need to be experts on every nuance of markdown formatting. I realize that it triggers a markdown lint warning, but it's saving us from predictable, hard to detect, and easily avoidable editing issues, so I count it as a win.

**Comment by mairaw** [comment]
Yeah, I agree that the two spaces at the end are horrible and they're usually deleted by mistake when we get contributions. We're slowly getting rid of them in other sections like "In this section", etc. But when we want to have a soft break line, we've adopted using a \ at the end instead of a <br /> tag.

But for the See also section, I find that it doesn't make a huge difference in terms of layout to use the bulleted list (although I did prefer the old layout as well), but using it makes the content a lot simpler and cleaner. It seems that VS also adopted the same format: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-move-around-in-the-visual-studio-ide?view=vs-2017#see-also

But anyway, we can discuss more about this offline. I'm closing the issue here, since it seems we've standardized all See also sections in our content. PRs are welcome if we still have some left.

Thanks @nemrism and @NextTurn for your help with this!
