### ISSUE TITLE
Missing description / formatting issue

### ISSUE THREAD

**Issue by ygoe** [dotnet/docs#6999]
It would be nice to see a description at the top, not just for each overload. Because they probably all do the same.

Also, there's a remark only for the last overload (with one parameter) that finally explains (sort of) what these methods do and why. But it has additional paragraph breaks in the middle of the sentence.

I'd also wish for a more detailed explanation of how this is done, to imagine why I should use this magic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d38e24cd-3568-ee10-e18c-6262faeeb5bb
* Version Independent ID: 4b23ab47-87c7-32b1-a0ca-9c13d5ec93e5
* Content: [HashCode.Combine Method (System)](https://docs.microsoft.com/en-us/dotnet/api/system.hashcode.combine?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.HashCode.Combine%60%606);k(DevLang-csharp)%26rd%3Dtrue&view=netcore-2.1)
* Content Source: [xml/System/HashCode.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/HashCode.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Hi @ygoe, thanks for your feedback. Yes, docs.microsoft.com now allows us to do this instead of having to add remarks individually because all overaloads are now all in one page. But the size of the reference is huge and we haven't had time to make this sort of improvement yet since we migrated the content. I've added this to our backlog.
