### ISSUE TITLE
bcdc.Method1();  

### ISSUE THREAD

**Issue by ravidw** [dotnet/docs#7051]
It is not clear why "bcdc.Method1();" returns "Derived - Method1" after using overide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4702e20f-4482-e0ce-bf61-784d436b64d5
* Version Independent ID: c88cfd2b-fdee-64eb-c26c-4d808e82e8b6
* Content: [Knowing When to Use Override and New Keywords (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/knowing-when-to-use-override-and-new-keywords)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/knowing-when-to-use-override-and-new-keywords.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/knowing-when-to-use-override-and-new-keywords.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@ravidw The paragraph immediately following the sample you reference above explains how virtual and override change the method resolution from using the compile-time type to the run-time type. 

I'm closing this as resolved.

**Comment by GitLloyd** [comment]
As I believe @ravidw did not stop reading right after that and had noticed the paragraph you mentioned, which does not specify what you wrote, your answer does not help. It's still not clear. Why does the program care about the object being declared as a DerivedClass for the "override" method and chooses that instead of the BaseClass method, despite the type being BaseClass, but doesn't care about the "new" method, if it "hides" (?) that of the BaseClass? Also, it's said that ovverride "extends" the BaseClass method, but it actually doesn't "extend" anything, it just literally replaces the base method implementation with its own in the DerivedClass.
