### ISSUE TITLE
Step 1 of "To Change Appearance of Characters" is wrong

### ISSUE THREAD

**Issue by sulustart** [dotnet/docs#7111]
The original text says, "Set the SelectionFont property to an appropriate font." But the correct property name in Visual Studio 2017 for a Windows Forms RichTextBox is "Font" property. There is no "SelectionFont" property. (-sulu@startmail.com)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

When I said above "Visual Studio 2017" I was referring to the Properties window of the RichTextBox. FYI

* ID: 584465a0-ff2f-d448-5cc6-745ca7e472af
* Version Independent ID: 415582d3-238c-9624-30be-d088c9a311f8
* Content: [How to: Set Font Attributes for the Windows Forms RichTextBox Control](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/how-to-set-font-attributes-for-the-windows-forms-richtextbox-control)
* Content Source: [docs/framework/winforms/controls/how-to-set-font-attributes-for-the-windows-forms-richtextbox-control.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/controls/how-to-set-font-attributes-for-the-windows-forms-richtextbox-control.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for your comment, @sulustart. Applying a font or color to selected text is very different from applying it to all text in the text box, which is what the Font property does. The SelectionFont property is not visible in the Visual Studio properties window, since the presence of selected text is a runtime-only characteristic. The SelectionFont and SelectionColor property values can only be set or retrieved programmatically. This article indicates how to do this. 
Since the article is not incorrect, I'm going to close this PR. If you disagree, please feel free to respond.

**Comment by sulustart** [comment]
Thank you Ron!
I really appreciate your thoughtful email explaining how this works.

-sulu
