### ISSUE TITLE
No docs for runtime vs development package for Linux

### ISSUE THREAD

**Issue by shahid-pk** [dotnet/docs#714]
This should be clearly stated because on production servers we don't need the development package **dotnet-dev-preview2-**\* ( preview in the package name scares system admins) . On production servers this package **dotnet-sharedframework-microsoft.netcore.app-1.0.0** will suffice for .deb based distributions.

**Comment by mairaw** [comment]
@blackdwarf @kendrahavens is this related to the deployment instructions we'll be adding here?

**Comment by blackdwarf** [comment]
@mairaw we should, actually. I think we should cover these in the installation as well.

**Comment by BillWagner** [comment]
/cc @JRAlexander 

Do we have this information already as part of the Docker docs? Of so, can we close this?

**Comment by kendrahavens** [comment]
Adding @KathleenDollard.

I don't think we should only have these instructions in the Docker docs because it is also relevant outside container scenarios. Interested users may not think to look in the Docker docs on how to deploy your app and run on a server with only the runtime installed (and not the .NET sdk). I don't think this capability is super clear in our deployment doc: https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli

**Comment by JRAlexander** [comment]
I believe it is covered in the Docker docs, but I will verify. Agree with @kendrahavens. It's not super clear.

**Comment by KathleenDollard** [comment]
@leecow can we chat next week on what we need here?

**Comment by leecow** [comment]
@KathleenDollard ... book it :-)

**Comment by JRAlexander** [comment]
@KathleenDollard, @leecow Would you all mind if I join you for that?

**Comment by shahid-pk** [comment]
I think the docs should say something on the lines of  "For production environments you only need the run time in case of shared apps. Standalone apps has the run time deployed with them. The sdk package is not required for production servers"
We can take example from mono. In case of mono for production only the mono-runtime package is required for development mono-complete package is required.

**Comment by JRAlexander** [comment]
This was added a while back. Closing.
