### ISSUE TITLE
The address regex also matches the scheme

### ISSUE THREAD

**Issue by Benexx** [dotnet/docs#7158]
When using the regex for matching the address it failed when using a start-of-line sign (^). The description says it should match an IP address or host name but the test string also includes the scheme. So "^mydomain\.com$" failes while "^https://mydomain\.com$" works

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98854bd4-e32e-df8d-f48f-2b647f2bd509
* Version Independent ID: 3b9bb944-2585-43e0-d21c-fb234ec9366b
* Content: [&lt;add&gt; Element for bypasslist (Network Settings)](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/add-element-for-bypasslist-network-settings)
* Content Source: [docs/framework/configure-apps/file-schema/network/add-element-for-bypasslist-network-settings.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/network/add-element-for-bypasslist-network-settings.md)
* Product: **dotnet-framework**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by rpetrusha** [comment]
I'm not quite sure that I understand your comment, @Benexx. The example doesn't use the `^` anchor, and it's not clear to me why you'd want to use it. Also, how did you test the bypass list?

**Comment by Benexx** [comment]
The example is working correctly but the description states you can use a regex to match the domain or IP address. For example when I want to match `www.domain.com` and not `anotherwww.domain.com` I cannot use the regex `www\.domain\.com$` because that will test valid on both domains. If I read the description I would expect that the correct regex for matching exacly the url should be  `^www\.domain\.com$` but this regex failes. This because (apparently) the regex is tested agains `http://www.domain.com`  (the domain AND the scheme) and not `www.domain.com` maybe this should be mentioned in the description. The correct regex for only 1 domain is `^https?://www\.domain\.com$`.

I tested this by request a local url with a C# WebClient request with a non-existing proxy in the web.config. When the bypasslist matches the domain the proxy should be ignored and the request should success. When the bypasslist didn't match the non-existing proxy would be used and throws a nework exception.

**Comment by rpetrusha** [comment]
@davidsh, can you help with this?

**Comment by mairaw** [comment]
Ping @davidsh @karelz

**Comment by davidsh** [comment]
@Benexx Thank you for your report.

I tested some of the regex expressions you commented on above using: https://regex101.com/

In particular this regex is not 100% valid since it has unescaped delimiters:
>^https?://www\.domain\.com$

so I had to modify it to:
>^https?:\/\/www\.domain\.com$

>If I read the description I would expect that the correct regex for matching exacly the domain should be `^www\.domain\.com$` but this regex fails. This because (apparently) the regex is tested again `http://www.domain.com` (the domain AND the scheme) and not `www.domain.com` maybe this should be mentioned in the description.

Since you explicitly tested this and observed this behavior, I would say that this is an old bug in the .NET Framework.  The intent of the feature for this setting is that you shouldn't need to specify a scheme.  So it was intended that a regex of `^www\.domain\.com$` would work for your example scenario.

Please open up a bug in .NET Framework here:
https://developercommunity.visualstudio.com/spaces/61/index.html

In general, though, we don't update the documentation to reflect bugs since the intent is that the bug would be fixed in some future version.  But such a fix would be documented via release notes, etc.

**Comment by Benexx** [comment]
Thanks for the response, added a bug report:
https://developercommunity.visualstudio.com/content/problem/485109/the-address-regex-also-matches-the-scheme.html
