### ISSUE TITLE
round-off error

### ISSUE THREAD

**Issue by johnnyagerard** [dotnet/docs#7189]
&gt;Note the round-off errors associated with the double type.

What round-off error?
I don't see any.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 227f6a03-7076-a47a-24de-a2c3c31a90b5
* Version Independent ID: 8538cb70-a092-1166-1cd9-b77f5e6a80d4
* Content: [% Operator (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/remainder-operator)
* Content Source: [docs/csharp/language-reference/operators/remainder-operator.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/remainder-operator.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
You're right, @johnnyagerard. There is no "error" associated with the double type. It would be useful, though, to add an instance of "error" caused by double imprecision to the example. For example, `        Console.WriteLine(.41 % .2);` produces a result of 0.00999999999999995 instead of the expected .01. Would you like to open a PR to make the change, or would you like us to?

**Comment by johnnyagerard** [comment]
@rpetrusha I opened PR #7208.
