### ISSUE TITLE
The string key of the Add(string, string) method is not case sensitive!

### ISSUE THREAD

**Issue by moyanming** [dotnet/docs#7192]
If I Add("A","1") and Add("a","2"), there is only one key "A" and this key have value "1,2". But [a] is "1,2" which is same as [A]="1,2".
I need case sensitive, that means the value of the key "A" is "1", the value of the key "a" is "2". How to fix this?
Best regards!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d196de7a-5f7a-0b18-f642-8ce0de6fdc36
* Version Independent ID: 9b48cd26-8403-e596-580f-a5c9193aba54
* Content: [NameValueCollection.Add Method (System.Collections.Specialized)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.namevaluecollection.add?view=netframework-4.7.2)
* Content Source: [xml/System.Collections.Specialized/NameValueCollection.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections.Specialized/NameValueCollection.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for your question, @moyanming. If you don't explicitly specify a comparer when instantiating the NameValueCollection object and don't copy from an existing NameValueCollection object, comparisons by default are case-insensitive. For a NameValueCollection object that automatically performs case-sensitive comparisons, call the [NameValueCollection(IEqualityComparer)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.namevaluecollection.-ctor#System_Collections_Specialized_NameValueCollection__ctor_System_Collections_IEqualityComparer_) constructor overload with an `equalityComparer` argument of either of  [StringComparer.InvariantCulture](https://docs.microsoft.com/en-us/dotnet/api/system.stringcomparer.currentculture),  [StringComparer.CurrentCulture](https://docs.microsoft.com/en-us/dotnet/api/system.stringcomparer.invariantculture), or  [StringComparer.Ordinal](https://docs.microsoft.com/en-us/dotnet/api/system.stringcomparer.ordinal), depending on the exact type of case-sensitive comparison you want.
Since I think that this should answer your question, I'll close this issue.

**Comment by moyanming** [comment]
Hi @rpetrusha , yes, the NameValueCollection(IEqualityComparer) constructor overload with StringComparer which implements the IEqulityComparer is what I want.
I am sorry for the less read about the NameValueCollection doc [here](https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.namevaluecollection?view=netframework-4.7.2).
Thank you for your answer!

**Comment by rpetrusha** [comment]
You're welcome, @moyanming. And thanks for responding. It strikes me that the [NameValueCollection class](https://docs.microsoft.com/dotnet/api/system.collections.specialized.namevaluecollection)  documentation might be enhanced by noting how to specify something other than the default case-insensitive comparison. I'll schedule some time to do this in the near future.

**Comment by moyanming** [comment]
@rpetrusha , if I add twice value "1" to the same key "A" as follow:
Add("A","1");
Add("A","1");
there are two values ("1,1") of the key "A", ["A"]="1,1", why the same value still add to the same key?
Best regards.

**Comment by rpetrusha** [comment]
It happens because the NameValueCollection stores multiple values to the same key. If that's not the behavior that you want -- that is, if you only want one value per key -- use the [Dictionary\<TKey, TValue>](https://docs.microsoft.com/dotnet/api/system.collections.generic.dictionary-2) class.
