### ISSUE TITLE
Doesn't clearly specify output format

### ISSUE THREAD

**Issue by owlstead** [dotnet/docs#7238]
Unclear if the linked private key is included, if the output is DER / binary or PEM. We are Mickeysoft, we ignore Developers, Developers, Developers, Developers, Developers!!!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50c1f644-9a56-288e-57e5-5a2f0bfad9ec
* Version Independent ID: 14e4cad7-910c-5be6-8e5e-8098b34caed5
* Content: [X509ContentType Enum (System.Security.Cryptography.X509Certificates)](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509contenttype?view=netframework-4.7.2)
* Content Source: [xml/System.Security.Cryptography.X509Certificates/X509ContentType.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography.X509Certificates/X509ContentType.xml)
* Product: **dotnet-api**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by bartonjs** [comment]
I don't know that the description for the enum fields can be any better.  If `X509Certificate2.GetCertContentType(data)` returns `X509ContentType.Pkcs12` there's nothing saying that there's a private key in it.  Or a public certificate.  Just that the blob is a PKCS12 blob (aka a PFX).  It also doesn't indicate BER, DER, PEM-BER, PEM-DER, or "opaque"

For X509Certificate.Export, based on the different requested format types:

* Cert: Returns a DER-encoded value for the public portion of the X.509 public key certificate.
* Pkcs12: Returns a DER-encoded PKCS#12 PFX which contains this certificate,  using system defaults for content encryption and MAC algorithms.  If a private key is associated with this certificate (see X509Certificate2.HasPrivateKey) it will be included in the PFX.  If a private key is associated with this certificate and it cannot be exported a CryptographicException will be thrown.
* SerializedCert: On Windows, returns the value built by https://docs.microsoft.com/en-us/windows/desktop/api/wincrypt/nf-wincrypt-certserializecertificatestoreelement.  A PlatformNotSupportedException is thrown on non-WIndows operating systems.
* All other values throw (already addressed in Remarks)

For X509Certificate2Collection.Export:

* Cert: If the collection is empty, `null` is returned.  Otherwise, a DER-encoded value for the public portion of the X.509 public key certificate for the first object in the collection is returned.
* Pkcs12: Returns a DER-encoded PKCS#12 PFX using system defaults for content encryption and MAC algorithms.  The X.509 public key certificate for each object in this collection is included.  For each object in the collection, if a private key is associated with the certificate object (see X509Certificate2.HasPrivateKey) it will also be included in the PFX.  If any private key associated with a certificate in this collection cannot be exported a CryptographicException will be thrown.
* Pkcs7: Returns a BER-encoded PKCS#7/CMS signed data object with detached content and no SignerInfo values.  The X.509 public key certificate representation for each certificate object in this collection will be included in the certificates collection of the signed data object.
* SerializedStore: On Windows, returns the output of https://docs.microsoft.com/en-us/windows/desktop/api/wincrypt/nf-wincrypt-certsavestore with dwSaveAs=CERT_STORE_SAVE_AS_STORE and dwSaveTo=CERT_STORE_SAVE_TO_MEMORY.  PlatformNotSupportedException is thrown on other operating systems.
* SerializedCert: On Windows, returns `null` for an empty collection, otherwise the value built by https://docs.microsoft.com/en-us/windows/desktop/api/wincrypt/nf-wincrypt-certserializecertificatestoreelement for the first object in the collection.  PlatformNotSupportedException is thrown on other operating systems.
* CryptographicException is thrown for all other formats.


So, between those two Export method (group)s:

* Never PEM.
* A private key is included only for Pkcs12/Pfx.
* For Windows-proprietary formats the output is the proprietary binary encoding.
* For standards-based formats the output is the ASN.1 data encoded according to the rules of the standard (Distinguished Encoding Rules (DER) for Cert and Pkcs12; Basic Encoding Rules (BER) for Pkcs7).

**Comment by mairaw** [comment]
Thanks @bartonjs. @owlstead I hope that helps! Closing this issue.

**Comment by owlstead** [comment]
Thanks! You probably saw "some" frustration leaking through while filing the issue. Before nothing was done with the reports. I still think it is important to indicate that private keys, where available, are also exported when exporting to PFX/PKCS#12. That's not in the documentation - but at least it is here in the issue description by BartonJS :)
