### ISSUE TITLE
Coding style for named tuple fields

### ISSUE THREAD

**Issue by dhcgn** [dotnet/docs#7261]
What is the coding style for named tuple fields?

This coding style is not named here:
https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md

Because an unnamed tuples has fields named `Item*` I would deduce PascalCasing but the sample from https://docs.microsoft.com/en-us/dotnet/csharp/tuples contains a mixed style.

For example:

```
var named = (first: "one", second: "two");
var named = (Answer: 42, Message: "The meaning of life");
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bf15268-9d34-cf10-97b9-0b94022c3305
* Version Independent ID: 17728168-48fa-0f5f-0c19-31ae4ce6fdb9
* Content: [Tuple types - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/tuples#feedback)
* Content Source: [docs/csharp/tuples.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tuples.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thanks for the question, @dhcgn. The Tuple* and ValueTuple* types use PascalCasing because they are members of the type's public interface. Typically, unnamed and named tuples in C# are a convenience feature that are used internally only and are not publicly exposed; as the Conclusion section of the [C# tuple types](https://docs.microsoft.com/en-us/dotnet/csharp/tuples#conclusion) article notes, tuples 
> "are most useful for utility methods that are private, or internal. Create user-defined types, either class or struct types when your public methods return a value that has multiple elements." 

In that case, you'd use camelCasing for named tuple fields.

 I hope that this answers your question.  I'll close this issue, since camelCasing is the recommended coding style for internal program elements. If you disagree, please feel free to respond.

**Comment by weitzhandler** [comment]
There should be clear style guidelines when to use pascalcasing and when camelcasing.
