### ISSUE TITLE
Need more detail on docker commands

### ISSUE THREAD

**Issue by simeyla** [dotnet/docs#7293]
This document literally spends more time explaining what a `using` statement and a .NET namespace are than explaining the docker commands. Surely if someone is working with docker they already know the language?

The following needs *much* more explanation:

&gt; docker build -t dotnetapp-dev .
&gt; docker run --rm dotnetapp-dev Hello from Docker

* Where do I run this command from?
* What exactly is a tag? Is this the name of my container? The name of an app? The name of the instance of my dev container?
* Does this command *create* me a container?
* Where does the container live? 
* What is the `.` referring to? The location of the Dockerfile?
* What does `rm` mean? It sounds dangerous!

Anyway the point being this is meant to be about docker basics, and unfortunately I have way more questions now than when I started :-(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ef1481-3b6f-30bf-330d-45400c0a349c
* Version Independent ID: 03a156f7-b178-4d54-503d-26d229f89dcd
* Content: [Learn Docker Basics with .NET Core](https://docs.microsoft.com/en-us/dotnet/core/docker/docker-basics-dotnet-core)
* Content Source: [docs/core/docker/docker-basics-dotnet-core.md](https://github.com/dotnet/docs/blob/master/docs/core/docker/docker-basics-dotnet-core.md)
* Product: **dotnet-core**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by BillWagner** [comment]
ping @Thraka

**Comment by clarenceb** [comment]
The tutorial does assume some basic knowledge of docker and includes some references for further reading.

>    Where do I run this command from?

Open a terminal (e.g. `cmd.exe` on Windows) and `cd` into the directory where you ran the `dotnet new console` command.  Then run the `docker` commands from that directory.

>    What exactly is a tag? Is this the name of my container? The name of an app? The name of the instance of my dev container?

It's a friendly name you can attach to the Docker image that is built.  The image containers everything needed to run your app in a container.  You can add a version to the tag (default is "latest"), e.g. `docker build -t dotnetapp-dev .` produces an image called `dotnetapp-dev:latest` (run the `docker images` command to see this).  But you could also use a specific version tag, like `docker build -t dotnetapp-dev:v1 .` which would create an image called `dotnetapp-dev:v1`.  You can add additional tags to the same image with the `docker tag` command.

    Does this command create me a container?

No, `docker build` creates a Docker image.  `docker run` creates a container.  You can create many containers from the same image, similar to how you can spin up many VMs from the same VM image template.

    Where does the container live?

The container runs on your local machine and is managed via the Docker engine (e.g. Docker Desktop).  You can see running containers by typing `docker ps`.  If the container exits, as in the case of the "hello world" app, then you can type `docker ps -a` to see exited containers (which can be removed manually with `docker rm`).  However, the example used ` docker run --rm` which automatically removes the container when it exists (i.e. when the hello world program terminates).

    What is the . referring to? The location of the Dockerfile?

Yes.  If the Dockerfile was called something else, e.g. Dockerfile.dev then you need to also use the `-f` flag to specify the custom filename.

    What does rm mean? It sounds dangerous!

As described above, it means "Automatically remove the container when it exists".  Otherwise, you need to clean up exited containers manually.  Exited/stopped containers take up some disk space.  A quick way to clean up all exited or stopped containers is with `docker container prune`.

**Comment by Thraka** [comment]
I just published an update to this article which should show up sometime today. Please let me know if it helps. I rewrote everything with a less focus on the app and more focus on docker.
