### ISSUE TITLE
PROBLEM: 样式数据和数据模板

### ISSUE THREAD

**Issue by dawnchan030920** [dotnet/docs#7294]
第2步是直接把代码写在&lt;page&gt;标签里面吗？为什么提示“已多次设置属性Content”？

Translation: Is step 2 of [Style data with data templates](https://docs.microsoft.com/en-us/dotnet/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application#style-data-with-data-templates) written directly in the `<page>` tag? Why prompt "Property Content has been set more than once"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0dc39f7-b153-a46c-3b88-07c8ed2c71bc
* Version Independent ID: 78a14535-9703-e2af-4451-783a7c4c10be
* Content: [Create a WPF application in Visual Studio](https://docs.microsoft.com/en-us/dotnet/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application)
* Content Source: [docs/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by asloppyone** [comment]
不在page那个地方，在APP.xaml那里

**Comment by gewarren** [comment]
> 不在page那个地方，在APP.xaml那里

Translation: Not in the page, in APP xaml.

**Comment by gewarren** [comment]
@Thraka Should we clarify where to insert the XAML?

**Comment by Thraka** [comment]
It is clarified https://docs.microsoft.com/en-us/dotnet/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application#style-controls this says to add it to the app xaml. But, I don't think this would cause the problem. The error is that the property `Content` has been set more than once. So there is some other issue with the xaml.

@1277201882 can you share more information? Can you share your xaml?

**Comment by gewarren** [comment]
@Thraka I think the issue is in reference to this section, which does have a Content attribute.

https://docs.microsoft.com/en-us/dotnet/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application#style-data-with-data-templates

**Comment by Thraka** [comment]
@gewarren This error comes from setting that property twice, either through the attribute or through child content. However, I think the problem is that they have copy/pasted the label into the `<page>` directly.

@1277201882 The label shouldn't be added directly to the page, it was already added in the [#create the ui for expensereport page](https://docs.microsoft.com/en-us/dotnet/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application#create-the-ui-for-expensereportpage) section. Or you have content in the label: `<Label Style="{StaticResource labelStyle}">CONTENT</Label>` and you shouldn't have that there.

We need to see your XAML to really understand where you error is.
