### ISSUE TITLE
Getting Started with F# on .NET Core Improvements

### ISSUE THREAD

**Issue by cartermp** [dotnet/docs#742]
I merged the Getting Started with F# on .NET Core article so that we have something available for folks to took at.  Some feedback that was mentioned was to cut out most of the step-by-step stuff and just list the `project.json` changes supply code to copy/paste.  This would shorten and change the tone of the article, but could be good since it would be less for folks to read through.

I'm also open to other changes as well.

/cc @svick @mairaw @dsyme @enricosada

**Comment by BillWagner** [comment]
This is my personal opinion, so weight it appropriately with other feedback.

I prefer seeing a bit more detail rather than just supplying code to copy and paste. I find that the pure copy / paste articles don't help me learn anything. I get to the end, and I've got a working sample (that's cool). However, I can't extend those techniques to applications I'm building. 

Humans are pretty good at skimming text, so I try to err on the side of more detail rather than less.

**Comment by svick** [comment]
@BillWagner I'm not sure the goal of this article is to teach about details of project.json. That section is just a stopgap until `dotnet new -l fs -t lib` becomes available.

**Comment by cartermp** [comment]
@svick is right here, this is a stopgap until `dotnet new` is updated to have correct template support for F# class library, console app, and test project.  I don't know when that will happen, though.

**Comment by mairaw** [comment]
If it's a stop-gap solution then having the copy and paste only would be appropriate in this case. 
But I agree with @BillWagner that in general we should provide the steps with an explanation of why you're doing that. Then if someone wants just to skip all that and go to the final one, that's fine. That's why I also suggested that we provide the whole sample too so people can just download the whole thing if they want as well.
