### ISSUE TITLE
For FileExists and DirectoryExists unclear

### ISSUE THREAD

**Issue by paul1956** [dotnet/docs#7490]
What happens if a directory or file respectively exists with the desired name.  Also why are declarations in C# for VB functions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43683e65-70ff-74d7-1e43-0086eb3a793a
* Version Independent ID: aeed7219-e831-caa8-78b4-ffb697ef1f2c
* Content: [FileSystem.DirectoryExists(String) Method (Microsoft.VisualBasic.FileIO)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.fileio.filesystem.directoryexists?view=netframework-4.7.2#Microsoft_VisualBasic_FileIO_FileSystem_DirectoryExists_System_String_)
* Content Source: [xml/Microsoft.VisualBasic.FileIO/FileSystem.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.VisualBasic.FileIO/FileSystem.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
@paul1956, the DirectoryExists method return true if a directory with the specified path exists. It is intended to report only whether a directory, and not a file, exists. 

You're probably seeing a C# declaration because you have your language filter set to C#. The syntax shown is based on the language filter. Even though this method is in a "Visual Basic" assembly (Microsoft.VisualBasic.dll) and namespace, it actually is language-independent; it can be called from language that adheres to .NET's common language specification.

I hope that this answers your questions. Since this issue does not have a documentation impact, I'll close it. Feel free to reply if you disagree, however.

**Comment by paul1956** [comment]
What is the behavior of calling DirectoryExists and passing a string that points to a File, or calling FileExists and passing a string pointing to a directory (Return True expected behavior to casual user, Return False as System IO does, Throw Exception). The answer to those two questions is what needs to be documented, it is documented for IO.File.Exists and IO.Directory.Exists.  Yes my language filter was set incorrectly but that does not change the issue.

**Comment by rpetrusha** [comment]
I'll reopen the issue and add it to the backlog, @paul1956. I've you'd like to submit a pull request to modify the documentation, we'd welcome your contribution.

**Comment by paul1956** [comment]
I forked the repo but have no idea how to work with it, I can't even find the files that need to be changed.

What is missing is below 
For FileExists: "If path describes a directory, this method returns false."
For DirectoryExists: "If path describes a file, this method returns false."

**Comment by mikkelbu** [comment]
I think that @paul1956 is right about the wrong languages 
![image](https://user-images.githubusercontent.com/1007631/46310789-96d90d80-c5c0-11e8-8bf6-07d6b7dbab72.png)
and
![image](https://user-images.githubusercontent.com/1007631/46310879-e3bce400-c5c0-11e8-9903-3113cc072721.png)
...
Looking at the code I can (mostly) find references to VB examples in this file.
