### ISSUE TITLE
Need to mention that declaring out variable in `else if` may be incorrect

### ISSUE THREAD

**Issue by imba-tjd** [dotnet/docs#7552]
I think the doc needs to mention the following situation:

```c#
static void Main()
{
    if (false)
        ;
    else if (int.TryParse("123", out var result))
        Console.WriteLine(result);

    Console.WriteLine(result);
}
```

Beginner might be puzzled about why `The name 'result' does not exist in the current context`. Then the doc would explan that if the condition is `true`, the variable will not be declared.

But if the code is like this:

```c#
if (false)
    ;
else if (int.TryParse("123", out var result))
    Console.WriteLine(result);
else Console.WriteLine(result);
```

It would not cause error. So... mention this, either? I don't know whether my proposal is redundancy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f6c8480-77a7-7505-5224-0efe15b9b755
* Version Independent ID: 993250d1-108c-ab1a-886e-ca1bfa9104c7
* Content: [out parameter modifier (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/out-parameter-modifier)
* Content Source: [docs/csharp/language-reference/keywords/out-parameter-modifier.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/out-parameter-modifier.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@imba-tjd I'm going to close this. Your examples have run into some of the more detailed rules around scoping in C#.  Let's start with a simpler example:

```csharp
static void Main()
{ // This brace opens the scope for result.
  if (int.TryParse("123", out var result))
        Console.WriteLine(result);

    Console.WriteLine(result);
} // This brace closes the scope for result.
```

That compiles cleanly, because `result` has a scope that matches the scope of the `if` statement in which it is declared. That's the scope of the `Main` method.

Now, let's look at your first example:

```csharp
static void Main()
{
    if (false)
        ;
    else if (int.TryParse("123", out var result))
        Console.WriteLine(result);

    Console.WriteLine(result);
}
```

That doesn't compile becauset the scope of `result` is now the scope of the `else` clause in the first `if` statement. Adding the following braces (which doesn't change any scoping rules) should make this more clear:

```csharp
static void Main()
{
    if (false)
    {
        ;
    }
    else
    { // This braces opens the scope for result.
        if (int.TryParse("123", out var result))
        {
            Console.WriteLine(result);
         }
    } // This brace closes the scope for result.
    Console.WriteLine(result);
}
```

Finally, let's look at your final example:

```csharp
static void Main()
{
    if (false)
        ;
    else if (int.TryParse("123", out var result))
        Console.WriteLine(result);
    else Console.WriteLine(result);
}
```

As above, this becomes more clear by adding braces to make the nested scopes more clear:

```csharp
static void Main()
{
    if (false)
    {
        ;
    }
    else
    { // This brace opens the scope for result.
        if (int.TryParse("123", out var result))
        {
            Console.WriteLine(result);
         }
        else
        {
            Console.WriteLine(result);
        }
    } // This scope closes the scope for result.
}
```

These rules are covered in the C# language reference, and in the spec.

**Comment by imba-tjd** [comment]
@BillWagner Thank you for explaining my question. I also mean whether we could add a hint about this. If you consider the current doc is enough, it's also ok.
