### ISSUE TITLE
Self contained packaging produces unknown dlls

### ISSUE THREAD

**Issue by kudlatiger** [dotnet/docs#7553]
I see dll entitled "sos_amd64_amd64_4.6.26628.05.dll" when publishing .net core application in self contained mode, what does this do? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a17d5d-5f6e-d6bc-324b-af411a42ccb8
* Version Independent ID: f58588d7-70f6-aa32-5c6d-ac3e7d72d87c
* Content: [.NET Core Application Deployment](https://docs.microsoft.com/en-us/dotnet/core/deploying/)
* Content Source: [docs/core/deploying/index.md](https://github.com/dotnet/docs/blob/master/docs/core/deploying/index.md)
* Product: **dotnet-core**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
Hi @kudlatiger 

I did a quick search around and found https://docs.microsoft.com/en-us/dotnet/framework/tools/sos-dll-sos-debugging-extension and some other stuff that talk about SOS. It seems these are debugging helpers. I found another reference: https://bret.codes/net-core-and-windbg/

I'm guessing that it's named `sos_amd64_amd64_4.6.26628.05.dll`  because it's the sos.dll file but named to be platform/version specific.

If this does not answer your question, please feel free to reopen/comment on this issue. Thanks!
