### ISSUE TITLE
SignedCms.ComputeSignature() not prompting for certificate (doc says otherwise)

### ISSUE THREAD

**Issue by krwq** [dotnet/docs#7575]
[MSDN doc](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.pkcs.signedcms.computesignature?view=netframework-4.7.2) mentions that `SignedCms.ComputeSignature()` does prompt for certificate. This is not true, non of the .NET framework versions do - you will get an exception in such case.

Note that this only applies to parameterless constructor but applies to all .NET versions including Core.
There are more than one mentions on the doc page that this happens. Remarks section seems like it applies to all of the overloads but that's not the case for the parameterless constructor.

cc: @bartonjs

**Comment by bartonjs** [comment]
I assume that we would want to document the specific exception, so we should write it down here.

**Comment by krwq** [comment]
For full framework the exception is InvalidOperationException for corefx (arguably a bug) is PlatformNotSupportedException (See: https://github.com/dotnet/corefx/issues/32171).

**Comment by rpetrusha** [comment]
@krwq and @bartonjs, what is the status of this issue in view of dotnet/corefx#32226? In what version of .NET Core does the behavior of ComputeSignature change from throwing PlatformNotSupportedException to throwing InvalidOperationException if  CmsSigner.SignerIdentifierType does not equal SignerIdentifierType.NoSignature? Both behaviors should be documented.
-  The documentation should note that the silent parameter is ignored on .NET Core, shouldn't it?

**Comment by bartonjs** [comment]
I believe (by code inspection) that the `silent` parameter has no effect on either .NET Core or .NET Framework.  Though .NET Framework certainly keeps it around a lot longer before ignoring it.

The zero-argument overload succeeds<sup>*</sup> if SubjectIdentifierType.NoSignature was specified via a constructor overload, and otherwise throws InvalidOperationException.

<sub>* Well, it succeeds on the first call.  Maybe.  It'll throw a CryptographicException if any ComputeSignature overload has already been successfully called, or Decode was successfully called.</sub>
