### ISSUE TITLE
Pubs sample database is very out of date, I offer my updated version

### ISSUE THREAD

**Issue by manukautech** [dotnet/docs#7590]
I teach web dev. I was creating an ASP.NET Core 2.1 practical test for my students using the "pubs" database and a lot of distracting issues appeared like EF7 rewriting the field names in modern style. AI?! So I gave old "pubs" a modern makeover. Singular names for tables eg "titles" becomes "Title". Other identifiers following modern naming conventions eg "title_id" becomes "TitleId". I did however keep some of the "pubs" weirdness because newbie students should get some exposure to real life messiness. Therefore in table "Author" we have "Firstnames" and "Lastname" while in table "Employee" we keep "Firstname", "MiddleInitial", and "Lastname". Lol! I am happy to contribute this just tell me where to send it! Or should I give it its own little github repo?

Regards, John Calder
Senior Lecturer in Digital Technologies
Manukau Institute of Technology, NZ

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c40be1d-8249-c115-7c05-5b9f6d69f95f
* Version Independent ID: 2d9814af-f6fc-dc72-13a7-6bcd1dd7d84c
* Content: [Downloading Sample Databases](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/linq/downloading-sample-databases)
* Content Source: [docs/framework/data/adonet/sql/linq/downloading-sample-databases.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/sql/linq/downloading-sample-databases.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by douglaslMS** [comment]
@manukautech Professor Calder, first of all, I apologize for the slow response. Your issue came in while I was on vacation, it does not automatically get assigned to me, and I confess that I overlooked it.

We don't really have a place to host a community contribution like you're proposing, although I recognize the potential value. We also would not want to assume the responsibility for maintenance at this point. Personally, I always saw the value in Northwind and Pubs - during my years in Microsoft Support, I used them every day in test, solutions, and examples. 

I'm sure your updated Pubs database is of great value to your students, and regret that I don't know how we could help you to make it more broadly available. As one small improvement, I will update the links on this page.

**Comment by douglaslMS** [comment]
@manukautech FYI I'm am investigating further whether we might have a place to host your new and improved PUBS database.

**Comment by douglaslMS** [comment]
@manukautech Professor Calder, it's possible that the owners of the [SQL Server Samples repo](https://github.com/Microsoft/sql-server-samples) would be willing to host your PUBS database there. Presumably this would require a README to accompany it. I'm not sure whether they would want an MDF, a BAK, or scripts. In any case, please contact the email address at the bottom of the repo home page. Thank you and best wishes.
