### ISSUE TITLE
Document known differences between .NET Framework and .NET Core

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/docs#762]
I couldn't find any specific documentation about major diferences between .NET Framework and Core, but some of the topics that should be covered:
- Replacement for AppDomain's scenario of assembly isolation
- Replacement for AppDomain's scenario of remoting

There are probably other topics, but I encountered these two recently and figuring out what should be done to replace it was difficult. Samples for it would be helpful.

**Comment by mairaw** [comment]
I think we talk about these differences on the porting docs but we don't have a top-level topic on these differences: https://docs.microsoft.com/en-us/dotnet/articles/core/porting/libraries

**Comment by svick** [comment]
There is also [*Porting to .NET Core*](https://blogs.msdn.microsoft.com/dotnet/2016/02/10/porting-to-net-core/) on the .Net Blog, which contains a section on what you should use instead of discontinued technologies like `AppDomain`.

**Comment by cartermp** [comment]
Moving to backlog for now until we get more clarification on API changes.

**Comment by mairaw** [comment]
@terrajobst @weshaggard would you guys be the right people to talk about this issue?

**Comment by weshaggard** [comment]
@jkotas would probably be the best person to talk with on this subject but I don't think we really have any clear cut guidance for replacements in this space.

**Comment by jkotas** [comment]
Remoting: Doc update tracked by https://github.com/dotnet/corefx/issues/18394. The issue has some discussion about the options.

Assembly isolation: AssemblyLoadContext is the replacement. Documentation in https://github.com/dotnet/coreclr/blob/master/Documentation/design-docs/assemblyloadcontext.md. https://blogs.msdn.microsoft.com/dotnet/2016/05/27/making-it-easier-to-port-to-net-core/#comment-77765 and https://github.com/dotnet/coreclr/issues/295#issuecomment-75266259 has some more context.

**Comment by BillWagner** [comment]
There is good source material here on the [corefx wiki](https://github.com/dotnet/corefx/wiki/ApiCompat)

**Comment by mairaw** [comment]
@terrajobst @weshaggard would you guys be the ones helping with this request?

**Comment by mairaw** [comment]
We do cover higher level differences at https://docs.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server

**Comment by mairaw** [comment]
@sdmaclea it's assigned to you. For milestones, we use specific sprints. I'll add you to the docs-write team, so you can make changes to label/issues as needed.

**Comment by swythan** [comment]
Will there be a document listing all the changes that have been made in .Net Core but not ported to  .Net Framework for compatibility reasons? If I was even considering doing a port I would want to see that list.

I'm thinking of things like the change to floating point parsing & formatting that was announced today. Without a central list of these things it's down to each developer to search around for blog posts, GitHub issues, etc.
Us NetFX developers are used to having that high AppCompat guarantee, so it's already going to be a jarring experience coming over to corefx's brave new world. The more *undocumented* "small" gotchas that are waiting for us, the worse it will be.

**Comment by sdmaclea** [comment]
@swythan 

We have https://docs.microsoft.com/dotnet/standard/analyzers/portability-analyzer which will 
analyze the actual API usage of your app and generate a portability report for any port target

There is also an interactive list in the https://apisof.net/catalog/ if you want to browse.

**Comment by swythan** [comment]
Those are for API changes, not behavioural charges. 

My issue is that .Net Core is accepting changes that .Net Framework wouldn't because they might break existing code. That's fine, but if I'm porting from one to the other I'd really like to know where I should be testing.

**Comment by cartermp** [comment]
@swythan 

> Will there be a document listing all the changes that have been made in .Net Core but not ported to .Net Framework for compatibility reasons? If I was even considering doing a port I would want to see that list.

Realistically, no. .NET Core is the future of .NET and as such will be the only thing that gets new capabilities. So it's best to assume that nothing new will be backported.

**Comment by sdmaclea** [comment]
@swythan

> I'd really like to know where I should be testing.

We try to maintain backward compatibility where possible. The changes in the API surface are obviously the primary change. 

There are a few APIs which are _implemented_ by throwing `PlatformNotSupportException`. The https://docs.microsoft.com/en-us/dotnet/standard/analyzers/api-analyzer will help with those.

There are subtle backward compatibility behavioral differences. Most of them are unintentional so generating a list would prove difficult.

One of the areas which might be worth noting is in the area of locating assemblies.  .NET Core does not support a GAC and the loading model is different. Luckily these problems fail dramatically, which simplifies testing.

Certainly all the quirk support has also been removed.

Two of the most painful for customers are mentioned above, (but these are API changes)
+ Replacement for AppDomain's scenario of assembly isolation
+ Replacement for AppDomain's scenario of remoting

When porting, a fairly exhaustive test is probably in order.

**Comment by swythan** [comment]
> Realistically, no. .NET Core is the future of .NET and as such will be the only thing that gets new capabilities. So it's best to assume that nothing new will be backported.

I know that nothing else is being back-ported. I accept that. 

What I would really like to see is a list of known _behavioural_ differences between .Net Framework and .Net Core. 

Here's my approximate position:

1. Company uses .Net Framework for years. Gets used to the high levels of compatibility between releases and long support cycles.
2. .Net Core is released but company doesn't adopt it (even for new projects) due to real/perceived issues.
3. Lots of blog posts about new features, bug fixes & performance improvements in .Net Core.
    * **ALL** of them say "We won't be back-porting this to .Net Framework because **it would/might break compatibility**"
4. .Net Core 3.0 comes along and .Net 5 is announced. Looks like now might be the time to port stuff over.
5. I'm now left thinking: " I wonder how many of those fixes that were made _actually_ broke compatibility in a way I'm going to care about?"

I'm thinking of "little stuff" like the double parsing stuff I mentioned above; the recent changes to exception stack trace output (I think); things like that. They aren't going to show up in a compatibility scanner.

Without a central list, _everyone_ that does a port is going to have to work this all out for themselves by digging through release notes and GH issues. I believe there was a presentation at NDC (?) this week where they said (I paraphrase): "The compatibility issues are only going to get worse, so port now."
 
I personally feel like it _is_ Microsoft's duty to help out with this, if they want developers to get off NetFx.

**Comment by cartermp** [comment]
Unfortunately, it's impossible to document what you are asking for. Even switching your project to use PackageReference can result in semantic differences that are impossible to enumerate. There are some major pieces we document (i.e., no support for Windows Workflow) but every single behavioral difference is not possible. Doubly so if you're running your application on something other than Windows. For example, the networking libraries call into different things based on what platform you're on, leading to performance characteristics that are not identical across OS's. Since these are also moving targets, whatever we exhaustively documented at some point in time are likely to be very different just a few months later. That sort of situation would only make things worse for people looking to move to .NET Core, because then there's incorrect documentation about something.

**Comment by swythan** [comment]
I seem not to be making my point effectively. @sdmaclea has made me think of a better way of expressing it:
> Certainly all the quirk support has also been removed.

Could we have a list of _known_ changes for which .Net Framework would have (probably?) added a Quirk option?

I'm not looking for an exhaustive list of everything that _might_ have a compatibility  effect. I'm looking for a list of changes where the .Net Core team _actively chose_ that a breaking change was OK (e.g. in the interests of the future of the platform).

At the risk of diluting my point (and I don't want to get in a semantic argument), it's not _impossible_ to generate an exhaustive list, just likely to be _very_ expensive. The sort of thing I'm asking for wouldn't be as hard as that, but still might require looking through a lot of history of where these decisions were made. That's probably still expensive, but my employers (and many others) do pay Microsoft tens of thousands a year for developer tools. Normally the documentation is excellent.

Another thought: Does anyone maintain a list of functional differences between different .Net Standard implementations? Is there a compliance test suite? What I'm asking for is similar to that.

**Comment by jkotas** [comment]
> Could we have a list of known changes for which .Net Framework would have (probably?) added a Quirk option?

The .NET Framework servicing policy for last number of years has been that any observable behavior change has to be quirked (except for security fixes). .NET Core contains a lot (many hundreds) bug fixes that are observable behavior changes. Most of them would need quirks in .NET Framework. I doubt that a list of many hundreds of subtle differences would be useful to anybody. 

We used to run .NET Core corefx tests against .NET Framework and have tests annotated with differences. We have stopped doing that recently since we have maximized what we can bring over from .NET Framework and this coverage was not useful anymore. https://github.com/dotnet/corefx/pull/37972/ is PR that deleted a bulk of this special casing. You can get the idea about the amount and nature of the .NET Core and .NET Framework differences from this PR.

We had other customers asking for a list of changes with high breaking potential. This list should be much smaller and more manageable. It would have changes like the floating point parsing/formatting changes. Note that such list is applicable for both going from .NET Framework to .NET Core, as well as for going from older version of .NET Core to newer version of .NET Core. @swythan Would having list like this address your concern?

CoreCLR repo has a breaking-change label that we use to tag changes with high breaking potential:
https://github.com/dotnet/coreclr/issues?utf8=%E2%9C%93&q=label%3Abreaking-change . It is very low overhead way to track this. However, this convention is not consistently followed across .NET Core repos today - something that would need to be fixed to make this work.

**Comment by swythan** [comment]
@jkotas 
> We had other customers asking for a list of changes with high breaking potential. This list should be much smaller and more manageable. It would have changes like the floating point parsing/formatting changes. Note that such list is applicable for both going from .NET Framework to .NET Core, as well as for going from older version of .NET Core to newer version of .NET Core. @swythan Would having list like this address your concern?

**Yes, that's exactly what I'm asking for.** Thank you. I also agree about it being just as useful when moving between versions of .Net Core. 

Given that you think think the list of observable behaviour changes would be hundreds of items long, I can see that such a would probably not be useful enough to justify the expense of creating it. A link to dotnet/corefx#37972 and that [breaking change query](https://github.com/dotnet/coreclr/issues?utf8=%E2%9C%93&q=label%3Abreaking-change) (or this discussion) might be of help to those that want more detail, perhaps?

**Comment by jkotas** [comment]
> a list of changes with high breaking potential

@danmosemsft @karelz Does it sound reasonable to you to use `breaking-change` label to tag issues and changes with high breaking potential in CoreFX repo? It is in use for CoreCLR repo already. (Or suggest an alternative way how we can keep track of changes with high breaking potential.) Once we agree on the plan, I will update the repo documentation with it.

**Comment by sdmaclea** [comment]
This is bigger and broader than what I will take on.  I will remove my assignment and open separate issues for the pieces I will tackle.

**Comment by terrajobst** [comment]
> @danmosemsft @karelz Does it sound reasonable to you to use `breaking-change` label to tag issues and changes with high breaking potential in CoreFX repo?

Moving forward, I'd say yes. There is another effort right now to formalize our breaking change process between .NET Core versions. I've asked to include .NET Framework as an explicit section in that guidance. While we're not shooting for a 100%, we do try to maintain ABI compat whenever possible. Behavior is much more of a gray area though and tracking that is hard. I'm totally OK with tracking intentional breaking changes.

**Comment by danmosemsft** [comment]
Yes, labeling sounds like a good idea. @terrajobst do you want to send a mail to corefx users (the area owners alias)?

**Comment by IEvangelist** [comment]
Closing this issue as it is covered here:
https://docs.microsoft.com/en-us/dotnet/core/porting/net-framework-tech-unavailable
and here:
https://docs.microsoft.com/en-us/dotnet/core/compatibility/

**Comment by swythan** [comment]
@IEvangelist @gewarren 
It's a shame that the breaking-change PR searches that are linked to from the docs added in #18155 don't actually return much useful info. For example, I don't think the floating point parsing/formatting changes change I mentioned above are in that list.

**Comment by gewarren** [comment]
@swythan Are these the changes you are referring to?

https://docs.microsoft.com/en-us/dotnet/core/compatibility/corefx#floating-point-formatting-and-parsing-behavior-changed

**Comment by swythan** [comment]
> @swythan Are these the changes you are referring to?
> 
> https://docs.microsoft.com/en-us/dotnet/core/compatibility/corefx#floating-point-formatting-and-parsing-behavior-changed

Yes! Those pages are exactly what I wanted! 🎉🤦🏻‍♂️ 

In my defence I'm on a phone, so when I followed the link in the comment from @IEvangelist I only saw the guidance page, not all the sub pages with the actual lists of breaking changes. Once I knew the page existed I spotted the Table of Contents button and I'm a happy camper now.

If I was being really picky I'd point out that the NetFX to NetCore page mostly only lists WinForms issues, but most other changes will be covered elsewhere in these pages, though, so that's OK. 

Having these lists available will be very useful when porting. Thanks to everyone who worked on them.

**Comment by gewarren** [comment]
@swythan Oh good! Yes, the Framework -> Core page started its life as WinForms only, which is why it seems heavily focused on WinForms. It's only in the last few months we've expanded its scope, and it's a work in progress. We also have the APIs that always throw PNSE on .NET Core documented here: https://docs.microsoft.com/en-us/dotnet/core/compatibility/unsupported-apis
