### ISSUE TITLE
Document how to use new configuration system

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/docs#763]
For people coming from .NET Framework, there is a gap of how to do configuration when they are used to app.config. There should be documentation and an example of how to replace it.

**Comment by BillWagner** [comment]
We need to determine how this will work in the .NET Standard 2.0 world. 

@richlander who owns these types?

**Comment by themooserooster** [comment]
Has there been any progress on this front? Documentation exists for ASP.NET Core configuration, but not vanilla console apps in .NET Core.

**Comment by mairaw** [comment]
@twsouthwick @richlander who should we talk to to get this one done?

**Comment by mairaw** [comment]
@twsouthwick @richlander who can help with this one?

**Comment by mairaw** [comment]
@guardrex did anyone work with you to get the https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration done? I still don't know who would help us here @richlander

**Comment by guardrex** [comment]
Work with me? ... u mean the engineer reviewers? ... it was Hao and Chris ... and the docs cats.

https://github.com/aspnet/Docs/pull/8050

The stuff we have should&dagger; apply to both scenarios.

&dagger;should ... there was an ask on the issue from @tillig ( https://github.com/aspnet/Docs/issues/7102#issuecomment-399602285 ) to do just what @twsouthwick and @themooserooster are asking about. However, we may need to take another look and see how well that round of updates met this goal. The problem at the time is that the topic was *sooooo BAD* that this wasn't really the top priority for that round of updates. Therefore, let's take another look. I'll look now and ping back in a few minutes with a quick assessment.

**Comment by guardrex** [comment]
Analysis: We didn't resolve the concerns laid out here (or by @tillig) on the last round of updates to the ASP.NET Core *Configuration* topic. We can certainly resolve this issue with further updates (or a new topic, of course).

The primary focus of the last round of *Configuration* topic updates was to contextualize configuration for web apps to help web app devs use configuration providers in their apps. The last round of updates took a lot of the guesswork out of answering questions like, _How to I wire up configuration providers in my **_web app_**?_

We have a gorgeous Razor Pages sample app now (although I shouldn't say that about *my own sample* lol). We retained the `WebHostBuilder` examples in the topic because `CreateDefaultBuilder` might not be on the developer's path. However, we shed the console app examples, and that made matters worse for a broader audience.

Two possible solutions jump right out:

1. Hit the topic again with further updates. Either (a) roll console app examples back into each section alongside `CreateDefaultBuilder` and `WebHostBuilder` examples, or (b) add a section at the bottom of the topic that pertains to using the config providers in console apps.
1. New topic ... and it might not even go in the aspnet/Docs repo. Maybe it's over here, where it more broadly applies to .NET Core apps. I can probably write this up by cloning what we have and refactoring the examples/sample app from web app(s) to one or more console apps. I realize that this would lead to some duplication of content across the repos; however, web app devs probably really like what we did on the last round of updates to the *Configuration* topic. Post updates, it really explains what its *title says it will explain*: Configuration in **_ASP.NET_** Core.

**Comment by guardrex** [comment]
@mairaw I can "volunteer" (with permission :smile:) to make a version that applies broadly beyond web apps. Let me know if you want to explore that option. I don't think it would take very long ... no more than a day for the 1st draft.

**Comment by tillig** [comment]
I think it would be good to have some docs that both explain more generally the use of configuration in apps and maybe go a little more into the use of specific providers. A lot of the questions we get on the Autofac project, for example, are around how XML config works in the new world, and that doesn't get touched on too much in the ASP.NET Core related config docs. ("I used to have web.config or app.config... now what do I do?" Not even with respect to Autofac related config, but configuration in general. Folks used to the old stuff have no info on how to transition.)

Examples of array binding in the new docs show in-memory (helpful for tests but not much else) and JSON, but not really XML, INI, or other providers. Examples on overriding would also be helpful (again, based on questions I've seen from Autofac users).

Oh, and thanks for the reference link at the bottom! ;)

**Comment by guardrex** [comment]
I'm limited in how much time I can spend given our backlog. What I can do (with permission) is take the current topic at  https://docs.microsoft.com/aspnet/core/fundamentals/configuration and create a version aimed at covering config for non-web apps with a set of small samples more like what it used to have ... console apps. One day ... I think. However, no new coverage, per se.

Alternatively, we could just add console app samples to accompany the existing topic (perhaps with **some**&dagger; additional language).

**some**&dagger; == That topic is kind'a crazy big. I'm not excited about making it even *longer*.

Whoever does the work and wherever it ends up, the expansions you describe (e.g., more/better XML coverage) are things I definitely want to put an 👁 on for possible inclusion in the aspnet/Docs version where they make sense for web devs.

**Comment by guardrex** [comment]
@jwisener 

> docs are a mess and very confusing

That's not quite what we were going for ... *obviously*. Some of what you're raising will generate some issues to improve. Unfortunately, we don't know about many doc issues until someone pings us, but we're good about getting updates into the docs quickly. When you spot issues with any of the topics, there's a **Content feedback** button at the bottom of them. Send the feedback using that button, because it tags your comments to the topic you're looking at.

1. I assume your app is calling `CreateDefaultBuilder`: The appsettings environment file overrides the non-environment file. Ref source: https://github.com/aspnet/MetaPackages/blob/master/src/Microsoft.AspNetCore/WebHost.cs#L169-L170 `CreateDefaultBuilder` is described in the [Web Host](https://docs.microsoft.com/aspnet/core/fundamentals/host/web-host#set-up-a-host) topic. I've opened https://github.com/aspnet/Docs/issues/8920 to clarify that the order of config providers shown for setting up a host in the topic is the order that the config providers are called and thus the order that they override. There is a great deal more info on config in general in the [Configuration](https://docs.microsoft.com/aspnet/core/fundamentals/configuration/) topic, but you might want to wait 1-2 days before really diving into it ... we're doing a significant update on that topic right now. You can track the changes on https://github.com/aspnet/Docs/pull/8918.

2. Changing the env var in the portal should trigger a restart ... thus trigger your app to reload and consume the env var. The section of the Azure topic that pertains to this isn't detailed enough. I've opened https://github.com/aspnet/Docs/issues/8919 to address it. Are you sure you're clicking the **Save** button after you make your app setting change in the portal?

3. Yes, the defaults (actually, these have always been the defaults IIRC) for the environment OOB are *Development*, *Staging*, and *Production*. Of course, you can have your own additional environments if you require them. They are meaningful in the sense that startup code in an app based on one of the templates is set up to rely on the environment either being *Development* or not *Development* to add middlewares to the processing pipeline in `Startup.Configure`. See the [Environments](https://docs.microsoft.com/aspnet/core/fundamentals/environments) topic for more info.

> But when we try it doesn't seem to work properly.

Need more info+details on what you were doing and what behavior didn't happen.
