### ISSUE TITLE
Unable to build after following content to step 6

### ISSUE THREAD

**Issue by SuperCool83** [dotnet/docs#7643]
I was unable to build after following this tutorial through to step 6.
I have a list of Errors that focus on the fact that the ResetConsole() method is not being reached.  Somehow the declaring of the method is not accurate.
Is there any help that can be provided?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a19d334e-f53b-118a-7323-f81e86f73d3f
* Version Independent ID: c85171ff-7df3-2738-5ee1-4a8223aa680b
* Content: [Consuming a .NET Standard library in Visual Studio 2017](https://docs.microsoft.com/en-us/dotnet/core/tutorials/consuming-library-with-visual-studio?tabs=csharp)
* Content Source: [docs/core/tutorials/consuming-library-with-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/consuming-library-with-visual-studio.md)
* Product: **dotnet-core**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by SuperCool83** [comment]
solved it this way, perhaps this is required?
Could you explain the difference between these.

I did copy and paste the Program from the page and it wouldn't build but this builds and works fine

`using System;
using UtilityLibraries;

class Program
{
    static void Main(string[] args)
    {
        int row = 0;
        do
        {
            if (row == 0 || row >= 25)
                row = ResetConsole(row);
                

            string input = Console.ReadLine();

            if (String.IsNullOrEmpty(input)) break;

            Console.WriteLine($"Input: {input} {"Begins with uppercase? ",30}: " +
                $"{(input.StartsWithUpper() ? "Yes" : "No")}\n");
            row += 3;

        } while (true);
        return;
    }
        // Declare a ResetConsole local method
       public static int ResetConsole(int _row)
            {
            if (_row > 0)
            {
                Console.WriteLine("Press any key to continue...");
                Console.ReadKey();
            }

            Console.Clear();
            Console.WriteLine("\nPress <Enter> only to exit; otherwise, enter a string and press <enter>:\n");
            _row = 3;
            return _row;
        }


    }
`

**Comment by rpetrusha** [comment]
@SuperCool83, you weren't able to compile the original version of the example because the version of the C# compiler that you were using doesn't support [local functions](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/local-functions), which were introduced in C# 7.0; when you rewrote ResetConsole as a standalone method, you were able to compile. Since .NET Core 1.0 supported C# 7.0, that suggests that you weren't using .NET Core to develop the application that consumed the library. Is that the case? 
I'm going to close this issue, since the code does compile when using C# 7.0 and later compilers. But feel free to respond if you have any questions or need guidance.

**Comment by SuperCool83** [comment]
That is the case,

Thank you for your helpful response.

Great that the new functionality exists in Core.
