### ISSUE TITLE
How to use GetFile(string)

### ISSUE THREAD

**Issue by lm28** [dotnet/docs#7743]
How does one use the first example (GetFiles(String))….I try to pass my folder path as string but the 'args' is wanting some information?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be5663f7-3d2a-e997-7b92-be71df72f101
* Version Independent ID: 111b99c7-202a-c2ec-9a88-ae3cf4836309
* Content: [Directory.GetFiles Method (System.IO)](https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.getfiles?redirectedfrom=MSDN&view=netframework-4.7.2#System_IO_Directory_GetFiles_System_String_System_String_)
* Content Source: [xml/System.IO/Directory.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/Directory.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
As long as you're passing a valid directory path, @lm28, the method should work reliably. For some additional information on file and directory paths, see [File path formats on Windows systems](https://docs.microsoft.com/dotnet/standard/io/file-path-formats). If you are continuing to have difficulty, please let us know the argument that you're passing to the method. In the meantime, since I don't believe that your question points to a problem in the documentation, I'll close this issue.

**Comment by lm28** [comment]
Hi @rpetrusha I copied the code that was in the article. 
I was passing the path (as a string) to the string variable, (as per the the 'File Path Formats on Windows systems' link that you sent to me), but my problem was that VS would not compile/run my solution because it was looking for something to be passed to 'args'?
I'd like to try it again but now I don't know how to find that article again.
