### ISSUE TITLE
Acronyms and abbreviations

### ISSUE THREAD

**Issue by msgtmark777** [dotnet/docs#7759]
Most intelligent people use the full meaning of an abbreviation or acronym the first time it is used in a document followed by the acronym or abbreviation in parenthesis to insure everyone understands what the abbreviation or acronym is meant to specify in a SPECIFIC document!  Of course, no one ever said that the highly educated people at Microsoft are actually intelligent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dad3ebd2-7e88-2dc5-5470-caa78b63bcbe
* Version Independent ID: e8ced49b-8d72-5af2-38c7-847b58e30ada
* Content: [DataContext.ExecuteMethodCall(Object, MethodInfo, Object\[\]) Method (System.Data.Linq)](https://docs.microsoft.com/en-us/dotnet/api/system.data.linq.datacontext.executemethodcall?redirectedfrom=MSDN&view=netframework-4.7.2#System_Data_Linq_DataContext_ExecuteMethodCall_System_Object_System_Reflection_MethodInfo_System_Object___)
* Content Source: [xml/System.Data.Linq/DataContext.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.Linq/DataContext.xml)
* Product: **dotnet-api**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by rpetrusha** [comment]
Thanks for pointing out our excessive fondness for acronyms, @msgtmark777. CLR here is an abbreviation for common language runtime, and it really shouldn't have been used in the first place, since at best it's marginally accurate. These are .NET methods or managed methods. I've opened dotnet/dotnet-api-docs#531 to remove mention of CLR.
