### ISSUE TITLE
Tutorials: Immutable Collections

### ISSUE THREAD

**Issue by cartermp** [dotnet/docs#776]
Cross-linking from here: https://github.com/dotnet/corefx/issues/5165

There is a need to have a good tutorial on how to use immutable collections.  While we'll eventually have an API reference story in place, the conceptual content will still be lacking.

Let's see if we can pin down the key stuff to document.

**Content to cover:**
- [ ] Introduction, why immutable collections, what are they good for
- [ ] Showing how to use immutable arrays, dictionaries, hash sets, lists, queues, sorted dictionaries, sorted sets, and stacks
- [ ] Interoperating with the mutable collections
- [ ] Interoperating with F# immutable collections (I'd be more than happy to collaborate here)
- [ ] Overview of how they're implemented and how their space/time complexity trades off with the mutable collections

**Place where this lives:**

There are a few candidates here.  The [C# Guide](https://docs.microsoft.com/en-us/dotnet/articles/csharp/index) is an option, however there's certainly no limitation on language when using these data structures.  These could also fit under the [.NET Standard section](https://docs.microsoft.com/en-us/dotnet/articles/standard/index).

/cc @BillWagner @stephentoub

**Comment by mairaw** [comment]
Thanks for creating this @cartermp. I think this fits better with the Standard guide vs. one of the languages.

**Comment by eriawan** [comment]
@cartermp 

This is just my own 2 cents:

- I prefer to have the doc on separate repo so not in the same repo as.NET Core doc. Because they are focusing on different intention, although CoreFX is actually an implementation of CoreCLR from my quick simplified standpoint. So .NET Core should focus on intro, detailed architecture, code samples, showcasing samples with ASP.NET Core. Then .NET CoreFX should focus only on .NET BCL like the existing online MSDN Library of .NET 4.6 Class Library
- If the CoreFX has their own repository, the starting point should be under docs.microsoft.com but on different folder or subdomain.
- If the doc repo is decided to be on the same .NET Core doc repo, this is OK from the perspective of it's a single point to start to look for .NET Core and CoreFX class libraries, just like the existing MSDN Library of .NET Class Library. But this could be hard to do in the long run, as .NET Core and CoreFX are to me different intent, as I mention above.

**Comment by BillWagner** [comment]
Thanks @cartermp for starting this conversation.

I agree that the .NET Standard section is the best home. The language sections should be for language specific items, and these collections are surfaced to all the languages. 

Where there are language specific behaviors, that's where the language sections come in.

@eriawan Thank you for your thoughts. If we could, we'd probably rename the core-docs repo, as it does now encompass .NET Standard, .NET Core, and the major languages. Unfortunately, changing a repo name is not supported. Everything does hang off of docs.microsoft.com. Right now, core, standard, and each language does have its own sub-folder. Hopefully, that's close to what you are recommending above.

**Comment by atlemann** [comment]
Any progress on this? I would like to start using these collections, but I cannot find any documentation on the interwebs on how these collections work.
