### ISSUE TITLE
Why does order by tend to assign a smaller value to the character '_' over '0'

### ISSUE THREAD

**Issue by tunafish-msft** [dotnet/docs#7846]
Upon running the following snippet
                string s1 = "ss_ss";
		string s2 = "ss0ss";
		List&lt;string&gt; s = new List&lt;string&gt;() {s1,s2};
		List&lt;string&gt; ordered = s.OrderBy(x=&gt;x).ToList();
		for (int i = 0 ;i &lt; 2; i++)
		Console.WriteLine(ordered[i]);}}

output:
ss_ss
ss0ss

Expected:
ss0ss
ss_ss

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778faaf9-9b35-44e3-befb-56bc19eae568
* Version Independent ID: c9a682ac-3e9b-a1bd-aa59-b31ae950f9dc
* Content: [Enumerable.OrderBy Method (System.Linq)](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.orderby?view=netframework-4.7.2)
* Content Source: [xml/System.Linq/Enumerable.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Linq/Enumerable.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by svick** [comment]
Why do you expect that `_` should be sorted after `0`? Is it because it has lower Unicode code point (they're U+005F LOW LINE and U+0030 DIGIT ZERO)? That's not how the default culture-aware comparison works. [As far as I can tell](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.compareoptions?view=netframework-4.7.2#remarks), the general rule is that nonalphanumeric symbols come before alphanumeric characters (though there are exceptions).

If you want to compare strings based on the Unicode code points of their characters, you should use [ordinal comparison](https://docs.microsoft.com/en-us/dotnet/api/system.stringcomparer.ordinal?view=netframework-4.7.2#System_StringComparer_Ordinal):

```c#
List<string> ordered = s.OrderBy(x=>x, StringComparer.Ordinal).ToList();
```

**Comment by tunafish-msft** [comment]
Thank you for this explanation! I did assume the default case would be unicode based, and turns out I was wrong.

**Comment by tunafish-msft** [comment]
Thank you for this explanation! I did assume the default case would be unicode based, and turns out I was wrong.
