### ISSUE TITLE
Questions from a newbie

### ISSUE THREAD

**Issue by gitboy1** [dotnet/docs#7896]
"✓ DO make only the longest overload virtual (if extensibility is required). Shorter overloads should simply call through to a longer overload. " What determines the length of an overload? Is it the number of parameters? Also, what is a virtual overload?

"X DO NOT have overloads with parameters at the same position and similar types yet with different semantics." Can you provide and example of what this means?

"✓ DO use member overloading rather than defining members with default arguments. " Can you provide an example of what it means to define a member with default arguments vs. a member without default arguments.

Thank you in advance for your time and help.

Kind regards,
Jonathan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abb3b4b0-1055-8525-fc30-c5dd54fa36e3
* Version Independent ID: 07adc99b-60e9-1fc7-b552-cab16a338e86
* Content: [Member Overloading](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/member-overloading)
* Content Source: [docs/standard/design-guidelines/member-overloading.md](https://github.com/dotnet/docs/blob/master/docs/standard/design-guidelines/member-overloading.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Hi, @gitboy1.  By length of the overload, this article means the number of parameters that the individual overloaded method has. Optimally, each overload simply calls the overload that has the most parameters, so that only one overload provides the method implementation. Virtual means that method can be overridden by a derived class,

For the second point, a parameter of a particular type in a particular position should have a consistent meaning. For example, in a Person class, you wouldn't want to have a AddInformation overloads like AddInformation(string firstName, int age); and AddInformation(String lastName, double income);

For the third point, you can define a single method rather than overloading a method and provide default arguments. For example, CallOneMethod(string a = "value1", string b = "value2", string c = "value3"); there should be 3 or 4 overloads, where, for example, CallAMethod(string a) calls CallAMethod(string a, string b, string c), etc. Since optional parameters are now CLS-compliant, however, this recommendation is less important.

I hope that this answers your questions. Under the assumption that it does, I'll close this issue.

**Comment by gitboy1** [comment]
Mr. Petrusha,
Thank you for your explanation - it helped.
- Jonathan
