### ISSUE TITLE
Recommanded and supported alternative for Asp.net service on Azure?

### ISSUE THREAD

**Issue by ericbl** [dotnet/docs#7908]
About the "Classes within the System.Drawing namespace are not supported for use within a Windows or ASP.NET service":
what does Microsoft recommend and support to draw images in a ASP.NET Web service on Azure?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e4a052f-ea8e-a8c4-770d-d90fca5cc543
* Version Independent ID: 8f44358d-b378-6b5b-cde5-6e364bf8fa57
* Content: [System.Drawing Namespace](https://docs.microsoft.com/en-us/dotnet/api/system.drawing?redirectedfrom=MSDN&view=netframework-4.7.2)
* Content Source: [xml/ns-System.Drawing.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/ns-System.Drawing.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by ericbl** [comment]
Maybe already a possible answer to the above question, with this blog entry from Scott Hanselman
https://www.hanselman.com/blog/HowDoYouUseSystemDrawingInNETCore.aspx
(meant for .NET Core, but comments and alternative packages are also available on .NET Framework)

**Comment by Thraka** [comment]
@ericbl Hi! Yeah, pretty much what you found is a great source of information. For one reason or the other, ASP.NET can't use System.Drawing (probably related to the fact that there is no traditional Windows UI)

Personally I've used something like a Cloud Service on Azure, but it's a higher cost because you're running a full Windows VM. You would design that Cloud Service/VM to be triggered by your webservice/website and do whatever System.Drawing you needed and then bring that result back to the webservice/website.

You're better off using something from that page you found. I'm going to close this for now as it really isn't a documentation problem. If you have any other questions, feel free to ask.
