### ISSUE TITLE
@this vs this

### ISSUE THREAD

**Issue by juniormayhe** [dotnet/docs#7928]
If you intend to use the keyword this as a variable you can use @this

Ref: https://stackoverflow.com/questions/5536540/what-does-t-this-mean-in-a-delegate-declaration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f18483e-0603-040b-e3e9-0566dd04cd74
* Version Independent ID: c7b196b6-20e4-7567-7fd8-8b7145907665
* Content: [this (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/this)
* Content Source: [docs/csharp/language-reference/keywords/this.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/this.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thanks for your feedback, @juniormayhe. The use of the `@` prefix is documented in the [C# keywords](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/) topic and is a general language feature; it is not unique to `this` and shouldn't be documented for `this` separately.
Since this issue doesn't impact the documentation, I'll close it. If you disagree, however, please let us know.
