### ISSUE TITLE
Align project.json samples in the app types document to dotnet new templates

### ISSUE THREAD

**Issue by neman** [dotnet/docs#799]
When I enter command `dotnet new` I got following `project.json` lines

``` JSON
"dependencies": {},  
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0"
        }
      },
      "imports": "dnxcore50"
    }
  }
```

But it's slightly different from documentation within [App Types](https://docs.microsoft.com/en-us/dotnet/articles/core/app-types#portable-applications)  where it shows

``` JSON
"dependencies": {
    "Microsoft.NETCore.App": {  
        "version": "1.0.0",
        "type": "platform"
    }
},
"frameworks": {
    "netcoreapp1.0": {}
}
```

The both version works (build and run)

Which one version is correct, obsolete or are both version regular?

frameworks property in docs is not embedded within dependencies property.
cc @blackdwarf

**Comment by blackdwarf** [comment]
@neman both are correct . The one in the templates is slightly better because it places the dependency in the right framework, which means that if you want to multitarget between different frameworks the dependencies will be in the correct place. 

I will be making updates to the app types document soon, so will change the sample `project.json` files in the document to correspond to the `dotnet new` templates. Will rename and keep this issue to track that.

**Comment by mairaw** [comment]
@blackdwarf have you addressed this with your latest updates to the deployment topic?

**Comment by mairaw** [comment]
No longer applicable.
