### ISSUE TITLE
Some columns listing operators are displayed wrongly.

### ISSUE THREAD

**Issue by FMNSSun** [dotnet/docs#8034]
```
Logical OR 	`x 	y`
```

and

```
Conditional OR 	`x
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 362f3e73-a902-45e6-382d-328a4552a235
* Version Independent ID: d4253465-4bfc-e473-f745-0d5e1ff4e76c
* Content: [Introduction](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/introduction)
* Content Source: [spec/introduction.md](https://github.com/dotnet/csharplang/blob/master/spec/introduction.md)
* Product: **dotnet-csharp**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
This is related to #6335, which was fixed by dotnet/csharplang#1807.

However, now in GitHub interface, the [table](https://github.com/dotnet/csharplang/blob/master/spec/introduction.md#expressions) is not rendered correctly:
![image](https://user-images.githubusercontent.com/15279990/46421213-f30f6f00-c731-11e8-9724-edc186bc0c2b.png)

@BillWagner was the rendering logic updated such that the code-fenced pipe symbols must be escaped in the table? dotnet/csharplang#1807 should be reverted, then?

**Comment by imba-tjd** [comment]
@mairaw This issue has been resolved

**Comment by mairaw** [comment]
This is fixed now. Thanks for letting us know @FMNSSun.
