### ISSUE TITLE
HashCode and equality

### ISSUE THREAD

**Issue by agehrke** [dotnet/docs#8062]
I think this document is lacking info on HashCode and equality for ValueTuple.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 133c3b7b-833f-c2ce-aaa7-63f462f2e9ff
* Version Independent ID: f2aaa755-32cd-0d48-db81-5368ae6a152c
* Content: [ValueTuple Struct (System)](https://docs.microsoft.com/en-us/dotnet/api/system.valuetuple?view=netframework-4.7.2)
* Content Source: [xml/System/ValueTuple.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/ValueTuple.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for submitting your question, @agehrke. ValueTuple is a tuple type that has no members and is intended to be used primarily in calling static ValueTuple creation methods. Because of this, its Equals(ValueTuple) method always returns true, since two empty value tuples are necessarily equal. This is documented in the [ValueTuple.Equals(ValueTuple)](https://docs.microsoft.com/en-us/dotnet/api/system.valuetuple.equals?view=netframework-4.7.2#System_ValueTuple_Equals_System_ValueTuple_). The ValueTuple.GetHashCode method always returns 0; because the ValueTuple has no data, there is nothing to hash.
The documentation does not note that the value returned by the GetHashCode method is always 0. We'll update the documentation to note the return value.

**Comment by agehrke** [comment]
Ah, yes, this page is for `ValueTuple` with no members, but the remarks section contains general information about tuples. I think it would make sense to also explain about equality in this section and maybe a few words on hash code. The Equals documentation for `ValueTuple<T1,...>` does explain how equality is considered:

> Its components are equal to those of the current instance. Equality is determined by the default equality comparer for each component.

**Comment by rpetrusha** [comment]
Thanks for clarifying your request, @agehrke. The first two paragraphs of the topic have some general information on tuples and their usage. The remainder of the Remarks section focuses on the ValueTuple type specifically. Our intent here was to create a very general introduction to tuples (which is common to ValueTuple and each of the generic ValueTuple types) without going into very much detail. The problem with adding detail about testing for equality and the computation of hash codes here is that a test for equality is irrelevant to the ValueTuple type that we're documenting (all ValueTuple instances are necessarily equal since they have no instance data and therefore aren't really tuples at all), and since the hash code is always 0, it is effectively meaningless for ValueTuple as well.

My sense is that the more detail we add that applies primarily to other tuple types (as information on tests for equality and hash code computation would be), the more out of place that information is and the more confusion we create.
