### ISSUE TITLE
Document E2E VS Code Experience

### ISSUE THREAD

**Issue by richlander** [dotnet/docs#807]
We need to document the "end to end" VS Code experience with C# and .NET Core.

We have this great doc already: https://github.com/dotnet/core-docs/blob/master/docs/core/tutorials/using-on-macos.md. 

We need to document the very basic experience that doesn't include unit testing from the start, to deliver a super low friction adoption experience on one page.

The marketplace extension page needs to point into the docs, not the omnisharp repository for the experience, including debugging. We should also look at the code.vs.com pages, too.

See:
- https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp
- https://github.com/OmniSharp/omnisharp-vscode/blob/master/README.md
- https://code.visualstudio.com/docs/runtimes/dotnet
- https://code.visualstudio.com/docs/runtimes/unity
- https://code.visualstudio.com/docs/languages/csharp

/cc @DustinCampbell, @staceyhaffner

**Comment by BillWagner** [comment]
I'll likely be involved here as well. I think the VS Code experience dovetails nicely with the C# Guide materials I'm working on.

**Comment by DustinCampbell** [comment]
Do note that the marketplace page is the readme from the extension's repo. This is by design, and you'll see that this is the case for pretty much all extensions on the marketplace. For example, here're the next four most popular extensions after C#:

* https://marketplace.visualstudio.com/items?itemName=donjayamanne.python
* https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome
* https://marketplace.visualstudio.com/items?itemName=lukehoban.Go
* https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools

It'd be awesome if the repository's readme were given some love, so that it worked for both.

**Comment by mairaw** [comment]
@richlander is this the kind of topic you had in mind for this issue:
https://docs.microsoft.com/en-us/dotnet/articles/csharp/getting-started/with-visual-studio-code?

**Comment by kendrahavens** [comment]
I definitely want to add the Debug section to that doc now.

**Comment by mairaw** [comment]
@kendrahavens cool! I'm wondering if that should be in a separate topic though.

**Comment by mairaw** [comment]
Can we consider this done @richlander with the topic at https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code?

**Comment by BillWagner** [comment]
closed as a stale issue.
