### ISSUE TITLE
Confusing iterator method naming in the example.

### ISSUE THREAD

**Issue by LengVang** [dotnet/docs#8108]
Either change GetSingleDigitNumbers() to GetEnumerator() or vice versa.  Also, the statement: var enumerator = collection.GetEnumerator(); 
The collection is confusing.  It should be clear that it can be any user object that provide a function to returns IEnumerable&lt;T&gt;.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8ba3a4c-1796-84b8-4152-b9806483ce86
* Version Independent ID: bd878489-9a4c-6d99-6c4c-c56e0387012b
* Content: [Iterators](https://docs.microsoft.com/en-us/dotnet/csharp/iterators)
* Content Source: [docs/csharp/iterators.md](https://github.com/dotnet/docs/blob/master/docs/csharp/iterators.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @LengVang 

I'm trying to interpret your comment to provide the right fix.  The method names are by design, to show that an **iterator method** instructs the compiler to create the `GetEnumerator()` method so that it returns an object that will return each item that is `yield return`ed from the iterator method.

That connection isn't clear, and it should be made more explicit.

**Comment by pstricks-fans** [comment]
Maybe this function name should be changed to GetNumbers because the number of digits is not always single.

public IEnumerable<int> GetSingleDigitNumbers()
{
    int index = 0;
    while (index < 10)
        yield return index++;

    yield return 50;

    var items = new int[] {100, 101, 102, 103, 104, 105, 106, 107, 108, 109 };
    foreach (var item in items)
        yield return item;
}
