### ISSUE TITLE
DI should be defined as Dependency Injection, not Dependency Inversion

### ISSUE THREAD

**Issue by maverickelementalch** [dotnet/docs#8295]
The content defines DI as meaning Dependency Inversion but really uses it as meaning Dependency Injection, which leads to nonsensical statements like "DI is one way to implement the Dependency Inversion principle.".

The content should be rephrased as follows:

"The final principle, the Dependency Inversion principle, allows you to decouple the infrastructure layer from the rest of the layers, which allows a better decoupled implementation of the DDD layers. [...] Dependency Injection (DI) is one way to implement the Dependency Inversion principle."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a37dbbd-9672-4b6b-cd5a-4b21d15ebbd5
* Version Independent ID: 527c7941-e7b6-4a6e-3af6-a026fb0323a2
* Content: [Designing the microservice application layer and Web API](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/microservice-application-layer-web-api-design)
* Content Source: [docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/microservice-application-layer-web-api-design.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/microservice-application-layer-web-api-design.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
I agree. The DI acronym doesn't even need to really be used here. It could just be spelled out.

**Comment by Thraka** [comment]
@maverickelementalch I marked this as **up-for-grabs** as a good fix that can be done by the community. If you would like to make this change, please follow the simple instructions at the [contributor guide](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-edit-article?branch=master#update-an-existing-article). 

Thanks!

**Comment by mairaw** [comment]
@mvelosop FYI on an e-book issue and PR

**Comment by CESARDELATORRE** [comment]
DI means means "Dependency Injection".
The paragraph "_The final principle, the Dependency Inversion (DI) principle, allows you to decouple the infrastructure layer from the rest of the layers, which allows a better decoupled implementation of the DDD layers_." just needs to have deleted the "(DI)" acronym, that's a typo.
Also, instead of just "_DI is one way to implement the Dependency Inversion principle._"
This would be better "_Dependency Injection (DI) is one way to implement the Dependency Inversion principle._"

The resto of the text is right, I think.
