### ISSUE TITLE
Confusing (possibly erroneous?) code examples

### ISSUE THREAD

**Issue by ocpi4** [dotnet/docs#8461]
I am confused by the examples given in this article.
As far as I can tell the calling mechanism for both "Increase" and "Replace" subs in the examples on this page is the same (ByVal). And yet the example results show that you have different behaviour, with the "Increase" sub resulting in a change to array n (because, to quote "Because the array n is a reference type, replace (this should be increase?!) can change its members, even though the passing mechanism is ByVal."), but the "Replace" sub not being able to change array n.
Does the calling code not need to enclose the argument n in double parentheses to force the argument to be passed ByVal (as documented in the article "How to: Force an Argument to Be Passed by Value" )? eg "Call replace((n))"?
Note also that I believe the paragraph describing the 1st message box result should refer to the "Increase" sub, not the "Replace" sub?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ea0973f-8eb9-7bd0-5ce7-cb0930ca85f4
* Version Independent ID: eea63a16-a44b-10a7-ea5d-d4b9485357b1
* Content: [How to: Protect a Procedure Argument Against Value Changes (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/procedures/how-to-protect-a-procedure-argument-against-value-changes)
* Content Source: [docs/visual-basic/programming-guide/language-features/procedures/how-to-protect-a-procedure-argument-against-value-changes.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/language-features/procedures/how-to-protect-a-procedure-argument-against-value-changes.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for your comment, @ocpi4. Passing an array by value to a procedure allows the value of its individual elements to be changed (as the Increase method does), but does not allow an entirely different array to be substituted for the array passed as an argument (as the Replace method attempts to do). The same applies to passing an object, such as a Person object, by value -- you can change individual Person object properties and fields and have those changes reflected back to the caller, but you can't substitute a new Person object and have that reflected back to the caller.

Enclosing an argument in parentheses causes an argument to be passed by value to a method that is expecting a by-reference argument. Since arguments are passed by value to both Increase and Replace, that isn't applicable here.

I hope that this answers your questions.

The example description should indeed refer to the Increase method, not the Replace method. We'll make that correction.

**Comment by ocpi4** [comment]
Hi Ron,

Thanks for the answer – I now understand better what’s going on.

Interestingly, in Excel VBA it seems you can’t use the “ByVal” keyword when passing an array (which seems to make sense given it has no effect!)…

Thanks,
Oliver.
