### ISSUE TITLE
is null-coalescing operator an atomic operation ?

### ISSUE THREAD

**Issue by DickBaker** [dotnet/docs#8526]
The docs makes no statement about concurrency and atomic operation. For example the statement
myObj = myObj ?? new MyObject();   // can another thread intervene between test and assignment ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 038ae35e-c5e9-e1a4-a6dd-afe379201245
* Version Independent ID: d73f3d5a-00d4-2e22-c120-8e8d6d101a54
* Content: [?? Operator (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-coalescing-operator)
* Content Source: [docs/csharp/language-reference/operators/null-coalescing-operator.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/null-coalescing-operator.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
> The docs makes no statement about concurrency and atomic operation.

I don't see why it should. If you have e.g. `i += 1;`, then it *looks* like a single operation, so I would understand why someone would think it might be atomic, but it's not.

But with `i = i + 1;` or `myObj = myObj ?? new MyObject();`, it seems clear to me that you have two distinct operations: one that reads the variable and another one that writes to it. So I think there is no reason to expect that to be atomic. Why do you think otherwise?

**Comment by pkulikov** [comment]
@DickBaker 

>For example the statement `myObj = myObj ?? new MyObject();` // can another thread intervene between test and assignment ?

The right expression (the one after `??`) is evaluated only if the left expression evaluates to `null`. The current docs don't state it, but maybe they should. Designers of the language didn't know what would the right expression do. It can go such crazy that making it "atomic" might result in a deadlock. So, no, the `??` operator is not atomic. 

If you want to make atomic test/assignment, consider the [Interlocked.CompareExchange](https://docs.microsoft.com/en-us/dotnet/api/system.threading.interlocked.compareexchange?view=netframework-4.7.2#System_Threading_Interlocked_CompareExchange__1___0____0___0_) method:
```csharp
Interlocked.CompareExchange<MyClass>(ref myObj, new MyClass(), null);
```

However, note that that behavior differs from `myObj = myObj ?? new MyClass();`: in case of the method call, its arguments are evaluated first. That means that `new MyClass()` would be always called.

By the way, I'm curious as @svick: what made you think that that operator might be atomic?

**Comment by DickBaker** [comment]
Petr, thanks for posting.
Actually I thought ?? wasn't atomic, but the behaviour of the .? null-conditional-operator
https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-6#null-conditional-operators
is atomic (and very handy to simplify event handlers).
This opposing behaviour may confuse devs, hence my suggestion to explicitly state that ?? operator is not atomic.
[thanks also for your Interlocked snippet and the warning that it doesn't fit the scenario I posed!]

**Comment by pkulikov** [comment]
@DickBaker 
>...but the behaviour of the `?.` null-conditional-operator
https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-6#null-conditional-operators
is atomic (and very handy to simplify event handlers).

The null-conditional `?.` operator is also not atomic. [This snippet](https://sharplab.io/#v2:D4AQDABCCMDcCwAoEBmKAmCBhCBvJEhEBRqEApgG7kB2ALhAKLX0ASAhjQCYA25AThA4AHYbXJcEiIsWmk0IACwQAsgAoAlHhIzCIsTQkB+AHQBJGpQD2Aa3Jq6ACwCWAZwA0TFnQCC/AOauJowAtsJ0AJ4aUjIAvkixQA==) shows how `?.` works with events:

```csharp
Happened?.Invoke(this, EventArgs.Empty);
```

is converted to 

```csharp
EventHandler happened = this.m_Happened;
if (happened != null)
{
    happened(this, EventArgs.Empty);
}
```

That might make `?.` look atomic with events. However, in general case it's not atomic.

**Comment by DickBaker** [comment]
Amazing how quickly everyone [well me anyway!] takes the magic (magician popping the rabbit out of the hat) for granted and forgets the hard-work (or sleight-of-hand) for granted. You are of course correct about the code generation and the fact that the Happened?.Invoke is actually not atomic (e.g. another thread could have intervened with += or -= to Happened e.h. before our thread makes use of the happened temporary variable).
Good discussion, and I suggest that the docs makes this non-atomicity clear to future dev readers in case they chase the wrong rabbit. Thanks for your help and clarification/reminder!

**Comment by BillWagner** [comment]
I'm going to close this.

I'll make several points:

1. The `??` operator is not atomic. As others have said, we state only when an operation (or method) is atomic. The same is true with the `?.` operator.
1. We do use explain the semantics of `?.` by declaring that the left hand side of the operator is evaluated only once because *it does matter*. 

> It is true that no operator evaluates an operand more than once. But, some operators may not evaluate all operands.  Consider the example: `if (thing != null && thing.Property == 5`. `thing` may be evaluated once or twice, because it appears twice in the boolean expression. We explain `x?.y` to be the same result as `x != null ? x.y : default` but `x` is evaluated only once. Similarly, `x ?? 0` is the same result as `x != null ? x : 0`, but `x` is evaluated only once.

In both of those examples, the expressions look like variables, with no side-effects. If true, the results are the same for all single threaded programs. If a thread switch could take place, the fact that `x` is evaluated only once means that these operators can't crash because the value is assigned to `null` after being null-checked. 

If `x` were a method call with side-effects, it means that those side effects only happen once.

The docs are correct, the details I've just added are in the linked C# langauge spec.

**Comment by mabakay** [comment]
We can type now "a ? b ??= c : d ?? e" yey!
