### ISSUE TITLE
This doc should call out how StringReader.ReadLine handles new lines at the end of file

### ISSUE THREAD

**Issue by tylerl0706** [dotnet/docs#8612]
if you have a blank line at the end of the string, StringReader.ReadLine() will give you `null` for that.

If you have 2 blank lines at the end of the string, the two calls to ReadLine will give you first an empty string and then `null`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5543d837-5155-8683-6223-09a9f0a0d745
* Version Independent ID: 7fc74a35-04a2-3d65-7140-a1ea680d707b
* Content: [StringReader.ReadLine Method (System.IO)](https://docs.microsoft.com/en-us/dotnet/api/system.io.stringreader.readline?redirectedfrom=MSDN&view=netframework-4.7.2#feedback)
* Content Source: [xml/System.IO/StringReader.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/StringReader.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by karelz** [comment]
@tylerl0706 can you submit PR with the changed wording?

**Comment by mikedn** [comment]
There may be some sort of confusion here about that blank line at the end is supposed to be. As far as I can tell `ReadLine()` works as expected and the documentation is correct.

**Comment by rjmholt** [comment]
Well the relevant remark in the documentation is:
> A line is defined as a sequence of characters followed by a line feed ("\n"), a carriage return ("\r"), or a carriage return immediately followed by a line feed ("\r\n"). The string that is returned does not contain the terminating carriage return or line feed. The returned value is null if the end of the string has been reached.

It's uncontroversial then that `"a\nb\nc\n"` returns the three lines `"a"`, `"b"` and `"c"` given this definition.

But I could perhaps read this as also meaning that `"a\nb\nc"` should only return two lines, `"a"` and `"b"`, since they are only two "sequences of characters followed by a linefeed, carriage return or both", followed by `null`.

Given that this is not the case, and that the documentation makes no reference to any special behaviour that occurs at the end of the string, I think it's fair to add a small extra note on what happens at the end of the string, and how the behaviour here differs from `s.Split(new [] { "\r\n", "\n", "\r" }, StringSplitOptions.None)`, because at the end of the day people are going to use them in similar scenarios.

**Comment by mikedn** [comment]
> But I could perhaps read this as also meaning that "a\nb\nc" should only return two lines, "a" and "b", since they are only two "sequences of characters followed by a linefeed, carriage return or both", followed by null.

That would be highly controversial 😁

> Given that this is not the case, and that the documentation makes no reference to any special behaviour that occurs at the end of the string, I think it's fair to add a small extra note on what happens at the end of the string

Yep, that should work. Interestingly, the base class already says something like that:
> A line is defined as a sequence of characters followed by a carriage return (0x000d), a line feed (0x000a), a carriage return followed by a line feed, Environment.NewLine, **or the end-of-stream marker**. The string that is returned does not contain the terminating carriage return or line feed. The return value is null if the end of the input stream has been reached. 
```
https://docs.microsoft.com/en-us/dotnet/api/system.io.textreader.readline

**Comment by rjmholt** [comment]
The relevant line in question:
https://github.com/dotnet/dotnet-api-docs/blob/d42d6e7178e293d24939d4a3bd5b2f43973c82ba/xml/System.IO/StringReader.xml#L832

Hopefully I can submit a PR this week.

**Comment by tylerl0706** [comment]
PR opened:
https://github.com/dotnet/dotnet-api-docs/pull/671
