### ISSUE TITLE
Recommended host for symbol packages

### ISSUE THREAD

**Issue by qbit86** [dotnet/docs#8670]
&gt; Until there is a recommended host for symbol packages...

Isn't it https://nuget.smbsrc.net (instead of http://www.symbolsource.org ) such recommended host?
Mentioned here: https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages

&gt; ...you can embed symbol files by setting the AllowedOutputExtensionsInPackageBuildOutputFolder property

How can I embed C# source files in the main package? (Like embedding in symbol package with &lt;IncludeSource&gt; property.) Is it legit to build symbol package with C# sources and PDBs alongside DLLs, rename it from MyPackage.symbols.nupkg to MyPackage.nupkg, and publish to NuGet.org?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc2b4abb-c382-17ef-f1f3-1413ee27aaa0
* Version Independent ID: 4d4bb4d2-a8f4-f142-7154-40ce7fc7ae32
* Content: [NuGet and .NET libraries](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/nuget#symbol-packages)
* Content Source: [docs/standard/library-guidance/nuget.md](https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/nuget.md)
* Product: **dotnet**
* GitHub Login: @JamesNK
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
@qbit86 Hi! Sorry for the delay in getting to this issue. The guidance for NuGet has changed quite a bit since you filed this issue. The article has been updated several times and removed the symbolsource.org information. Also, **SourceLink** is a good thing to add to your open source projects along with the new **.snupkg** format for symbols.

I don't think you can include source in the main package automatically. You need to create your own nuspec file and generate the **.nupkg** directly.
