### ISSUE TITLE
Invalid and misleading typo

### ISSUE THREAD

**Issue by falahati** [dotnet/docs#8706]
"For example, it replaces \a with \x07." Should be the other way around.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 605c2300-6061-886c-b953-6b6d0901c032
* Version Independent ID: a484ed71-a293-f766-3d5f-a8766f95473c
* Content: [Regex.Unescape(String) Method (System.Text.RegularExpressions)](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.unescape?view=netframework-4.7.2)
* Content Source: [xml/System.Text.RegularExpressions/Regex.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/Regex.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by elgonzo** [comment]
Actually, this remark is completely confusing and doesn't make little sense; it could be read in any way. ( (perhaps some formatting got lost in the process of finalizing this documentation?) 

If you have the literal char sequences `\`,`a`, or `\`,`x`,`0`,`7` in the string, **both**  will be converted/"unescaped" by the Regex.Unescape method to the bell character (ordinal value 7).

The documentation here fails to distinguish between an actual character in a string/character represented by their escape sequence (both `'\a'` and `'\x07'` would be the same **single** bell character), and a character sequence that itself is a textutal representation of an escape sequence reprensenting a character (such as '@"\a"' or '@"\0x07", which are just 2 or 4 chararcters, respectively, with none of them actually being the bell character).

Instead of saying

> it replaces \a with \x07

the documentation should say one of two things:

> it replaces @"\a" and @"\0x07" with '\x07'
or
> it replaces @"\a" and @"\0x07" with '\a'

Both statement would be correct, but since the debugger normally shows the bell character as `\a` and not as `\0x7`, i would prefer the latter suggestion.

**Comment by Coolerhino** [comment]
Hi, I have added pull request to address this issue. 
Isn't a case of converting @"\a" to "\a" covered in former paragraph?

> It reverses the transformation performed by the Escape method by removing the escape character ("\") from each character escaped by the method. These include the \, *, +, ?, |, {, [, (,), ^, $,., #, and white space characters. In addition, the Unescape method unescapes the closing bracket (]) and closing brace (}) characters.

**Comment by elgonzo** [comment]
The paragraph you quoted does not cover converting non-printable characters. This paragraph only covers (more or less) stripping the escape character in front of those (printable) characters that have a "special" meaning in a regular expression.

Stripping the backslash character is not what is happening when @"\a" is converted to "\a". Stripping just the backslash would turn @"\a" into "a", not into "\a".

**Comment by elgonzo** [comment]
@Coolerhino, i just took a quick look in your pull request. You have some ambiguities and errors in it, unfortunately.

> hexadecimal values in verbatim string literals with the actual printable characters.

This is ambiguous, and in the worst case misleading. This (verbatim) string `@"Some 0xDE 0xAD 0xBE 0xEF"` clearly has some hexadecimal values in it. ;-)

Also, there is a another mistake in this sentence. Not all characters are printable!
The bell character (0x07) we are talking here so much in this issue is not a printable character. :-)

> it replaces @"\0x07" with @"\a", or @"\x0A" with @"\n".

Incorrect. It does not replace `@"\0x07"` with `@"\a"`, and it does not replace `@"\x0A"` with `@"\n"`. It would replace `@"\0x07"` with `"\a"` (the latter not a verbatim string!). And it would replace `@"\x0A"` with `"\n"`, respectively.

That's why i also woud recommend to not use both verbatim string syntax and normal string syntax together to explain the behavior of Regex.Unescape. If the documentation system allows, i would very much prefer a notation where the four(!) characters in `@"\0x07"` would be easily identifiable as individual characters in a string (without running the risk of mistaking it for an actual escape sequence in a normal string). In the same way, such a notation could also help conveying the fact that `"\0x07"` is just a single(!) character (and would not be easily confused with the verbatim 4-character string i talked about in the previous sentence).

Additionally, your explanation gives a false sense that only representations of character sequences using hex notations will be converted. But this is far from the truth. Not only will `@"\0x07"` be converted to`"\a"`, but `@"\a"` will also be converted to `"\a"`.

**Comment by Coolerhino** [comment]
I read the reply, the implementation and other docs and the simplest and most clear explanation I can think of is following:
>It replaces all escaped unprintable metacharacters with their representation supported by regular expressions in .NET. For example, it replaces @"\a" and @"\x07" with "\a", or @"\x0A" and @"\n" with "\n".

Because ultimately the point of this method is to undo escaping printable and unprintable metacharacters, as seen in [comment](https://github.com/dotnet/corefx/blob/d69f113afb5c43702e7c8477c6dbe2f9e9465355/src/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexParser.cs#L185)
So, if the original string contained "\x0A", was escaped and then this method was used, it would convert it to "\n" since it doesn't know which representation was used in original string. Please correct me if I have wrong reasoning.

Also, regarding implementation- is it desired behavior if the method converts escaped hex numbers (alphanumerical characters that are not regex metacharacters) to chars?

**Comment by elgonzo** [comment]
@Thraka,

The approved commit with the updated explanation has two errors. First, it should be @"\x07" and not @"\0x07" (the latter would not represent a valid character code due to the 0 before the x).

Second, the results are not the verbatim strings @"\a" nor @"\n". It is wrong to use the verbatim string symbol for the replacement results; the results would be rather "\a", or "n" respectively.

See this dotnetfiddle illustrating both errors: https://dotnetfiddle.net/EWLos0

**Comment by elgonzo** [comment]
@Thraka,

the approved commit of the updated documentation has two errors. First, it should be @"\x07" and not @"\0x07" (the latter would not represent a valid character code due to the 0 before the x).

Second, the results are not the verbatim strings @"\a" nor @"\n". It is wrong to use the verbatim string symbol for the replacement results; the results would be rather "\a", or "\n" respectively.

See this dotnetfiddle illustrating both errors: https://dotnetfiddle.net/EWLos0
