### ISSUE TITLE
Erroneously showing literal angle brackets?

### ISSUE THREAD

**Issue by tswett** [dotnet/docs#8846]
"If you want angle brackets to appear in the text of a documentation comment, use &lt; and &gt;, as shown in the following example."

Right now, as shown above, the documentation says that you can make angle brackets appear in a documentation comment by using literal angle brackets (&lt; and &gt;). Is this supposed to say that you can make angle brackets appear by using entities (the &lt; entity and the &gt; entity)? If I remember right, angle brackets are not supposed to appear in an XML document except as tag delimiters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d5aa865-b9d2-e977-a272-3886aa0a1111
* Version Independent ID: 353b1c44-b90a-e5cc-a193-7b42ec714290
* Content: [Recommended Tags for Documentation Comments (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/recommended-tags-for-documentation-comments)
* Content Source: [docs/csharp/programming-guide/xmldoc/recommended-tags-for-documentation-comments.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/xmldoc/recommended-tags-for-documentation-comments.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Yeah, I'm not sure. It doesn't seem to make sense to me. If you want brackets in the documentation, you use the HTML encoding such as `&gt;`

@BillWagner I can fix this up. I just want to make sure that changing the example is correct. I think it is. Putting < or > inside of the cref seems odd, since the syntax is { } for the overload and the cref attribute needs to resolve to something. I see this note as specifying that the COMMENT TEXT inside of the documentation nodes needs to be encoded.

**Comment by kthy** [comment]
I agree that this is simply a case of `ampersand g t semicolon` being passed and interpreted as a literal angle bracket in the documentation source.

**Comment by BillWagner** [comment]
@Thraka Your analysis is correct. Go ahead and make the fix.
