### ISSUE TITLE
tour-of-csharp/statements - code samples not included completely

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#8935]
@FlexOr2 commented on [Wed Nov 07 2018](https://github.com/dotnet/docs.de-de/issues/113)

The "code samples" in the statements section are not included completely anymore. 
Seems the cause are changes in the "Program.cs" file. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 017f9566-a4df-e294-d6e8-da9252469ca9
* Version Independent ID: 6665f9d5-24bf-ac0d-62f5-d63ed53132ed
* Content: [C#-Anweisungen – Überblick über C#](https://docs.microsoft.com/de-de/dotnet/csharp/tour-of-csharp/statements)
* Content Source: [docs/csharp/tour-of-csharp/statements.md](https://github.com/dotnet/docs.de-de/blob/live/docs/csharp/tour-of-csharp/statements.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---

@CeciAc commented on [Wed Nov 07 2018](https://github.com/dotnet/docs.de-de/issues/113#issuecomment-436696233)

Hello @FlexOr2 
Thank you for your feedback.
I'm checking the live page and I don't see any missing/broken code.
Can you please provide more information so we can work on this issue?

Kind regards,
Microsoft DOCS International Team

---

@FlexOr2 commented on [Thu Nov 08 2018](https://github.com/dotnet/docs.de-de/issues/113#issuecomment-436935906)

Hi @CeciAc ,
the method definitions are missing in the code samples for all statements.
E.g. the yield statement code sample looks like:

`
{
    for (int i = from; i < to; i++) 
    {
        yield return i;
    }
    yield break;
}
static void YieldStatement(string[] args)
{
    foreach (int i in Range(-10,10)) 
    {
        Console.WriteLine(i);
    }
}
`

So I don't see the definition of the "Range" method here.

**Comment by CeciAc** [comment]
Hi team,
please check this issue about missing data in the documentation

Kind regards,
Microsoft DOCS International Team

**Comment by mikkelbu** [comment]
The problem is this [change](https://github.com/dotnet/samples/commit/693a9e49d3c2059cf78c55c5de2278d1d559e1c6#diff-5e65a1cd6d2960f0cacbf33a3c723c02) that removed a using, thus make all the references to the file using line numbers invalid. I've reintroduced the using to make all references from the different language versions work again (like [German](https://docs.microsoft.com/de-de/dotnet/csharp/tour-of-csharp/statements) or [Italian](https://docs.microsoft.com/it-it/dotnet/csharp/tour-of-csharp/statements)), but a better - long term - approach will be to use labels instead of line numbers for the references.
