### ISSUE TITLE
Bad example, doesn't compile, needs to be nullable

### ISSUE THREAD

**Issue by zidocread** [dotnet/docs#8959]
Hi.
This code from this docs' page doesn't compile as the ValueTuple is not nullable, please fix it:

```
public (string FName, string MName, string LName, int Age) GetPersonalInfo(string id)
{
    PersonInfo per = PersonInfo.RetrieveInfoById(id);
    if (per != null)
       return (per.FirstName, per.MiddleName, per.LastName, per.Age);
    else
       return null;    // here's the problem
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 158425f1-86b1-101a-9172-14c944867784
* Version Independent ID: 6386f636-99b3-93c3-ca9e-0134f3e3be10
* Content: [Methods - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/methods)
* Content Source: [docs/csharp/methods.md](https://github.com/dotnet/docs/blob/master/docs/csharp/methods.md)
* Product: **dotnet-csharp**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by lucasnobredev** [comment]
The _return null_ would work if the method was written like that:
``` csharp
public (string, string, string, int)? GetPersonalInfo(string id) { ... }
```

However, I believe it's not enough because this moment in section wants to explain tuples, not **?** like a nullable return. I mean.. I think it would be too much complex.

How about simplify the example code of method GetPersonalInfo (both) like:
``` csharp
public (string, string, string, int) GetPersonalInfo(string id)
{
    PersonInfo per = PersonInfo.RetrieveInfoById(id);
    return (per.FirstName, per.MiddleName, per.LastName, per.Age);
}
```

And we can add another example which will be showing a way to work with returns null, putting the **?**.

What you think?
