### ISSUE TITLE
Add DOTNET_CLI_UI_LANGUAGE and DOTNET_ROOT to the list of environment variables

### ISSUE THREAD

**Issue by JosefPihrt** [dotnet/docs#8988]
Add DOTNET_CLI_UI_LANGUAGE to the list of environment variables.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ba6c9b5-64cb-1dc6-21d0-ad8f0a1185fe
* Version Independent ID: 0f6c658c-b477-2d2c-2a9a-d74f6ae38d3f
* Content: [dotnet command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your feedback @JosefPihrt. @livarcocc @dsplaisted @KathleenDollard @nguerrera since when this env variable has been supported? Also, anything we should add in regards to this such as use cases, etc. besides a basic description that it sets the language of the CLI UI using a locale value such as en-us, etc.? Do we have a list of locales supported by the CLI for me to add? Thanks!

**Comment by mairaw** [comment]
Still waiting for confirmation on this one.

**Comment by nguerrera** [comment]
> since when this env variable has been supported?

Since .NET Core SDK 2.0. 

> Also, anything we should add in regards to this such as use cases, etc. besides a basic description that it sets the language of the CLI UI using a locale value such as en-us, etc.? 

No, that's it. :)

> Do we have a list of locales supported by the CLI for me to add?

It is the same list as the languages supported by Visual Studio: https://docs.microsoft.com/en-us/visualstudio/install/install-visual-studio?view=vs-2017#step-6---install-language-packs-optional.

https://github.com/dotnet/xliff-tasks/blob/master/src/XliffTasks/build/XliffTasks.props#L26

.NET resource manager rules apply, so you don't have to pick an exact match, you can also pick descendants in the CultureInfo tree. For example, if I set it to `fr-CA`, then it will find and use the `fr` translations. Also, if you set it to a language that is not supported, then the CLI will fall back to English.

**Comment by mairaw** [comment]
Thanks @nguerrera!

**Comment by Bartolomeus-649** [comment]
Please include what is used for, only for localization and resolving resources to the correct language, or does it affect other things as well? Like regional settings? Date and time format?
 
Also, how does it relate to other settings for language on OS level (system, user and so on).

Also, what if you set the language to, for example russian, how will you then display stuff when the default codepage is 437? 

So perhaps @nguerrera s "No, that's it. :)" remark was a bit hasty...and remember, Murphy would never let "No, that's it." get past him  ;)

**Comment by AdvancedPowerArmor** [comment]
It looks like it is still open. It would be great to update the list and add some examples.

**Comment by mairaw** [comment]
I also need to add the DOTNET_ROOT environment variable to this article. Would need confirmation of when this was introduced.

**Comment by wli3** [comment]
it is a runtime feature. First seem in SDK 2.1.300

**Comment by wli3** [comment]
We need to bump the priority for DOTNET_ROOT. It is been a year. And we don't have any official document for what it is for and what to set to. The only meaningful explanation is on a twitter thread. cc @richlander

**Comment by mairaw** [comment]
Yeah I know 😢 I'll schedule this one for this month and see if we can make that happen. Having your and @richlander's help to get those values accurately documented would be great. I'll ping you for review.

**Comment by wli3** [comment]
I am happy to help review, although SDK team does not own this feature, runtime team does
