### ISSUE TITLE
docker run on Ubuntu

### ISSUE THREAD

**Issue by matthewluck** [dotnet/docs#9034]
After following the steps and checking over them, as well as attempting subtle changes in an attempt to get it to work on my own, the final command does not work for me.

I get the following: No executable found matching command "dotnet-out/Hello.dll".

This is my first attempt at trying Docker so I won't be surprised if it is something I have done, was just looking for guidance as I don't see in the documents a step for remedying the issue.  

For reference, my Docker version is 18.09.0 and dotnet --version is 2.1.5.  If its useful, my Ubuntu is 18.04 as well.

Thank you for the guide either way though!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ef1481-3b6f-30bf-330d-45400c0a349c
* Version Independent ID: 03a156f7-b178-4d54-503d-26d229f89dcd
* Content: [Learn Docker Basics with .NET Core](https://docs.microsoft.com/en-us/dotnet/core/docker/docker-basics-dotnet-core)
* Content Source: [docs/core/docker/docker-basics-dotnet-core.md](https://github.com/dotnet/docs/blob/master/docs/core/docker/docker-basics-dotnet-core.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **johnalex**

**Comment by clarenceb** [comment]
The DLL will match the directory name where you ran `dotnet new console` (you can also use the `-o <dirname>` flag create the project in a sub folder with a name of your choosing).  You can see what the DLL is called by running `dotnet build` then listing the DLLs in the bin folder, e.g.

Mac/Linux:

`ls bin/Debug/netcoreapp2.1/*.dll`

Windows:

`dir bin\Debug\netcoreapp2.1\*.dll`

In my case it's called `hello-docker.dll` because I created the project with the command: `dotnet new console -o hello-docker`, then ran `cd hello-docker` and `dotnet build`.

So for my case I would use `ENTRYPOINT ["dotnet", "out/hello-docker.dll"] in my `Dockerfile`.

**Comment by kristianjaeger** [comment]
@clarenceb Thanks. It'd be awesome if they could update the doc to show that the name of the folder the user creates is important.  I hit the same issue on OS X Mojave.  Cheers.

**Comment by Thraka** [comment]
I updated this article and it should make sense now. This should be published today.

**Comment by kristianjaeger** [comment]
Thanks @Thraka !
