### ISSUE TITLE
API Documentation should indicate obsolescence

### ISSUE THREAD

**Issue by dnch** [dotnet/docs#917]
When trying to build a new project using `System.Collections` I ran into trouble trying to get my work to compile. It was only after help from someone on the .NET Slack channel and a chance click on the "View Source" button on the docs that I saw this:

https://github.com/dotnet/corefx/blob/master/src/System.Collections.NonGeneric/src/System/Collections/SortedList.cs/#L64

As you can see on https://docs.microsoft.com/en-us/dotnet/core/api/system.collections.sortedlist#System_Collections_SortedList, there's no indication that this is the case.

It would be great if this information could somehow be included. Thanks!

**Comment by BillWagner** [comment]
Ping @terrajobst for advice on what the best forward-looking guidance should be.

**Comment by mairaw** [comment]
You're right @dnch. The doc page should display a boilerplate and the obsolete attribute also needs to be displayed. I'll check if we're tracking this issue internally already.

**Comment by terrajobst** [comment]
We generally don't think that the `[Obsolete]` marker is appropriate for cases where large chunks of API surface have been replaced with something better, such as the case with non-generic collections. For one, it's often quite noise because you'll now get hundreds of warnings telling you that `SortedList` is a non-generic collection and you really be using something else. That's often not actionable.

`ObsoleteAttribute` works best for cases where an API shouldn't be called because it's always a bad idea (rare) or when a single method is replaced with another method. Both of these cases seem to be better suited by analyzers because:

1. Analyzers have more context. Often, it's not that an entire API is banned but certain ways to call it are (combination of arguments etc).
2. Analzyers can be accompanied by fixers. Nothing is more frustrating than having to mechanically do what a tool tip tells you. <kbk>Ctrl</kbd> <kbd>.</kbd> is much easier to use and also has a way to apply the fix to the entire project or even solution.

Does this help?

**Comment by mairaw** [comment]
As we think about how we want to surface those in the docs, how do we make the distinction? Historically, reflection would see the attribute and add a boilerplate on MSDN.

**Comment by terrajobst** [comment]
We haven't designed the end-to-end yet. I think whatever the option is we'll try to make it data driven rather than writing custom code for all the analyzers. And if it's data driven, I think there would be a way to extend the doc tooling to pull in that information, akin to how the attribute worked. In this world, though, it would probably not manifest itself in the syntax section but probably as a custom section in the docs.

**Comment by BillWagner** [comment]
In the fullness of time, I'd love an experience where tools read what platform(s) I want to support in a library, and reports on any API that would have problems. In particular:

- Changing the build configuration would cause any analyzers to run again and either add new reports, or remove those no longer applicable in the selected platforms.

- Including a NuGet package not supported on the chosen platforms would generate some kind of warning. (This probably requires some NuGet enhancements too.)

- Squiggles when I use an API not supported for a platform.

I've run into this issue myself, and there's not a lot of obvious help why an API isn't included. Is there a short-term solution that moves us along the path we want to travel?

**Comment by terrajobst** [comment]
Agreed. We're still fleshing out how the story will work in the build tools and our IDEs. Whatever mechanism we invent, we should make sure the docs echo it.

**Comment by mairaw** [comment]
@terrajobst any ideas on when you will have a proposal to this? we're going through our features for docs and don't want to implement things when they're still unstable

**Comment by terrajobst** [comment]
Multi-targeting and .NET Standard is the number thing my team works on right now. I think we should have a committed high-level plan by EOW this week. From there on, it's mostly a matter of us designing the concrete UX up the stack. Unfortunately, I don't have an ETA for that.

**Comment by mairaw** [comment]
Any updates on this @terrajobst?

**Comment by terrajobst** [comment]
Yes, I've added a [PR to my tool](https://github.com/terrajobst/platform-compat/pull/24). The experience looks like this:

![](https://cloud.githubusercontent.com/assets/5169960/25361775/d9387f76-2904-11e7-9050-c33d19d8b48f.gif)

**Comment by mairaw** [comment]
This is neat! Let's sync on how we want to surface this information on the docs then, @terrajobst.

/cc @dend

**Comment by mairaw** [comment]
We'll add info to the API docs from https://github.com/dotnet/platform-compat/tree/master/docs to indicated deprecated APIs.

**Comment by rpetrusha** [comment]
During Sprint 143, I'll add information on APIs that are not recommended and their suggested replacements.

**Comment by dnch** [comment]
This is awesome! 😄
