### ISSUE TITLE
Needs more info

### ISSUE THREAD

**Issue by potatoqualitee** [dotnet/docs#9204]
Can this please have the equivalent's solution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98513c27-0ac2-43f9-00ac-72a2989876e7
* Version Independent ID: 50dd4d83-9de1-2901-4704-a45836309010
* Content: [Compiler Error CS0116](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0116)
* Content Source: [docs/csharp/language-reference/compiler-messages/cs0116.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-messages/cs0116.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @potatoqualitee 

This is not written as well as it should be. The fix is that any methods must be contained in a struct or class. Those types can be contained in a namespace.

I've added this to our backlog, and added the up-for-grabs label to encourage community contributions.

**Comment by jmarkman** [comment]
I think I'll take a stab at this.

**Comment by BillWagner** [comment]
Thanks @jmarkman 

Tag me if you have any questions.
