### ISSUE TITLE
Defining "Standard" content

### ISSUE THREAD

**Issue by richlander** [dotnet/docs#9233]
I was looking at some of the content that is now in the "standard" directory. The original intent of that directory was to define the most basic and timeless aspects of .NET that are meaningful for any .NET implementation. Implementation-specific content would go into the "core" and "framework" directories, for example. Or scenario specific content would go in the "machinelearning" directory, for example. I think that vision remains a good one.

These directories give me pause. Let's discuss.

- https://github.com/dotnet/docs/tree/master/docs/standard/containerized-lifecycle-architecture
- https://github.com/dotnet/docs/tree/master/docs/standard/microservices-architecture
- https://github.com/dotnet/docs/tree/master/docs/standard/modern-web-apps-azure-architecture
- https://github.com/dotnet/docs/tree/master/docs/standard/modernize-with-azure-and-containers
- https://github.com/dotnet/docs/tree/master/docs/standard/serverless-architecture

cc @mairaw @CESARDELATORRE

**Comment by mairaw** [comment]
@wadepickett @BillWagner I think there are ongoing discussions about the placement for the .NET Architecture books, no?

**Comment by BillWagner** [comment]
A top-level architecture node would make sense, but if we do that we'd need to update the .NET Hub page, and handle a large number of redirections.

**Comment by richlander** [comment]
I'd rather us make the write fix. We have three choices:

- Give up on the initial plan for "standard" and allow more content like this in it.
- Go back to the initial plan for "standard" and move the non-standard content out.
- Keep existing content in but do not add any more such content.

The last idea is clearly incoherent, so let's drop that. I'm a fan of the second option. Also, if the architecture content is valuable (and we have been investing non-trivial effort/funds into it), then it deserves its own node.

**Comment by CESARDELATORRE** [comment]
It always felt pretty strange to have .NER Application Architecture content within the .NET Standard section. I think it should move out, as well.

**Comment by mairaw** [comment]
@wadepickett any updates on this?

**Comment by wadepickett** [comment]
Just realized this was still open!  The architecture content is published on a top level in the TOC in the .NET Guide rather than in the Standard area (which is good), while the doc source lives in the standard directory of the repo (which will cause confusion).  It was agreed to move this content out of the stardard area in the repo.   However, at the time it sounded like it would be moved to the Architecture Center rather than a new directory in the .net docs repo. That seemed to have died on the vine.  

@CESARDELATORRE if you, Brian Blanchard, Jason Roberts and Travis Grizzel agree on how much of this to move to the Architecture Center and how to organize it (For example under “Application Architecture”) it can be moved to that repo as soon as you want to.   Whatever is left, if anything should move under an "architecture" or "application-architecture" (or simarly named) directory in the .NET repo. (just a suggestion, Mark LeBlanc or Mairaw would make the call on that). 

@mairaw, if there is no agreed plan on moving the content to the architecture center by the end of this month, I would suggest just moving it out of the "standard" directory and into "architecture" or whatever you feel best fits so it does not linger any longer in "standard".

**Comment by mairaw** [comment]
I've chatted with @CESARDELATORRE and @nishanil recently and managed to get this answer. 

The architecture content is not published on the top level in the TOC. It's within the standard folder, which is what contains the .NET Guide content.

I'm working on a PR right now https://github.com/dotnet/docs/pull/12804 to move that content into its own section. The standard folder should only be about .NET fundamentals concepts, so I'll assign this issue to myself.

**Comment by wadepickett** [comment]
Update:  Looks like this was being resolved on a seperate thread.  The content will stay on the .net repo and will move out of standard and to its own folder.  It will not go to the architecture center.  On the dotnet homepage there will be a new tab for .NET architecture guidance to help with its discovery.

**Comment by wadepickett** [comment]
.. and looks like I just crossed updates with Maira. Thanks Maira.  I should have refreshed the page first.
