### ISSUE TITLE
Grammar Issue

### ISSUE THREAD

**Issue by johnechiappetta** [dotnet/docs#9288]
The text advises, "Use past tense (as in this example) when the event reports something that has happened."  However, the example referred to, "Progress," is not a past tense form of "to progress." (It is present indefinite, IIRC.)  This could be improved by changing the name to a past tense verb, such as "MadeProgress" or "Progressed", or by removing the parenthetical reference to the example.  (The latter approach still leaves an example that conflicts with the advice given, so it's not ideal.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e2507bc-e567-23f9-aeb9-f7529baa7032
* Version Independent ID: c42718d0-15b4-a87f-4353-e15656686889
* Content: [Introduction to Events](https://docs.microsoft.com/en-us/dotnet/csharp/events-overview)
* Content Source: [docs/csharp/events-overview.md](https://github.com/dotnet/docs/blob/master/docs/csharp/events-overview.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
I'd like @rpetrusha 's opinion on this one.

**Comment by rpetrusha** [comment]
Thanks for your feedback, @johnechiappetta. Since this is just a signature with no implementation, it's difficult to determine the intent of the event. But progress events are typically status events and therefore present tense events -- that is, they're intended to indicate what proportion of an operation has currently been completed. Given that, the use of Progress seems correct (though I have to confess that I see it didn't quite see it as a verb). 

It could be argued that a present participle ("Progressing") better conforms to the naming convention, though it seems to me that it does so at the expense of clarity. MadeProgress seems to also be less clear, as is MakingProgress. 

It's also true that event naming convensions seem to be violated more often than not. For example, In .NET, click events appear to be named both Click and Clicked to express the same basic kind of event,  even though the event is informational and therefore a past event. 

I do think, though, that the text becomes less confusing by remove the parenthetical reference to the example.

Thoughts?

**Comment by BillWagner** [comment]
Adding the "up for grabs" label.  I think the correct fix is in the previous comment:

> I do think, though, that the text becomes less confusing by remove the parenthetical reference to the example.
