### ISSUE TITLE
Misleading intro

### ISSUE THREAD

**Issue by Ponant** [dotnet/docs#9324]
The sentence "Microservices architecture often starts with the server-side handling data and logic. " is misleading and not necessarily true. A microservice architecture often has a a front end ui served by a server, e.g. .ASP.NET and sent to the client. I think the  first paragraph in this page implicitly hints that you are using a client-side framework such as Angular. This is why this paragraph could be improved, and probably extended. For instance one can say that UI composition can be made on the front-end server by gathering data from other services, or UI composition can be made on the client by ajax calls to the different microservices or via an api gateway. And then follow up with the pros and cons because the paragraph states it is better to do ui composition without explaining why.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 891b3701-b4d3-c4bf-713a-52d4be2106e2
* Version Independent ID: ee8f9fe1-dab0-6c01-ea47-0c37ce9ef1e1
* Content: [Creating composite UI based on microservices](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/architect-microservice-container-applications/microservice-based-composite-ui-shape-layout)
* Content Source: [docs/architecture/microservices/architect-microservice-container-applications/microservice-based-composite-ui-shape-layout.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/architect-microservice-container-applications/microservice-based-composite-ui-shape-layout.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mairaw** [comment]
Thanks for your feedback @Ponant. @CESARDELATORRE @mvelosop please take a look.

**Comment by mvelosop** [comment]
Hi @mairaw, @Ponant,

Actually, IMHO, I do think the first paragraph is appropriate and not misleading, just because the justification for a microservices architecture comes **mostly** from the back-end, considering issues like scalability and maintainability. However the **often** part just doesn't preclude any other consideration, it's just "most of the time".

As of technology, I just don't see any implication on Angular over Ajax or the other way around, that's why I think the paragraph is as neutral as can be.

As for "_... one can say that UI composition can be made on the front-end server by gathering data from other services..._" that's just what the second paragraph states in "_Of course, you could have an ASP.NET MVC service in between producing the HTML and JavaScript_", if I got it right. Besides, that's just the architecture of the MVC microservice that's detailed elsewhere in the guide.

However, perhaps @CESARDELATORRE's opinion here would help clarify.

**Comment by mairaw** [comment]
@nishanil can you comment here?

**Comment by CESARDELATORRE** [comment]
I think the sentence is basically right: It says: "Microservices architecture **often** starts with the server-side handling data and logic."

Usually most enterprises and developers start with the server side not with micro-front-ends. 

However, I think it can be slightly improved by saying that even when in many current cases enterprises are using microservices architectures for the backend services and have a monolithic UI, the next level or 'state of the art' microservices architecture also includes an UI driven by microservices which is also called "Micro-Frontends": 
https://micro-frontends.org/
https://martinfowler.com/articles/micro-frontends.html

We should also probably talk explicetely about the term 'MICRO-FRONTEND' which at the time of my original writing didn't exist, so I was talking about 'UI driven by microservices'.

Probably, the section's title should include the term "Micro-Frontend".

Hope it helps and thanks for the feedback! 👍
