### ISSUE TITLE
Table examples

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#9355]
@LMFSoft commented on [Sat Dec 01 2018](https://github.com/dotnet/docs.it-it/issues/55)

Please add more examples for &lt;list type="table"&gt;.

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 40ad53e4-4786-d1a1-5f8a-2a8b914ebb37
* Version Independent ID: df94f227-fd86-0fad-e5fe-d0053d9ed321
* Content: [&lt;list&gt; (Guida per programmatori C#)](https://docs.microsoft.com/it-it/dotnet/csharp/programming-guide/xmldoc/list)
* Content Source: [docs/csharp/programming-guide/xmldoc/list.md](https://github.com/dotnet/docs.it-it/blob/live/docs/csharp/programming-guide/xmldoc/list.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by KalleOlaviNiemitalo** [comment]
The [Sandcastle documentation for `<list>`](http://ewsoftware.github.io/XMLCommentsGuide/html/e433d846-db15-4ac8-a5f5-f3428609ae6c.htm) contains examples of two-column and four-column tables. However, [DocFX v2 always translates `<list type="table">` to a two-column HTML table](https://github.com/dotnet/docfx/blob/778444375710572e4ed734ca396e42642336e75e/src/Microsoft.DocAsCode.Metadata.ManagedReference.Common/Transform/TripleSlashCommentTransform.xsl#L146-L173). I think DocFX expects you to write the tables in Markdown overwrite files rather than in XML documentation comments.

**Comment by BillWagner** [comment]
reopening to address as part of the XML docs update.
