### ISSUE TITLE
C# Guide: Getting Started with Visual Studio 

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#943]
The getting-started-with-visual-studio topic (http://github.com/dotnet/docs/blob/master/docs/csharp/getting-started/with-visual-studio.md) index should contain:

o installation information for Visual Studio Community Edition (current version)
o Tour of the Visual C# Templates
o Create and run your first C# program.
o basic debugging with Visual Studio

At this time, the "current version" should be the public preview 4, as the next major release is Visual Studio 15.

**Comment by GuardRex** [comment]
How does https://github.com/dotnet/docs/pull/1679 fit into the picture? ... or has the direction changed? If so, should that PR be closed?

**Comment by BillWagner** [comment]
@GuardRex I don't think PR #1679 should be closed. There's a lot of good work there that improves the content we have. Maybe we move this topic into April, and start with the other sub-tasks in #942 first. Then, this can get merged, and it would be easier to move the parts focused on core to the getting started directory under core.

@mairaw what's your opinion?

**Comment by GuardRex** [comment]
We all see that there's a major challenge here: .NET Core, tooling, and language are somewhat strongly linked at a high level (i.e., the level of introductory docs). It's difficult to concentrate on one without muddying it up with the other two.

The sub-tasks look like bits of the Core tutorials, except for the difference that they'll have a better example than *Hello World!*, which is what we have in the [VS for macOS one](https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/using-on-mac-vs) ... *PLUS* ... with the debugging bits, such as from the bottom of the [2nd VS for macOS tutorial](https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/using-on-mac-vs-full-solution). I take it that your intention was to dup those bits somewhat ... I mean if one assumes the reader hasn't seen the tooling, then most of what's over there in those tutorials will end up over here just re-factored/combined differently.

WRT #1679: If that content is headed over to Core tutorials, then I'd prefer to just close the PR and move/merge it there directly in a new PR, primarily because there's refactoring to be done + there was a lot of file name/TOC churn on #1679. I think it will be smoother that way.

**Comment by rpetrusha** [comment]
There's still a major difference, though, between a C# tutorial that uses .NET Core and a .NET Core tutorial that uses C#. Assuming that the languages were supported, each of the existing C# tutorials, for example, could be converted to a VB or even a C++ tutorial without actually changing any text. (There may be some incidental text changes, but that's about all.) So the focus here is really, given knowledge of a language, how to you create a simple application in .NET Core.
What we also need is a tutorial that covers some basic language concepts (variables, variable scope, properties, methods, control structures, etc.) but just uses a simple .NET Core app as its backdrop. The focus here is on learning about C#, not learning about .NET Core.

**Comment by GuardRex** [comment]
> What we also need is a tutorial that covers some basic language concepts (variables, variable scope, properties, methods, control structures, etc.) but just uses a simple .NET Core app as its backdrop.

... which is what I think of when I think of a C# (or 'name your language') "getting started" doc. I was wondering why tooling would appear in the C# guide other than CLI commands and screenshots of console apps. I presume this has all been worked out by the team, so I just need to know if I should follow the sub-tasks as written. If so, I'm ready to get crank'in on them.

**Comment by GuardRex** [comment]
If #1679 is going in, can #1686 go in as well?

**Comment by mairaw** [comment]
I don't wanna lose the changes you made for those PRs but I haven't had time to review them yet. 😢 

For example. for the class library topic, do we want to show how to create .NET Core libraries or .NET Standard libraries and where would the topic live if it was the second choice?

The duplication was not a decision made, it just happened. That's why when I think of that macOS VS Code tutorial, I mostly see it as a CLI topic not a VS Code one and it's not specific to Mac.

**Comment by BillWagner** [comment]
Is this expanding into a project? It feels like this is expanding in scope.

In the fullness of time, we want great "getting started" content around the tools, the libraries and platforms, and the programming languages. The sample will be simple, and could be largely shared among the different topics. 

What's different is the main focus of the text: what the reader will learn from reading and following along. I'd also expect that we would liberally link between the different topics. 

With the two PRs in progress, were all agreed that we don't want to lose any of that work. Some of those should get merged reasonably soon, as it relates to the VS 2017 release.

**Comment by GuardRex** [comment]
We just chatted briefly about it. Yes, let's please get those two prior PR's merged first (or decide to close them and refactor the content for Core getting started/tutorials). They may not mostly affect this work, but they're in that section of the docs with TOC churn. I'd like to see what things look like when the dust settles wherever they land. That can't happen until next week at the soonest.

For 942 and sub-tasks, I have questions about the organization and content. I'm just about out of time to get anything done this week, but I'll definitely read everything carefully this weekend and come back with focused questions on the bits that I don't understand. I'll put those on the parent 942 issue ... prob Monday morning.

**Comment by BillWagner** [comment]
Closing this.

It doesn't fit the new organization of the C# guide, the two PRs that are part of the discussion have been merged.
