### ISSUE TITLE
Code Quality Sub Par

### ISSUE THREAD

**Issue by jwbats** [dotnet/docs#9477]
The email validation code quality is sub par. There are return statements strewn all throughout the code. The methods IsValidEmail() and DomainMapper() are both modifying a single private variable. They kind of have to, because DomainMapper() is passed as a function to Regex.Replace().

I was looking for some ready-made email validation, but I'm not about to copypaste this into my project. If I do, then that means I'll have to maintain it. I tried to refactor it, but it's too much effort already. This is one can of worms I'm not about to open up.

Microsoft needs to realize that some people will use this in production code. And this is what creates a world of messy, unmaintainable code, which in turn leads to failed projects.

You guys need to start setting better examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 202e3f9f-a12a-53de-9069-fd469e3dbebc
* Version Independent ID: fd3699bb-4881-b6b4-1275-43eed3d5f626
* Content: [How to: Verify that Strings Are in Valid Email Format](https://docs.microsoft.com/en-us/dotnet/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format)
* Content Source: [docs/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
Hi! Thanks for the feedback. I agree with you. This could should be tightened up and redesigned perhaps using more modern C# approaches that eliminate the need for that extra variable and make it more portable. 

As you can see from the other comments, this article has been talked about a lot. The point of the article is to teach about RegEx and not necessarily about parsing email addresses. Although, since this is an example of that, it should do it well and clean.

Again, thank you for the feedback. I feel like changing this would be a fun diversion for me, unless you wanted to do it yourself. This code is taken from a snippet located here: 

https://github.com/dotnet/samples/blob/master/snippets/csharp/VS_Snippets_CLR/RegularExpressions.Examples.Email/cs/example4.cs

**Comment by Thraka** [comment]
@jwbats Hi! Would you like to review the code change? https://github.com/dotnet/samples/pull/504
