### ISSUE TITLE
C# Tutorial: Using Visual Studio to create, debug, and deploy applications.

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#948]
This issue tracks content for https://github.com/dotnet/core-docs/docs/csharp/tutorials/create-debug-deploy.md

This topic should cover an end to end scenario using C# and Visual Studio to create an application, learn the basics of the Visual Studio debugger to fix problems, and deploying the final application (likely in Azure).  

This tutorial should include a full sample that developers can follow along with as work through the tutorial.

**Comment by rpetrusha** [comment]
This issue is addressed with the set of topics at [Building a C# Hello World Application with .NET Core in Visual Studio 2015](https://docs.microsoft.com/en-us/dotnet/articles/csharp/getting-started/with-visual-studio) and [Building a C# Hello World application with .NET Core in Visual Studio 2017 RC](https://docs.microsoft.com/en-us/dotnet/articles/csharp/getting-started/with-visual-studio-2017).
