### ISSUE TITLE
What is the different bitween nuget package and nuget tool?

### ISSUE THREAD

**Issue by baruchiro** [dotnet/docs#9598]
If both are a nuget, so every tool is also can be imported as nuget?

I have a library I want to publish as nuget, and I want to publish a tool that uses this nuget. What should I do?
Create two projects in one solution, one project for nuget and one project for the tool?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ffe064a-2c6e-284f-7706-528d1c861de3
* Version Independent ID: 7ff2fe61-8884-694d-db38-3e2cc292fe61
* Content: [How to create a .NET Core Global Tool - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create)
* Content Source: [docs/core/tools/global-tools-how-to-create.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/global-tools-how-to-create.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment]
@baruchiro Hi!

Your tool project would reference the NuGet package that contains the library you're using. When you then build the NuGet package for the tool, it will know the dependency on the other NuGet package and when you install the tool, the install system will automatically pull down the dependency NuGet package along with the tool NuGet package.

This is **if** you want to have your library distributed that way. Otherwise, you can just have your tool project reference the other code project and when it builds the NuGet package for the tool, it would just include the compiled library DLL in the tool package for you.

Let me know if that answers your question or not.

**Comment by baruchiro** [comment]
I think you answer the question.

But just for validating- the best practice for publishing both library and tool is to separate them, and let the tool to use the nuget?
