### ISSUE TITLE
How do you know which access modifier to use?

### ISSUE THREAD

**Issue by coreys079** [dotnet/docs#9609]
I am struggling with this as to which access modifier to use for each class. Can anyone possibly explain this to me?

**Comment by Thraka** [comment]
@coreys079 Hi! 

It depends on what your intent for the class is. Are you making a library for others to use? You'll probably be making a lot of  `public` classes then. In the library, are there things you need to hide from outside users but you will be using throughout the library for yourself? Then `internal` is what you want.

You can review the modifiers here: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/access-modifiers

Since this issue isn't related to a specific documentation article, I'm going to closet it. Hopefully some of the documentation in the link will help you understand it better. You can also explore some of the q & a articles related to this on Stack Overflow: https://stackoverflow.com/search?q=access+modifiers+c%23

**Comment by coreys079** [comment]
I have one more question if I may ask? In Web Api Under;
Public class WebApplication2Controller : ApiController

Is there a default code configuration that goes under it, because different examples I have seen looks different, and some use valuecontrollers. Does it depend on the project your doing?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Thraka** [comment]
I don't know, you would be better off asking in that forum or stack overflow area, or even reading up on the ApiController documentation.
