### ISSUE TITLE
It's not clear whether == and != operators use ordinal comparison

### ISSUE THREAD

**Issue by Neme12** [dotnet/docs#9619]
The "Default ordinal comparisons" section makes it clear that string.Equals uses an ordinal comparison, but there's no information about what the behavior of C#'s builtin == and != operators is. Do they use ordinal comparison too?

The only time the operators are mentioned is here:
> Avoid using the == and != operators when you test for equality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11ecfc18-477b-f792-4136-2feb46bbc5d3
* Version Independent ID: 82f53ae8-a9d4-dea9-5acd-6d9202a40882
* Content: [How to: Compare strings - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/how-to/compare-strings)
* Content Source: [docs/csharp/how-to/compare-strings.md](https://github.com/dotnet/docs/blob/master/docs/csharp/how-to/compare-strings.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@Neme12 the "Default ordinal comparisons" mentions that the [equality operator](https://docs.microsoft.com/en-us/dotnet/api/system.string.op_equality?view=netframework-4.7.2) uses ordinal comparison. Though, it doesn't name it "== operator", but "String.Equality". Do you think it should be stated in a clearer way.

By the way, the updated article of the `==` operator is synced with this how-to article. Not yet live, that's why the link to the repo md file:
https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/equality-comparison-operator.md

**Comment by Neme12** [comment]
I see, sorry. It didn't occur to me that `Equality` was actually the operator, so my mind just skipped that when reading, assuming it's some other method I don't know and don't care about.

**Comment by BillWagner** [comment]
cc @dend @joelmartinez for the most recent comment.
