### ISSUE TITLE
C# Guide: Structs

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#966]
This issue tracks the topic for https://github.com/dotnet/docs/blob/master/docs/csharp/structs.md

Much of the content can be taken from here: https://msdn.microsoft.com/en-us/library/ms173109.aspx

edit: @mairaw updated the link to the first topic

**Comment by mairaw** [comment]
With the content ported from MSDN, it seems that we now have duplication of struct topics @BillWagner:

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/structs
https://docs.microsoft.com/en-us/dotnet/csharp/structs

The first one gets way more views (probably because of the keywords used in the title and the link juice obtained from msdn redirection).

**Comment by rpetrusha** [comment]
@BillWagner, @mairaw, they have identical titles, but very different content. The second struct topic is probably mistitled; it's more about value types than structs proper. If there's anything in the second topic that can be consolidated into the first topic, we should do that, and probably find a home for whatever remaining content doesn't belong in the structs topic.

**Comment by BillWagner** [comment]
closing as stale.  While this will be covered, it doesn't match the new TOC structure.
