### ISSUE TITLE
How to install dotnet core runtime on many remote machines? 

### ISSUE THREAD

**Issue by amirgra** [dotnet/docs#9699]
How to install dotnet core runtime on many remote machines? 
With PowerShell remoting I tried downloading the installer and run it but it didn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff5c1c2a-7d86-703c-038e-062f5dcfc5b0
* Version Independent ID: cab4f67f-f338-8990-6454-853a0f01627e
* Content: [Prerequisites for .NET Core on Windows](https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x)
* Content Source: [docs/core/windows-prerequisites.md](https://github.com/dotnet/docs/blob/master/docs/core/windows-prerequisites.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@leecow @richlander can you help with this question? Is this something we need to cover in the docs?

**Comment by Thraka** [comment]
Closing this due to lack of response. Also, considering that you can deploy .NET Core via a zip file and ensuring the prerequisites are installed, there shouldn't be a problem remotely deploying it. If there is a specific problem installing via PowerShell, please share the specific details. You may also find help on StackOverflow.

**Comment by reframalo** [comment]
I have a similar problem. We're getting the first experiences with windows server core, which has no ui. When installing the dotnet hosting environment, it hangs up, propably due to a request to the user. If I try the same on common windows server it does the installation, but pops up with a warning to restart IIS. Are there any parameters for installer to avoid the popup?

**Comment by Thraka** [comment]
@reframalo I ran the installer with the `-?` parameter and was shown this:

![image](https://user-images.githubusercontent.com/2672110/62072358-543d8d00-b1f3-11e9-8cdc-81cdc1ca80f4.png)

So I think that you can run something like this `dotnet-hosting-2.2.6-win.exe /install /quiet` to get it to be a silent install.

**Comment by Beeg-Yoshi** [comment]
> 

This works amazingly, thank you!
