### ISSUE TITLE
Windows Installer option appears to be depreciated

### ISSUE THREAD

**Issue by casterle** [dotnet/docs#9702]
The linked page contains a "product lifecycle" warning at the top. Is this solution going away, or can you point to a more recent page on the topic?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdf77b0f-5062-0a1a-c172-821d24a378a4
* Version Independent ID: f67b80a0-9126-40c8-a8c7-c6a5c6efdff5
* Content: [Deploying a WPF Application (WPF)](https://docs.microsoft.com/en-us/dotnet/framework/wpf/app-development/deploying-a-wpf-application-wpf)
* Content Source: [docs/framework/wpf/app-development/deploying-a-wpf-application-wpf.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/app-development/deploying-a-wpf-application-wpf.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @casterle. I imagine you're talking about the Windows Installer Deployment link, correct?

I almost feel like we should remove this topic and link to https://docs.microsoft.com/en-us/visualstudio/deployment/deploying-applications-services-and-components since this topic is very outdated. 

Thoughts @OliaG @gewarren @Mikejo5000?

**Comment by OliaG** [comment]
Agree. The new link looks much better. We need to explicitly add WinForms and WPF words. Also we might want to point out what is available in Framework and in Core.

**Comment by mairaw** [comment]
I'm moving this to the backlog. @Thraka I think would be good to take a look at the deployment story for desktop as whole along with the VS docs team (/cc @gewarren)
