### ISSUE TITLE
Not clear what the default mode for Server GC is

### ISSUE THREAD

**Issue by changov** [dotnet/docs#9739]
.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fcebd46-8a64-9531-f6e1-3a330b61bb0f
* Version Independent ID: 7538a252-8fa8-4615-92df-f1c6d7d6a3e4
* Content: [Latency Modes](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/latency)
* Content Source: [docs/standard/garbage-collection/latency.md](https://github.com/dotnet/docs/blob/master/docs/standard/garbage-collection/latency.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thank you for your feedback, @changov. I apologize for the belated response. Workstation GC is the default, as reflected in the [Fundamentals of garbage collection](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/fundamentals)  and [\<gcServer> element](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/gcserver-element) articles. Since I don't believe that a discussion of whether workstation or server mode is the default is appropriate for this article, I'll close this issue.

**Comment by changov** [comment]
The documentation page is about GCLatencyMode, and my comment is about that: what is the default when Server GC mode is used?

**Comment by rpetrusha** [comment]
Sorry, @changov. I'd completely misunderstood your question. @Maoni0, what are the default latency modes for server and workstation GC?

**Comment by Maoni0** [comment]
default (as in, you are running a standalone exe that's not hosted) for both Server and Workstation GC is always Interactive.

**Comment by rpetrusha** [comment]
Thanks, @changov, for opening the issue, and @Maoni0 for responding. I'll revise the documentation during the next sprint.
