### ISSUE TITLE
Missing VB samples should fall back to C#, not C++

### ISSUE THREAD

**Issue by ocdtrekkie** [dotnet/docs#9757]
**Issue description**

So I was looking at a sample of the System.Net.Mail.Attachment class (I previously discovered this hole in the VB samples here: https://github.com/dotnet/docs/issues/6129#issuecomment-401176644), and with my docs view set to VB, I found it extremely odd I was looking at C++ code, rather than at the very least, C# code, which I am more likely to expect. From issues like #8555, you can also see, in the lack of a VB sample, the docs site shows C++.

When failing to find a VB sample for a given snippet, Docs should really show C# because it's more similar syntax.

**Comment by mairaw** [comment]
Thanks for your feedback @ocdtrekkie. Yes, I agree with you that if VB is missing, the default language should be C#. This feedback is already captured on the following issue:
https://github.com/MicrosoftDocs/feedback/issues/927

As far as helping us port the samples to VB, your contribution would be super valuable and we'd welcome your PR. Probably best to do the whole file at once since we usually try to keep the languages with parity. So it would be strange to have a VB version that doesn't match the C# version of the file.
