### ISSUE TITLE
Volume GUID path format?

### ISSUE THREAD

**Issue by glenn-slayden** [dotnet/docs#9803]
Only because this page is so comprehensive, I should mention the **_one_** file system path naming format which is **_not_** mentioned, namely the so-called **volume GUID** syntax, which looks like this: (e.g.)

<pre>\\?\Volume{30d23498-b8e0-42cb-912d-851eb0fffc7b}\</pre>

As with other types of paths, additional path specification(s) can be appended to further navigate to some directory or file on the specified volume:

<pre>\\?\Volume{30d23498-b8e0-42cb-912d-851eb0fffc7b}\path\to\file\or\directory</pre>

GUID paths like this are especially great when persisted as long-term references because they are immune from breakage (continue to work properly) when volume drive letters (C:, D:) are subject to change.

See https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-volume. As you surely know, there's also some lesser-related information here https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b74b99ff-32f8-c2d1-0a62-5907985f591e
* Version Independent ID: 716a28dc-360e-2964-47f5-0ff18bb00b1c
* Content: [File path formats on Windows systems](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats)
* Content Source: [docs/standard/io/file-path-formats.md](https://github.com/dotnet/docs/blob/master/docs/standard/io/file-path-formats.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
@JeremyKuhne, can you comment on this PR?

**Comment by glenn-slayden** [comment]
[edited original issue for further clarity]

**Comment by JeremyKuhne** [comment]
I think it is useful to call out that these are supported now.

**Comment by glenn-slayden** [comment]
@JeremyKuhne  Haven't they always been?

**Comment by JeremyKuhne** [comment]
> @JeremyKuhne Haven't they always been?

Not in .NET. I changed 4.6.2 to allow device path syntax (`\\?\`, `\\.\`). I also made sure .NET Core supported these style paths from the start.

**Comment by rpetrusha** [comment]
@glenn-slayden and @JeremyKuhne, I've added this as a work item in an upcoming sprint.

**Comment by glenn-slayden** [comment]
> I changed 4.6.2 to allow device path syntax (`\\?\`, `\\.\`)...

@JeremyKuhne Yes, and indeed the so-called"device path" prefixes are already mentioned in a [subsection](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#dos-device-paths) of the docs page that this issue is complaining about. What's _not_ mentioned on that page is the use of ***volume GUIDs*** under that umbrella.

To be fair, you could argue that enumerating the particular subtypes of device path prefix is not really a .NET topic, once .NET supports such prefixes in general overall. That's why I originally introduced this issue by saying...

> Only because this page is so comprehensive...

**Comment by JeremyKuhne** [comment]
@glenn-slayden To be clear, I'm not suggesting that we don't document them, quite the contrary. I _want_ it to be called out. It is one of the _many_ reasons I pushed support for device paths through in 4.6.2.

You asked me if volume guids were always supported, and the answer is no.

Yes, for .NET you can infer this by the fact that we wouldn't allow `\\?\` as documented. To be super pedantic, `\\.\` was allowed in some cases, but not all. You can, for example, list files with the volume guid format. You can't, however, open a file stream this way as it is explicitly [blocked](https://referencesource.microsoft.com/#mscorlib/system/io/filestream.cs,728). Rather than get into another crazy level of detail and forcing someone to dig into the full history of this code we're documenting the device path format as not supported until 4.6.2. (There may be even more caveats with `\\.\` prior to 4.5- I haven't looked. Path code is a bit wonky for a lot of reasons, the key ones being that .NET originally supported Windows 98 / NT 4.0 and a lack of understanding of how paths actually work in NT.)

For Windows itself I believe this concept (guid volume identifiers) was introduced in Windows XP, but I'm not 100% on that. The relevant APIs didn't exist before then.

**Comment by glenn-slayden** [comment]
@JeremyKuhne  Well let's hope we can figure out a way to mention volume GUIDs in the doc page without getting too much into the weeds. Thanks.

**Comment by JeremyKuhne** [comment]
@glenn-slayden I think we're capable of being pretty succinct for this. Thanks for your feedback on this issue.

**Comment by glenn-slayden** [comment]
Thanks all.
