### ISSUE TITLE
Review links to MSDN blogs

### ISSUE THREAD

**Issue by priyanka-gomatam** [dotnet/docs#9807]
Resolving file references in team build link does not exist. Please update to a working link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0067cc97-4a34-364c-ff91-7864bca5c3e1
* Version Independent ID: 902901c2-f8b6-c58c-c2e8-f93aab2487c9
* Content: [Compiler Error CS0246](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0246)
* Content Source: [docs/csharp/language-reference/compiler-messages/cs0246.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-messages/cs0246.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Assigning P1 because this is one example of a much larger issue where we have links to MSDN blogs that have been removed.

To fix this, we should remove all those links that are failing.

**Comment by mairaw** [comment]
Created an internal work item for this issue for our vendor team: https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1436790

**Comment by mairaw** [comment]
Status update: I changed the title of this issue to be a bit less specific to this page since we'll review all blog links. We're starting the updates with the ones already migrated to the new blog platform. Some links that are currently broken might be redirected somewhere in the next couple of weeks, so we'll wait and see before we remove them.
