### ISSUE TITLE
Example uses the obsolete parameter. Please change it to the supported parameter.

### ISSUE THREAD

**Issue by jackbond** [dotnet/docs#9935]
So you say SharedRuntime is obsolete, but then in the Examples section you provide an example for the obsolete flag, but not its replacement???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d
* Version Independent ID: 5bc7caa5-f1c2-d7d5-fe02-80c65cca9672
* Content: [dotnet-install scripts - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)
* Content Source: [docs/core/tools/dotnet-install-script.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-install-script.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
@jackbond Looks like the note got added at some point but the example was forgotten. If you would like, you can submit an edit for this but clicking the Edit button at the top of the article. I'll add this bug to the community project and see if someone wants to fix it.

Thanks for reporting it. I'm editing the title of your bug so that anyone looking at it understands the issue without at first glance.

**Comment by Kubik2000** [comment]
@Thraka @jackbond hey I will take this one
