### ISSUE TITLE
Text could be clearer and more consistent

### ISSUE THREAD

**Issue by JacquesValois** [dotnet/docs#9959]
sbyte: 8 bits, range from -128 - 127
short: 16 bits, range from -32,768 - 32,767
int : 32 bits, range from -2,147,483,648 - 2,147,483,647
long : 64 bits, range from –9,223,372,036,854,775,808 to 9,223,372,036,854,775,807

I am assuming that sbyte: 8 bits, range from -128 - 127 is stands for -128 to +127 as for long : 64 bits. Using the "-"  seperator for value ranges is not clear but still understandable. For consistency and clarity, they should all be stated as the "long : 64 bits, range from" with the from and to words.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9770af4-de82-7034-a56b-c68a6b5c55e5
* Version Independent ID: 6bd64fcc-5c84-e541-12f4-0cdcfe4f5dd2
* Content: [C# Types and Variables - A tour of the C# language](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/types-and-variables)
* Content Source: [docs/csharp/tour-of-csharp/types-and-variables.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tour-of-csharp/types-and-variables.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
I agree that it would be better the way you suggest. Do you want to submit a Pull Request with those changes? If you do and don't know how, you can follow [this guide](https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents).

I also noticed that the `long` line incorrectly uses the en dash character instead of minus. I think that should be fixed too.
